### ISSUE TITLE
Handle 'comb' Formatting for Form Fields

### ISSUE THREAD

**Issue by mdmcconnell** [pdfcpu/pdfcpu#1001]
The PDF file format specification provides for form fields to have an associated set of "field flags".  In the case of text fields, bit 25 signifies the field's appearance should use 'comb' spacing, that "[Spreads the user-entered text evenly across the width of the text field. If a border color is specified in the Appearance tab, each character entered in the field is separated by lines of that color.](https://helpx.adobe.com/uk/acrobat/using/pdf-form-field-properties.html)"  The attached form contains several such fields.  Here is one that has been filled in Acrobat Reader:

![image](https://github.com/user-attachments/assets/dc91df94-06cf-4a5e-8d7e-59b378489f9b)

Here is the outcome using pdfcpu:

![image](https://github.com/user-attachments/assets/2b742b0d-b010-4e39-8ebb-08243c6f28a3)

Examining the appearance streams data, it seems that pdfcpu "carries" the 'comb' appearance stream from the original file into the filled file, but does not assign that stream to relevant fields.  pdfcpu also changes or ignores other appearance aspects (font, bolding, justification) of text fields, versus what is specified in the original file.

**Comment by hhrutter** [comment]
This should be fixed with the latest commit!
Let me know..

**Comment by mdmcconnell** [comment]
Fantastic!  Yes, it is working, this is a great help:
![image](https://github.com/user-attachments/assets/f8e82d2b-83ee-417d-ba46-5dd4f57dcd7d)
I think other appearance information of the form field is still disregarded.
