### ISSUE TITLE
Positioned stamping

### ISSUE THREAD

**Issue by gbenroscience** [pdfcpu/pdfcpu#101]
Apologies @hhrutter . Thanks for this amazing library! I was going to ask for a feature! After working overnight though, I came up with a hack that works well with my scenario.

Please see #62  

I want to position an image stamp on a page with pdfcpu. But as I later saw on another issue, the positioning feature is not yet available for the stamping feature

So, would it be okay to suggest the following as an hack for lovers of your beautiful library?

1. Determine the dimensions of the pdf paper(page)
2. Create a transparent image whose dimensions equal the one calculated in step 1
3. Load image stamp and render using golang's draw methods on the transparent image above while respecting the position specified by the user in the rendering.

4. Save this image and note the path to the saved file.
5. Apply this image via pdfcpu's stamp.go to your pdf.

I implemented this overnight and it works wonderfully and saved me from paying for Unidoc's pdf library.

Question is, is it too hacky to be included in pdfcpu?

If not, I would love to contribute it to pdfcpu.

Thanks for this library once again.

**Comment by hhrutter** [comment]
Hello!
Is this a bug report or a feature request?
Please provide more information.

**Comment by gbenroscience** [comment]
Also,  is there a way to get the pdf paper dimensions with pdfcpu? I am currently using another library to compute the page size

**Comment by gbenroscience** [comment]
A couple of optimisations could be added to the hacky steps above if you feel it is okay to use though.

Steps involving needless io operations can be eliminated by allowing the initial step which fetches the image to feed it directly to the pdfcpu#ParseWatermarkDetails function.

And if possible, pdfcpu should be able to return the page's dimensions instead of us resorting to another library; which has the extra overhead of having to load the file again from the file system

**Comment by hhrutter** [comment]
Hi there!

Importing/converting an image to pdf already has a positioning feature.
See here: http://pdfcpu.io/generate/import

My plan is to provide positioning in the same way to stamping/watermarking.
Basically you choose an anchor and then add an offset that may be positive or negative.
Would that work for you?

**Comment by gbenroscience** [comment]
Great then! I would look forward to seeing the same thing done to stamping/watermarking!

Thanks

**Comment by olekukonko** [comment]
@gbenroscience were you able to resolve this?

**Comment by gbenroscience** [comment]
@olekukonko, Yes! I was able to follow the exact steps listed above and  solve the positioning problem It definitely works. Only issue now is that pdfcpu wont allow the stamping of an already stamped document; else the technique would have been easily extensible to that scenario also.

**Comment by gbenroscience** [comment]
I was able to bypass this by using `png` of the same paper size, positioning the stamp on the `png` before applying it to the document.

**Comment by gbenroscience** [comment]
Hello @hhrutter, I am currently checking out the positioning enhancement. How do I specify positioning for the stamp?

**Comment by olekukonko** [comment]
@gbenroscience you need to just set "position:pos" and "offset :off" see https://pdfcpu.io/core/watermark configuration, it has been updated
