### ISSUE TITLE
Parsing error if page rotation is float with all-zero fraction

### ISSUE THREAD

**Issue by fancycode** [pdfcpu/pdfcpu#1018]
### Thank you for submitting a possible bug!

Please ensure the following:

* Your issue is based on the latest commit

ff51203026d797e891c145229251bd53cf5307dd

* State your OS and OS version

Ubuntu Linux 20.04

* When reporting a problem with a specific PDF input file please avoid stating the organization responsible for the PDFWriter - just refer to the *PDFWriter*

Page resources are stored with dictionaries like this:
```
<<
  /Resources <<
    /XObject <<
      /F 111 0 R
      /FFT0 222 0 R
    >>
  >>
  /MediaBox[ 0 0 2400 3400]
  /Type /Page
  /Parent 333 0 R
  /Contents 444 0 R
  /Rotate 90.0
  /CropBox [ 0 0 2400 3400]
>>
```

During parsing, the `/Rotate` entry is read as integer:
https://github.com/pdfcpu/pdfcpu/blob/ff51203026d797e891c145229251bd53cf5307dd/pkg/pdfcpu/model/xreftable.go#L1713-L1714

This is according to the standard which defines the value as `integer`, however there seem to be some writers that store the value as floating point number with an all-zero fractional part.

The `integer` datatype is defined as "An integer **SHALL** be written as one or more decimal digits optionally preceded by a sign." (emphasis mine), so imho it should be fine to also support cases like the above and reject all values that have a non-zero fractional component.

**Comment by hhrutter** [comment]
Thanks for reporting this.

Please no details about the PDFWriter.

**Comment by hhrutter** [comment]
Thanks for reporting this!

**Comment by fancycode** [comment]
> Please no details about the PDFWriter as part of the issue.

I assumed you wanted to have a reference about which PDF writers might create such files to later understand why a change was introduced (and it's asked in the issue template).

But if it's not necessary I can omit this information in future reports.

**Comment by hhrutter** [comment]
Hi Joachim!

No - to the contrary.

If you need to refer to whoever produced a file in question then please just write "the PDFWriter did t".
This is in order to avoid shaming in any direction in case of a PDF spec violations.
I can always check the info dict myself.

**Comment by fancycode** [comment]
Understood. However as I am not allowed to share the files in most of my reports, I thought it would be good to at least reference the writer - not to shame but for reference.
