### ISSUE TITLE
Getting fontDescriptor error on ValidationNone

### ISSUE THREAD

**Issue by lgonzalez-silen** [pdfcpu/pdfcpu#102]
I'm hitting the error at this line on a pdf (with confidential info) I'm trying to merge:

https://github.com/pdfcpu/pdfcpu/blob/f49dee971bb0531b194a6df61bde9be811fe9139/pkg/pdfcpu/optimize.go#L922

`fontDescriptor: FontDescriptor dict incorrect dict type for font object 335`

I'm running it with ValidationNone in the config.

Shouldn't ValidationNone allow this check to be omitted?

If I comment out that error, the file seems to merge correctly.

**Comment by lgonzalez-silen** [comment]
For reference, I set a breakpoint to see what the object looked like when it broke (expecting Type FontDescriptor):

![FontDescriptorTableReference](https://user-images.githubusercontent.com/2609368/63197852-eabcdb80-c046-11e9-947a-0a5bf72fc3af.png)

![TableObject](https://user-images.githubusercontent.com/2609368/63197860-ef818f80-c046-11e9-8619-441b3055b7f5.png)

**Comment by hhrutter** [comment]
Generally the optimization step assumes a validated file.
The ValidationNone shortcut is really only for usecases that deal with PDFs where
the PDFWriter used to create these originally is known to produce PDFs of consistent and valid nature. In an environment where I have to deal with PDFs of unknown origin I would be hesitant to turn off validation.

**Comment by lgonzalez-silen** [comment]
Ok, I'll see if I can edit the pdf to remove confidential info and still make it fail.

Would love to not have to use ValidationNone. Wondering if optimization is a necessary step for the merge? It's definitely nice, but PDFs that fail to validate merge properly then what's the harm in allowing it?

For more context, the two PDFs I've noticed in our corpus failing validation were both modified by iTextSharp (the first with the FontDescriptor pointing to a Font Type, the second one with a UTF16 string that has an uneven number of bytes):

`PDFKit.NET 19.2.101.10850; modified using iTextSharp™ 5.5.13-SNAPSHOT ©2000-2017 iText Group NV (DocuSign, Inc.; licensed version)`

`Designer 6.2; modified using iTextSharp™ 5.5.13-SNAPSHOT ©2000-2017 iText Group NV (DocuSign, Inc.; licensed version)`

**Comment by hhrutter** [comment]
Again, you would not have run into an error during optimization with validation on.
With validation turned off you are risking errors during processing due to the PDF  being invalid regardless whether the operation seems to work or not. 

It's actually more common than one likes to see that well known PDF Writers produce PDFs that don't comply with the PDF spec. My approach has been, if Adobe Reader and other well known readers open it then pdfcpu should  also not cause any problem and in these cases I extend relaxed validation after identifying the root of a particular validation error. This smells very much smth like it.

**Comment by lgonzalez-silen** [comment]
Makes sense. Both the PDFs I'm running into errors with can be opened by Reader, Preview, etc. I will still try to get you specific examples that reproduce the issue.

**Comment by lgonzalez-silen** [comment]
Thanks for fixing this one too! This change gets past the error I had before, but now it stops at

https://github.com/pdfcpu/pdfcpu/blob/c336114e656a567454f968bf2f58908c40c94674/pkg/pdfcpu/validate/font.go#L122

with `"pdfcpu: validateFontDescriptor: corrupt font descriptor dict"`

I will email you the output of `pdfcpu val -vv`

This is a screenshot of the `d` at that point:

![Screen Shot 2020-07-09 at 10 58 25 AM](https://user-images.githubusercontent.com/2609368/87056119-2e768180-c1d3-11ea-8282-14ef94a04b27.png)

Let me know if you'd like me to open a new issue.

**Comment by hhrutter** [comment]
This should be fixed with [e408740](https://github.com/pdfcpu/pdfcpu/commit/e408740d07ed18959e45380a20acd05c3b75e800).
If not please do file a separate issue.
