### ISSUE TITLE
nil pointer dereference if page tree node has no "Type"

### ISSUE THREAD

**Issue by fancycode** [pdfcpu/pdfcpu#1020]
### Thank you for submitting a possible bug!

Please ensure the following:

* Your issue is based on the latest commit

ff51203026d797e891c145229251bd53cf5307dd

* State your OS and OS version

Ubuntu Linux 20.04

* When reporting a problem with a specific PDF input file please avoid stating the organization responsible for the PDFWriter - just refer to the *PDFWriter*

Most of the pages nodes have no `Type` entry, causing a nil-pointer deference here:
https://github.com/pdfcpu/pdfcpu/blob/ff51203026d797e891c145229251bd53cf5307dd/pkg/pdfcpu/model/xreftable.go#L1916

I suggest updating the node type to `Pages` if it has `Count` and `Kids` (this fixes the crash.

**Comment by hhrutter** [comment]
Thanks for reporting this!

**Comment by fancycode** [comment]
> Page dicts w/o _Type_ are not PDF spec compliant.

I know, however it would be good if pdfcpu could still parse them (just as other PDF readers / libraries do).

**Comment by fancycode** [comment]
Also if you really want to adhere to the standard strictly, it still would be better to return a proper error object instead of crashing with a nil pointer dereference.

But as pdfcpu might be used on the server side for PDF processing, supporting most of the (almost) valid PDFs that users might send should be (at least imho) preferred.

**Comment by fancycode** [comment]
Sure, I can look into checking the `ValidationMode` in #1021

**Comment by fancycode** [comment]
> Sure, I can look into checking the `ValidationMode` in #1021

Done. Nodes with missing `Type` are ignored in strict validation just as unknown types were before (and still are).
