### ISSUE TITLE
Deployed API Issue - `config problem: mkdir /home/api: permission denied` 

### ISSUE THREAD

**Issue by DakshChhokra** [pdfcpu/pdfcpu#1032]
# Issue

When trying to use pdfcpu as a package in a go-api it works as expected locally(Mac OS 14.7.1) but when deployed to an Amazon Linux Instance fails with `pdfcpu: config problem: mkdir /home/api: permission denied`. 

My deployed instance is running on `Amazon Linux 2023 version 2023.6.20241010`. The pdfcpu package version is `pdfcpu v0.9.1`

# PDFCPU Code in the API

I only use this package in one place with the following code to stamp one pdf on top of another

```go
desc := "scalef:1 rel, rot:0"
if err := api.AddPDFWatermarksFile(baseFileName, outputFileName, nil, true, stampFileName, desc, nil); err != nil {
  return fmt.Errorf("failed to stamp PDF: %w", err)
}
```

As mentioned above I only see the issue on a deployed instance and not when running this locally. 

# Question

Is there a way to prevent the package from creating a dir for config files? Can I somehow bypass this step?

**Comment by DakshChhokra** [comment]
My project did not need fonts so I just ended up using `api.DisableConfigDir()`

**Comment by hhrutter** [comment]
see also #528
