### ISSUE TITLE
Paper Size Information Not available

### ISSUE THREAD

**Issue by gbenroscience** [pdfcpu/pdfcpu#104]
I would like to know how to get the paper size(I mean the page size) information for a PDF page.

Thanks!

**Comment by hhrutter** [comment]
Do you mean in a Go backend or on the command line.

We can extend `pdfcpu info` to output the paper size for homogenous files, meaning for PDF files with consistent page sizes.

**Comment by gbenroscience** [comment]
Hi @hhrutter! Thanks for responding! My use case is in a Go backend. 

I am currently outputting it using another pdf library which makes the process unwieldy and adds extra dependencies.
It would be nice to be able to do everything within pdfcpu.

Thanks again

**Comment by olekukonko** [comment]
@gbenroscience I want to agree with you, however `PDF files with consistent page sizes.` is another issue raised by @hhrutter 

Here is what I think are the possibilities

- Return  ` page sizes` in info
- ` page sizes`  can also be `[]string` for PDF files with multiple sizes 

However, this can also have a limitation if you are doing certain modifications on each page wich id dependent on paper size hence 

- ` page sizes` can be `map[int]string` where `int` is the `page number` and `string` is the `page size`
-  this is still been retrieved by `info` and not adding any other function or complexity anywhere else 


@hhrutter thanks for the wonderful and excellent work you have done here.

**Comment by hhrutter** [comment]
the api command for this using Reader will make it into the nexrt release.
Thanks for using pdfcpu! 💚

**Comment by olekukonko** [comment]
Hello, @hhrutter, I think `func PageDims(inFile string) ` needs to be consistent with other APIs. you don't want to make extra `io` because of page information 

```go
func AddAttachments(rs io.ReadSeeker, w io.Writer, files []string, conf *pdf.Configuration) error
func AddAttachmentsFile(inFile, outFile string, files []string, conf *pdf.Configuration) (err error)

func ExtractMetadata(rs io.ReadSeeker, outDir string, selectedPages []string, conf *pdf.Configuration) error
func ExtractMetadataFile(inFile, outDir string, selectedPages []string, conf *pdf.Configuration) error


```

#### Proposal 

```go
func PageDims(rs io.ReadSeeker) 
func PageDimsFile(inFile string) 
```

Regards
Oleku

**Comment by gbenroscience** [comment]
@hhrutter, I think I agree with @olekukonko on this. My scenario can do without the overhead of extra io calls.

**Comment by hhrutter** [comment]
The documentation is not clear on this but in the api there are 2 call layers:

1) a low level layer based on io.ReadSeeker, and io.Writer
2) a file based layer on top of it

As I said above layer 2 is still missing and will make it into the next release:
func PageDims(rs io.ReadSeeker, conf *pdf.Configuration)

Pretty much what @olekukonko  suggested.

Thanks for the feedback!

**Comment by olekukonko** [comment]
@hhrutter I should be the one saying thank you for the prompt response.  Be rest assure i would be one of the first to help tes this out.

**Comment by hhrutter** [comment]
fixed with v.0.2.5

**Comment by olekukonko** [comment]
Well done @hhrutter  am currently testing the code however I think you should have exposed Height and Width in `Dim` such as 

```go
func (d Dim) Height() float64 {
	return d.h
}

func (d Dim) Width() float64 {
	return d.w
}
```

What do you think ?

**Comment by olekukonko** [comment]
I currently had to do this 

```go
	dims, err := api.PageDimsFile(s.input)

	if err != nil {
		return -1, -1, err
	}

	if len(dims) < 1 {
		return -1, -1, fmt.Errorf("dim error: expected 2 dimentions")
	}

	var w, h float64

	_, err = fmt.Sscanf(dims[0].String(), "%fx%f", &w, &h)
	if err != nil {
		return -1, -1, err
	}

```

Which is just a drity hack

**Comment by hhrutter** [comment]
If I was doing this in Java I would have agreed. This is Go and we want to follow the best practice in keeping things simple and to the minimum wherever we can.

Oh I see you have a specific usecase..
What is it you are trying to achieve? Dimension parsing is already baked into the api.
Maybe you could explain and open another seperate issue since this is kind of off topic here.
