### ISSUE TITLE
How to fill pdf form

### ISSUE THREAD

**Issue by wj903829182** [pdfcpu/pdfcpu#105]
Itext7 has a good function of filling in form fields。this function can help us to Design templates and fill-in data，Generate the PDF file for the specified template。I didn't see this feature in pdfcpu.Do you have this function? Please tell me.Will this feature be added later?

**Comment by hhrutter** [comment]
Hi!
Form filling is definitely a feature coming up.
What's your specific use case?
See #42.

**Comment by wj903829182** [comment]
Hello！
    Thank you for your reply.
   The specific use case such as Express bill ，Contract。
   Sometimes we need to populate different data to produce PDF files based on PDF templates，so we need fill pdf form。At present, we use itext7 technology to solve our problems.
But it only has advantages in the web backend solution, and it is not very good for the client to solve the problem of form filling.Because Java is not suitable for writing clients, go is more suitable for clients.

**Comment by hhrutter** [comment]
Understood.
Keep checking, form processing will be a feature of pdfcpu.

**Comment by hhrutter** [comment]
I am closing this referring to #42.
