### ISSUE TITLE
processXRefStream: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by ungerik** [pdfcpu/pdfcpu#1052]
* Version: `v0.9.1`
* Linux

`processXRefStream` panics with `invalid memory address or nil pointer dereference` at the following line using some real-world PDFs of customers that I can't attach here:

```go
	if entry, ok := ctx.Table[*objNr]; ok && *entry.Offset == *offset {
		entry.Object = *xsd
	}
```

I suspect that `entry` or `entry.Offset` are nil. Defensive checks would be good.

**Comment by hhrutter** [comment]
Thanks for reporting this!

**Comment by ungerik** [comment]
The latest commit checks for `entry.Offset != nil`, so I guess you can close this issue. Or also check for `entry != nil`, can that ever be nil?

**Comment by hhrutter** [comment]
Hi!
Presumably successfully located map entries are never nil in this case.
As far as panics please report them as issues so we can address them.
