### ISSUE TITLE
equalObjects: unhandled compare for type <nil>

### ISSUE THREAD

**Issue by rnewton** [pdfcpu/pdfcpu#107]
Hitting an unusual error while stamping a pdf. `equalObjects: unhandled compare for type <nil>` using pdfcpu version v0.2.5. Appears to be related to some array in the file, but I haven't dug in to see what's going on. 

Offending pdf attached

One thing of note, perhaps, is that there are a few pages that are landscape while the rest of the document is portrait.

**Comment by rnewton** [comment]
[8da396bd1476dabfad586e6c.pdf](https://github.com/pdfcpu/pdfcpu/files/3611660/8da396bd1476dabfad586e6c.pdf)

**Comment by hhrutter** [comment]
Thanks for reporting this and for the sample.
I'll check it out.

**Comment by hhrutter** [comment]
This will be fixed in the next release.

**Comment by rnewton** [comment]
Great. Thank you! Any idea when the next release will be pushed out?

**Comment by hhrutter** [comment]
Over this weekend hopefully

**Comment by hhrutter** [comment]
fixed with v0.2.5
