### ISSUE TITLE
API not working for adding watermarks?

### ISSUE THREAD

**Issue by orcaman** [pdfcpu/pdfcpu#110]
Hi team,

It seems that the examples of adding watermarks using the API do not work. For instance, the example provided here: https://godoc.org/github.com/pdfcpu/pdfcpu/pkg/api#example-AddWatermarksFile

Has the function `ParseWatermarkDetails` failing with `pdfcpu: ambiguous parameter prefix "r"`. Every parameter given to this function fails for the same reason (`o: 0.3` etc.)

Am I missing something? Is there another way to get the API to work for adding watermarks? 

Thanks!

**Comment by hhrutter** [comment]
Sorry I am still working on the documentation for this.

A new feature is also that pdfcpu supports parameter completion for all command config strings aka *description*. 

So for example the stamp command provides the parameters: points and position
There is an unfortunate bug in the example as indicated by the error message:

To resolve this you can use `pos` for `position`
Whatever the string maybe, it has to be unique and identifying one of the command parameters.

**Comment by orcaman** [comment]
Cool. Thanks, this works :-)
