### ISSUE TITLE
Portfolio vs Attachment

### ISSUE THREAD

**Issue by KopiasCsaba** [pdfcpu/pdfcpu#112]
Dear @hhrutter,

thank you very much for pdfcpu, we enjoy using it!

I'm not quite sure if what I'm writing now is a bugreport or a feature request, feel free to decide please:)

So the thing is, that pdfcpu seemingly does a PDF Portfolio creation instead of adding an attachment. I'm no pdf expert, I'm not really sure what is the internal difference.

But what we see is that acrobat reader handles them differently.

## Attachment
If I take an example PDF with attachment, for example, from here:
https://tcpdf.org/examples/example_041/

This looks like this:
![example_041_screenshot](https://user-images.githubusercontent.com/7661267/66385853-7c025b80-e9c1-11e9-8bad-c3a8acde569c.png)
(Note the icon on the left toolbar, that contains the attachments)

## Portfolio
Given this input files:
- [raw.pdf](https://github.com/pdfcpu/pdfcpu/files/3701752/raw.pdf)
- [attachment.png](https://user-images.githubusercontent.com/7661267/66385731-4a899000-e9c1-11e9-85bc-c866906d61dd.png)

And executing:

```bash
cp raw.pdf attached_with_pdfcpu.pdf
pdfcpu  attachments add attached_with_pdfcpu.pdf attachment.png
```
Results in: [attached_with_pdfcpu.pdf](https://github.com/pdfcpu/pdfcpu/files/3701765/attached_with_pdfcpu.pdf)

This looks like this:
![attached_with_pdfcpu_screenshot](https://user-images.githubusercontent.com/7661267/66385956-b23fdb00-e9c1-11e9-80b4-e4da2cc8229d.png)

When handling portfolios, there is a "Portfolio" option showing up in the "View" menu.

So we would like to have a feature (or fix?) to be able to add regular attachments!

Looking forward to hear what do you think!

(Our problem is that acrobat opens these files in this not-so-useful view that is hard to hide & explain to our users:))

Best regards,
Csaba

**Comment by KopiasCsaba** [comment]
(Don't get disturbed by the pdfcpu version in the screenshot, the latest version does the same.)

**Comment by hhrutter** [comment]
You are right!
What pdfcpu is doing right now for "attachments" is creating a portfolio.
Looks like we need the distinction between attachments and portfolio.
So in addition to `pdfcpu attachments add` we would have `pdfcpu portfolio add`

**Comment by KopiasCsaba** [comment]
Thank you very much!:)
