### ISSUE TITLE
How to determine if document has been watermarked

### ISSUE THREAD

**Issue by gbenroscience** [pdfcpu/pdfcpu#113]
Hi @hhrutter. Great job with the last release! I am currently unable to determine if a pdf has been previously watermarked or not as info does not return any watermark details.

How can we determine if a document has been watermarked ?

**Comment by olekukonko** [comment]
I think this should have come with `Info` and ` InfoFile` however they both return `[]string` the solution might be to add 

- `pdfcpu watermark check` 
- `CheckWatermarks`
- `CheckWatermarksFile`

I also strongly believe this information is important enough to be in `Info`

**Comment by hhrutter** [comment]
Hi!
What's your usecase for checking via the api if a pdf has been watermarked?
I think we can include it as part of the info block that gets printed when you execute
`pdfcpu info xyz.pdf`

**Comment by gbenroscience** [comment]
pdfcpu has the ability to remove and update watermarks, but at what point do I know that I am supposed to call update or remove watermark instead of add watermark.

Usecase: Trying to build a UI for stamping on top of pdfcpu. At the point of opening the document I need to know everything about the document to allow me make some UI decisions.

**Comment by olekukonko** [comment]
I think I agree with @gbenroscience if you look at it programmatically. At what point do you call `RemoveWatermarks` id there is no way to know if there is a `Watermark` in the first place?

**Comment by hhrutter** [comment]
A UI on top of pdfcpu is a nice usecase.
I would say only the user can decide whether you want to replace a page's watermark (and doing an update) or add to it but if you tell me more about your usecase maybe I understand your requirement better.

**Comment by olekukonko** [comment]
I think in `UI` feedback is important for user experience, even if the user can decide there must be a button to trigger the action at that point 

- What state will the button be 
- When the Button is Pressed What Operation should happen 
- Remove watermark button should be disabled if no watermark is present
- Etc. 

`If you just want to add to the page without destroying any previous watermarks/stamps just always do ADD stamp.
`

I don't think adding a new page is the right solution

**Comment by hhrutter** [comment]
Understood.
Scheduled for next release.
