### ISSUE TITLE
Expose Dim Height & Width

### ISSUE THREAD

**Issue by olekukonko** [pdfcpu/pdfcpu#114]
This is related to #104 

#### Introduction 
Somthings you need to apply a watermark to the exact height and width of a document. The current `pdupdf` returns heigh and width as strings. 

#### Use Case: Recharge Image to exact width.

- [Original PDF  sb.pdf](https://github.com/pdfcpu/pdfcpu/files/3706663/sb.pdf)
- ![Stamp Image bg.joj](https://user-images.githubusercontent.com/2615393/66470897-6143eb80-ea82-11e9-9673-615725f6b0bb.jpg)
- [Output out.pdf](https://github.com/pdfcpu/pdfcpu/files/3706664/out.pdf)

#### Currently 
If there is a way to know the width, the image size would have been reduced before stamping.  This is currently been done with `Sscanf` as follows:

```go
	dims, err := api.PageDimsFile(s.input)

	if err != nil {
		return -1, -1, err
	}

	if len(dims) < 1 {
		return -1, -1, fmt.Errorf("dim error: expected 2 dimentions")
	}
	var w, h float64

	_, err = fmt.Sscanf(dims[0].String(), "%fx%f", &w, &h)
	if err != nil {
		return -1, -1, err
	}

```

### Proposal 

Expose Height & Width 

```go
func (d Dim) Height() float64 {
	return d.h
}

func (d Dim) Width() float64 {
	return d.w
}
```

**Comment by hhrutter** [comment]
OK, so that's easy: Just use a relative scalefactor of 1.0 like so:
`pdfcpu stamp add 'logo.img pos:c s:1.0 rel' src.pdf dest.pdf`

**Comment by olekukonko** [comment]
`scalefactor` will preserve the aspect ratio of the image and would not work for cases where the height is fixed (this would have been reduced with scale)

**Comment by hhrutter** [comment]
OK understood.
Goes into the next release.

**Comment by jpap** [comment]
I'd also like to have `w` and `h` of a `Dim` public.  I'm using `ctx.PageDims()` to parse a PDF so that I can return the page dimensions.

The only way to do so at the moment is to parse `Dim.String()`...

**Comment by jpap** [comment]
Thank you, @hhrutter! <3
