### ISSUE TITLE
ParseWatermarkDetails: Text Encoding and Parameters

### ISSUE THREAD

**Issue by Laur1nMartins** [pdfcpu/pdfcpu#117]
i really really like this package but i found a bug i think:
Executing the following line of code
`wm, err := pdfcpu.ParseWatermarkDetails("$$$üäö$$$, pos:bc, rot:0, off:0 10, s:1, op:1", true)`
results in this string being printed as watermark: `$$$ˆ...ˆ⁄ˆ¶$$`, the german character 'äüö' just dont get printed. I read through the code but im not deep enough into the project to spot where the problem might be.

And i would like to make another suggestion: 
When a **:** is used inside the watermark text the program just cuts everything behind that character. Inside the code of **ParseWatermarkDetails** the paramter string is split after every **:** . i think this could be avoided by passing the text string as separate parameter ?

**Comment by Laur1nMartins** [comment]
My point of concern is that most people will search quit some time to find out about this : thing. 
For exmaple: using a Timestamp inside a watermark that contains a : prints just the first half of the time. How should someone that is not directly looking into your code know that you use that : as a seperator ?

My proposition would be to split the string into <text-source> and <options>. Your code does just that by parsing the string. When these parameters are given directly seperated there would be less parsing overhead and no one will have problems with : in the text string.

Or am i missing some detail ?

**Comment by hhrutter** [comment]
I am aware the documentation at pdfcpu.io is lacking - sorry.
This is going to be fixed with the next release.

**Comment by mschmidt291** [comment]
So there is no known quick-fix for using special characters like Ä,Ö,Ü etc. in the watermarkdetails until this bug is fixed?

**Comment by hhrutter** [comment]
Expect this to be fixed by the end of this week.
