### ISSUE TITLE
Win10: ambiguous parameter prefix "'f"

### ISSUE THREAD

**Issue by kejmlch** [pdfcpu/pdfcpu#118]
in Windows 10 cmd:
pdfcpu nup 'f:A4L' out.pdf in.pdf
pdfcpu: ambiguous parameter prefix "'f"

**Comment by hhrutter** [comment]
You are missing the n-Up value, have you tried:

`pdfcpu nup 'f:A4L' out.pdf 4 in.pdf` ?

`formsize`and `papersize` are the same, so 
`pdfcpu nup 'paper:A4L' out.pdf 4 in.pdf`should also work.

If you are supplying the n-Up value and still get this error message
then I do not have an explanation until I have tested this on Win10.
I don't see it happening on the Mac.

**Comment by kejmlch** [comment]
I forgot to overwrite the parameter, nor does it work either way.

c:\GoUser\bin>pdfcpu nup 'f:A4L' out.pdf 4 in.pdf
pdfcpu: ambiguous parameter prefix "'f"

c:\GoUser\bin>pdfcpu nup 'paper:A4L' out.pdf 4 in.pdf
pdfcpu: ambiguous parameter prefix "'paper"

**Comment by kejmlch** [comment]
pdfcpu nup f:A4L out.pdf 4 in.pdf
and
pdfcpu nup paper:A4L out.pdf 4 in.pdf
is working

**Comment by hhrutter** [comment]
Works fine. No issue,
