### ISSUE TITLE
Merge failed

### ISSUE THREAD

**Issue by adam6313** [pdfcpu/pdfcpu#125]
I want to merge files
But an error has occurred
this error: 
"msg":"marge file failed","output":"Read: xRefTable failed: pdfcpu: headerVersion: corrupt pdf stream - no header version available"

What happened or what I did wrong?

Thanks!

**Comment by hhrutter** [comment]
Hi!

First make sure the PDFs you want to merge are all valid:
`pdfcpu validate test.pdf`

If you get an error create verbose validation output like so:
`pdfcpu validate -vv test.pdf` and post the resulting stacktrace

If you merge valid PDFs  and merging throws an error, 
please create verbose merge output and post the resulting stacktrace
`pdfcpu merge -vv out.pdf in1.pdf in2.pdf`

if merging seems successful but you can't open it then
make sure it is valid:
`pdfcpu validate mergedfile.pdf`
If validation throws an error please post the stacktrace (see above)

**Comment by hhrutter** [comment]
Is this still an issue for you?
If not I am gonna close this in a couple of days.
