### ISSUE TITLE
Add Watermark by API always return unsupported color space

### ISSUE THREAD

**Issue by mwolf1989** [pdfcpu/pdfcpu#126]
I have Create a png  qr and i want to stamp it on pdf pages. I use the github.com/skip2/go-qrcode lib for qr code creation. 

When i want to add this with this code to the pdf:

```	
        onTop := true
	conf := pdfcpu.NewDefaultConfiguration()
	conf.ValidationMode = pdfcpu.ValidationNone
	wm, err := pdfcpu.ParseWatermarkDetails("./qrcodes/" + email + ".png", onTop)
	if err != nil {
		log.Fatalln("Parse Watermark error:", err)
	}
	err = api.AddWatermarksFile("./pdfs/1.pdf", "./ppdfs/" + email + ".pdf", nil, wm, conf )
	if err != nil {
		log.Fatalln("AddWatermarks file error: ", err)
	}
```

It always returns 

AddWatermarks file error:  unsupported color space

what kind of color space is needed and how can i change this?

**Comment by hhrutter** [comment]
Hello,

Please post a stacktrace, or even better a test png that reproduces this.

If you are using the api, just turn on the appropriate loggers before calling into the api like so:

```
PDFCPULog.SetDefaultDebugLogger()
PDFCPULog.SetDefaultInfoLogger()
PDFCPULog.SetDefaultStatsLogger()
PDFCPULog.SetDefaultTraceLogger()
PDFCPULog.SetDefaultReadLogger()
PDFCPULog.SetDefaultValidateLogger()
PDFCPULog.SetDefaultOptimizeLogger()
PDFCPULog.SetDefaultWriteLogger()
```
