### ISSUE TITLE
Color Lookup Table in String Literal is not loaded correctly

### ISSUE THREAD

**Issue by dharnitski** [pdfcpu/pdfcpu#128]
Steps to reproduce:

Extract images from this document - https://vivaldi.nlr.ru/pn000151996/file (20MB)

You get PNG images with messed up Color Lookup table

Fixed in https://github.com/pdfcpu/pdfcpu/pull/127

**Comment by hhrutter** [comment]
Thanks for discovering this.
Please provide a signed commit so I can merge this in.

**Comment by dharnitski** [comment]
Hi @hhrutter,
just pushed signed commit under separate PR - https://github.com/pdfcpu/pdfcpu/pull/130
