### ISSUE TITLE
Watermark: ÄÜÖüäö get displayed wrong

### ISSUE THREAD

**Issue by Laur1nMartins** [pdfcpu/pdfcpu#132]
Using this config:
`wm := pdfcpu.DefaultWatermarkConfig()`
`wm.Update = true`
`wm.OnTop = true`
`wm.Dy = 12`
`wm.Pos = pdfcpu.BottomCenter`
`wm.FontSize = 10`
`wm.Diagonal = pdfcpu.NoDiagonal`
`wm.TextLines = strings.Split(revel.Message(c.Session["currentLocale"].(string), "ims.pdf_stamp", file.Fversion, time.Now().Format("2006-01-02")), "\\n")`
`err = api.AddWatermarksFile(cachedFilePath, "", nil, wm, nil)`
`if err != nil {`
`revel.AppLog.Error(err.Error())`
`}`
results in ÄÖÜöäü getting written as  Ãœ Ã– Ã¼ Ã¶ Ã¤ Ã„.

**Comment by hhrutter** [comment]
Since v0.3 you need to call `pdf.ParseTextWatermarkDetails`.
Have a look at pkg/api/api_test.go/TestAddWatermarks.

**Comment by Laur1nMartins** [comment]
Im a bit confused now. 
The correct way of adding a stamp is calling pdf.ParseTextWatermarkDetails ?
What is the purpose of those other exported functions that i used mistankingly ?

**Comment by hhrutter** [comment]
Like I said check out the test function I mentioned.
It's all laid out for you over there.
If you have further questions you can ping me on the gopher slack in the #pdfcpu channel.
