### ISSUE TITLE
Trailer dict parse error

### ISSUE THREAD

**Issue by OrganicChem** [pdfcpu/pdfcpu#137]
This is a stacktrace of a validation of a problematic file:

go pdfcpu: ./pdfcpu validate -v /Users/marlon/Desktop/go\ pdfcpu/in1/vocab.pdf
validating(mode=relaxed) /Users/marlon/Desktop/go pdfcpu/in1/vocab.pdf ...
INFO: 2019/11/29 16:06:19 PDF Version 1.5 conforming reader
Fatal: pdfcpu: parse: unterminated dictionary
github.com/pdfcpu/pdfcpu/pkg/pdfcpu.init
/Users/horstrutter/go/src/github.com/pdfcpu/pdfcpu/pkg/pdfcpu/parse.go:34
runtime.doInit
/Users/horstrutter/gotip/src/runtime/proc.go:5222
runtime.doInit
/Users/horstrutter/gotip/src/runtime/proc.go:5217
runtime.doInit
/Users/horstrutter/gotip/src/runtime/proc.go:5217
runtime.doInit
/Users/horstrutter/gotip/src/runtime/proc.go:5217
runtime.main
/Users/horstrutter/gotip/src/runtime/proc.go:190
runtime.goexit
/Users/horstrutter/gotip/src/runtime/asm_amd64.s:1357
Read: xRefTable failed
github.com/pdfcpu/pdfcpu/pkg/pdfcpu.Read
/Users/horstrutter/go/src/github.com/pdfcpu/pdfcpu/pkg/pdfcpu/read.go:75
github.com/pdfcpu/pdfcpu/pkg/api.ReadContext
/Users/horstrutter/go/src/github.com/pdfcpu/pdfcpu/pkg/api/api.go:71
github.com/pdfcpu/pdfcpu/pkg/api.Validate
/Users/horstrutter/go/src/github.com/pdfcpu/pdfcpu/pkg/api/api.go:222
github.com/pdfcpu/pdfcpu/pkg/api.ValidateFile
/Users/horstrutter/go/src/github.com/pdfcpu/pdfcpu/pkg/api/api.go:268
github.com/pdfcpu/pdfcpu/pkg/cli.Validate
/Users/horstrutter/go/src/github.com/pdfcpu/pdfcpu/pkg/cli/cli.go:33
github.com/pdfcpu/pdfcpu/pkg/cli.Process
/Users/horstrutter/go/src/github.com/pdfcpu/pdfcpu/pkg/cli/process.go:92
main.process
/Users/horstrutter/go/src/github.com/pdfcpu/pdfcpu/cmd/pdfcpu/main.go:105
main.handleValidateCommand
/Users/horstrutter/go/src/github.com/pdfcpu/pdfcpu/cmd/pdfcpu/prepare.go:100
main.CommandMap.Handle
/Users/horstrutter/go/src/github.com/pdfcpu/pdfcpu/cmd/pdfcpu/registry.go:85
main.main
/Users/horstrutter/go/src/github.com/pdfcpu/pdfcpu/cmd/pdfcpu/main.go:61
runtime.main
/Users/horstrutter/gotip/src/runtime/proc.go:203
runtime.goexit
/Users/horstrutter/gotip/src/runtime/asm_amd64.s:1357

**Comment by hhrutter** [comment]
Please post the output of `pdfcpu validate -vv yourFile.pdf` this will tell us more. Can you share a sample pdf with this behavior?

**Comment by OrganicChem** [comment]
Output file from `pdfcpu validate -vv yourFile.pdf`

[output.txt](https://github.com/pdfcpu/pdfcpu/files/3906525/output.txt)

PDF File:
[vocab.pdf](https://github.com/pdfcpu/pdfcpu/files/3906528/vocab.pdf)

**Comment by hhrutter** [comment]
Fixed with v0.3.1
