### ISSUE TITLE
Parse error during validation

### ISSUE THREAD

**Issue by OrganicChem** [pdfcpu/pdfcpu#138]
This is a stacktrace of a validation of a problematic file:

go pdfcpu: ./pdfcpu validate -v /Users/marlon/Desktop/large\ pdf\ files/GSWC-Standard-Drawings-Rev-1.3-February-2018.pdf
validating(mode=relaxed) /Users/marlon/Desktop/large pdf files/GSWC-Standard-Drawings-Rev-1.3-February-2018.pdf ...
INFO: 2019/11/29 16:12:43 PDF Version 1.5 conforming reader
Fatal: strconv.Atoi: parsing "j": invalid syntax
dereferenceObject: problem dereferencing object 8
github.com/pdfcpu/pdfcpu/pkg/pdfcpu.dereferenceObject
/Users/horstrutter/go/src/github.com/pdfcpu/pdfcpu/pkg/pdfcpu/read.go:2156
github.com/pdfcpu/pdfcpu/pkg/pdfcpu.dereferenceObjects
/Users/horstrutter/go/src/github.com/pdfcpu/pdfcpu/pkg/pdfcpu/read.go:2256
github.com/pdfcpu/pdfcpu/pkg/pdfcpu.dereferenceXRefTable
/Users/horstrutter/go/src/github.com/pdfcpu/pdfcpu/pkg/pdfcpu/read.go:2335
github.com/pdfcpu/pdfcpu/pkg/pdfcpu.Read
/Users/horstrutter/go/src/github.com/pdfcpu/pdfcpu/pkg/pdfcpu/read.go:80
github.com/pdfcpu/pdfcpu/pkg/api.ReadContext
/Users/horstrutter/go/src/github.com/pdfcpu/pdfcpu/pkg/api/api.go:71
github.com/pdfcpu/pdfcpu/pkg/api.Validate
/Users/horstrutter/go/src/github.com/pdfcpu/pdfcpu/pkg/api/api.go:222
github.com/pdfcpu/pdfcpu/pkg/api.ValidateFile
/Users/horstrutter/go/src/github.com/pdfcpu/pdfcpu/pkg/api/api.go:268
github.com/pdfcpu/pdfcpu/pkg/cli.Validate
/Users/horstrutter/go/src/github.com/pdfcpu/pdfcpu/pkg/cli/cli.go:33
github.com/pdfcpu/pdfcpu/pkg/cli.Process
/Users/horstrutter/go/src/github.com/pdfcpu/pdfcpu/pkg/cli/process.go:92
main.process
/Users/horstrutter/go/src/github.com/pdfcpu/pdfcpu/cmd/pdfcpu/main.go:105
main.handleValidateCommand
/Users/horstrutter/go/src/github.com/pdfcpu/pdfcpu/cmd/pdfcpu/prepare.go:100
main.CommandMap.Handle
/Users/horstrutter/go/src/github.com/pdfcpu/pdfcpu/cmd/pdfcpu/registry.go:85
main.main
/Users/horstrutter/go/src/github.com/pdfcpu/pdfcpu/cmd/pdfcpu/main.go:61
runtime.main
/Users/horstrutter/gotip/src/runtime/proc.go:203
runtime.goexit
/Users/horstrutter/gotip/src/runtime/asm_amd64.s:1357

**Comment by hhrutter** [comment]
Please post the output of `pdfcpu validate -vv yourFile.pdf`
but to get to the bottom of this we need a pdf file to reproduce or
you  turn on the parseLogger in main.go  and `go install` pdfcpu on your machine.
This is the line where you need to remove the comment: //PDFCPULog.SetDefaultParseLogger()
Should be in initLogging line 158. (This logger is very verbose hence turned off by default.)

**Comment by OrganicChem** [comment]
Output file from `pdfcpu validate -vv yourFile.pdf`
[output.txt](https://github.com/pdfcpu/pdfcpu/files/3906514/output.txt)

PDF file:
[GSWC-Standard-Drawings-Rev-1.3-February-2018.pdf](https://github.com/pdfcpu/pdfcpu/files/3906516/GSWC-Standard-Drawings-Rev-1.3-February-2018.pdf)
