### ISSUE TITLE
Support last page in page selection

### ISSUE THREAD

**Issue by hsanoyan** [pdfcpu/pdfcpu#140]
How can I ignore last page in page selection, if I don't know the page count?

**Comment by hhrutter** [comment]
That's a tricky one. 
We need to extend the page selection syntax for this.

**Comment by hsanoyan** [comment]
Yes I know about that one. There is a case when I need to add stamp for all pages expect first one and last one. I'm using `2-` to skip first one, but not sure how to skip last one. My current solution is to require value from user. But actually wanted to have skip last by default. 
I just thought it is common and there might be some solution. Anyway thanks for replay and for this project.

**Comment by hhrutter** [comment]
Would a pdfcpu cmd help you that returns the page count?

**Comment by hsanoyan** [comment]
It can help but I don't want to do that. Here is why. I have a golang server for processing `PDF` getting data from request. And I'm requesting the server from another nodejs server. I don't want to keep defaults in golang server, instead I want to have them in node server as in that context defaults will make sense.

Another option I can see is to implement custom `!last!` placeholder in which case it will be replaced by the page count. But I thought this is something that will be good to be implemented in package itself. I'm very new to golang, but if you think it will be easy I can try to open PR?

**Comment by hhrutter** [comment]
It is tricky. It has to be intuitive and all of the following expressions have to work, given `L`as the symbol for last page:
`!L`
`2-,!L` should be the same as `2-L`
`odd,!L`

Of course `L-x`should not be possible so there are some design considerations that have to be resolved beforehand.

**Comment by hsanoyan** [comment]
I agree that `L` can make some confusion and also another invalid case. So worth to think more about this. But I think if we are going to add this feature maybe add `last-n`? This definitely will cover more cases. What you think?

**Comment by hhrutter** [comment]
We have to tweak the used regexp and be careful not to introduce side effects at the same time.
What do you mean by `last-n`? I am still inclined to implement `L`.

**Comment by hsanoyan** [comment]
I mean have an option to skip last 5 pages for example. Do you think this is not that common use case?

**Comment by hhrutter** [comment]
I think we can make the symbol L (=last page) work.
Stay tuned.

**Comment by hsanoyan** [comment]
If you wish, can you send me the `.go` file where I can find the code and open PR?

**Comment by hhrutter** [comment]
This is fixed with the next release.

**Comment by hsanoyan** [comment]
Sorry @hhrutter, I missed this comment somehow. Thanks for your support and for great project.
