### ISSUE TITLE
go modules defaults to version 0.2.5 (not v0.3)

### ISSUE THREAD

**Issue by rigelrozanski** [pdfcpu/pdfcpu#142]
When I've tried including this project go mod automatically includes version `0.2.5` in the `go.mod` file

```
require (
        ...
	github.com/pdfcpu/pdfcpu v0.2.5
        ...
}
```
When I manually change the line to the have `v.0.3` go mod spits out the following error during installation: 

```
go: errors parsing go.mod:
.......<my project dir>......./go.mod:9: invalid module version "v0.3": no matching versions for query "v0.3"
make: *** [install] Error 1
```

I have a feeling that it's due to semantic versioning not being used... really a patch number of `0` should be included, your release should probably be for version `v0.3.0`
See more: https://semver.org/

**Comment by rigelrozanski** [comment]
Fix if I use the following in my `go.mod`
```
	github.com/pdfcpu/pdfcpu v0.2.6-0.20191115001021-1e3294bc5ab2
```

**Comment by hhrutter** [comment]
Which go mod proxy are you using?
For some reason [go.dev](https://go.dev/) only shows v0.2.5 as the latest version.
I haven't had time to look into this and the process to update the proxy when a new version gets pushed. pdfcpu has been using semantic versioning all along. must be smth else.
