### ISSUE TITLE
HexString validation fails

### ISSUE THREAD

**Issue by OrganicChem** [pdfcpu/pdfcpu#143]
pdfcpu validate --v gives:

output: 
[output.txt](https://github.com/pdfcpu/pdfcpu/files/3939931/output.txt)

PDF reference file: 
[bad1.pdf](https://github.com/pdfcpu/pdfcpu/files/3939933/bad1.pdf)

**Comment by hhrutter** [comment]
This show off unusual white space within < > hexLiterals.
