### ISSUE TITLE
Measure dict parse error

### ISSUE THREAD

**Issue by OrganicChem** [pdfcpu/pdfcpu#144]
Issued: ./pdfcpu validate -vv bad2.pdf

Output: 
[output.txt](https://github.com/pdfcpu/pdfcpu/files/3940457/output.txt)

PDF Reference file:
[bad2.pdf](https://github.com/pdfcpu/pdfcpu/files/3940462/bad2.pdf)

Interestingly, this file was created using Acrobat Pro DC.

Separately, I'm wondering if there is a way during a merge or split process that if a malformed PDF file is encountered, there is any way within this library to "massage" the file so that the file can be "fixed" in-stream (similar to re-saving the file with a valid PDF creator/editor)?

**Comment by hhrutter** [comment]
I already touched on this in #136.

Validation and subsequent optimization is inherent to most pdfcpu operations before the PDF gets written back.

pdfcpu defaults to *relaxed validation* which in combination with optimization already takes care of a lot of the artifacts we have seen where PDF writers don't stick to the PDF spec at 100%.

Extending validation is an ongoing process.

Long story short pdfcpu is already doing this behind the scenes and for those cases where not we have to rely on users like you creating issues so we can keep on improving validation and optimization. 

The way to simply *fix* a PDF would be: `pdfcpu optimize test.pdf testopt.pdf`

**Comment by OrganicChem** [comment]
I tried the optimize fix above for a v1.7 file that is malformed and got:
`Read: xRefTable failed: pdfcpu: scanLineRaw: returning nothing`

**Comment by hhrutter** [comment]
Thx for discovering this bug!
Sorry it was not obvious to me this was a seperate *bad* file.

**Comment by OrganicChem** [comment]
Since the latest binary is 3 commits behind, I needed to install with $GOPATH. Just a comment: on Mac OS, go install fails. Instead go build works! You may want to change the readme for this instruction.

**Comment by hhrutter** [comment]
`go install` works for me. That's all I do. And I'm on a Mac.
