### ISSUE TITLE
Generalize Extract* to read and write from a Reader and Writer

### ISSUE THREAD

**Issue by advancedlogic** [pdfcpu/pdfcpu#145]
Change all the Extract* functions so that I can specify a Reader and a Writer.
For example:

`func ExtractContent(rs io.ReadSeeker, outDir string, selectedPages []string, conf *pdf.Configuration) error`

into

`func ExtractContent(rs io.ReadSeeker, ws io.WriteSeeker, selectedPages []string, conf *pdf.Configuration) error`

**Comment by hhrutter** [comment]
Hi there!

What's your specific usecase?
The reason I am asking is extraction results in an unknown number of file writes.
The current design is *Extract all artifacts of given type to destination X*.

**Comment by sagikazarmark** [comment]
I would like to extract a specific attachment from a file and process it.

**Comment by sagikazarmark** [comment]
@hhrutter Thanks a lot!

I went through the referenced commit, but I can't seem to find a way to extract a single attachment in the API. The Extract methods are still trying to write to files. Can you point me to the right place?

Thanks!

**Comment by hhrutter** [comment]
Take a look at: 

func TestAttachmentsLowLevel(t *testing.T) in [attachments_test.go](https://github.com/pdfcpu/pdfcpu/blob/master/pkg/api/test/attachments_test.go)

**Comment by sagikazarmark** [comment]
Got it, thanks!
