### ISSUE TITLE
Merge append

### ISSUE THREAD

**Issue by dhf0820** [pdfcpu/pdfcpu#149]
Under the version prior to this repository, my list contained the output from the previous merge and a could continuously append documents as they were processed. This new version seems to recreate the output file and it is the first file in the merge list.  The file becomes nil and the merge fails.  

What is the proper way to do this with the new version?

Don French

**Comment by hhrutter** [comment]
Hi!

The behavior of `merge`never changed and is documented here: http://pdfcpu.io/core/merge

**Comment by dhf0820** [comment]
Question: If the output file has something in it, What happens to it?

**Comment by hhrutter** [comment]
```
Go-> pdfcpu help merge
usage: pdfcpu merge [-v(erbose)|vv] [-q(uiet)] outFile inFile...

Concatenate a sequence of PDFs/inFiles into outFile.

verbose, v ... turn on logging
        vv ... verbose logging
  quiet, q ... disable output
   outFile ... output pdf file
   inFiles ... a list of at least 2 pdf files subject to concatenation.
```
`outFile`contains the merged result and nothing else.
That means a pre-existing `outFile`  gets overwritten.

**Comment by jpedlow** [comment]
Would it be worthwhile, in this case (I have a similar use case), to consider adding APPEND, which adds to the end of out.pdf while preserving its current existing content?

**Comment by hhrutter** [comment]
This feature is live with the latest commit.
For details please refer to `pdfcpu help merge`.
Thank you for using pdfcpu 💚
