### ISSUE TITLE
Starting merge from 2 page

### ISSUE THREAD

**Issue by JohnnyMclain12** [pdfcpu/pdfcpu#150]
Hello,

Is it possible to merge two pdf files starting from second page to the end?

**Comment by hhrutter** [comment]
Hi!

I don't understand exactly but if you want to merge 2 PDFs, skipping the first page of each file you can do this:

```
pdfcpu trim -pages 2- test1.pdf
pdfcpu trim -pages 2- test2.pdf
pdfcpu merge merged.pdf test1.pdf test2.pdf
```
