### ISSUE TITLE
Invalid page rotate value

### ISSUE THREAD

**Issue by lynzt** [pdfcpu/pdfcpu#152]
Running: `pdfcpu validate` produces the following error...

[crash - 3529e669.log](https://github.com/pdfcpu/pdfcpu/files/4017242/crash.-.3529e669.log)

We're unable to provide the original file as it contains personal information. Please let me know if you have what you need to recreate (and fix) the issue.

**Comment by hhrutter** [comment]
This is a bug in the validator and will be fixed in the upcoming release!
Stay tuned.
