### ISSUE TITLE
Unable to specify color for watermark from api

### ISSUE THREAD

**Issue by divan** [pdfcpu/pdfcpu#153]
Hi, thanks for a fantastic piece of software.
I'm trying to use watermarking feature as a library, and use a following code:

```go
    conf := pdfcpu.NewDefaultConfiguration()
    wm := pdfcpu.DefaultWatermarkConfig()
    wm.OnTop = true
    wm.Diagonal = pdfcpu.NoDiagonal
     ... // set other watermark configs
    //wm.Color = pdfcpu.SimpleColor{255, 0, 0}
    err := api.AddWatermarksFile(inFile, outFile, nil, wm, conf)
```

the problem is there seem to be no way to specify a text color, as `SimpleColor` has only private fields `r`, `g` and `b`. As a hack, I can use `ParseTextWatermarkDetails` and provide color via command-line description flags, but that's too hacky.

I can see few of solutions here:
 1) create a constructor function for SimpleColor - aka `NewSimpleColor(r, g, b float32)`
 2) make `SimpleColor` fields public - `R`, `G`, `B` instead of `r`, `g`, `b`
 3) use `color.Color` interface from stdlib in `Watermark` (and make SimpleColor to satisfy this interface)

I can make a PR for the solution, but would love to know authors' opinion on that matter.

**Comment by hhrutter** [comment]
Hi there!

Watermarking via the api works differently.
Please get the latest release and check out: pdfcpu/pkg/api/test/stamp_test.go
Let me know in case this doesn't work for you.

Thank you for using pdfcpu 💚

**Comment by divan** [comment]
@hhrutter thanks! Yes, I realized that I can use `ParseTextWatermarkDetails` but it feels like unneeded layer of complexity for using the library. This description line is a good solution for specifying complex configuration from command line (due to the lack of better options), but when using it as a library, it feels unneeded burden.

Everything except `Color` field works perfectly with current design. Like, setting `wm.Diagonal = pdfcpu.NoDiagonal` is explicit, clear, discoverable and documented, without a need to learn a special description line format.

I think solution number 1 (adding constructor for SimpleColor) will perfectly solve the issue without introducing any changes into the types or api of the library, so it seems pretty safe.

PS. Actually, for my particular use case I needed to set Color to black (default is grey), and managed to do this just by using zero value of SimpleColor. But just for the sake of making library api better, I think it's worth to solve this color issue.

**Comment by hhrutter** [comment]
I am happy with exporting r, g, b in SimpleColor aka your option 2.
Let me know if you are going to submit a PR otherwise I fix this myself.

I have to stress though that `ParseTextWatermarkDetails`is there for a reason.
Without it you will run into problems as soon as you are using special characters.

**Comment by hhrutter** [comment]
Since I have not heard back I am going to fix this the way I described above and close it.
