### ISSUE TITLE
PDF page sizes after importing images

### ISSUE THREAD

**Issue by doronbehar** [pdfcpu/pdfcpu#154]
Somewhat related to #136 , I have some PDF files created with `convert` from imagemagick (see [`convert(1)`](https://www.mankier.com/1/convert). Apparently, the PDFs it created are not viewed properly in Adobe reader. To be more specific, I scan Homework JPGs with [OpenNoteScanner](https://github.com/ctodobom/OpenNoteScanner) and then create a PDF on the computer with `convert`.

My Homework reviewers, told me that many pages in my PDFs are not viewable (in Adobe reader - they don't know anything else) and hence they gave me grades of around 0 for all of these assignments.. I know this is a bug in imagemagick, but I was wondering perhaps I could run some `pdfcpu` command and fix the PDFs before I send them. I tried `pdfcpu optimize` but I'm not sure how to test this since I'm using GNU/Linux and I can't install Adobe reader...

I do see some evidence that these PDFs are malformed - with [`zathura`](https://git.pwmt.org/pwmt/zathura), I get the following warnings when opening and scrolling up and down the PDF `convert` created:

```
error: ICC profile (N=3) is not Gray
warning: ignoring broken ICC profile
```

I get these warnings with and without running `pdfcpu optimze`.

On a slightly different topic, but in the attempt to help my self with the same issue, I've encountered the `pdfcpu import` command which it seems I can use instead of imagemagick's `convert`. Unfortunately, it seems I _can't_ replace `convert` with it because scans of different sizes wind up in different sizes of page in the final PDF - Scans of smaller sections of an A4 wind up way bigger then scans of the size of roughly A4. But, it is possible to fix this issue with certain parameters to the `convert` command.

Here are the results of the PDF creation with their corresponding commands.

- [PDF made with `convert`](https://github.com/pdfcpu/pdfcpu/files/4023166/algebra1m_hw4.convert.pdf): Created with `convert -units pixelsperinch -density 72 -page A4 algebra1m_hw4*.jpg algebra1m_hw4.convert.pdf`.
- [PDF made with `pdfcpu import`](https://github.com/pdfcpu/pdfcpu/files/4023073/algebra1m_hw4.pdfcpu.pdf): Using just `pdfcpu import algebra1m_hw.convert.pdf algebra1m_hw*.jpg`.

And the original images:

[algebra1m_hw4-basedim.q2.jpg](https://user-images.githubusercontent.com/10998835/71777958-3db81080-2f9f-11ea-91c0-92abc9a916eb.jpg)
[algebra1m_hw4-basedim.q7 1.jpg](https://user-images.githubusercontent.com/10998835/71777959-3e50a700-2f9f-11ea-8fd2-8d306007244e.jpg)
[algebra1m_hw4-basedim.q7 2.jpg](https://user-images.githubusercontent.com/10998835/71777960-3e50a700-2f9f-11ea-94d4-ef924ec60276.jpg)
[algebra1m_hw4-basedim.q11-20a-b.jpg](https://user-images.githubusercontent.com/10998835/71777961-3e50a700-2f9f-11ea-83f1-0ed566c99e85.jpg)
[algebra1m_hw4-basedim.q20c.jpg](https://user-images.githubusercontent.com/10998835/71777962-3ee93d80-2f9f-11ea-888e-18fa01ab54fe.jpg)
[algebra1m_hw4-basedim.q20d-e.jpg](https://user-images.githubusercontent.com/10998835/71777963-3ee93d80-2f9f-11ea-917e-c0e8e1287153.jpg)

BTW the other reason I'm using `convert` is because of it's ability to aggregate SVG images as well while `pdfcpu import` reports: `needs an image extension (.jpg, .jpeg, .png, .tif, .tiff)`.

**Comment by hhrutter** [comment]
Hello!

Let's see if we can get your homework grades back on track..
When importing images pdfcpu defaults to generating pages with page dimensions 
corresponding to the image dimensions of the imported images as documented [here](http://pdfcpu.io/generate/import) 

Just specify your desired output format and center the image on the page and play around with scaling a little bit like so:

`pdfcpu import 'f:A4, pos:c, scale:.8 rel' algebra.pdf *.jpg`

(A relative scaling factor of 1.0 should work, but it cuts off some content here, this gives me something to investigate.)

The most important part to realize when using `pdfcpu import`:
Unless you explicitly set the position of your image pdfcpu defaults to `pos: full`
and therefore creating pages with dimensions matching the imported images.
So when you import a bunch of images you get a PDF with different page sizes.
If you want to create a PDF that you can print just set `pos:c`and the desired format.

Q: Can you tell me about your use case for importing SVG to PDF? 

Thank you for using pdfcpu 💚

**Comment by doronbehar** [comment]
Oh right! The final result with those arguments seems better. I hope my homework reviewers won't complain now. Thanks for helping me out with this! I'd have never picked it up myself - I'm too busy to get deep into those kind of commands crafting ever since I started studying.

> (A relative scaling factor of 1.0 should work, but it cuts off some content here, this gives me something to investigate.)

I didn't notice any cuttings made to my photos - no content missing.

> Q: Can you tell me about your use case for importing SVG to PDF?

My homework reviewers require me to put a cover page for each assignment and I create the cover page using LaTeX to make it pretty. Up until now, with `convert`, I've converted the cover page PDF to SVG with `pdf2svg` and then ran the `convert` program. Just today I've learned that `pdfcpu import` _appends_ to a file when the file already exists so knowing these can shorten and simplify my workflow. Didn't notice this fact before...

So thanks for helping me out :green_heart:  pdfcpu seems much more promising and elegantly built then `convert`! Speaking of elegance, I could never figure out what's up with the completion. I'm the [maintainer of pdfcpu in NixOS](https://github.com/NixOS/nixpkgs/pull/76974) and I would really like to get completion working somehow for us - `pdfcpu help` says there is completion but I couldn't find any other evidence for it.

**Comment by hhrutter** [comment]
Understood!

Please open a separate issue about pdfcpu command completion.
My response will be useful for other users as well.

**Comment by doronbehar** [comment]
So to summarize, pdfcpu can't really fix arbitrarily malformed PDF files - such as those I created with `convert`?

**Comment by hhrutter** [comment]
You are importing the pics one by one right? 
As I said you have to play around with scaling.
Go down with scaling a little bit, try .7, then maybe .6.. for the one that gets rendered too big.
Also try to see if setting dpi manually makes a difference.

As far as *repairing* files, see #136.
There is just too many ways a PDF may end up corrupt.
If you have a PDF that opens with Adobe Reader or Mac Preview but `pdfcpu validate`fails I am happy to look into it and this will over time make pdfcpu more robust.

What is your PDF Reader of choice under NixOS?
I need to integrate a Linux PDF Reader into my personal testsuite.

**Comment by doronbehar** [comment]
> What is your PDF Reader of choice under NixOS?
I need to integrate a Linux PDF Reader into my personal testsuite.

I use mostly [zathura](https://git.pwmt.org/pwmt/zathura). For the sake of clearance, the `convert` made PDFs which failed for Adobe Reader didn't fail for me under Linux's Firefox but they did fail under Window's Firefox! Also `pdfcpu validate` reported issues for these PDFs only with `-mode strict`.

I hope this helps.

> There is just too many ways a PDF may end up corrupt.
> If you have a PDF that opens with Adobe Reader or Mac Preview but pdfcpu validatefails I am happy to look into it and this will over time make pdfcpu more robust.

My case is inverted to this, so I think pdfcpu is acting fine according to this policy.

**Comment by hhrutter** [comment]
Strict validation mode doesn't get you far these days if you want to process existing PDFs.
That's also why pdfcpu internally defaults to `relaxed validation`.
Other than that 👍
