### ISSUE TITLE
CLI command completion explained

### ISSUE THREAD

**Issue by doronbehar** [pdfcpu/pdfcpu#156]
I'm the [maintainer of pdfcpu in NixOS](https://github.com/NixOS/nixpkgs/pull/76974) and I would really like to get completion working somehow for us - `pdfcpu help` says there is completion but I couldn't find any other evidence for it. Ref: https://github.com/pdfcpu/pdfcpu/issues/154

**Comment by hhrutter** [comment]
Hello!

Here is how pdfcpu's internal command completion works:
```
Go-> pdfcpu validate test.pdf
validating(mode=relaxed) test.pdf ...
validation ok

Go-> pdfcpu val test.pdf
validating(mode=relaxed) test.pdf ...
validation ok

Go-> pdfcpu v test.pdf
pdfcpu: ambiguous command "v"
Run 'pdfcpu help' for usage.

Go-> pdfcpu ve test.pdf
usage: pdfcpu version

Go-> pdfcpu ve
pdfcpu: v0.3.2 dev
```
If you are using commands that use subcommands like `stamp`:
```
Go-> pdfcpu stamp
usage: pdfcpu stamp add    [-v(erbose)|vv] [-q(uiet)] [-pages selectedPages] [-upw userpw] [-opw ownerpw] -mode text|image|pdf string|file description inFile [outFile]
       pdfcpu stamp remove [-v(erbose)|vv] [-q(uiet)] [-pages selectedPages] [-upw userpw] [-opw ownerpw] inFile [outFile]
       pdfcpu stamp update [-v(erbose)|vv] [-q(uiet)] [-pages selectedPages] [-upw userpw] [-opw ownerpw] -mode text|image|pdf string|file description inFile [outFile]
````
All of the following are equal:
```
pdfcpu stamp add -mode text -pages even Draft '' test.pdf
pdfcpu st add -mode text -pages even Draft '' test.pdf
pdfcpu st a -mode text -pages even Draft '' test.pdf
pdfcpu st a -m text -pages even Draft '' test.pdf
pdfcpu st a -m text -p even Draft '' test.pdf
```

For commands and subcommands pdfcpu consistently tries to identify command prefixes.
For flags the following is hardcoded:
* stats = s
* mode = m
* key = k
* units = u
* pages = p
* quiet = q
* verbose = v

**Comment by doronbehar** [comment]
I see! Then that's not completion, these are shortcuts :laughing:. By "Completion" I was sure you've meant shell tab completion.. @hhrutter Would you be interested in ZSH tab completion to be added to the project? I might not be able to do it right away (not until semester brake) but I'd love to contribute this to the project. `pdfcpu` has many sub commands and options it's hard to remember so I think shell tab completion should be very helpful.

**Comment by hhrutter** [comment]
Sure! That would be a great addition to pdfcpu! 🎉

**Comment by doronbehar** [comment]
Awesome! I've added that to my todo-list.

I'd like to suggest a small enhancement request on the matter never the less: To replace the usage of the word "completion" with perhaps "shortcut" all over the codebase because I think it's pretty misleading. I'll explain why: Many CLI programs these days have a builtin completion shell functions generation that goes somewhere like this, say in a `.zshrc`:

```zsh
# setup completion for programx
eval "$(programx completion)"
```

And having read about it in `pdfcpu help`, I was sure this goes somehow like this, or that there's a completion file I can manually download and put in my dotfiles in order to have shell-tab-completion.
Anyway, that was _my_ 1st guess. Hence I'd kindly advise to change the term :green_heart:.

**Comment by hhrutter** [comment]
I agree this can create confusion. I'll see to explain this better in `pdfcpu help`.
If we support tab-completion I hope we can do this for both `zsh` and `bash`.
