### ISSUE TITLE
GoReleaser build artifacts suggestion

### ISSUE THREAD

**Issue by jftuga** [pdfcpu/pdfcpu#157]
In your `.goreleaser.yaml`, you can add the following to create a .zip file for Windows only.

This is a snippet of what I use on my projects:

    archive:
      name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ .Arm }}"
      format: tar.gz
      format_overrides:
        - goos: windows
          format: zip
      replacements:
          darwin: macOS
      wrap_in_directory: true

Note that this also renames Darwin to MacOS.

Here is one of my full `.goreleaser` files, if you are interested:
https://github.com/jftuga/nics/blob/master/.goreleaser.yml

**Comment by hhrutter** [comment]
Thanks! Great suggestion! Goes into the next release  🎉
Thank you for using pdfcpu 💚
