### ISSUE TITLE
Merge out.pdf *.pdf potentially not working.

### ISSUE THREAD

**Issue by jpedlow** [pdfcpu/pdfcpu#158]
Hello,

pdfcpu: 0.3.2
build : 2020-01-04T09:13:53Z
commit: 623e0df
Winx86-64

It appears that the documented ability to merge all pdfs in a folder via (merge out.pdf *.pdf) does not, at a minimum, communicate well, and at worst not working at all.

Attempting a (-merge out.pdf *.pdf), the console outputs: "usage: pdfcpu merge [-v(erbose)|vv] [-q(uiet)] outFile inFile..."

No out.pdf exists afterwords, no worning, no completion etc.

**Comment by hhrutter** [comment]
Hello!

Please describe the usecase that causes you problems.
I am not sure I understand.

**Comment by jpedlow** [comment]
Hello!

I have ~150 pdf files in a folder, I would like to merge them all.
I understand PDFcpu can use the following syntax: pdfcpu merge out.pdf *.pdf
This does not work for me. No error. No out.pdf.

I am able to merge via directly named files (no wildcard): pdfcpu merge
out.pdf file1.pdf file2.pdf

I hope this helps clarify.

**Comment by hhrutter** [comment]
Please try:

`pdfcpu merge -vv out.pdf *.pdf`

This should give you at least a stacktrace which you can post here for follow up.

**Comment by hhrutter** [comment]
Hello!

Do you have anything stacktrace etc, to follow up on for analysis?
if not I am going close this.

**Comment by tiborepcek** [comment]
Same for me. I am suing `pdfcpu merge -vv out.pdf *.pdf` on Windows 10 (1909) via cmd.exe with this error:

`Fatal: open *.pdf: The filename, directory name, or volume label syntax is incorrect.`

**Comment by hhrutter** [comment]
I follow up with you on this on #199
