### ISSUE TITLE
Multistamp produces invalid files

### ISSUE THREAD

**Issue by xconstruct** [pdfcpu/pdfcpu#159]
Hi and thank you for implementing multi-stamp functionality so quickly.

We're running into an issue where applying multi-page PDF stamps results in a broken output that fails validation. Error messages are random even when re-running the command on the same input. This happens with different stamps and input PDFs, but only with the new multi-stamp behavior - i.e. limiting the input stamp to a single page still works as before.

[error.log](https://github.com/pdfcpu/pdfcpu/files/4090546/error.log)
[file.pdf](https://github.com/pdfcpu/pdfcpu/files/4090552/file.pdf)
[OptimizeTest.pdf](https://github.com/pdfcpu/pdfcpu/files/4090556/OptimizeTest.pdf)

```
pdfcpu watermark add -vv -mode pdf file.pdf 'rot:0, pos:tl, s:1 rel' OptimizeTest.pdf out.pdf 2> error.log

pdfcpu version
pdfcpu: 0.3.2
build : 2020-01-04T09:13:57Z
commit: 623e0df
```

**Comment by hhrutter** [comment]
Thanks for submitting this. I'll check it out.
