### ISSUE TITLE
OSX Preview permissions

### ISSUE THREAD

**Issue by flowchartsman** [pdfcpu/pdfcpu#161]
With a file encrypted like so:
```go
encConf := pdfcpu.NewAESConfiguration("", "password", 256)
encConf.Permissions = pdfcpu.PermissionsNone | (1 << 2) | (1 << 11)

if err := api.EncryptFile(inFile, outFile, encConf); err != nil {
	log.Fatalf("error encrypting file: %v", err)
}
```

Displaying the following info

```
$ ./pdfcpu info test_watermark.pdf
         PDF version: 1.7
          Page count: 4
           Page size: 612.00 x 792.00 points
............................................
               Title:
              Author:
             Subject:
        PDF Producer: pdfcpu v0.3.2 dev
     Content creator:
       Creation date: D:20200122171917+-5'00'
   Modification date: D:20200122171917+-5'00'
............................................
              Tagged: No
              Hybrid: No
          Linearized: No
  Using XRef streams: Yes
Using object streams: Yes
         Watermarked: Yes
............................................
           Encrypted: Yes
         Permissions:
permission bits: 100000000100
Bit  3: true (print(rev2), print quality(rev>=3))
Bit  4: false (modify other than controlled by bits 6,9,11)
Bit  5: false (extract(rev2), extract other than controlled by bit 10(rev>=3))
Bit  6: false (add or modify annotations)
Bit  9: false (fill in form fields(rev>=3)
Bit 10: false (extract(rev>=3))
Bit 11: false (modify(rev>=3))
Bit 12: true (print high-level(rev>=3))
```

I see the following in OSX Preview, by going to **Tools -> Show Inspector**:
<img width="366" alt="enc_preview_window" src="https://user-images.githubusercontent.com/926884/72940795-83196380-3d3d-11ea-8eae-81d0238ac175.png">

Unsure if this is expected behavior, but worth an issue if not.

**Comment by hhrutter** [comment]
Hi!

Other than a potential permission bits problem.
Are you saying that you can open this file without a password?

**Comment by flowchartsman** [comment]
No, it has no user password, only an owner password. I just assumed that with encryption, but without the copy bit set, it would disallow copying.

**Comment by hhrutter** [comment]
So the output of `pdfcpu info` clearly confirms which permission bits are set.
This corresponds to how you setup your permissions for this file as described above.
Honestly - I have no clue how to interpret Mac Preview's output: *You may copy from this PDF*

**Comment by hhrutter** [comment]
There is an optimized `permissions` command as part of https://github.com/pdfcpu/pdfcpu/releases/tag/v0.6.0

Dealing/setting the possible PDF permission bits is all pdfcpu is concerned.
As far as the semantics (which are not trivial) please refer to the PDF specification.
