### ISSUE TITLE
Split by Bookmarks

### ISSUE THREAD

**Issue by beeing** [pdfcpu/pdfcpu#164]
Hi, I would like to request for the above feature where a PDF can be split based on the bookmark and save to the filename with bookmark.pdf

Thanks.

**Comment by hhrutter** [comment]
Hello!

Please describe your specific use case.

Thank you for using pdfcpu 💚

**Comment by beeing** [comment]
For performance optimisation, I'm planning to generate a transactional PDF which consists of many parts in one file.

Each part is meant for different email recipient and usually starts in a new page.

The only issue is to able to split it so that it goes back to separate PDF files.

**Comment by hhrutter** [comment]
Sorry I still do not understand.
Boomarks is an optional PDF feature.
What do you mean by *splitting based on bookmark(s)?*

If you can provide a concrete sample pdf and tell us how you would like to split it up
we may be able to help you.

Thank you!

**Comment by beeing** [comment]
Hi, if you want, I can email a sample to show you. Thanks.

**Comment by hhrutter** [comment]
Great!
Please send your sample to: hhrutter@gmail.com

**Comment by hhrutter** [comment]
Got it!

How do you create your document outline/bookmarks?
Also with DXperience?

`pdfcpu validate` indeed fails with the error you mentioned.
This is a bug we have to fix first.

Other than that I think we can come up with a solution for your split strategy.
Stay tuned.

**Comment by beeing** [comment]
Yes, I create using their reporting tool. However there are many ways to create PDF reporting.

If pdfcpu support bookmark split, then it will be help alot on the efficiency for this process.

Thanks!

**Comment by hhrutter** [comment]
This feature is live with the latest commit!
Check `pdfcpu help split`

Sidenote:
Your PDF Writer is producing a broken trailer with an invalid size. 
pdfcpu is extended now so it digests these kind of errors.

**Comment by beeing** [comment]
Hi, just wondering is there a new release that comes with this feature?

Thanks.

**Comment by hhrutter** [comment]
Sure!
I am still working on a couple of improvements.
Once I am finished there will be a new release.
Meanwhile just go ahead and build pdfcpu from the latest commit in order to split by bookmarks.

**Comment by beeing** [comment]
Sure, thanks and looking forward for it.

**Comment by beeing** [comment]
Hi @hhrutter, I have a suggestion for a minor tweak on this feature.

When a PDF file have multiple pages with the same bookmark, it is split to separate files.

Right now, I need to call pdf merge to combine the files with same bookmark.

Instead of 2 commands, can the output be combined to a single PDF for same bookmark?

Thanks!

**Comment by hhrutter** [comment]
ok, we need to fix this.
can you provide a small sample file.
Thank you.

**Comment by beeing** [comment]
I've sent to your gmail. Thanks.

**Comment by mrvainv2** [comment]
Hi,

Today, I discovered this nice piece of software and played around with the functionality (tip of the iceberg) and I really liked it.

**Q1-** I have bookmarks in my pdf with slashes (date) which obviously are not allowed to be save in the directory. Is it possible to accommodate for these special characters and convert them to e.g. an underscore?

**Comment by hhrutter** [comment]
This would be something that is the responsibility of the caller.
Other than that I am ready to close this issue - any objections?

**Comment by beeing** [comment]
No objections, thanks @hhrutter
