### ISSUE TITLE
Read: xRefTable failed: EOF with file reader from a Minio server into api

### ISSUE THREAD

**Issue by mclark4386** [pdfcpu/pdfcpu#165]
So I have this code I'm trying to use to merge all my pdfs from a minio bucket into a single pdf to download. I started out just trying to merge, but was getting get this error from the merge, so after a little research I found the issues where you were asking for validations of the file. If I download the files and then run the validation it works perfectly, but when I try to validate each file as I get it I get the error below:

```
	letters := []io.ReadSeeker{}

	var outFile io.Writer = bytes.NewBuffer([]byte{})
	config := pdf.NewDefaultConfiguration()
	// config.ValidationMode = pdf.ValidationStrict

	for _, thing := range things {
		if obj, err := client.GetObject(bucket, thing.FilePath, minio.GetObjectOptions{}); err != nil {
			println("find objects error")
			return c.Error(http.StatusUnprocessableEntity, err)
		} else {
			letters = append(letters, obj)
			if err = api.Validate(obj, config); err != nil {
				fmt.Printf("obj err:%+v\n    %s\n", obj, err.Error())
				// return c.Error(http.StatusUnprocessableEntity, err)
			}
		}
	}
	// config.Eol = pdf.EolCR
	if err := api.Merge(letters, outFile, config); err != nil {
		println("merge error")
		return c.Error(http.StatusUnprocessableEntity, err)
	}
```

```
Read: xRefTable failed: EOF
obj err:&{mutex:0xc00051ee70 reqCh:0xc00089d500 resCh:0xc00089d560 doneCh:0xc00089d5c0 currOffset:18703 objectInfo:{ETag:c4fe8c25cc002f8af3cccce0cd363677 Key:7679e350-ba34-4cf6-b3ca-2c0a85e96bdf.pdf LastModified:{wall:0 ext:63716108853 loc:<nil>} Size:18703 ContentType:application/pdf Metadata:map[Strict-Transport-Security:[max-age=15552000; includeSubDomains; preload]] Owner:{DisplayName: ID:} StorageClass: Err:<nil>} seekData:false isClosed:false isStarted:true prevErr:0xc000032070 beenRead:true objectInfoSet:true}
```

Will be happy to try to help as much as possible, but since I can't give access to the bucket it'll probably have to be following your instructions for getting data to diagnose it^^; Thanks for the awesome util/lib!

**Comment by hhrutter** [comment]
Hi, interesting use case!

*api.Merge* already validates each file @ pre-merge and then also the result.
You can skip validation by passing in a configuration with ValidationMode = pdf.ValidationNone.

This is something that needs to be debugged.
Unfortunately I do not have a proper test environment available for Minio.

Have you ensured that you also get this error when you run a test without a loop?

Have you tried to get verbose log output with `log.SetDefaultLoggers()` or smth similar
to narrow this down?

**Comment by mclark4386** [comment]
I was doing the validate for debugging, because I wanted to know which files were the issue. Well, all of them apparently.

Are you suggesting I just send one file in and see if I get the same thing? I'm happy to make whatever changes to debug it, but am not sure what you are referring to with the verbose output with `log.SetDefaultLoggers()`!

Just let me know what steps you would like me to take and I'm happy to give it a go!

**Comment by hhrutter** [comment]
Hi,

I am pretty sure this is part of the problem:

pdfcpu's api.Validate expects a *io.ReadSeeker* whereas minio returns a *io.ReadCloser*:

MinIO:
`func (c Core) GetObject(bucketName, objectName string, opts GetObjectOptions) (io.ReadCloser, ObjectInfo, http.Header, error)`

pdfcpu:
`func Validate(rs io.ReadSeeker, conf *pdf.Configuration) error`

To work around this you have to obtain a *ReadSeeker*.
Maybe this helps: [How do I go from io.ReadCloser to io.ReadSeeker?](https://stackoverflow.com/questions/37718191/how-do-i-go-from-io-readcloser-to-io-readseeker)

**Comment by mclark4386** [comment]
For testing I'll grab it with `ioutil.ReadAll()`and load that into a `bytes.NewReader()` and see if that works. Thanks for the research either way!

**Comment by hhrutter** [comment]
Sure!

If you are dealing with bigger files I would recommend using `io.Copy` over `ioutil.ReadAll` because `io.Copy` uses a fixed size 32K buffer.

Let me know the solution you ended up with.
Cheers!

**Comment by mclark4386** [comment]
It should be a lot of smaller files. But that worked! Thanks so much for the help!
