### ISSUE TITLE
PDF size after splitting

### ISSUE THREAD

**Issue by yuthan** [pdfcpu/pdfcpu#167]
hi , 
i am having issue while split up the page from large PDF document approx 7500 pages . After that each page consist 299kb but the same generate as single pdf it can take 89kb . then i had used adobe pdf audit space tool  and come to know that fonts are taking up space (attached screenshot for your reference) . is that anyway to remove the font . 
![Untitled](https://user-images.githubusercontent.com/3508729/74598087-d6f34000-5090-11ea-88a8-512a6dee8b56.png)

**Comment by hhrutter** [comment]
This makes sense. For example when you have a PDF that is embedding 1 font file then after you split the file each resulting PDF file also needs to embed the font file.

If you can share a sample file I can inspect this problem for you. (post here or email to hhrutter@gmail.com) Maybe there is something going on that is new for pdfcpu regarding support of asian fonts.

Thank you for using pdfcpu 💚

**Comment by yuthan** [comment]
Thanks @hhrutter i will update the PDF here by today.

**Comment by yuthan** [comment]
hi @hhrutter  thanks for the immediate response for my issue . i have resolved the issue by splitting the pdf at the stream level instead of after generating.
