### ISSUE TITLE
validate: Digest non standard named action

### ISSUE THREAD

**Issue by wedi** [pdfcpu/pdfcpu#170]
Trying to rotate a PDF file I get this fatal error message:  

```
$ pdfcpu rotate test2.pdf 180
writing test2.pdf...
pdfcpu: validateNameEntry: dict=Named entry=N invalid dict entry: Print

$ pdfcpu version
pdfcpu: 0.3.2
```

Here's the bug report following https://github.com/pdfcpu/pdfcpu/issues/136#issuecomment-559740523.

`pdfcpu validate -vv test2.pdf &> crash.log`: [crash.log](https://github.com/pdfcpu/pdfcpu/files/4289877/crash.log), this is [the PDF file](https://media.essen.de/media/wwwessende/aemter/33/EidesstattlicheVersicherung_2018.pdf).

**Comment by hhrutter** [comment]
Thanks for reporting this!
