### ISSUE TITLE
CLI install instructions

### ISSUE THREAD

**Issue by QuLogic** [pdfcpu/pdfcpu#172]
I know I can just go to Releases, or `go get` things, but I'm having a hard time finding any install instructions on pdfcpu.io.

**Comment by hhrutter** [comment]
Hi!
Right now, there is not really anything to do other than *go get*.
See the *Install* section [here](https://github.com/pdfcpu/pdfcpu)

**Comment by QuLogic** [comment]
I know how to install, the point is it's not anywhere on pdfcpu.io.

**Comment by hhrutter** [comment]
Great!!

pdfcpu.io is on the gh-pages branch.
Happy to accept anything you can contribute.

Thanks for using pdfcpu 💚
