### ISSUE TITLE
api.ImportImagesFile() does not seem to properly close resource.

### ISSUE THREAD

**Issue by ibrahimnoorz** [pdfcpu/pdfcpu#174]
I have a use case where I create temporary images and then import them into a target pdf file using pdfcpu's **api.ImportImagesFile())**. 
After successful import, I delete the temporary images. I noticed that pdfcpu seems to hold on to the opened files longer than needed. 

While debugging, I came up with the following temporary fix. In the api.ImportImagesFile() function, I have modified the defer block as below:

```
defer func() {
	for _, f := range rc {
		//not returning on error because we need to close the remaining resources
		if err := f.Close(); err != nil {
			//return
		}
	}

	if err != nil {
		f2.Close()
		if f1 != nil {
			f1.Close()
			os.Remove(tmpFile)
		}
		return
	}

	if err = f2.Close(); err != nil {
		return
	}
	if f1 != nil {
		if err = f1.Close(); err != nil {
			return
		}
		if err = os.Rename(tmpFile, outFile); err != nil {
			return
		}
	}
}()
```

**Comment by hhrutter** [comment]
Hi!

You may be right.
Many thanks for reporting this!
