### ISSUE TITLE
unknown PDF Root version: 1#2E5

### ISSUE THREAD

**Issue by mtzanidakis** [pdfcpu/pdfcpu#175]
Hello,
we have a pdf with a weird root version.

```
$ pdfcpu version
pdfcpu: v0.3.2 dev

$ pdfcpu info version_error.pdf
identifyRootVersion: unknown PDF Root version: 1#2E5
: 1#2E5
```

With something like that:
```
diff --git a/pkg/pdfcpu/version.go b/pkg/pdfcpu/version.go
index d666e4c..211ec9c 100644
--- a/pkg/pdfcpu/version.go
+++ b/pkg/pdfcpu/version.go
@@ -54,7 +54,7 @@ func PDFVersion(versionStr string) (Version, error) {
                return V13, nil
        case "1.4":
                return V14, nil
-       case "1.5":
+       case "1.5", "1#2E5":
                return V15, nil
        case "1.6":
                return V16, nil
```

it works.

The [pdf in question](https://drive.google.com/file/d/1IBHNnnXSfZe-cStYLiXvTuHu0mTPyczG/view?usp=sharing)

Thanks in advance

**Comment by hhrutter** [comment]
Thanks for reporting this!

**Comment by hhrutter** [comment]
Fixed with [v0.3.3](https://github.com/pdfcpu/pdfcpu/releases)

**Comment by thorsted** [comment]
Curious if this issue was fixed to ignore the Catalog version entry as it is an optional key or should it still be flagged as a validation error?

**Comment by hhrutter** [comment]
I don't know if this answers your question but
the optional `Version` entry in the catalog cannot be ignored since its intention is to override the header version.
