### ISSUE TITLE
Getting Error: go: github.com/hhrutter/pdfcpu@v0.3.2: parsing go.mod: unexpected module path "github.com/pdfcpu/pdfcpu" 

### ISSUE THREAD

**Issue by kishannigamkb** [pdfcpu/pdfcpu#176]
Go build is failing due to this:

go: github.com/hhrutter/pdfcpu@v0.3.2: parsing go.mod: unexpected module path "github.com/pdfcpu/pdfcpu"
go: error loading module requirements

I tried doing go get -u github.com/pdfcpu/pdfcpu, results(no error):

$ go get -u github.com/pdfcpu/pdfcpu
go: finding github.com/hhrutter/lzw latest
go: finding github.com/hhrutter/tiff latest
go: finding golang.org/x/image latest
go: finding golang.org/x/tools latest
go: finding golang.org/x/xerrors latest
go: finding golang.org/x/sync latest
go: finding golang.org/x/sys latest
go: finding golang.org/x/crypto latest
go: finding golang.org/x/net latest
$

But even after this go build fails with same error as described above. Any help would be great! :)

**Comment by hhrutter** [comment]
Which version are you on?
`go version`

**Comment by kishannigamkb** [comment]
@hhrutter $ go version
go version go1.11.1 linux/amd64

**Comment by kishannigamkb** [comment]
Update:

I updated my go version to 1.13

$ go version
go version go1.13.4 linux/amd64

But now on go build error is slightly different but i guess root cause is same:

github.com/hhrutter/pdfcpu/pkg/api: github.com/hhrutter/pdfcpu@v0.3.2: parsing go.mod:
        module declares its path as: github.com/pdfcpu/pdfcpu
                but was required as: github.com/hhrutter/pdfcpu

**Comment by hhrutter** [comment]
Please see #178 how to build using the latest commit.
Maybe this helps.
You also may want to try a `go mod tidy` before.
