### ISSUE TITLE
The pkg.go.dev pdfcpu package isn't up to date

### ISSUE THREAD

**Issue by Cedric-Caballol-Shepy** [pdfcpu/pdfcpu#178]
Hello,

Thank you for the tool.

I wanted to use the function `MergeCreateFile` added in answer to #149  but it seems that the repository isn't up to date (https://pkg.go.dev/github.com/pdfcpu/pdfcpu@v0.3.2/pkg/api is from January 4). 
Is it possible to update this to make the `go get` command getting the latest version ?

Thanks in advance for your help.

**Comment by Cedric-Caballol-Shepy** [comment]
I didn't know that I could refer to commits in go mod (adding `github.com/pdfcpu/pdfcpu v0.3.3-0.20200216094053-6d5c8c050379` to the depencies worked).
Nevermind, sorry for the inconvenance !

**Comment by hhrutter** [comment]
You are welcome!

Thanks for using pdfcpu 💚
