### ISSUE TITLE
DecodeUTF16String: UTF16 needs even number of bytes

### ISSUE THREAD

**Issue by ekulabuhov** [pdfcpu/pdfcpu#179]
Hey! I'm using pdfcpu version 0.3.2. I saw this error message when trying to merge two PDF documents together:

> DecodeUTF16String: UTF16 needs even number of bytes: [77 105 99 114 111 115 111 102 116 174 32 79 102 102 105 99 101 32 87 111 114 100 32 50 48 48 55]

This is the PDF document causing it:
[Factoring agreement_en.pdf](https://github.com/pdfcpu/pdfcpu/files/4476307/Factoring.agreement_en.pdf)

This is the stack:
<img width="727" alt="Screen Shot 2020-04-13 at 10 15 53 PM" src="https://user-images.githubusercontent.com/4452263/79245215-64dd8280-7eaa-11ea-9994-c7163f12d357.png">

Crash log:
[crash.log](https://github.com/pdfcpu/pdfcpu/files/4476656/crash.log)

Is it something important that prevents the merge from completing or can it be bypassed?

Thanks!

**Comment by hhrutter** [comment]
Thanks for reporting this!
I'll get back to you.

**Comment by hhrutter** [comment]
Hello!

This was fixed with #155.
Please build using the latest commit and you should be fine.
This will also be in the next release but I cannot commit to a release date at this time.

Thank you for your patience!

**Comment by ekulabuhov** [comment]
Thank you, Horst! Will check it out with the latest version.
