### ISSUE TITLE
pdfcpu: validateFontFile3SubType: FontFile3 missing Subtype "Type1C"

### ISSUE THREAD

**Issue by ekulabuhov** [pdfcpu/pdfcpu#180]
Getting this error during a validation. Judging by the Creator field, the file in question was produced by WebKit.

Could I send the PDF file to your email?

The crash log:
[crash.log](https://github.com/pdfcpu/pdfcpu/files/4476601/crash.log)

Thank you for the library!

**Comment by hhrutter** [comment]
Yes, send it over and I take a look.

Thanks for using pdfcpu 💚
