### ISSUE TITLE
AWS Lambda Support

### ISSUE THREAD

**Issue by rnewton** [pdfcpu/pdfcpu#186]
Hello! I've been using pdfcpu v0.2.5 happily for a while to add an image watermark to PDFs as they are provided to me. I've got it deployed to AWS Lambda currently under v0.2.5, but I was running into some unrelated dictionary issues. On a whim, I decided to update to v0.3.2 to see if the issue was fixed. Locally, it was, but the lambda handler no longer runs. I get `Failed access to font dir: neither $XDG_CONFIG_HOME nor $HOME are defined`, which makes sense because the home directory isn't exactly a concept in lambda functions. After digging into the code a bit, I noticed a more recent refactor to setup a font cache in the home directory when running the pdfcpu command (`pkg/font/metrics.go:init`).

Before I dig into trying to solve this problem, I wanted to ask if aws lambda was supported or could be supported.

**Comment by rnewton** [comment]
Workaround for anyone who needs this is to set `HOME` env to `/tmp` in lambda settings.

**Comment by hhrutter** [comment]
Hello!

I am not familiar with AWS Lambda but I can imagine that the location of pdfcpu's fontdir may cause an issue. I am contemplating making it configurable.

In any case if you do have a workaround, maybe you can write up a little tutorial on how to get up and running with pdfcpu on AWS Lambda and I will happily link to it from pdfcpu's ReadMe and pdfcpu.io.

Thank you for using pdfcpu 💚

**Comment by jftuga** [comment]
@hhrutter 

Could you set `HOME` to `/tmp` in the code, if the `HOME` environment variable is not set / defined?

@rnewton 

Do you think this would solve the problem?

**Comment by rnewton** [comment]
I'm not sure it's necessary to make any changes in the code, but a fallback may be nice. Setting `HOME` to `/tmp` is working nicely.
