### ISSUE TITLE
optimize: improved xreftable clean up

### ISSUE THREAD

**Issue by hos** [pdfcpu/pdfcpu#187]
I have a PDF which contains useless information which I want to remove. Using Reduce file size in Adobe Acrobat DC I was able to remove that information using only `discard private data of other applications` checkbox PDF Optimizer. When I run Optimize it don't remove that data though when I run n-up extra data is removed. Workaround could be probably to create new PDF by only importing pages without any information, but I think this is something that will be nice if Optimize will do.

If this feature is out of scope of this package, is there any recommended way to get rid of that data using this package?

**Comment by hhrutter** [comment]
`pdfcpu nup` creates a new file from scratch so it makes sense that all redundant info is gone
whereas `pdfcpu optimize` retains the original cross reference table after applying optimization.
So yes if you can share a sample PDF we can extend optimization for this purpose.

Thank you for using pdfcpu 💚

**Comment by hos** [comment]
[original.pdf](https://github.com/pdfcpu/pdfcpu/files/4623524/original.pdf) 788K
[opt.pdf](https://github.com/pdfcpu/pdfcpu/files/4623523/opt.pdf) 777K (optimized with pdfcpu)
[opt-acrobat.pdf](https://github.com/pdfcpu/pdfcpu/files/4623522/opt-acrobat.pdf) 215K (optimized with acrobat dc)
[nup.pdf](https://github.com/pdfcpu/pdfcpu/files/4623521/nup.pdf) 233K (resampled with nup)

Hope this files are enough.

Thank you for your help, great work and being nice. 🙏🧡
