### ISSUE TITLE
merge: input parameter validation

### ISSUE THREAD

**Issue by doronbehar** [pdfcpu/pdfcpu#188]
So today I encountered a small UX issue I was wondering what would be your opinion:

I wanted to run this command:

```
pdfcpu merge physics2p-hw4.pdf physics2p-cover.pdf physics2p-hw4.pdf
```

But it failed with:

```
Read: xRefTable failed: pdfcpu: can't find last xref section
```

Which puzzled me because I never had reading issues from pdfcpu with the PDFs generated by my scanner. But, then I realized, that `pdfcpu` wasn't aware that it's reading the same file it will attend to write to - the file `physics2p-hw4.pdf` was empty because it was the output file and because of that `pdfcpu` failed to read it.

This error led me to re-scan that hw assignment (No big deal though :)).

Perhaps a warning should be printed when such colliding arguments are given? Or even better - what if pdfcpu will ask the user whether to delete or move the original file it operated on?

**Comment by hhrutter** [comment]
HI!

Yes, better checking the input parameters for `pdfcpu merge` makes s lot of sense.
I put that down as an enhancement.

**Comment by doronbehar** [comment]
Cool.

I think there are more sub commands that may need this check, e.g:
`collect`, `trim`
