### ISSUE TITLE
Export method encodeStream in pkg/pdfcpu/filter.go

### ISSUE THREAD

**Issue by raff** [pdfcpu/pdfcpu#190]
I am implementing basic form filling (I actually have something working) but in order to create the appropriate "appearance" of filled stream I need to create a stream object. I can do everything with the current API, but doing the "encodeStream" (I am basically doing this: https://github.com/pdfcpu/pdfcpu/blob/master/pkg/pdfcpu/stamp.go#L1493-L1514)

Also, I know you are planning to add form filling, if you have an idea of what kind of API you'd like to expose, I can probably open a PR.

**Comment by hhrutter** [comment]
Hi there!
Please see my comment @ #124

**Comment by raff** [comment]
That's fine. In the mean time, would you consider exporting encodeStream so I don't have to fork the project just for that ?

**Comment by hhrutter** [comment]
😞 `pdfcpu.encodeStream` alone does not get you very far plus it is an intrinsic part of pdfcpu that is not supposed to be exported. If you can't wait there is no way around forking.

**Comment by raff** [comment]
As I said I can do what I need with just that (I only need to add/replace
the appearance stream for filled fields). But if you are not comfortable
exporting it, that's fine.
