### ISSUE TITLE
optimize: handle recursive resource dict structures

### ISSUE THREAD

**Issue by akkuman** [pdfcpu/pdfcpu#192]
https://github.com/pdfcpu/pdfcpu/blob/master/pkg/pdfcpu/optimize.go#L524

[test pdf](https://github.com/pdfcpu/pdfcpu/files/4539746/asd.pdf)

similar to https://github.com/pdfcpu/pdfcpu/issues/185

**Comment by hhrutter** [comment]
Thanks for reporting this.
I fix this asap.
