### ISSUE TITLE
validateArrayEntry: dict=Highlight entry=QuadPoints invalid dict entry

### ISSUE THREAD

**Issue by StefanSchroeder** [pdfcpu/pdfcpu#194]
When parsing a PDF file with api.ReadContextFile the fatal error
validateArrayEntry: dict=Highlight entry=QuadPoints invalid dict entry
is printed, although this seems to be a reasonably valid PDF.

**Comment by hhrutter** [comment]
Hello!

Happy to look into this.
Can you share a stracktrace or even better a sample?

**Comment by StefanSchroeder** [comment]
sure. I need to strip some confidential parts, though; but I'll make sure that the error persists.

**Comment by StefanSchroeder** [comment]
[error06.pdf](https://github.com/pdfcpu/pdfcpu/files/4702516/error06.pdf)
There you go.
