### ISSUE TITLE
watermark: handle absolute Windows filenames for PDF watermarks

### ISSUE THREAD

**Issue by Blesmol** [pdfcpu/pdfcpu#195]
It seems that on windows it is not possible providing an absolute file path to ``ParsePDFWatermarkDetails()``. Most likely because of the colon included in the drive letter.

```
stampFile := "stamp.pdf"  // Works
stampFile = "C:\\my_project\\stamp.pdf" // Same file, does not work
fmt.Printf("Stamp is located at %v\n", stampFile)

wm, err := pdfcpu.ParsePDFWatermarkDetails(stampFile, "rot:0, sc:1", true)
if err != nil {
  panic(err)
}
```

Error is "C is not a PDF file".

Any way to overcome this while keeping the file in its location? Relative path is not always an option, as that only works while staying on the same drive.

**Comment by hhrutter** [comment]
Hello and thanks for reporting this!

Could you provide your output or the corresponding stacktrace?

**Comment by Blesmol** [comment]
Great, thanks Horst! Also, of course, for pdfcpu in general, great work!
