### ISSUE TITLE
api: Use without importing pdfcpu/pkg/pdfcpu

### ISSUE THREAD

**Issue by Blesmol** [pdfcpu/pdfcpu#196]
Hi,

For using the watermark-related functions from the API, like ``AddWatermarksFile()``, it is required to have an object of type ``Watermark`` which, as far as I can see, cannot be constructed with API functionality, but only with functionality from the pdfcpu pkg like, e.g., the ``ParseTextWatermarkDetails()`` function. Wouldn't it be better if the API was self-contained, i.e. would not require to include the pdfcpu pkg as well?

See also the [``AddWatermarkDetails()`` example](https://godoc.org/github.com/hhrutter/pdfcpu/pkg/api#ex-AddWatermarksFile).

**Comment by hhrutter** [comment]
Valid point!

That needs to be adressed across the whole api.

As far as watermarks/stamps I am thinking of smth like:
```
func AddWatermarksFile(inFile, outFile string,
                       selectedPages []string, 
                       mode wmMode,   // (text,image,pdf)
                       parameter string, // text, image filename, pdf filename
                       descriptor string, // eg. "rot:0, sc:.3 rel"
                       onTop bool,
                       conf *pdf.Configuration) (err error)
```

**Comment by Blesmol** [comment]
So this would then combine the two existing calls into a single one? Looks good from my perspective!

What I do not know is whether people out there are currently using ``Watermark`` objects multiple times on different PDF objects. In such a case the objects would be recreated every time now. But honestly, reusing ``Watermark`` objects that way could also be a hypothetical use-case...

I assume the ``wmMode`` type from the proposal would then also be included in the API?

**Comment by hhrutter** [comment]
For now I am just contemplating..

We could also have:
```
func AddTextWatermarksFile(inFile, outFile string, selectedPages []string, onTop bool, text, desc string)
func AddImageWatermarksFile(inFile, outFile string, selectedPages []string, onTop bool, fileName, desc string)
func AddPDFWatermarksFile(inFile, outFile string, selectedPages[]string, onTop bool, fileName, desc string)

func UpdateTextWatermarksFile(inFile, outFile string, selectedPages []string, onTop bool, text, desc string)
func UpdateImageWatermarksFile(inFile, outFile string, selectedPages []string, onTop bool, fileName, desc string)
func UpdatePDFWatermarksFile(inFile, outFile string, selectedPages[]string, onTop bool, fileName, desc string)


```
