### ISSUE TITLE
api: New function GetPermissions() to allow programmatically checking PDF permissions

### ISSUE THREAD

**Issue by Blesmol** [pdfcpu/pdfcpu#197]
Hi,

I wanted to ask whether it would be possible to add functions like ``GetPermissions(...)`` and ``GetPermissionsFile(...)`` to the API.

Signatures would for example be as follows:
```
func GetPermissions(rs io.ReadSeeker, conf *pdf.Configuration) (int16, error) { ... }
func GetPermissionsFile(infile string, conf *pdf.Configuration) (int16, error) { ... }
```

The current functionality from ``ListPermissions()`` does exactly what its name says, it lists the permissions on the file as strings. But this also means that it is hard to use this functionality to programmatically check which of the PDF permission bits are set, although that information is already available internally. With ``ListPermissions()`` this would mean one hast to check whether the first returned string contains the text "Full access" or the "Permission Bits: 010101010101" part, and in the second case, parse that information again and then extract the required bit.

**Comment by hhrutter** [comment]
Hello!

Yes, returning the current permission bits seems useful.

Thanks for using pdfcpu 💚

**Comment by Blesmol** [comment]
Finally came to use the new API... looks good and works like expected, thanks!
