### ISSUE TITLE
watermark: scaleFontSize panic

### ISSUE THREAD

**Issue by appiteasy** [pdfcpu/pdfcpu#198]
Hi, I just recompiled with the latest release and get a crash in pdfcpy.scaleFontSize .
I reinstalled with the previous release and it works fine.
I am using the AddWmText function.
Any idea of what I should do or what has changed for using this function?
Thanks for your help,,
below is the stack trace.
Best regards,
Thierry

panic(0xdfae60, 0x186bf80)
        /usr/local/go/src/runtime/panic.go:969 +0x166
github.com/pdfcpu/pdfcpu/pkg/pdfcpu.scaleFontSize(0xc00063ab38, 0xc00059e3d0, 0x0, 0x0, 0x0, 0x3feccccccccccccd, 0x0, 0x0, 0x0, 0x0, ...)
        /go/src/github.com/pdfcpu/pdfcpu/pkg/pdfcpu/create.go:491 +0x12a
github.com/pdfcpu/pdfcpu/pkg/pdfcpu.createBoundingBoxForColumn(0xc00063ab38, 0xc00059e400, 0xc00059e3e8, 0x1, 0x3, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /go/src/github.com/pdfcpu/pdfcpu/pkg/pdfcpu/create.go:564 +0x4dc
github.com/pdfcpu/pdfcpu/pkg/pdfcpu.WriteColumn(0xc0006bbf20, 0xc00063ab38, 0x0, 0x0, 0x0, 0xf2221e, 0x9, 0xf1aebc, 0x2, 0x48, ...)
        /go/src/github.com/pdfcpu/pdfcpu/pkg/pdfcpu/create.go:736 +0x5d4
github.com/pdfcpu/pdfcpu/pkg/pdfcpu.WriteMultiLine(...)
        /go/src/github.com/pdfcpu/pdfcpu/pkg/pdfcpu/create.go:775
github.com/pdfcpu/pdfcpu/pkg/pdfcpu.createForm(0xc00031a6e0, 0xb, 0xc000698820, 0xc000c49e00, 0x0, 0x0)
        /go/src/github.com/pdfcpu/pdfcpu/pkg/pdfcpu/stamp.go:1936 +0xcbf
github.com/pdfcpu/pdfcpu/pkg/pdfcpu.addPageWatermark(0xc00031a6e0, 0xb, 0xc000698820, 0x0, 0xd8d960)
        /go/src/github.com/pdfcpu/pdfcpu/pkg/pdfcpu/stamp.go:2219 +0x159
github.com/pdfcpu/pdfcpu/pkg/pdfcpu.AddWatermarks(0xc000670ba0, 0xc0006bbe60, 0xc000698820, 0x0, 0x1c2089f301)
        /go/src/github.com/pdfcpu/pdfcpu/pkg/pdfcpu/stamp.go:2318 +0x28e
github.com/pdfcpu/pdfcpu/pkg/api.AddWatermarks(0x1137d20, 0xc000011218, 0x112f960, 0xc000011220, 0x0, 0x0, 0x0, 0xc000698820, 0xc0007405a0, 0x30, ...)
        /go/src/github.com/pdfcpu/pdfcpu/pkg/api/api.go:994 +0x1d8
github.com/pdfcpu/pdfcpu/pkg/api.AddWatermarksFile(0xc00077e1e0, 0x25, 0xc00077e1e0, 0x25, 0x0, 0x0, 0x0, 0xc000698820, 0x0, 0x0, ...)
        /go/src/github.com/pdfcpu/pdfcpu/pkg/api/api.go:1059 +0x325
main.AddWmText(0xc00077e1e0, 0x25, 0xc00077e1e0, 0x25, 0x0, 0x0, 0xf2d7d2, 0x12, 0x0, 0x4, ...)

**Comment by hhrutter** [comment]
Hello!

Can you post the details of your watermark?

Thanks for reporting this!

**Comment by appiteasy** [comment]
Hi, I am using either one line like 'confidential' or 2 lines: first line is 'confidential' , second line is "Name FirstName". I am also using an optional watermark background image. The background image always works. Only adding even watermark text with one line cause the problem. I am forcing now to use the previous release (v0.3.2) and it works fine.
This is my function using api.AddWatermarksFile:
func AddWmText(inFile string, outFile string, lineOne string, lineTwo string, conf *pdf.Configuration) error {
	var err error
	var txtArr []string

	if len(lineOne) > 0 && len(lineTwo) > 0 {
		txtArr = make([]string, 2)
		txtArr[0] = lineOne
		txtArr[1] = lineTwo
	} else if len(lineOne) > 0 {
		txtArr = make([]string, 1)
		txtArr[0] = lineOne
	} else if len(lineTwo) > 0 {
		txtArr = make([]string, 1)
		txtArr[0] = lineTwo
	}
	wm := pdfcpu.DefaultWatermarkConfig()
	wm.TextLines = txtArr
	wm.OnTop = true
	wm.Opacity = 0.4
	wm.FontSize = 72
	wm.Scale = 0.9
	//  err = AddWatermarksFile(inputPdfFileName, ouputPdfFileName , selectedPages []string, wm *pdf.Watermark, conf *pdf.Configuration)
	fmt.Println("after add watermarksFile ")
	err = api.AddWatermarksFile(inFile, outFile, nil, wm, conf)
	fmt.Println("after add watermarksFile err:", err)
	return err
}

**Comment by hhrutter** [comment]
Hi! 

You are supposed to call `pdf.ParseTextWatermarkDetails(text, descr, onTop)`
Like in the [stamp tests](https://github.com/pdfcpu/pdfcpu/blob/master/pkg/api/test/stamp_test.go).
Please try that out and let me know if it works for you.

Using the watermark command from the api is known to be cumbersome.
This will be streamlined. Have a look at #196

**Comment by appiteasy** [comment]
Thank you very much for your help and for such a quick follow up,
 I will try that. 
Best regards

**Comment by appiteasy** [comment]
Hi Horst,

Thank you for your support.

Everything is working well now with the latest release.

 

I have another question:
Is it possible to replace an Image with a stamp (vs removing and adding)?

When removing, we do not have information of where this image was (bounding box)  in the document.
I would like to generate a content dynamically, either with text (or watermark done with text would work as well).
Typically, a contract of an employee, I want to fill it with the employee specific data. Text replacement would be great of course (but complicated in pdf…).

I could also put image tags in the document and replace them with watermark text…

Any idea to do such a thing with pdfcpu?

 

Again thank you for your responsive support

Best regards,

Thierry



 

De : Horst Rutter <notifications@github.com> 
Envoyé : lundi 8 juin 2020 12:29
À : pdfcpu/pdfcpu <pdfcpu@noreply.github.com>
Cc : appiteasy <th@appiteasy.com>; Author <author@noreply.github.com>
Objet : Re: [pdfcpu/pdfcpu] watermark: scaleFontSize panic (#198)

 

Hi!

You are supposed to call pdf.ParseTextWatermarkDetails(text, descr, onTop)
Like in the stamp tests <https://github.com/pdfcpu/pdfcpu/blob/master/pkg/api/test/stamp_test.go> .
Please try that out and let me know if it works for you.

Using the watermark command from the api is known to be cumbersome.
This will be streamlined. Have a look at #196 <https://github.com/pdfcpu/pdfcpu/issues/196>

**Comment by hhrutter** [comment]
I am not sure I understand your requirement. 
You can update the watermark of a page by `pdfcpu stamp update ... ` on the command line or using the `Update` flag in the Watermark struct if you are using the api.

This is off topic so am going to close this issue.
If you want to follow up please open a separate issue.

Thank you for using pdfcpu 💚
