### ISSUE TITLE
merge: (Win10) wildcard merging not working

### ISSUE THREAD

**Issue by tiborepcek** [pdfcpu/pdfcpu#199]
I am using `pdfcpu merge -vv out.pdf *.pdf` on Windows 10 (1909) via cmd.exe with this error:

`Fatal: open *.pdf: The filename, directory name, or volume label syntax is incorrect.`

But `pdfcpu merge out.pdf file1.pdf file2.pdf file3.pdf` works.

Any help, please?

Thank you.

**Comment by hhrutter** [comment]
Hello!

I am happy to look into this.

Which pdfcpu release are you on?
Please execute `pdfcpu version`

Thanks for reporting this!

**Comment by tiborepcek** [comment]
pdfcpu: 0.3.3
build : 2020-05-25T13:07:33Z
commit: 4a9adac

**Comment by hhrutter** [comment]
Fixed with [v0.3.4](https://github.com/pdfcpu/pdfcpu/releases/tag/v0.3.4).

**Comment by tiborepcek** [comment]
> Fixed with [v0.3.4](https://github.com/pdfcpu/pdfcpu/releases/tag/v0.3.4).

I do not see version for Windows. Am i missing something? Thanks.

**Comment by hhrutter** [comment]
You are right!
Win execs are missing.
Something happened with the release.
I'll look into it.

**Comment by hhrutter** [comment]
Good to go!
Let me know if you keep having problems!
