### ISSUE TITLE
attach: multiple files attached leads to validateNameTreeDictLimitsEntry: leaf node corrupted

### ISSUE THREAD

**Issue by KopiasCsaba** [pdfcpu/pdfcpu#201]
Hello!

First of all, thank you very much for this software, we are very happy for it.

We found a bug related to attachment handling, please let me explain it.

### Symptomps:
Attaching many files results in a strange pdf file. Adobe acrobat reader is unable to open/save some of the attachments.
Other pdf readers (Okular, Foxit) can extract those attachments, but not acrobat.

### Other weirdness
1:
pdfcpu list says (to the same pdf it created) this:
`pdfcpu: validateNameTreeDictLimitsEntry: leaf node corrupted`

2:
Attaching the same files to the same pdf results in pdfs with different file sizes. 

### Details
All the files (input and out) are here:

[gl.zip](https://github.com/pdfcpu/pdfcpu/files/4824244/gl.zip)

Command history:
```bash
pdfcpu version
pdfcpu: 0.3.3
build : 2020-05-25T13:07:35Z
commit: 4a9adac


# Attaching files...
$ cp orig.pdf attached.pdf
$ pdfcpu attachment add attached.pdf files/*

$ cp orig.pdf attached2.pdf
$ pdfcpu attachment add attached2.pdf files/*

$ cp orig.pdf attached3.pdf
$ pdfcpu attachment add attached3.pdf files/*



$ ls -l
-rw-rw-r-- 1 csaba csaba 122224 jún   24 10:29 attached2.pdf
-rw-rw-r-- 1 csaba csaba 122214 jún   24 10:30 attached3.pdf
-rw-rw-r-- 1 csaba csaba 122221 jún   24 10:27 attached.pdf
#  ^^^ different sizes!

# Validation issue:
$ pdfcpu attachment list attached.pdf 
pdfcpu: validateNameTreeDictLimitsEntry: leaf node corrupted

$ pdfcpu attachment list attached2.pdf 
pdfcpu: validateNameTreeDictLimitsEntry: leaf node corrupted

$ pdfcpu attachment list attached3.pdf 
pdfcpu: validateNameTreeDictLimitsEntry: leaf node corrupted

```

And this is a screencapture of how acrobat handles this:
[vokoscreen-2020-06-24_10-49-20.zip](https://github.com/pdfcpu/pdfcpu/files/4824207/vokoscreen-2020-06-24_10-49-20.zip)

I've tried it with an acrobat reader dc from 2018, and that had the same problem.
Also this might be in pdfcpu for a long time, as it was there even before the attachment/portfolio distinction, we have files that were created with the older version and this happens there too.

Thank you very much for checking out what could be the problem here!

Best regards,
Kopiás Csaba

**Comment by hhrutter** [comment]
Thanks for reporting this.
I take a look.

**Comment by hhrutter** [comment]
The 3 files you use for your size test (attach.pdf, attach2.pdf, attach3.pdf) are all identical?
Especially when processing PDFs of unknown nature/origin please always make sure the can be validated by pdfcpu:
`pdfcpu val foreign.pdf``

My guess is in this case the original file already does not validate and returns the `leaf node corrupted`error.

**Comment by KopiasCsaba** [comment]
Hi!

Yes they are all identical, they were made with cp from orig.pdf & pdfcpu attachment add!

```
$ pdfcpu val orig.pdf 
validating(mode=relaxed) orig.pdf ...
validation ok
```
Orig.pdf is just a pdf i created with libreoffice, nothing special.

You can see it for yourself in the attachment, but i think you can recreate this with your own pdf too!

**Comment by KopiasCsaba** [comment]
(all those files are in the zip file i have attached by the way)

**Comment by hhrutter** [comment]
Attaching file works like:
`pdfcpu attachments add     [-v(erbose)|vv] [-q(uiet)] [-upw userpw] [-opw ownerpw] inFile file...`

I understand you were attaching orig.pdf in a loop 20 times to what?
Which is your inFile?

**Comment by KopiasCsaba** [comment]
I just attached the same file to itself, so almost yes, so all the files are the orig.pdf's copies.

```
$ cp orig.pdf attached.pdf
$ pdfcpu attachment add attached.pdf files/*
```
(where files/* will be orig.pdf's 20 copy)

**Comment by hhrutter** [comment]
ok. I reproduced this!

**Comment by tballison** [comment]
Many thanks for the test file! https://issues.apache.org/jira/browse/TIKA-3332
