### ISSUE TITLE
attach: Do not store absolute paths

### ISSUE THREAD

**Issue by KopiasCsaba** [pdfcpu/pdfcpu#202]
Dear Developer(s)!

When adding an attachment, the full original path is stored in the pdf file.

E.g. doing this:
```bash
pdfcpu attachment add /data/home/csaba/work/fpr/issues/1010/test/gl/gl2/orig.pdf /data/home/csaba/work/fpr/issues/1010/test/gl/gl2/foobar/orig.pdf
```

Will result in this:

![image](https://user-images.githubusercontent.com/7661267/85527012-c63c7300-b60a-11ea-9b06-db9e644a29ef.png)

 It would be nice if only the basename would be stored!

Thank you very much!

Result file:
[orig.pdf](https://github.com/pdfcpu/pdfcpu/files/4824303/orig.pdf)

Best regards,
Csaba

**Comment by hhrutter** [comment]
Fixed with [v0.3.4](https://github.com/pdfcpu/pdfcpu/releases/tag/v0.3.4).
