### ISSUE TITLE
extractPages: Output filename creation

### ISSUE THREAD

**Issue by Blesmol** [pdfcpu/pdfcpu#203]
Currently the `ExtractPagesFile()` function generates output files that should follow the pattern '\<infileWithoutExtension\>_\<pageNr\>.pdf". However, this only works if the file extension of the input file is completely lowercase 'pdf'. Else this might result in files with names like `test.PDF_17.pdf`

I assume this could be fixed by replacing line 263 in `extract.go` with
```
fn := strings.TrimSuffix(fileName, filepath.Ext(fileName))
```

**Comment by hhrutter** [comment]
Thanks for reporting this!

**Comment by hhrutter** [comment]
There is now an easier way to process extracted PDFs.
Let me know if you still need this to process written files.

With the latest release you can process any extracted single page PDF context directly
if you do smth like in api/test/extract_test.go:

````
func TestExtractPagesLowLevel(t *testing.T) {
	msg := "TestExtractPagesLowLevel"
	inFile := filepath.Join(inDir, "TheGoProgrammingLanguageCh1.pdf")
	outFile := filepath.Join(outDir, "MyExtractedAndProcessedSinglePage.pdf")

	// Create a context.
	ctx, err := api.ReadContextFile(inFile)
	if err != nil {
		t.Fatalf("%s readContext: %v\n", msg, err)
	}

	// Extract page 1.
	i := 1
	ctxNew, err := ctx.ExtractPage(i)
	if err != nil {
		t.Fatalf("%s extractPage(%d): %v\n", msg, i, err)
	}

	// Here you can process this single page PDF context.

	// Write context to file.
	if err := api.WriteContextFile(ctxNew, outFile); err != nil {
		t.Fatalf("%s write: %v\n", msg, err)
	}
}
```

**Comment by Blesmol** [comment]
Works like a charm, thanks!
