### ISSUE TITLE
extractPages: Allow to provide own base output filename to ExtractPagesFile() or return list of generated files

### ISSUE THREAD

**Issue by Blesmol** [pdfcpu/pdfcpu#204]
When using `ExtractPagesFile()` directly, one has to know the pattern on how the generated output files are named (and which was changed with the recent update to v0.3.4).

Would it be possible to either allow to provide own base filenames instead of just the output dir, or can a list of filenames for the generated files be returned?

**Comment by hhrutter** [comment]
Hello!
I am not really sure what you mean by that.
Can you elaborate?

**Comment by Blesmol** [comment]
Sure. 
I am currently consuming the go API of pdfcpu to do (amongst others) the following: I am extracting a single page out of a multi-paged PDF file and then continue processing the resulting file. Extracting is done by calling function `ExtractPagesFile()` from pdfcpu.

So we would, for example, have the following code:
```
err = pdfcpuapi.ExtractPagesFile("example.pdf", "targetDir/", []string{strconv.Itoa(17)}, nil)
```

If I now want to proceed working on the resulting extracted PDF file, I need to know under which exact filename this was stored in the output folder by pdfcpu. Up to v0.3.3 this would have been "page_17.pdf", since v0.3.4 this would be "example_17.pdf". But this I had to find out by analyzing either the involved code on side of pdfcpu or by looking at the resulting output. Currently there is no proper way to have this programmatically. For example, `ExtractPagesFile()`  could additionally return a string list that contains the names of the generated files.

**Comment by hhrutter** [comment]
related to #203

**Comment by hhrutter** [comment]
A work around for your particular usecase may be to use `pdfcpu trim`or `pdfcpu collect` or the corresponding API calls.
All you care about is a single page pdf - your outFile for these commands.

**Comment by hhrutter** [comment]
There is now an easier way to process extracted PDFs.
See my comment under #203

**Comment by Blesmol** [comment]
Works like a charm, thanks!
