### ISSUE TITLE
watermark: Manual creation of watermark

### ISSUE THREAD

**Issue by asaleem772** [pdfcpu/pdfcpu#205]
Steps to reproduce issue: 

use api to call below, 

```go
wm := pdfcpu.DefaultWatermarkConfig()
wm.TextLines = []string{"WaterMark Text Here"}
wm.FontSize = 5
wm.Opacity = 0.25
wm.ScaleAbs = false
wm.Scale = 1.5
wm.ScaledFontSize = 2
wm.OnTop = false

var b bytes.Buffer
foo := io.Writer(&b)

err = api.AddWatermarks(bytes.NewReader(fileBytes), foo, nil, wm, nil)
```
And then it is returning nil pointer exception, I have debugged the root cause of it, and found below code has the issue, where nil pointer is trying to access ```box.Width()```

```go
func scaleFontSize(r *Rectangle, lines []string, scaleAbs bool,
	...
		if width == 0 {
			**_box_**, _ := calcBoundingBoxForLines(lines, x, y, fontName, *fontSize)
			www = box.Width() + mLeft + mRight + 2*borderWidth
		}
        ...
	
}
```
```calcBoundingBoxForLines``` returns `nil` in box and we are then checking `box.Width()` which throws nil pointer exception. 

This issue came after recent change in 0.34 version, before that it was working fine. 

@hhrutter 

Thank you.

**Comment by hhrutter** [comment]
Hello,

You have to go through the api to produce your wm instance!

You have two options:

1) 
```
func AddTextWatermarksFile(inFile, outFile string, selectedPages []string, onTop bool, text, desc string, conf *pdfcpu.Configuration) error 
```

2) if you want to use ReadSeeker/Writer:
```
wm, err := TextWatermark(text, desc, onTop, false)
if err != nil {
	return err
}
...
and then you call:

AddWatermarks(rs io.ReadSeeker, w io.Writer, selectedPages []string, wm *pdf.Watermark, conf *pdf.Configuration) error {

```

Have a look at [the updated stamp tests](https://github.com/pdfcpu/pdfcpu/blob/master/pkg/api/test/stamp_test.go)

**Comment by asaleem772** [comment]
Hi @hhrutter , 

I tried above suggestions using ReadSeeker/Writer.

And I am getting below error: 

```unable to place watermark on pdf: pdfcpu: missing write file descriptor.```

Below is my code snippet.


```go 
wm, err = api.TextWatermark("COPY / KOPIE", "points:60, col: 1 0 0, rot:60, sc:1.5 abs, opacity:.25", false, false)
if err != nil {
	return errors.Wrapf(err, "unable to place watermark on pdf")
}
var b bytes.Buffer
foo := io.Writer(&b)
err = api.AddWatermarks(bytes.NewReader(fileBytes), foo, nil, wm, nil)
if err != nil {
	return errors.Wrapf(err, "unable to place watermark on pdf")
}

```

And func ```go AddTextWatermarksFile() ``` works fine, but this is costly function as we have to create temporary files to use this function.

**Comment by hhrutter** [comment]
Please install the latest commit and let me know if you keep having this problem.

**Comment by asaleem772** [comment]
> Please install the latest commit and let me know if you keep having this problem.

Thank you @hhrutter , it worked well this time with latest commit 	
`github.com/pdfcpu/pdfcpu v0.3.5-0.20200715225555-e408740d07ed`
