### ISSUE TITLE
encrypt: using api fails in v0.3.4

### ISSUE THREAD

**Issue by bihe** [pdfcpu/pdfcpu#206]
I am using the pdfcpu API to encrypt PDF streams. The approach worked <= **v0.3.3** but results in an error in **v0.3.4**
Error: `pdfcpu: missing write file descriptor` 
I've created a sample repository to show the issue: https://github.com/bihe/pdfcpu_issue/

The sample code uses `Optimize` to encrypt a PDF payload:
```go
import (
	pdfApi "github.com/pdfcpu/pdfcpu/pkg/api"
	pdf "github.com/pdfcpu/pdfcpu/pkg/pdfcpu"
)

conf = pdf.NewRC4Configuration(newPwd, newPwd, 40)
conf.Cmd = pdf.ENCRYPT
conf.UserPWNew = &newPwd

buff := new(bytes.Buffer)
if err = pdfApi.Optimize(bytes.NewReader(payload), buff, conf); err != nil {
	return fmt.Errorf("could not process PDF payload: %v", err)
}
```` 

If I use **v0.3.3** in `go.mod` the test works.

```
PASS
ok      github.com/bihe/pdfcpu_issue    0.003s
```

Changing the version to **v0.3.4** results in the error message:

```
--- FAIL: Test_PDF_Encryption (0.00s)
    issue_test.go:16: could not encrypt PDF payload with password '12345': could not process PDF payload: pdfcpu: missing write file descriptor
FAIL
exit status 1
FAIL    github.com/bihe/pdfcpu_issue    0.003s
```

Either I am using the API incorrectly or there was a change which focuses only on files and not on "streams". The change was introduced in the commit: https://github.com/pdfcpu/pdfcpu/commit/d8b8be9e0a1ee44fce6cb546ea0c0c129d5fca7f

**Comment by hhrutter** [comment]
Thanks for reporting this!
I'll have a look.

**Comment by hhrutter** [comment]
Please install the latest commit and let me know if you keep having this problem.

**Comment by bihe** [comment]
👍 works great with `require github.com/pdfcpu/pdfcpu v0.3.5-0.20200715225555-e408740d07ed`
```
❯ go test -v
=== RUN   Test_PDF_Encryption
--- PASS: Test_PDF_Encryption (0.00s)
PASS
ok      github.com/bihe/pdfcpu_issue    0.003s
```

thx, solved!
