### ISSUE TITLE
pdfcpu: missing write file descriptor

### ISSUE THREAD

**Issue by jozuenoon** [pdfcpu/pdfcpu#207]
Hi!

This is breaking change https://github.com/pdfcpu/pdfcpu/commit/d8b8be9e0a1ee44fce6cb546ea0c0c129d5fca7f#diff-1f58690efd2b9d45abf9d269399235baR1031-R1034 on 0.3.4 release.  We are passing buffer based io.Writer and we have no intention to write any files.
Based on my quick analysis, it seems that we are forced to pass `*os.File`, otherwise Write will always fail on `setFileSizeOfWrittenFile`.

Please consider allowing to pass in-memory buffers that are not file associated.

As a workaround, we are reverting to 0.3.3 version.

**Comment by hhrutter** [comment]
Thanks for reporting this!

There was a reason for this and pdfcpu is still Alpha but could you do me a favour and post a little snippet around the api call that breaks in your case. 

I will investigate this.
Rest assured there was no intention in destroying backwards compatibility.

Thank you!

**Comment by jozuenoon** [comment]
@hhrutter thanks for your great job on the project :) 

I added PR proposal with example code snippet #208. Let's discuss there further on details and why the error was returned.

**Comment by AlmogBaku** [comment]
what's the workaround?

**Comment by hhrutter** [comment]
Hello!

If this is related to the panic as discussed above this is fixed with the latest commit.
Otherwise please open a separate issue so I can follow up.

Thank you for using pdfcpu 💚

**Comment by AlmogBaku** [comment]
I'm asking because it still panicing... or maybe you haven't released yet? (just did `go get -u`) and faced this error

**Comment by hhrutter** [comment]
Please doublecheck if the following commit appears in your git log:
`ef81799 2020-07-15 Witold Konior Handle non *os.File buffers. (Fix #207) (#208)`

**Comment by AlmogBaku** [comment]
ok, that probably was the issue.
I'll just wait for the release :D
