### ISSUE TITLE
read: Invalid trailer entry for previous xref section offset causing panic

### ISSUE THREAD

**Issue by lgonzalez-silen** [pdfcpu/pdfcpu#209]
I'm getting the following when I call Validate on a PDF (with real customer PII, so cannot be shared):

`dereferenceObject: problem dereferencing object 1: pdfcpu: ParseObjectAttributes: can't find "obj"`

It is on this line, on v0.3.4:

https://github.com/pdfcpu/pdfcpu/blob/2ee507230b28f1ddc42a1fa909455c0fe53b533d/pkg/pdfcpu/parse.go#L244

The image has the stack and the uint8 values in the buffer. I also copied the buffer text (in case it helps for tests), minus the initial/ending uint8 values that don't map to chars.

![Screen Shot 2020-07-07 at 7 27 26 PM](https://user-images.githubusercontent.com/2609368/86855772-0aa72480-c089-11ea-9e08-4f065c77a701.png)

```
endstream
endobj
1 0 obj
<< /Count 1 /Kids [4 0 R] /Type /Pages >>
endobj
5 0 obj
<< /Pages 1 0 R /Type /Catalog >>
endobj
xref
1 5
0000593111 00000 n
0000000210 00000 n
0000592964 00000 n
0000000012 00000 n
0000593171 00000 n
trailer
<< /Prev 0 /Root 5 0 R /Size 6 >>
startxref
593223
%%EOF
```

**Comment by hhrutter** [comment]
Hello!

Although this is a very interesting bug during reading/parsing, this can really only reliably fixed with a sample input PDF at hand.
If you can't share it here but you're still interested in a fix please get in touch with me via email: hhrutter@gmail.com

Also please not that I am not inclined in providing free commercial support which this very much sounds like.
I am happy to sign contracts and NDAs though and there is always the Sponsor button.

Thank you for using pdfcpu 💚

**Comment by lgonzalez-silen** [comment]
Let me be clear that I value your work enormously! I'm sorry if it seemed like I was asking for support. This is not a major issue, and I consider reporting it as a contribution to make PDFCPU better. 👍 

I've gone ahead and made a financial contribution as well. Again, thank you!

I'll follow up by email on the disclosure challenges.

**Comment by hhrutter** [comment]
Hi Luis,

I very much appreciate this and welcome you as a backer of pdfcpu. 💚
Coding in Go is what I love and as I said I will fix this as soon as you send me a sample.

It's just that I have to draw a line somewhere as far as what users take for granted about me being on call for fixes.
I 🙏  that everybody understands.

**Comment by lgonzalez-silen** [comment]
The latest commit fixes Validate for my document. Thank you so much!

**Comment by hhrutter** [comment]
Thank you for supporting pdfcpu 💚
