### ISSUE TITLE
Changing api should also change MAJOR part of version

### ISSUE THREAD

**Issue by vblz** [pdfcpu/pdfcpu#212]
According to https://semver.org/ API changing should follow changing MAJOR part of version. So I relayed that nothing changed except bugs and I could update without any changes in my code.

After upgrading from v0.3.2 to v0.3.4 I've found out that there are API changes in https://godoc.org/github.com/pdfcpu/pdfcpu/pkg/api#ExtractPages method. This is not a big deal, but anyway it would be great if I could relay that nothing will change in API in PATCH version.

**Comment by hhrutter** [comment]
You're right - my bad..
Unintentional though and happened during a hectic release preparation phase.
Thanks for using pdfcpu 💚
