### ISSUE TITLE
import: support NRGBA64

### ISSUE THREAD

**Issue by toantruong95** [pdfcpu/pdfcpu#213]
There are many image types that are not supported now. Do we have a plan to support them?

**Comment by hhrutter** [comment]
Hello!

Image extraction is still experimental and my approach is extending it incrementally.
Any specific image file type you are looking for that pdfcpu does not support at the moment?

Thank you for using pdfcpu 💚

**Comment by TruongQToan** [comment]
Thank you for your support. In my use cases, I need to import the images which are the screenshot for the phone, they seem to have type `NRGBA66` and are not supported by pdfcpu now. If you can make this type possible, I feel very thankful for that.

**Comment by hhrutter** [comment]
if you can share a sample we can make it happen!

Thank you for using pdfcpu 💚

**Comment by TruongQToan** [comment]
Because these images are confidential, I cannot public here. Could I share those images to your email?

**Comment by hhrutter** [comment]
Sure you can! 
My email is hhrutter@gmail.com.
Thank you!

**Comment by TruongQToan** [comment]
I have sent you the image. Thank you for supporting this.
