### ISSUE TITLE
split: panic attack

### ISSUE THREAD

**Issue by xschmets** [pdfcpu/pdfcpu#215]
Hi,

Thank you for this great tool.

I noticed that I cannot split a merged PDF comming from PDFsam.

I get the following error each time :

"unexpected panic attack: interface conversion: pdfcpu.Object is pdfcpu.IndirectRef, not pdfcpu.Dict".

The info/validation/optimization of the file is OK.

I am using pdfcpu: v0.3.4-next (build : 2020-06-28T19:16:02Z commit: 2ee5072) under Windows 10.

Have a nice day.

**Comment by hhrutter** [comment]
Hi there,

I need to see a stacktrace.

Do you think you can share a sample.pdf that makes pdfcpu split fail?
If not please post the output of `pdfcpu split -vv in.pdf .`

Thanks for reporting this!

**Comment by xschmets** [comment]
Here is a file.
[PDFsam_merge.pdf](https://github.com/pdfcpu/pdfcpu/files/5007163/PDFsam_merge.pdf)
