### ISSUE TITLE
api: Add support for page boundaries

### ISSUE THREAD

**Issue by zanmato** [pdfcpu/pdfcpu#216]
Recently I had to define a **TrimBox** and a **BleedBox** for PDFs going to a print shop. I did this by essentially copying the `ImportImages` func to be able to access the dict of the newly created image page. 
I guess another way to accomplish this is by running `ReadContext` afterwards to access the context, but it's still a bit clunky to me.  
I think a better way would be to allow a callback func in the **Import** config that passes references to the page dict allowing you to insert/modify these boundary boxes. This way you don't have to change the method signature and thus won't break any compatibility with previous versions.

Something like this:
```go
type ImportCallback func(int, Dict) error

// Import represents the command details for the command "ImportImage".
type Import struct {
	// .... Omitted the rest
        Callback ImportCallback
}
```

```go
&pdfcpu.Import{
  DPI: 300,
  Callback: func(i int, pageDict pdfcpu.Dict) error {
     // Omitted part of getting the MediaBox to get the width and height for brevity
     pageDict.Insert("TrimBox", pdfcpu.NewNumberArray(0, 0, width - someMargin, height - someMargin))
     return nil
  }
}
```

I guess something like this could also solve #210 by enabling insertion of a **CropBox**
I would be happy to submit a PR for this, although I haven't considered the CLI part of the project with this feature proposal.

**Comment by hhrutter** [comment]
Hi there!

I am aware proper support for PDF's page boundaries is lacking.
Consider me inspired by your proposal but this needs to be adressed across the board.

Thanks for using pdfcpu 💚

**Comment by kpym** [comment]
It will be nice if the cli tool also has the ability to manage all the boxes, not only the `cropbox` (as requested in #210).
For example something like 
```shell
> pdfcpu boxe -pages '!2-4,!12-' media,trim="0 0 300 450" crop="50 50 250 400" 
``` 
would be nice. Other possible commands for `pdfcpu boxe` are`list` and `delete`.

**Comment by hhrutter** [comment]
For now the plan is to extend the `pdfcpu import` command because that's where this is really needed per described usecase. 


I am hesitant to provide a separate command for juggling around with page boundaries for a given PDF because the consequences can be brutal and not irreversible. Basically this is smth for the api but necessarily for the cli.

Can you describe your specific usecase for this cli feature?

**Comment by kpym** [comment]
> Can you describe your specific usecase for this cli feature?

If for example you have a software that requires `trimbox` and your pdf do not have one. 
Or if some software (like `pdfcpu` before the correction of #245) ignore the `cropbox` and use the `mediabox` in place, we can modify the `mediabox` to be equal to the current `cropbox` to get around this.

**Comment by hhrutter** [comment]
Please be specific?
Which software requires a trimbox and for what reason?
I am learning here..

**Comment by kpym** [comment]
> Please be specific?
> Which software requires a trimbox and for what reason?
> I am learning here..

I'm not pdf-boxes specialist neither ;) 

As far as I know all "standard" applications (viewers, home printers) use only the `mediabox` and the `cropbox`. But all professional prepress drivers and softwares use mainly the other boxes (has to be verified). For this reason PDF/X standards require the `trimbox`, and the `bleedbox` but not the `cropbox`.

You can check some info about the pdf boxes [here](https://www.prepressure.com/pdf/basics/page-boxes).

**Comment by hhrutter** [comment]
This is fixed with the latest commit including the two new commands:
* pdfcpu crop
* pdfcpu boxes
