### ISSUE TITLE
Error "missing required Font" on LaTeX generated files with formulas

### ISSUE THREAD

**Issue by erikgeiser** [pdfcpu/pdfcpu#218]
Multiple commands (`split`, `collect`, ...) throw a "missing required Font" error when operating on PDFs that were compiled using LaTeX and that contain formulas, which is pretty common for LaTeX files. Consider the following LaTeX file:

```latex
% broken.tex
\documentclass[a4paper]{article}
\begin{document}
Broken PDF: $a = 1$
\end{document}
```

It can be compiled to `broken.pdf` with the command `pdflatex broken.tex`. `pdfcpu` will then fail to collect a page from the PDF:

```
$ pdfcpu collect -pages 1 broken.pdf x.pdf
writing x.pdf...
pdfcpu: page 1: missing required Font: (Brok)28(en)-334(PDF)1(:)]TJ/F11
```

If you do not have a LaTeX distribution set up I can provide an example file that reproduces this error. 

Thanks for the great library.

**Comment by hhrutter** [comment]
Hi and thanks for reporting this! 

Please be so kind and share a sample file to reproduce and fix this.
You can also send me an email hhrutter@gmail.com

Thanks for using pdfcpu 💚

**Comment by erikgeiser** [comment]
I also noticed that other aspects of LaTeX also cause this error, such as `\section` in this document:

```latex
% section.tex
\documentclass[a4paper]{article}
\begin{document}
\section{Broken PDF: Section}
\end{document}
```

I've send you PDF samples for both cases via email.

**Comment by hhrutter** [comment]
Fixed with latest commit.
