### ISSUE TITLE
does pdfcpu support embed font into pdf?

### ISSUE THREAD

**Issue by liming-coder** [pdfcpu/pdfcpu#219]
i want to create a text watermark with custom chinese font "SimSun", such as "test测试". the watermark is added but chinese text can't display. i guess the needed glyphs are not exacted and embedded into the target pdf.
how can i achieve this with pdfcpu?
thanks.

**Comment by hhrutter** [comment]
Not yet.
#171 will address your issue.

**Comment by hhrutter** [comment]
Closing duplicate of #171
