### ISSUE TITLE
api: Handle nil arguments gracefully

### ISSUE THREAD

**Issue by erikgeiser** [pdfcpu/pdfcpu#220]
The `api.Merge` function panics when no `io.ReadSeeker`s are passed. This is a nonsensical call but I think it should still be handled with a gracefully error message. Here's some sample code:

```Go
var buffer bytes.Buffer
pdfcpuAPI.Merge([]io.ReadSeeker{}, &buffer, nil)
```

This is the relevant section from the panic:

```
github.com/pdfcpu/pdfcpu/pkg/api.Merge(0xc000032758, 0x0, 0x0, 0x133da20, 0xc0000112f0, 0xc00007e3f0, 0xc000032770, 0x1087046)
	[redacted]/pkg/mod/github.com/pdfcpu/pdfcpu@v0.3.5-0.20200802160406-be1e0eb55afc/pkg/api/api.go:1630 +0x34f
```

**Comment by hhrutter** [comment]
Fixed with latest commit.
