### ISSUE TITLE
Exporting StreamDict internal functions

### ISSUE THREAD

**Issue by marcosinger** [pdfcpu/pdfcpu#221]
Hey @hhrutter, 

Firstly, thank you for this excellent library. I've started to use it a few months ago, and so far, it's pretty easy to grasp despite the insane PDF spec. But, one issue that I've is regarding encode/decode `StreamDict` object.

Right now, both [encodeStream](https://github.com/pdfcpu/pdfcpu/blob/master/pkg/pdfcpu/filter.go#L64) and [decodeStream](https://github.com/pdfcpu/pdfcpu/blob/master/pkg/pdfcpu/filter.go#L123) functions are private, and I needed to copy/paste the source code from the library to work with it on my end.

I think exporting it as a `StreamDict` method would make it better for anyone who wants to reuse this code, and will add more value to the `StreamDict` object itself since the API will end up straightforward.

I propose something like this:

```go
func (sd *pdfcpu.StreamDict) Decode() error {
  // decode code goes here
}

func (sd *pdfcpu.StreamDict) Encode() error {
  // encode code goes here
}
```

so changing those places where we use it is just a matter of:

### Decode
```go
// pkg/pdfcpu/attach.go on fileSpecStreamDictInfo function
if err := sd.Decode(); err != nil {
  return nil, desc, modDate, err
}
```
 ### Encode
```go
// pkg/pdfcpu/readImage.go on createSMaskObject function
if err := sd.Encode(); err != nil {
  return nil, err
}
```

What do you think about it? Do you see any drawbacks or concerns regarding it?
Many thanks for considering my request.

**Comment by hhrutter** [comment]
Oi Marco! 👊

I remember you from GopherCon Brasil! - Palestra bacana 👍 

First and foremost I am curious about your usecase.
Can you tell me what it is you are trying to achieve or working on?
StreamDict decoding is really as much low level as you can get with PDF processing and therefore not part of the api.

👍 I agree that encoding and decoding should be methods on *StreamDict* as far as the design goes.

There are 2 reasons why these methods are not exported right now:
* pdfcpu usage is supposed to be via cli or api and en/decoding objectstreams is not something that is part of the api.
* As the whole project is still Alpha (as stated in the ReadMe) this also applies to streamDict en/decoding.

There are still corner cases where decoding needs to be tested properly and worked on eg. FilterPipelines using more than 1 filter. It is hard to get a hand on PDFs using such more exotic filter pipelines and even more work to generate them for testing + my time is limited. I just think it would be premature to make this code public at this point.

Maybe your use case is really a potential pdfcpu operation?

You can also find me on the Gopher Slack in the #pdfcpu channel.

**Comment by hhrutter** [comment]
Hi there!

I am going ahead and have fixed this design flaw.
Currently the only use case where pdfcpu does not support complex filter pipelines is during image extraction.

Thanks for your suggestion 💚

**Comment by hhrutter** [comment]
Fixed with latest commit.
