### ISSUE TITLE
cli: image watermark panics

### ISSUE THREAD

**Issue by lhq0826** [pdfcpu/pdfcpu#222]
```bash
$ pdfcpu watermark add -mode image 'draft_icon.png' 'rotation:-30, scalefactor:1 abs' test.pdf 456.pdf
writing 456.pdf...
pages: all
unexpected panic attack: interface conversion: color.Color is color.NRGBA, not color.RGBA
```
Linux 42ded2a8723f 4.19.76-linuxkit #1 SMP Tue May 26 11:42:35 UTC 2020 x86_64 GNU/Linux

-rw-r--r--  1 root root 135K Sep  9 10:30 draft_icon.png

**Comment by hhrutter** [comment]
Hi!

Thanks for reporting this!

Unfortunately without a stack trace this is going to be difficult to debug.

If you can share a sample file that reproduces this we can fix this.
Either post here or send me an email: hhrutter@gmail.com

Thank you for using pdfcpu 💚

**Comment by shvc** [comment]
- version: Linux x86_64
```
./pdfcpu version
pdfcpu: 0.3.5
build : 2020-08-30T22:40:02Z
commit: 6faa4ad
```

- watermark image
```
http://nginx.org/nginx.png
```
- pdf file
```
http://africau.edu/images/default/sample.pdf
```
- error command
```
./pdfcpu watermark add -mode image 'nginx.png' 'rotation:-30, scalefactor:1 abs' sample.pdf
writing sample.pdf...
pages: all
unexpected panic attack: interface conversion: color.Color is color.NRGBA, not color.RGBA
```

**Comment by hhrutter** [comment]
Thanks I take a look!

**Comment by hhrutter** [comment]
Fixed with latest commit!
