### ISSUE TITLE
Relax validation for missing fontDescriptor.StemV and empty imageStreamDict.Intent

### ISSUE THREAD

**Issue by eduardonunesp** [pdfcpu/pdfcpu#224]
Recently I received a PDF file to update, unfortunately, the PDF file is protected against editing, but is open to copy and a solution found to edit the PDF file is to open in macOS app Preview and "export as PDF", which will create a "clone" of the original PDF file without the security against editing and edit the "clone":

<img width="366" alt="image" src="https://user-images.githubusercontent.com/582516/93087695-4e14a500-f66f-11ea-9137-9a16bc3ef75b.png">

Is it possible to clone a PDF file (open to copy) in `pdfcpu` (and the clone have full access) ?

**Comment by eduardonunesp** [comment]
Another strange behavior with that protected file is when executing the permission list on that file it returns the following message:

```bash
pdfcpu permissions list protected_file.pdf
dict=fdDict required entry=StemV missing
```

When check the permissions on macOS Preview app it shows the following message:

<img width="366" alt="image" src="https://user-images.githubusercontent.com/582516/93092564-f75e9980-f675-11ea-8ed9-d61257622bc2.png">

**Comment by hhrutter** [comment]
Hello!

If you run into problems with pdfcpu always ensure your PDF is recognized as valid.

You can always run `pdfcpu val my.pdf`

In this particular case you are dealing with an invalid PDF file.
Some font descriptor dict is missing the required entry *StemV*.

If you can open and save this file in Preview without entering any password
Try `pdfcpu optimize old.pdf new.pdf`or `pdfcpu decrypt old.pdf new.pdf`.
One of these commands  should achieve the same result.
Just remember that internally pdfcpu always needs to make sure the file validates,
which is a problem with this very file.

You can hack validate/font.go around line 209 and modify
```
_, err = validateNumberEntry(xRefTable, d, dictName, "StemV", fontDictType != "Type3", pdf.V10, nil)
if err != nil {
	return err
}
```

to something like:
```
_, err = validateNumberEntry(xRefTable, d, dictName, "StemV", false, pdf.V10, nil)
if err != nil {
	return err
}
```
this turns this dict entry from required to optional.

This should get the validation of this file beyond this corrupt font dict.

We can always extend relaxed validation later to ignore this issue.
Once validation passes you should be able to execute `pdfcpu info my.pdf`
if you still get an error please send me the output of either `pdfcpu val -vv my.pdf`or pdfcpu info -vv my.pdf``

**Comment by eduardonunesp** [comment]
Hi

I updated the following line as suggested:
```go
_, err = validateNumberEntry(xRefTable, d, dictName, "StemV", false, pdf.V10, nil)
if err != nil {
	return err
}
```
And the following result returned:
```bash
$ pdfcpu info my.pdf
pdfcpu info my.pdf
pdfcpu: validateNameEntry: dict=imageStreamDict entry=Intent invalid dict entry:
```
Maybe this PDF has many issues beyond the font descriptor

**Comment by hhrutter** [comment]
This smells like a bug!

Again, if both Adobe Reader and Mac Preview can open this file, pdfcpu should do so as well.
If you can send me the output of 'pdfcpu val -vv my.pdf &> my.log`
I can provide a fix and you may even be able to complete the validation of your file.

Thank you!

**Comment by eduardonunesp** [comment]
Thank you @hhrutter if you need another log or help please let me know!

**Comment by hhrutter** [comment]
Can you try this for me?

validate/xObject.go line 480:
Replace:
`return pdf.MemberOf(s, []string{"AbsoluteColorimetric", "RelativeColorimetric", "Saturation", "Perceptual"})`

with:
`return pdf.MemberOf(s, []string{"", "AbsoluteColorimetric", "RelativeColorimetric", "Saturation", "Perceptual"})`

**Comment by eduardonunesp** [comment]
Same error I think

```bash
validating(mode=relaxed) my.pdf ...
validation error: dict=fdDict required entry=StemV missing
```

**Comment by eduardonunesp** [comment]
Ops, here is the changes, both together looks like it works 

```
diff --git a/pkg/pdfcpu/validate/font.go b/pkg/pdfcpu/validate/font.go
index 6005e4a..670dce4 100644
--- a/pkg/pdfcpu/validate/font.go
+++ b/pkg/pdfcpu/validate/font.go
@@ -206,7 +206,7 @@ func validateFontDescriptorPart2(xRefTable *pdf.XRefTable, d pdf.Dict, dictName,
                return err
        }

-       _, err = validateNumberEntry(xRefTable, d, dictName, "StemV", fontDictType != "Type3", pdf.V10, nil)
+       _, err = validateNumberEntry(xRefTable, d, dictName, "StemV", false, pdf.V10, nil)
        if err != nil {
                return err
        }
diff --git a/pkg/pdfcpu/validate/xObject.go b/pkg/pdfcpu/validate/xObject.go
index 3fc8dc6..f1e8674 100644
--- a/pkg/pdfcpu/validate/xObject.go
+++ b/pkg/pdfcpu/validate/xObject.go
@@ -475,7 +475,7 @@ func validateImageStreamDictPart2(xRefTable *pdf.XRefTable, sd *pdf.StreamDict,

        // Intent, name, optional, since V1.0
        validate := func(s string) bool {
-               return pdf.MemberOf(s, []string{"AbsoluteColorimetric", "RelativeColorimetric", "Saturation", "Perceptual"})
+               return pdf.MemberOf(s, []string{"", "AbsoluteColorimetric", "RelativeColorimetric", "Saturation", "Perceptual"})
        }
        _, err = validateNameEntry(xRefTable, sd.Dict, dictName, "Intent", OPTIONAL, pdf.V11, validate)
        if err != nil {
```

**Comment by hhrutter** [comment]
We have 2 issues here:

**Comment by eduardonunesp** [comment]
Sorry I closed by accident! 🤣

**Comment by hhrutter** [comment]
Fine!, 

These fixes will go into the next commit.

**Comment by eduardonunesp** [comment]
Now the `pdf` is showing the permissions correctly

```bash
pdfcpu permissions list my.pdf
permission bits: 100000000100
Bit  3: true (print(rev2), print quality(rev>=3))
Bit  4: false (modify other than controlled by bits 6,9,11)
Bit  5: false (extract(rev2), extract other than controlled by bit 10(rev>=3))
Bit  6: false (add or modify annotations)
Bit  9: false (fill in form fields(rev>=3)
Bit 10: false (extract(rev>=3))
Bit 11: false (modify(rev>=3))
Bit 12: true (print high-level(rev>=3))
```

**Comment by hhrutter** [comment]
Fixed with latest commit!

**Comment by jzacsh** [comment]
(sorry for the noise...)

in case anyone else hits this, since this is the top web result for `pdfcpu: validateNameEntry: dict=imageStreamDict entry=Intent invalid dict entry:`, I fixed my issue by deleting highlights/annotations in my PDF (via `ps2pdf -dShowAnnots=false orig.pdf cleaned.pdf`) and that made pdfcpu happy again (so `pdfcpu booklet -- out.pdf 2 cleaned.pdf` no longer throws the above error).
