### ISSUE TITLE
Million logs outputs in 'writeNRGBAImageBuf'

### ISSUE THREAD

**Issue by ikki74** [pdfcpu/pdfcpu#228]
Hello,
In the last version the function 'writeNRGBAImageBuf' is writing literally 'millions' of logs lines while converting a fullhd image, so it is really slow and not operative ... Can you delete those logs?:

fmt.Printf("writeNRGBAImageBuf: w=%d h=%d\n", w, h)
fmt.Printf("(%d/%d)\n", x, y)

Thanks!

**Comment by hhrutter** [comment]
Fixed with latesrt commit!

**Comment by ikki74** [comment]
Thanks a lot! Great job!

**Comment by hhrutter** [comment]
感谢您使用 pdfcpu 💚
