### ISSUE TITLE
cli: watermark, no watermark visible

### ISSUE THREAD

**Issue by shvc** [pdfcpu/pdfcpu#229]
### pdfcpu command success, but no watermark image added
- pdfcpu command(Linux x86_64) version
  ```
  ./pdfcpu version
  pdfcpu: 0.3.5
  build : 2020-08-30T22:40:02Z
  commit: 6faa4ad
  ```
- watermark image file
  `https://upload.wikimedia.org/wikipedia/commons/thumb/d/d1/Albert_Logo.png/280px-Albert_Logo.png`

- pdf file
  `https://vager.cc/pkgs/api.pdf`

- command
  ```
  ./pdfcpu watermark add -mode image 280px-Albert_Logo.png 'rotation:-30, scalefactor:1 abs' api.pdf api-wm.pdf
  writing api-wm.pdf...
  pages: all
  ```
  seems command success, but no watermark add to api-wm.pdf

**Comment by hhrutter** [comment]
Does `pdfcpu stamp add .........` work using this image on this pdf?

**Comment by shvc** [comment]
> A watermark is the first content that gets rendered for a page.
> The visibility of the watermark therefore depends on the transparency of all layers rendered after/on top.
> 
> Does `pdfcpu stamp add .........` work using this image on this pdf?

stamp is OK 
```
./pdfcpu stamp add -mode image 280px-Albert_Logo.png '' api.pdf api-stamp.pdf
```
But the watermark image is on top layer of new pdf

**Comment by hhrutter** [comment]
What you can do is play around with opacity, for example:

`./pdfcpu stamp add -mode image 280px-Albert_Logo.png 'op:.5' api.pdf api-stamp.pdf`

This also gives you a watermark like effect.

**Comment by zhumengyifang** [comment]
I want to add a text watermark to the entire page. What should I do

**Comment by hhrutter** [comment]
你好!

Try a relative scalefactor 1.0:
 `pdfcpu watermark add -mode text 'Watermark' 'scale:1.0'  in.pdf out.pdf`

See also http://pdfcpu.io/core/watermark

This is not related to #229 - Please open a new issue if you have further questions!

Thank you for using pdfcpu 💚

**Comment by zhumengyifang** [comment]
thanks I don t speak much English
I use this desc:scalefactor:1 abs,rot:0,op:0.5,points: 15
code :
wm, err := pdfcpu.ParseTextWatermarkDetails("text", fmt.Sprintf("scalefactor:0.9 abs,rot:0,op:0.5,points: 15"), true)
output:
![image](https://user-images.githubusercontent.com/39289075/93992633-5c299a80-fdc0-11ea-91bd-4f596ee4029e.png)

I want this
![image](https://user-images.githubusercontent.com/39289075/93992251-e7eef700-fdbf-11ea-840c-289477c78382.png)

**Comment by zhumengyifang** [comment]
This is not related to #229 - Please open a new issue if you have further questions!
sorry  I'll delete those comments later

**Comment by hhrutter** [comment]
Either you wait until pdfcpu supports CJKV or you use an image watermark. 
See #171

**Comment by zhumengyifang** [comment]
thank you ， also dynamically generate text to do this, but there are some problems。

**Comment by dbaynard** [comment]
> A watermark is the first content that gets rendered for a page.
> The visibility of the watermark therefore depends on the transparency of all layers rendered after/on top.

Could this be added to the watermark documentation? Perhaps at the end of https://github.com/pdfcpu/pdfcpu/blob/53c77288cbd238433a255a5e2ebb34fc28be0cf6/cmd/pdfcpu/usage.go#L315
