### ISSUE TITLE
Executing from PHP

### ISSUE THREAD

**Issue by lhq0826** [pdfcpu/pdfcpu#230]
php-fpm
`PHP 7.2.19 (fpm-fcgi) (built: Jul  3 2019 21:36:03)`

pdfcpu version
`0.3.5`

php-fpm exec("pdfcpu version") not valid but php-cli is work

**Comment by hhrutter** [comment]
Hello!

There is nothing I can do without further information.
Please post a stacktrace or suppy a sample so I can follow up.

You can produce a stacktrace with: `pdfcpu val -vv my.pdf` but it
would really help if I have access to this file or a sample to reproduce this issue.

You can either post it here or send me an email: hhrutter@gmail.com

Thank you for using pdfcpu 💚

**Comment by lhq0826** [comment]
```php
<?php

var_dump(exec("pdfcpu version"));
```
run it on the browser with php-fpm nginx not valid but php-cli is work

**Comment by hhrutter** [comment]
I am not sure I understand your problem exactly but I am guessing you are trying to call the pdfcpu binary from php-fpm.
The reason for your problem may be that pdfcpu is unable to locate it's working directory during package init().

Try setting $HOME to /tmp.

Also take a look at: #186 and #225 

Here is also a [link](https://stackoverflow.com/questions/57923943/executing-a-golang-binary-from-phps-shell-exec-function) that may help you.

**Comment by lhq0826** [comment]
It works, thank you very much
