### ISSUE TITLE
Failed access to font dir: neither $XDG_CONFIG_HOME nor $HOME are defined

### ISSUE THREAD

**Issue by zhumengyifang** [pdfcpu/pdfcpu#231]
starting failed. Do I need to do anything on Linux

**Comment by hhrutter** [comment]
Try setting $HOME for the user executing pdfcpu.
See #230, #186,  #225

**Comment by henrixapp** [comment]
Hi,

I had an similar issue running pdfcpu as Wasm, naturally there is no $HOME in browser. I simply

```
go mod vendor
sed -i 's/init(/init2(/g' vendor/github.com/pdfcpu/pdfcpu/pkg/font/metrics.go
```

because I didn't need font support for my project. I know it is not best practise, but it works for my project (https://github.com/henrixapp/pdfcomprezzor).

**Comment by hhrutter** [comment]
Please open a separate issue for your issue, and describe your use case.
