### ISSUE TITLE
wasm build issues

### ISSUE THREAD

**Issue by henrixapp** [pdfcpu/pdfcpu#232]
When compiling a program using pdfcpu for extraction/writing of images in pdfs in browser, I encountered the following error (in node.js everything works fine).

```
Failed access to font dir: neither $XDG_CONFIG_HOME nor $HOME are defined
```

The problem is simply caused by the fact that there is no "$HOME" in browsers to read/write from in `pkg/font/metrics.go`.

Would it be possible to either run the initialisation of fonts when actually needed, or prevent the program/ init of `pkg/font/metrics.go`, when on GOOS=js?

 As I have described before, I simply bypass, these checks by running following commands before build, which is kind of hacky and I would like to stop it:

```
go mod vendor
sed -i 's/init(/init2(/g' vendor/github.com/pdfcpu/pdfcpu/pkg/font/metrics.go
```

Thank you for this great library! It really makes fun using it.

You can find my source code here https://github.com/henrixapp/pdfcomprezzor , it was inspired by https://dev.to/wcchoi/browser-side-pdf-processing-with-go-and-webassembly-13hn

**Comment by hhrutter** [comment]
Hi!

Nice project 👍 
I am working on a solution that allows to disable config dir usage for usecases like yours.
Stay tuned for the upcoming release.

Thank you for using pdfcpu 💚

**Comment by henrixapp** [comment]
Thank you for fixing it that quick!

**Comment by hhrutter** [comment]
👍  Let me know how this works out for you.

**Comment by henrixapp** [comment]
It works out of the 📦 . But I think you have added an extra dependency for yaml that is bloating my binary a little bit (about 1 MB). I am still investigating, how I can shrink the binary. Maybe I remove some init functions (not the nice way).

**Comment by hhrutter** [comment]
OK. That's a very good point. 👍 
Since I am using yaml only for parsing I will see to do that myself and get rid of this dependency.

**Comment by hhrutter** [comment]
The latest commit does not have the yaml lib dependency for JS.
Please give it a shot and let me know how it goes.

**Comment by henrixapp** [comment]
Yes it works (reduces the size by about 500kb), thank you. I had to delete `vendor/github.com/pdfcpu/pdfcpu/pkg/pdfcpu/parseConfig.go` to build my project with pdfcpu as dependency, I don't think this is intended.

The error is 
```
vendor/github.com/pdfcpu/pdfcpu/pkg/pdfcpu/parseConfig_js.go:180:6: parseConfigFile redeclared in this block
        previous declaration at vendor/github.com/pdfcpu/pdfcpu/pkg/pdfcpu/parseConfig.go:86:54
```

Searching a little bit around, I found this solution to the problem: Move the `//+build !js` tag upwards in `parseConfig.go`, so that it is above the license statement and it works like a charm! Thank you for the support. I might look around a little in pdfcpu later next week and add some `//+build !js` tags in fork, if you wish to I would then submit a pull request.

**Comment by hhrutter** [comment]
Honestly, I don't have much experience with how build tags work.
Did you explicitly opt-in to vendoring?

Also are you saying that the creation of the vendor/ entry depends on the location of the build tag in the source file? 
Do you have more info about that?

**Comment by henrixapp** [comment]
> Did you explicitly opt-in to vendoring?

Kind of, had to, in order to find/fix this error. If you do not vendor, the path just changes. The main issue is that the Go compiler seems to ignore your `//build !js` if it is not on top of the file, causing a failed build.

> Also are you saying that the creation of the vendor/ entry depends on the location of the build tag in the source file?
Do you have more info about that?

No, I just want to point out, that the tag is in the wrong spot. According to https://dave.cheney.net/2013/10/12/how-to-use-conditional-compilation-with-the-go-build-tool it is also redundant to use suffix and tag for controlling the build, so you should be able to remove the tag in `parseConfig_js.go`.

> We can also discuss on slack either #pdfcpu channel or DM is ok.

ok great. leaving this for now.

**Comment by hhrutter** [comment]
Thank you for your contribution 💚 

For now I am closing this as fixed.

We can always discuss other needed modifications for the js build as you are making progress 
which may require reopening this.
