### ISSUE TITLE
Possibly malformed PDF

### ISSUE THREAD

**Issue by zhumengyifang** [pdfcpu/pdfcpu#233]
Hi,
    I try use AddWatermarks  But there was an error

pdf size ：2763049
       2.8M

page count:
     138

err Info:
      object: non matching objNr(4629) or generationNumber(0) tags found.

code :

    err = api.AddWatermarks(bytes.NewReader(respByte), buffer, nil, wm, nil)
    if err != nil {
    	fmt.Println("this err")
    }

code :

       obj, endInd, streamInd, streamOffset, err := object(ctx, offset, objNr, genNr)
	if err != nil {
		return nil, err
	}

     because  objNr==4626   *objectNr==4629 so:

      if objNr != *objectNr || genNr != *generationNr {
		return nil, 0, 0, 0, errors.Errorf("object: non matching objNr(%d) or generationNumber(%d) tags found.", *objectNr, *generationNr)
      	}

![image](https://user-images.githubusercontent.com/39289075/94528362-d9df2180-026a-11eb-819f-24bb23264d4d.png)

Any information is helpful

**Comment by hhrutter** [comment]
Hello!

This file seems to be invalid.

If and only if you can open it in Adobe Reader or Mac Preview I can help you
if you can provide me the file or a sample in order to debug and analyze this.
You can also email me at hrutter@gmail.com

Thank you for using pdfcpu 💚

**Comment by zhumengyifang** [comment]
Thank you very much:
file:
[demo.pdf](https://github.com/pdfcpu/pdfcpu/files/5302863/demo.pdf)

demo code:
func GetWatermarkPdf() (string, error) {
	wm, err := pdfcpu.ParseTextWatermarkDetails("text", fmt.Sprintf("scalefactor:0.9 abs,rot:0,op:0.05,points: 15"), true)
	if err != nil {
		fmt.Println(err)
	}
	err = api.AddWatermarksFile("inFilePath", "outFilePath", nil, wm, nil)
	if err != nil {
		fmt.Println(err)
	}

	return "reader", nil
}

**Comment by hhrutter** [comment]
OK I take a look!
.. and thanks for being a sponsor 💚 💚 💚

**Comment by zhumengyifang** [comment]
So now there's no problem

**Comment by zhumengyifang** [comment]
Hi:
        Is there any progress？

**Comment by hhrutter** [comment]
Hello!

This was fixed instantly with commit [63d5b3](https://github.com/pdfcpu/pdfcpu/commit/63d5b3d355b87fb8b9418e97f361b6a3d66171b3).
Just fetch everything and `go install`.

Otherwise this will be in the next release.
Usually a release contains all git commits since the last release plus any new feature or enhancement.

**Comment by zhumengyifang** [comment]
Hello! 
       Please tell me which release it is! thanks

**Comment by hhrutter** [comment]
It's in the upcoming release v0.3.7 which will be ready by end of October.

**Comment by hhrutter** [comment]
Hello!
v0.3.7 will be out in 2 days!
Thank you for you patience!

**Comment by hhrutter** [comment]
Release v0.3.7 is out!
This includes this fix!
Thank you for your support!
💚

**Comment by zhumengyifang** [comment]
Thank you !
