### ISSUE TITLE
Factur-X PDF Attachment Extraction results in files of zero length

### ISSUE THREAD

**Issue by MatthiasPetermann** [pdfcpu/pdfcpu#237]
Hello everybody,

I am trying to extract an attachment from a PDF file:

```
PS D:\git\pdfcpu\cmd\pdfcpu> .\pdfcpu.exe attach list D:\factur-x\zugferd211de\ZUGFeRD211_DE\Beispiele\MINIMUM\zugferd_2p1_MINIMUM_Rechnung.pdf
factur-x.xml
PS D:\git\pdfcpu\cmd\pdfcpu> .\pdfcpu.exe attach extract D:\factur-x\zugferd211de\ZUGFeRD211_DE\Beispiele\MINIMUM\zugferd_2p1_MINIMUM_Rechnung.pdf d:\tmp
```

The file is created under d:\tmp, but it is 0 bytes long - so it contains no data. I've tried it with several Factur-X-PDFs and it doesn't seem to work with any. Could it be the PDF version (PDF/A)? Can anyone confirm this? 

Thanks & best regards
Matthias

**Comment by hhrutter** [comment]
Works on my Mac:

```
Go-> pdfcpu att list zugferd_2p1_MINIMUM_Rechnung.pdf
factur-x.xml
Go-> pdfcpu att ext zugferd_2p1_MINIMUM_Rechnung.pdf .
Go-> lsd factur-x.xml
-rwxr-xr-x  1 horstrutter  staff   8.4K Oct  8 18:59 factur-x.xml*
```

Maybe there is an issue with absolute Win paths.
Please also check if you can extract to the current dir.

**Comment by hhrutter** [comment]
Please let me know if your still have this problem otherwise I will close this within a couple of days due to inactivity.

**Comment by MatthiasPetermann** [comment]
Thanks for coming back to my request. I will perform the suggested test asap and provide feedback. In the meantime I did some similiar testing with the api which seems to work from a technical perspective. Kind regards, Matthias
