### ISSUE TITLE
corrupt pdf stream - no header version available after attaching file

### ISSUE THREAD

**Issue by Fank** [pdfcpu/pdfcpu#239]
I tried to attach a xml file to a PDF/A-3 file for [ZUGFeRD](https://www.pdf-tools.com/pdf20/en/zugferd/)

Code:
```go
	err := api.AddAttachmentsFile("/home/florian/Downloads/pdfa3.pdf", "/home/florian/Downloads/pdfa3_2.pdf", []string{"/home/florian/Downloads/factur-x.xml"}, false, &pdfcpu.Configuration{
		Reader15:        true,
		ValidationMode:  pdfcpu.ValidationStrict,
		WriteXRefStream: true,
	})
```

Original file which were converted to PDF 1.7 by using Ghostscript   
[pdfa3.pdf](https://github.com/pdfcpu/pdfcpu/files/5402826/pdfa3.pdf)

attaching xml file [factur-x.zip](https://github.com/pdfcpu/pdfcpu/files/5402856/factur-x.zip)    
to PDF [pdfa3_2.pdf](https://github.com/pdfcpu/pdfcpu/files/5402857/pdfa3_2.pdf)

![image](https://user-images.githubusercontent.com/1900106/96469755-dcabb180-122d-11eb-8cde-944bab76b12e.png)

```
~/go/bin/pdfcpu validate -mode strict Downloads/pdfa3_2.pdf 
validating(mode=strict) Downloads/pdfa3_2.pdf ...
Read: xRefTable failed: pdfcpu: headerVersion: corrupt pdf stream - no header version available
```

Environment
```
$ go version
go version go1.14.4 linux/amd64
$ cat go.mod | grep pdfcpu
	github.com/pdfcpu/pdfcpu v0.3.6

```

**Comment by hhrutter** [comment]
Hi!
Try to pass *nil* for your configuration and let me know how that goes.

**Comment by Fank** [comment]
Thanks for the Info, it looks like its working now.
No clue why i didn't tried it with `nil`.
Thanks for the quick help.
