### ISSUE TITLE
api：merge Error

### ISSUE THREAD

**Issue by LQ1314521** [pdfcpu/pdfcpu#240]
hello author:

error: dereferenceObject: problem dereferencing stream 5: pdfcpu: loadEncodedStreamContent: missing streamLength

code: 
 inFiles := []string{"kw1.pdf", "kw2.pdf"}
	err := api.MergeAppendFile(inFiles, "out.pdf", nil)
	if err != nil {
		log.Println(err)
	}

**Comment by hhrutter** [comment]
Hello!

If you can share here or send sample files to hrutter@gmail.com I can reproduce and possibly fix this.

Thank you for using pdfcpu 💚

**Comment by LQ1314521** [comment]
package main

import (
	"github.com/pdfcpu/pdfcpu/pkg/api"
	"log"
)

func main() {
	inFiles := []string{"kw1.pdf", "kw2.pdf"}
	err := api.MergeAppendFile(inFiles, "out.pdf", nil)
	if err != nil {
		log.Println(err)
	}
}

**Comment by LQ1314521** [comment]
thank you...

**Comment by hhrutter** [comment]
Hello!

I am sorry, I gave you the wrong email address before. 
The correct one is: hhrutter@gmail.com

Have you checked both PDFs validate before you tried to merge them?
You can do that that like so: `pdfcpu val my.pdf`

I need to reproduce this problem so I can provide a fix for you.
Please post  you can share here or send me an email.

Thank you for using pdfcpu 💚

**Comment by hhrutter** [comment]
Please send me a sample and I try to provide a fix.
If I don't hear back I will close this due to inactivity.
Thank you for using pdfcpu 💚 

请给我一个样本，我尝试提供修复
如果我没有收到回音，则由于不活动而将其关闭。
感谢您使用pdfcpu 💚
