### ISSUE TITLE
headerVersion: corrupt pdf stream - no header version available

### ISSUE THREAD

**Issue by mcasper** [pdfcpu/pdfcpu#241]
Hey folks 👋 I've got a case of what I assume is yet another malformed PDF, along the lines of https://github.com/pdfcpu/pdfcpu/issues/136 and https://github.com/pdfcpu/pdfcpu/issues/91

After opening the PDF and saving with a PDF editing application (in my case Adobe Acrobat Reader DC), `pdfcpu` then considers the PDF valid (presumably because the application repaired it).

Attached is the `validate -vv` log and the offending PDF, please let me know if I can provide anything else of use, and thank you for this project!

[crash.log](https://github.com/pdfcpu/pdfcpu/files/5424460/crash.log)
[test_scan_glass.pdf](https://github.com/pdfcpu/pdfcpu/files/5424462/test_scan_glass.pdf)

**Comment by hhrutter** [comment]
Thanks, I'll check it out.

**Comment by hhrutter** [comment]
This file has no´info dict at all and is therefore suspicious to me.
Which PDF writer was used to create this?

**Comment by mcasper** [comment]
This is the result of scanning something on our office scanner, a [Sharp MX-4070N](https://business.sharpusa.com/Document-Systems/Models/Details/MX-M4070)

**Comment by hhrutter** [comment]
Fixed with the latest commit!

**Comment by mcasper** [comment]
Thank you so much!
