### ISSUE TITLE
Parsing errors

### ISSUE THREAD

**Issue by tballison** [pdfcpu/pdfcpu#246]
I recently ran pdfcpu on our bugtracker corpus on Apache Tika.  I timed out `pdfcpu validate -mode strict` after 2 minutes on the following files:

GHOSTSCRIPT-696022-0.pdf
PDFIUM-875-0.pdf
GHOSTSCRIPT-693527-0.pdf
qpdf-149-0.zip-0.pdf
qpdf-LINK-305-0.pdf
PDFBOX-3922-0.pdf
GHOSTSCRIPT-696121-3.pdf
PDFBOX-4131-1.pdf
PDFBOX-4131-0.pdf
GHOSTSCRIPT-698454-0.pdf
GHOSTSCRIPT-698409-0.pdf
POPPLER-673-0.pdf

Files can be found here under the projects' subdirectories: https://corpora.tika.apache.org/base/docs/bug_trackers/

Happy to make these files easier to use.  Let me know if we can help.

Cheers!

**Comment by hhrutter** [comment]
Hey, nice.. thanks for reporting these..
I'll take a look.

**Comment by hhrutter** [comment]
OK, so I didn't find POPPLER-673-0.pdf

The rest of the files may now be validated using the latest commit
with the exception being GHOSTSCRIPT-696121-0.pdf, which contains a really messed up xref section with invalid offsets.
Since Adobe Reader complains about it with an error on opening I am not worried about this one.

**Comment by tballison** [comment]
Woah, that was fast.  Thank you!

On poppler...looks like I forgot to add the gitlab files to our public corpus.  Thank you for helping _me_ find a bug!

The direct link to the file is: https://www.ecfr.eu/page/ECFR269_EU_COALITION_EXPLORER_2018_V1.10.pdf

The overall issue is: https://gitlab.freedesktop.org/poppler/poppler/-/issues/673

**Comment by hhrutter** [comment]
>> The direct link to the file is: https://www.ecfr.eu/page/ECFR269_EU_COALITION_EXPLORER_2018_V1.10.pdf
This link is dead.

**Comment by petervwyatt** [comment]
The Wayback Machine is your friend: https://web.archive.org/web/20200302050235/https://www.ecfr.eu/page/ECFR269_EU_COALITION_EXPLORER_2018_V1.10.pdf

**Comment by hhrutter** [comment]
Can you guys verify this for me please:

If I *Save as* this link I get a damaged junk. If I open this url within the browser the PDF gets rendered and then after saving pdfcpu couldn't be happier, but I am not sure if this is the very problematic file because the meta info does not mention POPPLER at all: 
```
Go-> pdfcpu info ECFR269_EU_COALITION_EXPLORER_2018_V1.10.pdf
         PDF version: 1.7
          Page count: 1113
           Page size: 67.73 x 41.13 cm
............................................
               Title: EU Coalition Explorer
              Author: ECFR European Council on Foreign Relations
             Subject: Data of the EU28 Survey on Coalition Building in the European Union
        PDF Producer: Adobe PDF library 10.01
     Content creator: Adobe Illustrator CS6 (Windows)
       Creation date: D:20181029193725+01'00'
   Modification date: D:20181112213900+01'00'
            Keywords: EU Coalition Explorer
                      EU28 Survey
                      Rethink Europe
                      ECFR
                      ECFR Berlin
                      European Council on Foreign Relations
                      Josef Janning
                      Christoph Klavehn
                      Almut Müller
                      Wiebke Ewering
                      Denkbuilder
                      Dieter Dollacker
                      Dirk Waldik
............................................
              Tagged: No
              Hybrid: No
          Linearized: No
  Using XRef streams: Yes
Using object streams: Yes
         Watermarked: No
............................................
           Encrypted: No
         Permissions: Full access
```

**Comment by tballison** [comment]
It turns out I have a local copy of the file from an intermediate crawl.  The sha256: 6ebce47514e8a4f07a58034557f0cb4566c25cf15d1b08f53e255bc4c6e89bb8, and that checks out with what I just downloaded from the internet archive.

**Comment by tballison** [comment]
Again, many thanks!
