### ISSUE TITLE
headerVersion: corrupt pdf stream - no header version available

### ISSUE THREAD

**Issue by simon-franz** [pdfcpu/pdfcpu#253]
HI there, 
I'm stumpled upon a pdf with an invalid header version. Chrome and Adobe Acrobat Reader can open and display the file without problems nontheless.

The error message when validating the file is
`Read: xRefTable failed: pdfcpu: headerVersion: corrupt pdf stream - no header version available`

Executing 
`pdfcpu validate -vv "file2.pdf"`

results into:
` READ: 2020/11/27 15:59:24 Read: begin
 INFO: 2020/11/27 15:59:24 PDF Version 1.5 conforming reader
 READ: 2020/11/27 15:59:24 readXRefTable: begin
 READ: 2020/11/27 15:59:24 scanning for offsetLastXRefSection starting at 494938
 READ: 2020/11/27 15:59:24 Offset last xrefsection: 495122
 READ: 2020/11/27 15:59:24 buildXRefTableStartingAt: begin
 READ: 2020/11/27 15:59:24 headerVersion begin
Fatal: pdfcpu: headerVersion: corrupt pdf stream - no header version available
github.com/pdfcpu/pdfcpu/pkg/pdfcpu.headerVersion
	/Users/horstrutter/go/src/github.com/pdfcpu/pdfcpu/pkg/pdfcpu/read.go:1011
github.com/pdfcpu/pdfcpu/pkg/pdfcpu.buildXRefTableStartingAt
	/Users/horstrutter/go/src/github.com/pdfcpu/pdfcpu/pkg/pdfcpu/read.go:1160
github.com/pdfcpu/pdfcpu/pkg/pdfcpu.readXRefTable
	/Users/horstrutter/go/src/github.com/pdfcpu/pdfcpu/pkg/pdfcpu/read.go:1225
github.com/pdfcpu/pdfcpu/pkg/pdfcpu.Read
	/Users/horstrutter/go/src/github.com/pdfcpu/pdfcpu/pkg/pdfcpu/read.go:73
github.com/pdfcpu/pdfcpu/pkg/api.ReadContext
	/Users/horstrutter/go/src/github.com/pdfcpu/pdfcpu/pkg/api/api.go:48
github.com/pdfcpu/pdfcpu/pkg/api.Validate
	/Users/horstrutter/go/src/github.com/pdfcpu/pdfcpu/pkg/api/validate.go:42
github.com/pdfcpu/pdfcpu/pkg/api.ValidateFile
	/Users/horstrutter/go/src/github.com/pdfcpu/pdfcpu/pkg/api/validate.go:91
github.com/pdfcpu/pdfcpu/pkg/cli.Validate
	/Users/horstrutter/go/src/github.com/pdfcpu/pdfcpu/pkg/cli/cli.go:33
github.com/pdfcpu/pdfcpu/pkg/cli.Process
	/Users/horstrutter/go/src/github.com/pdfcpu/pdfcpu/pkg/cli/process.go:35
main.process
	/Users/horstrutter/go/src/github.com/pdfcpu/pdfcpu/cmd/pdfcpu/process.go:88
main.processValidateCommand
	/Users/horstrutter/go/src/github.com/pdfcpu/pdfcpu/cmd/pdfcpu/process.go:126
main.commandMap.process
	/Users/horstrutter/go/src/github.com/pdfcpu/pdfcpu/cmd/pdfcpu/cmd.go:145
main.main
	/Users/horstrutter/go/src/github.com/pdfcpu/pdfcpu/cmd/pdfcpu/main.go:55
runtime.main
	/Users/horstrutter/gotip/src/runtime/proc.go:204
runtime.goexit
	/Users/horstrutter/gotip/src/runtime/asm_amd64.s:1374
Read: xRefTable failed
github.com/pdfcpu/pdfcpu/pkg/pdfcpu.Read
	/Users/horstrutter/go/src/github.com/pdfcpu/pdfcpu/pkg/pdfcpu/read.go:74
github.com/pdfcpu/pdfcpu/pkg/api.ReadContext
	/Users/horstrutter/go/src/github.com/pdfcpu/pdfcpu/pkg/api/api.go:48
github.com/pdfcpu/pdfcpu/pkg/api.Validate
	/Users/horstrutter/go/src/github.com/pdfcpu/pdfcpu/pkg/api/validate.go:42
github.com/pdfcpu/pdfcpu/pkg/api.ValidateFile
	/Users/horstrutter/go/src/github.com/pdfcpu/pdfcpu/pkg/api/validate.go:91
github.com/pdfcpu/pdfcpu/pkg/cli.Validate
	/Users/horstrutter/go/src/github.com/pdfcpu/pdfcpu/pkg/cli/cli.go:33
github.com/pdfcpu/pdfcpu/pkg/cli.Process
	/Users/horstrutter/go/src/github.com/pdfcpu/pdfcpu/pkg/cli/process.go:35
main.process
	/Users/horstrutter/go/src/github.com/pdfcpu/pdfcpu/cmd/pdfcpu/process.go:88
main.processValidateCommand
	/Users/horstrutter/go/src/github.com/pdfcpu/pdfcpu/cmd/pdfcpu/process.go:126
main.commandMap.process
	/Users/horstrutter/go/src/github.com/pdfcpu/pdfcpu/cmd/pdfcpu/cmd.go:145
main.main
	/Users/horstrutter/go/src/github.com/pdfcpu/pdfcpu/cmd/pdfcpu/main.go:55
runtime.main
	/Users/horstrutter/gotip/src/runtime/proc.go:204
runtime.goexit
	/Users/horstrutter/gotip/src/runtime/asm_amd64.s:1374`

Thanks in advance!

**Comment by hhrutter** [comment]
Hello,
In order to fix that I would need to have this file in my hands.
If this is not possible you can cut off the first 100 bytes also, but the whole file would be better for analysis and proper testing.
Thanks for using pdfcpu 💚

**Comment by simon-franz** [comment]
Thanks for your fast response!
I have contacted you with the corresponding file.

**Comment by hhrutter** [comment]
This should work with the latest commit.

**Comment by simon-franz** [comment]
Thanks confirmend!
