### ISSUE TITLE
dereferenceObject: problem dereferencing stream 11: EOF

### ISSUE THREAD

**Issue by simon-franz** [pdfcpu/pdfcpu#256]
Hi threre

I try to process a file from "HP Scan Extended Application" with PDF Version 1.7.
The pdf is normally displayed in chrome and acrobat reader.

When validating the file this error comes up:
`dereferenceObject: problem dereferencing stream 11: EOF`

The detailed output looks like this:
`validating(mode=relaxed) file.pdf ...
 READ: 2020/12/01 13:36:59 Read: begin
 INFO: 2020/12/01 13:36:59 PDF Version 1.5 conforming reader
 READ: 2020/12/01 13:36:59 readXRefTable: begin
 READ: 2020/12/01 13:36:59 scanning for offsetLastXRefSection starting at 515183
 READ: 2020/12/01 13:36:59 Offset last xrefsection: 515316
 READ: 2020/12/01 13:36:59 buildXRefTableStartingAt: begin
 READ: 2020/12/01 13:36:59 headerVersion begin
 READ: 2020/12/01 13:36:59 headerVersion: end, found header version: 1.7
 READ: 2020/12/01 13:36:59 newPositionedReader: positioned to offset: 515316
 READ: 2020/12/01 13:36:59 line: <xref>
 READ: 2020/12/01 13:36:59 buildXRefTableStartingAt: found xref section
 READ: 2020/12/01 13:36:59 parseXRefSection begin
 READ: 2020/12/01 13:36:59 parseXRefSection: <0 13>
 READ: 2020/12/01 13:36:59 parseXRefTableSubSection: begin
 READ: 2020/12/01 13:36:59 detected xref subsection, startObj=0 length=13
 READ: 2020/12/01 13:36:59 parseXRefTableEntry: begin
 READ: 2020/12/01 13:36:59 parseXRefTableEntry: Object #0 is unused, next free is object#0, generation=65535
 READ: 2020/12/01 13:36:59 parseXRefTableEntry: Insert new xreftable entry for Object 0
 READ: 2020/12/01 13:36:59 parseXRefTableEntry: end
 READ: 2020/12/01 13:36:59 parseXRefTableEntry: begin
 READ: 2020/12/01 13:36:59 parseXRefTableEntry: Object #1 is in use at offset=9, generation=0
 READ: 2020/12/01 13:36:59 parseXRefTableEntry: Insert new xreftable entry for Object 1
 READ: 2020/12/01 13:36:59 parseXRefTableEntry: end
 READ: 2020/12/01 13:36:59 parseXRefTableEntry: begin
 READ: 2020/12/01 13:36:59 parseXRefTableEntry: Object #2 is in use at offset=345553, generation=0
 READ: 2020/12/01 13:36:59 parseXRefTableEntry: Insert new xreftable entry for Object 2
 READ: 2020/12/01 13:36:59 parseXRefTableEntry: end
 READ: 2020/12/01 13:36:59 parseXRefTableEntry: begin
 READ: 2020/12/01 13:36:59 parseXRefTableEntry: Object #3 is in use at offset=345650, generation=0
 READ: 2020/12/01 13:36:59 parseXRefTableEntry: Insert new xreftable entry for Object 3
 READ: 2020/12/01 13:36:59 parseXRefTableEntry: end
 READ: 2020/12/01 13:36:59 parseXRefTableEntry: begin
 READ: 2020/12/01 13:36:59 parseXRefTableEntry: Object #4 is in use at offset=514723, generation=0
 READ: 2020/12/01 13:36:59 parseXRefTableEntry: Insert new xreftable entry for Object 4
 READ: 2020/12/01 13:36:59 parseXRefTableEntry: end
 READ: 2020/12/01 13:36:59 parseXRefTableEntry: begin
 READ: 2020/12/01 13:36:59 parseXRefTableEntry: Object #5 is in use at offset=345859, generation=0
 READ: 2020/12/01 13:36:59 parseXRefTableEntry: Insert new xreftable entry for Object 5
 READ: 2020/12/01 13:36:59 parseXRefTableEntry: end
 READ: 2020/12/01 13:36:59 parseXRefTableEntry: begin
 READ: 2020/12/01 13:36:59 parseXRefTableEntry: Object #6 is in use at offset=514417, generation=0
 READ: 2020/12/01 13:36:59 parseXRefTableEntry: Insert new xreftable entry for Object 6
 READ: 2020/12/01 13:36:59 parseXRefTableEntry: end
 READ: 2020/12/01 13:36:59 parseXRefTableEntry: begin
 READ: 2020/12/01 13:36:59 parseXRefTableEntry: Object #7 is in use at offset=514514, generation=0
 READ: 2020/12/01 13:36:59 parseXRefTableEntry: Insert new xreftable entry for Object 7
 READ: 2020/12/01 13:36:59 parseXRefTableEntry: end
 READ: 2020/12/01 13:36:59 parseXRefTableEntry: begin
 READ: 2020/12/01 13:36:59 parseXRefTableEntry: Object #8 is in use at offset=514787, generation=0
 READ: 2020/12/01 13:36:59 parseXRefTableEntry: Insert new xreftable entry for Object 8
 READ: 2020/12/01 13:36:59 parseXRefTableEntry: end
 READ: 2020/12/01 13:36:59 parseXRefTableEntry: begin
 READ: 2020/12/01 13:36:59 parseXRefTableEntry: Object #9 is in use at offset=514838, generation=0
 READ: 2020/12/01 13:36:59 parseXRefTableEntry: Insert new xreftable entry for Object 9
 READ: 2020/12/01 13:36:59 parseXRefTableEntry: end
 READ: 2020/12/01 13:36:59 parseXRefTableEntry: begin
 READ: 2020/12/01 13:36:59 parseXRefTableEntry: Object #10 is in use at offset=514887, generation=0
 READ: 2020/12/01 13:36:59 parseXRefTableEntry: Insert new xreftable entry for Object 10
 READ: 2020/12/01 13:36:59 parseXRefTableEntry: end
 READ: 2020/12/01 13:36:59 parseXRefTableEntry: begin
 READ: 2020/12/01 13:36:59 parseXRefTableEntry: Object #11 is in use at offset=515035, generation=0
 READ: 2020/12/01 13:36:59 parseXRefTableEntry: Insert new xreftable entry for Object 11
 READ: 2020/12/01 13:36:59 parseXRefTableEntry: end
 READ: 2020/12/01 13:36:59 parseXRefTableEntry: begin
 READ: 2020/12/01 13:36:59 parseXRefTableEntry: Object #12 is in use at offset=515116, generation=0
 READ: 2020/12/01 13:36:59 parseXRefTableEntry: Insert new xreftable entry for Object 12
 READ: 2020/12/01 13:36:59 parseXRefTableEntry: end
 READ: 2020/12/01 13:36:59 parseXRefTableSubSection: end
 READ: 2020/12/01 13:36:59 parseXRefSection: All subsections read!
 READ: 2020/12/01 13:36:59 parseXRefSection: parsing trailer dict..
 READ: 2020/12/01 13:36:59 line (len 7) <trailer>
 READ: 2020/12/01 13:36:59 line: <>
 READ: 2020/12/01 13:36:59 line: <<<>
 READ: 2020/12/01 13:36:59 scanTrailer dictBuf after start tag: <<<>
 READ: 2020/12/01 13:36:59 scanTrailer dictBuf next line: </Size 13>
 READ: 2020/12/01 13:36:59 scanTrailer dictBuf next line: </Root 8 0 R>
 READ: 2020/12/01 13:36:59 scanTrailer dictBuf next line: </Info 9 0 R>
 READ: 2020/12/01 13:36:59 scanTrailer dictBuf next line: </Info 10 0 R>
 READ: 2020/12/01 13:36:59 scanTrailer dictBuf next line: </Info 11 0 R>
 READ: 2020/12/01 13:36:59 scanTrailer dictBuf next line: </Info 12 0 R>
 READ: 2020/12/01 13:36:59 scanTrailer dictBuf next line: <>>>
 READ: 2020/12/01 13:36:59 processTrailer: trailerString: (len:78) <<< /Size 13 /Root 8 0 R /Info 9 0 R /Info 10 0 R /Info 11 0 R /Info 12 0 R >> >
 READ: 2020/12/01 13:36:59 processTrailer: trailerDict:
<<
	<Info, (9 0 R)>
	<Root, (8 0 R)>
	<Size, 13>
>>
 READ: 2020/12/01 13:36:59 parseTrailerDict begin
 READ: 2020/12/01 13:36:59 parseTrailerInfo begin
 READ: 2020/12/01 13:36:59 parseTrailerInfo: Root object: (8 0 R)
 READ: 2020/12/01 13:36:59 parseTrailerInfo: Info object: (9 0 R)
 READ: 2020/12/01 13:36:59 parseTrailerInfo end
 READ: 2020/12/01 13:36:59 parseTrailerDict end
 READ: 2020/12/01 13:36:59 buildXRefTableStartingAt: end
TRACE: 2020/12/01 13:36:59 EnsureValidFreeList begin
TRACE: 2020/12/01 13:36:59 EnsureValidFreeList: empty free list.
 READ: 2020/12/01 13:36:59 readXRefTable: end
 READ: 2020/12/01 13:36:59 dereferenceXRefTable: begin
 READ: 2020/12/01 13:36:59 decodeObjectStreams: begin
 READ: 2020/12/01 13:36:59 decodeObjectStreams: end
 READ: 2020/12/01 13:36:59 dereferenceObjects: begin
 READ: 2020/12/01 13:36:59 dereferenceObject: begin, dereferencing object 0
 READ: 2020/12/01 13:36:59 free object 0
 READ: 2020/12/01 13:36:59 dereferenceObject: begin, dereferencing object 1
 READ: 2020/12/01 13:36:59 in use object 1
 READ: 2020/12/01 13:36:59 dereferenceObject: dereferencing object 1
 READ: 2020/12/01 13:36:59 ParseObject: begin, obj#1, offset:9
 READ: 2020/12/01 13:36:59 newPositionedReader: positioned to offset: 9
 READ: 2020/12/01 13:36:59 buffer: endInd=-1 streamInd=160
 READ: 2020/12/01 13:36:59 object: big stream, we parse object until stream
 READ: 2020/12/01 13:36:59 pdfFilterPipeline: begin
 READ: 2020/12/01 13:36:59 pdfFilterPipeline: end
 READ: 2020/12/01 13:36:59 streamDictForObject: end, Streamobject #1
 READ: 2020/12/01 13:36:59 LoadEncodedStreamContent: begin
<<
	<BitsPerComponent, 8>
	<ColorSpace, DeviceRGB>
	<Filter, [DCTDecode]>
	<Height, 2338>
	<Length, 345360>
	<Name, Im1>
	<Subtype, Image>
	<Type, XObject>
	<Width, 1654>
>>
 READ: 2020/12/01 13:36:59 newPositionedReader: positioned to offset: 176
 READ: 2020/12/01 13:36:59 LoadEncodedStreamContent: seeked to offset:176
 READ: 2020/12/01 13:36:59 readContentStream: begin streamLength:345360
 READ: 2020/12/01 13:36:59 readContentStream: count=345360, buflen=345360(54510)
 READ: 2020/12/01 13:36:59 readContentStream: end
 READ: 2020/12/01 13:36:59 LoadEncodedStreamContent: end: len(streamDictRaw)=345360
 READ: 2020/12/01 13:36:59 saveDecodedStreamContent: begin decode=false
 READ: 2020/12/01 13:36:59 dereferenceObject: end obj 1 of 13
<<<
	<BitsPerComponent, 8>
	<ColorSpace, DeviceRGB>
	<Filter, [DCTDecode]>
	<Height, 2338>
	<Length, 345360>
	<Name, Im1>
	<Subtype, Image>
	<Type, XObject>
	<Width, 1654>
>>>
 READ: 2020/12/01 13:36:59 logStream: no stream content
 READ: 2020/12/01 13:36:59 dereferenceObject: begin, dereferencing object 2
 READ: 2020/12/01 13:36:59 in use object 2
 READ: 2020/12/01 13:36:59 dereferenceObject: dereferencing object 2
 READ: 2020/12/01 13:36:59 ParseObject: begin, obj#2, offset:345553
 READ: 2020/12/01 13:36:59 newPositionedReader: positioned to offset: 345553
 READ: 2020/12/01 13:36:59 buffer: endInd=90 streamInd=26
 READ: 2020/12/01 13:36:59 object: small stream within buffer, parse until stream
 READ: 2020/12/01 13:36:59 pdfFilterPipeline: begin
 READ: 2020/12/01 13:36:59 streamDictForObject: end, Streamobject #2
 READ: 2020/12/01 13:36:59 LoadEncodedStreamContent: begin
<<
	<Length, 47>
>>
 READ: 2020/12/01 13:36:59 newPositionedReader: positioned to offset: 345586
 READ: 2020/12/01 13:36:59 LoadEncodedStreamContent: seeked to offset:345586
 READ: 2020/12/01 13:36:59 readContentStream: begin streamLength:47
 READ: 2020/12/01 13:36:59 readContentStream: count=47, buflen=47(2F)
 READ: 2020/12/01 13:36:59 readContentStream: end
 READ: 2020/12/01 13:36:59 LoadEncodedStreamContent: end: len(streamDictRaw)=47
 READ: 2020/12/01 13:36:59 saveDecodedStreamContent: begin decode=false
 READ: 2020/12/01 13:36:59 dereferenceObject: end obj 2 of 13
<<<
	<Length, 47>
>>>
 READ: 2020/12/01 13:36:59 logStream: no stream content
 READ: 2020/12/01 13:36:59 dereferenceObject: begin, dereferencing object 3
 READ: 2020/12/01 13:36:59 in use object 3
 READ: 2020/12/01 13:36:59 dereferenceObject: dereferencing object 3
 READ: 2020/12/01 13:36:59 ParseObject: begin, obj#3, offset:345650
 READ: 2020/12/01 13:36:59 newPositionedReader: positioned to offset: 345650
 READ: 2020/12/01 13:36:59 object: small obj w/o stream, parse until endobj
 READ: 2020/12/01 13:36:59 dict: end, #3
 READ: 2020/12/01 13:36:59 dereferenceObject: end obj 3 of 13
<<<
	<ArtBox, [0 0 596 842]>
	<Contents, [(2 0 R)]>
	<MediaBox, [0 0 596 842]>
	<Parent, (4 0 R)>
	<Resources, <<
		<ProcSet, [PDF ImageC ImageB ImageI]>
		<XObject, <<
			<Im1, (1 0 R)>
		>>>
	>>>
	<Rotate, 0>
	<Type, Page>
>>>
 READ: 2020/12/01 13:36:59 logStream: no ObjectStreamDict
 READ: 2020/12/01 13:36:59 dereferenceObject: begin, dereferencing object 4
 READ: 2020/12/01 13:36:59 in use object 4
 READ: 2020/12/01 13:36:59 dereferenceObject: dereferencing object 4
 READ: 2020/12/01 13:36:59 ParseObject: begin, obj#4, offset:514723
 READ: 2020/12/01 13:36:59 newPositionedReader: positioned to offset: 514723
 READ: 2020/12/01 13:36:59 object: small obj w/o stream, parse until endobj
 READ: 2020/12/01 13:36:59 dict: end, #4
 READ: 2020/12/01 13:36:59 dereferenceObject: end obj 4 of 13
<<<
	<Count, 2>
	<Kids, [(3 0 R) (7 0 R)]>
	<Type, Pages>
>>>
 READ: 2020/12/01 13:36:59 logStream: no ObjectStreamDict
 READ: 2020/12/01 13:36:59 dereferenceObject: begin, dereferencing object 5
 READ: 2020/12/01 13:36:59 in use object 5
 READ: 2020/12/01 13:36:59 dereferenceObject: dereferencing object 5
 READ: 2020/12/01 13:36:59 ParseObject: begin, obj#5, offset:345859
 READ: 2020/12/01 13:36:59 newPositionedReader: positioned to offset: 345859
 READ: 2020/12/01 13:36:59 buffer: endInd=-1 streamInd=160
 READ: 2020/12/01 13:36:59 object: big stream, we parse object until stream
 READ: 2020/12/01 13:36:59 pdfFilterPipeline: begin
 READ: 2020/12/01 13:36:59 pdfFilterPipeline: end
 READ: 2020/12/01 13:36:59 streamDictForObject: end, Streamobject #5
 READ: 2020/12/01 13:36:59 LoadEncodedStreamContent: begin
<<
	<BitsPerComponent, 8>
	<ColorSpace, DeviceRGB>
	<Filter, [DCTDecode]>
	<Height, 2338>
	<Length, 168374>
	<Name, Im2>
	<Subtype, Image>
	<Type, XObject>
	<Width, 1654>
>>
 READ: 2020/12/01 13:36:59 newPositionedReader: positioned to offset: 346026
 READ: 2020/12/01 13:36:59 LoadEncodedStreamContent: seeked to offset:346026
 READ: 2020/12/01 13:36:59 readContentStream: begin streamLength:168374
 READ: 2020/12/01 13:36:59 readContentStream: count=168374, buflen=168374(291B6)
 READ: 2020/12/01 13:36:59 readContentStream: end
 READ: 2020/12/01 13:36:59 LoadEncodedStreamContent: end: len(streamDictRaw)=168374
 READ: 2020/12/01 13:36:59 saveDecodedStreamContent: begin decode=false
 READ: 2020/12/01 13:36:59 dereferenceObject: end obj 5 of 13
<<<
	<BitsPerComponent, 8>
	<ColorSpace, DeviceRGB>
	<Filter, [DCTDecode]>
	<Height, 2338>
	<Length, 168374>
	<Name, Im2>
	<Subtype, Image>
	<Type, XObject>
	<Width, 1654>
>>>
 READ: 2020/12/01 13:36:59 logStream: no stream content
 READ: 2020/12/01 13:36:59 dereferenceObject: begin, dereferencing object 6
 READ: 2020/12/01 13:36:59 in use object 6
 READ: 2020/12/01 13:36:59 dereferenceObject: dereferencing object 6
 READ: 2020/12/01 13:36:59 ParseObject: begin, obj#6, offset:514417
 READ: 2020/12/01 13:36:59 newPositionedReader: positioned to offset: 514417
 READ: 2020/12/01 13:36:59 buffer: endInd=90 streamInd=26
 READ: 2020/12/01 13:36:59 object: small stream within buffer, parse until stream
 READ: 2020/12/01 13:36:59 pdfFilterPipeline: begin
 READ: 2020/12/01 13:36:59 streamDictForObject: end, Streamobject #6
 READ: 2020/12/01 13:36:59 LoadEncodedStreamContent: begin
<<
	<Length, 47>
>>
 READ: 2020/12/01 13:36:59 newPositionedReader: positioned to offset: 514450
 READ: 2020/12/01 13:36:59 LoadEncodedStreamContent: seeked to offset:514450
 READ: 2020/12/01 13:36:59 readContentStream: begin streamLength:47
 READ: 2020/12/01 13:36:59 readContentStream: count=47, buflen=47(2F)
 READ: 2020/12/01 13:36:59 readContentStream: end
 READ: 2020/12/01 13:36:59 LoadEncodedStreamContent: end: len(streamDictRaw)=47
 READ: 2020/12/01 13:36:59 saveDecodedStreamContent: begin decode=false
 READ: 2020/12/01 13:36:59 dereferenceObject: end obj 6 of 13
<<<
	<Length, 47>
>>>
 READ: 2020/12/01 13:36:59 logStream: no stream content
 READ: 2020/12/01 13:36:59 dereferenceObject: begin, dereferencing object 7
 READ: 2020/12/01 13:36:59 in use object 7
 READ: 2020/12/01 13:36:59 dereferenceObject: dereferencing object 7
 READ: 2020/12/01 13:36:59 ParseObject: begin, obj#7, offset:514514
 READ: 2020/12/01 13:36:59 newPositionedReader: positioned to offset: 514514
 READ: 2020/12/01 13:36:59 object: small obj w/o stream, parse until endobj
 READ: 2020/12/01 13:36:59 dict: end, #7
 READ: 2020/12/01 13:36:59 dereferenceObject: end obj 7 of 13
<<<
	<ArtBox, [0 0 596 842]>
	<Contents, [(6 0 R)]>
	<MediaBox, [0 0 596 842]>
	<Parent, (4 0 R)>
	<Resources, <<
		<ProcSet, [PDF ImageC ImageB ImageI]>
		<XObject, <<
			<Im2, (5 0 R)>
		>>>
	>>>
	<Rotate, 0>
	<Type, Page>
>>>
 READ: 2020/12/01 13:36:59 logStream: no ObjectStreamDict
 READ: 2020/12/01 13:36:59 dereferenceObject: begin, dereferencing object 8
 READ: 2020/12/01 13:36:59 in use object 8
 READ: 2020/12/01 13:36:59 dereferenceObject: dereferencing object 8
 READ: 2020/12/01 13:36:59 ParseObject: begin, obj#8, offset:514787
 READ: 2020/12/01 13:36:59 newPositionedReader: positioned to offset: 514787
 READ: 2020/12/01 13:36:59 object: small obj w/o stream, parse until endobj
 READ: 2020/12/01 13:36:59 dict: end, #8
 READ: 2020/12/01 13:36:59 dereferenceObject: end obj 8 of 13
<<<
	<Pages, (4 0 R)>
	<Type, Catalog>
>>>
 READ: 2020/12/01 13:36:59 logStream: no ObjectStreamDict
 READ: 2020/12/01 13:36:59 dereferenceObject: begin, dereferencing object 9
 READ: 2020/12/01 13:36:59 in use object 9
 READ: 2020/12/01 13:36:59 dereferenceObject: dereferencing object 9
 READ: 2020/12/01 13:36:59 ParseObject: begin, obj#9, offset:514838
 READ: 2020/12/01 13:36:59 newPositionedReader: positioned to offset: 514838
 READ: 2020/12/01 13:36:59 object: small obj w/o stream, parse until endobj
 READ: 2020/12/01 13:36:59 dict: end, #9
 READ: 2020/12/01 13:36:59 dereferenceObject: end obj 9 of 13
<<<
	<D, [(1 0 R) FitH 2338]>
	<S, GoTo>
>>>
 READ: 2020/12/01 13:36:59 logStream: no ObjectStreamDict
 READ: 2020/12/01 13:36:59 dereferenceObject: begin, dereferencing object 10
 READ: 2020/12/01 13:36:59 in use object 10
 READ: 2020/12/01 13:36:59 dereferenceObject: dereferencing object 10
 READ: 2020/12/01 13:36:59 ParseObject: begin, obj#10, offset:514887
 READ: 2020/12/01 13:36:59 newPositionedReader: positioned to offset: 514887
 READ: 2020/12/01 13:36:59 object: small obj w/o stream, parse until endobj
 READ: 2020/12/01 13:36:59 dict: end, #10
 READ: 2020/12/01 13:36:59 dereferenceObject: end obj 10 of 13
<<<
	<Extensions, <<
		<ADBE, <<
			<BaseVersion, 1.7>
			<ExtensionLevel, 3>
		>>>
	>>>
	<Metadata, (11 0 R)>
	<OpenAction, (9 0 R)>
	<Pages, (4 0 R)>
	<Type, Catalog>
>>>
 READ: 2020/12/01 13:36:59 logStream: no ObjectStreamDict
 READ: 2020/12/01 13:36:59 dereferenceObject: begin, dereferencing object 11
 READ: 2020/12/01 13:36:59 in use object 11
 READ: 2020/12/01 13:36:59 dereferenceObject: dereferencing object 11
 READ: 2020/12/01 13:36:59 ParseObject: begin, obj#11, offset:515035
 READ: 2020/12/01 13:36:59 newPositionedReader: positioned to offset: 515035
 READ: 2020/12/01 13:36:59 buffer: endInd=74 streamInd=57
 READ: 2020/12/01 13:36:59 object: small stream within buffer, parse until stream
 READ: 2020/12/01 13:36:59 pdfFilterPipeline: begin
 READ: 2020/12/01 13:36:59 streamDictForObject: end, Streamobject #11
 READ: 2020/12/01 13:36:59 LoadEncodedStreamContent: begin
<<
	<Length, 2338>
	<Subtype, XML>
	<Type, Metadata>
>>
 READ: 2020/12/01 13:36:59 newPositionedReader: positioned to offset: 515099
 READ: 2020/12/01 13:36:59 LoadEncodedStreamContent: seeked to offset:515099
 READ: 2020/12/01 13:36:59 readContentStream: begin streamLength:2338
 READ: 2020/12/01 13:36:59 readContentStream: count=596, buflen=2338(922)
Fatal: EOF
dereferenceObject: problem dereferencing stream 11
github.com/pdfcpu/pdfcpu/pkg/pdfcpu.loadStreamDict
	C:/Users/Simon/Documents/GitHub/pdfcpu/pkg/pdfcpu/read.go:2135
github.com/pdfcpu/pdfcpu/pkg/pdfcpu.dereferenceObject
	C:/Users/Simon/Documents/GitHub/pdfcpu/pkg/pdfcpu/read.go:2234
github.com/pdfcpu/pdfcpu/pkg/pdfcpu.dereferenceObjects
	C:/Users/Simon/Documents/GitHub/pdfcpu/pkg/pdfcpu/read.go:2311
github.com/pdfcpu/pdfcpu/pkg/pdfcpu.dereferenceXRefTable
	C:/Users/Simon/Documents/GitHub/pdfcpu/pkg/pdfcpu/read.go:2390
github.com/pdfcpu/pdfcpu/pkg/pdfcpu.Read
	C:/Users/Simon/Documents/GitHub/pdfcpu/pkg/pdfcpu/read.go:78
github.com/pdfcpu/pdfcpu/pkg/api.ReadContext
	C:/Users/Simon/Documents/GitHub/pdfcpu/pkg/api/api.go:48
github.com/pdfcpu/pdfcpu/pkg/api.Validate
	C:/Users/Simon/Documents/GitHub/pdfcpu/pkg/api/validate.go:42
github.com/pdfcpu/pdfcpu/pkg/api.ValidateFile
	C:/Users/Simon/Documents/GitHub/pdfcpu/pkg/api/validate.go:91
github.com/pdfcpu/pdfcpu/pkg/cli.Validate
	C:/Users/Simon/Documents/GitHub/pdfcpu/pkg/cli/cli.go:33
github.com/pdfcpu/pdfcpu/pkg/cli.Process
	C:/Users/Simon/Documents/GitHub/pdfcpu/pkg/cli/process.go:35
main.process
	C:/Users/Simon/Documents/GitHub/pdfcpu/cmd/pdfcpu/process.go:88
main.processValidateCommand
	C:/Users/Simon/Documents/GitHub/pdfcpu/cmd/pdfcpu/process.go:126
main.commandMap.process
	C:/Users/Simon/Documents/GitHub/pdfcpu/cmd/pdfcpu/cmd.go:145
main.main
	C:/Users/Simon/Documents/GitHub/pdfcpu/cmd/pdfcpu/main.go:55
runtime.main
	c:/go/src/runtime/proc.go:204
runtime.goexit
	c:/go/src/runtime/asm_amd64.s:1374
`

**Comment by hhrutter** [comment]
Hello,

Thanks for reporting this.
Yes, there is smth weird going on here.
For such a case I need to debug the structure of the PDF in question.
Please post or send me a sample if you can or have access to the scanning app.

Thank you!

**Comment by simon-franz** [comment]
Hi, thanks for the fast reply!
Do you need the full pdf-file? or is there a specific part of the pdf enough?
Thanks in advance

**Comment by hhrutter** [comment]
Yes please only the whole file in this case.
Thank you.
