### ISSUE TITLE
Extract audio

### ISSUE THREAD

**Issue by yhcd** [pdfcpu/pdfcpu#257]
Hi,
I want to extract audio (mp3) from pdf, and embed a new version of the audio to it.
Your code is nice. I learned a lot about pdf format from pdfcpu. Thank you.
I will try it my self, but it will take a long time. I'm not good at golang and pdf

**Comment by hhrutter** [comment]
Hello, 

There are different ways you can attach an mp3 file.
You can either add it as a regular file attachment.
In this case pdfcpu has your back, just do smth like `pdfcpu attach extract my.pdf` on the cmd line.

Another way of adding audio to your PDF is via page anntotations.
Right now pdfcpu offers limited support for annotation processing.

If you want post or send me (hhrutter@gmail.com) a sample PDF and I am happy to take a look and see how pdfcpu can help you.

**Comment by hhrutter** [comment]
Closed due to inactivity.
