### ISSUE TITLE
validation error: first element refers to invalid destination page dict

### ISSUE THREAD

**Issue by simon-franz** [pdfcpu/pdfcpu#261]
Hi there,
I've multiple PDFs which were created from "ReportBuilder" with PDF-Version 1.4.
They are created from rental-car agencies (looks like autoeurope and hertz).
They can be opened in Chrome and Acrobat Reader without any problem.

The corresponding error is:
```
validating(mode=relaxed) D:\pdf\invalid\0bc9cbeb249dba844e75013a4cf4da82\filepdf ...
validation error: pdfcpu: validateDestinationArrayFirstElement: first element refers to invalid destination page dict
```

Best regards

**Comment by hhrutter** [comment]
ok, please get me a sample file and I provide a fix.

**Comment by hhrutter** [comment]
Please send me a sample if you can so I can provide a fix.
Thank you!

**Comment by simon-franz** [comment]
Hi,
sadly in this documents there are person related details involved so I cannot share the document itself.
If there is anything else beside the document let me know.
I'll close this case, Please let me know if there is anything else (besides the file) I can assist with in this case.

**Comment by hhrutter** [comment]
ok. There is just no way to fix smth like this without having a file to analyze and to test against.
