### ISSUE TITLE
validation error: validateFontEncoding: invalid Encoding name: StandardEncoding

### ISSUE THREAD

**Issue by simon-franz** [pdfcpu/pdfcpu#262]
Hi there,
I've multiple docuemnts created by "IntSig Information Co., Ltd" with PDF-Version 1.5.
When searching it seems to be the Android App "[camscanner](https://play.google.com/store/apps/developer?id=INTSIG+Information+Co.,Ltd&hl=gsw&gl=US)" 
Opening in different PDF-Tools does work without problem.
I can share the document if this is helpful.

The validation seems to fail with this error:
```
validating(mode=relaxed) D:\pdf\invalid\3dc72da7e64a0045a30012879ffa4a5d\file.pdf ...
validation error: validateFontEncoding: invalid Encoding name: StandardEncoding
```

Thanks in advance

**Comment by hhrutter** [comment]
OK, please send me one sample PDF so we can provide a fix.
Thank you for reporting this 💚
