### ISSUE TITLE
validation error: dict=Link entry=QuadPoints: unsupported in version 1.4

### ISSUE THREAD

**Issue by simon-franz** [pdfcpu/pdfcpu#263]
HI there,
I've multiple documents created by "15Below via ABCpdf" with PDF-Version 1.4.
They are travel confirmations and travel details of the airline Lufthansa.

The documents can be opened normally, even validating the document with the online tool of https://www.pdf-online.com/osa/validate.aspx does conform the file as non PDF/A standard.
```
Validating file "file.pdf" for conformance level pdf1.4
The document does conform to the PDF 1.4 standard.
Done.
```

To verify the pdf/a i've checked the same validator with a pdf/a compliant file from [here](https://tcpdf.org/examples/example_065/). If it is pdf/A compliant it does list it as `The document does conform to the PDF/A-1b standard.`

Validating the file results into this error:
```
validating(mode=relaxed) D:\pdf\invalid\72e9ac0f4864998763b98c82a14f9d45\file.pdf ...
validation error: dict=Link entry=QuadPoints: unsupported in version 1.4
This file could be PDF/A compliant but pdfcpu only supports versions <= PDF V1.7
```

Thanks in advance!

**Comment by hhrutter** [comment]
Understood. Send me a sample and I take a look at this.

**Comment by hhrutter** [comment]
Please send me a sample if you can so I can provide a fix.
Thank you!

**Comment by simon-franz** [comment]
Hi,
sadly in this documents there are person related details involved so I cannot share the document itself.
I'll close this case, Please let me know if there is anything else (besides the file) I can assist with in this case.
