### ISSUE TITLE
headerVersion: corrupt pdf stream - no header version available

### ISSUE THREAD

**Issue by eshevarova** [pdfcpu/pdfcpu#265]
Hello!
I tried to merge two pdf files with "Merge" function, but got an error "headerVersion: corrupt pdf stream - no header version available". Looks like #253. Is it fixed for my problem?
[crash.log](https://github.com/pdfcpu/pdfcpu/files/5701804/crash.log)
[abfab7da-004b-49d1-9a7c-45f4a29b0baf.pdf](https://github.com/pdfcpu/pdfcpu/files/5701805/abfab7da-004b-49d1-9a7c-45f4a29b0baf.pdf)

Thanks a lot!

**Comment by hhrutter** [comment]
No, this is something different, but thanks for reporting it.
A fix will be in the next release which is due in a couple of days.

Thank you for using pdfcpu 💚

**Comment by eshevarova** [comment]
Thanks for your quick response!

**Comment by hhrutter** [comment]
Fixed with latest commit
