### ISSUE TITLE
Import images and upload to Amazon S3

### ISSUE THREAD

**Issue by giautm** [pdfcpu/pdfcpu#266]
Hi,

I'm trying to build service that receive upload images then build into and PDF and upload to S3/GCP. I note that pdfcpu, it's store pdf file image in memory before write it to stream. It may cause out-of-memory if I have a lot of image uploaded.

Is there any solution to write chunk of bytes to upstream?

Thank you,

**Comment by hhrutter** [comment]
Hello!

Please checkout #60 and let me know if you have any further questions.
It's a slightly different usecase but maybe @plaisted can help out here.

Thanks for using pdfcpu 💚
