### ISSUE TITLE
Whether concurrent processing is supported

### ISSUE THREAD

**Issue by zhumengyifang** [pdfcpu/pdfcpu#267]
Seems to have led to chaos

**Comment by zhumengyifang** [comment]
err = api.AddWatermarks(bytes.NewReader(reader), buffer, nil, wm, nil)

**Comment by hhrutter** [comment]
Hello,

Please describe your issue.
How can I help you?

**Comment by zhumengyifang** [comment]
I'm sorry. It's my problem
