### ISSUE TITLE
New Tagged Release for `AddWatermarksMap`?

### ISSUE THREAD

**Issue by TheDiscordian** [pdfcpu/pdfcpu#269]
Hey I was looking through this library. I quite like the idea of `AddWatermarksMap`

Can we possibly get a new version tagged up so I can easily use 4dee3f995b93db4277cc2925b79f870899460938 ?

Cheers :)

**Comment by hhrutter** [comment]
👍  Sure thing.
Stay tuned for the upcoming release.

**Comment by hhrutter** [comment]
This is addressed in v0.3.8 
Please check out [pkg/api/test/stampVersatile_test.go](https://github.com/pdfcpu/pdfcpu/blob/master/pkg/api/test/stampVersatile_test.go)
