### ISSUE TITLE
Feature Request: AddWatermarksSliceMap

### ISSUE THREAD

**Issue by TheDiscordian** [pdfcpu/pdfcpu#270]
```go
func (ctx *Context) AddWatermarksSliceMap(m map[int][]*Watermark) error {
```

This would be very useful for adding multiple watermarks to a page all at once. My apologies if I've missed the feature :).

**Comment by hhrutter** [comment]
Hi!

I get your idea but I am sorry this is too late for the upcoming release.
It's definitely not that easy as suggested in #271 which is also the reason I have to put this off.
I suggest we revisit this once v0.3.8 is out and take it from there.

Thank you for using pdfcpu 💚

**Comment by TheDiscordian** [comment]
Sounds good to me!

As I'm keen to add multiple watermarks to a single page... What could go wrong with using that PR? Currently it produces a working PDF (seemingly), but is it technically incorrect?

**Comment by hhrutter** [comment]
Yes, it is correct but it does not consider optimization of resources watermarks bring along.
As long as you don't worry about file size you're good.

I like your idea though and will integrate it unless you want to rebase and modify #271.

pdfcpu/stamp.go: 
`func (ctx *Context) AddWatermarksMap(m map[int]*Watermark) error`

Here we need: 
`func (ctx *Context) AddWatermarksSliceMap(m map[int][]*Watermark) error`

api/stamp.go:
```
func AddWatermarksMap(rs io.ReadSeeker, w io.Writer, m map[int]*pdfcpu.Watermark, conf *pdfcpu.Configuration) error 
func AddWatermarksMapFile(inFile, outFile string, m map[int]*pdfcpu.Watermark, conf *pdfcpu.Configuration) error
```

Here we'll need:
```
func AddWatermarksSliceMap(rs io.ReadSeeker, w io.Writer, m map[int][]*pdfcpu.Watermark, conf *pdfcpu.Configuration) error 
func AddWatermarksSliceMapFile(inFile, outFile string, m map[int][]*pdfcpu.Watermark, conf *pdfcpu.Configuration) error
```

**Comment by hhrutter** [comment]
This has been integrated with the latest commit.
