### ISSUE TITLE
Proposal for documentation (website) update

### ISSUE THREAD

**Issue by gernotstarke** [pdfcpu/pdfcpu#274]
I suggest to update the documentation - both in style and content:

## 1. migrating to the "/docs" based built of the site (formerly, a stale branch gh_pages was used for generating the website)

I created a preliminary/prototype version in a fork: https://gernotstarke.github.io/pdfcpu/,

Somehow the logo is (currently) not showing, and all subpages of "Command line" are missing... (

In case the overall appearance seems ok for you, I would continue to migrate more content.

## 2. add an "Examples" page to the website.
Yes - there are a few examples scattered in the code, but the feature-rich api imho justifies examples "in-one-location"

A nice example is the archunit.org website - they have "use-cases" as a top-level navigation element on the homepage.

I'd be willing to contribute - please give me an indication if that's interesting for you.

**Comment by gernotstarke** [comment]
seems my latest commits broke the whole layout... assets and css are currently unavailable in the preview :-(

**Comment by gernotstarke** [comment]
that's how it SHOULD look like (on the remote version, some assets are not copied during the Jekyll build, I investigate)

![image](https://user-images.githubusercontent.com/1233990/103224974-25b46c00-4929-11eb-8db1-70f8465c2cba.png)

**Comment by hhrutter** [comment]
I agree this looks much better.
Thanks for your effort 👍 
Still I want to hold off on that matter until I have the time it takes and more to the point content that's also worth the effort.
Coding on..
