### ISSUE TITLE
pdfcpu fails to handle empty PDF objects

### ISSUE THREAD

**Issue by petervwyatt** [pdfcpu/pdfcpu#276]
pdfcpu fails to handle empty PDF objects (where there is nothing but whitespace between obj and endobj keywords).
validate command fails even in the case of an unreferenced empty object - see object 6 in attached PDF.
Situation should be handled - internally treat as equivalent to the PDF null object

$ pdfcpu validate pdfcpu-fail.pdf
validating(mode=relaxed) pdfcpu-fail.pdf ...
dereferenceObject: problem dereferencing object 6: pdfcpu: parse: no buffer available

$ pdfcpu validate -v pdfcpu-fail.pdf
validating(mode=relaxed) pdfcpu-fail.pdf ...
 INFO: 2020/12/29 21:23:23 PDF Version 1.5 conforming reader
Fatal: pdfcpu: parse: no buffer available
github.com/pdfcpu/pdfcpu/pkg/pdfcpu.init
        /mnt/c/Temp/share/pdfcpu/pkg/pdfcpu/parse.go:41
runtime.doInit
        /usr/local/go/src/runtime/proc.go:5646
runtime.doInit
        /usr/local/go/src/runtime/proc.go:5641
runtime.main
        /usr/local/go/src/runtime/proc.go:191
runtime.goexit
        /usr/local/go/src/runtime/asm_amd64.s:1374
dereferenceObject: problem dereferencing object 6
github.com/pdfcpu/pdfcpu/pkg/pdfcpu.dereferenceObject
        /mnt/c/Temp/share/pdfcpu/pkg/pdfcpu/read.go:2182
github.com/pdfcpu/pdfcpu/pkg/pdfcpu.dereferenceObjects
        /mnt/c/Temp/share/pdfcpu/pkg/pdfcpu/read.go:2282
github.com/pdfcpu/pdfcpu/pkg/pdfcpu.dereferenceXRefTable
        /mnt/c/Temp/share/pdfcpu/pkg/pdfcpu/read.go:2361
github.com/pdfcpu/pdfcpu/pkg/pdfcpu.Read
        /mnt/c/Temp/share/pdfcpu/pkg/pdfcpu/read.go:79
github.com/pdfcpu/pdfcpu/pkg/api.ReadContext
        /mnt/c/Temp/share/pdfcpu/pkg/api/api.go:48
github.com/pdfcpu/pdfcpu/pkg/api.Validate
        /mnt/c/Temp/share/pdfcpu/pkg/api/validate.go:42
github.com/pdfcpu/pdfcpu/pkg/api.ValidateFile
        /mnt/c/Temp/share/pdfcpu/pkg/api/validate.go:91
github.com/pdfcpu/pdfcpu/pkg/cli.Validate
        /mnt/c/Temp/share/pdfcpu/pkg/cli/cli.go:33
github.com/pdfcpu/pdfcpu/pkg/cli.Process
        /mnt/c/Temp/share/pdfcpu/pkg/cli/process.go:35
main.process
        /mnt/c/Temp/share/pdfcpu/cmd/pdfcpu/main.go:101
main.processValidateCommand
        /mnt/c/Temp/share/pdfcpu/cmd/pdfcpu/process.go:105
main.commandMap.process
        /mnt/c/Temp/share/pdfcpu/cmd/pdfcpu/cmd.go:80
main.main
        /mnt/c/Temp/share/pdfcpu/cmd/pdfcpu/main.go:62
runtime.main
        /usr/local/go/src/runtime/proc.go:204
runtime.goexit
        /usr/local/go/src/runtime/asm_amd64.s:1374

[pdfcpu-fail.pdf](https://github.com/pdfcpu/pdfcpu/files/5750322/pdfcpu-fail.pdf)

**Comment by hhrutter** [comment]
Hello!

Who was the creator of this PDF?
Is this even representative? 
Do we have any real world sample eg. produced by Adobe Reader and such?
OK, I'll check it out.
I will also go back and check the spec.

Thanks for reporting!

**Comment by petervwyatt** [comment]
I do have a few real-world PDFs but I cannot share them unfortunately. I think it is caused by a brain-dead privacy tool that is trying to scrub incrementally updated PDFs... and this is the result. I reduced them down to this as the root cause but there may also be other variants (e.g. if there is a PDF comment as the body of the object - so not pure whitespace, just logical whitespace).  

Related PDF spec quotes: 

- clause 7.3.9: "An indirect object reference (see 7.3.10, "Indirect objects") to a nonexistent object shall be treated the same as a null object. Specifying the null object as the value of a dictionary entry (7.3.7, "Dictionary objects") shall be equivalent to omitting the entry entirely."
- clause 7.5.4: "The cross-reference table (comprising the original cross-reference section and all update sections) shall contain one entry for each object number from 0 to the maximum object number defined in the PDF file, even if one or more of the object numbers in this range do not actually occur in the PDF file."

**Comment by hhrutter** [comment]
This will be fixed!
