### ISSUE TITLE
nup: full-page background color

### ISSUE THREAD

**Issue by adamgreenhall** [pdfcpu/pdfcpu#279]
Context: I'm trying to use nup with some margin around the pages. I'd like to have the sheet background be a different color so I can clearly see the nup'd pages.

I tinkered around, but couldn't figure out an easy way to do this via nup or watermarking. If you have a suggestion on how to proceed (or a reference I should read to figure it out), I'm happy to contribute a PR.

**Comment by hhrutter** [comment]
Hi there!

*margin* is already part of the command *description*.
Have you tried that?

As far as color support we can do that 👍

**Comment by hhrutter** [comment]
Q: Do you like to define the background for the entire destination page or each of the destination areas of nup'ed content individually?

**Comment by adamgreenhall** [comment]
I was thinking about a background color for the entire destination page

**Comment by hhrutter** [comment]
ok. makes sense. 
I will provide this asap so booklet.go can leverage.

**Comment by hhrutter** [comment]
Fixed with latest commit!
