### ISSUE TITLE
cli: stamp/watermark with subtext

### ISSUE THREAD

**Issue by sawe1900** [pdfcpu/pdfcpu#281]
Hi all! Just discovered this project; very, very nice!!
Is it possible to add options for a watermark sub tekst? 
Main text (larger size): DRAFT
Sub text (smaller size, below main text): Owned by the owner

Cheers!

**Comment by hhrutter** [comment]
Hello!

I am assuming you are using the CLI.

You can do this for example by executing a sequence of *pdfcpu stamp add* commands along with corresponding positioning like so:
```
Go-> pdfcpu stamp add -mode text 'DRAFT' 'sc:1.0 abs, points:48, rot:0, off:0 20' in.pdf out.pdf
writing out.pdf...
pages: all
Go-> pdfcpu stamp add -mode text 'Owned by the owner' 'sc:1.0 abs, points:24, rot:0, off:0 -20' out.pdf out1.pdf
writing out1.pdf...
pages: all
```

**Comment by hhrutter** [comment]
Closed due to inactivity
