### ISSUE TITLE
Correct use of semantic versioning

### ISSUE THREAD

**Issue by txgruppi** [pdfcpu/pdfcpu#282]
Can you please make correct use of semantic versioning? https://semver.org/

From version 0.3.4 to 0.3.8 there are breaking changes, which require a major version bump.

Not following _semver_ is a problem when using libraries in a high automated environment.

**Comment by hhrutter** [comment]
As stated in the ReadMe pdfcpu is still Alpha which is also reflected by v0.x.y and yes we are following semver.

See https://semver.org/ 4)
```
4) Major version zero (0.y.z) is for initial development. 
   Anything MAY change at any time. 
   The public API SHOULD NOT be considered stable.
```

**Comment by txgruppi** [comment]
@hhrutter it would not hurt to start using it "correctly" since package managers usually know to update to any version with the same major value

**Comment by hhrutter** [comment]
Again, this package is Alpha and the api may break any time.
This is consistent with semver.

**Comment by hhrutter** [comment]
Closed due to inactivity.
