### ISSUE TITLE
Validating PDF links

### ISSUE THREAD

**Issue by Phantas0s** [pdfcpu/pdfcpu#287]
I've a PDF (a book I'm writing) and I would like to be sure that there is no dead links in there (both internal and external). I was thinking adding the following functionality to your tool: parsing the PDF for every link, sending an HTTP request for external ones (and look at the response code) and verifying somehow the internal ones.

I have no clue about PDFs but I "know" Golang so I could take care of that.

What do you think?

**Comment by hhrutter** [comment]
Hi there,

There are different ways how links may be embedded in PDF.
While pdfcpu has not really dealt with links specifically it is doable of course.

All you have to do is walk the page tree and identify links for HTTP heartbeat checking.
If you check the code base you'll see there isn't much on top of reading in the PDF and walking the page tree
ready for you to use so you are on your own but I suggest you take a deep dive into the [PDF spec](http://wwwimages.adobe.com/content/dam/Adobe/en/devnet/pdf/pdfs/PDF32000_2008.pdf) first.

Have fun 💚

**Comment by hhrutter** [comment]
Hello!
On 2nd thought this might be a useful feature.
I add it into the pipeline.

**Comment by Phantas0s** [comment]
Nice! I really hoped I could work on that but at the end I've little time. Sorry.

**Comment by hhrutter** [comment]
👍  Same here..

**Comment by hhrutter** [comment]
Get the latest commit for this and try this:
```
Go-> pdfcpu val -l PDF32000_2008.pdf
validating(mode=relaxed) PDF32000_2008.pdf ...
validating URIs..
...........................
Page 8: http://www.aiim.org/pdfrefdocs status=404
Page 10: http://adobe.com/go/pdf_ref_bibliography status=404
Page 10: http://www.adobe.com/go/pdf_ref_bibliography status=404
Page 11: http://www.aiim.org/pdfnotes status=404
Page 753: http://developer.apple.com/fonts/TTRefMan/ status=404
Page 754: http://www.agfamonotype.com/printer/pan1.asp status=404
Page 755: http://www.rsasecurity.com/rsalabs/node.asp?id=2125 status=404
validation error: broken links detected
Go->
```
