### ISSUE TITLE
merge bookmarks

### ISSUE THREAD

**Issue by charleslaw** [pdfcpu/pdfcpu#289]
I am merging 2 PDFs and would like to keep bookmarks for both.

I thin the most natural way to do this is to make the filenames into top-level bookmarks, and then nest all the bookmarks for the files underneath.

I took a look at the merge code and was out of my depths - is this something that is theoretically straightforward? Are there any big challenges with doing this?

Thanks!

**Comment by hhrutter** [comment]
Negative - merging document outlines is not trivial.
These are tree like structures containing linked lists with pointers to page locations using PDF actions or destinations
and along with these go name trees which also would have to be merged.

I shouldn't say this too loud but at the same time it's also not a secret that
the pdfcpu merge facility is quick and dirty with focus on *quick*.
All it cares about is merging page trees.

**Comment by hhrutter** [comment]
Closed due to inactivity.
