### ISSUE TITLE
Optimizing some PDFs results in "blank" pages when viewing in Chrome or Mozilla

### ISSUE THREAD

**Issue by meerkat-mary** [pdfcpu/pdfcpu#292]
Hi pdfcpu developers,

I'm running into an issue where merging two pdfs produces a pdf that can be viewed in Mac Big Sur/Windows just fine, however when viewing through a webbrowser, the PDF pages for one of the pdf entries is blank

The affected pdf in question has the following properties
```
         PDF version: 1.3
          Page count: 14
           Page size: 595.27 x 841.89 points
............................................
               Title: 
              Author: 
             Subject: 
        PDF Producer: MB5100 series
     Content creator: Canon SC1001
       Creation date: D:20201209082827+09'00'
   Modification date: D:20201209100322Z
............................................
              Tagged: No
              Hybrid: No
          Linearized: Yes
  Using XRef streams: No
Using object streams: No
         Watermarked: No
............................................
           Encrypted: No
         Permissions: Full access
```

It seems to consist of a scanned image on each page. I can't send across the PDF for investigation as it contains PII/sensitive content :( - The optimize step in the merge or watermark functions seem to be stripping the entire image on the page -  I've attached the output log of a direct optimize cli command, I hope this can help 

[crash.log](https://github.com/pdfcpu/pdfcpu/files/5972715/crash.log)

Unfortunately I receive files like this often and I need to be able to preserve their contents since users view the merged output in their browser. Would it be possible to update the Configuration strut to pass in a flag to disable optimization if possible please? I can then pass in a disable flag when merging or adding watermarks (or applying any other operation to the PDF) via the API for 'older' PDFs

Thank you! 😄

**Comment by hhrutter** [comment]
If you can't share the content it would be helpful if you could send me a log of the original like so:
`pdfcpu validate -vv original.pdf &> original.log`

Then maybe by comparing both PDF structures before and after optimization we get some clue what's going on, although nothing beats having the original content stream at hand because in there lies the culprit..

**Comment by meerkat-mary** [comment]
Thanks for the quick response @hhrutter!

I ran the command above and here is the original log:
[original.log](https://github.com/pdfcpu/pdfcpu/files/5974370/original.log)

I'll try and recreate the issue with a non-sensitive file if I can get my hands on one, though it may tough - if I do I'll reply back on this thread :)

After running the optimize command on the original file - it can open fine in Mac Preview and I see the contents of the page, however when I open it in Chrome browser (or in PDF.js from Mozilla - I see blank pages in place)

**Comment by hhrutter** [comment]
This is odd, I don't see anything out of the ordinary with this file.
I am assuming the original file does render fine in Chrome?
Does Adobe (Reader) have any problem with it?
Optimization also does not do much in the case of this particular file.
I am really curious to reproduce this issue.

**Comment by meerkat-mary** [comment]
The original file renders fine in Chrome yes (and in Mac Preview). Adobe can also render the optimized file too.

I think this may be a Chrome/Mozilla viewer issue for this particular PDF encoding (MB5100 Series) as the contents are still present when viewing in Safari/Mac, so it may not be worth chasing this actually. I can just get my user to download the pdf from their browser and view it offline for now.

If I manage to get a sample file that has the same issue I'll re-open this issue and attach it for your inspection, thank you!

(I do have another PDF file that fails relaxed mode validation, I'll create a separate issue with the crash log attached 😄 )
