### ISSUE TITLE
Relaxed mode validation results in a "validateIntegerEntry: dict=formStreamDict entry=FormType invalid type" error

### ISSUE THREAD

**Issue by meerkat-mary** [pdfcpu/pdfcpu#293]
Hi @hhrutter,

I come across the following error when validating (in relaxed mode) a PDF that was sent to me:
`validateIntegerEntry: dict=formStreamDict entry=FormType invalid type`

I'm using the latest version and I can open the file in Mac Preview, here is the verbose crash log: [validate-crash.log](https://github.com/pdfcpu/pdfcpu/files/5975518/validate-crash.log)

Unfortunately the contents of the PDF are sensitive again, so I can't send across the original for inspection :( but as before I'll try and recreate the issue with a sample PDF if possible

Thank you! 😄

**Comment by hhrutter** [comment]
This is a PDF spec violation as the optional `FormType` entry in a form stream dict should be the Integer constant `1`.
In your file it shows up as `1`and `1.00`.
Try the latest commit which extends relaxed validation.

**Comment by meerkat-mary** [comment]
Awesome, I'll give that go! thanks 😄
