### ISSUE TITLE
Validation problem

### ISSUE THREAD

**Issue by kpym** [pdfcpu/pdfcpu#294]
I was not able to merge this file [2021-02-13_002.pdf](https://github.com/pdfcpu/pdfcpu/files/5975969/2021-02-13_002.pdf) because `pdfcpu` reporte a problem.

```bash
> pdfcpu validate 2021-02-13_002.pdf
validating(mode=relaxed) 2021-02-13_002.pdf ...
decodeObjectStreams: problem decoding object stream 2
: pdfcpu: parseObjectStream: corrupt object stream dict
```

But I was able to merge this file with `cpdf` and with `mutool` without problem.

This `pdf` was created by [doXiSafe for Android](https://play.google.com/store/apps/details?id=de.cib.doxisafe.android) and contains `jpeg2000` strames.

When I check it with Acrobat preflight, the file is compatible with `PDF 1.5` (but not with `PDF 1.4`).

![Acrobat_preflight_pdf1 5](https://user-images.githubusercontent.com/3142701/107854444-1aa39580-6e1c-11eb-8d2a-70331f613a4a.png)

![Acrobat_preflight_pdf1 4](https://user-images.githubusercontent.com/3142701/107854443-1aa39580-6e1c-11eb-9156-a0c93519d90f.png)

Thanks for your work!

**Comment by hhrutter** [comment]
👍 Thanks for reporting this.
I am on it..

**Comment by hhrutter** [comment]
Which application is the creator of this PDF ?
Although the info dict is optional, this file contains no meta info whatsoever and looks suspicious to me for this very reason.

It violates the spec as far as writing an objectstream concerned.
It uses `0x00` to separate the (obj#, offset) pairs for contained objects but the PDF specification mandates to use white space:

<img width="1180" alt="Screenshot 2021-02-13 at 19 32 18" src="https://user-images.githubusercontent.com/11322155/107858038-43cf2080-6e32-11eb-8a42-27f3d78db602.png">

**Comment by kpym** [comment]
> Which application is the creator of this PDF ?

As I said in my OP this `pdf` was created by [doXiSafe for Android](https://play.google.com/store/apps/details?id=de.cib.doxisafe.android). This is German company that have big experience with PDFs.

> Although the info dict is optional, this file contains no meta info whatsoever and looks suspicious to me for this very reason.
> 
> It violates the spec as far as writing an objectstream concerned.
> It uses `0x00` to separate the (obj#, offset) pairs for contained objects but the PDF specification mandates to use white space:

I can't argue on this point because I don't know the PDF specifications, but the fact is that no other tool I've tried complains, and Acrobat considers this file as valid for versions 1.5, 1.6 and 1.7.

> Fixed - The latest commit takes care of this and behaves relaxed when parsing the object stream prolog.

Thanks ! 🚀

**Comment by kpym** [comment]
I've checked, it works now, thanks ! 🙏🎉

**Comment by petervwyatt** [comment]
@hhrutter Just FYI - Table 1 (all parts of ISO 32000) defines "white-space characters" for PDF - and it explicitly INCLUDES null (0x00). Don't get fooled by the common-use name - or lacking support nul as valid whitespace in other implementations! :-)

**Comment by hhrutter** [comment]
Thanks for pointing this out. 
You are right!

I was looking at 4.42 instead of table 1.
Will need to revise the usage of whitespace across the board.
