### ISSUE TITLE
Color conversion

### ISSUE THREAD

**Issue by aabacchus** [pdfcpu/pdfcpu#295]
I often scan some work and want to convert the images to a pdf for uploading.
These images can be very large in size but I can "remove" the color from them by converting the pdf to grayscale, and this can vastly reduce the file sizes, usually by about 10 times.

At the moment I use Ghostscript in this way:
```bash
#!/bin/sh
gs      -sOutputFile=gray.pdf \
        -sDEVICE=pdfwrite \
        -sColorConversionStrategy=Gray \
        -dProcessColorModel=/DeviceGray \
        -dCompatibilityLevel=1.4 \
        -dNOPAUSE \
        -dBATCH \
        $1
```

Could a similar feature be implemented in pdfcpu?

**Comment by hhrutter** [comment]
Hello!
Can you share a small sample input PDF for analysis?

**Comment by aabacchus** [comment]
Here's a jpg photo of a page of work: ![sample-pic](https://user-images.githubusercontent.com/43711769/108118094-c3105e80-7095-11eb-8844-506b596d21b8.jpg)
Taken pretty hurriedly, lighting is yellow, there's a bit of my table in the background.
It's 3.3M.

Converted to a pdf using `pdfcpu import sample-pic.pdf sample-pic.jpg`: [sample-pic.pdf](https://github.com/pdfcpu/pdfcpu/files/5991500/sample-pic.pdf)
Also 3.3M.

Now running the above script: [gray.pdf](https://github.com/pdfcpu/pdfcpu/files/5991497/gray.pdf)
Size is 420k and no distracting colour.

**Comment by hhrutter** [comment]
I'll check it out 👍 
Thank you for using pdfcpu 💚

**Comment by hhrutter** [comment]
Fixed with the latest commit!

Now you can do: `pdfcpu import -- "gray:true" gray.pdf test.jpg` to get what you need.
