### ISSUE TITLE
booklet: book printing using multiple folios

### ISSUE THREAD

**Issue by iilyak** [pdfcpu/pdfcpu#296]
The booklet mode is great however it doesn't allow easy printing of multiple folios. I am trying to custom print a book using this technique https://www.instructables.com/How-to-bind-your-own-Hardback-Book/ unfortunately it is impossible to do with one invocation of pdfcpu.

**Comment by iilyak** [comment]
I am trying to figure out if it is possible to use a combination of `collect`, `trim`, `nup` and `rotate` to achieve what I need using multiple invocations.

**Comment by hhrutter** [comment]
Hi!
At first sight this looks like a potential extension to the booklet command.
Will be taken into consideration.
Thanks for the suggestion 💚

**Comment by hhrutter** [comment]
This is implemented with the latest commit.
Let me know how that works our for you!
