### ISSUE TITLE
stamp: incorrect positioning on already rotated pages

### ISSUE THREAD

**Issue by meerkat-mary** [pdfcpu/pdfcpu#298]
Hi @hhrutter,

I'm running into an issue where stamps are incorrectly added to the bottom left (and rotated 90 degrees to the right) for a portrait page - instead of the bottom right (with no rotation) as intended. Here is the Text description snippet:

```
text := strconv.Itoa(i)
desc := "pos:br, off: -10 10, align:r, rot:0, sc: 1 abs"
wm, err := api.TextWatermark(text, desc, true, false, pdfcpu.POINTS)
```

For most PDFs, it correctly adds a page number stamp to the bottom right hand side of the page, however for some PDFs it seems to think they are in landscape format, when I open those PDFs they are in portrait mode and they haven't been manually rotated - any idea on what this could be?

I'll send a sample PDF to your email address shortly

Thanks!

**Comment by hhrutter** [comment]
OK please send over a sample.
I'll check.

**Comment by hhrutter** [comment]
Hi there!

You just discovered pdfcpu misinterprets existing page rotations when stamping 🔥 .

In PDF world clockwise rotation equals positive rotation.
I could complain about this not to be intuitive as far as trigonometry is concerned but that won't make a difference unfortunately.. Thanks for reporting this 💚

**Comment by meerkat-mary** [comment]
No problem :) thanks for looking into this!

**Comment by hhrutter** [comment]
This is fixed with the latest commit!

**Comment by meerkat-mary** [comment]
Thanks @hhrutter !!
