### ISSUE TITLE
parse: handle stream dict /Length 0 gracefully

### ISSUE THREAD

**Issue by kpym** [pdfcpu/pdfcpu#299]
The attached files [bug3im1.pdf](https://github.com/pdfcpu/pdfcpu/files/6020254/bug3im1.pdf) and [bug3im2.pdf](https://github.com/pdfcpu/pdfcpu/files/6020252/bug3im2.pdf) were created by ImageMagick. The only difference is that the second one was sent to the `stdout` which was redirected to the file.
```bash
> magick.exe -density 300 bug3.pdf -threshold 77% -type bilevel -compress Group4 bug3im1.pdf
> magick.exe -density 300 bug3.pdf -threshold 77% -type bilevel -compress Group4 pdf:- > bug3im2.pdf
```
Why the two files are not identical, I have no idea. But the fact is that both files are considered as valid with `relaxed` mode:
```bash
lidating(mode=relaxed) bug3im1o.pdf ...
validation ok
```
And both has the same problem in `strict` mode:
```bash
validation error (try -mode=relaxed): dict=xObjectStreamDict required entry=Subtype missing
```
When we optimize them with `pdfcpu optimize` the first looks ok, but **the `ccitt` stream disappears of the second one**.

Both files are considered as valid pdf 1.3 by Acrobat Preflight.

I don't know if this is a bug in `optimize` or a bug in `validate` but the behavior is not normal, IMO.

**Comment by petervwyatt** [comment]
Windows 10 Adobe Acrobat Pro DC Print Production Preflight "Syntax Check" fails verybadly for me for bug3im2.pdf:
![image](https://user-images.githubusercontent.com/26521615/108692085-4e836700-7550-11eb-94b1-267df9146361.png)

**Comment by petervwyatt** [comment]
xref table is clearly broken in bug3im2.pdf (right side):
![image](https://user-images.githubusercontent.com/26521615/108692538-d79a9e00-7550-11eb-85a3-f61c5dceccfe.png)

**Comment by kpym** [comment]
Strange : Acrobat 9 Pro do not report a problem.

![Acrobat 9 Pro - Preflight](https://user-images.githubusercontent.com/3142701/108694501-6aaae800-74ff-11eb-949e-a80738e651f3.png)

In any case `optimize` should not remove image that is perfectly viewable (Chrome, Acrobat, Sumatra). It could try to repair the `xref` table if it is broken, IMO.

**Comment by hhrutter** [comment]
My observation is the files produced by ImageMagick contain bogus stream length pointers.
It uses a ind ref which points to 0.

**Comment by hhrutter** [comment]
The issue comes down to "Should the indicated stream length get validated against the actual stream content?"

**Comment by kpym** [comment]
> The issue comes down to "Should the indicated stream length get validated against the actual stream content?"

Should I change the title ?

My guess is that "Yes", `pdfcpu` should consider the real stream size (and may be repair the wrong data) because the readers do that (they display the image).

**Comment by kpym** [comment]
> My observation is the files produced by ImageMagick contain bogus stream length pointers.
> It uses a ind ref which points to 0.

Just for info : this pdf was produced with 7.0.7 but the last version, 7.0.11, do not have this problem.

**Comment by hhrutter** [comment]
Considering that ImageMagick contains bogus Length pointers and an xref table that is so beautifully corrupted one may be lead to believe this all is intentionally.

**Comment by hhrutter** [comment]
ok then please provide files created with the latest ImageMagick release and we take it from there.

**Comment by kpym** [comment]
> ok then please provide files created with the latest ImageMagick release and we take it from there.

As I said the pdf files from the last version of ImageMagick are ok. But this is not the question as you said, the question is "Should the indicated stream length get validated against the actual stream content?".

If you think that the answer is "no" you can close this issue. If you think like me, that the anser is "yes" probably this could be fixed. 

By the way having good repair capabilities in `pdfcpu` is an important feature, IMO.

**Comment by hhrutter** [comment]
We don't want to repair any crappy PDF that appears and thereby supporting the authors of those libraries.
Instead we should throw this back to them and demand they produce valid PDF
.
pdfcpu is not Adobe Reader/Acrobat and does not have customers it wants to keep.
That's why I am raising the point.

@petervwyatt, what do you suggest, you are in a better position to judge here.

@kpym if you are saying the latest version produces  a valid xref then please by any means see if the optimization error still exists and if so I provide a fix. I would not bother providing a fix for an old version of any library also for the reason stated above.

**Comment by kpym** [comment]
> @kpym if you are saying the latest version produces a valid xref then please by any means see if the optimization error still exists and if so I provide a fix. I would not bother providing a fix for an old version of any library also for the reason stated above.

There is no optimization error with the last version of ImageMagick (because the stream length is ok). 

> pdfcpu is not Adobe Reader/Acrobat and does not have customers it wants to keep.

`Sumatra` do not have customers to keep ;)  
Isn't `optimize` supposed to be safe ? Deleting an image from "bad" pdf is probably not the good behavior. The "safe" options, IMO, are : 
- throw an error and refuse to optimize;
- optimize withour repair;
- optimize and repair.

Delete a stream because the declared length is wrong, do not looks as an optimization to me.

In any case, thanks for considering this, and thanks for your work.

**Comment by petervwyatt** [comment]
I will point out that the bad xref data (4294967295) is actually FFFF FFFF in hex - so obviously ImageMagik has/had some bad code.

Unfortunately issues with `/Length` not precisely matching the spec and the stream data are very, very common so I think this is one area pdfcpu should try to support. The degenerate `/Length 0` is a commonly seen idiom used by some lazy producers since it is generally corrected by many common PDF processors. Since most filters have EOD markers this is not too much of an issue when there are no other errors present, but unfiltered streams can (and do!!) result in different repairs by different processors.

**Comment by hhrutter** [comment]
@kpym I did not say `optimize` is not screwing up something here.
I am just asking you to check if the "disappearing" image also happens when processing a file that is produced using the latest version if ImageMagick.

👍 Ok so then it is settled, `/Length 0` issues need a work around.

**Comment by kpym** [comment]
> I am just asking you to check if the "disappearing" image also happens when processing a file that is produced using the latest version if ImageMagick.

- [I first said](https://github.com/pdfcpu/pdfcpu/issues/299#issuecomment-783276838):
    > Just for info : this pdf was produced with 7.0.7 but the last version, 7.0.11, do not have this stdout problem.
- [then I said](https://github.com/pdfcpu/pdfcpu/issues/299#issuecomment-783289973):
    > As I said the pdf files from the last version of ImageMagick are ok. 
- [then I said](https://github.com/pdfcpu/pdfcpu/issues/299#issuecomment-783308145):
    > There is no optimization error with the last version of ImageMagick (because the stream length is ok).

I was probably not clear but : the last version of ImageMagick (7.0.11) is ok. The stream `/Length` is not zero when the result is piped. And `pdfcpu optimise` do not remove the image in this case.

So this is not an ImageMagick problem (any more). This was just an example of badly formatted pdf that displays differently before and after optimization.

> 👍 Ok so then it is settled, /Length 0 issues need a work around.
> Although this is all real bad engineering and should NOT be supported IMHO.

🙏 Thanks for considering this question.

**Comment by hhrutter** [comment]
Are you saying `optimize` works as expected when processing a file based on the latest ImageMagick?

**Comment by kpym** [comment]
@hhrutter Here are, [as requested](https://github.com/pdfcpu/pdfcpu/issues/299#issuecomment-783473678), the the files (with suffix `n` for "new") obtained by the same command with the last version of ImageMagick: 
- [bug3im1n.pdf](https://github.com/pdfcpu/pdfcpu/files/6023336/bug3im1n.pdf)
- [bug3im2n.pdf](https://github.com/pdfcpu/pdfcpu/files/6023339/bug3im2n.pdf)
