### ISSUE TITLE
extract image: use leading zeros in file names

### ISSUE THREAD

**Issue by iilyak** [pdfcpu/pdfcpu#300]
I tried to extract all images from pdf to run them via OCR engine and assemble back in the right order.

```
./pdfcpu extract -mode image page.pdf images
```

However after extraction step the images are named as 

```
page_100_R502.jpg
page_101_R507.jpg
page_102_R512.jpg
page_103_R517.jpg
page_104_R522.jpg
page_105_R527.jpg
page_106_R532.jpg
page_107_R537.jpg
page_108_R542.jpg
page_109_R547.jpg
page_10_R52.jpg
```

This means it is hard to iterate over files in order because they are not alphabetically sorted. The better approach would be to determine how many digits would be enough to represent last page and pad 0 on the left to make all page numbers the same length.

```
page_001_R5.jpg
...
page_009_R51.jpg
page_010_R52.jpg
```

**Comment by hhrutter** [comment]
Hello!

Understood, and I guess there isn't any simple bash / scripting magic for this.

This is something easy to add but just another opinionated approach like the way pdfcpu is naming the output files right now so I am hesitant to change it. 

Another thing is there are already users out there relying on the current naming who might not be happy if we change this now.

api/extract.go: line68 is where the formatting of the output filename happens:

```
outFile := filepath.Join(outDir, fmt.Sprintf("%s_%d_%s.%s", fileName, i, img.Name, img.Type))
```

**Comment by hhrutter** [comment]
This will be fixed in the upcoming release.
