### ISSUE TITLE
import: support webp image format

### ISSUE THREAD

**Issue by TruongQToan** [pdfcpu/pdfcpu#301]
I had an issue regarding importing an image to pdf because the format is not supported. This happens with some types of images that are screenshots from iPhones. Because the image is private, I would like to email that to you and not post it here. 
Once again, thank you very much for your effort in building this useful library and I hope you can help me with this.

**Comment by hhrutter** [comment]
Sure. Send me a sample and I check it out.

**Comment by TruongQToan** [comment]
I have sent you the image. Thank you for checking it out.

**Comment by sonltcoder** [comment]
I'm troubling with the same issue with @TruongQToan. Hope it will be solved soon.

**Comment by hhrutter** [comment]
This image file does not open in Mac Preview?
Is there any way you can open and view this?

How did you create this image on the iPhone?
With an app? Screenshot?..

**Comment by TruongQToan** [comment]
It's strange. I am using Mac Preview and it can be opened. The file name is 1414.png, could you check again if you open the correct file?

**Comment by hhrutter** [comment]
This looks like a RIFF file.
How did you create this file?

**Comment by TruongQToan** [comment]
It was screenshotted by an iPhone.

**Comment by hhrutter** [comment]
Since [WebP](https://en.wikipedia.org/wiki/WebP) is a file format by Google I think this file is probably from an Android phone.
We can provide support for `webp` into pdfcpu but I think it makes sense to rely on the file type `.webp`.
Maybe you can find out why your file has the suffix `.png`when in reality it is a `.webp`.

**Comment by TruongQToan** [comment]
Actually, it did not have a file extension. I added a file extension into
that to open by Preview. Because in my application, users will upload
images and we do not always has a file extension, can we check the file
type by something else?

**Comment by TruongQToan** [comment]
Extra info in case you need it, the person taking this image reported that the screenshot had been taken on an iPhone 7 with iOS 14.4. Thank you very much.

**Comment by hhrutter** [comment]
Fixed with latest commit.

**Comment by TruongQToan** [comment]
Thank you very much.

**Comment by hhrutter** [comment]
You're welcome!
Please consider becoming a pdfcpu sponsor.
A Github sponsorship keeps this project alive.
Thank you for using pdfcpu 💚

**Comment by TruongQToan** [comment]
Sure. Thank you very much.
