### ISSUE TITLE
crypto: Issue found by Svace static analyzer

### ISSUE THREAD

**Issue by vvdvortsova** [pdfcpu/pdfcpu#303]
Hello
This warning found with the Svace.
In each case, using a variable res after comparison with nil, res may be nil. It may lead to panic.

https://github.com/pdfcpu/pdfcpu/blob/c5482e85456df9d702756466e37178ac8520419b/pkg/pdfcpu/crypto.go#L795
After having been compared to NULL value at crypto.go:795, pointer 'r' is dereferenced at crypto.go:796.
https://github.com/pdfcpu/pdfcpu/blob/c5482e85456df9d702756466e37178ac8520419b/pkg/pdfcpu/crypto.go#L796

**Comment by hhrutter** [comment]
Thank you for reporting this 💚
