### ISSUE TITLE
Allow skipping/overriding ctx.Info entries in `Write`

### ISSUE THREAD

**Issue by grncdr** [pdfcpu/pdfcpu#304]
Hi, thanks for this great library, it covers quite a lot of useful functionality.

I've noticed that even if I set my own "Producer" in the Info dict of a PDF, it will be overwritten to `pdfcpu v0.39` [here](https://github.com/pdfcpu/pdfcpu/blob/7b7432d9c87a12b774ef6fe7325729300e4f6804/pkg/pdfcpu/info.go#L132) when writing to a file.

_Edit:_ the exact call-stack is:

- [Write](https://github.com/pdfcpu/pdfcpu/blob/9ed5add8ac399239d9ee0c678e9804ab1a4c7db6/pkg/pdfcpu/write.go#L34)
- [prepareContextForWriting](https://github.com/pdfcpu/pdfcpu/blob/9ed5add8ac399239d9ee0c678e9804ab1a4c7db6/pkg/pdfcpu/write.go#L65)
- [ensureInfoDictAndFileID](https://github.com/pdfcpu/pdfcpu/blob/9ed5add8ac399239d9ee0c678e9804ab1a4c7db6/pkg/pdfcpu/write.go#L133)
- [ensureInfoDict](https://github.com/pdfcpu/pdfcpu/blob/9ed5add8ac399239d9ee0c678e9804ab1a4c7db6/pkg/pdfcpu/write.go#L179)
- [Dict.Update](https://github.com/pdfcpu/pdfcpu/blob/9ed5add8ac399239d9ee0c678e9804ab1a4c7db6/pkg/pdfcpu/info.go#L132)

In my fork I've made [this small change](https://github.com/grncdr/pdfcpu/commit/cec77d2bd7d407646346c6c57eb3768fa539523f) to work around it, but I'm wondering if you would accept a patch where "Producer" is only set if it's not already present?

**Comment by hhrutter** [comment]
Hello!

Of course, that's because pdfcpu is producing an output PDF by processing your input PDF.
I suggest you set the *Creator* in the PDF that you process with pdfcpu.

**Comment by hhrutter** [comment]
Ofcourse you're free to do whatever you want in your fork
but all things being equals and because of fairness I'd be happier if you left the Producer to pdfcpu.
It's just one of these little things that can make a big difference for a small project like this in terms of gaining user adoption.

**Comment by grncdr** [comment]
Ok, I thought maybe the current situation was just a side effect of implementing the CLI and library together. As it's now clear that the library and not just the CLI intends to include it's own name into any PDFs it writes, this issue can be closed.
