### ISSUE TITLE
validation: "Unescape: illegal escape sequence \ detected"

### ISSUE THREAD

**Issue by jidzhang** [pdfcpu/pdfcpu#305]
The pdf was print by AutoCAD2014, and I tested many pdf files(print by autocad2014), report the same error.

command line: pdfcpu.exe watermark add -m text "Test String" "" dwg.pdf dwg-out.pdf
then report error message: Unescape: illegal escape squence \ detected

[dwg.pdf](https://github.com/pdfcpu/pdfcpu/files/6065571/dwg.pdf)

**Comment by hhrutter** [comment]
Thank you for reporting this!

**Comment by hhrutter** [comment]
This is a correct error message since "\ " as in backslash followed by space (0x20) is an undefined escape sequence.
There is also no indication of a unicode string here.

We could handle this as an empty string but I am undecided/unclear at this moment.

```
<Measure, <<
				<A, [
					<<
						<C, 1>
						<U, (\ )>
					>>
					]>
				<D, [
					<<
						<C, 1>
						<U, (\ )>
					>>
					]>
				<R, (\ )>
				<Subtype, RL>
				<Type, Measure>
				<X, [
					<<
						<C, 0.35>
						<U, (\ )>
					>>
					]>
			>>>
```

**Comment by hhrutter** [comment]
Fixed with latest commit.
