### ISSUE TITLE
validation: info dict: missing object

### ISSUE THREAD

**Issue by HuabeiYou** [pdfcpu/pdfcpu#307]
Hi there,

I was trying to add watermarks on pdf files using `api.AddTextWatermarksFile` but got the error `validation error: pdfcpu: validateString: missing object` for some of them. It seems like the error is coming from `pdfcpu/validate/info.go` line 60 to 64: `if xRefTable.ValidationModa == pdf.ValidationRelaxed { ... }`.

I then tried the CLI mode.
`validate -m relaxed F18E1000.pdf` gives error:
```
validating(mode=relaxed) F18E1000.pdf ...
validation error: pdfcpu: validateString: missing object
```
However `pdfcpu validate -m strict F18E1000.pdf` worked
```
validating(mode=strict) F18E1000.pdf ...
validation ok
```

I attached the sample pdf below. Also, is there a way to change the validation mode and make `api.AddTextWatermarksFile` work?

Thanks!
[F18E1000.pdf](https://github.com/pdfcpu/pdfcpu/files/6087346/F18E1000.pdf)

**Comment by HuabeiYou** [comment]
> Hi there,
> 
> I was trying to add watermarks on pdf files using `api.AddTextWatermarksFile` but got the error `validation error: pdfcpu: validateString: missing object` for some of them. It seems like the error is coming from `pdfcpu/validate/info.go` line 60 to 64: `if xRefTable.ValidationModa == pdf.ValidationRelaxed { ... }`.
> 
> I then tried the CLI mode.
> `validate -m relaxed F18E1000.pdf` gives error:
> 
> ```
> validating(mode=relaxed) F18E1000.pdf ...
> validation error: pdfcpu: validateString: missing object
> ```
> 
> However `pdfcpu validate -m strict F18E1000.pdf` worked
> 
> ```
> validating(mode=strict) F18E1000.pdf ...
> validation ok
> ```
> 
> I attached the sample pdf below. Also, is there a way to change the validation mode and make `api.AddTextWatermarksFile` work?
> 
> Thanks!
> [F18E1000.pdf](https://github.com/pdfcpu/pdfcpu/files/6087346/F18E1000.pdf)

Update: Found out I can change the validation mode by passing in the Configuration, but it didn't solve my problem, here is the error:
- Add text watermark using ValidationNone:
```
text: corrupt -  <<
	<BaseFont, Helvetica>
	<Encoding, WinAnsiEncoding>
	<Subtype, Type1>
	<Type, Font>
>>
```
- Add text watermark using ValidationStrict:
```
dict=type1FontDict required entry=FirstChar missing
```

**Comment by hhrutter** [comment]
OK, I shall check it out.
Thank you for reporting this 💚

**Comment by hhrutter** [comment]
Looks like this file was created/modified on an Apple device (possibly Mac Preview) and then processed with "pdf-tools".
"pdf-tools" corrupted the info dict, so I would not recommend using it.
All info dict entries using indirect references point to empty objects:

```
175:   offset=  841786 generation=0 pdfcpu.Dict
<<
	<AAPL:Keywords, (180 0 R)>
	<CreationDate, (178 0 R)>
	<Creator, (177 0 R)>
	<Keywords, (179 0 R)>
	<ModDate, (D:20180922122321Z)>
	<Producer, (3-Heights\(TM\) PDF Security Shell 4.8.25.2 \(http://www.pdf-tools.com\) / pdcat \(www.pdf-tools.com\))>
	<Title, (176 0 R)>
>>
  176: f   next=     177 generation=0
  177: f   next=     178 generation=0
  178: f   next=     179 generation=0
  179: f   next=     180 generation=0
```

We are working on a fix.

Thank you for using pdfcpu 💚

**Comment by hhrutter** [comment]
Fixed with latest commit.
