### ISSUE TITLE
validation errors

### ISSUE THREAD

**Issue by HuabeiYou** [pdfcpu/pdfcpu#310]
Hi there,

Thanks for the speedy fix of #307, I recently found two more files (crash.log attached below) that can be opened by a pdf viewer but failed the validation, so maybe you wanna have a look.
1.pdf:
```
validating(mode=relaxed) 1.pdf ...
dereferenceObject: problem dereferencing object 762: pdfcpu: parse: corrupt hex literal
```
and 2.pdf:
```
validating(mode=relaxed) 2.pdf ...
validation error: pdfcpu: validateIntegerEntry: dict=freeFormGouraudShadedTriangleMeshesDict entry=BitsPerFlag invalid dict entry
```
Thanks for the help!
[1_crash.log](https://github.com/pdfcpu/pdfcpu/files/6167933/1_crash.log)
[2_crash.log](https://github.com/pdfcpu/pdfcpu/files/6167934/2_crash.log)

**Comment by hhrutter** [comment]
Thanks for reporting this 💚

**Comment by hhrutter** [comment]
The issue with 2.pdf is fixed in order to fix the issue with the corrupt hex literal I will need the pdf for a fix.

**Comment by hhrutter** [comment]
Closed due to inactivity.
