### ISSUE TITLE
validateDateEntry: invalid date on watermark add

### ISSUE THREAD

**Issue by pierremonico** [pdfcpu/pdfcpu#312]
Unfortunately I can't disclose the file this is run on since it is confidential, but when running `pdfcpu watermark add -mode text -- "Approved" "" ~/in.pdf ~/out.pdf` I get following stdout: 
```
writing /Users/someUser/out.pdf...
pdfcpu: validateDateEntry: <20141117162446Z00'00'> invalid date
```

Did I miss anything or what is the date validation all about? 

Thank you.

**Comment by hhrutter** [comment]
Hi!

When a pdfcpu comand returns such an error the approach is to first check if the source PDF file validates fine.
Please post the output of `pdfcpu val -vv source.pdf` and we take it from there.
The stack trace and a few lines above should be sufficient.

Thank you for reporting this and for using pdfcpu 💚

**Comment by pierremonico** [comment]
Hi @hhrutter, thanks for the reply. Please find the full log attached.
[log.txt](https://github.com/pdfcpu/pdfcpu/files/6203963/log.txt)

**Comment by hhrutter** [comment]
This file contains an invalid Date missing `D:`
<img width="800" alt="Screenshot 2021-03-25 at 11 47 27" src="https://user-images.githubusercontent.com/11322155/112462764-b8667a80-8d61-11eb-9e93-a6d9451d17a8.png">


```
739: was compressed 441[17] generation=0 pdfcpu.Dict 
<<
	<ADBE_CompoundType, <<
		<DocSettings, (439 0 R)>
		<LastModified, (20141117162446Z00'00')>
		<Private, Header>
	>>>
>>
```
This dict is usually generated by Adobe Acrobat.
A possibility is that the culprit is the producer of this PDF: *PDF-tools.com*

**Comment by pierremonico** [comment]
Thanks for the insight. Sorry if here is not the right place to ask but: for my use-case where I just want to get a document watermarked, why does validation need to pass first? Can't I just skip that and have my doc watermarked?

**Comment by hhrutter** [comment]
pdfcpu has to assume a valid input file, there is really no way around that.
The way it works is once an input PDF is read into memory it gets validated.
Only if the validation is successful processing of your chosen operation starts.

But there is a workaround for cornercases, try this:

1) Locate your pdfcpu config dir: `pdfcpu ver -v`

2) Edit config.yml and set validationMode to *validationNone*:
```
#########################
# Default configuration #
#########################

reader15: true
decodeAllStreams: true

# validationMode:
# ValidationStrict,
# ValidationRelaxed,
# ValidationNone
validationMode: ValidationRelaxed
```
Let me know if this works out for you and don't forget to reset the validationMode after your done with the file in question.
In general stamping without validation is not recommended and is not guaranteed to work.

Do you know the processing history of this file?
It's hard to believe that Adobe messes up like this, all other Dates in this PDF are correct.
Most probably PDF-tools.com is to blame for this in which case you could file a bug with them or just switch to a different tool.

**Comment by pierremonico** [comment]
Thanks for the workaround and sorry for the late reply. Unfortunately I don't know the processing history of the file, let's hope it's an isolated case.

**Comment by hhrutter** [comment]
Relaxed validation using v0.3.10 will digest these odd Dates.
