### ISSUE TITLE
watermark position and size error

### ISSUE THREAD

**Issue by RickyWei** [pdfcpu/pdfcpu#316]
Hi there,

I am trying to use the api to add a stamp to pdf, which should be looked like this
![image](https://user-images.githubusercontent.com/22569611/112934010-e693e380-90ee-11eb-9d5f-2809d18e6a1c.png)
my code as following
```go
err := api.AddTextWatermarksFile(inFile, outFile, nil, true, "draft", "points:48, sc:1, fillc:.8 .8 .4, op:.3", nil)
```
But unfortunately, I got result like this. **The stamp is smaller than the example, the text is mirrored and the position is not in the center.**
Also, I got same result by using the cmd. ` pdfcpu stamp add -mode text -- "Draft" "points:48, sc:1, fillc:.8 .8 .4, op:.3" in.pdf out.pdf`(the version is v0.3.9 dev)
![image](https://user-images.githubusercontent.com/22569611/112934153-26f36180-90ef-11eb-8d32-b4f7c39095ae.png)

Look forward to your help.
Thanks in advance :)

**Comment by hhrutter** [comment]
Thanks for reporting this!

Please be so kind and share your original test PDF and I take a look.

**Comment by RickyWei** [comment]
> Thanks for reporting this!
> 
> Please be so kind and share your original test PDF and I take a look.

Thanks for your reply.
The pdf link is here https://github.com/RickyWei/pdftool/blob/main/inputpdf/Google.pdf

**Comment by RickyWei** [comment]
@hhrutter Any advice for this problem? Did I make any mistake or miss any thing?

**Comment by hhrutter** [comment]
This is a bug and I am working on a fix.

**Comment by RickyWei** [comment]
> This is a bug and I am working on a fix.

Thanks for your help. I will keep an eye on this thread. If you need me to provide any info or help, please let me know. : )

**Comment by hhrutter** [comment]
Fixed with latest commit!
