### ISSUE TITLE
hash PDF difference

### ISSUE THREAD

**Issue by Shea11012** [pdfcpu/pdfcpu#317]
when I add properties into the pdf and remove the property，then compare hash between the origin pdf  and the modify pdf why they are difference?

**Comment by hhrutter** [comment]
Hello!

Every PDF gets validated and optimized before any pdfcpu command execution.
When pdfcpu creates a PDF after command execution it writes out the underlying cross reference table cleanly object by object.

**Comment by Shea11012** [comment]
> Hello!
> 
> Every PDF gets validated and optimized before any pdfcpu command execution.
> When pdfcpu creates a PDF after command execution it writes out the underlying cross reference table cleanly object by object.

Thank you for your reply.
If I want to keep same hash, how can i do that?

**Comment by hhrutter** [comment]
This will be enforced by signing your PDF but that feature is still being worked on.
Short answer: Right now you can't :(

**Comment by Shea11012** [comment]
thank you.
