### ISSUE TITLE
Access pagecount and metadata

### ISSUE THREAD

**Issue by meerkat-mary** [pdfcpu/pdfcpu#318]
Hi pdfcpu developers,

At the moment the [InfoFile](https://github.com/pdfcpu/pdfcpu/blob/292d125947cac2a381358ac44bbfb51e0ec01126/pkg/api/info.go#L53)  api function returns a formatted string array similar to this example:

```
pdfcpu info -u cm test.pdf
         PDF version: 1.7
          Page count: 1
           Page size: 21.00 x 29.70 cm
.........................................
               Title:
              Author:
             Subject:
        PDF Producer: pdfcpu v0.3.2
     Content creator:
       Creation date: D:20190823010752+02'00'
   Modification date: D:20190823010752+02'00'
            Keywords: key1
                      key2
          Properties: name1 = val1
                      name2 = val2
..........................................
              Tagged: No
              Hybrid: No
          Linearized: No
  Using XRef streams: Yes
Using object streams: Yes
          Watermarks: No
..........................................
           Encrypted: No
         Permissions: Full access
```

Would it be possible to introduce a new api function to return this information as a Struct please?

I need to extract the page count and the title/author/subject to display this metadata in my UI, however I need to pattern match on the strings (and split them correctly) in order to get the right information out which is a little fragile - or if pdfcpu already has this functionality could you kindly point me in the right direction?

Thank you! 😀

**Comment by hhrutter** [comment]
Hi there,

If you have a validated xRefTable in front of you it should all be there:

![Screenshot 2021-04-03 at 00 11 54](https://user-images.githubusercontent.com/11322155/113457955-80220480-9411-11eb-9128-c2b519a1f3a4.png)

**Comment by meerkat-mary** [comment]
Perfect thank you @hhrutter - I'll give this a go and let you know if I have any issues 😀

**Comment by meerkat-mary** [comment]
I was able to pass in the pdf path to ```api.ReadContextFile``` which returned a Context Struct containing an XRefTable struct - so now I can get the metadata directly! Thank you for your help @hhrutter ⭐

**Comment by hhrutter** [comment]
👍 
Please consider becoming a sponsor.
Sponsorship plays an important part in keeping pdfcpu alive in the long run.
Lots of features to come..

**Comment by hhrutter** [comment]
Thank you so much for becoming a pdfcpu sponsor.
Very much appreciated 💚
