### ISSUE TITLE
validation: GoTo Action without entry "D"

### ISSUE THREAD

**Issue by calumwallbridge** [pdfcpu/pdfcpu#319]
Getting this validation error in relaxed mode when working fine in Mac Preview:
`validation error: dict=GoTo required entry=D missing.`

Attached both the pdf and the simple logs (verbose file too big) :)
[nosplit.pdf](https://github.com/pdfcpu/pdfcpu/files/6254531/nosplit.pdf)
[nosplit.log](https://github.com/pdfcpu/pdfcpu/files/6254539/nosplit.log)

**Comment by hhrutter** [comment]
Thanks for reporting this.
I'll check it out.

**Comment by hhrutter** [comment]
This is fixed with v0.3.10
