### ISSUE TITLE
embed hocr (invisible text)

### ISSUE THREAD

**Issue by freman** [pdfcpu/pdfcpu#32]
tesseract (and by extension gosseract) produce an html/xml format called hocr containing information about the text that was ocred

I'd like to be able to embed this in my pdfs (like https://github.com/tmbdev/hocr-tools/blob/master/hocr-pdf) but I'm stuck at trying to add the invisible font :(

Any help you can offer along those lines would be awesome.

**Comment by hhrutter** [comment]
Sorry I don't know anything about _hocr_.
Also no idea why there is a need for an invisible font.
Maybe if you can provide a sample hocr-pdf output I can help you.

**Comment by freman** [comment]
The most common way to embed hocr (html ocr) is to use a transparent TTF and add the text to the document in the correct locations. It's one way do searchable scans (well, not with hocr, but with transparent fonts, the hocr is just a format that's outputted by tesseract)

If I can figure out how to add a TTF to a document using pdfcpu I can do the rest pretty much :D

I've managed it with the `gofpdf` and the `unidoc` libraries but I'd rather keep my dependancies down to just `pdfcpu` (unidoc can't even extract the scans :() :D

![sample](https://user-images.githubusercontent.com/506680/44372929-bb55ba80-a529-11e8-95b6-40ebf114014e.png)
[sample.hocr.txt](https://github.com/hhrutter/pdfcpu/files/2304252/sample.hocr.txt)

**Comment by hhrutter** [comment]
Although it is not pdfcpu's main intention, you can easily generate your own pdfs as long as you know what you are doing. Here is a pointer: 'pdfcpu/pkg/pdfcpu/createTestPDF.go'
It is very low level but as long as you have the ttf file in your hands and you know your way around with FontDescriptor dicts in PDF it is doable - not very convenient though I have to admit. 
:(

So please let me understand this:
The file you posted is the result of tesseract processing a screenshot image of the license file?
The tesseract FAQ tells me tesseract can produce pdfs directly or hocr. What's stopping you from outputting what you need in one pass using tesseract?

You mentioned you managed to get what you want using fpdf and unidoc.
Can you run the file you posted through this pipeline?
I'd like to analyze the output to get a better understanding
and this would help me figure out how that could in the overall picture of pdfcpu.
It's a pdf processor after all
;)

Please don't forget to star pdfcpu if you haven't already done so.

**Comment by freman** [comment]
> It is very low level but as long as you have the ttf file in your hands and you know your way around with FontDescriptor dicts in PDF it is doable
That's my problem, this is my first foray into the world of PDF, I'm making some progress but it's slow going.

> The file you posted is the result of tesseract processing a screenshot image of the license file?
Simple example so I can show you what I'm doing, my only other example is a scan of my council rates bill, don't think you want to be reading that.

> What's stopping you from outputting what you need in one pass using tesseract?
I'm actually using [gosseract](https://github.com/otiai10/gosseract) which is wrapped around tesseract libraries and doesn't appear to support pdf output at all (tho maybe it can be implemented - I'll have to look into it)

> Can you run the file you posted through this pipeline?
Ok, that I had a little trouble with (everything was setup for dealing with A4 documents from a scanner - and indeed from a pdf, not a png), but done.

[sample2.hocr.txt](https://github.com/hhrutter/pdfcpu/files/2308372/sample2.hocr.txt)
[sample2.pdf](https://github.com/hhrutter/pdfcpu/files/2308368/sample2.pdf)
![sample2](https://user-images.githubusercontent.com/506680/44434612-75fbc080-a5ef-11e8-98f0-9003bbbf76ae.png)

**Comment by abhilashsajeev** [comment]
@hhrutter Any updates on this? Adding ocr to existing pdf would be really great feature. current python library ocrmypdf is slow.

**Comment by hhrutter** [comment]
Hi!

There are no immediate plans on incorporating OCR into pdfcpu and that's also the reason why this issue is closed.
