### ISSUE TITLE
decrypt: avoid double unescaping of string literals

### ISSUE THREAD

**Issue by NicYan** [pdfcpu/pdfcpu#322]
/usr/local/bin/pdfcpu decrypt -c /tmp/research-pdf/ /tmp/research-pdf/CS_479378d2ad++.pdf /tmp/research-pdf/out1.pdf

Message :
writing /tmp/research-pdf/out1.pdf...
Unescape: illegal escape sequence \N detected

**Comment by hhrutter** [comment]
Thank you for reporting this!

I need more info in order to analyze this.
Can you provide an encrypted sample PDF?

Or at least post a stack trace showing the error context.
You can generate verbose output by adding `-v` or very verbose output with `-vv`

**Comment by NicYan** [comment]
Thank you for your reply!
The pdf file is really inconvenient to provide, sorry!

The following are the details after adding -v

/usr/local/bin/pdfcpu decrypt -v -c /tmp/research-pdf/ /tmp/research-pdf/CS_479378d2ad++.pdf /tmp/research-pdf/out1.pdf

Message:
writing /tmp/research-pdf/out1.pdf...
 INFO: 2021/04/14 18:22:25 PDF Version 1.5 conforming reader
 INFO: 2021/04/14 18:22:25 permission bits: 100000000100
 INFO: 2021/04/14 18:22:25 Bit  3: true (print(rev2), print quality(rev>=3))
 INFO: 2021/04/14 18:22:25 Bit  4: false (modify other than controlled by bits 6,9,11)
 INFO: 2021/04/14 18:22:25 Bit  5: false (extract(rev2), extract other than controlled by bit 10(rev>=3))
 INFO: 2021/04/14 18:22:25 Bit  6: false (add or modify annotations)
 INFO: 2021/04/14 18:22:25 Bit  9: false (fill in form fields(rev>=3)
 INFO: 2021/04/14 18:22:25 Bit 10: false (extract(rev>=3))
 INFO: 2021/04/14 18:22:25 Bit 11: false (modify(rev>=3))
 INFO: 2021/04/14 18:22:25 Bit 12: true (print high-level(rev>=3))
 INFO: 2021/04/14 18:22:26 validating
Fatal: Unescape: illegal escape sequence \N detected
github.com/pdfcpu/pdfcpu/pkg/pdfcpu.Unescape
	/home/soft/pdfcpu/pkg/pdfcpu/string.go:173
github.com/pdfcpu/pdfcpu/pkg/pdfcpu.StringLiteralToString
	/home/soft/pdfcpu/pkg/pdfcpu/utf16.go:123
github.com/pdfcpu/pdfcpu/pkg/pdfcpu/validate.validateStringEntry
	/home/soft/pdfcpu/pkg/pdfcpu/validate/objects.go:1073
github.com/pdfcpu/pdfcpu/pkg/pdfcpu/validate.validateStructElementDictPart2
	/home/soft/pdfcpu/pkg/pdfcpu/validate/structTree.go:460
github.com/pdfcpu/pdfcpu/pkg/pdfcpu/validate.validateStructElementDict
	/home/soft/pdfcpu/pkg/pdfcpu/validate/structTree.go:476
github.com/pdfcpu/pdfcpu/pkg/pdfcpu/validate.validateStructElementKArrayElement
	/home/soft/pdfcpu/pkg/pdfcpu/validate/structTree.go:122
github.com/pdfcpu/pdfcpu/pkg/pdfcpu/validate.validateStructElementDictEntryKArray
	/home/soft/pdfcpu/pkg/pdfcpu/validate/structTree.go:167
github.com/pdfcpu/pdfcpu/pkg/pdfcpu/validate.validateStructElementDictEntryK
	/home/soft/pdfcpu/pkg/pdfcpu/validate/structTree.go:226
github.com/pdfcpu/pdfcpu/pkg/pdfcpu/validate.validateStructElementDictPart1
	/home/soft/pdfcpu/pkg/pdfcpu/validate/structTree.go:401
github.com/pdfcpu/pdfcpu/pkg/pdfcpu/validate.validateStructElementDict
	/home/soft/pdfcpu/pkg/pdfcpu/validate/structTree.go:471
github.com/pdfcpu/pdfcpu/pkg/pdfcpu/validate.validateStructElementKArrayElement
	/home/soft/pdfcpu/pkg/pdfcpu/validate/structTree.go:122
github.com/pdfcpu/pdfcpu/pkg/pdfcpu/validate.validateStructElementDictEntryKArray
	/home/soft/pdfcpu/pkg/pdfcpu/validate/structTree.go:167
github.com/pdfcpu/pdfcpu/pkg/pdfcpu/validate.validateStructElementDictEntryK
	/home/soft/pdfcpu/pkg/pdfcpu/validate/structTree.go:226
github.com/pdfcpu/pdfcpu/pkg/pdfcpu/validate.validateStructElementDictPart1
	/home/soft/pdfcpu/pkg/pdfcpu/validate/structTree.go:401
github.com/pdfcpu/pdfcpu/pkg/pdfcpu/validate.validateStructElementDict
	/home/soft/pdfcpu/pkg/pdfcpu/validate/structTree.go:471
github.com/pdfcpu/pdfcpu/pkg/pdfcpu/validate.validateStructElementKArrayElement
	/home/soft/pdfcpu/pkg/pdfcpu/validate/structTree.go:122
github.com/pdfcpu/pdfcpu/pkg/pdfcpu/validate.validateStructElementDictEntryKArray
	/home/soft/pdfcpu/pkg/pdfcpu/validate/structTree.go:167
github.com/pdfcpu/pdfcpu/pkg/pdfcpu/validate.validateStructElementDictEntryK
	/home/soft/pdfcpu/pkg/pdfcpu/validate/structTree.go:226
github.com/pdfcpu/pdfcpu/pkg/pdfcpu/validate.validateStructElementDictPart1
	/home/soft/pdfcpu/pkg/pdfcpu/validate/structTree.go:401
github.com/pdfcpu/pdfcpu/pkg/pdfcpu/validate.validateStructElementDict
	/home/soft/pdfcpu/pkg/pdfcpu/validate/structTree.go:471
github.com/pdfcpu/pdfcpu/pkg/pdfcpu/validate.validateStructElementKArrayElement
	/home/soft/pdfcpu/pkg/pdfcpu/validate/structTree.go:122
github.com/pdfcpu/pdfcpu/pkg/pdfcpu/validate.validateStructElementDictEntryKArray
	/home/soft/pdfcpu/pkg/pdfcpu/validate/structTree.go:167
github.com/pdfcpu/pdfcpu/pkg/pdfcpu/validate.validateStructElementDictEntryK
	/home/soft/pdfcpu/pkg/pdfcpu/validate/structTree.go:226
github.com/pdfcpu/pdfcpu/pkg/pdfcpu/validate.validateStructElementDictPart1
	/home/soft/pdfcpu/pkg/pdfcpu/validate/structTree.go:401
github.com/pdfcpu/pdfcpu/pkg/pdfcpu/validate.validateStructElementDict
	/home/soft/pdfcpu/pkg/pdfcpu/validate/structTree.go:471
github.com/pdfcpu/pdfcpu/pkg/pdfcpu/validate.validateStructElementKArrayElement
	/home/soft/pdfcpu/pkg/pdfcpu/validate/structTree.go:122
github.com/pdfcpu/pdfcpu/pkg/pdfcpu/validate.validateStructElementDictEntryKArray
	/home/soft/pdfcpu/pkg/pdfcpu/validate/structTree.go:167
github.com/pdfcpu/pdfcpu/pkg/pdfcpu/validate.validateStructElementDictEntryK
	/home/soft/pdfcpu/pkg/pdfcpu/validate/structTree.go:226
github.com/pdfcpu/pdfcpu/pkg/pdfcpu/validate.validateStructElementDictPart1
	/home/soft/pdfcpu/pkg/pdfcpu/validate/structTree.go:401
github.com/pdfcpu/pdfcpu/pkg/pdfcpu/validate.validateStructElementDict
	/home/soft/pdfcpu/pkg/pdfcpu/validate/structTree.go:471
github.com/pdfcpu/pdfcpu/pkg/pdfcpu/validate.validateStructElementKArrayElement
	/home/soft/pdfcpu/pkg/pdfcpu/validate/structTree.go:122
github.com/pdfcpu/pdfcpu/pkg/pdfcpu/validate.validateStructElementDictEntryKArray
	/home/soft/pdfcpu/pkg/pdfcpu/validate/structTree.go:167

**Comment by hhrutter** [comment]
👍 
There seems to be an issue with a particular string.

Was this file encrypted with pdfcpu or some other tool?

Do you have the original (unencrypted) PDF?
If so, please check if this error also ocurres during validation:
`pdfcpu validate -v test.pdf`

Please also check if you can open the original and the encrypted PDF with Adobe Reader or Mac Preview.

**Comment by NicYan** [comment]
The pdf file is encrypted by tools other than pdfcpu
I cannot get the unencrypted pdf file
If I know the original password, can I reset the permissions?
[validate.log](https://github.com/pdfcpu/pdfcpu/files/6314476/validate.log)

**Comment by hhrutter** [comment]
Thanks for standing by.

Unless you removed the arguments for supplying your password(s) (upw, opw) for confidentiality reasons
it looks like you are  trying to decrypt with the default passwords, which may be ok, as a reminder the usage is:

`usage: pdfcpu decrypt [-upw userpw] [-opw ownerpw] inFile [outFile]`

where upw is the user password and opw the owner password.

Normally pdfcpu should report an error if the provided password(s) are incorrect..

Please do me favor and install the latest commit which should give us more context to find out what's going on here
and rerun validation but now with `--v` since this will show us more.

**Comment by NicYan** [comment]
Sorry, it took so long to reply
My latest attempt to decrypt with the correct password is still the same error

Use version pdfcpu: v0.3.11 dev

The following is the error message:
pdfcpu decrypt -c /tmp/pdf/ -opw citicsRpt# /tmp/pdf/test.pdf /tmp/pdf/out.pdf
writing /tmp/pdf/out.pdf...
Unescape: illegal escape sequence \N detected: <þÿO\N:bT_Sр0>

pdfcpu decrypt -c /tmp/pdf/ -upw citicsRpt# /tmp/pdf/test.pdf /tmp/pdf/out.pdf
writing /tmp/pdf/out.pdf...
Unescape: illegal escape sequence \N detected: <þÿO\N:bT_Sр0>

There are detailed log information in the attachment
[err.log](https://github.com/pdfcpu/pdfcpu/files/6348373/err.log)

**Comment by hhrutter** [comment]
👍  This helps.
Thanks for discovering a bug.
Working on a fix.

**Comment by hhrutter** [comment]
Please check and let me know if this fix works for you.

Thank you!

**Comment by NicYan** [comment]
I used the latest code, and the bug was fixed!
Thank you so much for your help! You are a very responsible person!
