### ISSUE TITLE
extract image: Add output format

### ISSUE THREAD

**Issue by renard** [pdfcpu/pdfcpu#323]
Currently the output resource (at least for image) is hard-coded to `fmt.Sprintf("%s_%d_%s.%s", fileName, img.PageNr, img.Name, img.Type)`.

It would be nice to have the ability to specify it from CLI or in config file. The typical use case would be to convert PDF to CBZ files where the desired file scheme would be defined by `fmt.Sprintf("P%.3d.%s", img.PageNr, img.Type)`.

It would require to add an extra parameter to `api.ExtractImages` and I am not sure this is a correct way to do it. If you do have a better idea it would be appreciated.

TIA.

**Comment by hhrutter** [comment]
Thanks for the input.
Will be taken into consideration.
This is related to #300.

**Comment by hhrutter** [comment]
This will be addressed in the upcoming release.

**Comment by hhrutter** [comment]
Fixed with 0.3.12
