### ISSUE TITLE
read: handle corrupt pointer to previous xref section in trailer dict 

### ISSUE THREAD

**Issue by eshevarova** [pdfcpu/pdfcpu#326]
Hello!
I tried to merge pdf files with "Merge" function, but got an error "dereferenceObject: problem dereferencing object 3: strconv.Atoi: parsing \"j\": invalid syntax".  Could you help me, please?
[crash.log](https://github.com/pdfcpu/pdfcpu/files/6391319/crash.log)
[Zakaz_Azimut Otel Tulskaia_Spitsin.pdf](https://github.com/pdfcpu/pdfcpu/files/6391330/Zakaz_Azimut.Otel.Tulskaia_Spitsin.pdf)

**Comment by hhrutter** [comment]
ok, I take a look.

**Comment by hhrutter** [comment]
There is a corrupt pointer to the previous xref section.

This was possibly introduced by a one-off insert of the 3 bytes #9EE965 at the beginning of the file right before the PDF version header of the original first version of the file.

Then an incremental write happened adding some page annotations and  dumb copying the wrong offsets from the previous trailer.

I see if I can provide a fix for such a scenario.




 at the beginning of the file.

**Comment by eshevarova** [comment]
Thanks! I will be waiting for your answer.

**Comment by hhrutter** [comment]
Do you know the history of this file?
I am curious to know who inserted those 3 bytes at the beginning.

**Comment by eshevarova** [comment]
Yep.
This file was generated by our integration partner.
I have researched how we get this file. And it turned out that we got it by base64 string, and this string starts with “nullVJ...”. This “null” is those 3 bytes. 
We have sent email to our partner with this problem.

**Comment by hhrutter** [comment]
I prepared a fix.
Please fetch and go install the latest commit and let me know if this works for you.

**Comment by eshevarova** [comment]
It works. Thanks a lot!
