### ISSUE TITLE
validate: Link annotations: Quadpoints

### ISSUE THREAD

**Issue by bsathishciv** [pdfcpu/pdfcpu#330]
In Annotations.go, the quadpoint element size for Links is restricted to 8 (https://github.com/pdfcpu/pdfcpu/blob/master/pkg/pdfcpu/validate/annotations.go line:331) whereas, in https://www.adobe.com/content/dam/acom/en/devnet/pdf/pdfs/PDF32000_2008.pdf, it is mentioned that the quadpoints are multiples of 8.

Due to this we face an error from the library when validating my PDF which has links spanning multiple lines.

Kindly let me know if we have any possible way to skip the validations

Best regards,
Sathish Balaji

**Comment by petervwyatt** [comment]
I will just add that ISO 32000 (all editions) also say for **QuadPoints** "... specifying the four vertices of the quadrilateral in counterclockwise order." yet a number of popular implementations do NOT process the points "_in counterclockwise order_" which causes different behaviours between products as to where the actual link activation works. Just saying... the spec is clear!

**Comment by hhrutter** [comment]
@petervwyatt Thanks for the insight.
I will look into this.

**Comment by hhrutter** [comment]
This validation is fixed with latest commit.
