### ISSUE TITLE
An API function to export attachments as bytes

### ISSUE THREAD

**Issue by vsenko** [pdfcpu/pdfcpu#331]
Currently it's only possible to export attachments to a specified folder as files. In certain scenarios it could be advantageous to be able to obtain them as bytes.

Things to consider:
- current implementation is disk IO bound as long as the attachments have to be saved to the filesystem;
- in some cases it is not desirable to save user's data to filesystem because of specific regulations.

Would the project benefit from such a new feature?

In case if it will, how should it be implemented? What about adding two new functions:
```go
func ExtractAttachmentsAsBytes(rs io.ReadSeeker, fileNames []string, conf *pdfcpu.Configuration) ([][]byte, error)
func ExtractAttachmentsAsBytesFile(inFile, files []string, conf *pdfcpu.Configuration) ([][]byte, error)
```

**Comment by hhrutter** [comment]
Make sense but for such cases we rather return the *[]Attachment* which comes with an *io.Reader* - like in:
```
pdfcpu.ExtractAttachments(ids []string) ([]Attachment, error)
```

Then further attachment processing is up to the user.

**Comment by vsenko** [comment]
I'm in need of this feature and going to implement it in the fork in the forthcoming days. As far as I can see, these exact functions are trivial to implement.

I could make a pull request out of it, but I'll need some guidance.

Ideas:
- Every function that saves files to a folder would benefit from a memory only alternative.
- Probably it would be better to utilize a slice of `io.Writer`s similar to `SetPermissions`, this way all `Export*` functions would behave similarly.
- In my opinion functions like `RemoveAttachments` `RemoveAttachmentsFile` have the perfect signature - the first one is`rs io.ReadSeeker` -> `w io.Writer`, the second one is `inFile string` -> `outFile string`, but with all `Export*` functions the first ones are already `rs io.ReadSeeker` -> `outDir string`. I don't know if breaking changes are OK or not currently. In case if they're OK, the signature could be changed to `rs io.ReadSeeker` -> `ws []io.Writer`, otherwise new functions names are needed.

In case if it would be harder for you to guide me than to implement it some other way, please feel free to inform me about it, I'll just stick to my fork for a while.

**Comment by hhrutter** [comment]
Hello!
I appreciate the effort but this will already be part of the upcoming release and is being worked on.
I will definitely consider your input.
Also PRs in general better after the release - right now not so good because of substantial changes to the code base.

**Comment by vsenko** [comment]
Got it, thank you for your work!
