### ISSUE TITLE
watermark error: dict=optContentPropertiesDict required entry=D missing

### ISSUE THREAD

**Issue by jidzhang** [pdfcpu/pdfcpu#332]
The pdf file was plot by GStarCAD 2020，and I tested many files. 
I'm sure that all pdf files plot by GStarCAD 2020/2021 will get the same error.

Please check the attached file.

[2.pdf](https://github.com/pdfcpu/pdfcpu/files/6490430/2.pdf)

**Comment by hhrutter** [comment]
ok, I want to take a look at this but 2.pdf does not validate:
```
Go-> pdfcpu val -v 2.pdf
validating(mode=relaxed) i332.pdf ...
 INFO: 2021/05/17 09:39:24 PDF Version 1.5 conforming reader
Fatal: unexpected EOF
```

Is this your problem because it looks different.
You need a valid file in order to add watermarks.

**Comment by jidzhang** [comment]
> 
> 
> ok, I want to take a look at this but 2.pdf does not validate:
> 
> ```
> Go-> pdfcpu val -v 2.pdf
> validating(mode=relaxed) i332.pdf ...
>  INFO: 2021/05/17 09:39:24 PDF Version 1.5 conforming reader
> Fatal: unexpected EOF
> ```
> 
> Is this your problem because it looks different.
> You need a valid file in order to add watermarks.

Hi, Hrutter

I think you downloaded the wrong file. Please download the 2.pdf again.

The file is 963 bits,  very small.

And I run the command: pdfcpu val -v 2.pdf,  get:

C:\Users\thinkpad\Desktop\pdfcpu_0.3.11_Windows_i386>pdfcpu.exe val -v 2.pdf
validating(mode=relaxed) 2.pdf ...
 INFO: 2021/05/21 12:59:59 PDF Version 1.5 conforming reader
 INFO: 2021/05/21 12:59:59 validating
STATS: 2021/05/21 12:59:59 XRefTable:
*************************************************************************************************
HeaderVersion: 1.7
has 1 pages
using xref streams
XRefTable:
                     Size: 9
              Root object: (1 0 R)
XRefTable with 9 entries:
    0: f   next=       0 generation=65535
    1:   offset=       9 generation=0 pdfcpu.Dict type=Catalog
<<
        <OCProperties, (20 0 R)>
        <PageLayout, SinglePage>
        <PageMode, UseOC>
        <Pages, (2 0 R)>
        <Type, Catalog>
>>
    2:   offset=     653 generation=0 pdfcpu.Dict type=Pages
<<
        <Count, 1>
        <Kids, [(3 0 R)]>
        <Type, Pages>
>>
    3:   offset=     119 generation=0 pdfcpu.Dict type=Page
<<
        <Contents, (4 0 R)>
        <MediaBox, [0 0 841.89 595.28]>
        <Parent, (2 0 R)>
        <Resources, (21 0 R)>
        <Type, Page>
>>
    4:   offset=     234 generation=0 pdfcpu.StreamDict
<<
        <Filter, FlateDecode>
        <Length, (5 0 R)>
>>
    5:   offset=     550 generation=0 pdfcpu.Integer
243
   19:   offset=     609 generation=0 pdfcpu.Dict
<<
>>
   20:   offset=     631 generation=0 pdfcpu.Dict
<<
>>
   21:   offset=     569 generation=0 pdfcpu.Dict
<<
        <Properties, (19 0 R)>
>>

Empty free list.

Total pages: 1
No font info available.

No image info available.


STATS: 2021/05/21 12:59:59 Timing:
STATS: 2021/05/21 12:59:59 read                 :  0.041s  97.6%
STATS: 2021/05/21 12:59:59 validate             :  0.001s   2.4%
STATS: 2021/05/21 12:59:59 total processing time:  0.042s

STATS: 2021/05/21 12:59:59 Original:
STATS: 2021/05/21 12:59:59 File size            : 963.000000 Bytes (963 bytes)
STATS: 2021/05/21 12:59:59 Total binary data    : 243.000000 Bytes (243 bytes) 25.2%
STATS: 2021/05/21 12:59:59 Total other data     : 720.000000 Bytes (720 bytes) 74.8%

Fatal: dict=optContentPropertiesDict required entry=D missing
github.com/pdfcpu/pdfcpu/pkg/pdfcpu.Dict.Entry
        /Users/horstrutter/go/src/github.com/pdfcpu/pdfcpu/pkg/pdfcpu/dict.go:110
github.com/pdfcpu/pdfcpu/pkg/pdfcpu/validate.validateDictEntry
        /Users/horstrutter/go/src/github.com/pdfcpu/pdfcpu/pkg/pdfcpu/validate/objects.go:236
github.com/pdfcpu/pdfcpu/pkg/pdfcpu/validate.validateOCProperties
        /Users/horstrutter/go/src/github.com/pdfcpu/pdfcpu/pkg/pdfcpu/validate/optionalContent.go:421
github.com/pdfcpu/pdfcpu/pkg/pdfcpu/validate.validateRootObject
        /Users/horstrutter/go/src/github.com/pdfcpu/pdfcpu/pkg/pdfcpu/validate/xReftable.go:977
github.com/pdfcpu/pdfcpu/pkg/pdfcpu/validate.XRefTable
        /Users/horstrutter/go/src/github.com/pdfcpu/pdfcpu/pkg/pdfcpu/validate/xReftable.go:40
github.com/pdfcpu/pdfcpu/pkg/api.ValidateContext
        /Users/horstrutter/go/src/github.com/pdfcpu/pdfcpu/pkg/api/api.go:70
github.com/pdfcpu/pdfcpu/pkg/api.Validate
        /Users/horstrutter/go/src/github.com/pdfcpu/pdfcpu/pkg/api/validate.go:50
github.com/pdfcpu/pdfcpu/pkg/api.ValidateFile
        /Users/horstrutter/go/src/github.com/pdfcpu/pdfcpu/pkg/api/validate.go:91
github.com/pdfcpu/pdfcpu/pkg/cli.Validate
        /Users/horstrutter/go/src/github.com/pdfcpu/pdfcpu/pkg/cli/cli.go:33
github.com/pdfcpu/pdfcpu/pkg/cli.Process
        /Users/horstrutter/go/src/github.com/pdfcpu/pdfcpu/pkg/cli/process.go:35
main.process
        /Users/horstrutter/go/src/github.com/pdfcpu/pdfcpu/cmd/pdfcpu/process.go:95
main.processValidateCommand
        /Users/horstrutter/go/src/github.com/pdfcpu/pdfcpu/cmd/pdfcpu/process.go:137
main.commandMap.process
        /Users/horstrutter/go/src/github.com/pdfcpu/pdfcpu/cmd/pdfcpu/cmd.go:145
main.main
        /Users/horstrutter/go/src/github.com/pdfcpu/pdfcpu/cmd/pdfcpu/main.go:55
runtime.main
        /Users/horstrutter/gotip/src/runtime/proc.go:225
runtime.goexit
        /Users/horstrutter/gotip/src/runtime/asm_386.s:1315
validation error
github.com/pdfcpu/pdfcpu/pkg/api.Validate
        /Users/horstrutter/go/src/github.com/pdfcpu/pdfcpu/pkg/api/validate.go:55
github.com/pdfcpu/pdfcpu/pkg/api.ValidateFile
        /Users/horstrutter/go/src/github.com/pdfcpu/pdfcpu/pkg/api/validate.go:91
github.com/pdfcpu/pdfcpu/pkg/cli.Validate
        /Users/horstrutter/go/src/github.com/pdfcpu/pdfcpu/pkg/cli/cli.go:33
github.com/pdfcpu/pdfcpu/pkg/cli.Process
        /Users/horstrutter/go/src/github.com/pdfcpu/pdfcpu/pkg/cli/process.go:35
main.process
        /Users/horstrutter/go/src/github.com/pdfcpu/pdfcpu/cmd/pdfcpu/process.go:95
main.processValidateCommand
        /Users/horstrutter/go/src/github.com/pdfcpu/pdfcpu/cmd/pdfcpu/process.go:137
main.commandMap.process
        /Users/horstrutter/go/src/github.com/pdfcpu/pdfcpu/cmd/pdfcpu/cmd.go:145
main.main
        /Users/horstrutter/go/src/github.com/pdfcpu/pdfcpu/cmd/pdfcpu/main.go:55
runtime.main
        /Users/horstrutter/gotip/src/runtime/proc.go:225
runtime.goexit
        /Users/horstrutter/gotip/src/runtime/asm_386.s:1315
