### ISSUE TITLE
jpeg re-encoding at default quality

### ISSUE THREAD

**Issue by zanmato** [pdfcpu/pdfcpu#333]
Version 3.10 (9fa39afd543b0c2ca3137f93279a186115ed1f77) introduces a call to `jpeg.Encode` for all jpeg images without a quality setting. This causes the jpeg to be reencoded in worse quality, at least in our case. Since if no quality option is specified the quality will be set to the default, which is 75 (https://golang.org/pkg/image/jpeg/#pkg-constants).
Ideally the image shouldn't be re-encoded at all. Is it possible to introduce an option for this? Along with a quality option.

**Comment by hhrutter** [comment]
Understood.
Let me think about this.
