### ISSUE TITLE
Adding New Bookmarks to Merged PDFs

### ISSUE THREAD

**Issue by meerkat-mary** [pdfcpu/pdfcpu#335]
Hi pdfcpu developers,

Is it possible to add new bookmarks (so that it appears in the sidebar) using pdfcpu? I've been able to use this excellent library to merge multiple documents together and it would be great to polish the output PDF with sidebar bookmarks to help make it easier for my users to navigate through (large) PDFs

Perhaps functionality that works in a similar way to WaterMarkMaps where you can construct a bookmark and page number map and the library wizzes through and adds them? 😀

If there is a way to get this done with the existing library functions, could you kindly provide a code example please? I had a look and I was only able to find a Split by Bookmark feature in the API

Grateful for your time!
Mary

**Comment by hhrutter** [comment]
Hello!

This sounds like a useful feature and goes into the pipeline.

**Comment by meerkat-mary** [comment]
Thank you @hhrutter :)

**Comment by elucidsoft** [comment]
+1

**Comment by hhrutter** [comment]
This feature is now part of v0.3.12 !
Checkout: [bookmarks_test.go](https://github.com/pdfcpu/pdfcpu/blob/master/pkg/api/test/bookmarks_test.go)

**Comment by meerkat-mary** [comment]
Amazing, thank you so much @hhrutter ⭐️ - I'll test it out

**Comment by hhrutter** [comment]
👍 Let me know

**Comment by meerkat-mary** [comment]
Hi @hhrutter - the bookmarking functionality works great, thank you very much!

There's a minor issue where it has trouble adding certain characters e.g. for the following Title "Applicant’s Form" - the apostrophe comes out garbled (attached screenshot) 

![image](https://user-images.githubusercontent.com/72500241/126815806-5f594acf-d71d-453a-8e53-5be576e52a8c.png)

The apostrophe was added in windows FYI (though I'm viewing the PDF on a Mac)

**Comment by hhrutter** [comment]
Thanks for reporting this!

**Comment by hhrutter** [comment]
This is fixed with latest commit!

**Comment by meerkat-mary** [comment]
Amazing, thank you! ⭐️

**Comment by iilyak** [comment]
How do I use this feature from CLI?

**Comment by hhrutter** [comment]
Sorry, not available via the CLI.
Also.. kind of complicated, there may be nested bookmarks..
