### ISSUE TITLE
decrypt: Unescape: illegal escape sequence \õ detected

### ISSUE THREAD

**Issue by ydzh** [pdfcpu/pdfcpu#337]

**Comment by ydzh** [comment]
the pdf can be decryed by chrome successfully. will the pdfcpu support to process illegal character?

**Comment by hhrutter** [comment]
A similar issue was fixed for #322.
Please go get the latest commit.
If the issue persists I will need a sample pdf to povide a fix.
Thank you for using pdfcpu 💚
