### ISSUE TITLE
attach: retrieve attachment file names for extraction

### ISSUE THREAD

**Issue by vsenko** [pdfcpu/pdfcpu#338]
For attachments with descriptions functions `ListAttachments` and `ListAttachmentsFile` return not the file names, but concatenated strings that include file names and descriptions: https://github.com/pdfcpu/pdfcpu/blob/master/pkg/api/attach.go#L59

Because of this it is impossible to reliably obtain the list of attachments file names and thus to extract them.

A function(s) that will always return plain file names would be really handy.

**Comment by vsenko** [comment]
By the way, ListAttachments also sorts strings, but in some cases the order of attachments could be significant. As long as attachments are successively encoded in PDF file, it's sensible to consider them ordered. It would be handy if the new functions would not sort the filenames alphanumerically. Otherwise the order will be lost.

**Comment by hhrutter** [comment]
This will be fixed in the upcoming release.

BTW if you call ExtractAttachments and supply fileNames = nil pdfcpu will extract ALL attachments,
so there is no need to process the output of ListAttachments.
