### ISSUE TITLE
Create a page with text and image (or add text/image to existing pages)

### ISSUE THREAD

**Issue by raff** [pdfcpu/pdfcpu#339]
I need to create a PDF with text (/Content) and images (/Resources). The specific use case is to create a searchable PDF from a scanned PDF.

Another options could be to be able to add text to a page (that already contains the image) or add an image to a page that already contains the text (currently I can create new pages that are either text only (with pdfcpu.CreateDemoXRef) or image only (with pdfcpu.NewPageForImage).

Do you have any suggestion ?

**Comment by hhrutter** [comment]
Hello!

Have you tried the stamp api?

Check out:
pkg(api/stamp_test.go
pkg/samples/stamp/...

**Comment by hhrutter** [comment]
Closed due to inactivity.
