### ISSUE TITLE
(Win) import: wildcard not working

### ISSUE THREAD

**Issue by larrylau** [pdfcpu/pdfcpu#343]
> pdfcpu: 0.3.11
build : 2021-04-05T17:50:49Z
commit: 956f29f

It seems that os.Args not expanded wildcard paths on windows cmd shell.
> pdfcpu import album.pdf pics/*
pics/* needs an image extension (.jpg, .jpeg, .png, .tif, .tiff, .webp)

**Comment by hhrutter** [comment]
Thanks for reporting this!

**Comment by hhrutter** [comment]
This will be fixed in the upcoming release.
