### ISSUE TITLE
merging AcroForms

### ISSUE THREAD

**Issue by bruno-farias** [pdfcpu/pdfcpu#344]
Hi,

I have some documents with empty digital signatures fields and after using the merge command from pdfcpu it changes the file structure somehow that PDF readers can't use it anymore and the field it's gone.

![image-20210617-092444](https://user-images.githubusercontent.com/5460340/122903244-e1de7480-d357-11eb-97e5-dbe8461adcd2.png)

**I don't need this to work in every reader, at least on Adobe Reader should be fine, as sometimes in others it doesn't work anyway**

One thing that I notice was that the signature annotation from the originally generated file it's different from the one after merged:

Before merge: 
`<< /Type /Annot /Subtype /Widget /Rect [322.866142 137.873622 549.637795 191.870079] /P 11 0 R /F 4 /FT /Sig /T (\FE\FF\00s\00i\00g\00n\00a\00t\00u\00r\00e\00_\00e\00m\00p\00l\00o\00y\00e\00e\00_\001) /Ff 0 >>`

After merge:
`<</F 4/FT/Sig/Ff 0/P 11 0 R/Rect[322.866142000000 137.873622000000 549.637795000000 191.870079000000]/Subtype/Widget/T(\FE\FF\00s\00i\00g\00n\00a\00t\00u\00r\00e\00_\00e\00m\00p\00l\00o\00y\00e\00e\00_\001)/Type/Annot>>`

Also providing both files for comparison:

[invalid_pdf_without_siganture.pdf](https://github.com/pdfcpu/pdfcpu/files/6693047/invalid_pdf_without_siganture.pdf)
[default_extracted_pcleasing.pdf](https://github.com/pdfcpu/pdfcpu/files/6693048/default_extracted_pcleasing.pdf)

**Comment by hhrutter** [comment]
Hi and thanks for reporting this!

Merging PDFs containing Acrobat forms is untested territory to say the least but an interesting although not so common use case. You can have empty or populated forms, you can have digital signatures relying on form fields and much more..
You can even be trying to merge several PDF with each of them containing a different form.

I am gonna put that into the pipeline.

Thank you for using pdfcpu 💚

**Comment by hhrutter** [comment]
Do you think you can tell me a little bit more about your specific usecase/workflow?
I will try to solve this focused on your scenario first.
Thanks.

**Comment by bruno-farias** [comment]
We dynamically generate multiple PDF files that all can contain signature and form fields. Then we need to merge generated files into one file. The end user can later use the signature field to initiate digital signing process in preferred tool (e.g. Adobe Reader, DocuSign etc)

**Comment by hhrutter** [comment]
This is addressed with v0.3.12.
Please feed back.

**Comment by bruno-farias** [comment]
Tested and it now works!

Many thanks for your help and support 💚
