### ISSUE TITLE
validate: extGState dict entry TR

### ISSUE THREAD

**Issue by uwaeae** [pdfcpu/pdfcpu#347]
I had a PDF which is always crashing with the Message: "pdfcpu: processFunction: obj must be dict or stream dictessage "

[02_AN_512105769_Jacobsen(1).pdf](https://github.com/pdfcpu/pdfcpu/files/6728421/02_AN_512105769_Jacobsen.1.pdf)
[crash.log](https://github.com/pdfcpu/pdfcpu/files/6727547/crash.log)

best regards 

Florian

**Comment by hhrutter** [comment]
Thank you for reporting this!
A fix will be part of the upcoming release.
