### ISSUE TITLE
Windows installers do nothing

### ISSUE THREAD

**Issue by ooker777** [pdfcpu/pdfcpu#348]
I download both Windows installers in https://github.com/pdfcpu/pdfcpu/releases/tag/v0.3.11, but nothing happens. PowerShell cannot detect the `pdfcpu` command.

I use Windows 10 Home 10.0.19042 N/A Build 19042

**Comment by hhrutter** [comment]
Hi!

There is no Windows installer.
All you get is a zip file that contains a Windows exe file - the pdfcpu command line interface.
I am no Windows guy but just unzip the file and then run it like any other exe.

**Comment by ooker777** [comment]
ah I get it. Just open shell in the folder and type `pdfcpu`. I was confused because the expected behavior to run an exe file is to double click it.
