### ISSUE TITLE
Issue found by Svace static analyzer 

### ISSUE THREAD

**Issue by vvdvortsova** [pdfcpu/pdfcpu#354]
Hello
This warning found with the Svace.
There is mb can be nil. It can lead to panic.
https://github.com/pdfcpu/pdfcpu/blob/281745f818decfaec5ec2764d8fd43230ce30742/pkg/pdfcpu/info.go#L254
due to
https://github.com/pdfcpu/pdfcpu/blob/281745f818decfaec5ec2764d8fd43230ce30742/pkg/pdfcpu/boxes.go#L86
mb is dereferenced here
https://github.com/pdfcpu/pdfcpu/blob/281745f818decfaec5ec2764d8fd43230ce30742/pkg/pdfcpu/info.go#L256

**Comment by hhrutter** [comment]
Hello!
Could you post the whole report, so things stay in context for a better solution.
Thank you for reporting this!

**Comment by vvdvortsova** [comment]
Yes, sure. The whole report will looks like this
```
func appendPageBoxesInfo(...) {
...
mb := pb.MediaBox() // here mb may be nil
cb := pb.CropBox()
if cb == nil || mb.equals(*cb) {// here mb is dereferenced and it may lead to panic
      appendEqualMediaAndCropBoxInfo(ss, pb, unit, currUnit)
      return
}
appendNotEqualMediaAndCropBoxInfo(ss, pb, unit, currUnit)
```

``` 
func (pb PageBoundaries) MediaBox() *Rectangle { // may return nil value 
	if pb.Media == nil {
		return nil
	}
	return pb.Media.Rect
}
```
