### ISSUE TITLE
parse error: % within StringLiteral

### ISSUE THREAD

**Issue by lucashmorais** [pdfcpu/pdfcpu#356]
Hi there,

First of all, thank you for the amazing work on this library. I write this just to point out that I found a probably malformed PDF that is well handled by some other tools, but not by this one. The error I get by running validation on it is `Read: xRefTable failed: pdfcpu: scanLineRaw: returning nothing`. The sample file is the following:

[Sample](https://drive.google.com/file/d/1t9CKAWahi1kSkhjZbtYiFpdw5Smu_UhL/view?usp=sharing)

I run the tests with version 0.3.12, 0.3.11, and a more recent custom-built binary. I am not sure what writer might have generated the file, but I suppose it is either an old version of PowerPoint or LibreOffice Impress.

Thanks,
Lucas

**Comment by lucashmorais** [comment]
Just in case it might be useful, here is the repaired version of the same file produced by [PDF2GO](https://www.pdf2go.com/repair-pdf), which succeeds at validation:

[Repaired sample](https://drive.google.com/file/d/1CW9aXmQd_6wppV_bzIXnZWw8d3yeRi-S/view?usp=sharing)

**Comment by hhrutter** [comment]
Thanks for reporting this 👍

**Comment by hhrutter** [comment]
This is fixed with the latest commit.
