### ISSUE TITLE
Multiple stamp definitions in CLI

### ISSUE THREAD

**Issue by signalwerk** [pdfcpu/pdfcpu#359]
I use `pdfcpu` today for the first time and I have to say it's super awesome! This makes me so happy.

I think this is a feature request, but please let me know if it's a documentation-issue and I will happily provide a documentation PR.

## Use case
I would like to do a different Stamp on the first page of a pdf than on all the other pages.

## Current implementation

```sh
# process the first page and write the output to a tempoary file
pdfcpu stamp \
    add -unit 'mm' -pages '1' -mode text "Frontpage" "scalefactor: 1.0 abs, points: 12, rot: 0, fillcolor:#000000" \
    test.pdf temp.pdf

# do an other processing step with the temporary file
pdfcpu stamp \
    add -unit 'mm' -pages '2-l' -mode text "other pages" "scalefactor: 1.0 abs, points: 8, rot: 0, fillcolor:#000000" \
    temp.pdf out.pdf
```

## Suggested implementation
```sh
pdfcpu stamp \
    add -unit 'mm' -pages '1' -mode text "Frontpage" "scalefactor: 1.0 abs, points: 12, rot: 0, fillcolor:#000000" \
    add -unit 'mm' -pages '2-l' -mode text "other pages" "scalefactor: 1.0 abs, points: 8, rot: 0, fillcolor:#000000" \
    test.pdf out.pdf
```

**Comment by hhrutter** [comment]
The CLI commands are already quite complex.. 
Stamp sequences/batches need to be handled either via some OS level script or preferably in your Go backend.

Have a look at [stampVersatile_test.go](https://github.com/pdfcpu/pdfcpu/blob/master/pkg/api/test/stampVersatile_test.go).

**Comment by signalwerk** [comment]
👌 Sure I understand. Thank you. I will do it in two steps.
