### ISSUE TITLE
bookmarks: some chinese characters not displayed properly

### ISSUE THREAD

**Issue by kaiceo** [pdfcpu/pdfcpu#362]
Testing text mixing chinese, digital, english and punctuation is utf8 encoding,  every character is checked by utf8.ValidRune and passed. 
But some text encode error , i dont know where error occured, maybe i should not use utf8 encoding, or some thing wrong from utf8 encoding to utf16 by the latest commit modification
anyway, it is awesome after this commit
use package from the latest commit, test text is below
[testing str.txt](https://github.com/pdfcpu/pdfcpu/files/6889992/testing.str.txt)

![20210728112122](https://user-images.githubusercontent.com/63705580/127258606-0b5e3293-71e1-4d8a-a6d3-d98e5df39f09.png)

**Comment by hhrutter** [comment]
This issue is related to the specific font (file) used in your PDF viewer.
Maybe some Unicode Private Use Area code points.

**Comment by kaiceo** [comment]
thanks for replying in time, i will do more tests, maybe figure out some solutions . more feedbacks will be supplied by then

**Comment by kaiceo** [comment]
Some wierd  situation happened, three testing is below, all chinese words are usual, but some words including "尾" encode error

    f := "a919-2065308.pdf"
    api.AddBookmarksFile(f, "out.pdf", []pdfcpu.Bookmark{{Title: "test", PageFrom: 1}}, pdfcpu.NewDefaultConfiguration())
    api.AddBookmarksFile(f, "out.pdf", []pdfcpu.Bookmark{{Title: "测试", PageFrom: 1}}, pdfcpu.NewDefaultConfiguration())
    api.AddBookmarksFile(f, "out.pdf", []pdfcpu.Bookmark{{Title: "尾巴", PageFrom: 1}}, pdfcpu.NewDefaultConfiguration())


![image](https://user-images.githubusercontent.com/63705580/127323094-7e7d9b29-0a4e-46cb-b7da-4a60a1c1a58a.png)
  
![image](https://user-images.githubusercontent.com/63705580/127323287-eb350649-dbb4-4b22-91cb-fc6e5d74083e.png)
![image](https://user-images.githubusercontent.com/63705580/127323343-6bdb183a-05bc-4392-a991-2aba267a2b2a.png)
  

[SimSun Font.zip](https://github.com/pdfcpu/pdfcpu/files/6893032/SimSun.Font.zip)
[a919-2065308.pdf](https://github.com/pdfcpu/pdfcpu/files/6893039/a919-2065308.pdf)

**Comment by kaiceo** [comment]
func encodeUTF16String(s string) string {
	    rr := utf16.Encode([]rune(s))
	    bb := []byte{0xFE, 0xFF}
	    for _, r := range rr {
		    bb = append(bb, byte(r>>8), byte(r&0xFF))
	    }
	    return string(bb)
    }

@hhrutter  i am trying to learn how to encode chinese to utf-16be recently, but i dont understand  what mechanism is below code , at least it is different from some teaching i got to build a utf-16be, maybe limited my knowledge level.
 
     bb = append(bb, byte(r>>8), byte(r&0xFF))

your assistance may help me to resolve this issue as soon as possible, thks

**Comment by kaiceo** [comment]
func encodeUTF16String(s string) string {
          rr := utf16.Encode([]rune(s))
          bb := []byte{0xFE, 0xFF}
          for _, r := range rr {
	          bb = append(bb, byte(r>>8), byte(r&0xFF))
          }
          return string(bb)
      }

@hhrutter i am trying to learn how to encode chinese to utf-16be recently, but i dont understand what mechanism is below code , at least it is different from some teaching i got to build a utf-16be, maybe limited my knowledge level.

     bb = append(bb, byte(r>>8), byte(r&0xFF))
your assistance may help me to resolve this issue as soon as possible, thks

**Comment by kaiceo** [comment]
@hhrutter I found some differences about adding chinese bookmark by api and manual.
for example :  作

1. add bookmark by api , not displayed
![image](https://user-images.githubusercontent.com/63705580/128155544-ee64ba78-3a96-40c0-884f-f3d7f0576699.png)

2. add bookmark manually in acrobat pro, displayed normally

![image](https://user-images.githubusercontent.com/63705580/128156172-1e72ab7b-d185-425b-bfdc-608301f7c9fc.png)

![image](https://user-images.githubusercontent.com/63705580/128155872-12be13ec-57ad-4d36-b718-c0f620110ae8.png)

result is 2 has extra "5C", i dont know the reason

**Comment by hhrutter** [comment]
I think I know what is going here..
The string literal needs to be escaped before it is written out to the file.

**Comment by hhrutter** [comment]
This is fixed with latest commit.
Let me know if this works for you.
Thank you for using pdfcpu 💚

**Comment by kaiceo** [comment]
it runs very well.
