### ISSUE TITLE
Page Resizing

### ISSUE THREAD

**Issue by imrushi** [pdfcpu/pdfcpu#363]
Hi,
I want to write code to resize every page to A4 size using pdfcpu library. The pages inside pdf will be any size like A3,A2.... and I want to convert them to A4 without losing the data (Resize).

Or there is already a function for it in pdfcpu library?

**Comment by hhrutter** [comment]
Hi!
Resizing is not yet part of pdfcpu but it sounds like a useful feature.
What's your preferred approach to handling existing page orientation in the output PDF?

**Comment by imrushi** [comment]
So I have logic for handling existing page orientation
1. we have to Take input a pdf file
2. Then we have to iterate through each page and get each page Height and Width and check if it is Landscape or Portrait 
following sudo code for same
```
dims, err := api.PageDimsFile(file)
if err != nil {
	fmt.Print(err)
}
var temp []string
for j, page := range dims {
        // Checking if page is landscape if it is landscape add page no. to temp
	if page.ToMillimetres().Height < page.ToMillimetres().Width { 
		temp = append(temp, strconv.Itoa(j+1))
	}
}
// we will pass the landscape pages in rotate function and rotate to 90 Degree or -90 Degree for Portrait 
err = api.RotateFile(file, outfile, 90, temp, conf)
```

**Comment by hhrutter** [comment]
OK.
I see 3 variants for resizing and here the pdfcpu papersize constants including orientation prove useful:

For example:

1) "A4": resize to A4 and keeps the current page orientation - no rotation needed

2) "A4P": resize to A4 and enforce portrait mode - rotate where necessary
     "A4L": resize to A4 and enforce landscape mode - rotate where necessary

3) "A4P -keep": resize to A4 and enforce portrait mode - keep original content orientation
     "A4L -keep": resize to A4 and enforce landscape mode - keep original content orientation

With 2) being the popular variant most likely.

**Comment by imrushi** [comment]
I think option 2 will be a good choice. And how will you implement it...

**Comment by robert-zaremba** [comment]
bump, was is there any update for page resize feature?
