### ISSUE TITLE
date validation

### ISSUE THREAD

**Issue by nhannh23** [pdfcpu/pdfcpu#366]
Hi @hhrutter 
Thanks for the great tool. Please help me with this issue. 🙏 
I'm having a problem while validating one of my pdf files. When I run `pdfcpu validate file_name.pdf`, it produces like below
```bash
validating(mode=relaxed) file_name.pdf ...
validation error (obj#:6): pdfcpu: validateDateObject: <D:20210730163356+09'00'> invalid date
```

At first, I tested your code with this string `D:20210730163356+09'00'`, and the result was fine. There is no problem.
However, when I take a look at the error message in my terminal, it showed like this:
```
pdfcpu: validateDateObject: \u003cD:20210730163459+09'00'\u0000\u003e invalid date
```

In my understanding, `\u003c` represents `<`, and `\u003e` is `>`. In the log, there is an additional `\u0000` which is a Null Unicode character. I guess this is the cause, which breaks [this condition](https://github.com/pdfcpu/pdfcpu/blob/master/pkg/pdfcpu/date.go#L154).

Please take a look at this matter. I can provide you the sample file via Slack DM.
Thanks in advance.

**Comment by hhrutter** [comment]
Yes please go ahead and send me your file for analysis.

**Comment by nhannh23** [comment]
I sent you the file. Thanks for your investigation.

**Comment by hhrutter** [comment]
This is fixed with latest commit.

**Comment by nhannh23** [comment]
Awesome.
Thank you very much.
