### ISSUE TITLE
Optimize breaks some pages

### ISSUE THREAD

**Issue by maxiride** [pdfcpu/pdfcpu#369]
I've tried to optimize a 4440 pages and 300MB PDF file, the process took a couple of minutes but resulted in a corrupted PDF.

Some pages are blank, some are missing content and others have been resized to a blank square page.

I've tried to output the logging with -vv but it's a hundred of thousands of lines of log, how can I help debug more cleanly the issue?

I've also tried to trim the original document to extract only the pages that got corrupted and re-run the optimize process on the trimmed files, the result in this case was perfectly clean which I find rather odd. If the issue is within some pages I can't see why the optimize would work on them as trimmed but not with the whole document.

**Comment by hhrutter** [comment]
That issue is likely related to the specific page tree structure of your file.
If you can get me access to that file I can provide a fix - I am sorry there is really no other way.

**Comment by hhrutter** [comment]
This is a known bug (#357) related to writing out xref streamdicts for a large object set.
As a workaround reconfigure pdfcpu and turn off xref streams .
You have to edit your config.yml to set writeXrefStream: false like so:

```
Go-> pdfcpu ver -v
pdfcpu: v0.3.12 dev
config: /Users/horstrutter/Library/Application Support/pdfcpu/config.yml
Go-> cd "/Users/horstrutter/Library/Application Support/pdfcpu"
Go-> cat config.yml
#########################
# Default configuration #
#########################

reader15: true
decodeAllStreams: true

# validationMode:
# ValidationStrict,
# ValidationRelaxed,
# ValidationNone
validationMode: ValidationRelaxed

# eol for writing:
# EolLF
# EolCR
# EolCRLF
eol: EolLF

writeObjectStream: true
writeXRefStream: false
encryptUsingAES: true

# encryptKeyLength: max 256
encryptKeyLength: 256

# permissions for encrypted files:
# -3901 = 0xF0C3 (PermissionsNone)
#    -1 = 0xFFFF (PermissionsAll)
permissions: -3901

# displayUnit:
# points
# inches
# cm
# mm
unit: points
Go->
```

**Comment by maxiride** [comment]
Thank you very much for the quick reply! This issue also shed light on tweaks we can implement on the PDF generation process.

I suppose this issue can be closed as being a duplicate after all. Thanks again.

**Comment by hhrutter** [comment]
Please consider becoming a pdfcpu sponsor.
Sponsorship ensures this project does not go stale because of maintainer burnout over the long run.
Thank you for using pdfcpu 💚
