### ISSUE TITLE
api: stamping with user font

### ISSUE THREAD

**Issue by dongfangxu-dongfangxu** [pdfcpu/pdfcpu#370]
`wm, err := pdfcpu.ParseTextWatermarkDetails(text, "font:SimSun, points:48, col: 1 0 0, rot:45, sc:1 abs", onTop, pdfcpu.POINTS)
api.AddWatermarksFile(in, out, nil, wm, nil)`

I need to add text watermark to PDF，The configuration is not initialized when i create watermark detail，so the following code did not pass the verification ，my userfont does not contain Simsun and I can't add watermark for the first time，Unless I load the configuration in advance，like this 'pdfcpu.NewDefaultConfiguration()' ， Before I create watermark detail

`func IsUserFont(fontName string) bool {
	_, ok := UserFontMetrics[fontName]
	return ok
}`

**Comment by hhrutter** [comment]
In order to use a specific user font for stamping via the API the user font has to be installed.

There are two ways to do this:

1) Statically
You install your font via the CLI, for example: `pdfcpu font install simsun.ttf'

2) Dynamically:
Execute the following before your code for stamping:
```
api.LoadConfiguration()

if err := api.InstallFonts([]string{simsun.ttf}); err != nil {
    return err
}
```

Take a look at [fonts_test.go](https://github.com/pdfcpu/pdfcpu/blob/master/pkg/api/test/fonts_test.go)

**Comment by dongfangxu-dongfangxu** [comment]
Thank you for your reply

**Comment by SakuOtonashi** [comment]
可以尝试直接使用用户的字体
You can try to use the user's font directly
```golang
import (
	"github.com/adrg/sysfont"
	"github.com/pdfcpu/pdfcpu/pkg/api"
)

func loadChineseFont() (*sysfont.Font, error) {
	finder := sysfont.NewFinder(nil)
	font := finder.Match("simsun.ttc")
	err := api.InstallFonts([]string{font.Filename})
	if err != nil {
		return nil, err
	}
	return font, nil
}
```

**Comment by SoldierAb** [comment]
> 可以尝试直接使用用户的字体 You can try to use the user's font directly
> 
> ```go
> import (
> 	"github.com/adrg/sysfont"
> 	"github.com/pdfcpu/pdfcpu/pkg/api"
> )
> 
> func loadChineseFont() (*sysfont.Font, error) {
> 	finder := sysfont.NewFinder(nil)
> 	font := finder.Match("simsun.ttc")
> 	err := api.InstallFonts([]string{font.Filename})
> 	if err != nil {
> 		return nil, err
> 	}
> 	return font, nil
> }
> ```

with your code, still not working , api.InstallFonts throws error ` open : no such file or directory`
  
用了楼主的方式，不行，提示 ` open : no such file or directory`, 请问楼主解决了么？

**Comment by dongfangxu-dongfangxu** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年8月11日(星期四) 下午2:49
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [pdfcpu/pdfcpu] api: stamping with user font (#370)





  
可以尝试直接使用用户的字体 You can try to use the user's font directly
 import ( 	"github.com/adrg/sysfont" 	"github.com/pdfcpu/pdfcpu/pkg/api" ) func loadChineseFont() (*sysfont.Font, error) { 	finder := sysfont.NewFinder(nil) 	font := finder.Match("simsun.ttc") 	err := api.InstallFonts([]string{font.Filename}) 	if err != nil { 		return nil, err 	} 	return font, nil }
  
with your code, still not working , api.InstallFonts throws error  open : no such file or directory
 
用了楼主的方式，不行，提示  open : no such file or directory, 请问楼主解决了么？
