### ISSUE TITLE
maintaining bookmarks via JSON

### ISSUE THREAD

**Issue by cwmoss** [pdfcpu/pdfcpu#374]
pdfcpu supports annotations, properties and keywords but not bookmarks. it would be great if reading and inserting/deleting of bookmarks would be supported.

use case:
A\ update bookmarks after some merge
B\ use (technical) bookmarks on pdf creation to mark pages. use these marks to find pagenumbers. insert other PDFs. remove the these bookmarks after the merge

**Comment by cwmoss** [comment]
I am a CLI user.

maybe bookmark import/export is then a better solution. as I understand it, a bookmark consists of title, level and pagenumber. export could produce something like a json file, one could do all the modifications and then import could completely override and replace the existing bookmark structure.

BTW: a `-format json` for list and info commands could be an awesome addition.

**Comment by hhrutter** [comment]
json-ifying all non trivial command input is one way - agreed - but I am still not sold on that.
It might overwhelm the majority of the pdfcpu userbase and right now my focus is adoption.

I'd rather extend the API but editing bookmarks per se is not a trivial task.
A bookmark's destination (which really is an outlineItem dict) may be any location on any page and may be using a zoom level
.. and even more like the PDF spec will tell you.

**Comment by afparsons** [comment]
> BTW the pdfcpu merge facility does not preserve bookmarks right now.

@hhrutter: is this on the roadmap? Should I file a formal feature request? I would love to be able to maintain the bookmarks in my PDFs when merging them into one file.

**Comment by hhrutter** [comment]
Fixed => https://github.com/pdfcpu/pdfcpu/releases/tag/v0.5.0
