### ISSUE TITLE
err: interrupted system call

### ISSUE THREAD

**Issue by maxiride** [pdfcpu/pdfcpu#375]
I'm applying an image stamp on several thousand PDF.

The process is basically a for loop iterating over a slice of filepaths and calling the applicaTesto() function which is a barebone wrapping of the pdfcpu.AddTextWatermarksFile() method.

On some files the following error is returned:
`interrupted system call`

On subsequent runs the error is returned for different files, a possible indication that the issue isn't file realated.

```
// applicaTesto applica del testo al PDF
func (j *Job) applicaTesto(inFile, text, conf string) error {
	err := pdfcpu.AddTextWatermarksFile(inFile, outFile, []string{"1"}, true, text, conf, imponi.PdfConf)
	if err != nil {
		return  err
	}
	return nil
}
```

OS: Ubuntu 20.04
pdfcpu configuration used:
```
var PdfConf *pdfcpuc.Configuration

func init() {
	PdfConf = pdfcpuc.NewDefaultConfiguration()
	PdfConf.Unit = pdfcpuc.MILLIMETRES
	PdfConf.WriteXRefStream = false // Necessario per compatibilità file enormi https://github.com/pdfcpu/pdfcpu/issues/369
}
```

**Comment by hhrutter** [comment]
Hi there!

Hunting this down may be tricky.
Please do me a favour and see if you can reproduce it in the following order: 
* a different machine with your Ubuntu configuration
* a different machine running a different Linux 
* under Win
* under MacOS

In any case I will need to see a detailed output the error message you are getting.

**Comment by maxiride** [comment]
I've done intensive testing which I will summarize later, the TL;DR version is that SAMBA\SMB most likely can't handle too much i\o, feedback is welcome on this conclusion.

---

Without going into too many details I'll try to summarize the relevant aspects.

- The application was run in a docker container (ubuntu 20.04 image) on a bare metal VMWare host physically connected to a QNAP (through two Gigabit ethernet) which acts as the storage drives for the VMs. and containers run on the VMWare node.

- The application performed i\o on a SMB\SAMBA file server exposed by on another VMs (on the same VMWare instance and QNAP).

 - The processing power and the bandwidth have been excluded as suspects as they didn't even get close to capacity.
 - The host\container etc have also been excluded as suspects, I've tried to spin up the application on different container images, on the bare metal machine and different operating systems.
 - During the previous trials the application performed perfectly only when run directly in the same VMs that exposed the file server.

Even thought in every case there is always a neglectable network traversing from the VMs that perform the processing and the storage array (which are on the same cabinet though) the only real difference between the attempts has been that from the perspective of the application it did i\o on a SMB share vs on the disk itself (even thought the disk is anyway remote on the QNAP).

---

# Workaround implemented

For the purpose of getting things going the application has been rewritten to copy the file to process in a local temporary folder (inside the container where it runs), perform the manipulation with pdfcpu (so that "from its POV is doing i\o on its storage) and then copy it back to the destination path.

This approach means that for any given file to process the network is traversed two times
1. to copy over the file
2. to copy it back once ready

## Performance aspects

The issue happened when processing thousands of files, the new implementation while adding a bit of overhead to the process didn't affect at all the total processing time.

----

My conclusion is that **this isn't a pdfcpu issue** but an implementation issue and the ticket can be closed but I'm happy to share more technical details if's needed.

**Comment by hhrutter** [comment]
Thanks for the thorough investigation!
Definitely 👍   the outcome.
