### ISSUE TITLE
extract: repeatedly extracted pages are not identical / result in different checksums

### ISSUE THREAD

**Issue by Kampii** [pdfcpu/pdfcpu#378]
I used [this demo](https://wcchoi.github.io/go-wasm-pdfcpu/)  which automatically downloads the first page. I did it five times and checked the hash with `echo -n first_page.pdf | shasum` , and it was different every time:

8d00891653646c48229d326608fb00b0e35a3ce5
448114d698d386c3fa4d4300b2f835351d8dd8a0
7218a4a3954bf6617efd89836d395897c1576d54
886a1d89d5f86c90df96e16d8b096a11b2be362f
72f4caf594484f01438d02449abff7e73656f9a2

I was expecting to get the same hash every time. Is this a bug or I am missing some settings? Please kindly advise.

**Comment by hhrutter** [comment]
Without looking at this - some content in the extracted PDF may be the result of iterating over a map.
Iterating over Go maps produces random iteration sequences.

**Comment by Kampii** [comment]
I am not quite sure what that means, but is it something that can be fixed somehow?

**Comment by Kampii** [comment]
Well that is the core for one of our features which basically does not allow user to upload duplicate pages regardless of what the file name is or how many pages are there in a file. This is the reason why we split the pdf into separate pages and get the hash sum of each page and verify if user already has it.

**Comment by hhrutter** [comment]
ok. I need to check this.

**Comment by hhrutter** [comment]
That's not gonna work out for a couple of reasons.
pdfcpu inserts creation and modification dates and the order in which objects are written to disk is indeterministic as there are various loops ranging over maps - this concerns eg. all dictionaries.

**Comment by Kampii** [comment]
Understood. Thank you for looking into this. Have a great rest of the week!
