### ISSUE TITLE
api: error handling

### ISSUE THREAD

**Issue by shun-tak** [pdfcpu/pdfcpu#379]
### Issue
It is hard for pdfcpu users to handle errors because pdfcpu api always returns `errors.Errorf`.

e.g. https://github.com/pdfcpu/pdfcpu/blob/befba81f91eed5ce28d9f09db9adf98e47ffc696/pkg/pdfcpu/validate/objects.go#L193

### One idea to resolve this
Define error types and return them.
API users can handle errors like this:
```
lines, err := pdfcpuApi.Info(file, []string{"-5"}, nil)
if err != nil {
	if errors.Is(err, pdfcpu.NamedError) {
		doSomething()
		return
	}

	doSomething2()
}
```

I would be grateful if developers understand this idea.

**Comment by shun-tak** [comment]
Thanks hhrutter!
I don't think errors are always caused by bugs. When pdfcpu is used in a service that is a business application, customers of the service upload all kinds of pdf files.

I personally think the following errors are likely to happen:
- PDF 2.0 encryption not supported
- please provide the correct password

If the service developers (pdfcpu users) could get the error type, they would handle the errors and noticed the customers how to fix errors.

**Comment by hhrutter** [comment]
Agreed for these situations it makes sense for the caller to be able to handle a specific error.
I will start to return sentinel errors for the two cases you mentioned.

**Comment by shun-tak** [comment]
Great! Thanks!

**Comment by hhrutter** [comment]
This is fixed with latest commit.

Thank you for using pdfcpu 💚
