### ISSUE TITLE
unable to extract images from a pdf where BitPerComponent is not 8

### ISSUE THREAD

**Issue by mrg0lden** [pdfcpu/pdfcpu#380]
Hi, I've encountered this error:

https://github.com/pdfcpu/pdfcpu/blob/f99879e05a77296a55075b3a684f399a52c400c4/pkg/filter/flateDecode.go#L239

I'm trying to extract images from a PDF file where one of the images has a `bpc` of 1. I'm willing to implement the solution for my use-case, but I'll have to understand how the image is encoded if possible.

**Comment by hhrutter** [comment]
Thanks for reporting this. 
If you can share a sample then we can implement this - that would be the easiest way.

**Comment by mrg0lden** [comment]
I wish I can, but the only files I have can't be shared. For the time-being I'll implement the functionality in a fork. I'll happily share an example if I can make one, then make a PR to merge the changes with the mainstream repo. The fork will be open source regardless, so feel free to play around with it (when it happens 🌚).

**Comment by hhrutter** [comment]
OK. Can you at least post the output of `pdfcpu images list your.pdf`
Thanks!

**Comment by mrg0lden** [comment]
I'm sorry I didn't notice your response, here's the output:
```
page  obj#  id  type width height colorspace comp bpc interp   size filters
===========================================================================
   1   251  I1 image   411    411    Indexed    3   1          4 KB FlateDecode
   2     4 Im0 image   850   1170  DeviceRGB    3   8         83 KB DCTDecode
   3     8 Im0 image   850   1170  DeviceRGB    3   8        108 KB DCTDecode
   4    12 Im0 image   850   1170  DeviceRGB    3   8        143 KB DCTDecode
```

**Comment by hhrutter** [comment]
1 bit per component, 3 components and Indexed.. Sounds interesting.
If I had access to those flate encoded 4 KB I could implement this but 
there will be no extension to the image decoding part without any test going along with it.

**Comment by mrg0lden** [comment]
[test.pdf](https://github.com/pdfcpu/pdfcpu/files/7228449/test.pdf)

This file is similar, but doesn't have the same color space. I managed to make the image using Photoshop, but I don't have a subscription for Acrobat DC, so I made this one with MS Word. I tried to share the bmp file as is but GitHub refused it, so I'll share it as a .txt file.
[untitled.txt](https://github.com/pdfcpu/pdfcpu/files/7228463/untitled.txt)

If you have access to Acrobat, you probably can make a file that resembles the encoding above.
That's all I can do for now in terms of testing material. I hope that helps, and thank you for your efforts with the project as a whole, and this issue in particular.

Regards

**Comment by mrg0lden** [comment]
It might be a dumb question, but what's this `7` for?
https://github.com/pdfcpu/pdfcpu/blob/f99879e05a77296a55075b3a684f399a52c400c4/pkg/filter/flateDecode.go#L278

**Comment by hhrutter** [comment]
bytesPerPixel := (bpc*colors + 7) / 8

This is the general way to ensure you don't miss the last byte.
eg. for bpc=1 colors=3 you would end up with bytesPerPixel = 0

‪On Sat, Sep 25, 2021 at 2:36 AM ‫محمّد‬‎ ***@***.***> wrote:‬

**Comment by mrg0lden** [comment]
Hey, I managed to make this PDF file by hand to make it similar. However, Adobe Reader won't open it, but Chrome does open it. IDK what needs to be fixed. I guess you can inspect it with a hex editor.
When I tried to inspect it with pdfcpu I got this error
```dereferenceObject: problem dereferencing object 8: pdfcpu: ParseObjectAttributes: can't find generation number```
[Untitled-1.pdf](https://github.com/pdfcpu/pdfcpu/files/7272323/Untitled-1.pdf)

**Comment by petervwyatt** [comment]
There are a lot of issues with your hand-coded attempt for an XRefStm - it is highly invalid. Don't even consider what Chrome does as a remote indication of a valid PDF file (https://twitter.com/angealbertini/status/939555534625177602?s=20):

* /Index [7 7] --> "The first integer shall be the first object number in the subsection; the second integer shall be the number of entries in the subsection". You have objects with object numbers that are both less than 7 and greater than 14. Thus your /Size entry is also incorrect

* /Prev 7704 --> this file offset lands in the middle of XMP data stream so it is incorrect. Most likely you mean 10164 for this specific file (until you edit it, in which case that value will shift)

* /W [1 2 0] --> "The sum of the items shall be the total length of each entry; it can be used with the Index array to determine the starting position of each subsection." So each entry in your XRefStm should be 3 bytes yet your deFLATEd data stream is 28 bytes long which is (a) not a multiple of 3 and (b) doesn't match with what /Index suggests. And when I hex dump the deFLATEd data it makes no sense according to Table 18 "Entries in a cross-reference stream".

**Comment by hhrutter** [comment]
Your original `test.pdf` is a real bitmap, but also throws some error.
I can fix this but your original issue is different and concerns the `Indexed Colorspace`.

```
Go-> pdfcpu ima li test.pdf
pages: all
1 images available
page  obj#      id  type width height colorspace comp bpc interp size filters
=============================================================================
   1    12 Image12 image  1890   1417 DeviceGray    1   1        5 KB FlateDecode
Go->
```

The  `Untitled.pdf` is corrupt I have to agree on that.

**Comment by hhrutter** [comment]
Extracting the image out of your test.pdf works fine.

What I would need in order to reproduce and fix the error reported originally on the top is an image object using a `Predictor`.
This does not show up in the output of `pdfcpu images list` but you can first use this command to identify the object number and then check the concrete image dict in the output of `pdfcpu val -v test.pdf`.

**Comment by mrg0lden** [comment]
I'll try to comeback to this issue soon. 

I'm new to dealing with PDFs. All the PDFs I uploaded above were made using either MS Word or Adobe Acrobat then edited by hand. I just learned about the reference tables and all of this stuff. I'm going to come back to this issue with a proper PDF file and an initial implementation once I get some time. Thank you for your care.

**Comment by hhrutter** [comment]
This is fixed with the latest commit!
Thanks everybody for their input 👍

**Comment by mrg0lden** [comment]
Sorry for the late response. I'm now getting an "unexpected EOF" error when I try to extract images. I tried all of the `pkg/api` functions and also the CLI, but I stil get the same error. I tried `pdfcpu validate -vv filename.pdf` and got `validation ok`

I'd like to share the file with you but I cannot share it on public. Here's a Google Drive link shared with your gmail email address: https://drive.google.com/file/d/1XBXA5WuifgLrlg9HtAMUbsrYCNlTYpKo/view?usp=sharing

**Comment by hhrutter** [comment]
Thanks for reporting this.
I'll check it out.

**Comment by hhrutter** [comment]
This is fixed with the latest commit!

**Comment by mrg0lden** [comment]
I can confirm that it is! Thank you!

**Comment by hhrutter** [comment]
Thanks so much for your contribution!
Very much appreciated 💚
