### ISSUE TITLE
[Discussion] Merge: open\close files as they are appended instead of opening them all at once.

### ISSUE THREAD

**Issue by maxiride** [pdfcpu/pdfcpu#382]
To merge 10.000 files in groups of 1000 files, 10 merged files I initially did it synchronously by calling `.MergeCreateFile` on the first group of 1k files, then the second one and so on.

pdfcpu is blazing fast but I wanted to squeeze more juice out of it, so I tried to wrap everything in a goroutine. 10 goroutines are launched each with its own group of files to merge and here things got complicated.

The error "too many open files" started to popup which led me to discover that each OS has a limit on the number of simultaneously opened files at any given time. By reading the internals I noticed that pdfcpu does indeed open all the files to be merged beforehand and then proceeds to the merge, the files are  then closed in a deferred function.

https://github.com/pdfcpu/pdfcpu/blob/8837dd1ee074da887e13d5f962d7617bc4b0799a/pkg/api/merge.go#L93

I didn't dig in much more than this but I'd like to understand if there might be room for improvement by opening and closing files to be appended as they are appended to the new file instead of opening them all at once and then closing them. Or if instead is in the author design to leave to the caller the responsibility of handling such situations.

---
OS: Ubuntu 20.04 docker image
Default ulimit -n: 1024 (max file handles, max simultaneously open files) which can be raised safely to 10k and more in containerized environments.

---
Edit

I am aware that pdfcpu provides the underlying Merge which uses a io read seeker and a writer to build my own implementation of a merge process. I'm just wondering saying that this event might or might not open grounds of improvement.

**Comment by hhrutter** [comment]
I hope you aware you are navigating dangerous waters with your usecase.
Whenever creating really large PDFs you have to watch out for all kinds of overflow issues at least 
regarding the internal representation of object numbers.

Other than that pdfcpu follows the convention for tool providers not getting into goroutine/channel land
leaving the execution model up to the user.

Yet I am going to investigate if pdfcpu gets in the way in such cases.

**Comment by hhrutter** [comment]
Closed due to inactivity.
