### ISSUE TITLE
stamp/watermark: `position`

### ISSUE THREAD

**Issue by christian-heusel** [pdfcpu/pdfcpu#383]
Dear `pdfcpu` contributors, at first let me thank you for this awesome tool and all the work you put into it ❤️ 

I recently noticed, that the `aligntext` (as described [here](https://pdfcpu.io/core/watermark.html)) option does not change anything for me.
I intially noticed the issue using the golang api, but here is the minimum example with just the commandline tool:

```
pdfcpu watermark add -mode text -- "Christian" "align: l, rot: 0.0" in.pdf out.pdf
pdfcpu watermark add -mode text -- "Christian" "align: c, rot: 0.0" in.pdf out.pdf
pdfcpu watermark add -mode text -- "Christian" "align: r, rot: 0.0" in.pdf out.pdf
```

These all produce the same output for me. 🤔

**Comment by hhrutter** [comment]
This makes sense for single line watermarks.

Try this: 
```pdfcpu watermark add -mode text -- "Christian\nline 2" "align: l, rot: 0" in.pdf out.pdf```

although what you really want I believe is:
```pdfcpu stamp add -mode text -- "Christian\nline 2" "align: l, rot: 0" in.pdf out.pdf```

**Comment by christian-heusel** [comment]
Ah thanks for the hint, I guess that the reported issue now just turns into a question because I seemingly misunderstood what the option is doing ... 

What I am looking for is an option to align a Mark/Stamp on the left side of a page with a small margin, but so far I always had to use some offsets that break with varying text length .. :(
`pdfcpu stamp add -mode text -- "Christian Heusel" "marg: 0, pos: l,  marg: 0, rot: -90" Test.pdf out.pdf`
![image](https://user-images.githubusercontent.com/26827864/134660476-11d751b1-dade-467f-8ad0-75b8114eb3b1.png)

How do I really get this to the left side of the page?

**Comment by hhrutter** [comment]
This may be an issue with the transform matrix. Needs to be looked at.
Meanwhile as a workaround use some negative x offset like `off: -30 0`
and make sure you check out the samples [here](https://github.com/pdfcpu/pdfcpu/tree/master/pkg/samples/stamp/text).

**Comment by hhrutter** [comment]
This is fixed with the latest release.

**Comment by christian-heusel** [comment]
Already applied the fix in our software, thanks for fixing! 👍🏻 🥰
