### ISSUE TITLE
Some files output errors

### ISSUE THREAD

**Issue by shun-tak** [pdfcpu/pdfcpu#384]
Hi! Thanks for developing this great library!

I got several errors following:

```
1.pdf
dict=fdDict entry=Lang: unsupported in version 1.4
This file could be PDF/A compliant but pdfcpu only supports versions <= PDF V1.7

2.pdf
pdfcpu: validateAcroForm: missing required entry "Fields"

3.pdf
pdfcpu: validateColorSpaceArray: undefined color space: DeviceRGB

5.pdf
pdfcpu: validateDateObject: <2021/09/07 12:29:38> invalid date

6.pdf
pdfcpu: array element 0 not a number (Float/Integer

7.pdf
pdfcpu: PDF 2.0 encryption not supported
```

I think it is difficult to handle errors without files.
I would like to share these files directory with developers. Is it possible?

**Comment by hhrutter** [comment]
Thank you for reporting these.
if you can share the files please open new issues accordingly for each.
We have to treat all of them separately and will provide fixes where possible after thorough analysis.
This will help improve pdfcpu a lot.

**Comment by shun-tak** [comment]
Thank you very much! I'll make issues for each!
