### ISSUE TITLE
optimize content streams

### ISSUE THREAD

**Issue by maxiride** [pdfcpu/pdfcpu#385]
I've been using pdfcpu optimize for a while now with very successful results, recently it has been brought to my attention from a fellow peer another software called cpdfsqueeze (source and binares linked below), I'm not making an issue to bring attention to cpdfsqueeze but rather only because its source is available thus allowing for potential learnign and a pdfcpu improvement.

cpdfsqueeze managed to compress a 280MB PDF down to 19MB while pdfcpu (with or without the xrefstream option set to true\false) compressed it to 153MB and 156MB respectively.

From a purely side by side comparison the PDF produced are identical (given that they are all meant for printing so forms and other content is not important), however, due to a very low knowledge of the PDF internals I can't really tell what has been done.

In the event that the contributors will find the source code resourceful and "clean" on the PDF manipulation I am willingly to put a bounty to improve the optimization process.

---
cpdfqueeze
Source: https://github.com/johnwhitington/cpdfsqueeze
Binaries: https://github.com/coherentgraphics/cpdfsqueeze-binaries

Due to the troubles of producing large enough PDFs I've sent demo production files via email.

**Comment by hhrutter** [comment]
Checking for duplicate content streams is something I noticed cpdfsqeeze is doing and pdfcpu not doing right now. 
I am further investigating this.

**Comment by hhrutter** [comment]
Optimization takes care now of redundant content streams and forms.
