### ISSUE TITLE
pdf produced by Adobe Sign not parseable by pdfcpu

### ISSUE THREAD

**Issue by dlq84** [pdfcpu/pdfcpu#389]
Hello. I ran into an issue with processing pdfs produced by Adobe Sign. I'm not sure if the problem is with pdfcpu or if Adobe Sign produces bad pdfs. I also get the same error with https://github.com/signintech/pdft.

The error I'm getting from pdfcpu is:

```
> pdfcpu validate adobe_sign_test_optimized_encrypted_.pdf                                           1
validating(mode=relaxed) adobe_sign_test_optimized_encrypted_.pdf ...
dereferenceObject: problem dereferencing object 27: pdfcpu: decryptAESBytes: Ciphertext not a multiple of block size
```

Attached is the original PDF that I've ran through pdfcpu optimize and the signed copy of it produced by Adobe Sign. And the crash.log

[adobe_sign_test_optimized_encrypted_.pdf](https://github.com/pdfcpu/pdfcpu/files/7460545/adobe_sign_test_optimized_encrypted_.pdf)
[adobe_sign_test_optimized.pdf](https://github.com/pdfcpu/pdfcpu/files/7460546/adobe_sign_test_optimized.pdf)
[crash.log](https://github.com/pdfcpu/pdfcpu/files/7460563/crash.log)

Thanks for an awesome library and tool

**Comment by hhrutter** [comment]
Thanks for reporting this!
I will check it out.
Thanks for using pdfcpu 💚

**Comment by dlq84** [comment]
That's great, I appreciate it. I might find some time this weekend to investigate as well, if I do I'll post my findings here.

**Comment by dlq84** [comment]
Hello. I've done some digging. Just as expected this is related to digital signatures. It fails trying to decrypt the digital signature digest content which is defined by the PDF32000_2008.pdf standards document on page 468.

```
Key: Contents

Type: byte string

Value: (Required) The signature value. When ByteRange is present, the
value shall be a hexadecimal string (see 7.3.4.3, “Hexadecimal
Strings”) representing the value of the byte range digest.
For public-key signatures, Contents should be either a DER-encoded
PKCS#1 binary data object or a DER-encoded PKCS#7 binary data
object.
Space for the Contents value must be allocated before the message
digest is computed. (See 7.3.4, “String Objects“)
```

**Correct me if I'm wrong here, you know the code and most likely PDF internals much better than me.**

It seems to me that digital signature Content should never be sent to the `decryptAESBytes()` in the first place? Since it's defined as a DER encoded PKCS#1 or PKCS#7 and is therefor not simply AES?

I hope this makes sense.

**Comment by hhrutter** [comment]
Thanks for your input! 👍 
Right now I am busy but this is in the pipeline and will be taken care of.

**Comment by hhrutter** [comment]
Hello!

Sorry for the delay.
Did you manually encrypt this file and then add the signature?
Can you layout your exact workflow flow please?
