### ISSUE TITLE
Feature Request: Remove Blank Pages

### ISSUE THREAD

**Issue by elucidsoft** [pdfcpu/pdfcpu#390]
Can we get a command to remove blank pages?

**Comment by hhrutter** [comment]
Hi there!

In order to address this we'd have to come up with a definition for a "blank" page..

In any case there is: `pdfcpu pages remove -p(ages) selectedPages  inFile [outFile]` at your disposal.

**Comment by elucidsoft** [comment]
Yes, that is the difficult part.  I think passing in some kind of argument for amount of text on the page?  For example, if there are fewer than 100 characters, consider it empty and remove it?  I am not sure, but the issue we face is that the last page will often be empty with just a small empty box there, so it could be safely removed.  Determining however, if there is useful content on that page would be key.

**Comment by hhrutter** [comment]
You can even have invisible content for some reason.
I don't think pdfcpu is in a position to reason about things like that.

Could you share a sample? 
Just for a better analysis of the problem domain in question.

Thank you for supporting pdfcpu 💚

**Comment by elucidsoft** [comment]
I see, that is understandable.  I will work on finding a separate solution for my customers who are having this issue.
