### ISSUE TITLE
Performance issue while extracting image

### ISSUE THREAD

**Issue by renard** [pdfcpu/pdfcpu#391]
I faced performance issues from commit 49c75a6 while extracting images from a PDF file.

In #329 I reported issues with images having multiple filters and this issue was fixed in 49c75a6 letting me assume this is related to how images are processed.

I made a small piece of code to check the performance (quite same as #353) (see below). There is about 2 orders of magnitude of time processing between 5b54825 and 49c75a6, and same goes with memory consumption:

with 5b54825:
```
PDF: Read 90 pages
Alloc = 54 MiB	TotalAlloc = 58 MiB	Sys = 71 MiB	NumGC = 5

real	0m0.811s
user	0m0.625s
sys	0m0.502s
```

with 49c75a6:

```
PDF: Read 90 pages
Alloc = 1845 MiB	TotalAlloc = 6950 MiB	Sys = 1992 MiB	NumGC = 25

real	0m55.790s
user	0m54.706s
sys	0m1.259s
```

The tested PDF is as 90-page 50Mb PDF file. With all tested PDF files having images I have the exact same issue.

If the problem is related to how images with multiple filter are processed, I would suggest to add an option to bypass that part because the majority of PDF files do not have multiple filters images.

If I can find some time, I will look deeper.

The code used to test is:

```go
package main

import (
	"fmt"
	"os"
	"runtime"

	pdfapi "github.com/pdfcpu/pdfcpu/pkg/api"
	"github.com/pdfcpu/pdfcpu/pkg/pdfcpu"
)

func PrintMemUsage() {
        var m runtime.MemStats
        runtime.ReadMemStats(&m)
        // For info on each, see: https://golang.org/pkg/runtime/#MemStats
        fmt.Printf("Alloc = %v MiB", bToMb(m.Alloc))
        fmt.Printf("\tTotalAlloc = %v MiB", bToMb(m.TotalAlloc))
        fmt.Printf("\tSys = %v MiB", bToMb(m.Sys))
        fmt.Printf("\tNumGC = %v\n", m.NumGC)
}

func bToMb(b uint64) uint64 {
        return b / 1024 / 1024
}


func readPDF(file string) (err error) {
	f, err := os.Open(file)
	if err != nil {
		return err
	}
	defer f.Close()

	// fmt.Printf("PDF: Opening %s\n", f)
	// err = pdfapi.ExtractImages(f, nil, PrintImg, nil)

	// if err != nil {
	// 	fmt.Printf("PDF: %s\n", err)
	// 	return
	// }
	pages, err := pdfapi.ExtractImagesRaw(f, nil, nil)
	for _, page := range pages {
		// Pre v0.3.12
		fn := fmt.Sprintf("%.5d.%s", page.PageNr, page.Type)
		// Post v0.3.12
		// fn := fmt.Sprintf("%s.%s", page.Name, page.FileType)
		fmt.Printf("Adding %s\n", fn)
	}
	fmt.Printf("PDF: Read %d pages\n", len(pages))
	return
}

func PrintImg(img pdfcpu.Image, singleImgPerPage bool, maxPageDigits int) error {
	fmt.Printf("s:%s, d:%d, %#v\n", singleImgPerPage, maxPageDigits, img)
	return nil

}

func main() {
	fmt.Printf("ARGS: %#v\n", os.Args)
	err := readPDF(os.Args[1])
	if err != nil {
		fmt.Printf("Error: %s\n", err)
		panic(err)
	}
       PrintMemUsage()
}
```

**Comment by hhrutter** [comment]
Allright, this goes into the pipeline.
Thank you for reporting this.

**Comment by hhrutter** [comment]
Please try using `api.ExtractImages` which serves as a replacement for `ExtractImagesRaw` which is still there for backwards compatibility and will be phased out.

**Comment by renard** [comment]
I did with the code I provided above but adapting:

```golang
	 fmt.Printf("PDF: Opening %s\n", f)
	 err = pdfapi.ExtractImages(f, nil, PrintImg, nil)

	 if err != nil {
	 	fmt.Printf("PDF: %s\n", err)
	 	return
	 }
	// pages, err := pdfapi.ExtractImagesRaw(f, nil, nil)
	// for _, page := range pages {
	// 	// Pre v0.3.12
	//	fn := fmt.Sprintf("%.5d.%s", page.PageNr, page.Type)
	//	// Post v0.3.12
	//	// fn := fmt.Sprintf("%s.%s", page.Name, page.FileType)
	//	fmt.Printf("Adding %s\n", fn)
	// }
	//fmt.Printf("PDF: Read %d pages\n", len(pages))
```


`api.ExtractImages` does not change anything even with latest commit.

**Comment by hhrutter** [comment]
I will further investigate into this.

**Comment by ungerik** [comment]
This is an unnecessary slice allocation per pixel:
https://github.com/pdfcpu/pdfcpu/blob/d624641f2fb5ae4b56afdb638bff67abd5c2b0d8/pkg/pdfcpu/writeImage.go#L284

**Comment by hhrutter** [comment]
The extraction of DTC encoded streams has been optimized.
The only scenario where we do a (JPG) decoding is for CMYK based images - these get rendered as PNG.
All other DTC streams will be written as JPG.
