### ISSUE TITLE
split: failing optimization

### ISSUE THREAD

**Issue by lukaskund** [pdfcpu/pdfcpu#394]
Hey, 

Getting `pdfcpu: page 57: missing required XObject: Im0` during the split. File is openable / viewable in readers and can be splitted using poppler-utils `pdfseparate` command. As I understand things like this should be handled by relaxed validation? Let me know if I can help with anything.

File: https://easyupload.io/oo21mw

**Comment by hhrutter** [comment]
Great catch!
Thank you for reporting this!

**Comment by hhrutter** [comment]
This file has corrupt page content referring do undefined XObject Im0.
