### ISSUE TITLE
about merge files bookmarks

### ISSUE THREAD

**Issue by tongdaren** [pdfcpu/pdfcpu#395]
Hi, first of all, thanks to the author for providing such a great software. I would like to have a little idea about the pdf merge function, merge the pdf inside the source file with a bookmark inside the source file, the source file does not have a bookmark when you can use the source file name set as a bookmark before merging.

**Comment by hhrutter** [comment]
I am really sorry but I do not understand your feature request!

**Comment by hhrutter** [comment]
Closed due to inactivity.
