### ISSUE TITLE
Remove the extension check for .pdf

### ISSUE THREAD

**Issue by elucidsoft** [pdfcpu/pdfcpu#396]
Hi,

The extension check for .pdf is not necessary. In our backend code we don't use extensions at all, and our current process to use this tool is to rename the files, run it, and rename them back which is a bit of a burden so we can pass the check for the extension.  Can this be removed or a flag added to ignore it?

**Comment by hhrutter** [comment]
Hi!

Are you referring to a specific pdfcpu command or the api?

**Comment by elucidsoft** [comment]
It seems most commands require the file to end with the .pdf extension, otherwise it will throw an exception

**Comment by hhrutter** [comment]
Would it help to bypass the file extension check for infiles only?

**Comment by hhrutter** [comment]
There is the `checkFileNameExt` flag in the config file letting you disable the extension check for cmd inFiles.

You have to regenerate your config file for this:
1) The new `pdfcpu config` cmd prints out your config file path and its content. Backup config.yml!
2) Remove config.yml
3) Any cmd will ensure  configfile (at the default) location. This also applies to `pdfcpu config` :)
4) Restore your personal settings and any additional patches you might need like: `checkFileNameExt: false`
5) You're all set!

**Comment by elucidsoft** [comment]
Awesome, thank you!
