### ISSUE TITLE
panic in validate (validatePagesDict - Fatal: unexpected panic attack: runtime error: invalid memory address or nil pointer dereference)

### ISSUE THREAD

**Issue by hochhaus** [pdfcpu/pdfcpu#400]
Following up on #399, the second class of panics was found in three documents.

Attached, please find the output from the following commands:

```
./pdfcpu validate -v doc2.pdf &> doc2-crash-v.log
./pdfcpu validate -vv doc2.pdf &> doc2-crash-vv.log
./pdfcpu validate -v doc3.pdf &> doc3-crash-v.log
./pdfcpu validate -vv doc3.pdf &> doc3-crash-vv.log
./pdfcpu validate -v doc4.pdf &> doc4-crash-v.log
./pdfcpu validate -vv doc4.pdf &> doc4-crash-vv.log
```
[doc2-crash-v.log](https://github.com/pdfcpu/pdfcpu/files/7654557/doc2-crash-v.log)
[doc2-crash-vv.log](https://github.com/pdfcpu/pdfcpu/files/7654558/doc2-crash-vv.log)
[doc3-crash-v.log](https://github.com/pdfcpu/pdfcpu/files/7654559/doc3-crash-v.log)
[doc3-crash-vv.log](https://github.com/pdfcpu/pdfcpu/files/7654560/doc3-crash-vv.log)
[doc4-crash-v.log](https://github.com/pdfcpu/pdfcpu/files/7654561/doc4-crash-v.log)
[doc4-crash-vv.log](https://github.com/pdfcpu/pdfcpu/files/7654562/doc4-crash-vv.log)

These PDFs display correctly in PDF.js, pdfium and evince.

**Comment by hochhaus** [comment]
Using the [stressful PDF corpus](https://www.pdfa.org/a-new-stressful-pdf-corpus/) I found the following files which appear to trigger this case (and are also public):

* https://corpora.tika.apache.org/base/docs/bug_trackers/sumatrapdf/sumatrapdf-448-0.pdf
* https://corpora.tika.apache.org/base/docs/bug_trackers/pdf.js/pdf.js-7496-0.pdf
* https://corpora.tika.apache.org/base/docs/bug_trackers/poppler-gitlab/poppler-584-0.pdf
* https://corpora.tika.apache.org/base/docs/bug_trackers/poppler/poppler-22493-0.pdf
* https://corpora.tika.apache.org/base/docs/bug_trackers/poppler/poppler-22493-1.pdf

**Comment by hhrutter** [comment]
pdfcpu can handle these 5 files now.
Please get the latest & greatest and let me know if the issue with doc3 and doc4 persists.

Thanks for being sponsor 💚 👍

**Comment by hochhaus** [comment]
Thanks. I reran against doc2.pdf, doc3.pdf and doc4.pdf. Unfortunately, my private docs might be different cases since doc2.pdf and doc4.pdf still panic while doc3.pdf just errors.

I'm attaching updated output in case the improved logging is helpful to you. From my side resolution is low priority since I have a work around.

```
$ ./pdfcpu validate -vv doc2.pdf &> doc2-crash-vv.log
$ ./pdfcpu validate -vv doc3.pdf &> doc3-crash-vv.log
$ ./pdfcpu validate -vv doc4.pdf &> doc4-crash-vv.log
```

[doc2-crash-vv.log](https://github.com/pdfcpu/pdfcpu/files/7699944/doc2-crash-vv.log)
[doc3-crash-vv.log](https://github.com/pdfcpu/pdfcpu/files/7699945/doc3-crash-vv.log)
[doc4-crash-vv.log](https://github.com/pdfcpu/pdfcpu/files/7699946/doc4-crash-vv.log)
