### ISSUE TITLE
validate: date spec violations

### ISSUE THREAD

**Issue by hochhaus** [pdfcpu/pdfcpu#402]
As mentioned in in #399, we ran `pdfcpu validate` over a couple million PDFs. That resulted in ~15% of the documents failing relaxed validation despite (a sampling of them) displaying in common PDF viewers (pdf.js, pdfium & evince). I will report back later to confirm they also display in Acrobat Reader and Mac Preview.

Thankfully the vast majority of validation errors break down into a few common classes of errors. The most common of which is date validation failing. A sampling of failing formats are:

```
validation error (obj#:8): pdfcpu: validateDateObject: <D:20020301230221- 5' 0'> invalid date
validation error (obj#:73): pdfcpu: validateDateEntry: <D:20061102145045-05'> invalid date
validation error (obj#:2): pdfcpu: validateDateObject: <D:20150312082530-5'00'> invalid date
validation error (obj#:11): pdfcpu: validateDateObject: <D:20150521.124925823> invalid date
validation error (obj#:252): pdfcpu: validateDateObject: <D:20160404061414+65'53'> invalid date
validation error (obj#:1): pdfcpu: validateDateObject: <D: 20191003062617-07'00'> invalid date
validation error (obj#:3): pdfcpu: validateDateObject: <D:20191009100417-05'00''> invalid date
validation error (obj#:183): pdfcpu: validateDateObject: <D:20200429084309+ 0' 0'> invalid date
validation error (obj#:48): pdfcpu: validateDateObject: <D:20210419150333-04'00'Z> invalid date
validation error (obj#:8): pdfcpu: validateDateObject: <D:20210517043452}> invalid date
validation error (obj#:623): pdfcpu: validateDateEntry: <D:20210608122455Z00\'00> invalid date
validation error (obj#:1): pdfcpu: validateDateObject: <D: 20210827124448+00'00'> invalid date
validation error (obj#:1273): pdfcpu: validateDateEntry: <D:20211028112621--04'00> invalid date
```

Despite these formats very likely not following the spec would pdfcpu consider supporting (a subset of) them anyways (in relaxed mode) since they appear to be relatively common in the wild? Alternatively (or additionally), since some of these formats are very unexpected, could relaxed mode continue past dates that cannot be parsed (possibly falling back to a default date -- maybe 1970/1/1) to allow pdfcpu to be used with such PDFs?

**Comment by hhrutter** [comment]
Please get in touch with me: hhrutter@gmail.com
Thank you!

**Comment by hhrutter** [comment]
All of these are fixed with the latest commit.

**Comment by hochhaus** [comment]
Thanks!

**Comment by mkroetzsch** [comment]
I just came across this bug, presumably because I am not using the developer version where it was fixed. I found that a workaround (possibly also for other similar problems) was to re-encode the pdf with ghostscript:
```
gs -dNOPAUSE -sDEVICE=pdfwrite -sOUTPUTFILE=document-fixed.pdf  -dBATCH document-not-valid-in-pdfcpu.pdf
```
This might be helpful for some users who cannot upgrade easily or find unfixed problems of similar type in the future.

**Comment by cece24** [comment]
Hi @hhrutter! Would you happen to have an ETA of when this fix will be released? Thank you so much!

**Comment by hhrutter** [comment]
Work on the release is ongoing, unfortunately I am still unable to give you a tentative release date.
Meanwhile please use the latest commit.
