### ISSUE TITLE
validate: parse error trailerDict

### ISSUE THREAD

**Issue by newxiaoming** [pdfcpu/pdfcpu#408]
Read: xRefTable failed: parseTrailerDict: PDF1.4 conformant reader: found incompatible version: 1.6

How do I solve it?

Centos 7.9.2009

**Comment by hhrutter** [comment]
Please execute `pdfcpu val -vv test.pdf`and post the stacktrace.

Thank you for using pdfcpu 💚

**Comment by hhrutter** [comment]
If you could share the PDF I could fix this right away.

**Comment by hhrutter** [comment]
Closed due to inactivity.
