### ISSUE TITLE
Text extraction

### ISSUE THREAD

**Issue by suletm** [pdfcpu/pdfcpu#410]
Hello, 

first of all huge thanks for your work ! 

Documentation here [1] mentions extract feature, which supports a few things like image, raw content, fonts and etc. Looking through the existing code did not yield any insights about text extraction, so I was wondering if you could give some pointers about how to implement it with pdfcpu ?

[1] https://pdfcpu.io/extract/extract

**Comment by hhrutter** [comment]
Hello!
Text extraction is in the pipeline.
Due the complexity of this matter the implementation has been postponed to after the beta release.
See also #37, #13, #1

**Comment by suletm** [comment]
I am willing to test it when it's out. Again, thanks for all your hard work.
