### ISSUE TITLE
Add text and image at the same time using the API

### ISSUE THREAD

**Issue by pisciss** [pdfcpu/pdfcpu#416]
Hi, I'd like to know if its posible add a text and a image in the same function using the api in go.
 i have:
	wm, _ := api.TextWatermark(sello, alineacion, onTop, update, pdfcpu.POINTS)

	err = api.AddWatermarksFile(report, "output.pdf", nil, wm, nil)

How could add an image too?, sorry for my poor english. Thanks!

**Comment by hhrutter** [comment]
Sorry I was on vacation!
You can do this using: api.AddWatermarksMapFile

Thank you for using pdfcpu 💚
