### ISSUE TITLE
replace fonts inside a pdf document

### ISSUE THREAD

**Issue by mindon** [pdfcpu/pdfcpu#417]
- an embeded font with another
- a not-embedded font with another
- an embeded font with one not embedded
- a not-embedded font with one embedded

**Comment by hhrutter** [comment]
Hi!
Thanks for your suggestion.
I need to look into this.
Especially dealing with fonts that are not embedded is something new for pdfcpu because embedding font files is recommended by the PDF specification.

**Comment by kaiceo** [comment]
hope cjk fonts too，is it possbile all kinds of fonts could be replace some specific fonts to avoid copyright issues.

**Comment by hhrutter** [comment]
Sorry, avoiding copyright issues is not on the agenda of pdfcpu.

Also as stated at the end of the [ReadMe.md](https://github.com/pdfcpu/pdfcpu#readme) in the Disclaimer:
```Usage of pdfcpu assumes you know about and respect all copyrights of any PDF content you may be processing. This applies to the PDF files as such, their content and in particular all embedded resources like font files or images.```

**Comment by mindon** [comment]
just want a more comfortable readable pdf sometimes, not for any copyright issues like @kaiceo mentioned
