### ISSUE TITLE
validateNameTreeDictNamesEntry: missing "Kids" or "Names" entry

### ISSUE THREAD

**Issue by 0xtej** [pdfcpu/pdfcpu#418]
Example PDF: 
[delhi_metro.pdf](https://github.com/pdfcpu/pdfcpu/files/7845070/delhi_metro.pdf)

Crash Output:
[crash-vv.log](https://github.com/pdfcpu/pdfcpu/files/7845071/crash-vv.log)

**Comment by hhrutter** [comment]
This is fixed with the latest commit!
