### ISSUE TITLE
PDF Form filling

### ISSUE THREAD

**Issue by braindev** [pdfcpu/pdfcpu#42]
Any plans for PDF form filling?  PDF "flattening" would be a nice feature to go along with that.

Thanks!

**Comment by hhrutter** [comment]
Hi!
Form filling is definitely in the pipeline.
What's your definition of "flattening"?

**Comment by braindev** [comment]
A flattened PDF wouldn't allow the form fields to be edited.

**Comment by zbruhnke** [comment]
@hhrutter any timeline around this? It's something we're thinking about as well

**Comment by StefanSchroeder** [comment]
@hhrutter Any updates on this issue? Not pushing, just asking.

**Comment by hhrutter** [comment]
Hello!

I am hard at work and busy providing Unicode/CJKV support.
Please consider backing pdfcpu as a sponsor if you want to keep this project going.
The ❤️  button is right at the top of the ReadMe.

Thank you for using pdfcpu 💚

**Comment by kben** [comment]
@hhrutter Thanks for this incredible library, I just found it. Can I somehow support you with Code on this feature?

**Comment by hhrutter** [comment]
👍  Thanks, that's already being worked on.
Happy to take all your issues once it is released.

**Comment by karelbilek** [comment]
I tried to do PDF form filling myself, and it *almost works* but doesn't completely.

The easy part is to go through the PDF form fields and set the correct V field.

The hard part is to set the AP default appearance.

I tried to "delete" it and set NeedAppearances. What happens is AcroReader then regenerates *some* of them, but about half of them still show up empty! And I need to click inside and re-save (which makes NeedAppearances useless...)

Maybe it's something with this specific form, but some appearances are just not regenerating.

I lack the knowledge to re-create the AP myself on the form :(

**Comment by karelbilek** [comment]
I hope it will include recreating the AP appearances :D  and not just relying on NeedAppearances. I see you already do create appearances in a different part of the code (where you create text fields from scratch), so I guess you already have that :)

NeedAppearances seems a bit buggy, at least in Acrobat. I tried to study how AP streams work, and where to get the fonts reference, and my brain got too tired. :) I tried to look how iText does that and 💀 so complex. (And it is buggy too.)

yes looking forward to that. Btw pdfcpu is a great package, it allowed me to look inside PDF and play with it. Thanks a lot

**Comment by eduardo-mior** [comment]
I'm looking forward to it.

Any predictions for when this will be released?

@hhrutter  I am very grateful for your work.

**Comment by dingyaguang117** [comment]
@eduardo-mior @karelbilek @braindev @zbruhnke @StefanSchroeder @kben 

Hi guys, I implemented [form-filling](https://gist.github.com/dingyaguang117/28352dfd98364fd52cec71bd6b365efa) based on pdfcpu's low-level API.  Just for reference.

**Comment by hhrutter** [comment]
It is being worked on.

**Comment by karelbilek** [comment]
@dingyaguang117 huh interesting. Is "watermark" how it fills the AP appearance streams? Or is it a different thing?

**Comment by dingyaguang117** [comment]
> @dingyaguang117 huh interesting. Is "watermark" how it fills the AP appearance streams? Or is it a different thing?
Filling-form is based on modifing the value of  V key (Text Field) and AS key(Button Field)  in annotations.

**Comment by 0q2** [comment]
It's been four years, any updates?

**Comment by hhrutter** [comment]
This is part of the upcoming release which is all about form processing.
Please bear with me 🙏

**Comment by hhrutter** [comment]
=> https://github.com/pdfcpu/pdfcpu/releases/tag/v0.4.0

**Comment by karelbilek** [comment]
Hah good. As I promised to you one time on slack, I will try various PDFs I have to get you bugs for this, if I find them

**Comment by kben** [comment]
Hi, I just had the change to try the new implementation. But get the following error when trying to fill a textfield:

writing x.pdf...
pdfcpu: dict=<<
	<AP, <<
		<N, (757 0 R)>
	>>>
	<DA, (/Helv 12 Tf 0 g)>
	<F, 4>
	<FT, Tx>
	<Ff, 0>
	<P, (741 0 R)>
	<Rect, [413.50 545.75 565.20 568.80]>
	<Subtype, Widget>
	<T, (Textfield-5)>
	<TU, (857 0 R)>
	<Type, Annot>
	<V, (��FDSA)>
>> entry=MK missing.


Any idea what's happening here?

**Comment by hhrutter** [comment]
Not sufficient for analysis.
I need to see more of what you are doing.

**Comment by kben** [comment]
Using the follwoing PDF:

* doing a form export
* modify a textfiled
* try to fill the  pdf

https://www.aok.de/pk/magazin/cms/fileadmin/pk/rheinland-hamburg/pdf/antrag-leistungen-pflegeversicherung.pdf

**Comment by hhrutter** [comment]
Hi!
Are you trying to modify a PDF form that was not created with pdfcpu?
Then issues are expected and need to be followed up.
Please open a new issue.
Thank you!

**Comment by enahs** [comment]
@kben please link the issue here. seeing a similar problem on a 3rd party pdf fill.

**Comment by kben** [comment]
See bugreport #571
