### ISSUE TITLE
Updating images

### ISSUE THREAD

**Issue by axelssonHakan** [pdfcpu/pdfcpu#421]
Thanks for putting your effort into this library and simplifying pdf generation/manipulation for us mortals 😁

I have a project there I want to update an existing image in a pdf. The original pdf would act as a template and the object number is known (was thinking of using alt tags for the image but can't find them in the data structure).

Is it possible to "just" update the image(png) in an existing object? I feel a bit lost in the dict, raw, filter, submask, stream

What would another solution be? Just adding an image on top of the "template image"? Is it possible to get the coordinates of an image? I can find the resolution in the dict of the image but guessing there are some "boundryBox" that is placing it on the "canvas".

(Sorry for my naming of things - I don't have the knowledge of the PDF spec)

**Comment by hhrutter** [comment]
Hallo there!

Your best bet is probably rewriting the XObject in question.
You need to ensure identical image dimensions though.
Any other solution will get you in trouble eg. because of ongoing transformations.

**Comment by axelssonHakan** [comment]
Thanks for the answer.
I'm been poking around a bit more but not sure how to update that.
Is the XObject the same as  `pdfcpu.Object`?

Right now I only use pdfcpu package:
- Read
- FindObject //with the ObjectId i want to change

**Comment by hhrutter** [comment]
`pdfcpu.Object` is just an interface.

This usecase is not covered by pdfcpu at the moment and my resources are limited.
I am sorry to say that you are on your own with this.
I highly recommend reading the PDF specification..

**Comment by henrixapp** [comment]
Hi @axelssonHakan,

I was facing a similar issue. I resolved this by creating a new StreamDict with `CreateImageStreamDict` and  directly manipulating the xreftable of the old entry:
https://github.com/henrixapp/pdfcomprezzor/blob/2615a40d1fda6cc74bb8041c594da4ba8a2d6c56/main.go#L76

Best,
Henrik

**Comment by axelssonHakan** [comment]
Thanks for the feedback. I will make sure to check it out.
This is a weekend project soo hopefully I could get some time this weekend to try in out again

**Comment by hhrutter** [comment]
Closed due to inactivity.
