### ISSUE TITLE
SplitPDF corrupted document

### ISSUE THREAD

**Issue by juaismar** [pdfcpu/pdfcpu#422]
When I split a two page PDF, the second page is corrupted.
This only appears in a single (super mega secret ;-) )PFD.
I'm not very savvy in the internal structure of PDFs, but I'm trying to figure this out (since 2 days before) and will do a pull request if I find it.

### The originalPDF:
**Validation Strict**
`dict=type1FontDict required entry=FirstChar missing`
**Validation Relaxed**
works
**Validation None**
works

### The second (corrupted) PDF crash:
**Validation Relaxed**
`pdfcpu: validateFontDict: corrupt font dict`
**Validation None**
`pdfcpu: optimizeFontResourcesDict: expected Type=Font, unexpected Type: Pages`
**Validation Strict**
```
pdfcpu: dereferenceDict: wrong type pdfcpu.StreamDict <<<
        <BitsPerComponent, 8>
        <ColorSpace, DeviceRGB>
        <Filter, DCTDecode>
        <Height, 82>
        <Length, 64347>
        <Subtype, Image>
        <Type, XObject>
        <Width, 460>
>>>
```

PDFCPU version: v0.3.14-0.20220118121902-a0027457ca22
Windows 10

Thanks, I'll come back wiser and with the bug as a trophy.

**Comment by hhrutter** [comment]
Please share the stacktrace of: `pdfcpu val -vv splitResult.pdf`

**Comment by juaismar** [comment]
Total pages: 1
No font info available.

No image info available.


STATS: 2022/01/21 11:44:07 Timing:
STATS: 2022/01/21 11:44:07 read                 :  0.223s  98.1%
STATS: 2022/01/21 11:44:07 validate             :  0.004s   1.9%
STATS: 2022/01/21 11:44:07 total processing time:  0.227s

STATS: 2022/01/21 11:44:07 Original:
STATS: 2022/01/21 11:44:07 File size            : 89 KB (90748 bytes)
STATS: 2022/01/21 11:44:07 Total binary data    : 88 KB (89646 bytes) 98.8%
STATS: 2022/01/21 11:44:07 Total other data     : 1 KB (1102 bytes)  1.2%

Fatal: pdfcpu: dereferenceDict: wrong type pdfcpu.StreamDict <<<
        <BitsPerComponent, 8>
        <ColorSpace, DeviceRGB>
        <Filter, DCTDecode>
        <Height, 82>
        <Length, 64347>
        <Subtype, Image>
        <Type, XObject>
        <Width, 460>
>>>
github.com/pdfcpu/pdfcpu/pkg/pdfcpu.(*XRefTable).DereferenceDict
        C:/Users/Juan/go/pkg/mod/github.com/pdfcpu/pdfcpu@v0.3.14-0.20220118121902-a0027457ca22/pkg/pdfcpu/dereference.go:277
github.com/pdfcpu/pdfcpu/pkg/pdfcpu/validate.validateFontDict
        C:/Users/Juan/go/pkg/mod/github.com/pdfcpu/pdfcpu@v0.3.14-0.20220118121902-a0027457ca22/pkg/pdfcpu/validate/font.go:951
github.com/pdfcpu/pdfcpu/pkg/pdfcpu/validate.validateFontResourceDict
        C:/Users/Juan/go/pkg/mod/github.com/pdfcpu/pdfcpu@v0.3.14-0.20220118121902-a0027457ca22/pkg/pdfcpu/validate/font.go:1013
github.com/pdfcpu/pdfcpu/pkg/pdfcpu/validate.validateResourceDict
        C:/Users/Juan/go/pkg/mod/github.com/pdfcpu/pdfcpu@v0.3.14-0.20220118121902-a0027457ca22/pkg/pdfcpu/validate/pages.go:45
github.com/pdfcpu/pdfcpu/pkg/pdfcpu/validate.validatePageResources
        C:/Users/Juan/go/pkg/mod/github.com/pdfcpu/pdfcpu@v0.3.14-0.20220118121902-a0027457ca22/pkg/pdfcpu/validate/pages.go:114
github.com/pdfcpu/pdfcpu/pkg/pdfcpu/validate.validatePageDict
        C:/Users/Juan/go/pkg/mod/github.com/pdfcpu/pdfcpu@v0.3.14-0.20220118121902-a0027457ca22/pkg/pdfcpu/validate/pages.go:773
github.com/pdfcpu/pdfcpu/pkg/pdfcpu/validate.validatePagesDict
        C:/Users/Juan/go/pkg/mod/github.com/pdfcpu/pdfcpu@v0.3.14-0.20220118121902-a0027457ca22/pkg/pdfcpu/validate/pages.go:1005
github.com/pdfcpu/pdfcpu/pkg/pdfcpu/validate.validatePages
        C:/Users/Juan/go/pkg/mod/github.com/pdfcpu/pdfcpu@v0.3.14-0.20220118121902-a0027457ca22/pkg/pdfcpu/validate/pages.go:1046
github.com/pdfcpu/pdfcpu/pkg/pdfcpu/validate.validateRootObject
        C:/Users/Juan/go/pkg/mod/github.com/pdfcpu/pdfcpu@v0.3.14-0.20220118121902-a0027457ca22/pkg/pdfcpu/validate/xReftable.go:980
github.com/pdfcpu/pdfcpu/pkg/pdfcpu/validate.XRefTable
        C:/Users/Juan/go/pkg/mod/github.com/pdfcpu/pdfcpu@v0.3.14-0.20220118121902-a0027457ca22/pkg/pdfcpu/validate/xReftable.go:40
github.com/pdfcpu/pdfcpu/pkg/api.ValidateContext
        C:/Users/Juan/go/pkg/mod/github.com/pdfcpu/pdfcpu@v0.3.14-0.20220118121902-a0027457ca22/pkg/api/api.go:70
github.com/pdfcpu/pdfcpu/pkg/api.Validate
        C:/Users/Juan/go/pkg/mod/github.com/pdfcpu/pdfcpu@v0.3.14-0.20220118121902-a0027457ca22/pkg/api/validate.go:51
github.com/pdfcpu/pdfcpu/pkg/api.ValidateFile
        C:/Users/Juan/go/pkg/mod/github.com/pdfcpu/pdfcpu@v0.3.14-0.20220118121902-a0027457ca22/pkg/api/validate.go:92
        C:/Users/Juan/go/pkg/mod/github.com/pdfcpu/pdfcpu@v0.3.14-0.20220118121902-a0027457ca22/pkg/api/validate.go:115
github.com/pdfcpu/pdfcpu/pkg/cli.Validate
        C:/Users/Juan/go/pkg/mod/github.com/pdfcpu/pdfcpu@v0.3.14-0.20220118121902-a0027457ca22/pkg/cli/cli.go:32
github.com/pdfcpu/pdfcpu/pkg/cli.Process
        C:/Users/Juan/go/pkg/mod/github.com/pdfcpu/pdfcpu@v0.3.14-0.20220118121902-a0027457ca22/pkg/cli/process.go:35
main.process
        C:/Users/Juan/go/pkg/mod/github.com/pdfcpu/pdfcpu@v0.3.14-0.20220118121902-a0027457ca22/cmd/pdfcpu/process.go:119
main.processValidateCommand
        C:/Users/Juan/go/pkg/mod/github.com/pdfcpu/pdfcpu@v0.3.14-0.20220118121902-a0027457ca22/cmd/pdfcpu/process.go:175
main.commandMap.process
        C:/Users/Juan/go/pkg/mod/github.com/pdfcpu/pdfcpu@v0.3.14-0.20220118121902-a0027457ca22/cmd/pdfcpu/cmd.go:142
main.main
        C:/Users/Juan/go/pkg/mod/github.com/pdfcpu/pdfcpu@v0.3.14-0.20220118121902-a0027457ca22/cmd/pdfcpu/main.go:55
runtime.main
        C:/Program Files/Go/src/runtime/proc.go:255
runtime.goexit
        C:/Program Files/Go/src/runtime/asm_amd64.s:1581
validation error (obj#:8)
github.com/pdfcpu/pdfcpu/pkg/api.Validate
        C:/Users/Juan/go/pkg/mod/github.com/pdfcpu/pdfcpu@v0.3.14-0.20220118121902-a0027457ca22/pkg/api/validate.go:56
github.com/pdfcpu/pdfcpu/pkg/api.ValidateFile
        C:/Users/Juan/go/pkg/mod/github.com/pdfcpu/pdfcpu@v0.3.14-0.20220118121902-a0027457ca22/pkg/api/validate.go:92
github.com/pdfcpu/pdfcpu/pkg/api.ValidateFiles
        C:/Users/Juan/go/pkg/mod/github.com/pdfcpu/pdfcpu@v0.3.14-0.20220118121902-a0027457ca22/pkg/api/validate.go:115
github.com/pdfcpu/pdfcpu/pkg/cli.Validate
        C:/Users/Juan/go/pkg/mod/github.com/pdfcpu/pdfcpu@v0.3.14-0.20220118121902-a0027457ca22/pkg/cli/cli.go:32
github.com/pdfcpu/pdfcpu/pkg/cli.Process
        C:/Users/Juan/go/pkg/mod/github.com/pdfcpu/pdfcpu@v0.3.14-0.20220118121902-a0027457ca22/pkg/cli/process.go:35
main.process
        C:/Users/Juan/go/pkg/mod/github.com/pdfcpu/pdfcpu@v0.3.14-0.20220118121902-a0027457ca22/cmd/pdfcpu/process.go:119
main.processValidateCommand
        C:/Users/Juan/go/pkg/mod/github.com/pdfcpu/pdfcpu@v0.3.14-0.20220118121902-a0027457ca22/cmd/pdfcpu/process.go:175
main.commandMap.process
        C:/Users/Juan/go/pkg/mod/github.com/pdfcpu/pdfcpu@v0.3.14-0.20220118121902-a0027457ca22/cmd/pdfcpu/cmd.go:142
main.main
        C:/Users/Juan/go/pkg/mod/github.com/pdfcpu/pdfcpu@v0.3.14-0.20220118121902-a0027457ca22/cmd/pdfcpu/main.go:55
runtime.main
        C:/Program Files/Go/src/runtime/proc.go:255
runtime.goexit
        C:/Program Files/Go/src/runtime/asm_amd64.s:1581

**Comment by juaismar** [comment]
FYI:
The file works seting pkg/pdfcpu/pages.go Line 127 to true.
```
consolidateRes := false
// TODO consolidate via optimize flag
```
I'm sure that consolidateRes  is default false and that TODO exist for some reason.

**Comment by hhrutter** [comment]
Excellent If this solves your problem but resource consolidation at line 127 has been disabled for a reason.
Unless I have test files for further analysis this will not be changed.
This is also not a configuration candidate at this point.
