### ISSUE TITLE
replace images with other general filter(like jpeg)

### ISSUE THREAD

**Issue by kaiceo** [pdfcpu/pdfcpu#423]
early pdf embed images with CCITT FAX filter，could regenerate jpeg, png, zip, gif image and replace source image

[ACC.pdf](https://github.com/pdfcpu/pdfcpu/files/7930108/ACC.pdf)
![image](https://user-images.githubusercontent.com/63705580/150898305-f9cdf73e-ae6a-4950-b968-ce53e10c26aa.png)

**Comment by hhrutter** [comment]
Hello!
There is already a feature request for this.
Please check back at #421
