### ISSUE TITLE
Editing infoDict metadata

### ISSUE THREAD

**Issue by mikamiel** [pdfcpu/pdfcpu#424]
Can't find the command to edit values of metadata fields (e.g. Author, Subject, CreateDate, Creator, Producer, etc) of an arbitrary pdf file.

It's possible to extract metadata with "pdfcpu extract -mode meta" command, but how can one edit/change those fields?

**Comment by hhrutter** [comment]
Hello!

`pdfcpu keywords` is what you're looking for.

**Comment by mikamiel** [comment]
Maybe i miss smth, but `keywords` lets me edit/list a sort of custom/additional fields, while Author, Subject, CreateDate, Creator fields are specific mandatory pdf fields (thou they may be empty).

With `pdfcpu keywords` I can't seem to change e.g. "PDF Producer: pdfcpu  0.3.13" to, say "PDF Producer: foobar"

**Comment by hhrutter** [comment]
Well, the producer is pdfcpu.

**Comment by mikamiel** [comment]
> Well, the producer is pdfcpu.

Well, that's absolutly true)), it was just some obvious example )

**Comment by hhrutter** [comment]
Sorry I have to correct myself:
Try `pdfcpu prop add`
https://pdfcpu.io/properties/properties_add

**Comment by mikamiel** [comment]
Yes! That is it, thanks. 

But now i've faced another problem - I can't find a way to use spaces in properties (keys or values) on windows command line.

I've tried with no success:
`'Title=My title'`
`"Title=My title"`
`'Title=My\ title'`
`Title=My\ title`

**Comment by mikamiel** [comment]
Unfortunately pdfcpu does not allow to change values of base pdf metadata fields `Creator` and `Producer`.

`pdfcpu properties add test.pdf  Producer=teststring`

`property name "Producer" not allowed!`

**Comment by hhrutter** [comment]
Verfied - That's correct.
I am sorry, it's been a while since that has been implemented so I did not recall these exceptions.

You have to fork off the project and rebuild it after applying the following patch:
process.go line 1399: remove: if !validate.DocumentProperty(k) {....

Thank you for using pdfcpu  💚

**Comment by mikamiel** [comment]
Thanks, I'll try it.

Also i've found it impossible to change internal `ModifyDate` and `CreateDate` meta-fields.

But i believe editing metadata definetly needs to be present in such pdf multi-tool utility as pdfcpu.
There are a lot of situations when it's required to clean up/ sanitize metadata in a custom pdf for security(or other) reasons.

**Comment by xelan** [comment]
Same here, overriding metadata (producer, creator, dates) would be very useful. We're currently improving our PDF Toolkit[1] which currently uses pdftk for PDF manipulation, and this is the last feature currently left for full pdfcpu support as well. Maybe it could be behind a flag such as `-force` for the CLI?

[1] https://github.com/gmitirol/toolkit-pdftk/tree/feature/pdfcpu
