### ISSUE TITLE
no header version available

### ISSUE THREAD

**Issue by mario-imperato** [pdfcpu/pdfcpu#431]
Hi there I'm getting this error in reading in a pdf file. 
Attached you can find the log generated by pdfcpu: v0.3.13 dev
Apparently when reading the file it is not able to locate the string `%PDF-` to locate the header.
Now in the configuration there is a parameter headerBufSize that is assumed to be equal or less 100. 

Looking into the PDF at hand I find that the prefix is beyond the one hundred limit. 

An excerpt of the file:
`
--70097268-67dc-4e61-8d48-40b6f1453841
Content-Disposition: form-data; name=SSV1_2202070926208720RziE3dvFB; filename=SSV1_2202070926208720RziE3dvFB.pdf; filename*=utf-8''SSV1_2202070926208720RziE3dvFB.pdf

%PDF-1.7
%âãÏÓ
`

Setting the headerBufSize to something like 300 pdfcpu finds it but fails afterword in finding the root catalog when 
the invoked command is info.

`pdfcpu: Catalog: missing root dict`

I'm experimenting with the pdfcpu apis inside a golang project and I'm importing the package 

	github.com/pdfcpu/pdfcpu v0.3.13

in the go.mod. This version seems different from the latest dev check out even if the numbering seems the same. I find that the headerBufSize (for example) is hard coded to the value of 100.
 
Thank you for any help.
Mario

[crash.log](https://github.com/pdfcpu/pdfcpu/files/8035060/crash.log)

**Comment by hhrutter** [comment]
Hi there!
The configurable header buf size can be set to any value >= 100 if needed.
Please post the stacktrace you get after setting the header buf size.

**Comment by hhrutter** [comment]
What is the source of this PDF?
Checking your file header above.... this really looks weird.
.. like a http request body.. have you tried cleaning that up?
I am pretty sure you can throw away everything before %PDF.
Could be the reason the file offsets are invalid because of that leading junk and everythings fine after you remove it.

**Comment by mario-imperato** [comment]
[SSV1_2202070926208720RziE3dvFB.pdf](https://github.com/pdfcpu/pdfcpu/files/8035605/SSV1_2202070926208720RziE3dvFB.pdf)

This is the file... This pdf is a dev sample stored in a repo. So, I don't downloaded via Http but I got already in PDF format. I see the multipart header but really I don't have any clue of the process.... 
You are saying that everything is fine if I strip the garbage out? Actually I didn't try to strip the garbage off up to the %PDF........ I certainly can do some kind of logic like (if find content-disposition at the beginning remove up to the %PDF....). 
A question: I don't know if the PDF specs expects the %PDF at the very beginning or accept after some sort of preamble.... You used a 100bytes buffer so I assume that it should be at the beginning but not necessarily at the very beginning (as to speak). 

M.

**Comment by mario-imperato** [comment]
The trim fixed the issue....
I'm wondering if is possible to safely trim everything at the very beginning before '%PDF'.
What is your opinion?

**Comment by hhrutter** [comment]
What do you mean by *repo*? A public github repo?
Maybe you did not download it properly. Did you clone the repo?

Otherwise this is a judgement call. 
First I would check if `pdfcpu validate` passes possibly by increasing the header buf size in addition.
After that try and remove any leading junk and retry validation.

**Comment by mario-imperato** [comment]
By repo I mean a private content management system of contractual information. That file was stored that way before I downloaded....... I'll investigate what could have been the process that generated that stuff. 
Thank you.
M.
