### ISSUE TITLE
dict=Link entry=QuadPoints: unsupported in version 1.4\nThis file could be PDF/A compliant but pdfcpu only supports versions <= PDF V1.7

### ISSUE THREAD

**Issue by mpseay** [pdfcpu/pdfcpu#437]
Hey pdfcpu!
I've got a PDF here unfortunately I can't share. But, attempting to merge/validate it yields:

`dict=Link entry=QuadPoints: unsupported in version 1.4\nThis file could be PDF/A compliant but pdfcpu only supports versions <= PDF V1.7\n`

After further investigation, it looks like the library is explicit about supporting Quadpoints with v1.6. However, I was able to perform both of these actions with a slight modification although I'm not entirely sure of the impact:

```
diff --git a/pkg/pdfcpu/validate/annotations.go b/pkg/pdfcpu/validate/annotations.go
index 0aed620..b63a01a 100644
--- a/pkg/pdfcpu/validate/annotations.go
+++ b/pkg/pdfcpu/validate/annotations.go
@@ -330,7 +330,7 @@ func validateAnnotationDictLink(xRefTable *pdf.XRefTable, d pdf.Dict, dictName s
        }

        // QuadPoints, optional, number array, len= a multiple of 8, since V1.6
-       _, err = validateNumberArrayEntry(xRefTable, d, dictName, "QuadPoints", OPTIONAL, pdf.V16, func(a pdf.Array) bool { return len(a)%8 == 0 })
+       _, err = validateNumberArrayEntry(xRefTable, d, dictName, "QuadPoints", OPTIONAL, pdf.V14, func(a pdf.Array) bool { return len(a)%8 == 0 })
        if err != nil {
```

thoughts?

**Comment by hhrutter** [comment]
Hello!

We can extend relaxed validation to take this spec violation into account.

**Comment by mpseay** [comment]
Awesome-sauce! Much appreciated!

**Comment by mpseay** [comment]
@endigo Fix looks good to me. I'm currently running

`github.com/pdfcpu/pdfcpu v0.3.14-0.20220309084027-515c2eff91ec`

You can install the latest commit(5 days ago) `go get github.com/pdfcpu/pdfcpu@8f9a93cb9b537e4de850082e70a6fffd8e18512a`

Hope that helps!

**Comment by hhrutter** [comment]
Unfortunately I am unable to cut a release at this point. Please go get and install the current master branch like suggested above.

Thank you for using pdfcpu
