### ISSUE TITLE
Permission to print the document

### ISSUE THREAD

**Issue by readonly24** [pdfcpu/pdfcpu#438]
Hello,

I really need to have print permissions on some of my encrypted pdf documents.

Example: `pdfcpu encrypt -opw mypass -perm print mydoc.pdf` denies everything except printing of the document.

Thanks for pdfcpu, it's a useful and easy to use tool for me, having the print permission it would be perfect, now I using pdftk for this task. I'm using Windows 10.

**Comment by hhrutter** [comment]
This is fixed in the latest commit.

We now support `-perm none|print|all]` on the CLI for `pdfcpu encrypt` and `pdfcpu permissions set`.

You can also set the default permissions for PDF writing via tuning the configuration/config.yml:

```
# permissions for encrypted files:
# -3901 = 0xF0C3 (PermissionsNone)
# -1849 = 0xF8C7 (PerissionsPrint)
#    -1 = 0xFFFF (PermissionsAll)
permissions: -3901
```
Have fun with pdfcpu 💚

**Comment by readonly24** [comment]
Thanks a lot.
