### ISSUE TITLE
Duplicate form values when merging

### ISSUE THREAD

**Issue by artembrizinskij** [pdfcpu/pdfcpu#440]
Hi! @hhrutter, great project, thanks for that! 

I ran into a problem when merging two files whose forms have the same name.
Example: 
I have two identical pdfs whose forms are filled with different values.
After merging, the form values of both documents become identical (the values from the first document in the merge list are substituted) 
on the input: 
![image](https://user-images.githubusercontent.com/17120874/155090172-84c637e0-0076-4279-b7d3-0999d4047f9e.png)

and in the output, after merging, I get the same values for the first and second form - `first form`

[PdfFormExample(1).pdf](https://github.com/pdfcpu/pdfcpu/files/8114836/PdfFormExample.1.pdf)
[PdfFormExample(2).pdf](https://github.com/pdfcpu/pdfcpu/files/8114837/PdfFormExample.2.pdf)
[out.pdf](https://github.com/pdfcpu/pdfcpu/files/8114840/out.pdf)

**Comment by maxiride** [comment]
I encountered this issue for the first time even with the built-in Adobe Acrobat X Pro merging. The only workaround is to first flatten the single files and then merging them, [here is a comment](https://community.adobe.com/t5/adobe-acrobat-online-discussions/how-do-i-combine-multiple-fillable-forms-into-one-document-instead-of-seperate-files-in-one-document/m-p/8318276#M22619) from an adobe employee on the subject.

**Comment by artembrizinskij** [comment]
@maxiride Thanks for the hint!

**Comment by RFlipper** [comment]
I tried PDFtk it works correctly

`pdftk.exe  *.pdf cat output result.pdf`

[result.pdf](https://github.com/pdfcpu/pdfcpu/files/8139997/result.pdf)

Hope it will help to research the issue

**Comment by hhrutter** [comment]
This is fixed with the latest commit.
You should be able to do smth like: `pdfcpu merge out.pdf in.pdf in.pdf in.pdf`

**Comment by tmm1** [comment]
I'm having this issue with v0.9.1 and main. After `merge`, editing one copy of a form edits all the values. Looking at `form list`, I see `Multi page fields` listed.

**Comment by hhrutter** [comment]
> I'm having this issue with v0.9.1 and main. After `merge`, editing one copy of a form edits all the values. Looking at `form list`, I see `Multi page fields` listed.

Please submit or email your file for a fix if you can share.
Thank you!
