### ISSUE TITLE
extracting CCITT images

### ISSUE THREAD

**Issue by Chanonry** [pdfcpu/pdfcpu#441]
Not a bug as such although maybe a documentation improvement.

v0.3.13
Docker base image golang:1.17-buster

I am struggling to find my way around your api to extract CCITT encoded images.  

With ReadFile() I can create a Context. When I review the XRefTable.Table during debugging there are multiple XRefTableEntry values for CCITT that I want to grab and convert into a tiff file for further image processing.

This is where I get a bit lost. I want to filter on the StreamDict.Filter field or on the FilterPipeline then grab the relevant data and decode. Presumably

There are a number of types in the api that look potentially useful but its not clear what the correct workflow would be.

**Comment by Chanonry** [comment]
So I tried to use ObjectStreamDict to capture StreamDict/s from a TableEntry but this was corrupting the Filter data for some reason. In the end I wrote some code to process the XRefTableEntry to filter out the StreamDicts that had a single CCITT filter.

Seems to me there are a number of embedded interfaces within XRefTableEntry without any methods to access the underlying values? This makes dealing with this part of the API painful.  There again, maybe I am missing the point.

**Comment by hhrutter** [comment]
Hi there!

Do you intend to use the CLI ot the API?

pdfcpu already extracts ccitt encoded imagedata on the command line like so:
`pdfcpu extract -mode image in.pdf outDir`
The resuling image file will be a PNG.

If you need to use the API your hook is located in extract.go: 
`func ExtractImages(rs io.ReadSeeker, selectedPages []string, digestImage func(pdfcpu.Image, bool, int) error, conf *pdfcpu.Configuration) error`

This is also driving the CLI command mentioned above.

Thanks for using pdfcpu 💚

**Comment by hhrutter** [comment]
Closed due to inactivity.
