### ISSUE TITLE
Export width and height properties on `pdfcpu.Image`

### ISSUE THREAD

**Issue by wongk** [pdfcpu/pdfcpu#443]
We would like to filter out some of the images that are extracted from our PDFs based on width and height, and potentially even file size. Right now we cannot access that information.

**Comment by hhrutter** [comment]
Hi!

Extracting all images and then filtering the result does not work for you?

**Comment by wongk** [comment]
The `width` and `height` properties on `pdfcpu.Image` are not exported.

**Comment by wongk** [comment]
I am simply passing the reader object directly to an S3 uploader to stream the image to S3. I would prefer not to read the image into memory or "know anything" about image handling if pdfcpu could extract these attributes from the image metadata.

**Comment by wongk** [comment]
That would be ideal.

**Comment by hhrutter** [comment]
This is supported in the latest commit!

**Comment by wongk** [comment]
That's awesome, thank you!
