### ISSUE TITLE
Possibly corrupt annotation dict

### ISSUE THREAD

**Issue by tomo25** [pdfcpu/pdfcpu#445]
When you run the info API, it tries to read the annotation in the file. 
However, there are some pdf files that don't have a subtype in annotation so it will result in an ` invalid memory address or nil pointer dereference` error.  Thought it will be better if you can still fetch the info of the file, although when subtype is not specified.

where subtype is fetched
https://github.com/pdfcpu/pdfcpu/blob/master/pkg/pdfcpu/annotate.go#L557

where subtype is used and the error is caused
https://github.com/pdfcpu/pdfcpu/blob/master/pkg/pdfcpu/annotate.go#L524

**Comment by hhrutter** [comment]
Omitting the annotation type may be a violation of the PDF spec.
Can you share a sample file for further investigation?

**Comment by tomo25** [comment]
Thanks @hhrutter. Unfortunately, I can't provide an sample file because it contains confidential information, but I encountered this type of PDF a couple of times.  Would be safer if there it handles when subType is nil.

**Comment by hhrutter** [comment]
We can always extend relaxed validation but I prefer to do that based on evidence.
I am always curious about which PDF Writer produces what quality and so forth.

**Comment by hhrutter** [comment]
Can you at least post a stacktrace that points out the annotation dict in question.
Thank you.

**Comment by nhannh23** [comment]
Hi @hhrutter 
I guess I had the same problems in some of my files. I already sent you the file via Slack.
Could you please have some checks?
Thank you.

**Comment by hhrutter** [comment]
Nope, your file had a corrupted xref table caused by Google Sheet I guess.
Go get the latest commit for a fix.
I am leaving this open.

**Comment by hhrutter** [comment]
Closed due to inactivity.
