### ISSUE TITLE
Cannot install TTF fonts

### ISSUE THREAD

**Issue by nhannh23** [pdfcpu/pdfcpu#446]
Thanks for your dedication as always.

I can install a lot of TTF fonts normally, but the ones from this repository.
https://github.com/googlefonts/morisawa-biz-ud-gothic/tree/main/fonts/ttf

I got this error
```
unexpected panic attack: runtime error: slice bounds out of range [:1471273124] with capacity 201732
```

I think it is from here
https://github.com/pdfcpu/pdfcpu/blob/master/pkg/font/install.go#L478-L484

I had a hard time trying to understand the meaning of the variables.
Please help. Thank you very much.

**Comment by hhrutter** [comment]
This is fixed with latest commit.
