### ISSUE TITLE
MergeCreateFiles memory usage

### ISSUE THREAD

**Issue by maxiride** [pdfcpu/pdfcpu#447]
I'm using [MergeCreateFiles](https://pkg.go.dev/github.com/pdfcpu/pdfcpu/pkg/api#MergeCreateFile) to merge in a single document 6k PDF of 2 pages each for a total weight of 688 MB approximately.
[Below](https://github.com/pdfcpu/pdfcpu/issues/447#issuecomment-1080316266) futher details on the task being performed.

I assemble the slice of input files according to a certain business logic and then call MergeCreateFiles.

I noticed that the process running this very simple script consumed 2.7GB of RAM and I'm wondering why. I understand that the documents have all to be opened in order to be merged but didn't expect such high usage of the RAM. I'm trying to run a profiler but I still haven't understood well the cause.

* Your issue is based on the latest commit: yes
* State your OS and OS version: Windows 10 64bit

Please note that the PDF files are half of the total files reported. The other half are text file less than 1KB.
![image](https://user-images.githubusercontent.com/3630857/160082803-6b0d311d-b046-4b47-adef-ef3b98d471ae.png)

**Comment by hhrutter** [comment]
Hi there!
Can you please post the details of this operation.
What I need to see is a list of input files accompanied by page count and file size.

**Comment by maxiride** [comment]
Hello Horst!

The task involves 6645 files, each of 2 pages for a total of 13290 pages, the sum of the weight of the files is 662 MB, files have been sent via email per usual.

The code used to merge them is a bare bone call to the API package where `inFiles` is a slice of filepaths of the files to merge. For what's worth, all the files are in the same directory:
```go
	err := pdfapi.MergeCreateFile(inFiles, outFile, PdfConf)
	if err != nil {
		return errors.Wrap(err, fmt.Sprintf("KO unione %s", filepath.Base(outFile)))
	}

...
Below the configuration struct passed to the method call.
...
// PdfConf rappresenta la configurazione di base di pdfcpu con unità di misura impostata in millimetri
var PdfConf *pdfcpuc.Configuration

func init() {
	PdfConf = pdfcpuc.NewDefaultConfiguration()
	PdfConf.Unit = pdfcpuc.MILLIMETRES
	PdfConf.WriteXRefStream = false // Necessario per compatibilità file enormi https://github.com/pdfcpu/pdfcpu/issues/369
	PdfConf.ValidationMode = pdfcpuc.ValidationNone
}
```

**Comment by hhrutter** [comment]
You are aware 6000 input files is quite heavy..
The corresponding memory consumption is not a surprise to me and I am sure there is potential for optimization if you are really that worried about memory.
I also can't rule out a memory leak.
No excuses but also remember: pdfcpu is still Alpha.

**Comment by maxiride** [comment]
> You are aware 6000 input files is quite heavy.. 

Yeah I know, but due to the low page count and small filesize I gave it a run anyway.


> The corresponding memory consumption is not a surprise to me and I am sure there is potential for optimization if you are really that worried about memory.
I also can't rule out a memory leak.
No excuses but also remember: pdfcpu is still Alpha.

I don't think this is necessarily an issue, the event simply made me raise an eyebrow since I do obviously expect some heavy RAM usage, but not  4x the total file size. Definitively a very low priority.

**Comment by hhrutter** [comment]
The api portion of the merge command has been refactored, which should improve the memory consumption issue you reported.
Please let me know how this works out for you.

**Comment by hhrutter** [comment]
Closed due to inactivity.
