### ISSUE TITLE
Remove bookmarks

### ISSUE THREAD

**Issue by vorishirne** [pdfcpu/pdfcpu#448]
In my pdf existing bookmarks exist. AddBookmarks fail with above error. Need a way that i can remove bookmarks in pdf, so that after that i can then call AddBookmark.

**Comment by smackysnacks** [comment]
I'm also interested in this feature.

Is it possible to parameterize `(*Context).AddBookmarks` with something like `(*Context).AddBookmarks(bms []Bookmark, overwriteExisting bool)` and change

https://github.com/pdfcpu/pdfcpu/blob/a02156691061fee8247486e4733d11549cbb29ac/pkg/pdfcpu/bookmarks.go#L327-L329

to something like

```go
  if overwriteExisting {
    rootDict.Delete("Outlines")
  }

  if _, ok := rootDict.Find("Outlines"); ok { 
    return errExistingBookmarks 
  }
```

Then expose this from the API as a new function perhaps (e.g. `AddBookmarksOverwrite`)?

**Comment by hhrutter** [comment]
This is fixed with the latest release.
