### ISSUE TITLE
Watermark font size configuration not respected

### ISSUE THREAD

**Issue by gernotstarke** [pdfcpu/pdfcpu#449]
In my code, the TextWatermark() and AddWatermarkFile() functions behave different than in the tests… esp. the font size is extremely huge:
```
wm, err := api.TextWatermark("43", "font:Helvetica, points:24, aligntext:center,position:c, offset:0 0, scale:0.5 rel, diagonal:1, rendermode:0, fillcolor: 0.5 0.5 0.5", onTop, update, pdfcpu.POINTS)
if err != nil {
   fmt.Println("TextWatermark configuration error:", err)
}

err = api.AddWatermarksFile("sample-A4-portrait-3pgs.pdf", "out2.pdf", nil, wm, nil)
if err != nil {
   fmt.Println(err)
}
```
12 Points is a regular text size in letters and books, the resulting pdf looks as follows (pagesize is approx A4).
I can scale down that text with a “scale: 0.05” param, but it seems somewhat weird...

<img width="526" alt="image" src="https://user-images.githubusercontent.com/11322155/161405274-683c1c4f-f264-4fae-8d58-8aa910c2f3b7.png">

**Comment by hhrutter** [comment]
Hello!

This looks good to me.
I don't see any usage of 12 points in your issue but when using relative scaling for text watermarks the font size you are using is irrelevant.
You are using a relative scale factor: 0.5
This means the stamp is scaled by pdfcpu so it takes up 50% of your page width.

Thank you for using pdfcpu 💚

**Comment by gernotstarke** [comment]
For me it looks counter-intuitive to provide an absolute fontsize in points, and receive a watermark that is way larger than that. Even without providing a scale factor, the size remains huge (see sample below).

Initially I missed the explanation in the documentation saying "in combination with absolute scaling only".

`wm, err := api.TextWatermark("12", "font:Helvetica, points:12, position:br, rot: 0", true, false, pdfcpu.POINTS)
`

<img width="643" alt="grafik" src="https://user-images.githubusercontent.com/1233990/161416793-daedd3cb-8081-4a9c-bb57-5d3c2c68beaf.png">

thanx for helping me out.

**Comment by hhrutter** [comment]
Please refer to the documentation for the stamp command [here](https://pdfcpu.io/core/stamp) and also familiarize yourself with the defaults.


<img width="552" alt="Screen Shot 2022-04-04 at 10 51 23" src="https://user-images.githubusercontent.com/11322155/161558902-f61ecaba-ca7c-43b8-8741-590c884b436c.png">

**Comment by gernotstarke** [comment]
thanx for the perfect answer, will close the issue
