### ISSUE TITLE
Creation of leaflet from generated PDFs fails at v0.3.13 (works fine with v0.3.12 and earlier)

### ISSUE THREAD

**Issue by Hi-Fi** [pdfcpu/pdfcpu#454]
When tried to update pdfcpu to newer version, got following errors with same call that worked with earlier version. So a bit strangely error is not same every time, even call is exactly same

```
Error at Collect: pdfcpu: validateFontDict: unknown Subtype: CIDFontType2

Error at NUp: Read: xRefTable failed: pdfcpu: can't find last xref section
```

```
Error at Collect: pdfcpu: dereferenceDict: wrong type pdfcpu.StreamDict <<<
        <Filter, FlateDecode>
        <Length, 175>
>>>
Error at NUp: Read: xRefTable failed: pdfcpu: can't find last xref section
```

```
Error at Collect: pdfcpu: dereferenceDict: wrong type pdfcpu.StreamDict <<<
        <Filter, FlateDecode>
        <Length, 97>
>>>
Error at NUp: Read: xRefTable failed: pdfcpu: can't find last xref section
```

```
Error at Collect: pdfcpu: dereferenceDict: wrong type pdfcpu.StreamDict <<<
        <Filter, FlateDecode>
        <Length, 7085>
        <Length1, 18500>
>>>
Error at NUp: Read: xRefTable failed: pdfcpu: can't find last xref section
```

That error originates from https://github.com/Hi-Fi/sss/blob/main/print/pkg/pdf/booklet.go#L34.

### OS

Linux (Visual studio dev container, https://github.com/Hi-Fi/sss/tree/main/.devcontainer)

```
vscode ➜ /workspaces/sss-github/print (main ✗) $ uname -a
Linux 7cced97b57d6 5.10.104-linuxkit #1 SMP Thu Mar 17 17:08:06 UTC 2022 x86_64 GNU/Linux
vscode ➜ /workspaces/sss-github/print (main ✗) $ lsb_release -a         
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 11 (bullseye)
Release:        11
Codename:       bullseye
```

**Comment by hhrutter** [comment]
Hi!
I can probably fix this for you if you can share a PDF for debugging.
You can also email me.

**Comment by Hi-Fi** [comment]
PDF is fully generated in the linked service, so do you mean payload to call the service, or export generated pages without ordering those to booklet/leaflet?

**Comment by hhrutter** [comment]
I can see a parser error when executing `nup` on a particular PDF.
Please share this input file separately via link or email for analysis.
Thank you!

**Comment by Hi-Fi** [comment]
I think Nup error is irrelevant, as my code doesn't fail on the issue from Collect, but just prints the error. So issue happens already in that one.

But I can try to check what kind of pages are generated for leaflet, as plain A4 with columns works fine.

**Comment by hhrutter** [comment]
In order to fix this all I need is an isolated pdfcpu operation that fails and the corresponding input file so I can reproduce.

**Comment by Hi-Fi** [comment]
I'll try to provide those later today. Has to modify code to output the source file before failure.

**Comment by Hi-Fi** [comment]
Source file: https://www.dropbox.com/s/85j5ok3p9wxs78x/leaflet-20220417145828.pdf?dl=0 (generated with linked code, and added couple of empty pages in code to get page count dividable by 4).

Installed `pdfcpu` with brew, with output:
```
pdfcpu version
pdfcpu: 0.3.13

pdfcpu collect -p 1,4,2,3 leaflet-20220417145828.pdf collected.pdf
writing collected.pdf...
pdfcpu: dereferenceDict: wrong type pdfcpu.StreamDict <<<
	<Filter, FlateDecode>
	<Length, 175>
>>>
```

Same with older version (source file same):

```
~/Downloads/pdfcpu_0.3.12_macOS_x86_64/pdfcpu version
pdfcpu: 0.3.12
build : 2021-07-12T00:48:22Z
commit: 63d5ab6

~/Downloads/pdfcpu_0.3.12_macOS_x86_64/pdfcpu collect -p 1,4,2,3 leaflet-20220417145828.pdf collected.pdf
writing collected.pdf...
```

**Comment by Hi-Fi** [comment]
Apparently this one is already fixed (at least collect part) in the dev version:
```
~/go/bin/pdfcpu version                                                    
pdfcpu: v0.3.13 dev
~/go/bin/pdfcpu collect -p 1,4,2,3 leaflet-20220417145828.pdf collected.pdf
writing collected.pdf...
```

and output file works

**Comment by hhrutter** [comment]
Sounds good then 👍 
Too early too tell.
