### ISSUE TITLE
grid: merge all pages of a pdf file into a single-page pdf

### ISSUE THREAD

**Issue by miranquil** [pdfcpu/pdfcpu#458]
I'm trying to generate single-page PDF by puppeteer which could only generate multiple pages file. So I'm looking for some way to merge pages of a single pdf.

**Comment by hhrutter** [comment]
Try `pdfcpu grid out.pdf 1 10 in.pdf`
Substitute 10 with in.pdf's page count.

**Comment by miranquil** [comment]
> Try `pdfcpu grid out.pdf 1 10 in.pdf`
> Substitute 10 with in.pdf's page count.

Well, I have a 6-page pdf file and I tried `pdfcpu grid out.pdf 1 6 test.pdf` which printed `pdfcpu nup: n must be one of 2, 3, 4, 6, 8, 9, 12, 16`.

Also I've checked help response and I'm kind of confused. `6` is not `n`?

**Comment by hhrutter** [comment]
This sounds like a bug.
Are you running the latest release v0.3.13 or even better the latest commit?

**Comment by miranquil** [comment]
Yeah I'm running the latest version.

```sh
> pdfcpu version
pdfcpu: 0.3.13
```

**Comment by hhrutter** [comment]
I just checked and it works using the latest commit.

.. I noticed the command line documentation using `pdfcpu help grid` confuses the grid dimension parameters - this will be fixed/corrected with the next release.

Follow: https://pdfcpu.io/generate/grid and you should be fine.

**Comment by miranquil** [comment]
Seems strange... I just copied the example `pdfcpu grid -- "bo:off" out.pdf 1 4 in.pdf` and it still returns `pdfcpu nup: n must be one of 2, 3, 4, 6, 8, 9, 12, 16`.

**Comment by hhrutter** [comment]
You need to install the latest and greatest from the master branch or wait for the next release for which I cannot give you a date unfortunately.

**Comment by hhrutter** [comment]
`pdfcpu help grid` has been corrected.
