### ISSUE TITLE
adding pdfcpu as go dependency increases container size in 600mb

### ISSUE THREAD

**Issue by glserranv** [pdfcpu/pdfcpu#460]
Adding pdfcpu as a dependency increases 600MB to container size. Is this exepected/known?

**Comment by hhrutter** [comment]
Hello!

Since the binary is around 3 MB the image should stay slim but pdfcpu is known to use quite some memory.
Please give us more details about your observation.

**Comment by hhrutter** [comment]
Can you investigate further?
Also is your container size increasing by or to 600MB?

**Comment by J-Rocke** [comment]
I can build docker container with less than 70MB including pdfcpu as a go library and many more libs. I only include the binary and not the source code in the container which is a common best practice. I don't think this is a issue with pdfcpu but with the way the container is build.

**Comment by hhrutter** [comment]
👍 good news!

Is your docker file any different from the one in the repo, if not would you mind sharing yours?

```
# Dockerfile References: https://docs.docker.com/engine/reference/builder/

# Start from the latest golang base image
FROM golang:latest as builder

# install
RUN go install github.com/pdfcpu/pdfcpu/cmd/pdfcpu@latest

######## Start a new stage from scratch #######

FROM alpine:latest

RUN apk --no-cache add ca-certificates

WORKDIR /root/

# Copy the Pre-built binary file from the previous stage
COPY --from=builder /go/bin .

# Command to run the executable
CMD ["./pdfcpu"]
```

**Comment by J-Rocke** [comment]
@hhrutter I have a very similar Dockerfile but in our usecase pdfcpu is called directly from the go code. Since there is no evidence that pdfcpu greatly inflates binary size / container size this issue is missleading in my opinion and should maybe be closed. If you want to investigate more you can of course keep it open.

**Comment by hhrutter** [comment]
sounds good to me.
