### ISSUE TITLE
create: RTL - text inside table object

### ISSUE THREAD

**Issue by cezar-radan** [pdfcpu/pdfcpu#461]
In my tests I created PDF files using CreateFromJSONFile function (https://pkg.go.dev/github.com/pdfcpu/pdfcpu/pkg/api#CreateFromJSONFile)
with json files containing : header, footer, textfields, texts, tables and so on.
 
Everything is working perfect but when I switch to a RTL language (ex.Hebrew) the attribute "rtl": true
doesn't have any effect in case of tables and footer objects, this means that inside the tables the texts are not rotated in RTL fashion (in case of texts and textfields the aforementioned attribute works okay).
     .....
  "table": [{
                        "hide": false,
                        "header": {
                            "values": ["(סְכוּם", "מחיר", "תיאור", "כַּמוּת"],
                            "colAnchors": ["Center", "Center", "Center", "Center"],
                            "bgCol": "$CustomColor",
                            "rtl": true,
                            "font": {
                                "name": "$myOpenSansHebrewLabel"
                            }
                        },
......
There is another attribute that should  I use in tables and footer to obtain RTL effect ?
I mean, instead of "rtl": true should I use another attribute or o combination of attributes?
Thank you very much.

**Comment by hhrutter** [comment]
RTL fonts have not been addressed properly.
The next release will take care of this.
