### ISSUE TITLE
pdfcpu: config dir problem: invalid validationMode:

### ISSUE THREAD

**Issue by mrg0lden** [pdfcpu/pdfcpu#462]
Hi,
I'm running into a problem where my program exists unexpectedly with several different PDF files.
Digging into the code using GitHub's search I found the code point where that happens.

https://github.com/pdfcpu/pdfcpu/blob/437ac574b0eab4023d086dd93e0ee8d461deb713/pkg/pdfcpu/configuration.go#L275

The program is running inside a Docker container with `busybox` image, an almost `scratch` image, so I don't know if that's related.
The problem with `os.Exit()` is that it cannot be prevented in any way compared to `panic` which can be recovered from, which leads the whole program to exit immediately, an unfavorable state for my program.

**Comment by mrg0lden** [comment]
I can confirm that this bug is related to using the `busybox` image. I moved to an Ubuntu image and it worked fine.

**Comment by hhrutter** [comment]
I am aware `os.Exit(1)` is uncomfortable for API users.

I need to revisit all situations  where we do this but in this case we could issue a warning and move on silently using a new default configuration similiar to `-conf disable`on the CLI.

**Comment by mrg0lden** [comment]
I am not sure, but as I mentioned above. I think it's related to something missing in the `busybox` image but present in the `ubuntu` image. Unfortunately, I cannot investigate it now as I'm facing a deadline, but I'll hopefully revisit once things have settled.

**Comment by hhrutter** [comment]
Closed due to inactivity.
