### ISSUE TITLE
The T attribute of a form field is not correct

### ISSUE THREAD

**Issue by dingyaguang117** [pdfcpu/pdfcpu#464]
I'm trying to parse the form information like this:

```golang
item, ok :=r.ctx.XRefTable.Table[id]
dict, ok = item.Object.(pdfcpu.Dict)
```

But the T attribute seems to be wrong.

![image](https://user-images.githubusercontent.com/1930778/166171912-e6a265b1-bb9e-4d45-8f9f-615e0d01f03b.png)

What I get by `mutool` is `(topmostSubform[0].Page1[0].f_20[0])`

<img width="346" alt="image" src="https://user-images.githubusercontent.com/1930778/166171924-788cc935-e7d1-43de-bf7e-b85cf26af0eb.png">

[Attachment] Demo PDF:

[fw8ben.pdf](https://github.com/pdfcpu/pdfcpu/files/8600195/fw8ben.pdf)

**Comment by hhrutter** [comment]
You are dealing with a UTF16 encoded string.
Form extraction will be part of the next release.

**Comment by dingyaguang117** [comment]
> You are dealing with a UTF16 encoded string. Form extraction will be part of the next release.

Thanks very much for explaining. 

I have decoded the hex string, and got `f_20[0]`,   but what I get by mutool is `(topmostSubform[0].Page1[0].f_20[0])`.  

I wonder why there is a difference, mutool fill the full path for the form field?

**Comment by hhrutter** [comment]
Sorry no idea and I don't know the tool.

**Comment by dingyaguang117** [comment]
Thank you very much and look forward to the next release!

**Comment by petervwyatt** [comment]
It's the difference between partial and fully qualified path names used with PDF Fields as per clause 12.7.4.2:

> The **T** entry in the field dictionary (see "Table 226 — Entries common to all field dictionaries" holds a text string defining the field’s _partial field name_. The _fully qualified field name_ is not explicitly defined but shall be constructed from the partial field names of the field and all of its ancestors. For a field with no parent, the partial and fully qualified names are the same. For a field that is the child of another field, the fully qualified name shall be formed by appending the child field’s partial name to the parent’s fully qualified name, separated by a PERIOD (2Eh) as shown:
`parent’s_full_name.child’s_partial_name`
EXAMPLE If a field with the partial field name PersonalData has a child whose partial name is Address, which in turn has a child with the partial name ZipCode, the fully qualified name of this last field is
PersonalData.Address.ZipCode
