### ISSUE TITLE
svg support

### ISSUE THREAD

**Issue by Insua** [pdfcpu/pdfcpu#465]
add vector image to pdf need supported,is there any plan to do it

**Comment by Insua** [comment]
I both have png and svg,but svg is vector image,png is bitmap image,after zoom,the png image will be blurred
In my case,I will put the signatrue vector image,so I want to be clearly after zoom.
If support svg will be a big suprise.

**Comment by hhrutter** [comment]
You need to set your output dimensions during the conversion:
https://stackoverflow.com/questions/9853325/how-to-convert-a-svg-to-a-png-with-imagemagick

**Comment by hhrutter** [comment]
Closed due to inactivity.
