### ISSUE TITLE
Import image relative scaling might be false

### ISSUE THREAD

**Issue by TheoEb** [pdfcpu/pdfcpu#466]
Hello,
I'm trying to convert images to A4 pdf with the API, and ran into an issue.
If the pdf aspect ratio is between 0.7 and 1, the image will be scaled vertically and cropped horizontally.

It might be this part of the code:
https://github.com/pdfcpu/pdfcpu/blob/11d755a41bcb605c55e2727ab7608a93cb889224/pkg/pdfcpu/importImage.go#L445-L459

I think the aspect ratio of the image should be compared to the aspect ratio of the page and not to 1.

Is it a bug or an intentional behavior ?

**Comment by hhrutter** [comment]
Can you share a pic and the corresponding import command that reproduces your problem?

**Comment by TheoEb** [comment]
The corresponding command  is `pdfcpu import -- "pos:c, sc:1" example.pdf example.png`

It can be reproduced with this image:
![image](https://user-images.githubusercontent.com/36158810/168021956-7bbed2f0-0e5e-40d7-9057-d93263201b69.png)

**Comment by hhrutter** [comment]
Thanks, I will check that out.

**Comment by TheoEb** [comment]
Any updates ?
