### ISSUE TITLE
cut pages

### ISSUE THREAD

**Issue by sxsnwangrenfei** [pdfcpu/pdfcpu#467]
I want to copy every page after each page to cut the page, but I can't find the copy function.
`pdfcpu crop  -pages odd -- "pos:tl, dim:603.78 824.882" in.pdf out.pdf`
`pdfcpu crop  -pages even -- "pos:tr, dim:603.78 824.882" in.pdf out.pdf`
How to implement one command?

**Comment by hhrutter** [comment]
Hello!

I don't think I understand your request.
Could you please explain in more details.
What do you mean by *copy a page* ?
Maybe you can give us an example.

**Comment by sxsnwangrenfei** [comment]
> Hello!
> 
> I don't think I understand your request. Could you please explain in more details. What do you mean by _copy a page_ ? Maybe you can give us an example.
![I want](https://user-images.githubusercontent.com/29590048/168572834-98ce51af-5bf1-4202-945e-ff58cde7b038.jpg)
Can you see this picture? 
That's what I mean.
**Double page to single page.**
Thanks!

**Comment by hhrutter** [comment]
Ah.. understood!
Interesting usecase.
Let me think about it..

**Comment by hhrutter** [comment]
The next release will feature the `cut`command.

**Comment by hhrutter** [comment]
This is fixed with the latest release.
