### ISSUE TITLE
Remove all annotation according to their content?

### ISSUE THREAD

**Issue by AlawamiAZ** [pdfcpu/pdfcpu#468]
Hi

Is there a way to delete any annotation that has a certain content?
For example I have a pdf filled with useless annotations (links) and I want to delete only the objects that has that has that specific link:
![image](https://user-images.githubusercontent.com/85796614/168466023-8de7bca7-e16f-4e64-bf6b-a882eb7b8495.png)

thanks

**Comment by hhrutter** [comment]
Hello!

Removing annotations via search filter is not supported since there are different kind of annotations.
You need to supply a list of object numbers to: `pdfcpu annot remove in.pdf 1,2,3,4,5`.

Thank you for using pdfcpu 💚
