### ISSUE TITLE
create via JSON: adjusted text support

### ISSUE THREAD

**Issue by vsenko** [pdfcpu/pdfcpu#470]
The new "create by JSON" feature introduced in https://github.com/pdfcpu/pdfcpu/releases/tag/v0.3.13 is cool, but is not very handy in complex scenarios because of the lack of the ability to automatically break text strings into multiple lines according to a specified width.

For example consider a list of blocks each one of which contains an image and a string, they should be placed vertically one under another. In case if lengths of strings are not constrained, it would be rational to split long ones into several and position them under each other. Two problems arise: it's hard to figure out where to break the line optimally (it depends on the font and contents of the string) and the vertical size of the block becomes variable thus the position of the next block can not be calculated beforehand. And one more: it's impossible to determine the quantity of the blocks that can fit on one page.

As for me, a perfect solution would be like this:
- a way to specify width for text (along with position, font, size, etc) so that the text string would be split into several lines of text to fit the width;
- something like a cursor with current vertical position where the previous text finished, one would be able to position the next text block relatively to it;
- split-able pages (define one page with a lot of content) - so that the caller would not have to figure out on how many pages will his content fit.

This approach is inspired by http://www.fpdf.org/, see `MultiCell` and `Cell` in the Manual.

**Comment by hhrutter** [comment]
v0.4.0 supports justified textboxes.
Check out: pkg/samples/create/primitives/textAndAligment.pdf 
and it's corresponding JSON source: pkg/testdatat/json/create/textAndAlignment.json

**Comment by vsenko** [comment]
Looks good!
I'll give it a try in a couple of days, thank you so much for your work on this project, it's fantastic!
