### ISSUE TITLE
stamp: the stamp/watermark does not show up in the PDF Viewer

### ISSUE THREAD

**Issue by vsenko** [pdfcpu/pdfcpu#471]
Please ensure the following:

* Your issue is based on the latest commit:
TRUE
* State your OS and OS version
Ubuntu 18.04.6 LTS
* When reporting a problem with a specific PDF input file please avoid stating the organization responsible for the PDFWriter - just refer to the *PDFWriter*

Steps to reproduce:
```
$ ./pdfcpu validate sample.pdf 
validating(mode=relaxed) sample.pdf ...
validation ok
$ ./pdfcpu stamp add -mode text -- "Watermark text" "sc:1" sample.pdf sample-text.pdf 
writing sample-text.pdf...
$ ./pdfcpu stamp add -mode pdf -- "sample.pdf" "sc:1" sample.pdf sample-pdf.pdf 
writing sample-pdf.pdf...
```

New files are generated without warnings or errors, but viewers (at least Firefox and Gnome Evince) do not display any watermarks. Similar with `watermark`.

[sample.pdf](https://github.com/pdfcpu/pdfcpu/files/8708503/sample.pdf)

**Comment by ihipop** [comment]
@hhrutter 

I also have the similar problem, and I make a simple special test file

In this file, the first page is working for add watermarks

but the second page is not

the second page is cut from another pdf that also have the problem

[1.pdf](https://github.com/pdfcpu/pdfcpu/files/8726916/1.pdf)

**Comment by ihipop** [comment]
Your case is different from mine

You pdf can not see watermark in chrome，but in https://code-industry.net/masterpdfeditor/ ,it's  visible

![image](https://user-images.githubusercontent.com/423077/169259701-b706a7a0-e841-4791-ae64-3d66788574bb.png)

in my case ,both of them not work

**Comment by hhrutter** [comment]
Hello!

I can confirm a bug stamping input PDFs containing `OCProperties`.

Some more flexible PDF Viewers display the stamps in these cases (eg. MacPreview) but most including Adobe Reader don't.

**Comment by ihipop** [comment]
@hhrutter 
 with my sample pdf file，I tried all pdf reader I  have know，none of them can display the Watermark on the second page
I think my case maybe different.

**Comment by hhrutter** [comment]
OK, then please open a new issue with the specific pdfcpu command you are using and attach your input file.
Thank you

**Comment by hhrutter** [comment]
This is fixed with the latest commit.
Please go install.
