### ISSUE TITLE
permissions: calculation

### ISSUE THREAD

**Issue by ihipop** [pdfcpu/pdfcpu#473]
* Your issue is based on the latest commit
YES
* State your OS and OS version
Linux

https://github.com/pdfcpu/pdfcpu/blob/11d755a41bcb605c55e2727ab7608a93cb889224/pkg/pdfcpu/configuration.go#L170-L171

I can only find 3 permission listed here 

https://github.com/pdfcpu/pdfcpu/blob/11d755a41bcb605c55e2727ab7608a93cb889224/pkg/pdfcpu/configuration.go#L46-L52

But there is more permission bit listed here 

https://pdfcpu.io/encrypt/perm_list.html#examples

How can I calc them myself ?

**Comment by hhrutter** [comment]
Hello!

Thanks for the tip! This is what you need:

<img width="718" alt="Screen Shot 2022-05-18 at 10 30 32 PM" src="https://user-images.githubusercontent.com/11322155/169150571-873fe2c9-bffe-4198-8d85-7ee626d141fc.png">

**Comment by ihipop** [comment]
according to this table

 `44` permits print and copy

according to this table

| Bit\POS |  12    | 11     |  10    |   9   |   8   | 7     |    6  |  5    | 4 | 3 | 2 | 1 | 0 |
| ------- | ---- | ---- | ---- | ---- | ---- | ---- | ---- | ---- | ---- | ---- | ---- | ------- | ------- |
| 44 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 1    | 0 | 1 | 1 | 0 | 0 |
| 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 |



so I should define `~44` as `-45`  to make the pdf copy and printable ?right?

I think it's very counterintuitive, why not we design the API like this?

```go
const (
	PermissionPrint                                  = 1 << 3
	PermissionModifyDocContent                       = 1 << 4
	PermissionCopyDocText                            = 1 << 5
	PermissionModifyTextAnnotationsOrInteractiveForm = 1 << 6
	PermissionModifyFillExistsForm                   = 1 << 9
)
```

and set permission like this `PermissionPrint | PermissionCopyDocText` ?

**Comment by hhrutter** [comment]
The example from the spec turns on bits 3 and 5: 1111 1111 1101 0100 = -44

When you count the bit positions you start with 1 (not with 0).

The example assumes security handler rev 2 so bits 9-12 are disregarded.
Bits 1 and 2 are not interpreted so you should get the same permissions with: 1111 1111 1101 0111 = -41
My guess is the the same applies to bits 7 and 8.

In order to calculate specific permissions you just turn on the corresponding bits which will get you a two's complement binary integer for which you define the corresponding negative integer value.

It's all explained in the screenshot above.

**Comment by sourcec0de** [comment]
I'm thinking of a solution, something like this.

```go
package pdfpermissions

type Flag int16

const (
	FlagPrint                                  Flag = 1 << (3 - 1)
	FlagModifyDocContent                       Flag = 1 << (4 - 1)
	FlagCopyDocText                            Flag = 1 << (5 - 1)
	FlagModifyTextAnnotationsOrInteractiveForm Flag = 1 << (6 - 1)
	FlagFillExistingForm                       Flag = 1 << (9 - 1)
	FlagExtractTextGraphicsAccessibility       Flag = 1 << (10 - 1)
	FlagAssembleDocument                       Flag = 1 << (11 - 1)
	FlagPrintHighQuality                       Flag = 1 << (12 - 1)

	FlagAllPermissionsEnabled  = Flag(-1)
	FlagAllPermissionsDisabled = Flag(-3901)
)

var (
	FlagReadOnly = EnablePermissions(
		FlagPrint,
		FlagCopyDocText,
		FlagExtractTextGraphicsAccessibility,
		FlagPrintHighQuality,
	)
)

// EnablePermissions starts with PermissionsNone and enables the specified ones.
func EnablePermissions(permissions ...Flag) Flag {
	result := FlagAllPermissionsDisabled
	for _, perm := range permissions {
		result |= perm
	}
	return result
}

```

The API usage would be something along these lines.
```go
config.Permissions = pdfpermissions.FlagReadOnly
config.Permissions = pdfpermissions.EnablePermissions(
  FlagCopyDocText,
  FlagModifyTextAnnotationsOrInteractiveForm,
)
```

**Comment by hhrutter** [comment]
Please make sure your valuable feedback gets also posted/appended to issue
#473
Thank you!

**Comment by hhrutter** [comment]
Please see the optimized `permissions` command of https://github.com/pdfcpu/pdfcpu/releases/tag/v0.6.0
