### ISSUE TITLE
validation: leaf node corrupted

### ISSUE THREAD

**Issue by ihipop** [pdfcpu/pdfcpu#474]
* Your issue is based on the latest commit
YES
* State your OS and OS version
Linux

[crash sample.pdf](https://github.com/pdfcpu/pdfcpu/files/8727937/crash.sample.pdf)

```
pdfcpu validate /tmp/crash\ sample.pdf 
validating(mode=relaxed) /tmp/crash sample.pdf ...
validation error (obj#:141): pdfcpu: validateNameTreeDictLimitsEntry: leaf node corrupted (firstKey: G1415412 vs ) (lastKey: G1415412 vs )
```

**this pdf is working well in any other pdf reader**

print the pdf via chrome to a new pdf file  fix the problem

**Comment by ihipop** [comment]
I turned off the validation to bypass the problem

**Comment by hhrutter** [comment]
OK but you know that turning off validation is not really the long term solution.
Most pdfcpu features rely on valid PDFs - It's a gamble really..
You probably will deal with a similar artifact sooner than later.
I'll put it in the pipeline.

**Comment by hhrutter** [comment]
This is interesting 👀 

Your file contains a `NameTree` with `Limits` containing indirect references yet the PDF spec defines the elements of the Limits array to be of type `String`:

<img width="809" alt="Screen Shot 2022-05-21 at 10 54 56 PM" src="https://user-images.githubusercontent.com/11322155/169668705-065c7265-f490-4ee5-a5b6-1e0a98cfe9d1.png">

**Comment by hhrutter** [comment]
This is fixed with the latest release.
