### ISSUE TITLE
stamp: the stamp/watermark does not show up in any PDF Viewer, case 2

### ISSUE THREAD

**Issue by ihipop** [pdfcpu/pdfcpu#475]
Related: https://github.com/pdfcpu/pdfcpu/issues/471

The case above will show watermark on some PDF reader

My case is different, I tried all pdf readers I have known，none of them can display the Watermark on the second page,the second page is cut from another pdf that also have the problem

Steps to reproduce:

Download sample file:

https://github.com/pdfcpu/pdfcpu/files/8726916/1.pdf

```bash
$pdfcpu validate 1.pdf 
validating(mode=relaxed) 1.pdf ...
validation ok
$pdfcpu stamp add -mode text -- "Watermark text" "sc:1" 1.pdf 1-out.pdf
writing 1-out.pdf...
```

[1-out.pdf](https://github.com/pdfcpu/pdfcpu/files/8749492/1-out.pdf)

**Comment by hhrutter** [comment]
What's the story of your input file 1.pdf.
It was last written by pdfcpu.
I need to know how you created this for analysis.

**Comment by ihipop** [comment]
> What's the story of your input file 1.pdf. It was last written by pdfcpu. I need to know how you created this for analysis.

I have a pdf that can not show to public, but also has the problem

I cut one page from the pdf ，delete all the content, leave it to a blank page,and add watermark by pdfcpu,it still not work

I add a blank page to the first， via other pdf editor，nd add watermark by pdfcpu, the added page works ,the previous page  still not

**Comment by ihipop** [comment]
I also find another pdf that can show to public which also has the problem

The whole PDF is too big,I cut the first page to share with you


This file is special, when with the desc of `sc:1 abs`, it  will not work
 remove the `abs` description, it works

```bash
// this works
pdfcpu stamp add -mode text -- "Watermark text" "sc:1" '2.pdf' 2-out.pdf
// this will not work
pdfcpu stamp add -mode text -- "Watermark text" "sc:1 abs" '2.pdf' 2-out.pdf

```

2.pdf is created by `iTextSharp 4.1.6 by 1T3XT`  [2.pdf](https://github.com/pdfcpu/pdfcpu/files/8749688/2.pdf)

**Comment by hhrutter** [comment]
OK - This sounds like some chaining of pdfcpu operations.

Do you have something like a general usecase?
Maybe I can tell you an easier way to achieve what you want.
Or is there some specific reason - maybe because of that particular one file - for your processing steps?

The scaling operator defaults to relative scaling (relative to page dimensions)

.. I need to look into this more.

**Comment by ihipop** [comment]
> OK - This sounds like some chaining of pdfcpu operations.
> 
> Do you have something like a general usecase? Maybe I can tell you an easier way to achieve what you want. Or is there some specific reason - maybe because of that particular one file - for your processing steps?
> 
> The scaling operator defaults to relative scaling (relative to page dimensions)
> 
> .. I need to look into this more.

I have some internal pdf files that must trace the reader's identity ,so a watermark with users id on this pdf file is nessary

the user identity info must  fill  the full dimension of pdf files  like this

![image](https://user-images.githubusercontent.com/423077/169705395-2f2a7b64-8328-4df2-9200-11e3b8410c01.png)


 so I repeat N times of waterwark text  to make them reach every edge of pdf ,and to keep the watermark display at fixed font size, `abs` is required

the `abs` issue only affect 2.pdf ,not the 1.pdf

**Comment by hhrutter** [comment]
Interesting usecase!

So how do you do that? 
Are you using a script that calls `pdfcpu stamp add -mode text` in a loop?
Or are you using the api and loop over `api.AddTextWatermarksFile`?

**Comment by ihipop** [comment]
> Interesting usecase!
> 
> So how do you do that? Are you using a script that calls `pdfcpu stamp add -mode text` in a loop? Or are you using the api and loop over `api.AddTextWatermarksFile`?
> 
> Another question: Are you adding these stamps (= watermark with ontop:true) just to the first page or to all pages?

- Q:  
  Are you adding these stamps (= watermark with ontop:true) just to the first page or to all pages?
A: 
   No, To all pages. and the command line  used by pdfcpu cmd with 1.pdf is pasted, same result.

- Q: 
   how do you do that?Are you using a script that calls pdfcpu stamp add -mode text in a loop?
Or are you using the api and loop over api.AddTextWatermarksFile?
A: 
    - when I test it with pdfcpu cmd, there is not need to  suite  the use-case ,just test if the watermark an be added to the pdf and display in the pdf reader
    - when comes to the use-case, I write some code the call the api ,this is the sample code,it just repeat the watermark, not affect the result that is not working for 1.pdf /2.pdf
    ```go
package test

import (
	"github.com/pdfcpu/pdfcpu/pkg/api"
	"github.com/pdfcpu/pdfcpu/pkg/font"
	"github.com/pdfcpu/pdfcpu/pkg/pdfcpu"
	"github.com/pdfcpu/pdfcpu/pkg/pdfcpu/validate"
	"io"
	"os"
	"path/filepath"
	"strconv"
	"testing"
)

var configuration = api.LoadConfiguration()
var tempDir = os.TempDir()
var tempFilePrefix = "pdf-watermark_temp_"

func TestApiWrite(t *testing.T) {
	var err error
	var text = "Watermark text"
	inFile := "/tmp/1.pdf"
	in, err := os.Open(inFile)
	if err != nil {
		t.Fatal(err)
	}
	outFile, err := textWaterMark(text, in)
	if err != nil {
		t.Fatal(err)
	}
	t.Log(outFile)
}

// hackWM temporary fix https://github.com/pdfcpu/pdfcpu/issues/469
func hackWM(y int) string {
	return "pos:tl,points:16,rot:8,sc:1 abs,off:0 " + strconv.Itoa(y) + ",al:l,op:0.2"
}
func textWaterMark(text string, in io.ReadSeeker) (outFile string, err error) {
	onTop := true
	desc := hackWM(0)

	if text == "" {
		text = "This is a watermark"
	}

	var wm *pdfcpu.Watermark
	wm, err = api.TextWatermark(text, desc, onTop, false, pdfcpu.POINTS)
	if err != nil {
		return
	}

	realFontSize := wm.ScaledFontSize
	if realFontSize <= 0 {
		realFontSize = wm.FontSize
	}
	lineHeight := font.LineHeight(wm.FontName, realFontSize)
	singleLineWidth := font.TextWidth(text, wm.FontName, realFontSize)
	targetLineWidth := singleLineWidth
	targetText := text
	_ = targetLineWidth
	_ = targetText
	var out *os.File
	out, err = os.CreateTemp(tempDir, tempFilePrefix+"out-*.pdf")
	if out != nil {
		outFile, _ = filepath.Abs(out.Name())
		defer out.Close()
	}
	if err != nil {
		return
	}

	lineSpace := int(lineHeight * 6)
	_ = lineSpace
	var ctxCpu *pdfcpu.Context
	ctxCpu, err = readValidateAndOptimize(in, configuration)
	if err != nil {
		return
	}
	_ = ctxCpu
	var dms []pdfcpu.Dim
	dms, err = ctxCpu.PageDims()
	if err != nil {
		return
	}

	var wmsSliceMap = map[int][]*pdfcpu.Watermark{}
	for k, dm := range dms {
		curPage := k + 1
		dy := 0
		//repeat the text to reach the edge
		for dm.Width >= targetLineWidth {
			targetText += ("    " + text)
			targetLineWidth = font.TextWidth(targetText, wm.FontName, realFontSize)
		}
		for float64(dy)*-1 < dm.Height {
			wm, err = api.TextWatermark(targetText, hackWM(dy), onTop, false, pdfcpu.POINTS)
			wmsSliceMap[curPage] = append(wmsSliceMap[curPage], wm)
			dy -= int(lineSpace + int(lineHeight))
		}
	}

	err = ctxCpu.AddWatermarksSliceMap(wmsSliceMap)
	if err != nil {
		return
	}

	err = api.WriteContext(ctxCpu, out)
	if err != nil {
		return
	}
	out.Sync()
	return
}

func readValidateAndOptimize(rs io.ReadSeeker, conf *pdfcpu.Configuration) (ctx *pdfcpu.Context, err error) {
	ctx, err = readAndValidate(rs, conf)
	if err != nil {
		return nil, err
	}

	if err = api.OptimizeContext(ctx); err != nil {
		return nil, err
	}

	return ctx, nil
}

func readAndValidate(rs io.ReadSeeker, conf *pdfcpu.Configuration) (ctx *pdfcpu.Context, err error) {
	if ctx, err = api.ReadContext(rs, conf); err != nil {
		return nil, err
	}

	if conf.ValidationMode == pdfcpu.ValidationNone {
		// Bypass validation
		return ctx, nil
	}

	if err = validate.XRefTable(ctx.XRefTable); err != nil {
		return nil, err
	}

	return ctx, nil
}

    ```

**Comment by hhrutter** [comment]
This is fixed with the latest commit.
Please go install.

**Comment by ihipop** [comment]
Thanks ,I can confirm it works
