### ISSUE TITLE
stamp: problem with absolute scaling

### ISSUE THREAD

**Issue by khuuthanh96** [pdfcpu/pdfcpu#478]
The case above just occurs to some PDF files were generated by **Adobe PDF Library 10.0** or **Adobe PDF Library 22.1.149**.

Watermark or stamp get cut off in half with sc:0.5 rel and **totally disappear when I set sc with abs option**.

* Your issue is based on the latest commit - TRUE
<img width="205" alt="Screen Shot 2022-05-24 at 09 26 20" src="https://user-images.githubusercontent.com/32768121/169936100-07a75956-dab4-4b4a-b31a-d16918762a5d.png">

* State your OS and OS version
macOS Monterey version 12.3

* When reporting a problem with a specific PDF input file please avoid stating the organization responsible for the PDFWriter - just refer to the *PDFWriter*
[sample-error-file](https://github.com/pdfcpu/pdfcpu/files/8759128/01r_49948427.pdf)

Steps to reproduce:
*display with sc: 1 rel
```
 pdfcpu watermark add -m text -- "custom-field-1" "rot:0,fillcolor:#FF0000,sc:1 rel" 01r_49948427.pdf 111-01r_49948427.pdf
```
<img width="1108" alt="Screen Shot 2022-05-24 at 09 30 07" src="https://user-images.githubusercontent.com/32768121/169936473-79972174-534a-4962-bd74-ca7be202650a.png">

*display in half with sc: 0.5 rel
```
 pdfcpu watermark add -m text -- "custom-field-1" "rot:0,fillcolor:#FF0000,sc:0.5 rel" 01r_49948427.pdf 111-01r_49948427.pdf
```
<img width="1115" alt="Screen Shot 2022-05-24 at 09 34 19" src="https://user-images.githubusercontent.com/32768121/169936933-17557478-811b-490e-9ef5-7a6592daf856.png">

**Comment by hhrutter** [comment]
Thanks for reporting this!
This is related to #475

**Comment by hhrutter** [comment]
This is fixed with the latest commit.
Please go install.

**Comment by khuuthanh96** [comment]
I tested, It's work ❤️ 
Thanks so much
