### ISSUE TITLE
changeUserPassword: indRefToObject: input argument is nil

### ISSUE THREAD

**Issue by ananthstory** [pdfcpu/pdfcpu#479]
### api.ChangeUserPasswordFile() return pdfcpu: indRefToObject: input argument is nil Error message
Please refer following code which return above mentioned issue 

```
import(
	pdfcpuapi "github.com/pdfcpu/pdfcpu/pkg/api"
	pdfcpu "github.com/pdfcpu/pdfcpu/pkg/pdfcpu"
)
	conf := pdfcpu.NewAESConfiguration("upw", "opw", 256)
	err := pdfcpuapi.ChangeUserPasswordFile("test.pdf", "test1.pdf", "", "password123", conf)
	if err != nil {
		log.Fatalf("error : %v", err)
	}

```
## Output :
`error : pdfcpu: indRefToObject: input argument is nil`

## Reason : 
_value of ctx.Encrypt is nil here_ 

## Solution:
**File**: github.com/pdfcpu/pdfcpu/pkg/pdfcpu/write.go
**Function**: handleEncryption()
Add 
```
if err := setupEncryption(ctx); err != nil {
	return err
}
```
the function should be like this,
```
func handleEncryption(ctx *Context) error {

	if ctx.Cmd == ENCRYPT || ctx.Cmd == DECRYPT {

		if ctx.Cmd == DECRYPT {

			// Remove encryption.
			ctx.EncKey = nil

		} else {

			if err := setupEncryption(ctx); err != nil {
				return err
			}

			alg := "RC4"
			if ctx.EncryptUsingAES {
				alg = "AES"
			}
			log.CLI.Printf("using %s-%d\n", alg, ctx.EncryptKeyLength)
		}

	} else if ctx.UserPWNew != nil || ctx.OwnerPWNew != nil || ctx.Cmd == SETPERMISSIONS {

		// Set Encrypt for context
		if err := setupEncryption(ctx); err != nil {
			return err
		}

		if err := updateEncryption(ctx); err != nil {
			return err
		}

	}

	// write xrefstream if using xrefstream only.
	if ctx.Encrypt != nil && ctx.EncKey != nil && !ctx.Read.UsingXRefStreams {
		ctx.WriteObjectStream = false
		ctx.WriteXRefStream = false
	}

	return nil
}
```

**Comment by hhrutter** [comment]
Are you trying to change the password of an unecrypted file?
Please post the stacktrace of your code snippet at the top.

**Comment by ananthstory** [comment]
Yes, I am trying to set the password of the PDF file

**Comment by ananthstory** [comment]
@hhrutter - it is very urgent for me

**Comment by hhrutter** [comment]
Hello!

My task pipeline is swamped and I am not aware of any contractual obligations with you. 

This is open source development where developers with a full time job stay up until the middle of the night to fix bugs in their spare time.

You are also welcome to  consider sponsoring OSS projects like this if you depend on them.

Thank you for using pdfcpu 💚

**Comment by ananthstory** [comment]
ERROR: Permission to pdfcpu/pdfcpu.git denied to ananthstory.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

**Comment by hhrutter** [comment]
Hello!

What is the issue you are reporting?
If this is something different than #479 please create a separate issue.

Thank you for using pdfcpu 💚

**Comment by hhrutter** [comment]
Generally the first step is to encrypt your file setting the owner password and optionally a user password.
After that you may change either one of the passwords.

I still need to check your sample code which should return an error.
This smells like a bug.

**Comment by hhrutter** [comment]
Hello!

The latest commit outputs a warning if you want to change a password for an unencrypted file.

The *encrypt* command sets up password protection for your file: 
```
Go-> pdfcpu help encrypt
usage: pdfcpu encrypt [-m(ode) rc4|aes] [-key 40|128|256] [-perm none|print|all] [-upw userpw] -opw ownerpw inFile [outFile]

common flags: -v(erbose)  ... turn on logging
              -vv         ... verbose logging
              -q(uiet)    ... disable output
              -c(onf)     ... set or disable config dir: $path|disable
              -opw        ... owner password
              -upw        ... user password
              -u(nit)     ... display unit: po(ints) ... points
                                            in(ches) ... inches
                                                  cm ... centimetres
                                                  mm ... millimetres

Setup password protection based on user and owner password.

      mode ... algorithm (default=aes)
       key ... key length in bits (default=256)
      perm ... user access permissions
    inFile ... input pdf file
   outFile ... output pdf file
```
You need to provide at least the `owner password` in order to encrypt the file.
The `owner password` is also known as the permission password.

If you also want to setup a password to open your document then you need to supply a `user password` as well.

Once your file is encrypted you may use `changeopw` and `changeupw` or the respective api calls to change your passwords.
