### ISSUE TITLE
validation error (obj#:8): validateNames: unknown name tree name: Type

### ISSUE THREAD

**Issue by meerkat-mary** [pdfcpu/pdfcpu#485]
Hi @hhrutter,

We're facing an issue where pdf validation is unsuccessful due to a 'validation error (obj#:8): validateNames: unknown name tree name: Type' error. 

We're able to open and view this file successfully in Mac Preview and Acrobat Reader on Windows 7/10 and Mac OS Mojave using the latest commit (0ce7ef0eb604)

[output.log](https://github.com/pdfcpu/pdfcpu/files/8845844/output.log)

```
STATS: 2022/06/06 17:12:39 Original:
STATS: 2022/06/06 17:12:39 File size            : 56 KB (57482 bytes)
STATS: 2022/06/06 17:12:39 Total binary data    : 37 KB (37629 bytes) 65.5%
STATS: 2022/06/06 17:12:39 Total other data     : 19 KB (19853 bytes) 34.5%

Fatal: validateNames: unknown name tree name: Type

github.com/pdfcpu/pdfcpu/pkg/pdfcpu/validate.validateNames
	github.com/pdfcpu/pdfcpu/pkg/pdfcpu/validate/xReftable.go:132
github.com/pdfcpu/pdfcpu/pkg/pdfcpu/validate.validateRootObject
	github.com/pdfcpu/pdfcpu/pkg/pdfcpu/validate/xReftable.go:986
github.com/pdfcpu/pdfcpu/pkg/pdfcpu/validate.XRefTable
	github.com/pdfcpu/pdfcpu/pkg/pdfcpu/validate/xReftable.go:40
```

Please let me know if you'd like to see the original pdf file (as it contains sensitive PII information, I can email it)

Thank you!
Mary

**Comment by meerkat-mary** [comment]
Thanks @hhrutter, much appreciated 😀

**Comment by hhrutter** [comment]
This should be fixed with latest commit.

**Comment by meerkat-mary** [comment]
Awesome, I've just verified and it works - thank you for the quick update! ⭐️

**Comment by hhrutter** [comment]
You got it 👍
