### ISSUE TITLE
encryption & permissions

### ISSUE THREAD

**Issue by minchenzz** [pdfcpu/pdfcpu#486]
```
package main

import (
	"fmt"

	"github.com/pdfcpu/pdfcpu/pkg/cli"
	"github.com/pdfcpu/pdfcpu/pkg/pdfcpu"
)

func main() {
	conf := pdfcpu.NewDefaultConfiguration()
	conf.OwnerPW = "123"
	conf.UserPW = "123"
	conf.Permissions = pdfcpu.PermissionsNone

	cmd := cli.EncryptCommand("./data/test.pdf", "./data/testEncrypt.pdf", conf)
	fmt.Println(cli.Process(cmd))
}
```

pdfcpu v0.3.13
go v1.18

This can still be printed and copied.

**Comment by hhrutter** [comment]
Hello!

For encrypted files you need to enter the owner password to bypass set permissions.
As long as you don't know or don't enter the owner password set permissions apply.

Either don't set a user password for opening the ecrypted file with set permissions or share the user password only.

Thank you for using pdfcpu 💚

**Comment by hhrutter** [comment]
Closed due to inactivity.
