### ISSUE TITLE
could not extract images

### ISSUE THREAD

**Issue by rocksun** [pdfcpu/pdfcpu#488]
The code is :

```
func main() {
	err := pdfcpu.ExtractImagesFile("../testfiles/removed.pdf", "../testfiles/images", []string{"1", "2"}, nil)
	fmt.Println(err)
}
```
I use the version is 5d37c4925506.

It could not extract images at page 2.

[removed.pdf](https://github.com/pdfcpu/pdfcpu/files/8935776/removed.pdf)

**Comment by hhrutter** [comment]
This is fixed with latest commit!

Please consider becoming a pdfcpu sponsor!
Thank you for using pdfcpu  💚
