### ISSUE TITLE
validateColorSpaceArray: undefined color space: DeviceCMYK

### ISSUE THREAD

**Issue by zwq000** [pdfcpu/pdfcpu#490]
exec pdfcpu command error info 
**pdfcpu: validateColorSpaceArray: undefined color space: DeviceCMYK**

**Comment by hhrutter** [comment]
Hello!

Please share a sample file and I take a look.

Thank you for using pdfcpu 💚

**Comment by hhrutter** [comment]
Closed due to inactivity.

**Comment by ahaooahaz** [comment]
I had the same problem, i will send an email with the file to you.

**Comment by hhrutter** [comment]
I just discovered this file in my spam folder...
Thx

**Comment by hhrutter** [comment]
Fixed with the latest commit!
