### ISSUE TITLE
Page Resizing

### ISSUE THREAD

**Issue by gedw99** [pdfcpu/pdfcpu#491]
I need to sub-divide a PDF page(s) into smaller pages so you that i can print them on small form printers.

Say you have a A1 PDF, but need to print it with a A4 Printer. 

Can anyone think of a combination of commands that can achieve this ?

**Comment by hhrutter** [comment]
Hello!

The "scale to fit" option in the printer dialog does not suffice in your case?
A1 to Ax should not produce artifacts.

**Comment by hhrutter** [comment]
The next release will feature a `cut`command.

**Comment by hhrutter** [comment]
Fixed => v0.4.1
