### ISSUE TITLE
Custom Page Size

### ISSUE THREAD

**Issue by zambetti** [pdfcpu/pdfcpu#492]
Hello and compliments on a lovely project.

After reading the documentation, and experimenting with 'crop' and the 'boxes' commands, I cannot find a way to fit the MediaBox to an offset CropBox, it this possible?

With a PDF that has an offset CropBox (after using the 'crop' command)...

MediaBox (points) (0.00, 0.00, 56.88, 56.88) w=56.88 h=56.88 ar=1.00
CropBox (points) (0.00, 0.19, 56.69, 56.88) w=56.69 h=56.69 ar=1.00
TrimBox (points) (0.00, 0.19, 56.69, 56.88) w=56.69 h=56.69 ar=1.00 (default)
BleedBox (points) (0.00, 0.19, 56.69, 56.88) w=56.69 h=56.69 ar=1.00 (default)
ArtBox (points) (0.00, 0.19, 56.69, 56.88) w=56.69 h=56.69 ar=1.00 (default)

Is there any way to transform it into the following without clipping artwork?

MediaBox (points) (0.00, 0.00, 56.69, 56.69) w=56.69 h=56.69 ar=1.00
CropBox (points) (0.00, 0.00, 56.69, 56.69) w=56.69 h=56.69 ar=1.00
TrimBox (points) (0.00, 0.00, 56.69, 56.69) w=56.69 h=56.69 ar=1.00 (default)
BleedBox (points) (0.00, 0.00, 56.69, 56.69) w=56.69 h=56.69 ar=1.00 (default)
ArtBox (points) (0.00, 0.00, 56.69, 56.69) w=56.69 h=56.69 ar=1.00 (default)

I've found that it is possible to set the MediaBox by using the 'add' command (bit strange to use 'add' rather than 'set', but it works)...
pdfcpu boxes add -u mm "m:[0 0 20 20]"

But with an offset CropBox, this does not make sense to do.

As an idea, maybe a "fit" option could be added to refit any given box?

pdfcpu boxes add "c:fit" // Sets CropBox dimensions to MediaBox dimensions
pdfcpu boxes add "t:fit" // Sets TrimBox dimensions to CropBox dimensions
pdfcpu boxes add "b:fit" // Sets BleedBox dimensions to CropBox dimensions
pdfcpu boxes add "a:fit" // Sets ArtBox dimensions to CropBox dimensions
pdfcpu boxes add "m:fit" // Translates content by CropBox offset, sets CropBox position to (0,0), sets MediaBox dimensions to CropBox dimensions

**Comment by hhrutter** [comment]
Hello!

The cropbox is always there and defaults to the MediaBox.
If you setup a custom CropBox eg. within the MediaBox then you apply some clipping to your MediaBox.
Basically you define your visible region of the MediaBox.

Now, why would you want to modify the MediaBox afterwards?
What's your specific usecase for this?

Thank you for using pdfcpu 💚

**Comment by hhrutter** [comment]
Understood, we can do that.

**Comment by alvaro-canepa** [comment]
Hello and thanks for that great project!

I thing this is the same if you crop a pdf and then convert to png image. 

```bash
# PDF size of 595 x 864
pdfcpu crop -- "[0 500 595 864]" in.pdf out.pdf
pdftoppm -png -f 1 -l 1 out.pdf out
```
Files `in.pdf` and `out.pdf` has the same file size (in bytes)   
File `out.png` has with/height of `in.pdf` instead of `out.pdf`

**Comment by hhrutter** [comment]
You can set your boxes for individual pages via `pdfcpu boxes add` to anything you want - that's pure mechanics.
Interpretation of the result is a different story and the best source for this is still the PDF spec.

**Comment by hhrutter** [comment]
Closed due to inactivity.
