### ISSUE TITLE
Error decrypting: decryptAESBytes: Ciphertext not a multiple of block size

### ISSUE THREAD

**Issue by hueyy** [pdfcpu/pdfcpu#493]
When trying to decrypt some PDF files, e.g. [this one](https://journalsonline.academypublishing.org.sg/Journals/Singapore-Academy-of-Law-Journal/e-Archive/ctl/eFirstSALPDFJournalView/mid/495/ArticleId/1692/Citation/JournalsOnlinePDF), pdfcpu throws the following error:

> dereferenceObject: problem dereferencing object 202: pdfcpu: decryptAESBytes: Ciphertext not a multiple of block size

I believe the problem is in 8b9e92eaf592b6fb08fcbe184f83e35716dc7a4e. The issue does not occur with the preceding commit (11d755a41bcb605c55e2727ab7608a93cb889224).

For reference, I ran the following command:

```
pdfcpu decrypt input.pdf output.pdf
```

Please ensure the following:

- [x] Your issue is based on the latest commit
- [x] State your OS and OS version: Ubuntu 20.04 LTS
- [x] When reporting a problem with a specific PDF input file please avoid stating the organization responsible for the PDFWriter - just refer to the *PDFWriter*

**Comment by hhrutter** [comment]
Thank you for reporting this!

**Comment by hhrutter** [comment]
This is fixed with latest commit.
Please report back any issues.
