### ISSUE TITLE
missing required resource subdict: ColorSpace

### ISSUE THREAD

**Issue by wrzfeijianshen** [pdfcpu/pdfcpu#494]
OS version : win10
 .\pdfcpu.exe version
pdfcpu: v0.3.13 dev

hi, thanks.
How do you resolve or ignore this error and merge successfully? Merge a file from one page to a location on another
error : 
```
PS D:\code\src\pdfcpu\cmd\pdfcpu> ./pdfcpu.exe stamp add -mode pdf -- test/cut_20.pdf  'pos:tl, off:80 20 , sc:1.0 abs, rot: 0.0, op:1, mo:0'  test/20.pdf test/out20.pdf
writing test/out20.pdf...
pdfcpu: page 1: missing required resource subdict: ColorSpace
PageResourceNames:
ColorSpace: G
ExtGState: GS1
Font: F8, F77, F6, F78, F3, F11, F12, F79, F80, F26
Pattern:
Properties:
Shading:
XObject: Im2, Im1
```

[test.zip](https://github.com/pdfcpu/pdfcpu/files/9028321/test.zip)

**Comment by wrzfeijianshen** [comment]
I tried to change the code and it looks like the file is ok after execution. Although I do not know what problems will exist after modification, I look forward to your performance

```
func consolidateResourceSubDict(d Dict, key string, prn PageResourceNames, pageNr int) error {
	o := d[key]
	if o == nil {
		if prn.HasResources(key) {
			// return errors.Errorf("pdfcpu: page %d: missing required resource subdict: %s\n%s", pageNr, key, prn)
			return nil
		}
```

**Comment by wrzfeijianshen** [comment]
I tried to change the code and it looks like the file is ok after execution. Although I do not know what problems will exist after modification, I look forward to your performance

```
func consolidateResourceSubDict(d Dict, key string, prn PageResourceNames, pageNr int) error {
	o := d[key]
	if o == nil {
		if prn.HasResources(key) {
			// return errors.Errorf("pdfcpu: page %d: missing required resource subdict: %s\n%s", pageNr, key, prn)
			return nil
		}
```

**Comment by hhrutter** [comment]
Thank you for reporting this!

**Comment by hhrutter** [comment]
This is fixed with latest commit.

**Comment by zollybig** [comment]
win 10
github.com/pdfcpu/pdfcpu v0.8.0

src:
**err := api.CollectFile(pdfToProcess, SplitByFormatFileName(strings.TrimSuffix(pdfToProcess, filepath.Ext(pdfToProcess)),  fmtName, &fmtList), getPageListForFormat(&fmtList), nil)**

some pages works well, but on some pages I got 
_pdfcpu: page 28: missing required resource subdict: ColorSpace
PageResourceNames:
Font: C2_0
Pattern: 
Properties: 
Shading: 
XObject: Im0, Fm0
ColorSpace: 
ExtGState:_ 
I tried to move pages inside file (it was page 15, now 28), resave file from Adobe Acrobat, save with optimisation - with same result. Do You have a solution? Thanks
