### ISSUE TITLE
pdfcpu install error

### ISSUE THREAD

**Issue by srabieb** [pdfcpu/pdfcpu#495]
Hi, I get this error when installing via Go modules.
How to fix it?

go version go1.17.1 linux/amd64
WSL2 Ubuntu 20.04.4 LTS

![image](https://user-images.githubusercontent.com/26784284/177083885-3a4e19bb-7f1d-4b08-9fe7-835c9c739ca2.png)

**Comment by hhrutter** [comment]
Please double check that you have installed golang version >= 1.16

**Comment by srabieb** [comment]
> Please double check that you have installed golang version >= 1.16

![image](https://user-images.githubusercontent.com/26784284/177148814-5172cbbe-1709-4439-9b2a-47efdea68d11.png)

**Comment by hhrutter** [comment]
AFAIK this error indicates that the golang version used to install is too old for using `embed`.
There may be multiple go versions on your machine or some go.mod file requiring an older version.
I would give it a try with an empty container/machine then install go and immediately pdfcpu.
Sorry to say this, but I don't think I can help you with this.

**Comment by srabieb** [comment]
Thanks for the answer, I have another version installed on sudo.
