### ISSUE TITLE
validateAcroForm: missing required entry "Fields"

### ISSUE THREAD

**Issue by DeltaLaboratory** [pdfcpu/pdfcpu#496]
First of all, thank you very much for making this very nice library!
When I tried to decrypt the PDF file, this error appeared.
I am using pdfcpu go api (v0.3.13), go 1.18 and Ubuntu 20.04.
The editor was Adobe InDesign CC 14.0 (Windows)

the code was :
`api.Decrypt(bytes.NewReader(data), &out, pdfcpu.NewAESConfiguration(key, "", 128))`
and this code return error : `pdfcpu: validateAcroForm: missing required entry "Fields"`

When I tried to open this file with an edge browser, it opened well with no errors.

**Comment by hhrutter** [comment]
Hello!
Go get the latest commit and then go install and you should be good to go!
Thank you for using pdfcpu 💚

**Comment by DeltaLaboratory** [comment]
It returned another error, but original error seems solved!
I will create another seperated issue!
Thanks!
