### ISSUE TITLE
Validation Error: Fatal: dict=annotDict required entry=Subtype missing

### ISSUE THREAD

**Issue by meerkat-mary** [pdfcpu/pdfcpu#497]
Hi @hhrutter ,

We're facing an issue where pdf validation is unsuccessful due to a 'Fatal: dict=annotDict required entry=Subtype missing' error for two of our PDFs

We're able to open and view these files successfully in Mac Preview and Acrobat Reader on Windows 7/10 and Mac OS Mojave using the latest commit.

[output_1.log](https://github.com/pdfcpu/pdfcpu/files/9046754/output_1.log)
[output_2.log](https://github.com/pdfcpu/pdfcpu/files/9046755/output_2.log)

Please let me know if you'd like to see the original pdf file (as it contains sensitive PII information, I can email it)

Thank you!
Mary

**Comment by hhrutter** [comment]
I take a look..
