### ISSUE TITLE
nup merge single image 

### ISSUE THREAD

**Issue by rpdg** [pdfcpu/pdfcpu#501]
I'm trying to merge images into one pdf, it puts image twice while only one image exists.
```bash
pdfcpu nup -- "bo:off" out.pdf 2 in.jpg
```

OS :  windows 10 64bit

```bash
> pdfcpu version
pdfcpu: 0.3.13
build : 2021-11-30T15:53:00Z
commit: e89570a
```

**Comment by hhrutter** [comment]
Hello!

This behavior is intentionally.

What is your usecase?

**Comment by rpdg** [comment]
Thanks for reply.
In my usecase is trying to marge bank receipts into a pdf file by date, so it's a bit confusing to appear two times of one receipt. My temporary solution is to check the quantity first, then `pdfcpu nup out.pdf 1 in.jpg`

**Comment by hhrutter** [comment]
Hello!

This is intended behavior.

If you feed *nup* with image files pdfcpu creates outFile for a given paper size and arrange imageFiles on pages in a grid like fashion. For a single image file create a single page PDF file and fill the grid with copies of the image.
The reason for the special treatment for single image files is a printing usecase for graphics.

**Comment by rpdg** [comment]
Thanks @hhrutter
