### ISSUE TITLE
api: How to use v(erbose), vv in API.

### ISSUE THREAD

**Issue by KrasnovDaniil1** [pdfcpu/pdfcpu#503]
I couldn't find how to get detailed information about a file, where using Common Flags v(erbose), vv. Can you explain how to use the common flags in the API.

**Comment by hhrutter** [comment]
Hello!

This may help: https://pdfcpu.io/getting_started/common_flags

If not please go ahead and further explain your usecase.

**Comment by KrasnovDaniil1** [comment]
Hello. I have read this documentation. I know how to use it in CLI, but I don't know how to use it in API. Is there a function in the API that shows the same information as -v / -vv common flags ?

**Comment by hhrutter** [comment]
-v and -vv are just CLI flags that correspond to typical logger setups for *verbose* and *very verbose*.
You are free to play around and setup all your loggers. Check out log.go.
