### ISSUE TITLE
PDF Deference issue when Validation mode is set to None

### ISSUE THREAD

**Issue by joshpauline** [pdfcpu/pdfcpu#504]
I am trying to get the page Dimensions of a document using the `api.PageDims()` function and even when I set the validation mode to ValidationNone I am getting a duplicate key error. 

I have traced the function to this

```
func ParseObject(ctx *Context, offset int64, objNr, genNr int) (Object, error) {

	log.Read.Printf("ParseObject: begin, obj#%d, offset:%d\n", objNr, offset)

	obj, endInd, streamInd, streamOffset, err := object(ctx, offset, objNr, genNr)
	if err != nil {
		return nil, err
	}

	switch o := obj.(type) {

	case Dict:
		d, err := dict(ctx, o, objNr, genNr, endInd, streamInd)
		if err != nil || d != nil {
			// Dict
			return d, err
		}
		// StreamDict.
		return streamDictForObject(ctx, o, objNr, streamInd, streamOffset, offset)

	case Array:
		if ctx.EncKey != nil {
			if _, err = decryptDeepObject(o, objNr, genNr, ctx.EncKey, ctx.AES4Strings, ctx.E.R); err != nil {
				return nil, err
			}
		}
		return o, nil

	case StringLiteral:
		if ctx.EncKey != nil {
			bb, err := decryptString(o.Value(), objNr, genNr, ctx.EncKey, ctx.AES4Strings, ctx.E.R)
			if err != nil {
				return nil, err
			}
			return NewHexLiteral(bb), nil
		}
		return o, nil

	case HexLiteral:
		if ctx.EncKey != nil {
			bb, err := decryptHexLiteral(o, objNr, genNr, ctx.EncKey, ctx.AES4Strings, ctx.E.R)
			if err != nil {
				return nil, err
			}
			return NewHexLiteral(bb), nil
		}
		return o, nil

	default:
		return o, nil
	}
}

```

the pointer to conf is not being passed in or used in this function. so it is not being able to parse the document in question

**Comment by hhrutter** [comment]
Hi there,
Make sure you work is based on the latest commit.
In any case I would need to see a stacktrace at least.

**Comment by joshpauline** [comment]
I am using the api at the most recent version 

`	github.com/pdfcpu/pdfcpu v0.3.13
`


this is the function which leads to the error when calling `api.PageDims`

```
func GetPageHeight(file *[]byte) (*float64, error) {

	buf := bytes.NewReader(*file)
	conf := api.LoadConfiguration()

	conf.ValidationMode = pdfcpu.ValidationNone

	heights, err := api.PageDims(buf, conf)

	if err != nil {
		return nil, err
	}

	for _, page := range heights {
		return &page.Height, nil

	}

	return nil, nil
}

```

this is the error that my API logs produce 

```
{
    "errorMessage": "dereferenceObject: problem dereferencing object 43: pdfcpu: parse: duplicate key",
    "errorType": "withStack"
}

```

I will try to get a stack trace for you in the mean time

**Comment by vinser** [comment]
`github.com/pdfcpu/pdfcpu v0.3.13` is not the **latest commit**. You may check it by writing `github.com/pdfcpu/pdfcpu latest` in go.mod
May be it will help

**Comment by joshpauline** [comment]
@vinser thank you for the tip, I tried this and the issue is still the same. I can see the conf is not being handled in the master branch for the PageDim function when ParseObject function is called within the Read function

**Comment by joshpauline** [comment]
https://github.com/pdfcpu/pdfcpu/blob/a02156691061fee8247486e4733d11549cbb29ac/pkg/pdfcpu/read.go#L2558

Here is the dereference function, you can see that the configuration is not being used

**Comment by joshpauline** [comment]
@hhrutter @vinser actually that did fix the issue but my backend was being cached and was still using the other version. Thank you for your help!
