### ISSUE TITLE
Parsable Output

### ISSUE THREAD

**Issue by mbrevda** [pdfcpu/pdfcpu#506]
Is there an option to have output is json (or csv/anything easily parsable)? Would be great for when calling programmatically from other languages.

**Comment by hhrutter** [comment]
Sorry I don't understand your question.
Please be specific and layout your usecase.

**Comment by mbrevda** [comment]
The use case is simplifing parsing the output of a command. Here's what it might look like:

Instead of the usual output, `pdfcpu info --json file` might return:
```
{
  "PDFversion": "1.6",
  "Pagecount": "2",
  "Pagesize": "595.32 x 841.92 points"
   ...
}
```

the spaces can even be kept in the key names making it simpler to translate to json.

**Comment by mbrevda** [comment]
Thanks!!
