### ISSUE TITLE
Validation error "dict=fdDict entry=Lang: unsupported in version 1.3"

### ISSUE THREAD

**Issue by adamkral12** [pdfcpu/pdfcpu#511]
Hi, first of all, thank you for developing and maintaining this tool 👍 

I've come across a validation error in one of PDF files which got into our system.

Here's the stack trace from `pdfcpu validate -vv pdf_error.pdf`
[output.txt](https://github.com/pdfcpu/pdfcpu/files/9462408/output.txt)
I am on commit bfaf786e1825

Could you check if the validation can be relaxed as in other similar cases?
Thanks

**Comment by hhrutter** [comment]
Hi there!
Please install and test  your file using the latest commit and report back if your issue persists.
Thank you!

**Comment by adamkral12** [comment]
Hi, this is happening also on the latest commit (a02156691061fee8247486e4733d11549cbb29ac)

**Comment by adamkral12** [comment]
Hi @hhrutter, so do you have any suggestion on how to follow up here? :)

**Comment by hhrutter** [comment]
Relaxed validation will be extended with a fix on the upcoming release.
Thank you for using pdfcpu 💚

**Comment by hhrutter** [comment]
This should be fixed with the latest commit!
