### ISSUE TITLE
Remove annotations by type

### ISSUE THREAD

**Issue by afparsons** [pdfcpu/pdfcpu#515]
Overall, great work!

Removing annotations is easy enough _while attending the CLI session_:

```shell
$ pdfcpu annotations list <filepath>
```
> . . . take note of the object numbers . . .

```shell
$ pdfcpu annotations remove <filepath> <space-delimited integers>
```

But what if I don't know the object numbers and wish to include the CLI invocation in a shell script? I could try to parse the output from `pdfcpu annotations list <filepath>`, but as far as I can tell, there's no option to output JSON or XML, making the parsing of the text table(s) non-trivial.

It would be nice to simply pass an entire category to `remove`. For example:

```shell
# removes all popup annotations
$ pdfcpu annotations remove <filepath> popup

# removes all text annotations
$ pdfcpu annotations remove <filepath> text

# removes all link annotations
$ pdfcpu annotations remove <filepath> link

# remove multiple categories at once
$ pdfcpu annotations remove <filepath> popup text
```

Thank you for considering this small convenience feature.

**Comment by hhrutter** [comment]
Great suggestion!

Yes we can do it, the tricky part is categorizing all annotation types in a user friendly way.
I'll put that into the pipeline.

**Comment by afparsons** [comment]
The other option, as I alluded to, is to provide a `-json` option for all commands (not only for annotations, but of course, only where relevant). Such a flag would force the command to output a JSON-formatted string.

Doing so would shift some of the categorization responsibility to the user. If a user knew approximately what they wanted to delete, then this would allow the user to easily parse and find out which object numbers they needed to pass to `annotations remove`.

(Unless my alternative suggestion isn't idiomatic Go; this is the first Go project I've ever touched so I'm not sure what sets of behaviors users and programmers expect)

**Comment by hhrutter** [comment]
👍  point taken
