### ISSUE TITLE
cli: poster cmd with optional glue area

### ISSUE THREAD

**Issue by gedw99** [pdfcpu/pdfcpu#517]
I am an architect and lots of different software produces PDF's.

But I only have a A4 Laser printer and so i want to take a PDF and split it into 4 so that i can simulate having a A3 printer.
I think just glue the pages together and i have a A3 print that is legible. 

Anyone know what incarnation i need on the CLi for that ?

**Comment by hhrutter** [comment]
Hi there!

Please take a look at #491 and #363 .

We could also add a *poster* command, eg: `pdfcpu poster in.pdf 2 2`
Assuming an A3 in.pdf this would generate 4 A4 single page PDFs.

**Comment by gedw99** [comment]
Hey @hhrutter thank you for such a quick response.

Your proposed ```poster```command sounds like it will do what i need.

Could we eventually try to make it parametric.  When me and the scientists i work with have to Print a A1, we sometimes print to A3 or A4 and glue them together.  It would be really cool.

Regarding https://github.com/pdfcpu/pdfcpu/issues/491, I ried just now and it makes no difference. It registers that its A3 and scale it to 68%. But thats not helping.

Regards https://github.com/pdfcpu/pdfcpu/issues/363, I also think the ability to rotate is also needed.

I was also wondering if later we can add some sort of annotations later, to help with glueing. Its def a "nice to try later" thing though... 

Please let me know when you want to keep at code or test the code.

**Comment by hhrutter** [comment]
👍 
I put the *poster* command in the pipeline then.
Thx for using pdfcpu 💚

**Comment by gedw99** [comment]
Thank you so much

**Comment by hhrutter** [comment]
The next release will feature the `cut` command which will take care of this.

**Comment by hhrutter** [comment]
Fixed - v0.4.1 is for you!
