### ISSUE TITLE
dereferenceObject: problem dereferencing object 2

### ISSUE THREAD

**Issue by SahaPratik6267** [pdfcpu/pdfcpu#519]
* version 0.3.13
* the project is running in docker container on golang alpine image.

I have implemented the merge function which works for all the pdf i tried except one that i am trying now.

workflow:
1. first pdf is a 1 page pdf i am creating using maroto pdf library.
2. second pdf is uploaded by the user
3. Merge both pdf with code given below

merge code: 
func mergePDF(pdf1, pdf2 []byte) (*bytes.Buffer, error) {
	var rslist []io.ReadSeeker
	rs1 := io.ReadSeeker(bytes.NewReader(pdf1))
	rs2 := io.ReadSeeker(bytes.NewReader(pdf2))

	rslist = append(rslist, rs1, rs2)
	buf := &bytes.Buffer{}
	err := pdfcpu.Merge(rslist, buf, nil)
	if err != nil {
		return bytes.NewBuffer(nil), fmt.Errorf("error in merging pdf files: %w", err)
	}
	return buf, nil
}

with the pdf i am trying I am getting this error: dereferenceObject: problem dereferencing object 2

Please let me know if you can give me more info about this error.

Kind Regards
Pratik

**Comment by hhrutter** [comment]
Hello!

Firstly before merging please make sure your PDF passes validation : `pdfcpu val test.pdf`

**Comment by SahaPratik6267** [comment]
Yes the second pdf is showing the error during validation. just to check in installed pdfcpu in different directory and ran the validation in cmd,

pdfcpu validate test.pdf
validating(mode=relaxed) test.pdf ...
validation ok

Not sure why in golang project its showing the error.  Any idea how i can debug?

**Comment by hhrutter** [comment]
I need to see a stacktrace and then maybe I can help you.
Thank you!

**Comment by hhrutter** [comment]
Hi there!
Did you check out the latest commit?

**Comment by rmhofmann** [comment]
I think so - i ran `brew install pdfcpu` just this morning, so it should be the latest commit (is there an easy way to confirm?)

**Comment by hhrutter** [comment]
brew gives you the latest release if I am not mistaken.
You need to build based on the latest commit or wait for the new release which I am working on
and no I am sorry I can't give a specific date.

**Comment by hhrutter** [comment]
This should be fixed with https://github.com/pdfcpu/pdfcpu/releases/tag/v0.4.0
