### ISSUE TITLE
Validation issue with indirect refs to non-existing object

### ISSUE THREAD

**Issue by fnatte** [pdfcpu/pdfcpu#520]
Hi,

First of, thanks for a great library. The following issue has been tested with commit aa87096 and the v0.3.13 release, mac OS 12.15.1.

We're using this library to watermark/stamp files but we've had a few issues with some PDFs. I've investigated these files and found that they contain indirect refs to objects that don't exist (like `-1 0 R`). Since (most?) PDF readers seem to have no issues with these refs our users do not understand the issue with the files.

The related code in pdfcpu is in short:
1. `ValidateContext()`
2. `validateStructTree()`
3.  `validateStructElementDictEntryKArray()`
4. `IsValid()`
5. Error: `pdfcpu: IsValid: no entry for obj#-1`

At first I considered this an non-issue for pdfcpu until I found

> 	// 7.3.10
	// An indirect reference to an undefined object shall not be considered an error by a conforming reader;
	// it shall be treated as a reference to the null object.

This rule is actually refereed to in pdfcpu when dereferencing stream dictionaries. Shouldn't this rule also apply when validating arrays in dictionaries? If so, I believe there's a bug in `validateStructElementDictEntryKArray`/`IsValid`/`SetValid`.

Unfortunately I do not have any insight into how these problematic PDFs were created but I believe they have been exported from PowerPoint. Another problem is that I cannot share these PDFs with you and I have not found a reliable way to recreate PDFs with the issue. I can confirm though that the following change seem to fix our issue:

```
diff --git a/pkg/pdfcpu/validate/structTree.go b/pkg/pdfcpu/validate/structTree.go
index 1e3a0e9..2a12ba3 100644
--- a/pkg/pdfcpu/validate/structTree.go
+++ b/pkg/pdfcpu/validate/structTree.go
@@ -143,15 +143,12 @@ func validateStructElementDictEntryKArray(xRefTable *pdf.XRefTable, a pdf.Array)
 		// Avoid recursion.
 		ir, ok := o.(pdf.IndirectRef)
 		if ok {
-			valid, err := xRefTable.IsValid(ir)
-			if err != nil {
-				return err
-			}
-			if valid {
+			entry, found := xRefTable.FindTableEntry(ir.ObjectNumber.Value(), ir.GenerationNumber.Value())
+			if !found || entry.Object == nil || entry.Free {
 				continue
 			}
-			if err := xRefTable.SetValid(ir); err != nil {
-				return err
+			if !entry.Valid {
+				entry.Valid = true
 			}
 		}
```

I'll keep trying to create a PDF with this issue that I can share with you. But I thought that it might be worth hearing your take on the quote from 7.3.10. Should pdfcpu deal with the `-1` ref and handle it as a ref to the null object?

Thanks,
Matteus Hemström

**Comment by hhrutter** [comment]
Hi there!
I'd like to see one of these files first to digest as much of these corrupted indRefs at once.

**Comment by fnatte** [comment]
Hi again! Unfortunately I've not been able to produce files that I can share. So feel free to close this issue. If we ever get our hands on some PDFs we can share we can re-open it.
