### ISSUE TITLE
wasm compile error: too many arguments in call to handleHeaderBufSize

### ISSUE THREAD

**Issue by seanaye** [pdfcpu/pdfcpu#522]
Trying to compile to wasm with `GOOS=js GOARCH=wasm go build -o pdfcpu.wasm` results in the following error
```
# github.com/pdfcpu/pdfcpu/pkg/pdfcpu
./parseConfig_js.go:219:35: too many arguments in call to handleHeaderBufSize
	have (string, string, *Configuration)
	want (string, *Configuration)
```

### Thank you for submitting a possible bug!

Please ensure the following:

* Your issue is based on the latest commit - Yes, commit `aa87096eb8d84cb5d0eb759cfb47668f224331cc`
* State your OS and OS version - MacOS 12.6, M1 chip
* When reporting a problem with a specific PDF input file please avoid stating the organization responsible for the PDFWriter - just refer to the *PDFWriter* - N/A

**Comment by hhrutter** [comment]
Hi!

Confirming this bug.
Fix will be part of the upcoming release.

Thanks for using pdfcpu 💚

**Comment by hhrutter** [comment]
This should be fixed with the latest commit.
