### ISSUE TITLE
Validation Error: Fatal: pdfcpu: validateAcroForm: missing required entry "Fields"

### ISSUE THREAD

**Issue by meerkat-mary** [pdfcpu/pdfcpu#523]
Hi @hhrutter,

We're facing an issue where pdf validation is unsuccessful due to a 'Fatal: pdfcpu: validateAcroForm: missing required entry "Fields"' error for one of our PDFs

We're able to open and view this file successfully in Mac Preview and Acrobat Reader on Windows 7/10 and Mac OS Mojave using the latest commit.

[output_pdfcpu.log](https://github.com/pdfcpu/pdfcpu/files/9900704/output_pdfcpu.log)

Thank you!
Mary

**Comment by hhrutter** [comment]
Hello!

Just use the latest commit and you should be fine.

Thank you!

**Comment by meerkat-mary** [comment]
Hi @hhrutter - thanks for your reply, I tried with the latest commit (97106ac80a20a9688acc4ca3380cfe1a76af4251) and I got a different validation error

[output_pdfcpu_latest_commit.log](https://github.com/pdfcpu/pdfcpu/files/9913839/output_pdfcpu_latest_commit.log)

I was able to open this using Mac Preview and Adobe Acrobat Reader on Windows

Thanks!
Mary

**Comment by hhrutter** [comment]
Try the latest commit.

**Comment by meerkat-mary** [comment]
I've verified on the latest commit and it works, thank you @hhrutter!  ⭐️
