### ISSUE TITLE
page resize to custom size over 200 inch

### ISSUE THREAD

**Issue by CanadianHusky** [pdfcpu/pdfcpu#524]
Hello, 

I looked at open issue requests #363 and #491 but they do not cover what I am looking to do.

original PDF size = 3.6x200 inch ( =259.2 x 14400 pdf units)
I would like to rescale to a custom scale, or scale-to-fit to a custom final pdf output size that is larger than 200 inches. Adobe spec 1.6 supports theoretical limit of 15,000,000 inches (up from the previous 200 inch limit)

basically I am looking for something like this where custom final output size and scale factor can be plugged in
`pdfcpu -resize [scale_factor] -formsize-x 2592 -formsize-y 144000`
The goal is to enlarge by 10x making a final pdf at 36x2000 inch.

Can this be done ?
Best Regards

**Comment by hhrutter** [comment]
Hi there!

Doable.
My only suggestion would be to either accept a scale factor or an absolute width or height
based on the assumption that we want to preserve the aspect ratio.
Goes into the next release.

**Comment by CanadianHusky** [comment]
Wonderful!

...and yes it is perfectly fine if the command line accepts a scale factor only and calculates the final output size internally itself. The scaling is always expected to be proportional. My original post should have said "...scale factor *OR* custom final size" but allowing to plug in 2 values for formsize may leave future users under the impression that unproportional scaling is possible.

Just resize with factor is perfect.
The library is an undiscovered gem, Great work!

**Comment by hhrutter** [comment]
Fixed with v0.4.0
