### ISSUE TITLE
Support adding Chinese watermark？

### ISSUE THREAD

**Issue by yangyang20** [pdfcpu/pdfcpu#526]
`onTop := false
update := false
wm, _ := TextWatermark("你好", "", onTop, update, pdfcpu.POINTS)
AddWatermarksFile("in.pdf", "", nil, wm, nil)`

Chinese watermark cannot be added？

**Comment by gsslt** [comment]
Chinese fonts are required

**Comment by hhrutter** [comment]
You need to install your font using `pdfcpu font install`
See: https://pdfcpu.io/core/stamp
and if you want to to this programmatically I recommend usingg a stamp not a watermark: onTop = true
