### ISSUE TITLE
Specify a path for the config file

### ISSUE THREAD

**Issue by Zabrane** [pdfcpu/pdfcpu#528]
I'm running `pdfcpu` under a restricted user (`noperm`) which doesn't have a `$HOME` directory.
It would be great if we can specify the config dir location to avoid such a behaviour:
```
$ pdfcpu version
pdfcpu: config dir problem: mkdir /home/noperm: permission denied
```

Many thanks

**Comment by hhrutter** [comment]
Hi there!

Have you tried the `-conf` flag?
Checkout: https://pdfcpu.io/getting_started/config_dir.html and scroll all the way down.

**Comment by Zabrane** [comment]
@hhrutter hmm, i'm certainly missing something:
```
$ uname -a
Linux 5.4.0-131-generic #147-Ubuntu SMP Fri Oct 14 17:07:22 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

$ pdfcpu: 0.3.13
build : 2021-11-30T15:53:00Z
commit: e89570a

$ pdfcpu config
pdfcpu: unknown command "config"
Run 'pdfcpu help' for usage.
ray@ns342284:/tmp$ pdfcpu version
```

**Comment by Zabrane** [comment]
OK, i build the latest pdfcpu from master and now i can see the config:
```
$ pdfcpu config
config: /home/zab/.config/pdfcpu/config.yml
#############################
# pdfcpu v0.3.13 dev        #
# Created: 2022-11-13 19:16 #
#############################
#   Default configuration   #
#############################

# toggle for inFilename extension check (.pdf)
checkFileNameExt: true
[. . .]
```

From the doc, i can read this:
> You can also use this flag to disable the usage of a config dir.
> This comes in handy in (serverless) environments where the default [user’s config directory](https://golang.org/pkg/os/#U

Could you please explain how one can use the `-conf` to completely disable reading any conf dir?

**Comment by hhrutter** [comment]
For any CLI command `pdfcpu help yourCmd` should give you a hint like:

```
usage: pdfcpu split [-m(ode) span|bookmark] inFile outDir [span]

common flags: -v(erbose)  ... turn on logging
              -vv         ... verbose logging
              -q(uiet)    ... disable output
              -c(onf)     ... set or disable config dir: $path|disable
              -opw        ... owner password
              -upw        ... user password
              -u(nit)     ... display unit: po(ints) ... points
                                            in(ches) ... inches
                                                  cm ... centimetres
                                                  mm ... millimetres
```

.. so if you issue your cmd followed by `-conf disable` that should do the trick.. 🤞

**Comment by Zabrane** [comment]
Works as expected. Thank you.
