### ISSUE TITLE
Windows binary outdated

### ISSUE THREAD

**Issue by readonly24** [pdfcpu/pdfcpu#529]
The [latest binary for Windows](https://github.com/pdfcpu/pdfcpu/releases) seems to be outdated. Can you please update?

Thanks.

**Comment by hhrutter** [comment]
You need to `go install` the latest commit or wait for the next release.

**Comment by readonly24** [comment]
Thanks Horst for the quick response. I don't have go installed, im just a user. Any timeframe for the next version?

**Comment by hhrutter** [comment]
Soon hopefully!

**Comment by hhrutter** [comment]
https://github.com/pdfcpu/pdfcpu/releases/tag/v0.4.0
