### ISSUE TITLE
cli: Remove Watermark failing

### ISSUE THREAD

**Issue by zy520321** [pdfcpu/pdfcpu#530]
Hi,
 I tested the watermark, I found that the removal of the watermark prompted that the watermark was not found.
Is this a problem?
"pdfcpu watermark add -mode image -- "2.png" "" 1.pdf xx.pdf"
"pdfcpu.exe watermark remove xx.pdf"

**Comment by hhrutter** [comment]
Hi!

That message should appear only if you try to remove a watermark when there was none added or it was already removed.
In your case there may be a different reason due to your specific PDF inFile.
Hard for me to analyze unless I have the file at hand.

Thanks for using pdfcpu 💚

**Comment by zy520321** [comment]
Hi,
test files as follow:
[1.pdf](https://github.com/pdfcpu/pdfcpu/files/10017789/1.pdf)
[1_watermark.pdf](https://github.com/pdfcpu/pdfcpu/files/10017790/1_watermark.pdf)
![water](https://user-images.githubusercontent.com/9145848/202073931-cd335f64-21fe-40c3-ad81-7c6d04ca660b.jpg)

**Comment by hhrutter** [comment]
Closed due to inactivity.
