### ISSUE TITLE
Error Decrypting: checkStmv: unsupported "StdCF" entry in "CF": pdfcpu: supportedCFEntry: invalid entry "Length"

### ISSUE THREAD

**Issue by seanaye** [pdfcpu/pdfcpu#532]
### Thank you for submitting a possible bug!

Please ensure the following:

* Your issue is based on the latest commit - yep! `github.com/pdfcpu/pdfcpu v0.3.14-0.20221101223428-07d97625e3fa`
* State your OS and OS version: MacOS - arm64 v12.6 compile target `GOOS=js GOARCH=wasm`
* When reporting a problem with a specific PDF input file please avoid stating the organization responsible for the PDFWriter - just refer to the *PDFWriter*

I am a little stumped as to the cause of this issue but I think this is the best place to report it.

I have an electron app which decrypts pdf files using pdfcpu compiled to wasm.

In dev mode this works fine, but in production (final app bundle) I receive `pdfcpu: checkStmv: unsupported "StdCF" entry in "CF": pdfcpu: supportedCFEntry: invalid entry "Length"` when trying to decrypt files.

Other features of pdfcpu, like listing pdf permissions, works fine in the production bundle so I think it is unlikely the wasm file is being improperly imported or bundled.

I think this may be related to #83 since the error message is the same.

The error occurs for any encrypted file in production even when using the same pdf file as in "dev" the wasm binary file is exactly the same in dev and prod.

Relevant decryption code
```go
package convert

import (
	"bytes"
	"io"
	"syscall/js"

	"github.com/coparse-inc/app-monorepo/packages/pdfcpu-wasm/go/bridge"
	"github.com/orcaman/writerseeker"
	"github.com/pdfcpu/pdfcpu/pkg/api"
	"github.com/pdfcpu/pdfcpu/pkg/pdfcpu"
)

type ConvertFunc func([]byte, *pdfcpu.Configuration) ([]byte, error)
type ApiConvert func(io.ReadSeeker, io.Writer, *pdfcpu.Configuration) error

func createConverter(fn ApiConvert) ConvertFunc {
	return func(b []byte, c *pdfcpu.Configuration) ([]byte, error) {
		writerSeeker := &writerseeker.WriterSeeker{}
		r := bytes.NewReader(b)
		err := fn(r, writerSeeker, c)
		if err != nil {
			bridge.Log(err.Error())
			return nil, err
		}
		reader := writerSeeker.Reader()
		return io.ReadAll(reader)
	}
}

func jsWrapper(fn ConvertFunc) js.Func {
	return bridge.PromiseFn(2, func(args []js.Value) (interface{}, error) {
		arr := args[0]
		pw := args[1].String()
		b := bridge.ImportUint8Arr(arr)
		bridge.Log("before")
		conf := pdfcpu.NewAESConfiguration(pw, "", 128)
		bridge.Log("after")
		out, err := fn(b, conf)
		if err != nil {
			return nil, err
		}
		// copy bytes back to js
		return bridge.ExportUint8Arr(out), nil
	})
}

var Encrypt = jsWrapper(createConverter(api.Encrypt))
var Decrypt = jsWrapper(createConverter(api.Decrypt))

```

<details>
  <summary>Javascript bridge code</summary>
  
  
  ```go
package bridge

import (
	"errors"
	"fmt"
	"syscall/js"
)

func Log(s string) {
	js.Global().Get("console").Get("log").Invoke(s)
}

func Err(err error) js.Value {
	errorConstructor := js.Global().Get("Error")
	errorObj := errorConstructor.New(err.Error())
	return errorObj
}

func ImportUint8Arr(arr js.Value) []byte {
	inBuf := make([]uint8, arr.Get("byteLength").Int())
	js.CopyBytesToGo(inBuf, arr)
	return inBuf
}

func ExportUint8Arr(b []byte) js.Value {
	arrayConstructor := js.Global().Get("Uint8Array")
	dataJs := arrayConstructor.New(len(b))
	js.CopyBytesToJS(dataJs, b)
	Log("copied")
	return dataJs
}

func PromiseFn(nArgs int, fn func(args []js.Value) (interface{}, error)) js.Func {
	return js.FuncOf(func(this js.Value, args []js.Value) any {
		handler := js.FuncOf(func(this js.Value, promArgs []js.Value) any {
			resolve := promArgs[0]
			reject := promArgs[1]

			rej := func(err error) {
				reject.Invoke(Err(err))
			}

			if l := len(args); l != nArgs {
				s := fmt.Sprintf("Invalid number of arguments passed. Expected %d, received %d", nArgs, l)
				rej(errors.New(s))
			}

			go func() {
				res, err := fn(args)
				if err != nil {
					Log(err.Error())
					rej(err)
					return
				}
				resolve.Invoke(res)
			}()
			return nil
		})
		promiseConstructor := js.Global().Get("Promise")
		return promiseConstructor.New(handler)
	})
}
  ```
  
</details>

**Comment by hhrutter** [comment]
What you can try is patch `supportedCFEntry` in crypto.go to output the invalid Length in question:
```
return false, errors.Errorf("pdfcpu: supportedCFEntry: invalid entry \"Length\": %d", *l)
```
or try removing that length check altogether and see if this makes any difference.

This may help, other than strange behavior..
Sorry but WASM is not really  my domain.

**Comment by seanaye** [comment]
@hhrutter Just created a fork which logs via the following
```go
	l := d.IntEntry("Length")
	if l != nil && (*l < 5 || *l > 16) && *l != 32 {
    return false, errors.New(fmt.Sprintf("pdfcpu: supportedCFEntry: invalid entry \"Length\": %d", *l))
	}
```
When I run this compiled fork in the packaged electron app it logs out the length as `256`

**Comment by seanaye** [comment]
I think it might be possible that production electron is compressing the wasm binary in a way that causes different behaviour. Would that hypothesis be consistent with the `256` issue?

**Comment by seanaye** [comment]
If I remove the length check and update the error msg for `getR` to be the following
```go
func getR(d Dict) (int, error) {

	r := d.IntEntry("R")
	if r == nil || *r < 2 || *r > 5 {
		if r != nil && *r > 5 {
      return 0, errors.Errorf("pdfcpu: encryption: invalid \"R\": %d", *r)
		}
```

This logs out invalid R as `6`

**Comment by seanaye** [comment]
Verified the binaries are the same
`diff packages/pdfcpu-wasm/public/main.wasm packages/electron/dist/mac-arm64/Macro.app/Contents/Resources/app.asar.unpacked/build/main.8047a021.wasm` prints nothing

**Comment by hhrutter** [comment]
`This logs out invalid R as 6` ... R=6 is definitely not supported, that means you should be getting this error for a specific file regardless of dev or prod mode right?

**Comment by seanaye** [comment]
You would think so, but in dev mode the exact same file is working correctly. I will update my fork to always log R and see what it prints in dev mode

**Comment by seanaye** [comment]
Oops I was testing different files that have the same start of the filename in dev and prod. Will close and open new issue for decryption error
