### ISSUE TITLE
Modify Author and Title

### ISSUE THREAD

**Issue by rhaleblian** [pdfcpu/pdfcpu#536]
Hi!  Nice project.

I saw the command for viewing PDF info.  I want to edit the Title and Author fields for a given PDF.

If it's a compelling feature idea I could take a stab at adding it.  I'm new to Go but intend to become less so.

**Comment by hhrutter** [comment]
Hi there!

You can change both using the `property add`command.
Check out the very example ->  https://pdfcpu.io/properties/properties_add

**Comment by rhaleblian** [comment]
Ohh! Thank you.
