### ISSUE TITLE
Anchor Links in pdfcpu

### ISSUE THREAD

**Issue by meerkat-mary** [pdfcpu/pdfcpu#539]
Hi @hhrutter,

I'd like to add anchor hyperlinks that link to another page in the same pdf document, is this possible using existing functionality in the pdfcpu api? I had a look at `LinkAnnotation` and saw that I could link to a webpage but I had trouble finding an api function to link to another page in the same document

To add more detail:
-  My document has a table of contents and I'd like to add a transparent box around each entry in the table of contents that links to its associated page
- The table of contents was generated using gofpdf which has x and y values based on millimetres I believe (and co-ordinates start on the top left) - from this I can get x,y co-ordinates of the bounding box for each entry in the table of contents, I would need to convert these co-ordinates into pdfcpu compatible co-ordinates I assume
- I'm hoping to read in an existing document, add in some anchor links by specifying the bounding box of the clickable area and the page number to link to for each table of contents entry, and then write the document to file using pdfcpu

Appreciate your time and help,
Mary

**Comment by hhrutter** [comment]
Hi Mary!

We need to extend `LinkAnnotation` to support hyperlinks to pages.

Sorry to say this is not something I can do right away, because I am in the middle of a major refactoring needed for the upcoming release.

Meanwhile,  think about how you'd want to present your destination pages:

<img width="638" alt="Screen Shot 2022-12-21 at 13 32 50" src="https://user-images.githubusercontent.com/11322155/208906001-829750db-15db-4c4b-ae29-68de643850dc.png">

#

**Comment by meerkat-mary** [comment]
Thanks for confirming @hhrutter! No worries on not being able to implement this right away, good luck with the refactoring and upcoming release! ⭐ 

I think for me, the first row (`page /XYZ left top zoom`) is how I'd want to present the destination page, where the zoom factor is preserved but the page just starts at the top left.

**Comment by hhrutter** [comment]
Hi there!

This is part of v0.4.0!

https://github.com/pdfcpu/pdfcpu/blob/master/pkg/api/test/annotation_test.go has a testcase with a blueprint:
```
func TestAddLinkAnnotationWithDest(t *testing.T) {
	msg := "TestAddLinkAnnotationWithDest"

	inFile := filepath.Join(inDir, "Walden.pdf")
	outFile := filepath.Join(samplesDir, "annotations", "LinkAnnotWithDestTopLeft.pdf")

	// Create internal link:
	// Add a 100x100 link rectangle on the bottom left corner of page 2.
	// Set destination to top left corner of page 1.

	internalLink := model.NewLinkAnnotation(
		*types.NewRectangle(0, 0, 100, 100),
		nil,
		&model.Destination{Typ: model.DestXYZ, PageNr: 1, Left: -1, Top: -1},
		"",
		"id",
		0,
		&color.Red,
		true,
	)

	err := api.AddAnnotationsFile(inFile, outFile, []string{"2"}, internalLink, nil, false)
	if err != nil {
		t.Fatalf("%s add: %v\n", msg, err)
	}
}
```

**Comment by meerkat-mary** [comment]
Thank you very much @hhrutter! ⭐ 

I'll test this out and get back to you in the next few days 😃

**Comment by meerkat-mary** [comment]
I can confirm that the annotation links work - thank you very much, this is such a useful feature!

(I did notice that annotations with a border/colour did not render up on Mac Preview but they were present, just not visible, just an FYI)

**Comment by hhrutter** [comment]
👍  For annotation and form related rendering stuff pdfcpu's reference is A.Reader
