### ISSUE TITLE
Userfonts is not correct in the program shell function

### ISSUE THREAD

**Issue by qq413434162** [pdfcpu/pdfcpu#547]
In pdfcpu: 0.3.13

1. I run program with user A
2. In the program runing shell command [pdfcpu stamp add -p 2-l -mode text -- "test" "font:SourceHanSansCN-Bold, points:40, sc:1 abs, al:c, rot:0, op:0.12" a.pdf b.pdf]
3. The log print to font do not install SourceHanSansCN-Bold.ttf
4. I am make sure install in Userfonts(/home/[user A]/.config/pdfcpu/fonts):
5. For debug, In the program runing shell command [pdfcpu fonts list],then print to Userfonts(/tmp/pdfcpu/fonts)

q1. Why the use A's Userfonts is /tmp/pdfcpu/fonts?
q2. How can i slove the problem?

**Comment by hhrutter** [comment]
Hi!

I tried https://github.com/CyanoHao/WFM-Free-Font/blob/master/SourceHanSansCN/SourceHanSansCN-Bold.ttf and had no problem.

1) Check if your file is valid: `pdfcpu val test.pdf`

2) If your file is valid, post a stack trace that you can get with:
`pdfcpu val -vv intest.pdf`
or
`pdfcpu stamp add -vv -p 2-l -mode text -- "test" "font:SourceHanSansCN-Bold, points:40, sc:1 abs, al:c, rot:0, op:0.12" a.pdf b.pdf`

Once I see a stacktrace I can tell you more hopefully.

**Comment by qq413434162** [comment]
> Hi!
> 
> Stating your OS/version might help here.
> 
> I tried https://github.com/CyanoHao/WFM-Free-Font/blob/master/SourceHanSansCN/SourceHanSansCN-Bold.ttf and had no problem.
> 
> 1. Check if your file is valid: `pdfcpu val test.pdf`
> 2. If your file is valid, post a stack trace that you can get with:
>    `pdfcpu val -vv intest.pdf`
>    or
>    `pdfcpu stamp add -vv -p 2-l -mode text -- "test" "font:SourceHanSansCN-Bold, points:40, sc:1 abs, al:c, rot:0, op:0.12" a.pdf b.pdf`
> 
> Once I see a stacktrace I can tell you more hopefully.

In Ubuntu 16.04.3 LTS, I use supervisor manage my program.
I try to set the environment, solve the problem.

In the supervisor template,
environment=HOME=/home/A
