### ISSUE TITLE
Extraction of black & white images produces grayscale with brightness 0 and 1

### ISSUE THREAD

**Issue by SBelleguelle** [pdfcpu/pdfcpu#548]
I am using v0.3.13 on Windows.

I have a PDF with binary images embedded.  I am using the ExtractImage function and it generates what initially seem to be black PNG images.  On closer inspection it can be seen that the images produced have two brightness levels, but they are 0 and 1, rather than 0 and 255.

It seems the problem is in renderDeviceGrayToPNG and the decodePixelValue function which returns a value in the range {0,1}

				v := decodePixelValue(pix, im.bpc, dec[0])
				//fmt.Printf("x=%d y=%d pix=#%02x v=#%02x\n", x, y, pix, v)
				img.Set(x, y, color.Gray{Y: v})

Value v will be 0 or 1 for binary, and this is the Gray value being set in the image bitmap.

I was previously using version 0.3.6 and it extracted the binary images with grayscale values 0 and 255.

The document I have been working with can be downloaded from [https://www.researchgate.net/publication/278314878_Pastoral_Care](https://www.researchgate.net/publication/278314878_Pastoral_Care)

Thanks for a great library :-)

**Comment by hhrutter** [comment]
Hi there and thanks for your findings!

Right now I am in the middle of preparing a new release.
I hate to say this but at this point there is no way I can provide you with a fix because of this.
You can consider this to be fixed in the new release though.
Please bear with me 🙏 

Meanwhile I thank you for using pdfcpu 💚

**Comment by SBelleguelle** [comment]
Thanks for the update and I perfectly understand.

**Comment by hhrutter** [comment]
This is fixed with v0.4.0

**Comment by SBelleguelle** [comment]
Thank you :-)
