### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by mpiot** [pdfcpu/pdfcpu#551]
Hi,
I just want to know, if that's possible to create a new release and binary ? 
Except I'm wrong, I see the last one date of Nov 30, 2021

Thanks a lot :)

**Comment by hhrutter** [comment]
Yes, overdue I am aware.
👍 A new release has been in the making and is around the corner.
Keep following https://twitter.com/pdfcpu for any updates.

**Comment by Stochastic-Squirrel** [comment]
I just wanted to drop in and say  thanks @hhrutter! All the work that you and the other contributors have put into this project is very much appreciated. It is a stellar piece of software!

**Comment by mwansinck** [comment]
@hhrutter Do you have a roadmap about when the new release is being tagged? Thanks!

**Comment by hhrutter** [comment]
https://twitter.com/pdfcpu/status/1625794578921013250

**Comment by hhrutter** [comment]
https://github.com/pdfcpu/pdfcpu/releases/tag/v0.4.0
