### ISSUE TITLE
dict=fdDict entry=Lang: unsupported in version 1.4

### ISSUE THREAD

**Issue by jinigithub** [pdfcpu/pdfcpu#552]
pdfcpu validate -vv 1.pdf &>crash.log
Fatal: dict=fdDict entry=Lang: unsupported in version 1.4
This file could be PDF/A compliant but pdfcpu only supports versions <= PDF V1.7
[1.PDF](https://github.com/pdfcpu/pdfcpu/files/10564345/1.PDF)
[crash.log](https://github.com/pdfcpu/pdfcpu/files/10564346/crash.log)

**Comment by hhrutter** [comment]
Hello!

Please use the latest commit and you should be fine!
Thank you for using pdfcpu 💚

**Comment by jinigithub** [comment]
yes,it's fine now,tks a lot.
