### ISSUE TITLE
How to draw a line?

### ISSUE THREAD

**Issue by reply2future** [pdfcpu/pdfcpu#553]
I want to draw a line to pdf but there are no any documents about that.

Thank you for any helps.

**Comment by hhrutter** [comment]
Hi there!

pdfcpu is processing PDFs and occasionally also drawing but it is no PDF drawing package by definition.
There is a `func DrawLine` though which may help you but this is all low level and comes down to studying the PDF syntax.

Thank you for using pdfcpu 💚
