### ISSUE TITLE
unexpected panic attack: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by jinigithub** [pdfcpu/pdfcpu#555]
pdfcpu stamp add -mode text -- "text" "" 2.pdf out.pdf
writing out.pdf...
unexpected panic attack: runtime error: invalid memory address or nil pointer dereference
[2.pdf](https://github.com/pdfcpu/pdfcpu/files/10694154/2.pdf)

by the way,pdfcpu validate results ok.

**Comment by hhrutter** [comment]
This will work with the upcoming release!

Please follow https://twitter.com/pdfcpu for the release announcement
& Thank you for using pdfcpu 💚

**Comment by hhrutter** [comment]
This is fixed with v0.4.0
