### ISSUE TITLE
api: split: performance

### ISSUE THREAD

**Issue by yogimogi** [pdfcpu/pdfcpu#556]
Was trying to use pdfcpu libray to split a biggish (500+ pages) PDF file. Below are **main.go** and **go.mod** files.

**main.go** file
```
package main

import (
	"fmt"
	"time"

	"github.com/pdfcpu/pdfcpu/pkg/api"
	"github.com/pdfcpu/pdfcpu/pkg/pdfcpu"
)

func main() {
	t1 := time.Now()
	api.SplitFile("522_pages_file.pdf", "/tmp/out", 1, pdfcpu.NewDefaultConfiguration())
	fmt.Println(time.Since(t1))
}

```
**go.mod** file
```
module pdf

go 1.20

require github.com/pdfcpu/pdfcpu v0.3.13

require (
	github.com/hhrutter/lzw v0.0.0-20190829144645-6f07a24e8650 // indirect
	github.com/hhrutter/tiff v0.0.0-20190829141212-736cae8d0bc7 // indirect
	github.com/pkg/errors v0.9.1 // indirect
	golang.org/x/image v0.0.0-20210220032944-ac19c3e999fb // indirect
	golang.org/x/text v0.3.6 // indirect
	gopkg.in/yaml.v2 v2.4.0 // indirect
)

```
Program worked fine, just that, for this particular file time it took was **2m41.82237937s**
Just out of curiosity, I cloned the repository and replaced main method of file **pdfcpu/cmd/pdfcpu/main.go** with 
```
func main() {
	t1 := time.Now()
	api.SplitFile("522_pages_file.pdf", "/tmp/out", 1, pdfcpu.NewDefaultConfiguration())
	fmt.Println(time.Since(t1))
}
```
, did **go build .** and ran the program **./pdfcpu**. Now the time the program reports is **1m6.528867679s**.  I tried this many times, results are more or less the same. Am I missing something about how the library should be used with other Go programs where only **api.*** functions will be used.

regards, Yogesh

**Comment by hhrutter** [comment]
Interesting findings!
Thanks for the input!

**Comment by hhrutter** [comment]
I have been testing using v0.4.0 and cannot confirm your findings.
I get more or less the same stats with both of your scenarios for quite large files.
There very well may be something special about your particular file and I am happy to look into it assuming you can share the file.

**Comment by hhrutter** [comment]
Closed due to inactivity.
