### ISSUE TITLE
cli: crop: Should be allowed to crop PDFs into halves

### ISSUE THREAD

**Issue by zingmane** [pdfcpu/pdfcpu#557]
I try to achieve to cut PDFs into halves after scanning DinA3 pages.
Similar issue: https://github.com/pdfcpu/pdfcpu/issues/467

```sh
# does not work
pdfcpu crop  -pages odd -u mm -- "pos:tl, dim:.5 1 rel" in.pdf out.pdf
# problem parsing box definition: pdfcpu: invalid relative box height: 1.000000 must be positive < 1

# does also not work because there is no pos only left
pdfcpu crop  -pages odd -u mm -- "pos:l, dim:.5 rel" in.pdf out.pdf
```

My workaround is to reduce it to 0.999999 rather than 1.

The whole workflow is currently

1. double the pages with a seq which van easily generated: `pdfcpu collect -pages 1,1,2,2,3,3,4,4,5,5,6,6,... in.pdf out1.pdf`
2. crop even pages: pdfcpu crop  -pages even -- "pos:tl, dim:.5 .999999 rel" out1.pdf out2.pdf
3. crop odd pages: pdfcpu crop  -pages odd -- "pos:tr, dim:.5 .999999 rel" out2.pdf out3.pdf

But that does not work, I think because the pages are not really duplicated but only linked and when the original gets cropped the linked page is also cropped. Am I right?

**Comment by hhrutter** [comment]
I think you may have discovered a buggy situation - thank!
All commands have been implemented for isolated usecases.
Chaining pdfcpu commands is where it gets interesting and that will be more the focus in the near future.
You do not want to miss the next release which will feature the `cut` command..

**Comment by hhrutter** [comment]
This is fixed with the latest release.
