### ISSUE TITLE
PDF TrimFile Problem: dereferenceObject: problem dereferencing object. pdfcpu: parse: duplicate key

### ISSUE THREAD

**Issue by Kush-Wednesday** [pdfcpu/pdfcpu#558]
Hi, 

I am using v0.3.13 in Mac Os M1,

I am trying to extract 4 pages from the pdf
[sample.pdf](https://icseindia.org/document/sample.pdf) 

I checked its failing the validation

`$ pdfcpu validate sample.pdf
validating(mode=relaxed) sample.pdf
dereferenceObject: problem dereferencing object 222: pdfcpu: parse: duplicate key
`

here is the verbose output
[crash.log](https://github.com/pdfcpu/pdfcpu/files/10793013/crash.log)

**Comment by hhrutter** [comment]
Please go and get the latest release: https://github.com/pdfcpu/pdfcpu/releases/tag/v0.4.0
