### ISSUE TITLE
api.ImportImages return err--image: unknown format

### ISSUE THREAD

**Issue by jinigithub** [pdfcpu/pdfcpu#560]
i think it's not a bug,only i wrote the wrong codes.

//img as image.image
var bs []io.Reader
b := bytes.Buffer{}
out, err := os.OpenFile("test.pdf", os.O_CREATE|os.O_RDWR|os.O_APPEND, 0666)
png.Encode(b, img) 
....//b write to file out.png show okay.
bs = append(bs, &b)
err=api.ImportImages(nil, out, bs, nil, nil) //got error: image: unknown format
//and i can't get the idea of the first rs io.readseeker,point to ?

**Comment by hhrutter** [comment]
Hello!

You supply the first parameter if you want to import images into an existing PDF on new pages.
If you leave the first parameter nil, pdfcpu will write a brandnew file for you - that's the difference.

Please refer to: 

api.importImages_test.go and api.importImage.go: api.ImportimagesFile

**Comment by hhrutter** [comment]
Closed due to inactivity.
