### ISSUE TITLE
PDF signature?

### ISSUE THREAD

**Issue by pisciss** [pdfcpu/pdfcpu#561]
Hi Is there any news about being able to sign a pdf from a x509.Certificate? I have the certificate with the lib "crypto/x509" but i dont find a way to sign the pdf .. Thanks!

**Comment by hhrutter** [comment]
We have #168 in the pipeline.
Please check back.

**Comment by jm809** [comment]
---
#https;//ww.notion.so/n8n/Frontmatter-432c2b8dff1f43d4b1c8d20075510fe4 
description: How to use the API playground to try out n8n's public REST API.
contentType 💯  howto
---

#101 Using the API playground

/// info | Feature availability
The API playground isn't available on Cloud.
It's available for all self-hosted pricing tiers.
> [!CAUTION]
> 
The n8n API comes with a built-in Swagger UI playground in self-hosted versions. This provides interactive documentation, where you can try out requests. The path to access the playground depends on your hosting.

n8n constructs the path from values set in your environment variables:

` ` `shell
N8N_HOST 👎 N8N_PORT/N8N_PATH/api/v<api-version-number>/docs
` ` `
The API version number is `1` . There may be multiple versions available in the future. 
@Legislaturasj
