### ISSUE TITLE
Missing old interface for `api.Merge()` in version 0.4.0 

### ISSUE THREAD

**Issue by christian-heusel** [pdfcpu/pdfcpu#566]
### Thank you for submitting a possible bug!

Please ensure the following:

* Your issue is based on the latest commit: ✅
* State your OS and OS version: ArchLinux / Docker golang gontainer at tag `1.20-bullseye`

---

As said in Issue https://github.com/pdfcpu/pdfcpu/issues/447#issuecomment-1449818339 in reference to https://github.com/pdfcpu/pdfcpu/commit/a86469b721d0592fd1b5a21bb46aa969ef9d7e74:
> The api portion of the merge command has been refactored, which should improve the memory consumption issue you reported.
Please let me know how this works out for you.

This refactoring unfortunately broke our usage of `api.Merge()`, which made use of the buffer compatible interface:
https://github.com/henrixapp/pdfcomprezzor/blob/8d4dce38599eb3457dc582b484da3996f1b0e2c1/main.go#L92-L111

In the initial commit there was `api.OldMerge()` but it since has been deleted (in commit https://github.com/pdfcpu/pdfcpu/commit/de1d26495e753698770be98bad8e3f0b6a0e3a88) and we cannot find a version of the function that implements the old interface and corresponding functionality.

Did we miss something?

Again thank you so much for all the effort you put in `pdfcpu` 🤗 🎉

---
cc @henrixapp 
related to PR https://github.com/henrixapp/pdfcomprezzor/pull/9

**Comment by hhrutter** [comment]
I have revived the old api.Merge(ReadSeekers) as api.MergeRaw(...)
Please go get the latest commit.

Hope that works out for you and I am sorry for that.
This somehow slipped through..

Thx a ton for reporting this! 💚

**Comment by christian-heusel** [comment]
Very nice, thanks a lot for the very quick fixes and helpful interactions! 🥳
