### ISSUE TITLE
form fill error

### ISSUE THREAD

**Issue by JaDuyve** [pdfcpu/pdfcpu#572]
Hi,

I was trying to use the new functionality of form filling and I have the following error.

```console
$ pdfcpu form fill test.pdf form.json output.pdf
writing output.pdf...
unexpected panic attack: runtime error: index out of range [0] with length 0
```

* crash log using verbose logging: [crash.log](https://github.com/pdfcpu/pdfcpu/files/10891944/crash.log)
* [validation.log](https://github.com/pdfcpu/pdfcpu/files/10891959/validation.log)

pdfcpu version: v0.4.0 dev
OS used: Macos Ventura 13.2.1

If necessary, I can provide the `test.pdf` via mail or slack.

**Comment by hhrutter** [comment]
This issue should be fixed with the latest commit!
