### ISSUE TITLE
api: form fill

### ISSUE THREAD

**Issue by owenhankinson** [pdfcpu/pdfcpu#575]
### Thank you for submitting a possible bug!

Please ensure the following:

* Your issue is based on the latest commit
* State your OS and OS version
* When reporting a problem with a specific PDF input file please avoid stating the organization responsible for the PDFWriter - just refer to the *PDFWriter*

### Discription

OS: MacOS Ventura 13.0

I am new to using this library, I am mainly trying to use it to help with autofilling PDF forms with information we already have. Everything seems to be working correctly, until I get to using the `FillFormFile()` in `github.com/pdfcpu/pdfcpu@v0.4.0/pkg/pdfcpu/form/fill.go:476` as I debug, I can see the entry "T" it is looking for. It even shows in the function `d.StringLiteralEntry("T")` that the key is found. Yet it returns nil. 

### Here is my method for getting and filling the forms:
1. download the PDF (https://www.irs.gov/pub/irs-pdf/fw4.pdf) and use pdfcpu to export the JSON which contains the form information
2. running some functions on the JSON to make a new JSON file with data in the "value" section of the form entries.
3. Input the original file along with the new json into `FillFormFile()` and expect a new file.

**Comment by hhrutter** [comment]
Using the latest commit this is working for me more or less..
Opens fine on Mac Preview (with odd fill color though) but A.Reader complains about smth.
I need to play around more with this.

**Comment by owenhankinson** [comment]
@hhrutter not sure what you are referring to, but if this helps - here is the actual code I am running in GO

```
// getJsonFormExport removes the json information from the w4 pdf and unmarshals it into a w4JSON object
func getJsonFormExport(inFile, outFile string) (*w4JSON, error) {
	w4json := w4JSON{}
	err := api.ExportFormFile(inFile, outFile, nil)
	if err != nil {
		return nil, err
	}

	defer func() {
		err = os.Remove(outFile)
		if err != nil {
			return
		}
	}()

	bytes, err := ioutil.ReadFile(outFile)
	if err != nil {
		return nil, err
	}

	err = json.Unmarshal(bytes, &w4json)
	if err != nil {
		return nil, err
	}

	return &w4json, nil
}
```
and 
```
// This writes the info to the data in the json file exported from the w4 pdf
func (w *w4Writer) writeAndFillW4Info(
	employee *data.User,
	organization *data.Organization,
	signature *data.Signature,
	ssn string,
	cld *cloud.Config,
	jsonExport *w4JSON,
) error {

	jsonExport.writeFirstNameAndMiddleInitial(employee.FirstName, employee.MiddleName)
	jsonExport.writeLastName(employee.LastName)
	jsonExport.writeSSN(ssn)
	jsonExport.writeHomeAddress(employee.AddressLineOne)
	jsonExport.writeHomeCityStateZip(employee.AddressCity, employee.AddressState, employee.AddressZip)

	jsonExport.checkFilingStatusBox(strings.ToLower(employee.FilingStatus))

	jsonExport.checkMultipleJobsOrSpouseWorks(employee.MultipleJobsOrSpouseWorks)
	jsonExport.writeClaimDependents(employee.ClaimDependentsAmount)
	jsonExport.writeOtherIncome(employee.W4WithholdingOtherIncome.Decimal)
	jsonExport.writeOtherDeductions(employee.W4WithholdingOtherDeductions.Decimal)
	jsonExport.writeExtra(employee.W4ExtraWithholding.Decimal)

	// w.writeEmployeeSignature(organization, signature, cld)

	jsonExport.writeEmployerNameAndAddress(organization)
	jsonExport.writeEmployeeStartDate(employee.StartDate.Date)
	jsonExport.writeEIN(organization)

	bytes, err := json.Marshal(jsonExport)
	if err != nil {
		return err
	}

	file, err := os.Create("tmp.json")
	if err != nil {
		return err
	}

	_, err = file.Write(bytes)
	if err != nil {
		return err
	}

	err = file.Close()
	if err != nil {
		return err
	}

	err = api.FillFormFile("w4.pdf", "tmp.json", "w4_filled.pdf", nil)
	if err != nil {
		return err
	}

	defer func() {
		err = os.Remove("tmp.json") // no longer need this file
	}()

	return nil
}
```

**Comment by hhrutter** [comment]
*pdfcpu form filling* is foremost for forms created with pdfcpu.

If we want to make form filling work with PDFs produced by other PDF writers than pdfcpu:

🙏 At this point just use the cli to list/export and fill your form and report any issues and please also submit the PDF in question.

I don't see any other way here to make quick progess.

Reason: I need to focus on the core use cases right now for quick improvements.

Thank you!

**Comment by owenhankinson** [comment]
@hhrutter looks like using the CLI is working for the most part. The one issue I am running into is when editing a checkbox JSON value, I'm not seeing those changes reflected onto the PDF as the other changes are. Do you know any workarounds? Is this a known issue? Thanks again

**Comment by owenhankinson** [comment]
Here is the JSON, you can see the checkbox values are set to true before they go in, along with the other values - the textboxes are getting the values inputted correctly, but not the checkboxes

{"header":{"author":"SE:W:CAR:MP","creation":"2023-03-09 13:21:48 PST","creator":"Designer 6.5","keywords":"Fillable","producer":"Designer 6.5","source":"w4.pdf","subject":"Employee's Withholding Certificate","title":"2023 Form W-4","version":"pdfcpu v0.4.0 dev"},"forms":[{"textfield":[{"id":"84.85.87.3432","value":"Teri ","multiline":false,"locked":false},{"id":"84.85.87.3433","value":"Johnson","multiline":false,"locked":false},{"id":"84.85.87.3434","value":"4321432143214321fc af dsarfd safdsa  d","multiline":false,"locked":false},{"id":"84.85.87.3435","value":"City, AR 18493","multiline":false,"locked":false},{"id":"84.85.3436","value":"test","multiline":false,"locked":false},{"id":"84.85.88.3442","value":"","multiline":false,"locked":false},{"id":"84.85.88.3443","value":"","multiline":false,"locked":false},{"id":"84.85.3444","value":"500","multiline":false,"locked":false},{"id":"84.85.3445","value":"1.00","multiline":false,"locked":false},{"id":"84.85.3446","value":"0.00","multiline":false,"locked":false},{"id":"84.85.3447","value":"0.00","multiline":false,"locked":false},{"id":"84.85.3448","value":"Valor Education - 220 Foremost Dr, Austin, Texas 78745","multiline":true,"locked":false},{"id":"84.85.3449","value":"07/17/2023","multiline":false,"locked":false},{"id":"84.85.3450","value":"81-1145945","multiline":false,"locked":false},{"id":"84.86.83","value":"","multiline":false,"locked":false},{"id":"84.86.82","value":"","multiline":false,"locked":false},{"id":"84.86.81","value":"","multiline":false,"locked":false},{"id":"84.86.80","value":"","multiline":false,"locked":false},{"id":"84.86.79","value":"","multiline":false,"locked":false},{"id":"84.86.78","value":"","multiline":false,"locked":false},{"id":"84.86.77","value":"","multiline":false,"locked":false},{"id":"84.86.76","value":"","multiline":false,"locked":false},{"id":"84.86.75","value":"","multiline":false,"locked":false},{"id":"84.86.74","value":"","multiline":false,"locked":false},{"id":"84.86.73","value":"","multiline":false,"locked":false}],"checkbox":[{"id":"84.85.3437","value":true,"default":false,"locked":false},{"id":"84.85.3439","value":true,"default":false,"locked":false},{"id":"84.85.3440","value":true,"default":false,"locked":false},{"id":"84.85.3441","value":true,"default":false,"locked":false}]}]}

**Comment by hhrutter** [comment]
working on a fix..

**Comment by owenhankinson** [comment]
@hhrutter Update: I've checked some other PDF viewers - it looks like this is working, just not in the google viewer

**Comment by hhrutter** [comment]
Do you mean just opening the PDF in Chrome?

**Comment by owenhankinson** [comment]
> Do you mean just opening the PDF in Chrome?

Indeed.

**Comment by owenhankinson** [comment]
@hhrutter were you able to make any updates to allow chrome to see the checkbox?

**Comment by owenhankinson** [comment]
@hhrutter sounds good looking foward to hearing from you, please let me know how I can help :)

**Comment by hhrutter** [comment]
OK since you asked..

🙏 Please consider becoming a pdfcpu 💚 sponsor.

We here at pdfcpu headquarters could need some additional encouragement to keep going
and do what we love which is fixing all your issues and implementing all your feature requests.

**Comment by hhrutter** [comment]
Should be fixed with latest commit!

**Comment by hhrutter** [comment]
I open the filled forms on MacOs in Chrome (110.0.5481.177) and everything's looking good.
Can you verify this for me?

**Comment by hhrutter** [comment]
I closed this for a reason.
In order to get to the root of this please answer my questions:

1) Can you verify you see the checked Checkboxes for forms filled with pdfcpu on MacOS/Chrome?

2) Which OS Chromeversion are you using?

Thank you!

**Comment by owenhankinson** [comment]
1. I verify I see them in the Mac file viewer "Preview" (see screenshot 1 below) but on the chrome browser viewer, I cannot see these boxes checked. (see screenshot 2 below)
2. I am on Chrome Version 110.0.5481.177 (Official Build) (arm64)

### MacOS "Preview" Application
<img width="1062" alt="Screenshot 2023-03-13 at 9 20 19 AM" src="https://user-images.githubusercontent.com/75053404/224762936-d702a293-edbc-4a45-80a2-287d4e40cb14.png">

### Chrome Web Browser PDF Viewer
<img width="797" alt="Screenshot 2023-03-13 at 9 22 53 AM" src="https://user-images.githubusercontent.com/75053404/224763626-994c9256-643c-493b-93c9-58b2bb560877.png">

**Comment by hhrutter** [comment]
Are you sure you are on the latest commit?

Then export the json again and then refill.

Working for me on MacOs A.Reader & Chrome
Couldn't care less for Mac Preview for PDF forms.

**Comment by owenhankinson** [comment]
`> pdfcpu version pdfcpu: v0.4.0 dev` am I on the wrong version? When I use your go get there I see it is downloading version 3.14...

**Comment by hhrutter** [comment]
Looks like you are not running the latest commit.
You should be on commit: a410fdc3253318

Just follow the instructions in the [README.md](github.com/pdfcpu/pdfcpu):
```
git clone https://github.com/pdfcpu/pdfcpu
cd pdfcpu/cmd/pdfcpu
go install
```

or instead of cloning do:
You can replace `git clone...` with `go get github.com/pdfcpu/pdfcpu@master` which will download the latest commit on master.

If you don't succeed,  please post the output of: 
`go list -m -json github.com/pdfcpu/pdfcpu@master`

if you are running into timeout issues see #567

**Comment by owenhankinson** [comment]
looks like that did it, thanks so much for your help!
