### ISSUE TITLE
stamp: page x of y

### ISSUE THREAD

**Issue by a695918236** [pdfcpu/pdfcpu#577]

**Comment by hhrutter** [comment]
I am not sure I understand your question, but..

If you want to create stamps/watermarks e.g in a footer showing "Page x of y" 

.. you can do smth like `pdfcpu stamp add -mode text "Page %p of %P" "" in.pdf out.pdf`

In future  🙏  post your questions on the [pdfcpu discussion board](https://github.com/pdfcpu/pdfcpu/discussions)

Thank you!

**Comment by hhrutter** [comment]
Closed due to inactivity.
