### ISSUE TITLE
form processing error

### ISSUE THREAD

**Issue by StefanSchroeder** [pdfcpu/pdfcpu#579]
I did a fresh checkout from master. OS=Windows 10, Go=1.18

It's possible to create AcroForm PDFs using pdflatex. This is a minimal tex-file.
It compiles with Miktex. It can be opened in Acrobat Reader. 
The checkbox can be ticked and unticked.

```
\documentclass{article}
\usepackage[T1]{fontenc}
\usepackage[utf8]{inputenc}
\usepackage{insdljs}
\begin{document}
Hello Form.
\begin{Form}
\CheckBox[name=iamalittlecheckbox]{}
\end{Form}
\end{document}
```

The original PDF as produced by pdflatex provokes this error in pdfcpu
when calling *pdfcpu form list*

```
pdfcpu: DereferenceStreamDict: wrong type <<<
>>> types.Dict
```

Strangely enough, when opening the file in Acrobat and saving it _without_ changes, the file is properly processed. The result now is:

```
minimal.pdf
Pg L Field     │ Name
━━━━━━━━━━━━━━━┿━━━━━━━━━━━━━━━━━━━━
 1   CheckBox  │ iamalittlecheckbox
```

The error is thrown in 
pkg/pdfcpu/model/xreftable.go, line 854

Expected behavior: 
The PDF should be processed like indicated at the bottom without ever throwing the error mentioned above.

The original file (=unsaved in Acrobat, producing the error)
http://www.tokonoma.de/orig.pdf

The updated (saved in Acrobat, no error)
http://www.tokonoma.de/minimal.pdf

**Comment by hhrutter** [comment]
Your file does not pass validation.

Always ensure you have a valid file if you intend to process it with pdfcpu:
`pdfcpu val in.pdf`

This needs further investigation

**Comment by StefanSchroeder** [comment]
Thank you, Horst, for the quick and thorough analysis. I will recompile w/ 1.20 and make sure that I am on HEAD. Also, I will check why the original file does not pass validation. 🌻

**Comment by hhrutter** [comment]
The spec says unter table 168:

*...Each entry in the appearance dictionary may contain either a single appearance stream or an appearance subdictionary. In the latter case, the subdictionary shall define multiple appearance streams corresponding to different appearance states of the annotation.*

Your file is using an appearance subdict using an unexpected dict value for key "Yes":
```
<AP, <<
		<N, <<
			<Yes, <<
			>>>
		>>>
>>>
```

**Comment by StefanSchroeder** [comment]
Well, I am surprised that a mature application like pdflatex would produce non-conformant files.
I am not sure if I am going to escalate this in the pdflatex eco-system.

**Comment by hhrutter** [comment]
pdfcpu complies with PDF 1.7 (ISO-32000) (which is already superseded by PDF 2.0.)
I can't tell if this is the issue here though.
I will look into relaxing validation for this.

**Comment by petervwyatt** [comment]
@hhrutter please refer to ISO 32000-1:2008 clause 12.7.4.2.3 EXAMPLE 1 where a similar example for a checkbox field is explained (**Yes** is the name of the on-state for a checkbox). 
The wording in PDF 1.7 (ISO 32000-1) around appearance dictionaries has since been improved throughout PDF 2.0 (ISO 32000-2).

**Comment by hhrutter** [comment]
Exactly - The value of an appearance sub dictionary has to be a stream dict.
Whereas in the above test file the value is an empty dict - no stream dict.
Just confirming my stance, please correct me if I am wrong:

<img width="669" alt="Screen Shot 2023-03-10 at 00 05 40" src="https://user-images.githubusercontent.com/11322155/224180741-e2f9d5cb-4b82-485e-ac6c-90401ebe6040.png">

**Comment by petervwyatt** [comment]
Might you consider this degenerate as appearance streams are not required in PDF 1.7 (they are in PDF 2.0) but other shall statements imply certain data structures... so is it any different to an appearance content stream with zero length (no operators), and zero height/width BBox? 
I'll let you decide what is best for pdfcpu :-)

**Comment by hhrutter** [comment]
This should be fixed with latest commit!

**Comment by StefanSchroeder** [comment]
@hhrutter I confirm the defect is resolved. You are my hero :-)

**Comment by hhrutter** [comment]
If you are a happy user..
Please 🙏  spread the word and consider becoming a pdfcpu 💚 sponsor.
Sponsorship ensures pdfcpu stays alive and well maintained for the foreseeable future.
