### ISSUE TITLE
cli: validate using wildcard: no output unless validation error

### ISSUE THREAD

**Issue by lgaudreau** [pdfcpu/pdfcpu#583]
I'm using a loop to scan a folder with 1000s of PDFs.  It would be very nice to have only validation errors returned with the file name generating the error.

**Comment by hhrutter** [comment]
OK I can see that while validating a bunch of files even using quiet mode:

`pdfcpu validate -q *.pdf`

validation errors are output properly but without the corresponding file name.

**Comment by hhrutter** [comment]
This is fixed with the latest release.
