### ISSUE TITLE
api: watermark blank page

### ISSUE THREAD

**Issue by lxjxiaojun** [pdfcpu/pdfcpu#584]
I'm using AddWatermarksFile to add watermark to pdf files. In most cases it works, but I found one particular file, the output file was totally blank page. 
I was try to  validate it by `api.ValidateFile`, and the output was validation ok.(mode=relaxed btw). I was totally confused.

**Comment by hhrutter** [comment]
Hello!

`Watermarking` means you stamp  your page with a watermark.

You can either stamp the page before the page content gets rendered (`onTop = false`)
or you can stamp the page after page content gets rendered  (`onTop = true`).

In your case it sounds like you are using `onTop=false` and there may be some scanned image sitting on top of your watermark and therefore hiding it.

Make sure you use `onTop = true` when you create your watermark and set some opacity eg. 0.5.

**Comment by lxjxiaojun** [comment]
Thanks for your reply.

I do use `onTop = true`, here is my code:

`pdfcpu.ParseTextWatermarkDetails("test text", "sc:1,points:24,opacity:0.3,rot:30,fillcolor:#BEC4D5", true, types.POINTS)`

In my case, `AddWatermarksFile ` works properly of most files, but for one particular file, the original file can shows with adobe reader, after AddWatermarksFile, the output file is totally blank.

**Comment by hhrutter** [comment]
Please submit your file for analysis
Thank you.

**Comment by lxjxiaojun** [comment]
[0e499edf-4590-46d1-91fb-c9dd7209ef15.pdf](https://github.com/pdfcpu/pdfcpu/files/10950225/0e499edf-4590-46d1-91fb-c9dd7209ef15.pdf)

here is my file

**Comment by hhrutter** [comment]
This is fixed with the latest commit.
