### ISSUE TITLE
api: form export to memory

### ISSUE THREAD

**Issue by kben** [pdfcpu/pdfcpu#586]
Dear Horst,

I like to discuss a factoring of the current code to be able to call the API without writing/reading a json file. The extension of the code would move the current reads/writes out of the "pkg/pdfcpu/form/export.go" functions, so that those function just get the structs.

What do you think?

best regards
ben

**Comment by hhrutter** [comment]
Hello!

We can go in all kind of directions but the filling API is on hold until we reach stability to take it to the next level.
Until then please keep feeding JSON and report back any issues.

I have been working a full year on pdfcpu's form support and I am not inclined to take any premature steps right now.
Thank you for using pdfcpu 💚

**Comment by kben** [comment]
Alright. Just for completeness, the extension would only be in the export functions. The fill command can be used without json files.

**Comment by hhrutter** [comment]
This is fixed with the latest release.
