### ISSUE TITLE
How to set a background image for a specific page？ 

### ISSUE THREAD

**Issue by gunsluo** [pdfcpu/pdfcpu#587]
User case:  How to set a background image for a specific page？ e.g. I want to set the background image bg.png to 1st page of the PDF file.

`api.ImportImages` will import pictures to the last page of the PDF document. so any methods to set a background image with `pdfcpu`?   note: there may be text and other content on the page. 

@hhrutter  thank you in advance.

**Comment by gunsluo** [comment]
another question:  
Internal redirect links in PDF do not work properly after using api.Merge for multiple files. 

[PDFBox](https://github.com/nilostolte/PDFBox) works fine.


### Case: 
```
inFiles := []string{
		"test_fixtures/title.pdf",
		"test_fixtures/2.pdf",
	}

	// err := api.MergeCreateFile(inFiles, "out.pdf", nil)
	// if err != nil {
	// 	t.Fatal(err)
	// }

	f, err := os.Create("out.pdf")
	if err != nil {
		t.Fatal(err)
	}

	defer func() {
		cerr := f.Close()
		if err == nil {
			err = cerr
		}
	}()

	api.Merge("", inFiles, f, nil)
```

[2.pdf](https://github.com/pdfcpu/pdfcpu/files/10977835/2.pdf)
[title.pdf](https://github.com/pdfcpu/pdfcpu/files/10977837/title.pdf)

**Comment by hhrutter** [comment]
please open a new issue for this.
thank you.

**Comment by hhrutter** [comment]
If you create your PDF from scratch and via JSON you have full control over the background color for specific pages.

**Comment by hhrutter** [comment]
Just add an image watermark on page 1 eg. on the cmdline: 
`pdfcpu watermark add -page 1 -mode image "backgr.png" "rot:0, sc:1.0 rel" in.pdf out.pdf`

**Comment by gunsluo** [comment]
I will try. thank you very much.

**Comment by gunsluo** [comment]
it works fine. thank you very much.
