### ISSUE TITLE
api: extract images runtime error

### ISSUE THREAD

**Issue by mrg0lden** [pdfcpu/pdfcpu#588]
Hello,

I have faced a panic due to access to out-of-bounds memory in the following location

https://github.com/pdfcpu/pdfcpu/blame/97106ac80a20a9688acc4ca3380cfe1a76af4251/pkg/pdfcpu/writeImage.go#L479

**Comment by hhrutter** [comment]
Hello!

Interesting issue!
Do you think you can share the file in question and the details surrounding your usecase?
I am guessing you are extracting images via CLI/API?

You can also send me an email hhrutter@gmail.com

**Comment by mrg0lden** [comment]
Hello, yes as you mentioned, I'm trying to extract images from PDF files using the pdfcpu API, I'll try to share a PDF ASAP

**Comment by mrg0lden** [comment]
I shared the PDF through Google Drive to your provided email.

Here's the snippet I'm using to extract images

```
func (e *PDFImagesExtractor) extractUsingPDFCPU(refID uint64, pdf []byte) (imgs [][]image.Image, err error) {
	defer func() {
		err = fmt.Errorf("PDFCPU Panic: %s", recover())
	}()

	pdfR := bytes.NewReader(pdf)
	count, err := pdfcpuAPI.PageCount(pdfR, nil)
	if err != nil {
		e.log.Error("pdfcpu: failed to count PDF pages", refID, err)
		return nil, err
	}

	buf := bytes.Buffer{}

	for i := 0; i < count; i++ {
		pageImgs := []image.Image{}
		pdfcpuAPI.ExtractImages(pdfR, []string{fmt.Sprintf("%d", i+1)}, func(pImg pdfcpu.Image, _ bool, _ int) error {
			if pImg.Reader == nil {
				return nil
			}
			buf.Reset()
			buf.ReadFrom(pImg.Reader)

			img, _, err := image.Decode(&buf)
			if err != nil {
				e.log.Error("pdfcpu: failed to parse image", refID, err)
				return nil
			}

			pageImgs = append(pageImgs, img)

			return nil
		}, nil)

		imgs = append(imgs, pageImgs)
	}

	if len(imgs) == 0 {
		return nil, err
	}

	return imgs, nil
}
```

**Comment by hhrutter** [comment]
Are you on the latest release?
Image extraction for your test file works fine using the current CLI.
This means it has to work also using the API.

**Comment by hhrutter** [comment]
Closed due to inactivity.
