### ISSUE TITLE
merge named destinations

### ISSUE THREAD

**Issue by gunsluo** [pdfcpu/pdfcpu#591]
User case: I directly use `api.Merge` to merge multiple PFD files into one, code and test PDF, please see below.

[2.pdf](https://github.com/pdfcpu/pdfcpu/files/10977835/2.pdf)
[title.pdf](https://github.com/pdfcpu/pdfcpu/files/10977837/title.pdf)
```
inFiles := []string{
		"title.pdf",
		"2.pdf",
	}

	// err := api.MergeCreateFile(inFiles, "out.pdf", nil)
	// if err != nil {
	// 	t.Fatal(err)
	// }

	f, err := os.Create("out.pdf")
	if err != nil {
		t.Fatal(err)
	}

	defer func() {
		cerr := f.Close()
		if err == nil {
			err = cerr
		}
	}()

	api.Merge("", inFiles, f, nil)
```

Results:  link in the merged file cannot jump properly.
<img width="1016" alt="image" src="https://user-images.githubusercontent.com/9067076/225643856-c3d94e64-4e21-4a13-aba7-decbc7ccea7c.png">

Expected: the link still works fine. 

Other tools: [PDFBox](https://github.com/nilostolte/PDFBox) works fine.

**Comment by hhrutter** [comment]
👍

**Comment by hhrutter** [comment]
This is fixed with the latest release.
