### ISSUE TITLE
api:  Print Object String  and not raw text  

### ISSUE THREAD

**Issue by dachengai** [pdfcpu/pdfcpu#592]
* v0.4.0

=======  my code: ============
`
// Create a context.
ctx, err := api.ReadContextFile("./test.pdf")
if err != nil {
      fmt.Println("readContext: %v\n", err)
      return err
}

// Optimize resource usage of this context.
if err := api.OptimizeContext(ctx); err != nil {
      fmt.Println("optimizeContext: %v\n", err)
      return err
}

// Get page and print content 
for i := 1; i <= ctx.PageCount; i++ {
	page, err := pdfcpu.ExtractPage(ctx, i)
	if err != nil {
	    fmt.Println("extractPageContent(%d): %v\n", i, err)
	}
	// print by index order
    var indexs []int
    for k := range page.Table {
            indexs = append(indexs, k)
    }
    sort.Ints(indexs)
	for _, index := range indexs {
        v := page.Table[index]
        if v.Free || v.Compressed {
            fmt.Println("page value:", v.Free, v.Compressed)
            continue
        }
        fmt.Println("Object String:",v.Object.String())
    }

}
`
outputs not contain  raw text like:

This is  test content1
This is  test content2
This is  test [content3]

[outputs.txt](https://github.com/pdfcpu/pdfcpu/files/11010189/outputs.txt)
[test.pdf](https://github.com/pdfcpu/pdfcpu/files/11010191/test.pdf)

**Comment by hhrutter** [comment]
Hello!
The described behavior is correct.
You are just dumping the PDF objects.

**Comment by hhrutter** [comment]
Closed due to inactivity.
