### ISSUE TITLE
extract: memory usage

### ISSUE THREAD

**Issue by tarekziade** [pdfcpu/pdfcpu#595]
Hi there, thanks for this cool project. 

One feature I would love to see is extracting large files without loading the whole file in memory.
This is how `pdftotext` and `pdfminer` are doing, by loading the structure of the PDF through seek calls, for example https://github.com/pdfminer/pdfminer.six/blob/master/pdfminer/pdfparser.py#L61

It's a huge performance improvement for large files. For instance, a 750MiB PDF file of text content will take  17MiB of RSS.

I am not a Go developer, but if that's something interesting, I can study how to implement a patch

**Comment by hhrutter** [comment]
Hi!

What do you mean by extracting large files?
Please describe your usecase in detail.
Thank you for using pdfcpu 💚

**Comment by tarekziade** [comment]
> What do you mean by extracting large files?
> Please describe your usecase in detail.

Sure :)

- take a PDF that is 1GiB
- extract its text content by running pdfcpu 
- pdfcpu should not exceed 50MiB in Resident Set Size

**Comment by hhrutter** [comment]
pdfcpu can extract all kinds of things hence the question...
OK, are you using the cli: `pdfcpu extract -mode content .....`
or are you calling directly `api.ExtractContent` ?

**Comment by tarekziade** [comment]
I am using the CLI, so `pdfcpu extract -mode content`

**Comment by tarekziade** [comment]
About the title : I don't think it's a memory leak, it's just that you load the whole file in memory

```
$ /usr/bin/time -l pdfcpu extract -mode content huge.pdf res/
[..]
        4.03 real         3.07 user         1.05 sys
          1284911104  maximum resident set size
                   0  average shared memory size
                   0  average unshared data size
                   0  average unshared stack size
              314165  page reclaims
                   0  page faults
                   0  swaps
                   0  block input operations
                   0  block output operations
                   0  messages sent
                   0  messages received
                 435  signals received
                 218  voluntary context switches
                6657  involuntary context switches
         20612947804  instructions retired
         14103187806  cycles elapsed
          1280585728  peak memory footprint
```

Maximum RSS : 1284911104 (so over a GiB in memory)

with `pdftotext`:

```
$ /usr/bin/time -l pdftotext huge.pdf output.txt
        5.22 real         3.18 user         0.25 sys
            18968576  maximum resident set size
                   0  average shared memory size
                   0  average unshared data size
                   0  average unshared stack size
                4926  page reclaims
                 100  page faults
                   0  swaps
                   0  block input operations
                   0  block output operations
                   0  messages sent
                   0  messages received
                   0  signals received
                  57  voluntary context switches
                 952  involuntary context switches
         23010826569  instructions retired
         12273964631  cycles elapsed
            15704064  peak memory footprint
```
                
Max RSS: 18968576 (so ~17MiB)


File used https://ziade.org/huge.pdf

**Comment by hhrutter** [comment]
This should be addressed by https://github.com/pdfcpu/pdfcpu/releases/tag/v0.8.0
