### ISSUE TITLE
In-memory work

### ISSUE THREAD

**Issue by ostiwe** [pdfcpu/pdfcpu#596]
Hi, please tell me why it is impossible to merge several pdf files without using the file system?

I mean the api.

For example, I have 10 pdf files that need to be merged into one. At the same time, divide each of them with one empty sheet.

I saw the `before` parameter in the `InsertPagesFile` method, but it doesn't work as expected. I expect that after each "file" there will be a blank sheet. And as a result, a pdf is generated where an empty sheet is generated through each sheet.

It is also unclear how to work with the "selectedPages" parameter. I do not know how many pages there will be in each of the files.

Returning to the first question, why can't I collect `[]byte` of all files and then merge them? At the same time, add empty pages.

For example, I see it like this:

```go
	var fileFids = []string{
		"afd49fb5-3f73-4570-a01f-edb70a5142f5",
		"a78e3ec1-3d21-48b4-ba51-a67a9b0be02e",
		"855f0215-fe92-4bd9-b99b-4f650daaaa85",
	}

	var fileContents [][]byte

	for i := range fileFids {
		fileContent, err := storage.GetPDFFromExternalStorage(fileFids[i])
		if err != nil {
			panic(err)
		}

		fileContents = append(fileContents, fileContent)
	}


	pdfFile := pdfcpu.NewPDFFile("/some/file/name.pdf")

	for i := range fileContents {
		pdfFile.Append(fileContents[i])
		pdfFile.InsertBlankPage()
	}


	err := pdfFile.Save()
	if err != nil {
		panic(err)
	}
```

**Comment by ostiwe** [comment]
This is a cool project, but there are very few methods for working on the fly without using the file system

**Comment by hhrutter** [comment]
Hello!
Please do me a favor and open appropriate threads in [Discussions](https://github.com/pdfcpu/pdfcpu/discussions) if you have questions. 
The whole community will benefit from this.
Thank you for using pdfcpu 💚

**Comment by ostiwe** [comment]
https://github.com/pdfcpu/pdfcpu/discussions/597
