### ISSUE TITLE
Incorrect PNG import with transparency

### ISSUE THREAD

**Issue by alexander-miroch** [pdfcpu/pdfcpu#598]
A png file with a trasparent area is malformed when converted to the pdf.

Source file
https://joyplanet.store/page11.png

Result:
https://joyplanet.store/297448b1-5764-42e6-b122-23e3516d3a67-inner.pdf

Code snippet

`file := "page11.png"`
`output := "297448b1-5764-42e6-b122-23e3516d3a67-inner.pdf"`
`api.ImportImagesFile([]string{file}, output, nil, nil)`

Ubuntu 20.04
go version go1.19.1 linux/amd64

**Comment by hhrutter** [comment]
Hi!
Could you make your files available for analysis?
The links don't work.

**Comment by alexander-miroch** [comment]
Hi, I'm sorry, These are new links

source file
https://r.verycloud.io/page11.png

result
https://r.verycloud.io/297448b1-5764-42e6-b122-23e3516d3a67-inner.pdf

**Comment by hhrutter** [comment]
This is fixed with the latest release.
