### ISSUE TITLE
Reverse booklet

### ISSUE THREAD

**Issue by jessdwitch** [pdfcpu/pdfcpu#599]
Maybe this already exists and I'm bad at reading the docs, but I've got 2 pdfs, both with 2 "pages" per PDF page (side by side in landscape). One of them is a print-ready zine, so the first PDF page has the cover on the left and the back of the zine on the right, the second PDF page has the first page of content on the left and the last page of content on the right, etc. The other one is more like a book, and on the first PDF page has the cover on the left, and the first content page on the right. The second PDF page has the second content page on the left and the third content page on the right and so on.

I want to do the reverse of the `booklet` operation to these and turn them into 1 content page per PDF page: the cover on the first PDF page, the first content page on the second PDF page, second content page on the third PDF page and so on.

Is that possible or is this a feature request?

**Comment by hhrutter** [comment]
Hi!
This sounds more like a usecase of the upcoming `cut` command - will be part of the next release.
See #467, #557, #573#

**Comment by jessdwitch** [comment]
#467 Is exactly what I'm trying to do! Weird thing, I ended up doing the same thing they did with the `crop` even and odd then `merge`d them, then used `collect` to rearrange the pages to be in the correct order:

```bash
pdfcpu crop -- "pos: br, dim: .999 .5" ./tmp/source.pdf ./tmp/evens.pdf
pdfcpu crop -- "pos: tl, dim: .999 .5" ./tmp/source.pdf ./tmp/odds.pdf
pdfcpu merge ./tmp/merged.pdf tmp/odds.pdf tmp/evens.pdf
pdfcpu collect -p `python -c "print(','.join([str(x) for y in zip(range(1,51),range(51,100)) for x in y]))"` ./tmp/merged.pdf ./tmp/sorted.pdf
pdfcpu booklet ./tmp/print.pdf 2 ./tmp/sorted.pdf
```

The book is 100 pages and the python script is just generating a string that's like `1,51,2,52,3,52,...`
(Also, this feels like a textbook usecase for being able to pipe inputs/outputs)

This mostly works! `booklet` is where it gets weird. Half the pages are correct, but the other half are offset? There's like a block of whitespace at the beginning that pushes them all down, so they're half on the correct page and half on the next. This block of whitespace is not present in `sorted.pdf`. Any idea what's going on there?

**Comment by hhrutter** [comment]
Seems like one of these command messes up in your specific case.
Difficult to analyze this w/o your file..
Please, stay tuned for the upcoming release.

**Comment by hhrutter** [comment]
Please check with latest commit and post a test file for further analysis if the issue persists.
Thank you!

**Comment by hhrutter** [comment]
Closed due to inactivity.
