### ISSUE TITLE
Extract Image：The exported image is reversed

### ISSUE THREAD

**Issue by zy520321** [pdfcpu/pdfcpu#600]
Hi,
1.On the latest commit
2.win10
3.Original file and the exported image,as follows:
[2.pdf](https://github.com/pdfcpu/pdfcpu/files/11190042/2.pdf)
![2_1_IM7](https://user-images.githubusercontent.com/9145848/230889356-602fbaa7-d966-48c3-b5b6-5fd686827c99.jpg)

**Comment by hhrutter** [comment]
Fixed!
