### ISSUE TITLE
Unable to read due to no header version available error

### ISSUE THREAD

**Issue by ZackPoormanCalder** [pdfcpu/pdfcpu#605]
## Description
- Unable to read pdfs using pdfcpu api due to following error: `Read: xRefTable failed: pdfcpu: headerVersion: corrupt pdf stream - no header version available`
  - This happened while using version 0.4.0 of pdfcpu
  - I used the pdfcpu cli tool to validate all 3 files and they validated successfully (one of the validations below)
![Screenshot 2023-04-17 at 7 11 17 AM](https://user-images.githubusercontent.com/129113877/232481391-576adfde-5949-4211-9ed2-2a7cbb284e49.png)

- Emailed first 100 bytes of the 3 pdfs
- OS: Mac Ventura 13.3.1 & Ubuntu 20.04

**Comment by hhrutter** [comment]
Hi!
I don't see why reading via the API should cause you any problems for files validated on the CLI unless the config files in both cases differ maybe. Please share your API code that fails.

**Comment by ZackPoormanCalder** [comment]
Hi and thank you for the quick response!

Here's the API code 
```
// API is imported as: pdfcpu "github.com/pdfcpu/pdfcpu/pkg/api"

fileName := "some_file.pdf"
err := pdfcpu.RotateFile(fileName, "", 270, nil, &pdfcpuConfig.Configuration{Reader15: true, WriteObjectStream: true, Eol: "\r\n", ValidationMode: pdfcpuConfig.ValidationNone})
if err != nil {
    logging.Error("Error Rotating PDF: %v", err.Error())
    return 0, 0, 0, err
}
```

**Comment by hhrutter** [comment]
Have you compared the configurations you are using in API vs CLI ?
Especially watch out for `headerBufSize`

**Comment by ZackPoormanCalder** [comment]
I haven't and am using the default config for the CLI so the configs are different.
After running the validate command in the CLI with the config matching the API config it outputs `validate: mode === ValidationNone`. Wouldn't a similar thing happen in the API since we've set `ValidationMode` to `ValidationNone`?

**Comment by ZackPoormanCalder** [comment]
When running the `RotateFile` with `ValidationMode: ValidationNone` shouldn't it not run the validation? From the error message it appear to be attempting to validate the pdf

**Comment by hhrutter** [comment]
Which error message?
You need to set a headerBufSize >= 100 if you are passing your own configuration.

**Comment by ZackPoormanCalder** [comment]
Thank you, I didn't realize that I had to set the headerBufSize >= 100.

After setting headerBufSize > 100, I now get the following error when using the api to rotate the file: `Read: xRefTable failed: parseTrailerDict: PDF1.4 conformant reader: found incompatible version: 1.7`. Are there additional debugging steps I should take that will help?

**Comment by hhrutter** [comment]
My guess is your configuration has a problem.

The error you are reporting needs `config.Reader15` to be `false` but in your code above you set it to `true`.

Hard to tell without having the PDF in front of me.
The fact that you need to increase the headerBufSize > 100 indicates a PDF that deviates from the spec, so trouble may be ahead.

In any case validate your file first: `pdfcpu validate test.pdf`
Just edit your config file and increase the headerBufSize
Once you know the file validates move on to using the API.

**Comment by ZackPoormanCalder** [comment]
Unfortunately I am unable to share the pdf without multiple approvals by the pdf writers.

I was able to validate the pdfs with an updated config. When using the same config for the api the api fails to `RotateFile` still.
Here's the config used for both the pdfcpu cli and api:
```
{
Reader15: true, 
WriteObjectStream: true, 
WriteXRefStream: true,
DecodeAllStreams: true,
Eol: "\r\n",
ValidationMode: model.ValidationNone,
HeaderBufSize: 100
}
```
When using the above config I get the error `Recovered from panic: Failed to initialize parser: Failed to read pdf: Failed to to read pages: Failed to resolve pages object: Failed to resolve compressed object: Object ID (16) does not match ObjSpec ID (15)`.
If I change the `config.Reader15` to `false` then I get the error `Read: xRefTable failed: parseTrailerDict: PDF1.4 conformant reader: found incompatible version: 1.7`.

**Comment by ZackPoormanCalder** [comment]
Just checking in on options to fix this. Do you think this is still a config issue?

**Comment by ZackPoormanCalder** [comment]
I think I need separate configurations for pdfcpu to support pdfs that are version 1.4 and versions >1.4. Do you know the required settings to set since the default configuration throws `Read: xRefTable failed: parseTrailerDict: PDF1.4 conformant reader: found incompatible version: 1.7`.

**Comment by hhrutter** [comment]
Looks like you are dealing with a problematic file after all.
If you can share it I may be able to tell you if we can repair it.

**Comment by hhrutter** [comment]
Closed due to inactivity
