### ISSUE TITLE
validation error : FontFamily invalid type

### ISSUE THREAD

**Issue by xschmets** [pdfcpu/pdfcpu#606]
Hello,

I encountered an error while working (merge, ...) on a PDF.

The validation output :

pdfcpu validate TP1.pdf
validating(mode=relaxed) TP1.pdf ...
validation error (obj#:32): pdfcpu: validateStringEntry: dict=fdDict entry=FontFamily invalid type

Tested with versions 0.3.5, 0.3.13 and 0.4.0. Same result.
OS : Windows 11 Pro 22H2

Can you help ?

Thank you ;-)

Xavier

**Comment by hhrutter** [comment]
Possibly.
Can you provide a stack trace or sampe file for reproduction/analysis?

**Comment by hhrutter** [comment]
This is fixed with latest commit.
