### ISSUE TITLE
Merge files with numeric prefixes

### ISSUE THREAD

**Issue by Nemo08** [pdfcpu/pdfcpu#607]
Hi developer!
Can you add ability to sort merged files with numberic prefixes / postfixes?
E.g.
1. file.pdf
2.  file.pdf
....
12. file.pdf

Thanks to your work!

**Comment by hhrutter** [comment]
Hi!

I am not sure I understand.
Please give a detailed example of your usecase.

**Comment by hhrutter** [comment]
I'll check it out. 
There were already suggestions alike.

**Comment by joelschutz** [comment]
I created a PR #631 to deal with this issue.

**Comment by hhrutter** [comment]
This PR was merged in.
Please go install the latest commit.
