### ISSUE TITLE
Merge files with bookmarks

### ISSUE THREAD

**Issue by Nemo08** [pdfcpu/pdfcpu#608]
Can merged file save bookmarks from source files?
And maybe add to merged file file names as bookmark?

Thanks to your work!

**Comment by Nemo08** [comment]
Maybe like in other famous program? Tree bms like:
Merged-file1
    bm_from_file1_1
    bm_from_file1_2
Merged-file2
Merged_file3
    bm_from_file3_1
    bm_from_file3_1

**Comment by hhrutter** [comment]
Other famous programs? 
Please elaborate!

**Comment by Nemo08** [comment]
Adobe acrobat dc

**Comment by simonebortolin** [comment]
Nitro PDF

**Comment by hhrutter** [comment]
👍 Got it!
We can do this.

**Comment by hhrutter** [comment]
This is fixed with https://github.com/pdfcpu/pdfcpu/releases/tag/v0.4.2
