### ISSUE TITLE
read error

### ISSUE THREAD

**Issue by Tangerg** [pdfcpu/pdfcpu#611]
![image](https://user-images.githubusercontent.com/37281233/234156491-e6f22700-fb71-48dc-89a9-f4c5cd5d8438.png)
if the head !=nil and head.Generation ==nil, panic
![1682388378890](https://user-images.githubusercontent.com/37281233/234156665-67af7ce0-4adc-44be-99dc-0aa971ca5b69.png)

**Comment by hhrutter** [comment]
Understood!
Do you have a sample you can share for analysis?

**Comment by Tangerg** [comment]
![image](https://user-images.githubusercontent.com/37281233/234445092-acc286cc-9a4d-412d-b480-87c1d6a4db59.png)
when I use this function, I can't give you more file because it's a private PDF, sorry

**Comment by hhrutter** [comment]
Is this an API integration?
What are feeding into PageCount as rs?
May I see more of your code?

**Comment by hhrutter** [comment]
This issue is related to your input file.

Get the latest release and try this:

xreftable.go line 698: `if head.Generation == nil || *head.Generation != types.FreeHeadGeneration {`

Let me know if this works for you!

**Comment by hhrutter** [comment]
Closed due to inactivity.
