### ISSUE TITLE
Unable to fill PDF with pdfcpu API

### ISSUE THREAD

**Issue by hrushya07** [pdfcpu/pdfcpu#613]
### pdfcpu: missing header/footer heightpanic: Error

```
conf := &model.Configuration{
      CheckFileNameExt:                true,
      Reader15:                        true,
      DecodeAllStreams:                false,
      ValidationMode:                  model.ValidationRelaxed,
      Eol:                             "EolLF",
      WriteObjectStream:               true,
      WriteXRefStream:                 true,
      EncryptUsingAES:                 true,
      Permissions:                     model.PermissionsNone,
      Unit:                            types.POINTS,
      TimestampFormat:                 "2006-01-02 15:04",
      DateFormat:                      "2006-01-02",
      HeaderBufSize:                   100,
      OptimizeDuplicateContentStreams: false,
}
err := api.CreateFile(PDF_PATH, FILLED_JSON_PATH, OUTPUT_PATH, conf)
```

<img width="1100" alt="Screenshot 2023-04-27 at 9 42 06 AM" src="https://user-images.githubusercontent.com/85426572/234757878-f677093f-bcde-4a77-a1b4-7f85792d99d3.png">

**Comment by hhrutter** [comment]
You need to specify a height in your JSON for your header/footer.

**Comment by hrushya07** [comment]
Is this correct ? Beacuse after this im again getting same error
<img width="644" alt="image" src="https://user-images.githubusercontent.com/85426572/234563727-e174f4ee-f46f-4757-8432-20f78f62deb9.png">

**Comment by hhrutter** [comment]
Please explain your usecase then I can help you.

You may also post a stacktrace, that also helps.

**Comment by hrushya07** [comment]
Sure, So i want to fill a PDF and populate all the necessary fields.
Process i have done is -
1. Used cmd line to generate a json from pdf [pdfcpu form export <pdf_path> <json_path>]
2. filled json and now want to fill pdf using this json.

**Now on thing pdf is populating with cmd line [ie - pdfcpu form fill <pdf_path> <filled_json_path> <generated_pdf_path>]
but when tried to use its api [ie - api.CreateFile(pdf_path, filled_json_path, generated_pdf_path, config)], it is giving me error**

**Comment by hhrutter** [comment]
I guess all you are trying to do is fill a form and not creating a PDF..

The form export only exports your form fields.
You then edit the json and do a `pdfcpu form fill`.
During filling the header (containing metadata only) generated by export will be ignored!

**Comment by hrushya07** [comment]
So we are able to generate the pdf using cmdline
ie `pdfcpu form fill`
But with same input we are not able to generate pdf by golang implementation which is
`api.CreateFile(pdf_path, filled_json_path, generated_pdf_path, config)`

This is giving us error -
`pdfcpu: missing header/footer heightpanic: Error`

We are not getting why only golang implementation is having issue

**Comment by hhrutter** [comment]
For form filling integration into your backend you need to use `api.FillFormFile`.
See https://github.com/pdfcpu/pdfcpu/blob/master/pkg/api/test/form_test.go

**Comment by hrushya07** [comment]
> We are not getting why only golang implementation is having issue -

we filled a pdf using pdfcpu cmdline tool but when we want to fill same thing using code block which we are writing in golang it was giving us error.

As you mentioned regarding `api.FillFormFile`, we also tried but it was also throwing error - `pdfcpu: corrupt form field: missing entry FTpanic: Error`
Error for reference - 
<img width="407" alt="image" src="https://user-images.githubusercontent.com/85426572/235421622-4a7bb1a8-3857-4f8d-bc76-e52ffac124df.png">

**Comment by hhrutter** [comment]
If you are using exactly the same PDF input file for form filling via CLI and API and it works for either one then it should work both ways.

I need to see a stack trace.

**Comment by hrushya07** [comment]
Hello @hhrutter, It is no more issue now, We were exporting the json from one version and was filling the from from different version
Thank you for your support.
