### ISSUE TITLE
please provide the owner password with -opw

### ISSUE THREAD

**Issue by 981349873** [pdfcpu/pdfcpu#614]
![image](https://user-images.githubusercontent.com/20148421/234856269-08ff5af7-39f4-4b23-a621-01beea65a27e.jpeg)
Hi,the code report this,but this pdf doesn't have
 Pwd,I just want to modify the permissions

**Comment by hhrutter** [comment]
Have you tried passing an empty string for the owner password explicitly?
`-opw ""`

**Comment by 981349873** [comment]
Hi,yes i have tried use '' ,but also report this,and the 1.pdf has no password,it just doesn't have the copy permission,I have tried use python pypdf2 to deal this pdf, it's normal.

**Comment by hhrutter** [comment]
I need to see your PDF in order to reproduce, analyse and fix this.
You can send me an email.

**Comment by hhrutter** [comment]
Fixed!
