### ISSUE TITLE
When I use types. Streamdict. Encode, something's wrong.

### ISSUE THREAD

**Issue by n454149301** [pdfcpu/pdfcpu#615]
### Thank you for submitting a possible bug!

``` go
package main

import (
	"os"

	"github.com/pdfcpu/pdfcpu/pkg/api"
	"github.com/pdfcpu/pdfcpu/pkg/pdfcpu/model"
	"github.com/pdfcpu/pdfcpu/pkg/pdfcpu/types"
)

func main() {
	var err error
	var f *os.File
	if f, err = os.Open("in.pdf"); err != nil {
		panic(err)
	}
	var RootCtx *model.Context
	if RootCtx, err = api.ReadContext(f, model.NewDefaultConfiguration()); err != nil {
		panic(err)
	}
	if err = api.OptimizeContext(RootCtx); err != nil {
		panic(err)
	}

	for _, o := range RootCtx.XRefTable.Table {
		switch node := o.Object.(type) {
		case types.StreamDict:
			if err = node.Decode(); err != nil {
				panic(err)
			}
			if err = node.Encode(); err != nil {
				panic(err)
			}
		}
	}
	if err = api.WriteContextFile(RootCtx, "./out.pdf"); err != nil {
		panic(err)
	}
}

```

1、go run a.go
2、cp out.pdf in.pdf
3、go run a.go   （I go a panic）
panic: unexpected EOF

goroutine 1 [running]:
main.main()
	a.go:29 +0x1bb
exit status 2

If I comment out node. The node.Encode() line, it works.

**Comment by hhrutter** [comment]
Hello!

Please explain your usecase.

**Comment by n454149301** [comment]
Sorry, English is not my mother tongue, my English is very poor, do not understand what USECASE said.

The code above is just a simple example of the problem that I have with any PDF that I have used above code. I think there should be a problem here, but I'm not quite sure what the problem is. Generated "out.pdf" files I can open correctly.
I see maybe two possibilities:

1. The "out.pdf" generated by the above code. There may be a problem with the PDF file format, so bring it back "out.pdf" . When the PDF goes into the input file, it goes to node.Encode(). Panic is triggered.
2. Generated out.pdf file is fine, and the code above will trigger panic in some unknown scenario. And any file in the above code processing to generate "out.pdf" . After the PDF file, it will just trigger the bug.

**Comment by n454149301** [comment]
I think I know what my problem is, I read your "optimize" code, I mistakenly thought this function is just parsing work, did not expect to do so many changes to the original content of the matter.
This is a problem caused by my code understanding, and I will turn it off.
