### ISSUE TITLE
add properties: wrong encoding

### ISSUE THREAD

**Issue by volodymyrprokopyuk** [pdfcpu/pdfcpu#617]
* `pdfcpu` v0.4.0
* Manjaro Linux

When I do `pdfcpu properties add scores/При-долине-куст-калины-oz1w.pdf 'Title = При долине куст калины'`
I get

```pdfcpu info scores/При-долине-куст-калины-oz1w.pdf
         PDF version: 1.7
         Page count: 1
         Page size: 596.00 x 842.00 points
............................................
         Title: @8 4>;8=5 :CAB :0;8=K
         Author:
         ...
```

Does `pdfcpu` supports UTF-8 to correctly display Cyrillic?

**Comment by hhrutter** [comment]
Generally yes, but this is bug during adding properties.
Thanks for reporting this.

**Comment by hhrutter** [comment]
This is fixed  with latest commit.

**Comment by GwynethLlewelyn** [comment]
Piping in late, but I just wanted to confirm that this issue disappeared with v0.8.1 on macOS Big Sur (installed via Homebrew and compiled with go 1.23). Nice work :)
