### ISSUE TITLE
Extract image alpha masks

### ISSUE THREAD

**Issue by phenomen** [pdfcpu/pdfcpu#619]
Many images in complex graphics-rich documents have alpha mask. I apply those masks in graphics software to "restore" original transparency. Currently, pdfcpu does not extract masks.

Example of image in PDF:
![image](https://user-images.githubusercontent.com/138311/236736623-bdabff11-d176-4c10-a5e1-8235ba7cf7ef.png)

That's how **mupdf** extract it (black background but there is an alpha mask as separate file):
![mupdf](https://user-images.githubusercontent.com/138311/236735168-99f51134-848a-42fd-9a92-2720ec666f62.png)

That's how **pdfcu** extract it (black background, no alpha mask):
![pdfcu](https://user-images.githubusercontent.com/138311/236735170-03e8b972-b63e-403c-b0d3-87f54877ba0c.png)

In a perfect world it would be great to also automatically merge alpha mask with image but that's probably out of scope of pdfcu.

**Comment by phenomen** [comment]
> For images with alpha channel you want to have the mask written out as a separat file?

Yes. that would be an expected behavior matching other PDF tools.

**Comment by hhrutter** [comment]
Hello!

There is a variety of options as far as image XObjects are concerned.
Eg. imageMask, mask, softmask..

Could you share a case in point sample?

**Comment by phenomen** [comment]
@hhrutter sure. Here is an example of typical PDF with layers and images with transparency: 
https://freeleaguepublishing.com/wp-content/uploads/2023/05/DB-Character-Sheet-v1.pdf

When I extract images, I'm expecting something like this (PNG, no background):
![image](https://github.com/pdfcpu/pdfcpu/assets/138311/e34c0fbb-197e-488e-b586-1110e960739d)

**Comment by hhrutter** [comment]
This is not what mupdf does as per your description above.
mupdf writes out the original stream and in addition as a separate file the smask/alpha channel and we can do this.

if we wanted to extract the (jpg) image stream to a png with empty alpha channel, image extraction will be slowed down significantly, since right now we write back DCT encoded streams directly as JPGs.
