### ISSUE TITLE
api: return structs

### ISSUE THREAD

**Issue by CNLHC** [pdfcpu/pdfcpu#621]
https://github.com/pdfcpu/pdfcpu/blob/0342a8327d29476d741255b959119f92c81d626c/pkg/pdfcpu/annotation.go#L209

currently, the `ListAnnotation` API returns a string array and each element in the array represents a line in the formatted output. 

The extra parsing work is very inconvenient for the downstream program to integrate with this API.

What do you think about splitting the output format logic and annotations list logic?  The API can return a Golang object and the `cmd` module can cover the formatting work.

**Comment by geertjanvdk** [comment]
Just facing the same problem. Having an "API", I thought ListImages would indeed return raw information, and the presenting layer (CLI) would then use that raw information to print out. Instead, ListImages returns formatted strings.

Use case: I am generating PDFs using different tools, and I need to test the result. The pdfcpu API part sounded interesting, but it is not really useful if you got to parse strings.

Without breaking things, maybe introduce an SDK, which has all or most functions, but returns indeed (list of) objects? Like in my case `[]model.Image`.

**Comment by fbueckle** [comment]
I would also love this. Currently I am using the library to fetch the form fields using `ListFormFields` and later turn them to read only using `LockFormFields`. Between those two steps I have to work with the returned string array and for each entry use RegEx to "extract" the IDs which could break at any point if the returned string format changes.

**Comment by hhrutter** [comment]
I am going to take up your suggestion, but I am doing this across the board for the  whole API.
This will be part of the next release - couple of weeks since we just had a release.

**Comment by hhrutter** [comment]
This is part of https://github.com/pdfcpu/pdfcpu/releases/tag/v0.5.0
