### ISSUE TITLE
Problem to count the number of pages on a PDF (FONT problem)

### ISSUE THREAD

**Issue by jerem17** [pdfcpu/pdfcpu#623]
Hello, 

I use your Go API in one of my projects, especially to count the number of pages on PDFs. But I have just encountered a problem with a particular PDF, which does not allow me to count its page count. 
By using your CLI, I was able to get the following feedback: 

` INFO: 2023/05/22 20:31:55 PDF Version 1.5 conforming reader
 INFO: 2023/05/22 20:31:55 validating
Fatal: dict=type1FontDict required entry=FirstChar missing
github.com/pdfcpu/pdfcpu/pkg/pdfcpu/types.Dict.Entry
	/Users/horstrutter/Documents/pdfcpu/pkg/pdfcpu/types/dict.go:136
github.com/pdfcpu/pdfcpu/pkg/pdfcpu/validate.validateIntegerEntry
	/Users/horstrutter/Documents/pdfcpu/pkg/pdfcpu/validate/object.go:456
github.com/pdfcpu/pdfcpu/pkg/pdfcpu/validate.validateType1FontDict
	/Users/horstrutter/Documents/pdfcpu/pkg/pdfcpu/validate/font.go:691
github.com/pdfcpu/pdfcpu/pkg/pdfcpu/validate.validateFontDict
	/Users/horstrutter/Documents/pdfcpu/pkg/pdfcpu/validate/font.go:979
github.com/pdfcpu/pdfcpu/pkg/pdfcpu/validate.validateFontResourceDict
	/Users/horstrutter/Documents/pdfcpu/pkg/pdfcpu/validate/font.go:1012
github.com/pdfcpu/pdfcpu/pkg/pdfcpu/validate.validateResourceDict
	/Users/horstrutter/Documents/pdfcpu/pkg/pdfcpu/validate/page.go:46
github.com/pdfcpu/pdfcpu/pkg/pdfcpu/validate.validateResources
	/Users/horstrutter/Documents/pdfcpu/pkg/pdfcpu/validate/page.go:919
github.com/pdfcpu/pdfcpu/pkg/pdfcpu/validate.validatePagesDictGeneralEntries
	/Users/horstrutter/Documents/pdfcpu/pkg/pdfcpu/validate/page.go:858
github.com/pdfcpu/pdfcpu/pkg/pdfcpu/validate.validatePagesDict
	/Users/horstrutter/Documents/pdfcpu/pkg/pdfcpu/validate/page.go:1004
github.com/pdfcpu/pdfcpu/pkg/pdfcpu/validate.validatePages
	/Users/horstrutter/Documents/pdfcpu/pkg/pdfcpu/validate/page.go:1053
github.com/pdfcpu/pdfcpu/pkg/pdfcpu/validate.validateRootObject
	/Users/horstrutter/Documents/pdfcpu/pkg/pdfcpu/validate/xReftable.go:954
github.com/pdfcpu/pdfcpu/pkg/pdfcpu/validate.XRefTable
	/Users/horstrutter/Documents/pdfcpu/pkg/pdfcpu/validate/xReftable.go:41
github.com/pdfcpu/pdfcpu/pkg/api.readAndValidate
	/Users/horstrutter/Documents/pdfcpu/pkg/api/api.go:123
github.com/pdfcpu/pdfcpu/pkg/api.Info
	/Users/horstrutter/Documents/pdfcpu/pkg/api/info.go:36
github.com/pdfcpu/pdfcpu/pkg/api.InfoFile
	/Users/horstrutter/Documents/pdfcpu/pkg/api/info.go:60
github.com/pdfcpu/pdfcpu/pkg/cli.Info
	/Users/horstrutter/Documents/pdfcpu/pkg/cli/cli.go:183
github.com/pdfcpu/pdfcpu/pkg/cli.Process
	/Users/horstrutter/Documents/pdfcpu/pkg/cli/process.go:35
main.process
	/Users/horstrutter/Documents/pdfcpu/cmd/pdfcpu/process.go:135
main.processInfoCommand
	/Users/horstrutter/Documents/pdfcpu/cmd/pdfcpu/process.go:1300
main.commandMap.process
	/Users/horstrutter/Documents/pdfcpu/cmd/pdfcpu/cmd.go:143
main.main
	/Users/horstrutter/Documents/pdfcpu/cmd/pdfcpu/main.go:55
runtime.main
	/usr/local/go/src/runtime/proc.go:250
runtime.goexit
	/usr/local/go/src/runtime/asm_arm64.s:1172`

I think the problem is due to the missing font in this PDF, so it is certainly not compliant. Is there a way to relax this validation when using the API directly in a GO project? 

Thank you for your help

ps : Screenshot of online PDF Analyzer and The PDF version used is 1.4 : 
<img width="968" alt="image" src="https://github.com/pdfcpu/pdfcpu/assets/36238691/7bf8f4f4-4b29-481b-94f6-3cfe75460fa6">

**Comment by hhrutter** [comment]
This is fixed with latest commit.
