### ISSUE TITLE
Optimization fails for specific pdf-file

### ISSUE THREAD

**Issue by comzine** [pdfcpu/pdfcpu#624]
I want to work with one pdf-file and it fails. For example with trim command:
```
pdfcpu trim -pages 1 input.pdf &> crash.log
```
I get the attached log-file. The input.pdf validates.

I created the pdf-file with LibreOffice Writer (including a textbox).

Having pdfcpu 0.41 dev under ArchLinux.

[crash.log](https://github.com/pdfcpu/pdfcpu/files/11542229/crash.log)
[input.odt](https://github.com/pdfcpu/pdfcpu/files/11542230/input.odt)
[input.pdf](https://github.com/pdfcpu/pdfcpu/files/11542233/input.pdf)

// I investigated the code and found out, that the crash happens in 
```
func optimizeFontAndImages(ctx *model.Context) error
```

**Comment by hhrutter** [comment]
This is fixed with the latest commit.
