### ISSUE TITLE
Border on Filled Fields after Filling

### ISSUE THREAD

**Issue by vedantmamgain** [pdfcpu/pdfcpu#627]
After filling pdfs using the API, I'm noticing a border around the 
filled fields. This is not the desired behaviour, I'm wondering if
this is  specific to pdfs or a pdfcpu config which can be changed.

**Comment by vedantmamgain** [comment]
@hhrutter nudge about this

**Comment by hhrutter** [comment]
This is in the pipeline.
Are you testing with Adobe Reader?
The pdfcpu form support is opinionated and centered around Adobe Reader.

**Comment by vedantmamgain** [comment]
@hhrutter Can you let me know how to resolve the issue, if it's something that is in the roadmap can you point me to which part of the code needs to be fixed since I can pick this up as well.

**Comment by hhrutter** [comment]
This is fixed with latest commit!
