### ISSUE TITLE
extending annotation support

### ISSUE THREAD

**Issue by abhilashsajeev** [pdfcpu/pdfcpu#628]
There are separate methods to add annotations in [annotation_test.go](https://github.com/pdfcpu/pdfcpu/blob/0342a8327d29476d741255b959119f92c81d626c/pkg/api/test/annotation_test.go#L4) `NewLinkAnnotation`, `NewTextAnnotation`.

How about adding other annotations? From the code it is seen that we can add other annotations like Line, Circle etc. It shows  in [documentation](https://pkg.go.dev/github.com/pdfcpu/pdfcpu@v0.4.1/pkg/api#AddAnnotationsFile)

Could you please provide an example of using AddAnnotationsFile and AnnotationRenderer to create a line at top of all pages in a file?

**Comment by abhilashsajeev** [comment]
@hhrutter Providing a minimal example to add Annotations other than Link or Text would be really helpful

**Comment by hhrutter** [comment]
Hi!
I do my best to improve the docs and sporadically add new annotation types as time allows.
What would be the annotation you are most interested in for starters?

Rest assured I am happy to integrate new annotation types as long as they come along with accompanying tests.

**Comment by hhrutter** [comment]
The latest commit has support for Square and Circle annotations.
More to come..

**Comment by Jiaget** [comment]
Is it possible to add a highlight annotation example?

> The latest commit has support for Square and Circle annotations. More to come..

**Comment by hhrutter** [comment]
In the pipeline..

**Comment by hhrutter** [comment]
Highlight annotation support is in as of the latest commit!

Annotation support is still not complete.
If you have need for a specific annotation type, please let me know.
Until then I am gonna close this issue and focus on others.
