### ISSUE TITLE
pdfcpu crashes if no fontID is specified in textbox

### ISSUE THREAD

**Issue by henrixapp** [pdfcpu/pdfcpu#630]
Hi,

I am using pdfcpu (latest version from GitHub cloned) on a Mac to fill a PDF with some textboxes (later via API in an application).

If I add content to one of the fields, pdfcpu crashes: 

```
writing out.pdf...
unexpected panic attack: runtime error: slice bounds out of range [1:0]

exit status 1
```

The slice in question is in [this line](https://github.com/pdfcpu/pdfcpu/blob/0342a8327d29476d741255b959119f92c81d626c/pkg/pdfcpu/primitives/textField.go#L241) and selecting a fontID. When I provide a default value like 
```
fontID = "Helv"
if len(da[i-2]) > 1 {
	fontID = da[i-2][1:]
}
```
the pdf is filled successfully.

It would be great if pdfcpu would either give a better error message (like PDF is corrupt with no fontID) or have a default behavior (with warning).

Thanks for this awesome project!

**Comment by hhrutter** [comment]
Hi!

Please provide more details about:
> If I add content to one of the fields, pdfcpu crashes

thx

**Comment by henrixapp** [comment]
ok sorry for not being clear. Steps to reproduce:
Export the form in [this pdf](https://www.stura.uni-heidelberg.de/wp-content/uploads/Finanzen/Formulare/Finanzabrechnungsformular.pdf)

`pdfcpu form  export Finanzabrechnungsformular.pdf `

Edit the out.json and enter some value in the `EURO` field:
```
...
 {
       "id": "EURO",
       "value": "10",
       "multiline": false,
        "locked": false
 },
...
```
Then try to fill it:
```
pdfcpu form fill Finanzabrechnungsformular.pdf out.json out.pdf
writing out.pdf...
unexpected panic attack: runtime error: slice bounds out of range [1:0]
```

I found the line of code by searching a little bit. I think a better error message or default behavior with some warning would be great.

**Comment by hhrutter** [comment]
This is fixed with latest commit!
