### ISSUE TITLE
merge: links no longer working

### ISSUE THREAD

**Issue by sylvain1010** [pdfcpu/pdfcpu#632]
Hi there,

After merging the 2 attached PDF documents (`cover.pdf` and `content.pdf`) with `pdfcpu`, the references / links (e.g. Table of Contents) are no longer working.

I run the following command with the latest version of `pdfcpu`:
```
$ pdfcpu merge book.pdf cover.pdf content.pdf
```

[cover.pdf](https://github.com/pdfcpu/pdfcpu/files/11633209/cover.pdf)
[content.pdf](https://github.com/pdfcpu/pdfcpu/files/11633207/content.pdf)

You can also fin attached the generated `book.pdf`: [book.pdf](https://github.com/pdfcpu/pdfcpu/files/11633234/book.pdf)

**Comment by hhrutter** [comment]
This is fixed with https://github.com/pdfcpu/pdfcpu/releases/tag/v0.4.2
