### ISSUE TITLE
Attachments with Chinese names

### ISSUE THREAD

**Issue by rcy1122** [pdfcpu/pdfcpu#635]
pdfcpu version: v0.4.1 dev
os: macOS Monterey 12.6.2

I added an attached video named `操作.mp4` inside the pdf with the following code:
```go
err := api.AddAttachmentsFile("./content.pdf", "",[]string{"./操作.mp4"}, false, nil)
if err != nil {
    t.Fatal(err)
}
```
add attachtment file is ok. But read the `content.pdf` file,  receive an error about: `pdfcpu: invalid UTF-16BE detected`:
```go
pdfCtx, err := api.ReadContextFile("./content.pdf")
if err != nil {
    t.Fatal(err)
}
t.Log(pdfCtx.Creator)
```
The same video, after modifying the name, can be read.

**Comment by hhrutter** [comment]
This is fixed with latest commit.

**Comment by chun222** [comment]
> This is fixed with latest commit.

But there will be Chinese garbled characters.
![image](https://github.com/pdfcpu/pdfcpu/assets/57406062/fbf3efba-f231-41af-8c26-42f8d643743d)

**Comment by chun222** [comment]
> pdfcpu version: v0.4.1 dev os: macOS Monterey 12.6.2
> 
> I added an attached video named `操作.mp4` inside the pdf with the following code:
> 
> ```go
> err := api.AddAttachmentsFile("./content.pdf", "",[]string{"./操作.mp4"}, false, nil)
> if err != nil {
>     t.Fatal(err)
> }
> ```
> 
> add attachtment file is ok. But read the `content.pdf` file, receive an error about: `pdfcpu: invalid UTF-16BE detected`:
> 
> ```go
> pdfCtx, err := api.ReadContextFile("./content.pdf")
> if err != nil {
>     t.Fatal(err)
> }
> t.Log(pdfCtx.Creator)
> ```
> 
> The same video, after modifying the name, can be read.

老铁 你中文乱码解决没啊 @rcy1122

**Comment by hhrutter** [comment]
Can I see a stacktrace?

**Comment by chun222** [comment]
pdfcpu version :0.5.0

**Comment by rcy1122** [comment]
>  @hhrutter 说已经解决了，然后关闭该问题，当时我验证的版本是0.4.1，然而并没有解决。

**Comment by rcy1122** [comment]
> 

0.4.1 没有解决

**Comment by hhrutter** [comment]
Fixed with latest commit!

感谢您使用pdfcpu 💚 
请考虑成为赞助商 🙏🏻
