### ISSUE TITLE
PDF 2.0 encryption

### ISSUE THREAD

**Issue by Cheeches** [pdfcpu/pdfcpu#639]
I'm trying to validate my pdf but i get pdfcpu: PDF 2.0 encryption not supported.

Online Metadata viewer info:

pdf_version
1.7

encryption
Standard V5.6 (256-bit)

creator
Designer 6.4

producer
Acrobat Distiller 22.0 (Windows)

form
AcroForm

encrypted
yes (print:yes copy:yes change:no addNotes:yes algorithm:AES-256)

optimized
yes

Some header info:

%PDF-1.7
%âãÏÓ
86 0 obj
<</Filter/FlateDecode/First 54/Length 448/N 8/Type/ObjStm>>stream

Is it possible to convert the pdf to extract forms?

**Comment by hhrutter** [comment]
This is definitely a file encrypted with a PDF 2.0 - revision 6 of the standard security header is a PDF 2.0 feature.
Not yet supported!

**Comment by hhrutter** [comment]
This should work now with https://github.com/pdfcpu/pdfcpu/releases/tag/v0.8.0
