### ISSUE TITLE
about compress pdf

### ISSUE THREAD

**Issue by 981349873** [pdfcpu/pdfcpu#643]
hello,is there any functions to compress pdf? not optimize,i want to set compress level to compress pdf

**Comment by hhrutter** [comment]
Hi!

It depends on your definition of compression.

There is no such thing like a compress level as far as the PDF spec is concerned.
You have to deal with object streams using one (or a chain) of the defined compression techniques aka filters within the PDF spec.

If you are concerned about the overall file size then `pdfcpu optimize`  is the way to go.
It gets rid of redundant resources and streamlines the set of objects referenced by the cross reference stream.

If you want to tweak the compression for individual object streams (e.g. for an image resource) then
you have to deal with this at the object level constrained by the parameters of the specific filter(s) used.
This comes down to editing specific object streams for given filter type which is not trivial and there fore
not supported by pdfcpu.

**Comment by henrixapp** [comment]
For the simple case of compressing images in pdfs, you can take a look at my project: https://github.com/henrixapp/pdfcomprezzor

Basically it finds images, converts them to png and reduces size to a certain threshold.
