### ISSUE TITLE
pdfcpu: textfield missing "DA"

### ISSUE THREAD

**Issue by vedantmamgain** [pdfcpu/pdfcpu#644]
While trying to fill pdfs I noticed that I've been getting `pdfcpu: textfield missing "DA"` error. I looked into some threads on the internet regarding Default Appearance and found that changing the font to auto in adobe acrobat resolved this issue, unfortunately this fix isn't apt for me as I want to specify the font with which the pdfs should be filled. Can you given me some context on why this is the case and how to resolve this issue other than setting the font to auto.

**Comment by hhrutter** [comment]
This should be fixed.
Please go install the latest commit.

**Comment by vedantmamgain** [comment]
Switched to the latest commit but now I've started to get a panic. Posting the stack trace below

```
github.com/pdfcpu/pdfcpu/pkg/pdfcpu/types.Array.FloatNumber
	external/com_github_pdfcpu_pdfcpu/pkg/pdfcpu/types/types.go:354
github.com/pdfcpu/pdfcpu/pkg/pdfcpu/types.RectForArray
	external/com_github_pdfcpu_pdfcpu/pkg/pdfcpu/types/types.go:178
github.com/pdfcpu/pdfcpu/pkg/pdfcpu/primitives.NewTextField
	external/com_github_pdfcpu_pdfcpu/pkg/pdfcpu/primitives/textField.go:907
github.com/pdfcpu/pdfcpu/pkg/pdfcpu/primitives.renderTextFieldAP
	external/com_github_pdfcpu_pdfcpu/pkg/pdfcpu/primitives/textField.go:951
github.com/pdfcpu/pdfcpu/pkg/pdfcpu/primitives.EnsureTextFieldAP
	external/com_github_pdfcpu_pdfcpu/pkg/pdfcpu/primitives/textField.go:990
github.com/pdfcpu/pdfcpu/pkg/pdfcpu/form.fillTextField
	external/com_github_pdfcpu_pdfcpu/pkg/pdfcpu/form/fill.go:923
github.com/pdfcpu/pdfcpu/pkg/pdfcpu/form.fillTx
	external/com_github_pdfcpu_pdfcpu/pkg/pdfcpu/form/fill.go:961
github.com/pdfcpu/pdfcpu/pkg/pdfcpu/form.fillWidgetAnnots
	external/com_github_pdfcpu_pdfcpu/pkg/pdfcpu/form/fill.go:1024
github.com/pdfcpu/pdfcpu/pkg/pdfcpu/form.FillForm
	external/com_github_pdfcpu_pdfcpu/pkg/pdfcpu/form/fill.go:1064
github.com/pdfcpu/pdfcpu/pkg/api.FillForm
	external/com_github_pdfcpu_pdfcpu/pkg/api/form.go:521
```

**Comment by vedantmamgain** [comment]
@hhrutter Nudge about the above

**Comment by hhrutter** [comment]
Please post or send me this file then I can provide a fix.
Thank you

**Comment by vedantmamgain** [comment]
@hhrutter I've shared the file

**Comment by hhrutter** [comment]
This is fixed with latest commit!

**Comment by vedantmamgain** [comment]
@hhrutter The sentinel errors are private.

**Comment by hhrutter** [comment]
You are right!
I am going to fix that!

**Comment by hhrutter** [comment]
Checkout the latest commit!
