### ISSUE TITLE
about add margin

### ISSUE THREAD

**Issue by wingjson** [pdfcpu/pdfcpu#646]
hi,sir,is there any functions can add margin into every page? because i want to add height for every page. i know resize, Does the `Resize` function stretch the page when increasing the height?

**Comment by hhrutter** [comment]
Hello!

The `resize` command affects your page size.
What do you mean by margin?
If this is about your page content you may play around setting your crop box for that page.

**Comment by hhrutter** [comment]
Closed due to inactivity.
