### ISSUE TITLE
pagecount  report   pdfcpu: validateStringEntry: dict=fdDict entry=FontFamily invalid type

### ISSUE THREAD

**Issue by wingjson** [pdfcpu/pdfcpu#648]
hello,when i used pagecount,and set conf.ValidationMode = model.ValidationNone , it still report pdfcpu: validateStringEntry: dict=fdDict entry=FontFamily invalid type,i modified the newDefaultConfiguration ValidationMode:                  ValidationNone,   it's useless.
![image](https://github.com/pdfcpu/pdfcpu/assets/20148421/aafb5674-3c68-4b81-ac45-ef9ad208cc5d)

**Comment by hhrutter** [comment]
Please describe your usecase.
Are you using the API or the CLI?

If you are using the API this might help:

```
// EnsurePageCount evaluates the page count for xRefTable if necessary.
// Important when validation is turned off.
func (xRefTable *XRefTable) EnsurePageCount() error {
```

**Comment by 981349873** [comment]
Hi，I used api to count the pages of pdf,the most pdf were successful,but fewer pdf reported this,maybe some pdf is not standard, so how to count the pages of those pdf

**Comment by hhrutter** [comment]
Closed due to inactivity.
