### ISSUE TITLE
No forms filled error

### ISSUE THREAD

**Issue by vedantmamgain** [pdfcpu/pdfcpu#649]
We are currently working with a PDF form that contains a field that is conditionally filled. The filling of this field depends on certain conditions:

If the specified conditions are met, we populate the field with predefined values.
If the conditions are not met, we leave the field empty and do not fill it at all.
We encountered an issue when using PDFCPU, as it returns a "No forms filled" error if no field is filled in the PDF. To work around this problem, we attempted to fill the field with whitespaces, but that also resulted in an error.

To address this issue, can we consider implementing a configuration option during initialization. This configuration would allow us to define validation levels, specifying whether we want to throw an error in the scenario where no field is filled.

Additionally, can what is the possibility of treating whitespaces as valid values. By considering whitespaces as valid, we would avoid the above error, this is if the above takes a lot of time to implement.

Let me know if there's anything else I can help you with!

**Comment by vedantmamgain** [comment]
@hhrutter Nudge about the abvoe.

**Comment by hhrutter** [comment]
As per the latest release v0.4.2 filling is returning sentinel errors that you can catch!

**Comment by vedantmamgain** [comment]
@hhrutter Thanks a lot.
