### ISSUE TITLE
Infinite loop on pdf with circular bookmark

### ISSUE THREAD

**Issue by semvis123** [pdfcpu/pdfcpu#650]
PDFCPU gets stuck in an infinite loop on a pdf with circular bookmark.
Expected behavior: it detects the loop and throws an error.
Platform: MacOS 14.0
PDF: https://github.com/chromium/pdfium/blob/main/testing/resources/bookmarks_circular.pdf

**Comment by hhrutter** [comment]
Your file is damaged.
It does not open neither in Mac Preview nor in Adobe Reader.

**Comment by semvis123** [comment]
Yes, but pdfcpu should still produce an error instead of endlessly processing it. Current behavior is vulnerable to an DOS attack.

**Comment by hhrutter** [comment]
Have you tried using the latest commit fd12f8b?

I agree that a process hang is bad but what does that have to do with a DOS attack?

**Comment by semvis123** [comment]
I tried https://github.com/pdfcpu/pdfcpu/commit/fd12f8b0f2e3bff59f736070c34d88d84bdb63d7 , same result. When using this library on untrusted user input in a shared application, this bug can cause a problem for other users that are trying to use the service.

**Comment by semvis123** [comment]
https://github.com/chromium/pdfium/blob/main/testing/resources/bookmarks_circular.pdf
or raw:  https://github.com/chromium/pdfium/blob/main/testing/resources/bookmarks_circular.pdf?raw=true

**Comment by hhrutter** [comment]
This is fixed with https://github.com/pdfcpu/pdfcpu/releases/tag/v0.4.2
