### ISSUE TITLE
Improve handling of pull requests

### ISSUE THREAD

**Issue by Atomk** [pdfcpu/pdfcpu#656]
Looking at the PRs it seems that only a few of those are merged, most PRs are closed and contributions are committed independently by the maintainer. A few examples for context: [here](https://github.com/pdfcpu/pdfcpu/pull/430), [here](https://github.com/pdfcpu/pdfcpu/pull/631), [here](https://github.com/pdfcpu/pdfcpu/pull/483).

This has some disadvantages:
- The maintainer is listed as the sole commit author, which means:
    - The contribution (and contributor) is not properly credited, which makes it hard to find the actual author of a contibution by looking at git history
    - It's harder to see which users actually submitted contributions (for example, you can see the "Contributor" badge on the top-right of my comments, people who commit to master also appear in the [Contributors](https://github.com/pdfcpu/pdfcpu/graphs/contributors) list of the repo) _*see edit at the bottom_
- At a first glance, a list full of red unmerged PRs feels discouraging since, without digging in the comments, it looks like contributions are not likely to be merged
- It's not immediately clear which contributions were actually merged and which are rejected, you have to read all the comments in each PR to find out..

Ways to improve:
- You can add commits to other people's PRs, instead of reproducing the work in a separate commit and rejecting the PR. This is the reason why when you submit a PR there is a "Allow edits by maintainers" button.
- You can coauthor commits. [Example](https://github.com/ziglang/zig/pull/8417#issuecomment-813057875)
    - If you're willing to (or if uncredited contributors ask to) I think you can also edit old commits to add this line

I see that you take care in thanking people for their contributions, that's certainly appreciated, still I believe the current state of things could be improved to better encourage (and credit) contributors.

EDIT: I just saw you included most contributors in the README file, but this partially addresses only one of the issues I described.

**Comment by Atomk** [comment]
Thank you for sharing your perspective, now I better understand the context.

Last time I checked out the project the latest release was in 2021 so I thought thing were more or less complete. I did not know updates got more frequent, I understand that sometimes proposed changes do not go in the same direction you're headed and I think it's totally fine to close PRs that are not aligned with the goals you have in mind, or the current state of the project. I also understand that people not following the templates you provide can be frustrating since it may force you to use more of your already limited free time to clarify things. In this issue I specifically refer to the PRs that are closed while still merging the contributed changes.

Of course I am thankful that you decided to open source your work and that you are still maintaining and improving on it, I've used it just once to extract some assets from a PDF but I found it to be very well made, so sometimes I check the repo out of curiosity to see if there's still activity - and I am glad there still is!

The reason why I opened this issue is that I wish there were more contributors to help you out (and/or donations) and I guess looking at all the red PRs felt a bit discouraging, and comparing that to other projects I follow I felt this could be a a way to improve on this aspect. Again, it's not really about PRs closed for undeniably good reasons, it's more about contributions that could be merged in a "friendlier" way.

I must admit though that in the end it's your project and your free time, and maybe the additional time invested in better managing of accepted contributions does not encourage better collaboration in the way I think it does,. To be fair, in the three PRs I mentioned I didn't see anybody directly complain, just some confusion about it, but I still think details count. and whatever you choose to do about this I hope I could offer a valuable perspective. Thanks again for sharing your thoughts and your work.

**Comment by hhrutter** [comment]
👍🏻 Point taken.
The bottom line is there is only so much time I have for pushing this project forward so sometimes I am forced to make shortcuts in order to make progress which may not please everybody. Definitely agree I could use some more sponsors given the time I am investing into pdfcpu development.
