### ISSUE TITLE
API: ListFormFields() throws errors for PDF files

### ISSUE THREAD

**Issue by fbueckle** [pdfcpu/pdfcpu#657]
- Version Used: 0.4.2
- Package: API
- Go Version of Project: 1.20.5
- OS: Ubuntu 23.04

## Problem Description

I am trying to fetch the form fields of different PDF files and turn them read-only but during my testing `ListFormFields()` threw errors quite a few times. I'm using the default config with `Reader15` set to `true`. In order to check whether the problems are with the PDF files or the library I also tried to apply the same action using `Apache PDFBox` where I was able to list and make the form fields read-only without any problems.

### File 1
- File (obtained via Google Search): https://royalegroupnyc.com/wp-content/uploads/seating_areas/sample_pdf.pdf
- Error: `pdfcpu: validateNameEntry: dict=Named entry=N invalid dict entry: SaveAs`

### File 2
- File: [30010061_Einlegerbogen.pdf](https://github.com/pdfcpu/pdfcpu/files/12143966/30010061_Einlegerbogen.pdf)
- Error: `pdfcpu: validateNumberArrayEntry: invalid type at index 3`

---

If you need any additional information I'll gladly provide it. If those PDF files should currently not be supported please let me know and we can close this issue.

**Comment by hhrutter** [comment]
Make sure your input files pass validation before any further processing with pdfcpu : `pdfcpu validate yourfile.pdf`
I am going to analyse your files rest assured.

**Comment by hhrutter** [comment]
This is fixed with latest commit.

**Comment by fbueckle** [comment]
Thank you very much, appreciate it!

**Comment by hhrutter** [comment]
👍🏻 Please consider sponsorship if you are happy with pdfcpu 💚
