### ISSUE TITLE
Validation Error - PDF Portfolio/Attachment Extraction

### ISSUE THREAD

**Issue by inkwell84** [pdfcpu/pdfcpu#659]
### Discussed in https://github.com/pdfcpu/pdfcpu/discussions/658

<div type='discussions-op-text'>

<sup>Originally posted by **inkwell84** July 24, 2023</sup>
Hello, 

I am not sure this is a Bug so I did not want to submit it as an "Issue." Perhaps with your guidance we may determine that it is?

I am trying to extract PDF files that attached to a PDF Portfolio file.

I run `pdfcpu validate filename.pdf ` and I get this error:

```
validating(mode=relaxed) Portfolio of order #8_6-16-23.pdf ...
validation error (obj#:127): pdfcpu: validateNameEntry: dict=colFlddict entry=Subtype invalid dict entry: AFRelationship
```

I run `pdfcpu portfolio list filename.pdf` and I get this error:

```
pdfcpu: validateNameEntry: dict=colFlddict entry=Subtype invalid dict entry: AFRelationship
```

I run `pdfcpu attachment list filename.pdf` and I get this error:

```
pdfcpu: validateNameEntry: dict=colFlddict entry=Subtype invalid dict entry: AFRelationship
```

Can anyone help me understand what's going on (what can I do to fix?)</div>

**Comment by hhrutter** [comment]
Sorry, I did not receive your file.
hhrutter@gmail.com

**Comment by inkwell84** [comment]
I sent via gmail to you earlier and again just now, thank you!!

**Comment by hhrutter** [comment]
👍

**Comment by hhrutter** [comment]
This file is interesting to say the least:

We have a collection:
```
72: was compressed 147[3] generation=0 types.Dict
<<
	<D, (��51.0 Order note.pdf)>
	<Folders, (73 0 R)>
	<Reorder, (74 0 R)>
	<Schema, (75 0 R)>
	<Sort, <<
		<S, [adobe:Order FileName]>
	>>>
	<View, T>
>>
```

We have a collection schema dictionary:

```
75: was compressed 147[6] generation=0 types.Dict
<<
	<AFRelationship, (76 0 R)>
	<CompressedSize, (77 0 R)>
	<CreationDate, (78 0 R)>
	<Description, (79 0 R)>
	<FileName, (80 0 R)>
	<ModDate, (81 0 R)>
	<Size, (82 0 R)>
	<adobe:Order, (83 0 R)>
>>
```

Keys to collection field dictionaries are at the discretion of the PDFWriter.
.. but then we have the collection field dicts:

```
76: was compressed 147[7] generation=0 types.Dict subType=AFRelationship
<<
	<N, (Relationship)>
	<O, 6>
	<Subtype, AFRelationship>
>>

   77: was compressed 147[8] generation=0 types.Dict subType=CompressedSize
<<
	<N, (Compressed size)>
	<O, 7>
	<Subtype, CompressedSize>
	<V, false>
>>

36: was compressed 148[0] generation=0 types.Dict
<<
	<CreationDate, (D:20230617114510-04'00')>
	<Creator, (Adobe Acrobat Pro \(64-bit\) 22.3.20282)>
	<ModDate, (D:20230617170709-04'00')>
	<Producer, (Adobe Acrobat Pro \(64-bit\) 22.3.20282)>
>>
```

The **Subtype** of collection field dicts is defined by the PDF spec.

* **CompressedSize** was introduced with PDF 2.0, only this file claims version 1.7
* **AFRelationship** is not mentioned at all in the spec.

I am running out of ideas how this file can be validated since its Producer is Acrobat Pro.
@petervwyatt any suggestions?

**Comment by inkwell84** [comment]
So it was created with Acrobat Pro and it fails to meet spec? LOL

**Comment by petervwyatt** [comment]
@hhrutter without seeing the PDF, It sounds like it is a PDF 1.7 (ISO 32000-1:2008) file with Adobe Extension Level 3 additions - see https://pdfa.org/resource/pdf-specification-index/ for relevant documentation. Note that the Adobe Extensions are often slightly different to what PDF 2.0 standardized to make things less vendor specific and more generalized for the same feature.

**Comment by hhrutter** [comment]
This is fixed with latest commit.
