### ISSUE TITLE
Validation Error: DereferenceStreamDict: wrong type <Identity-H> types.Name

### ISSUE THREAD

**Issue by meerkat-mary** [pdfcpu/pdfcpu#660]
Hi @hhrutter,

Hope you are well, we're facing an issue where pdf validation is unsuccessful due to a `validation error (obj#:37): pdfcpu: DereferenceStreamDict: wrong type <Identity-H> types.Name` error for two of our PDFs

We're able to open and view these files successfully in Mac Preview and Acrobat Reader on Windows 7/10 and Mac OS Ventura using the latest commit (0.4.2).

[file1_output.log](https://github.com/pdfcpu/pdfcpu/files/12150335/file1_output.log)
[file2_output.log](https://github.com/pdfcpu/pdfcpu/files/12150341/file2_output.log)

Please let me know if you'd like to see the original pdf file (as it contains sensitive PII information, I can email it)

Thank you!
Mary

**Comment by hhrutter** [comment]
Hi there!

For one it does not look like you are running the latest release..

Secondly this file is in violation of the PDF spec.
The **ToUnicode** font dict entry is expected to be a stream and not a name.
Send me the file attached to email, from the log I can see other potential spec violations.
If this is the only one needed for positive validation I am happy to relax validation.

**Comment by meerkat-mary** [comment]
Thanks @hhrutter - I've sent you an email containing the two files for further inspection

**Comment by hhrutter** [comment]
This is fixed as of the latest commit!

**Comment by meerkat-mary** [comment]
Thanks @hhrutter - the file validation works in the latest commit, much appreciated ⭐

**Comment by hhrutter** [comment]
👍🏻 You are welcome!
