### ISSUE TITLE
Merge append bookmark list

### ISSUE THREAD

**Issue by oll37** [pdfcpu/pdfcpu#663]
If I append several files one after the other with 
```
pdfcpu merge -mode append a.pdf b.pdf
pdfcpu merge -mode append a.pdf c.pdf
pdfcpu merge -mode append a.pdf d.pdf
```
the bookmark list becomes more and more nested:
```
-a
--a
---a
---b
--c
-d
```

What I expected:
```
-a
-b
-c
-d
```
Can this be fixed by not creating a new bookmark for the original document every time?
Thanks for your help.

**Comment by hhrutter** [comment]
The release notes explain how to turn off bookmark creation during merging.
https://github.com/pdfcpu/pdfcpu/releases/tag/v0.4.2

**Comment by oll37** [comment]
I didn't want to disable the bookmarks completely. Rather, I was hoping that it would be possible to keep the bookmarks of the appended file at the same level as the previous ones.

**Comment by hhrutter** [comment]
Understood!
Needs to be fixed.

**Comment by hhrutter** [comment]
This is fixed as of latest commit!
