### ISSUE TITLE
pageNodeDict: cannot dereference, pageNodeDict - v0.4.2 onwards

### ISSUE THREAD

**Issue by meerkat-mary** [pdfcpu/pdfcpu#664]
Hi @hhrutter 

Hope you're well, I've run into a peculiar scenario that results in a `pageNodeDict: cannot dereference, pageNodeDict`:
- I have 2 PDF files (FILE_A and FILE_B) that I want to merge together in the following format: FILE_A, FILE_B, FILE_A 
- FILE_B is sandwiched between the duplicate FILE_A's to form an output pdf with the merged docs
- I then apply some bookmarks to the final merged output, with bookmark entries referencing each file (no intra-file bookmarks)
- Note, this error only occurs when I put the files in the order listed above, if I do any other variation e.g. FILE_A, FILE_A, FILE_B, then there's no issue

When I attempt to do this, I run into a `pageNodeDict: cannot dereference, pageNodeDict` error, and this only happens in v0.4.2 onwards, I've tested this on 0.4.1 and the error doesn't occur. I'll send you the two files over email to help with debugging - thank you!

Mary

**Comment by hhrutter** [comment]
Please use the latest commit!
` api.MergeRaw` does not support automatic bookmark creation, since this feature depends on filenames.
It will now disable bookmark creation by itself.

The merging part should work now for your files.
Please keep me updated.

**Comment by meerkat-mary** [comment]
Thank you very much @hhrutter for the quick turnaround on this ⭐ 

I'll test using the latest commit and will update you :)

**Comment by meerkat-mary** [comment]
I've tested and can confirm that the merging is no longer an issue, however I get the same error but I think I've narrowed it down to the following scenario:
- The `api.AddBookmarks` function takes in a slice of `Bookmarks`
- If the slice contains two or more Bookmarks with the same `Title`, I get the above error

I've tried assigning a random number suffix to the title as a test and the AddBookmarks function was successful

**Comment by meerkat-mary** [comment]
Works perfectly now, thank you! ⭐ 

Mary
