### ISSUE TITLE
Set custom permissions

### ISSUE THREAD

**Issue by rtywei** [pdfcpu/pdfcpu#665]
I want to set a pdf custom permission, this permission can only be modified, not all,

Now,
<img width="921" alt="image" src="https://github.com/pdfcpu/pdfcpu/assets/28942808/cf82519e-7283-4ff7-b445-be66fab97b86">

What is the solution?

Thanks

**Comment by hhrutter** [comment]
Setting permissions conveniently is in the pipeline.
Meanwhile please checkout #473 for some hints.

**Comment by hhrutter** [comment]
This is part of https://github.com/pdfcpu/pdfcpu/releases/tag/v0.6.0
