### ISSUE TITLE
Unable to detect font id 

### ISSUE THREAD

**Issue by bruno-farias** [pdfcpu/pdfcpu#671]
Hi, 

I'm getting the following error while trying to fill out a form, all fields except one work:
```pdfcpu: unable to detect font id```

pdfcpu version: pdfcpu: v0.4.2 dev
OS: Mac os 13.4.1

you can find the file [here](https://drive.google.com/file/d/1S7UIehA73ZRdk00VaEtw6tRBdOXX2n1n/view?usp=sharing)

The field that triggers the issue is Text4

**Comment by hhrutter** [comment]
This textfield contains an invalid default appearance string: `<DA, (/ 18 Tf)>`.

**Comment by hhrutter** [comment]
This should be fixed with https://github.com/pdfcpu/pdfcpu/releases/tag/v0.5.0

**Comment by bruno-farias** [comment]
Thanks a lot @hhrutter!
