### ISSUE TITLE
API: "Field" struct in "form" package does not export fields preventing the access to them

### ISSUE THREAD

**Issue by fbueckle** [pdfcpu/pdfcpu#675]
Not sure whether this counts as bug or feature request but I believe it is the former due to the way two `api` functions interact with each other.

### General Information

Please ensure the following:

* Used version: `1d309dcd12aa2208402cc103625f56160f743453 aka v0.5.0`
* Used OS: `Ubuntu 23.04`
* Used GoLang Version: `1.21.0.`

### Bug/Problem Summary

The `Field` struct used in `Forms` is not exporting its fields which prevents other projects to access those fields. This leads to problems when trying to "lock" form fields. Scenario goes as follows:

1. Obtain all form fields using the new function `FormFields` from the `api` packages
2. Try to extract the IDs of the struct in order to use them as input for `LockFormFields` which takes a string array as input
3. No field from the `Field` struct can be accessed due to the fields not being exported

If there is any error on my behalf, please let me know.

**Comment by hhrutter** [comment]
Please update pdfcpu's dependencies then pull and go install.
