### ISSUE TITLE
Cannot list annotations (version error)

### ISSUE THREAD

**Issue by little-flag** [pdfcpu/pdfcpu#680]
Getting this error:
```
> pdfcpu annot list test.pdf
dict=annotDict entry=NM: unsupported in version 1.3
This file could be PDF/A compliant but pdfcpu only supports versions <= PDF V1.7
```
The PDF in question is v1.3, produced by macOS (13.5.1) Quartz PDFContext. It's very simple, just some placeholder text and an underline annotation.

Is this a known/intended limitation? (Using pdfcpu CLI v0.5.0, though I had the same problem with previous version too.)

My use case is that I'd like to use pdfcpu to replace a bunch of non-Go code that I need to extract annotations (particularly [pdfannots](https://github.com/0xabu/pdfannots), which relies on pdfminer.six/Python). Just testing to see how plausible this is.

**Comment by hhrutter** [comment]
This file is in violation of the PDF specification.
The optional **NM** entry in annotation dicts is defined for PDF Versions 1.4 and beyond only.

**Comment by little-flag** [comment]
Thanks. I guess this is a problem with macOS.

**Comment by hhrutter** [comment]
True and good idea to report this 👍🏻 
Nevertheless, the latest commit relaxes validation of that attribute!
