### ISSUE TITLE
What does pdfcpu validate?

### ISSUE THREAD

**Issue by PhilterPaper** [pdfcpu/pdfcpu#684]
In a similar vein to #612, does your pdfcpu documentation include a list anywhere of what sort of things your validation is looking for and reporting on? I am looking for a PDF validator so I can figure out what PDF::Builder (a Perl library) is doing wrong for several PDFs it produces. These include
1. "An error exists on this page. Acrobat may not display the page correctly. Please contact..." This is a PDF that works fine if streams are uncompressed, but when compressed, it gets this message, but only with Adobe Acrobat Reader. BTW, it seems to load just fine, and doesn't ask permission to save the file upon exit (which it does if it "fixed up" something).
2. I have some PDFs embedded from G4 TIFF image files, that blow up upon loading, and I've never figured out what happened.
3. There are one or two other cases of allegedly bad PDFs that I don't recall the details on off the top of my head (possibly more TIFF image examples).

There are plenty of "repair" utilities and services, but even if the returned PDF works, they have completely rewritten it, so I can't tell what original code they found wanting, and fixed. I'm just looking for something to tell me where a Reader would find something amiss, so I can fix the PDF generator.

Note that both PDF::API2 and PDF::Builder have reasonably complete support up to PDF 1.4, with limited PDF 1.5 items supported. (Normally, a PDF is being created from scratch, rather than being read in and updated.) I'm hoping that the validation code can flag features to a certain level, so, for instance if it uses Object Streams in a supposedly 1.4 level file, it should fail it, while in 1.5 and up maybe just issue an informational note (if that). In other words, not just assume that anything valid in 1.7 is OK, but look at the claimed PDF level and possibly at a lower arbitrary level. Don't forget that the PDF level can be set/overridden in several places!

If pdfcpu isn't too hard to install and use (I will need to install Go first, and then your package, on Windows 10), and is useful for the cases I've seen, I will be happy to recommend it to PDF::Builder users as a debugging tool. More on my debugger wishlist at PhilterPaper/Perl-PDF-Builder/issues/199. Thanks!

**Comment by hhrutter** [comment]
#612 is in the pipeline.

You don't need to install Go for the CLI tool, just grab the binary for your OS:
https://github.com/pdfcpu/pdfcpu/releases/tag/v0.5.0

Then  feed your problematic files into: 

`pdfcpu val -v in.pdf` 
or
 `pdfcpu val -vv in.pdf`

🙏🏻  Hopefully this will give you some insight.

**Comment by PhilterPaper** [comment]
Thanks for the quick reply. I tried it on the first case (flate compression, "may not display"), and it found nothing. Can I assume that it deflates (decompresses) each stream, and found nothing? This suggests that there's a problem with Adobe Acrobat Reader, as a number of other PDF Readers don't report any problems. Do you know how to report a probable Adobe product bug? The Adobe Community has been of no help.

Later I will try pdfcpu on the other problem PDFs. I figured this one should be the simplest.

**Comment by PhilterPaper** [comment]
@petervwyatt responded to my Builder/199 and said that Ctrl+OK might work (it gave no additional information). He also discusses various aspects of PDF Reader standards, and there is no reference implementation. I figured that the free download of Adobe Acrobat Reader would be the closest thing to a Gold Standard, as it's so widely used. It's the one I primarily use -- I'm reluctant to drop big bucks on a product (the full Acrobat) which I have little use for, in support of a product I give away for free (PDF::Builder).

Besides the "may have a problem displaying" PDF (which pdfcpu gives a clean bill of health), I've been playing with two G4 CCITT TIFF files that were giving problems. One shows an even more serious problem now (quits while writing object 1), which I need to investigate. 

The other, page_3_G4_GT, still shows "Insufficient data for an image" dialog, and nothing comes up with Ctrl+OK ("Learn More" button simply shows a web page with suggestions for Acrobat users). The image is intended to be a bright green background, the TIFF image, and a yellow title at the bottom. 
* Acrobat Reader shows only the green background (no image or title)
* Firefox PDF display, GIMP, and XpdfReader show a solid black image, and title, 
* Chrome and Edge PDF display show black with a lot of garbage, and title. 

pdfcpu shows the Image object as "decoded stream content (length = 0)" which seems a little odd, and "Fatal: dict=type1FontDict required entry=FontDescriptor missing", which is odd because this code has never given trouble before. I'll have to investigate it further to see if it's been missing all along, and PDF::Builder output doesn't meet mode=strict requirements (always a possibility).

Here are the "may have a problem" PDF (01compressed) and the "insufficient data" PDF (page_3_g4_GT) to throw against your validator, if you'd like to try it. Same invitation to Peter, if he has any good tools (appreciate it!).
[01compressed.pdf](https://github.com/pdfcpu/pdfcpu/files/12447104/01compressed.pdf)
[page_3_g4_GT.pdf](https://github.com/pdfcpu/pdfcpu/files/12447105/page_3_g4_GT.pdf)

**Comment by hhrutter** [comment]
01compressed.pdf  renders fine in MacPreview and Chrome, A.Reader throws a warning like you said.

I noticed an empty content stream as part of the **Contents** array although I don't know if this is smth that may throw off A.Reader:

```
10:   offset=  208215 generation=0 types.StreamDict
<<
	<Filter, [FlateDecode]>
	<Length, 8>
>>
decoded stream content (length = 0)
```

.. why do we need to define 50 fonts in order to display a checker board?

**Comment by PhilterPaper** [comment]
This was a t-test (post-installation test) from someone else's product (PDF::TableX), which I didn't write. Yes, one font would have done the job instead of 64. I think it draws each square completely independently of every other one, passing in only the $pdf and $page objects, which means all new font objects, etc. for each page instead of reusing a common one. 

As for the empty stream, I'm guessing that they defined a graphics object somewhere and never put any content into it (I haven't bothered to look very deeply into it). That would be a place of suspicion if compressing the empty stream wasn't quite right -- did pdfcpu uncompress the empty stream OK? It works OK in A.Reader when uncompressed. I wonder if A.reader has a glitch when encountering a properly compressed, but empty, stream? You shouldn't waste space with such an object, but maybe they never tested with it?

**Comment by PhilterPaper** [comment]
I tried changing the empty text object and empty graphics object to their uncompressed counterparts (`  BT   ET  ` _and_ empty), changing the lengths, blanking out (_not_ erasing) `/Filter [ /FlateDecode ]`, and increasing the spaces in the objects by the difference in lengths, but no joy. 

I have a "TO DO" list item to _not_ compress a stream in PDF::Builder unless it saves at least 26 bytes of compressed data (to account for the `/Filter [ /FlateDecode ] ` that gets added).

**Comment by hhrutter** [comment]
I am not sure if I can be of any further help here.

**Comment by PhilterPaper** [comment]
OK, thank you for your time in looking at it.  I will try to remember to update/close this ticket when I get around to implementing "do not compress a stream _unless_ you save at least 26 bytes over the uncompressed version". At least I will be able to tell you that was, or was not, the cause of the problem (i.e., a problem in A.reader).

**Comment by PhilterPaper** [comment]
The 01compressed.pdf problem has been resolved... it turns out that save (_q_) and restore (_Q_) in a _text_ stream _sometimes_ results in this error in Adobe Acrobat Reader, so at least, that case is out of the way. Thanks to Vadim Repin for finding it. I still plan to some day tweak the use of compression, and still have the other PDF issues open.

**Comment by PhilterPaper** [comment]
I'll go ahead and close this one. Feel free to reopen it if it's useful for you to keep track of such things. The immediate problem with 01compressed.pdf has been fixed (remove save/restore in a _text_ stream), but I still have some other puzzlers, especially with image data. It's possible that some Readers simply don't support some image compression modes and image models, which pdfcpu probably can't address. I have informed the owner of the code (PDF::TableX) about the problem with save/restore, and hopefully they'll remove the calls. Thanks much!
