### ISSUE TITLE
Specify table columns padding

### ISSUE THREAD

**Issue by roromix** [pdfcpu/pdfcpu#692]
As part of a project, I need to have different padding depending on the column of the table.

I will make a pull request to add this functionality.

**Comment by hhrutter** [comment]
Beware - the **Create** feature is JSON driven & tested first.
Please wait with a PR and let's first discuss.

Direct API Calls into creation are not tested.
Whatever we need to extend has to be reflected in tests and also properly in createFromJSON_test.go.

First of all, what kind of model change are you suggesting for additional padding?

**Comment by roromix** [comment]
My suggestion is to add this in the Table struct : 
`ColPaddings     []*Padding //optional columns specific padding`

No problem, i will try to do the tests

**Comment by hhrutter** [comment]
I am thinking about a convenient way to express this in JSON.
Right now we have **ints** for *rows* and *columns* and I would like keep the JSON simple and readable.

Do you think you can describe your use case for this requirement?
Can you give an example?

**Comment by roromix** [comment]
> I am thinking about a convenient way to express this in JSON. Right now we have **ints** for _rows_ and _columns_ and I would like keep the JSON simple and readable.
> 
> Do you think you can describe your use case for this requirement? Can you give an example?

The use case is to have a more large padding for a specific column value or header. If null, we use the table padding.
Example in my PR #694
