### ISSUE TITLE
unable to merge multiple pdf document

### ISSUE THREAD

**Issue by mateors** [pdfcpu/pdfcpu#701]
I ran the following command
`> pdfcpu merge out.pdf Lead-Based_Paint_and_Lead-Based_Paint_Hazards_Disclosure_1_-_1221_ts62956.pdf Pet_Addendum_-_1113_ts59831.pdf  Res_LeaseMonth-to-Month_Rental_Agmt_-_1221_ts58268.pdf Addendum_No_1_-_1221_ts67645.pdf `KeysafeLockbox_Addendum_and_Tenant_Permission_to_Access_Property_-_413_ts61394.pdf

**But it shows me following error:**

**EmbeddedFilesNameTreeValue: unsupported in version 1.3
This file could be PDF/A compliant but pdfcpu only supports versions <= PDF V1.7**

**Comment by hhrutter** [comment]
In order to process PDF files with pdfcpu you have to ensure they are valid:
`pdfcpu validate test.pdf`

At least one of your files does not pass validation, please identify and then let's see what we can do about it.

**Comment by mateors** [comment]
> pdfcpu validate test.pdf

thank you very much for your quick response. But I am wondering how I merged the same files using one of the online generator. I think pdf version might be an issue.

**Comment by hhrutter** [comment]
Hello!

The reality is, many PDF Writers out there violate the PDF specification .

A lot of PDF Readers deal with situations like this by accepting spec. violations - it's just easier than a bug report directed to the PDF Writers.

pdfcpu validation has two modes: strict and relaxed - relaxed mode being the default.
Relaxed mode makes sure minor PDF spec violations are digested by the parser.

pdfcpu is still considered Alpha.
You can contribute to improve the pdfcpu parser by identifying a spec violation by running 
`pdfcpu validate yourfile.pdf` and then ideally - if you can share it - attach the file to an issue.

In many cases we can relax validation, sometimes not.
It depends on the severity of the violation.

Thanks for using pdfcpu 💚

**Comment by hhrutter** [comment]
This is fixed with the latest commit.
