### ISSUE TITLE
Crash reporting: "validateNameEntry: dict=CIDFontDict entry=Subtype invalid dict entry: Type1"

### ISSUE THREAD

**Issue by seongwon-privatenote** [pdfcpu/pdfcpu#702]
Hello, we are using pdfcpu to set a password on PDF files. Yesterday, we encountered a strange crash while processing a file, so I decided to report it.

The error message we received was as follows:
```
pdfcpu: validateNameEntry: dict=CIDFontDict entry=Subtype invalid dict entry: Type1
```

Upon reviewing the PDF specification document, it became clear that this was an actual spec violation. The PDF file itself was irregular. However, it's worth noting that Chrome Preview, Adobe Reader, and MacOS Preview are all able to open the file without issue.

For further details, you can refer to the crash log generated using the command `pdfcpu validate -vv sample.pdf &> crash.log`.
[crash.log](https://github.com/pdfcpu/pdfcpu/files/12508804/crash.log)

Here is the problematic PDF file for your reference:
[sample.pdf](https://github.com/pdfcpu/pdfcpu/files/12508807/sample.pdf)

We are currently using the latest release of pdfcpu, v0.5.0.

Thanks!

**Comment by hhrutter** [comment]
Thanks I take a look!

**Comment by hhrutter** [comment]
Hello!

The SubType entry of a CIDFontDict declares a Type 0 or Type 2 CID-Font.
If the glyph descriptions are based on CFF subType has to be *CIDFontType0*.
Respectively if the glyph descriptions are based on TrueType SubType has to be *CIDFontType2*.
A subType  **Type1** is undefined and neither is it clear how to repair smth like this.

if the parser simply ignores the invalid subType in your case validation passes
but it is indeterministic how pdfcpu will behave in subsequent processing steps for this file.
Therefore I am reluctant - Please go ahead and patch the parser in your fork.

I strongly recommend filing a bug report with the author/producer of this file.
Spec. violations like this one simply should not be ignored by any parser.
Should be an easy fix on the PDF Writer side as long as they know what they are doing.

Thank you for using pdfcpu 💚

**Comment by seongwon-privatenote** [comment]
Oh, I see.  Thank you so much for the detailed explanation.
