### ISSUE TITLE
collect: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by haifenghan** [pdfcpu/pdfcpu#705]
"pdfcpu collect -pages 5-8 2308.16597.pdf out.pdf" has an error:

> unexpected panic attack: runtime error: invalid memory address or nil pointer dereference

env:
macos ventura 13.5
Apple M2 chip
pdfcpu version: v0.5.0 dev
pdfcpu is installed via 'brew install pdfcpu'

PDF file is attached
[2308.16597.pdf](https://github.com/pdfcpu/pdfcpu/files/12536750/2308.16597.pdf)

**Comment by hhrutter** [comment]
Thanks I take a look!

**Comment by hhrutter** [comment]
This is fixed with the latest commit.
