### ISSUE TITLE
Fatal: dict=markupAnnot entry=IT: unsupported in version 1.4

### ISSUE THREAD

**Issue by cezarmathe** [pdfcpu/pdfcpu#706]
Hello, unfortunately I cannot submit the PDF as well as it's customer data.

**OS**: Arch Linux (Rolling)
**pdfcpu version**: tried both v0.5.0 and latest main (`5349a52db6c5548880871ce76824b85443a4829a` at the time of writing)

Here's a log:

[pdfcpu.log](https://github.com/pdfcpu/pdfcpu/files/12540781/pdfcpu.log)

Full error message: `Fatal: dict=markupAnnot entry=IT: unsupported in version 1.4 This file could be PDF/A compliant but pdfcpu only supports versions <= PDF V1.7`.

**Comment by hhrutter** [comment]
This field is optional and defined since PDF Version 1.6 - hence a spec violation.

**Comment by cezarmathe** [comment]
Not sure I'm following. Do you mean one of these?

1. My document is PDFv1.4 but the `IT` entry is defined in PDFv1.6.
2. My document is PDFv1.6 but pdfcpu thought it's PDFv1.4.
3. My document violates the spec rather than pdfcpu being the limitation.

**Comment by hhrutter** [comment]
1 + 2

**Comment by hhrutter** [comment]
This is fixed with latest commit.
