### ISSUE TITLE
ValidationNone no longer supported in Merge() function since v0.5.0

### ISSUE THREAD

**Issue by blakepatteson** [pdfcpu/pdfcpu#708]
Hi - first of all thanks for all your work on this library!

I noticed that this started failing as of upgrading to the latest version : 
    -Using version 0.5.0 - github.com/pdfcpu/pdfcpu v0.5.0
    -Using Windows 10 Pro Version 22H2 (OS Build 19045.3324)
    -Using Go version go version go1.21.1 windows/amd64

Steps to Reproduce : call the function : 

```func MergeCreateFile(inFiles []string, outFile string, conf *model.Configuration) (err error)``` 

...with a conf.ValidationMode of "model.ValidationNone" and see if the config is overwritten

I had this simple wrapper function that would call "api.MergeCreateFile()" with my specific config : 
```
func combinePDFs(allDocuments []pdfDocument, outPath string) error {
	conf := model.NewDefaultConfiguration()
	conf.ValidationMode = model.ValidationNone
	allPaths := getPathsFromDocumentSlice(allDocuments)
	if err := api.MergeCreateFile(allPaths, outPath, conf); err != nil {
		return &models.CmdErrorDetails{
			IsFatal: true,
			Title:   "ERR MERGING PDFS",
			Message: "Something went wrong when cominbing the input PDF's. Details : \n",
			ValuesList: append([]string{
				err.Error(),
				fmt.Sprintf("outPath : '%v'", outPath),
				fmt.Sprintf("conf : '%+v'", conf),
			}, allPaths[0], allPaths[1], "...", allPaths[len(allPaths)-1]),
		}
	}
	return nil
}
````

I want to ignore the validation errors for this particular operation, but as of be323230ede519cb324710899196d72f29315de1, it appears that this functionality is no longer supported 

In the previous version, it used to work fine. Now I get this error and this output : 

```
Now creating PDF......conf : 'pdfcpu configuration:
Path:              disable
CheckFileNameExt:  true
Reader15:          true
DecodeAllStreams:  false
ValidationMode:    none
Eol:               EolLF
WriteObjectStream: true
WriteXrefStream:   true
EncryptUsingAES:   true
EncryptKeyLength:  256
Permissions:       -3901
Unit :             points
TimestampFormat:        2006-01-02 15:04
DateFormat:             2006-01-02
HeaderBufSize:          100
OptimizeDuplicateContentStreams false
CreateBookmarks false
'
!!! ERR MERGING PDFS !!!
!!! ERR MERGING PDFS !!!

Something went wrong when cominbing the input PDF's. Details :

dict=extGStateDict entry=TK: unsupported in version 1.3
This file could be PDF/A compliant but pdfcpu only supports versions <= PDF V1.7

outPath : 'C\path\test\multi_employer_test/test.pdf'
conf : 'pdfcpu configuration:
Path:              disable
CheckFileNameExt:  true
Reader15:          true
DecodeAllStreams:  false
ValidationMode:    relaxed
Eol:               EolLF
WriteObjectStream: true
WriteXrefStream:   true
EncryptUsingAES:   true
EncryptKeyLength:  256
Permissions:       -3901
Unit :             points
TimestampFormat:        2006-01-02 15:04
DateFormat:             2006-01-02
HeaderBufSize:          100
OptimizeDuplicateContentStreams false
CreateBookmarks false
'
```

So it looks like "Merge()" no longer supports config "ValidationMode" of "ValidationNone" - not sure if that was intentional based on be323230ede519cb324710899196d72f29315de1?

For now my work around is just reverting to "0.4.0" for my use case.

**Comment by hhrutter** [comment]
Since bookmark handling is now part of *merging* all input files for merging have to pass validation.
Skipping validation is never a good idea and is only meant to be a last resort.

**Comment by blakepatteson** [comment]
Got it - thanks for getting back to me!

So it sounds like [the other library (no longer maintained)](https://github.com/phpdave11/gofpdf) I'm using to generate the input files might not all be passing validation, specifically it's giving with the extGStateDict : 

```
dict=extGStateDict entry=TK: unsupported in version 1.3
This file could be PDF/A compliant but pdfcpu only supports versions <= PDF V1.7
```

Any plans to support form-filling or using template PDF's in pdf generation like this [phpdave11/gofpdf](https://github.com/phpdave11/gofpdf) package? 

I'd definitely like to validate my pdf's, but it's also nice to have the option to override, especially since it's defined as valid config option here : 

```
const (
	// ValidationStrict ensures 100% compliance with the spec (PDF 32000-1:2008).
	ValidationStrict int = iota

	// ValidationRelaxed ensures PDF compliance based on frequently encountered validation errors.
	ValidationRelaxed

	// ValidationNone bypasses validation.
	ValidationNone
)
```

Would it be helpful if a log message was added to indicate to the user that the config settings are being overridden? If you think it's a good idea, I'd be happy to submit a pull request. Let me know what you think!

```
conf.ValidationMode = model.ValidationRelaxed
```

Thanks again!

**Comment by hhrutter** [comment]
I just pushed  a fix for you that relaxes validation of the symptom you mentioned above within the extGStateDict.
So that should at least should disappear after you *go install* the latest commit.

As far as **ValidationNone** let me think about how we're going to handle this moving forward.

Fact:
Validation is the perfect place to cache a few things along the way and for interning data structures for easier manipulation in subsequent processing operations. Hence some operations just need validation turned on or they won't work.

**Comment by blakepatteson** [comment]
Thanks so much!! Using 04840dd2b5ee9481547a08e33ea846ded6c2c31b fixed my issue with this error : 
```
dict=extGStateDict entry=TK: unsupported in version 1.3
This file could be PDF/A compliant but pdfcpu only supports versions <= PDF V1.7
```

Plus now my pdf's are being validated now, which is great.

And that's good to know. I appreciate having this new option of ***not*** having to override the pdfcpu's defaults.

Question - Does pdfcpu have a way to write text at certain (x,y) points on a given PDF page? Looks like [stamp](https://pdfcpu.io/core/stamp) may be the way to accomplish that?

I'd like to ditch my [phpdave11/gofpdf](https://github.com/phpdave11/gofpdf) dependency entirely (since it's no longer under active development), so I may just try and use pdfcpu instead with the [form](https://pdfcpu.io/form/form) or (possibly) [image](https://pdfcpu.io/generate/import) api. 

Regardless - thanks again!

**Comment by hhrutter** [comment]
Yes! => https://pdfcpu.io/core/stamp

**Comment by blakepatteson** [comment]
Very good - thanks a lot! I'll see if I can use pdfcpu instead for my purposes 👍
