### ISSUE TITLE
Watermarking fails with: unexpected EOF

### ISSUE THREAD

**Issue by tomassommareqt** [pdfcpu/pdfcpu#713]
First, thank you for a great pdf processing library!

There is an issue in pdfcpu.AddWatermarks causing it to fail if the pdf contains a flated content stream containing an EOF which is not uncommon.

After some investigation, this seem to stem from a known "dubious" behaviour in the standard libraries compression/zlib library. See the following go issue on GitHub: [https://github.com/golang/go/issues/14675](https://github.com/golang/go/issues/14675).

This has caused regressions in other standard library packages, e.g. [https://github.com/golang/go/issues/14676](https://github.com/golang/go/issues/14676). This have been fixed by wrapping the io.Reader in a stickyErrorReader. See: [https://go-review.googlesource.com/c/go/+/20297](https://go-review.googlesource.com/c/go/+/20297).

There are other PDF libraries that deal with the situation where an EOF is contained within a flated content stream. E.g., see the decompress function on line 66 in [https://github.com/py-pdf/pypdf/blob/main/pypdf/filters.py](https://github.com/py-pdf/pypdf/blob/main/pypdf/filters.py).

Do you think a similar way of dealing with possible EOFs in flated content streams can be implemented in pdfcpu?

OS: Mac OS X Ventura 13.5.2

**Comment by hhrutter** [comment]
Please share or point me to a test file for analysis and I am on it!

**Comment by hhrutter** [comment]
Will be addressed in the next release - see also #722

**Comment by hhrutter** [comment]
This should be fixed with https://github.com/pdfcpu/pdfcpu/releases/tag/v0.6.0

**Comment by tomassommareqt** [comment]
Thanks for fixing this! And sorry for not being of more assistance.

**Comment by hhrutter** [comment]
No problem!
