### ISSUE TITLE
Error Read: xRefTable failed: pdfcpu: headerVersion: corrupt pdf stream - no header version available

### ISSUE THREAD

**Issue by coderlabs** [pdfcpu/pdfcpu#714]
Get error when read context 

 "Read: xRefTable failed: pdfcpu: headerVersion: corrupt pdf stream - no header version available"

the example pdf https://icseindia.org/document/sample.pdf

**Comment by hhrutter** [comment]
Works fine for me using the latest commit.

Please check the version/commit you are using.

**Comment by coderlabs** [comment]
i'm using from branch master, but got still same error message : Read: xRefTable failed: pdfcpu: headerVersion: corrupt pdf stream - no header version available
