### ISSUE TITLE
Merge odd/even pages together (im-mem)

### ISSUE THREAD

**Issue by milkpirate** [pdfcpu/pdfcpu#716]
Hey,

I have a scanner that can scan to PDF @ FTP but that only single sided. What I now have is an in-mem FTP server (with a virtual system) that receives two PDF, one with all even pages one with all odd pages. I want to combine them correctly into one PDF and send the result by mail or put it back to (FTP) file system. The part thats missing is the PDF processing. 

I coded up something but it does not work, the PDF comes out broken:
```go
	target, err := memFs.Create("out.pdf")
	defer target.Close()

	for page := 1; page <= oddPageCount; page++ {
		pages := []string{fmt.Sprintf("%d", page)}
		err = pdfapi.InsertPages(oddReader, target, pages, false, nil)
		err = pdfapi.InsertPages(evenReader, target, pages, false, nil)
	}
```

I also tried to pre-create a empty PDF, and the merge stuff in, but I cant figure out the JSON part. So if there is an option to place a empty PDF in a reader/writer without JSON I would be happy about that:

```go
	err = pdfapi.Create(nil, strings.NewReader("{}"), target, nil)
```

I also saw `CreatePDFFile()` which seems to do what I want, but uses `os.Open()` which would not be my in-mem FS.

If you could hint me to the right code or propose a better option I would be really glad!

Thanks in advance

**Comment by hhrutter** [comment]
Sounds like you need to combine your files like a zipper.

**Comment by milkpirate** [comment]
Exactly.

**Comment by hhrutter** [comment]
Let me see, maybe we can integrate this as a special merging mode.

**Comment by hhrutter** [comment]
FYI This will be part of the upcoming release.

**Comment by hhrutter** [comment]
This is part of https://github.com/pdfcpu/pdfcpu/releases/tag/v0.6.0
See `pdfcpu help merge`.
