### ISSUE TITLE
dict=pagesDict entry=UserUnit: unsupported in version 1.3 This file could be PDF/A compliant but pdfcpu only supports versions <= PDF V1.7

### ISSUE THREAD

**Issue by YootTanA** [pdfcpu/pdfcpu#717]
Hi, I'm having the same issue like this one [93](https://github.com/pdfcpu/pdfcpu/issues/93).

This is my current version 
`pdfcpu: v0.5.0 dev`

This is the result from running this command `pdfcpu validate -vv downloads/runpod-invoice.pdf`

validating(mode=relaxed) downloads/runpod-invoice.pdf ...
 READ: 2023/09/26 18:38:04 Read: begin
 INFO: 2023/09/26 18:38:04 PDF Version 1.5 conforming reader
 READ: 2023/09/26 18:38:04 readXRefTable: begin
 READ: 2023/09/26 18:38:04 scanning for offsetLastXRefSection starting at 1942
 READ: 2023/09/26 18:38:04 Offset last xrefsection: 1999
 READ: 2023/09/26 18:38:04 buildXRefTableStartingAt: begin
 READ: 2023/09/26 18:38:04 headerVersion begin
 READ: 2023/09/26 18:38:04 headerVersion: end, found header version: 1.3
 READ: 2023/09/26 18:38:04 newPositionedReader: positioned to offset: 1999
 READ: 2023/09/26 18:38:04 xref line 1: <xref>
 READ: 2023/09/26 18:38:04 buildXRefTableStartingAt: found xref section
 READ: 2023/09/26 18:38:04 parseXRefSection begin
 READ: 2023/09/26 18:38:04 parseXRefSection: <0 15>
 READ: 2023/09/26 18:38:04 parseXRefTableSubSection: begin
 READ: 2023/09/26 18:38:04 detected xref subsection, startObj=0 length=15
 READ: 2023/09/26 18:38:04 parseXRefTableEntry: begin
 READ: 2023/09/26 18:38:04 parseXRefTableEntry: Object #0 is unused, next free is object#0, generation=65535
 READ: 2023/09/26 18:38:04 parseXRefTableEntry: Insert new xreftable entry for Object 0
 READ: 2023/09/26 18:38:04 parseXRefTableEntry: end
 READ: 2023/09/26 18:38:04 parseXRefTableEntry: begin
 READ: 2023/09/26 18:38:04 parseXRefTableEntry: Object #1 is in use at offset=681, generation=0
 READ: 2023/09/26 18:38:04 parseXRefTableEntry: Insert new xreftable entry for Object 1
 READ: 2023/09/26 18:38:04 parseXRefTableEntry: end
 READ: 2023/09/26 18:38:04 parseXRefTableEntry: begin
 READ: 2023/09/26 18:38:04 parseXRefTableEntry: Object #2 is in use at offset=738, generation=0
 READ: 2023/09/26 18:38:04 parseXRefTableEntry: Insert new xreftable entry for Object 2
 READ: 2023/09/26 18:38:04 parseXRefTableEntry: end
 READ: 2023/09/26 18:38:04 parseXRefTableEntry: begin
 READ: 2023/09/26 18:38:04 parseXRefTableEntry: Object #3 is in use at offset=594, generation=0
 READ: 2023/09/26 18:38:04 parseXRefTableEntry: Insert new xreftable entry for Object 3
 READ: 2023/09/26 18:38:04 parseXRefTableEntry: end
 READ: 2023/09/26 18:38:04 parseXRefTableEntry: begin
 READ: 2023/09/26 18:38:04 parseXRefTableEntry: Object #4 is in use at offset=573, generation=0
 READ: 2023/09/26 18:38:04 parseXRefTableEntry: Insert new xreftable entry for Object 4
 READ: 2023/09/26 18:38:04 parseXRefTableEntry: end
 READ: 2023/09/26 18:38:04 parseXRefTableEntry: begin
 READ: 2023/09/26 18:38:04 parseXRefTableEntry: Object #5 is in use at offset=785, generation=0
 READ: 2023/09/26 18:38:04 parseXRefTableEntry: Insert new xreftable entry for Object 5
 READ: 2023/09/26 18:38:04 parseXRefTableEntry: end
 READ: 2023/09/26 18:38:04 parseXRefTableEntry: begin
 READ: 2023/09/26 18:38:04 parseXRefTableEntry: Object #6 is in use at offset=828, generation=0
 READ: 2023/09/26 18:38:04 parseXRefTableEntry: Insert new xreftable entry for Object 6
 READ: 2023/09/26 18:38:04 parseXRefTableEntry: end
 READ: 2023/09/26 18:38:04 parseXRefTableEntry: begin
 READ: 2023/09/26 18:38:04 parseXRefTableEntry: Object #7 is in use at offset=189, generation=0
 READ: 2023/09/26 18:38:04 parseXRefTableEntry: Insert new xreftable entry for Object 7
 READ: 2023/09/26 18:38:04 parseXRefTableEntry: end
 READ: 2023/09/26 18:38:04 parseXRefTableEntry: begin
 READ: 2023/09/26 18:38:04 parseXRefTableEntry: Object #8 is in use at offset=59, generation=0
 READ: 2023/09/26 18:38:04 parseXRefTableEntry: Insert new xreftable entry for Object 8
 READ: 2023/09/26 18:38:04 parseXRefTableEntry: end
 READ: 2023/09/26 18:38:04 parseXRefTableEntry: begin
 READ: 2023/09/26 18:38:04 parseXRefTableEntry: Object #9 is in use at offset=15, generation=0
 READ: 2023/09/26 18:38:04 parseXRefTableEntry: Insert new xreftable entry for Object 9
 READ: 2023/09/26 18:38:04 parseXRefTableEntry: end
 READ: 2023/09/26 18:38:04 parseXRefTableEntry: begin
 READ: 2023/09/26 18:38:04 parseXRefTableEntry: Object #10 is in use at offset=475, generation=0
 READ: 2023/09/26 18:38:04 parseXRefTableEntry: Insert new xreftable entry for Object 10
 READ: 2023/09/26 18:38:04 parseXRefTableEntry: end
 READ: 2023/09/26 18:38:04 parseXRefTableEntry: begin
 READ: 2023/09/26 18:38:04 parseXRefTableEntry: Object #11 is in use at offset=399, generation=0
 READ: 2023/09/26 18:38:04 parseXRefTableEntry: Insert new xreftable entry for Object 11
 READ: 2023/09/26 18:38:04 parseXRefTableEntry: end
 READ: 2023/09/26 18:38:04 parseXRefTableEntry: begin
 READ: 2023/09/26 18:38:04 parseXRefTableEntry: Object #12 is in use at offset=307, generation=0
 READ: 2023/09/26 18:38:04 parseXRefTableEntry: Insert new xreftable entry for Object 12
 READ: 2023/09/26 18:38:04 parseXRefTableEntry: end
 READ: 2023/09/26 18:38:04 parseXRefTableEntry: begin
 READ: 2023/09/26 18:38:04 parseXRefTableEntry: Object #13 is in use at offset=335, generation=0
 READ: 2023/09/26 18:38:04 parseXRefTableEntry: Insert new xreftable entry for Object 13
 READ: 2023/09/26 18:38:04 parseXRefTableEntry: end
 READ: 2023/09/26 18:38:04 parseXRefTableEntry: begin
 READ: 2023/09/26 18:38:04 parseXRefTableEntry: Object #14 is in use at offset=363, generation=0
 READ: 2023/09/26 18:38:04 parseXRefTableEntry: Insert new xreftable entry for Object 14
 READ: 2023/09/26 18:38:04 parseXRefTableEntry: end
 READ: 2023/09/26 18:38:04 parseXRefTableSubSection: end
 READ: 2023/09/26 18:38:04 parseXRefSection: All subsections read!
 READ: 2023/09/26 18:38:04 parseXRefSection: parsing trailer dict..
 READ: 2023/09/26 18:38:04 line (len 7) <trailer>
 READ: 2023/09/26 18:38:04 line: <>
 READ: 2023/09/26 18:38:04 line: <<<>
 READ: 2023/09/26 18:38:04 scanTrailer dictBuf after start tag: <<<>
 READ: 2023/09/26 18:38:04 scanTrailer dictBuf next line: </Size 15>
 READ: 2023/09/26 18:38:04 scanTrailer dictBuf next line: </Root 3 0 R>
 READ: 2023/09/26 18:38:04 scanTrailer dictBuf next line: </Info 11 0 R>
 READ: 2023/09/26 18:38:04 scanTrailer dictBuf next line: </ID [<751ab3bf933f23639ac6e995f4b31fb9> <751ab3bf933f23639ac6e995f4b31fb9>]>
 READ: 2023/09/26 18:38:04 scanTrailer dictBuf next line: <>>>
 READ: 2023/09/26 18:38:04 processTrailer: trailerString: (len:116) <<<
/Size 15
/Root 3 0 R
/Info 11 0 R
/ID [<751ab3bf933f23639ac6e995f4b31fb9> <751ab3bf933f23639ac6e995f4b31fb9>]
>>
>
 READ: 2023/09/26 18:38:04 processTrailer: trailerDict:
<<
	<ID, [<751AB3BF933F23639AC6E995F4B31FB9> <751AB3BF933F23639AC6E995F4B31FB9>]>
	<Info, (11 0 R)>
	<Root, (3 0 R)>
	<Size, 15>
>>
 READ: 2023/09/26 18:38:04 parseTrailerDict begin
 READ: 2023/09/26 18:38:04 parseTrailerInfo begin
 READ: 2023/09/26 18:38:04 parseTrailerInfo: Root object: (3 0 R)
 READ: 2023/09/26 18:38:04 parseTrailerInfo: Info object: (11 0 R)
 READ: 2023/09/26 18:38:04 parseTrailerInfo: ID object: [<751AB3BF933F23639AC6E995F4B31FB9> <751AB3BF933F23639AC6E995F4B31FB9>]
 READ: 2023/09/26 18:38:04 parseTrailerInfo end
 READ: 2023/09/26 18:38:04 parseTrailerDict end
 READ: 2023/09/26 18:38:04 buildXRefTableStartingAt: end
TRACE: 2023/09/26 18:38:04 EnsureValidFreeList begin
TRACE: 2023/09/26 18:38:04 EnsureValidFreeList: empty free list.
 READ: 2023/09/26 18:38:04 readXRefTable: end
 READ: 2023/09/26 18:38:04 dereferenceXRefTable: begin
 READ: 2023/09/26 18:38:04 decodeObjectStreams: begin
 READ: 2023/09/26 18:38:04 decodeObjectStreams: end
 READ: 2023/09/26 18:38:04 dereferenceObjects: begin
 READ: 2023/09/26 18:38:04 dereferenceObject: begin, dereferencing object 0
 READ: 2023/09/26 18:38:04 free object 0
 READ: 2023/09/26 18:38:04 dereferenceObject: begin, dereferencing object 1
 READ: 2023/09/26 18:38:04 in use object 1
 READ: 2023/09/26 18:38:04 dereferenceObject: dereferencing object 1
 READ: 2023/09/26 18:38:04 ParseObject: begin, obj#1, offset:681
 READ: 2023/09/26 18:38:04 newPositionedReader: positioned to offset: 681
 READ: 2023/09/26 18:38:04 object: small obj w/o stream, parse until endobj
 READ: 2023/09/26 18:38:04 dict: end, #1
 READ: 2023/09/26 18:38:04 dereferenceObject: end obj 1 of 15
<<<
	<Count, 1>
	<Kids, [(8 0 R)]>
	<Type, Pages>
>>>
 READ: 2023/09/26 18:38:04 logStream: no ObjectStreamDict
 READ: 2023/09/26 18:38:04 dereferenceObject: begin, dereferencing object 2
 READ: 2023/09/26 18:38:04 in use object 2
 READ: 2023/09/26 18:38:04 dereferenceObject: dereferencing object 2
 READ: 2023/09/26 18:38:04 ParseObject: begin, obj#2, offset:738
 READ: 2023/09/26 18:38:04 newPositionedReader: positioned to offset: 738
 READ: 2023/09/26 18:38:04 object: small obj w/o stream, parse until endobj
 READ: 2023/09/26 18:38:04 dict: end, #2
 READ: 2023/09/26 18:38:04 dereferenceObject: end obj 2 of 15
<<<
	<Dests, <<
		<Names, []>
	>>>
>>>
 READ: 2023/09/26 18:38:04 logStream: no ObjectStreamDict
 READ: 2023/09/26 18:38:04 dereferenceObject: begin, dereferencing object 3
 READ: 2023/09/26 18:38:04 in use object 3
 READ: 2023/09/26 18:38:04 dereferenceObject: dereferencing object 3
 READ: 2023/09/26 18:38:04 ParseObject: begin, obj#3, offset:594
 READ: 2023/09/26 18:38:04 newPositionedReader: positioned to offset: 594
 READ: 2023/09/26 18:38:04 object: small obj w/o stream, parse until endobj
 READ: 2023/09/26 18:38:04 dict: end, #3
 READ: 2023/09/26 18:38:04 dereferenceObject: end obj 3 of 15
<<<
	<Names, (2 0 R)>
	<Pages, (1 0 R)>
	<Type, Catalog>
	<ViewerPreferences, (5 0 R)>
>>>
 READ: 2023/09/26 18:38:04 logStream: no ObjectStreamDict
 READ: 2023/09/26 18:38:04 dereferenceObject: begin, dereferencing object 4
 READ: 2023/09/26 18:38:04 in use object 4
 READ: 2023/09/26 18:38:04 dereferenceObject: dereferencing object 4
 READ: 2023/09/26 18:38:04 ParseObject: begin, obj#4, offset:573
 READ: 2023/09/26 18:38:04 newPositionedReader: positioned to offset: 573
 READ: 2023/09/26 18:38:04 object: small obj w/o stream, parse until endobj
 READ: 2023/09/26 18:38:04 dict: end, #4
 READ: 2023/09/26 18:38:04 dereferenceObject: end obj 4 of 15
<<<
>>>
 READ: 2023/09/26 18:38:04 logStream: no ObjectStreamDict
 READ: 2023/09/26 18:38:04 dereferenceObject: begin, dereferencing object 5
 READ: 2023/09/26 18:38:04 in use object 5
 READ: 2023/09/26 18:38:04 dereferenceObject: dereferencing object 5
 READ: 2023/09/26 18:38:04 ParseObject: begin, obj#5, offset:785
 READ: 2023/09/26 18:38:04 newPositionedReader: positioned to offset: 785
 READ: 2023/09/26 18:38:04 object: small obj w/o stream, parse until endobj
 READ: 2023/09/26 18:38:04 dict: end, #5
 READ: 2023/09/26 18:38:04 dereferenceObject: end obj 5 of 15
<<<
	<DisplayDocTitle, true>
>>>
 READ: 2023/09/26 18:38:04 logStream: no ObjectStreamDict
 READ: 2023/09/26 18:38:04 dereferenceObject: begin, dereferencing object 6
 READ: 2023/09/26 18:38:04 in use object 6
 READ: 2023/09/26 18:38:04 dereferenceObject: dereferencing object 6
 READ: 2023/09/26 18:38:04 ParseObject: begin, obj#6, offset:828
 READ: 2023/09/26 18:38:04 newPositionedReader: positioned to offset: 828
 READ: 2023/09/26 18:38:04 buffer: endInd=-1 streamInd=48
 READ: 2023/09/26 18:38:04 object: big stream, we parse object until stream
 READ: 2023/09/26 18:38:04 pdfFilterPipeline: begin
 READ: 2023/09/26 18:38:04 pdfFilterPipeline: end w/o decode parms
 READ: 2023/09/26 18:38:04 streamDictForObject: end, Streamobject #6
 READ: 2023/09/26 18:38:04 LoadEncodedStreamContent: begin
<<
	<Filter, FlateDecode>
	<Length, 1098>
>>
 READ: 2023/09/26 18:38:04 newPositionedReader: positioned to offset: 883
 READ: 2023/09/26 18:38:04 LoadEncodedStreamContent: seeked to offset:883
 READ: 2023/09/26 18:38:04 readStreamContent: begin streamLength:1098
 READ: 2023/09/26 18:38:04 readStreamContent: count=1098, buflen=1098(44A)
 READ: 2023/09/26 18:38:04 readStreamContent: end
 READ: 2023/09/26 18:38:04 LoadEncodedStreamContent: end: len(streamDictRaw)=1098
 READ: 2023/09/26 18:38:04 saveDecodedStreamContent: begin decode=false
 READ: 2023/09/26 18:38:04 dereferenceObject: end obj 6 of 15
<<<
	<Filter, FlateDecode>
	<Length, 1098>
>>>
 READ: 2023/09/26 18:38:04 logStream: no stream content
 READ: 2023/09/26 18:38:04 dereferenceObject: begin, dereferencing object 7
 READ: 2023/09/26 18:38:04 in use object 7
 READ: 2023/09/26 18:38:04 dereferenceObject: dereferencing object 7
 READ: 2023/09/26 18:38:04 ParseObject: begin, obj#7, offset:189
 READ: 2023/09/26 18:38:04 newPositionedReader: positioned to offset: 189
 READ: 2023/09/26 18:38:04 object: small obj w/o stream, parse until endobj
 READ: 2023/09/26 18:38:04 dict: end, #7
 READ: 2023/09/26 18:38:04 dereferenceObject: end obj 7 of 15
<<<
	<ExtGState, <<
		<Gs1, (9 0 R)>
	>>>
	<Font, <<
		<F1, (10 0 R)>
	>>>
	<ProcSet, [PDF Text ImageB ImageC ImageI]>
>>>
 READ: 2023/09/26 18:38:04 logStream: no ObjectStreamDict
 READ: 2023/09/26 18:38:04 dereferenceObject: begin, dereferencing object 8
 READ: 2023/09/26 18:38:04 in use object 8
 READ: 2023/09/26 18:38:04 dereferenceObject: dereferencing object 8
 READ: 2023/09/26 18:38:04 ParseObject: begin, obj#8, offset:59
 READ: 2023/09/26 18:38:04 newPositionedReader: positioned to offset: 59
 READ: 2023/09/26 18:38:04 object: small obj w/o stream, parse until endobj
 READ: 2023/09/26 18:38:04 dict: end, #8
 READ: 2023/09/26 18:38:04 dereferenceObject: end obj 8 of 15
<<<
	<Contents, (6 0 R)>
	<MediaBox, [0 0 595.28 841.89]>
	<Parent, (1 0 R)>
	<Resources, (7 0 R)>
	<Type, Page>
	<UserUnit, 1>
>>>
 READ: 2023/09/26 18:38:04 logStream: no ObjectStreamDict
 READ: 2023/09/26 18:38:04 dereferenceObject: begin, dereferencing object 9
 READ: 2023/09/26 18:38:04 in use object 9
 READ: 2023/09/26 18:38:04 dereferenceObject: dereferencing object 9
 READ: 2023/09/26 18:38:04 ParseObject: begin, obj#9, offset:15
 READ: 2023/09/26 18:38:04 newPositionedReader: positioned to offset: 15
 READ: 2023/09/26 18:38:04 object: small obj w/o stream, parse until endobj
 READ: 2023/09/26 18:38:04 dict: end, #9
 READ: 2023/09/26 18:38:04 dereferenceObject: end obj 9 of 15
<<<
	<Type, ExtGState>
	<ca, 1>
>>>
 READ: 2023/09/26 18:38:04 logStream: no ObjectStreamDict
 READ: 2023/09/26 18:38:04 dereferenceObject: begin, dereferencing object 10
 READ: 2023/09/26 18:38:04 in use object 10
 READ: 2023/09/26 18:38:04 dereferenceObject: dereferencing object 10
 READ: 2023/09/26 18:38:04 ParseObject: begin, obj#10, offset:475
 READ: 2023/09/26 18:38:04 newPositionedReader: positioned to offset: 475
 READ: 2023/09/26 18:38:04 object: small obj w/o stream, parse until endobj
 READ: 2023/09/26 18:38:04 dict: end, #10
 READ: 2023/09/26 18:38:04 dereferenceObject: end obj 10 of 15
<<<
	<BaseFont, Helvetica>
	<Encoding, WinAnsiEncoding>
	<Subtype, Type1>
	<Type, Font>
>>>
 READ: 2023/09/26 18:38:04 logStream: no ObjectStreamDict
 READ: 2023/09/26 18:38:04 dereferenceObject: begin, dereferencing object 11
 READ: 2023/09/26 18:38:04 in use object 11
 READ: 2023/09/26 18:38:04 dereferenceObject: dereferencing object 11
 READ: 2023/09/26 18:38:04 ParseObject: begin, obj#11, offset:399
 READ: 2023/09/26 18:38:04 newPositionedReader: positioned to offset: 399
 READ: 2023/09/26 18:38:04 object: small obj w/o stream, parse until endobj
 READ: 2023/09/26 18:38:04 dict: end, #11
 READ: 2023/09/26 18:38:04 dereferenceObject: end obj 11 of 15
<<<
	<CreationDate, (14 0 R)>
	<Creator, (13 0 R)>
	<Producer, (12 0 R)>
>>>
 READ: 2023/09/26 18:38:04 logStream: no ObjectStreamDict
 READ: 2023/09/26 18:38:04 dereferenceObject: begin, dereferencing object 12
 READ: 2023/09/26 18:38:04 in use object 12
 READ: 2023/09/26 18:38:04 dereferenceObject: dereferencing object 12
 READ: 2023/09/26 18:38:04 ParseObject: begin, obj#12, offset:307
 READ: 2023/09/26 18:38:04 newPositionedReader: positioned to offset: 307
 READ: 2023/09/26 18:38:04 object: small obj w/o stream, parse until endobj
 READ: 2023/09/26 18:38:04 dereferenceObject: end obj 12 of 15
<(react-pdf)>
 READ: 2023/09/26 18:38:04 logStream: no ObjectStreamDict
 READ: 2023/09/26 18:38:04 dereferenceObject: begin, dereferencing object 13
 READ: 2023/09/26 18:38:04 in use object 13
 READ: 2023/09/26 18:38:04 dereferenceObject: dereferencing object 13
 READ: 2023/09/26 18:38:04 ParseObject: begin, obj#13, offset:335
 READ: 2023/09/26 18:38:04 newPositionedReader: positioned to offset: 335
 READ: 2023/09/26 18:38:04 object: small obj w/o stream, parse until endobj
 READ: 2023/09/26 18:38:04 dereferenceObject: end obj 13 of 15
<(react-pdf)>
 READ: 2023/09/26 18:38:04 logStream: no ObjectStreamDict
 READ: 2023/09/26 18:38:04 dereferenceObject: begin, dereferencing object 14
 READ: 2023/09/26 18:38:04 in use object 14
 READ: 2023/09/26 18:38:04 dereferenceObject: dereferencing object 14
 READ: 2023/09/26 18:38:04 ParseObject: begin, obj#14, offset:363
 READ: 2023/09/26 18:38:04 newPositionedReader: positioned to offset: 363
 READ: 2023/09/26 18:38:04 object: small obj w/o stream, parse until endobj
 READ: 2023/09/26 18:38:04 dereferenceObject: end obj 14 of 15
<(D:20230926042927Z)>
 READ: 2023/09/26 18:38:04 logStream: no ObjectStreamDict
TRACE: 2023/09/26 18:38:04 FindTableEntry: obj#:8 gen:0 
TRACE: 2023/09/26 18:38:04 FindTableEntry: obj#:1 gen:0 
TRACE: 2023/09/26 18:38:04 FindTableEntry: obj#:2 gen:0 
TRACE: 2023/09/26 18:38:04 FindTableEntry: obj#:5 gen:0 
TRACE: 2023/09/26 18:38:04 FindTableEntry: obj#:9 gen:0 
TRACE: 2023/09/26 18:38:04 FindTableEntry: obj#:10 gen:0 
TRACE: 2023/09/26 18:38:04 FindTableEntry: obj#:6 gen:0 
TRACE: 2023/09/26 18:38:04 FindTableEntry: obj#:7 gen:0 
TRACE: 2023/09/26 18:38:04 FindTableEntry: obj#:1 gen:0 
TRACE: 2023/09/26 18:38:04 FindTableEntry: obj#:13 gen:0 
TRACE: 2023/09/26 18:38:04 FindTableEntry: obj#:14 gen:0 
TRACE: 2023/09/26 18:38:04 FindTableEntry: obj#:12 gen:0 
 READ: 2023/09/26 18:38:04 dereferenceObjects: end
 READ: 2023/09/26 18:38:04 identifyRootVersion: begin
TRACE: 2023/09/26 18:38:04 FindTableEntry: obj#:3 gen:0 
 READ: 2023/09/26 18:38:04 dereferenceXRefTable: end
 READ: 2023/09/26 18:38:04 Read: end
 INFO: 2023/09/26 18:38:04 validating
VALID: 2023/09/26 18:38:04 *** validateXRefTable begin ***
VALID: 2023/09/26 18:38:04 *** validateRootObject begin ***
VALID: 2023/09/26 18:38:04 validateNameEntry begin: entry=Type
VALID: 2023/09/26 18:38:04 validateNameEntry end: entry=Type
TRACE: 2023/09/26 18:38:04 FindTableEntry: obj#:1 gen:0 
VALID: 2023/09/26 18:38:04 validateResources: This page node has 1 pages
VALID: 2023/09/26 18:38:04 validateRectangleEntry begin: entry=MediaBox
VALID: 2023/09/26 18:38:04 validateNumberArrayEntry begin: entry=MediaBox
VALID: 2023/09/26 18:38:04 validateArrayEntry begin: entry=MediaBox
VALID: 2023/09/26 18:38:04 validateRectangleEntry begin: entry=CropBox
VALID: 2023/09/26 18:38:04 validateNumberArrayEntry begin: entry=CropBox
VALID: 2023/09/26 18:38:04 validateArrayEntry begin: entry=CropBox
VALID: 2023/09/26 18:38:04 validateIntegerEntry begin: entry=Rotate
VALID: 2023/09/26 18:38:04 validatePagesDict: PageNode: (8 0 R)
TRACE: 2023/09/26 18:38:04 FindTableEntry: obj#:8 gen:0 
TRACE: 2023/09/26 18:38:04 FindTableEntry: obj#:6 gen:0 
TRACE: 2023/09/26 18:38:04 FindTableEntry: obj#:7 gen:0 
TRACE: 2023/09/26 18:38:04 FindTableEntry: obj#:9 gen:0 
VALID: 2023/09/26 18:38:04 validateNameEntry begin: entry=Type
VALID: 2023/09/26 18:38:04 validateNameEntry end: entry=Type
VALID: 2023/09/26 18:38:04 validateNumberEntry begin: entry=LW
VALID: 2023/09/26 18:38:04 validateIntegerEntry begin: entry=LC
VALID: 2023/09/26 18:38:04 validateIntegerEntry begin: entry=LJ
VALID: 2023/09/26 18:38:04 validateNumberEntry begin: entry=ML
VALID: 2023/09/26 18:38:04 validateArrayEntry begin: entry=D
VALID: 2023/09/26 18:38:04 validateNameEntry begin: entry=RI
VALID: 2023/09/26 18:38:04 validateBooleanEntry begin: entry=OP
VALID: 2023/09/26 18:38:04 validateBooleanEntry begin: entry=op
VALID: 2023/09/26 18:38:04 validateIntegerEntry begin: entry=OPM
VALID: 2023/09/26 18:38:04 validateArrayEntry begin: entry=Font
VALID: 2023/09/26 18:38:04 validateNumberEntry begin: entry=FL
VALID: 2023/09/26 18:38:04 validateNumberEntry begin: entry=SM
VALID: 2023/09/26 18:38:04 validateBooleanEntry begin: entry=SA
VALID: 2023/09/26 18:38:04 validateNumberEntry begin: entry=CA
VALID: 2023/09/26 18:38:04 validateNumberEntry begin: entry=ca
VALID: 2023/09/26 18:38:04 validateNumber begin
VALID: 2023/09/26 18:38:04 validateNumber end 
VALID: 2023/09/26 18:38:04 validateNumberEntry end: entry=ca
VALID: 2023/09/26 18:38:04 validateBooleanEntry begin: entry=AIS
VALID: 2023/09/26 18:38:04 validateBooleanEntry begin: entry=TK
TRACE: 2023/09/26 18:38:04 FindTableEntry: obj#:10 gen:0 
VALID: 2023/09/26 18:38:04 validateNameEntry begin: entry=BaseFont
VALID: 2023/09/26 18:38:04 validateNameEntry end: entry=BaseFont
VALID: 2023/09/26 18:38:04 validateIntegerEntry begin: entry=FirstChar
VALID: 2023/09/26 18:38:04 validateIntegerEntry begin: entry=LastChar
VALID: 2023/09/26 18:38:04 validateNumberArrayEntry begin: entry=Widths
VALID: 2023/09/26 18:38:04 validateArrayEntry begin: entry=Widths
VALID: 2023/09/26 18:38:04 validateDictEntry begin: entry=FontDescriptor
VALID: 2023/09/26 18:38:04 validateStreamDictEntry begin: entry=ToUnicode
VALID: 2023/09/26 18:38:04 validateRectangleEntry begin: entry=MediaBox
VALID: 2023/09/26 18:38:04 validateNumberArrayEntry begin: entry=MediaBox
VALID: 2023/09/26 18:38:04 validateArrayEntry begin: entry=MediaBox
VALID: 2023/09/26 18:38:04 validateArrayEntry end: entry=MediaBox
VALID: 2023/09/26 18:38:04 validateNumberArrayEntry end: entry=MediaBox
VALID: 2023/09/26 18:38:04 validateRectangleEntry end: entry=MediaBox
VALID: 2023/09/26 18:38:04 validateDictEntry begin: entry=AA
VALID: 2023/09/26 18:38:04 validateRectangleEntry begin: entry=CropBox
VALID: 2023/09/26 18:38:04 validateNumberArrayEntry begin: entry=CropBox
VALID: 2023/09/26 18:38:04 validateArrayEntry begin: entry=CropBox
VALID: 2023/09/26 18:38:04 validateRectangleEntry begin: entry=BleedBox
VALID: 2023/09/26 18:38:04 validateNumberArrayEntry begin: entry=BleedBox
VALID: 2023/09/26 18:38:04 validateArrayEntry begin: entry=BleedBox
VALID: 2023/09/26 18:38:04 validateRectangleEntry begin: entry=TrimBox
VALID: 2023/09/26 18:38:04 validateNumberArrayEntry begin: entry=TrimBox
VALID: 2023/09/26 18:38:04 validateArrayEntry begin: entry=TrimBox
VALID: 2023/09/26 18:38:04 validateRectangleEntry begin: entry=ArtBox
VALID: 2023/09/26 18:38:04 validateNumberArrayEntry begin: entry=ArtBox
VALID: 2023/09/26 18:38:04 validateArrayEntry begin: entry=ArtBox
VALID: 2023/09/26 18:38:04 validateDictEntry begin: entry=BoxColorInfo
VALID: 2023/09/26 18:38:04 validateIntegerEntry begin: entry=Rotate
VALID: 2023/09/26 18:38:04 validateDictEntry begin: entry=Group
VALID: 2023/09/26 18:38:04 validateStreamDictEntry begin: entry=Thumb
VALID: 2023/09/26 18:38:04 validateIndRefArrayEntry begin: entry=B
VALID: 2023/09/26 18:38:04 validateArrayEntry begin: entry=B
VALID: 2023/09/26 18:38:04 validateNumberEntry begin: entry=Dur
VALID: 2023/09/26 18:38:04 validateDictEntry begin: entry=Trans
VALID: 2023/09/26 18:38:04 validateStreamDictEntry begin: entry=Metadata
VALID: 2023/09/26 18:38:04 validateIntegerEntry begin: entry=StructParents
VALID: 2023/09/26 18:38:04 validateStringEntry begin: entry=ID
VALID: 2023/09/26 18:38:04 validateNumberEntry begin: entry=PZ
VALID: 2023/09/26 18:38:04 validateDictEntry begin: entry=SeparationInfo
VALID: 2023/09/26 18:38:04 validateNameEntry begin: entry=Tabs
VALID: 2023/09/26 18:38:04 validateNameEntry begin: entry=TemplateInstantiated
VALID: 2023/09/26 18:38:04 validateDictEntry begin: entry=PresSteps
VALID: 2023/09/26 18:38:04 validateNumberEntry begin: entry=UserUnit
TRACE: 2023/09/26 18:38:04 freeList begin
STATS: 2023/09/26 18:38:04 XRefTable:
*************************************************************************************************
HeaderVersion: 1.3
has 1 pages
XRefTable:
                     Size: 15
              Root object: (3 0 R)
              Info object: (11 0 R)
                ID object: [<751AB3BF933F23639AC6E995F4B31FB9> <751AB3BF933F23639AC6E995F4B31FB9>]
XRefTable with 15 entries:
    0: f   next=       0 generation=65535
    1:   offset=     681 generation=0 types.Dict type=Pages 
<<
	<Count, 1>
	<Kids, []>
	<Type, Pages>
>>
    2:   offset=     738 generation=0 types.Dict 
<<
	<Dests, <<
		<Names, []>
	>>>
>>
    3:   offset=     594 generation=0 types.Dict type=Catalog 
<<
	<Names, (2 0 R)>
	<Pages, (1 0 R)>
	<Type, Catalog>
	<ViewerPreferences, (5 0 R)>
>>
    4:   offset=     573 generation=0 types.Dict 
<<
>>
    5:   offset=     785 generation=0 types.Dict 
<<
	<DisplayDocTitle, true>
>>
    6:   offset=     828 generation=0 types.StreamDict 
<<
	<Filter, FlateDecode>
	<Length, 1098>
>>
decoded stream content (length = 0)

    7:   offset=     189 generation=0 types.Dict 
<<
	<ExtGState, <<
		<Gs1, (9 0 R)>
	>>>
	<Font, <<
		<F1, (10 0 R)>
	>>>
	<ProcSet, [PDF Text ImageB ImageC ImageI]>
>>
    8:   offset=      59 generation=0 types.Dict type=Page 
<<
	<Contents, (6 0 R)>
	<MediaBox, [0 0 595.28 841.89]>
	<Parent, (1 0 R)>
	<Resources, (7 0 R)>
	<Type, Page>
	<UserUnit, 1>
>>
    9:   offset=      15 generation=0 types.Dict type=ExtGState 
<<
	<Type, ExtGState>
	<ca, 1>
>>
   10:   offset=     475 generation=0 types.Dict type=Font subType=Type1 
<<
	<BaseFont, Helvetica>
	<Encoding, WinAnsiEncoding>
	<Subtype, Type1>
	<Type, Font>
>>
   11:   offset=     399 generation=0 types.Dict 
<<
	<CreationDate, (14 0 R)>
	<Creator, (13 0 R)>
	<Producer, (12 0 R)>
>>
   12:   offset=     307 generation=0 types.StringLiteral 
(react-pdf)
   13:   offset=     335 generation=0 types.StringLiteral 
(react-pdf)
   14:   offset=     363 generation=0 types.StringLiteral 
(D:20230926042927Z)

Empty free list.

Total pages: 1
No font info available.

No image info available.

STATS: 2023/09/26 18:38:04 Timing:
STATS: 2023/09/26 18:38:04 read                 :  0.001s  80.0%
STATS: 2023/09/26 18:38:04 validate             :  0.000s  20.0%
STATS: 2023/09/26 18:38:04 total processing time:  0.002s

STATS: 2023/09/26 18:38:04 Original:
STATS: 2023/09/26 18:38:04 File size            : 2 KB (2454 bytes)
STATS: 2023/09/26 18:38:04 Total binary data    : 1 KB (1098 bytes) 44.7%
STATS: 2023/09/26 18:38:04 Total other data     : 1 KB (1356 bytes) 55.3%

Fatal: dict=pagesDict entry=UserUnit: unsupported in version 1.3
This file could be PDF/A compliant but pdfcpu only supports versions <= PDF V1.7

----------------------------------------------

From what I know is that relaxed mode should ignore this version problem, but It still occur with the file that I have tested.

Thank for checking.
Please tell me if you want more information.

**Comment by hhrutter** [comment]
if you can share a sample I can provide a fix.

**Comment by hhrutter** [comment]
This is fixed with the latest commit but ideally you should file a bug with react-pdf, the producer of your file.

**Comment by YootTanA** [comment]
Thank you sir, the issue is fixed. 

I'll try finding next bugs with react-pdf.
