### ISSUE TITLE
catalog: missing root dict

### ISSUE THREAD

**Issue by vedantmamgain** [pdfcpu/pdfcpu#722]
Got the following error while trying to Lock the form fields of a form pdf. I've shared the pdf over email, can you let me know the context behind the error and what might be the reason behind it.

**Comment by hhrutter** [comment]
Hi there!

This file cannot get parsed because of an EOF embedded into a FlateEncoded stream.
We already have an issue around this - see also #713.

**Comment by hhrutter** [comment]
This is fixed with https://github.com/pdfcpu/pdfcpu/releases/tag/v0.6.0
