### ISSUE TITLE
"insufficient access permissions" is insufficiently specific

### ISSUE THREAD

**Issue by Derek-Jones** [pdfcpu/pdfcpu#723]
The message: "insufficient access permissions" is an insufficiently specific message.

It could imply that the user does not have permissions to write images to the output directory (which I initially assumed).

A more helpful message would be something like:

"Insufficient pdf access permissions (see _permissions_ options)"

**Comment by hhrutter** [comment]
👍🏻

**Comment by hhrutter** [comment]
This is part of https://github.com/pdfcpu/pdfcpu/releases/tag/v0.6.0
