### ISSUE TITLE
Can only extract background images

### ISSUE THREAD

**Issue by mirh** [pdfcpu/pdfcpu#727]
https://www.quellidel68.it/doc/1966/LaZanzara196604.pdf
It only extracts backgrounds, but not the text images (ironically libreoffice seems to to do the opposite).

**Comment by hhrutter** [comment]
Hi!
Sorry for the delay, long pipeline.. I will check it out!

**Comment by hhrutter** [comment]
This is fixed with the upcoming release.

**Comment by hhrutter** [comment]
This is fixed with https://github.com/pdfcpu/pdfcpu/releases/tag/v0.6.0

**Comment by mirh** [comment]
It's better, but alas what I wanted is the JBIG2 mask (I verified that with `pdfimages`)
So this is blocked by #189 now I guess
