### ISSUE TITLE
corrupt pdf stream - no header version available

### ISSUE THREAD

**Issue by Ullaakut** [pdfcpu/pdfcpu#728]
Hi!

I am using the pdfcpu API and the CLI, and I can't seem to reproduce the CLI's behavior using the API because it seems that providing the default configuration with just the unit type changed causes the PDF header to be corrupt.

Here is the code I run when using the API:

```go
// Generate generates a PDF from the given card paths.
func (g *Generator) Generate(ctx context.Context, outPath string, cards []string) error {
	select {
	case <-ctx.Done():
		return nil
	default:
	}

	mod, err := api.ImageGridConfig(g.gridX, g.gridY, fmt.Sprintf("d:%d %d, bo:off", g.cellX, g.cellY))
	if err != nil {
		return fmt.Errorf("configuring grid: %w", err)
	}

	cfg := model.NewDefaultConfiguration()
	cfg.Unit = types.MILLIMETRES

	err = api.NUpFile(cards, outPath, nil, mod, cfg)
	if err != nil {
		return fmt.Errorf("creating PDF: %w", err)
	}

	return nil
}
```

And here is how I do it using the CLI: `pdfcpu grid -u="mm" -- "d:66 90, bo:off" test.pdf 3 3 <files>`

The PDF files generated via CLI work just fine, but those generated through the API can't be opened or used by other API calls.
When I try to merge them, I get the following error:

```go
Error: merging: Read: xRefTable failed: pdfcpu: headerVersion: corrupt pdf stream - no header version available
```

This issue only seems to happen when I specify a configuration though, but I only use the default configuration, and it exactly matches my cli config (`pdfcpu config`) besides the unit type.

Am I doing something wrong or is this a bug?

**Comment by hhrutter** [comment]
Hi there!
Can you share one of these corrupted artefacts for analysis and to see what's going on.
Thank you!

**Comment by Ullaakut** [comment]
Hi @hhrutter ! Thanks for the very fast reponse :) 

I tried reproducing it now and it doesn't seem to happen anymore.

It looks like it might actually have been related to irregular image size, because now that I uncommented the original code, it runs fine. All that changed since then is that I normalized the input images:

```go
// Generate generates a PDF from the given card paths.
func (g *Generator) Generate(ctx context.Context, outPath string, cards []string) error {
	select {
	case <-ctx.Done():
		return nil
	default:
	}

	// args := []string{
	// 	"grid",
	// 	"-u", "mm",
	// 	"--",
	// 	"d:66 90, bo:off",
	// 	outPath,
	// 	fmt.Sprint(g.gridX),
	// 	fmt.Sprint(g.gridY),
	// }
	// args = append(args, cards...)
	//
	// g.log.Info("Running command", lctx.Str("command", "pdfcpu"), lctx.Strs("args", args))
	// err := exec.Command("pdfcpu", args...).Run()
	// if err != nil {
	// 	return fmt.Errorf("creating grid: %w", err)
	// }

	// FIXME: https://github.com/pdfcpu/pdfcpu/issues/728
	mod, err := api.ImageGridConfig(g.gridX, g.gridY, fmt.Sprintf("d:%d %d, bo:off", g.cellX, g.cellY))
	if err != nil {
		return fmt.Errorf("configuring grid: %w", err)
	}

	err = api.NUpFile(cards, outPath, nil, mod, nil)
	if err != nil {
		return fmt.Errorf("creating PDF: %w", err)
	}

	return nil
}
```

I couldn't find the corrupted files from yesterday though, so I'll have to try to reproduce the issue after work today. Will update the issue as soon as I manage to do so!

Sorry for the confusion 😬
