### ISSUE TITLE
PDFInfo Function Error: Invalid Dict Entry: Link

### ISSUE THREAD

**Issue by bosix** [pdfcpu/pdfcpu#730]
Hey there :),

I encountered an issue while using the PDFInfo function on a PDF file. The error message I received was `pdfcpu: validateNameEntry: dict=formFieldDict entry=Subtype invalid dict entry: Link`.

I think this might have something to do with the following bit of PDF code:

```
25 0 obj
<</BS<</W 0>>/A<</S/URI/Type/Action/URI(mailto:test@example.com)>>/StructParent 3/Subtype/Link/F 4/Rect[358.91 245.84 459.35 263.26]>>
endobj
```

From what I can tell, "/Subtype/Link" should be fine - it's just saying that the object is a link. But for some reason, the PDFInfo function is having none of it.

It's worth mentioning that the PDF is a version 1.7 and was made with a custom tool. I'm not 100% sure that this line of code is the culprit, but it seems like a likely suspect. Further, we're using the library as a go module (v0.5.0) and the final go binary is running on linux mint (current lts).

Could you guys give me a hand with this? I'm not sure if it's a bug with PDFInfo, a weird thing with the PDF file, or maybe even something funky with the tool that made the PDF. Any insights would be super appreciated.

Thanks a bunch!

Best, Bosi

**Comment by hhrutter** [comment]
Hi!
Does your file pass validation?
`pdfcpu val test.pdf`

**Comment by bosix** [comment]
Hi,

no it does not:
![image](https://github.com/pdfcpu/pdfcpu/assets/26360670/5a91d175-87eb-49da-8782-c143a651e7da)

Here the corresponding object inside the pdf:
```
23 0 obj
<</BS<</W 0>>/A<</S/URI/Type/Action/URI(mailto:test@example.com)>>/StructParent 1/Subtype/Link/F 4/Rect[89.6 627.13 197.45 640.93]>>
endobj
```

**Comment by hhrutter** [comment]
Looks like a PDF spec violation to me.
Formfield dictionaries require `Subtype=Widget`.

**Comment by bosix** [comment]
Could you please provide further details about the issue? I'm not aware of any form fields inside the PDF.

**Comment by hhrutter** [comment]
This happens - sometimes there is an invisible or defunced  form.
If I had the file in front of me I could get to the bottom of this.

**Comment by bosix** [comment]
We have digged down the issue and found out that is was definitely a problem with the pdf itself.
Since it has nothing to do this pdfcpu, I'll close this issue.
