### ISSUE TITLE
More control over multistamp/multiwatermark placement (in terms of pages)

### ISSUE THREAD

**Issue by vsenko** [pdfcpu/pdfcpu#733]
Currently multistamp/multiwatermark are applied in a fixed manner: the first page of the recipient PDF gets the first page of the multistamp/multiwatermark (1-1), 2-2, 3-3, and etc.

In certain scenarios it would be convenient to be able to arrange placement of multistamp/multiwatermark differently, for example: 1-x, 2-1, 3-2, etc. Or 1-x, 2-x, 3-1, 4-2, etc. To shift the beginning of multistamp/multiwatermark several pages.

**Comment by hhrutter** [comment]
Not necessarily.
The stamp API provides a selectedPages parameter.
Execute on your cmd line for more on this: `pdfcpu selectedpages`

**Comment by hhrutter** [comment]
This fixed with https://github.com/pdfcpu/pdfcpu/releases/tag/v0.6.0
