### ISSUE TITLE
dereferenceObject: problem dereferencing object 1: pdfcpu: ParseObjectAttributes: can't find object number

### ISSUE THREAD

**Issue by vedantmamgain** [pdfcpu/pdfcpu#736]
I faced the above error when trying to validate a pdf. I've shared the pdf over the email

**Comment by hhrutter** [comment]
👍🏻 I will check it out.

**Comment by hhrutter** [comment]
This will be fixed in the upcoming release.

**Comment by vedantmamgain** [comment]
Thanks for the update @hhrutter

**Comment by hhrutter** [comment]
This is part of https://github.com/pdfcpu/pdfcpu/releases/tag/v0.6.0
