### ISSUE TITLE
Troubleshooting PDF Validate Error

### ISSUE THREAD

**Issue by sarahzc9** [pdfcpu/pdfcpu#737]
OS: MacOS Sonoma 14.0

Hi there! Thanks for this wonderful library. Our project involves filling fillable PDFs using this package and I've run into an issue with one of the PDFs. It's giving the following error when I run `pdfcpu validate`:

`validation error (obj#:864): pdfcpu: array element 0 not a number (Float/Integer`

The package works wonderfully with the other PDFs, so I think it's a problem with this particular file, but I have no clue what it means or what array it's referring to in order to fix it. Any help would be greatly appreciated!

Also, I noticed that this error was posted in this issue from 2 years ago (error number 6 in #384 ), but I can't find the follow ups with any solutions, so if there is something that you can point me towards, that would also be greatly appreciated.

Thank you! ^^

**Comment by sarahzc9** [comment]
Hello again, 

Thank you for the quick response! I pasted the stack trace below and attached the file in question. ^^
[Order - Ontario General Test (Template) - Filable.pdf](https://github.com/pdfcpu/pdfcpu/files/13435688/Order.-.Ontario.General.Test.Template.-.Filable.pdf)
 
```
Fatal: pdfcpu: array element 0 not a number (Float/Integer
github.com/pdfcpu/pdfcpu/pkg/pdfcpu/types.Array.FloatNumber
	github.com/pdfcpu/pdfcpu/pkg/pdfcpu/types/types.go:362
github.com/pdfcpu/pdfcpu/pkg/pdfcpu/types.RectForArray
	github.com/pdfcpu/pdfcpu/pkg/pdfcpu/types/types.go:178
github.com/pdfcpu/pdfcpu/pkg/pdfcpu.Annotation
	github.com/pdfcpu/pdfcpu/pkg/pdfcpu/annotation.go:145
github.com/pdfcpu/pdfcpu/pkg/pdfcpu/validate.validatePageAnnotations
	github.com/pdfcpu/pdfcpu/pkg/pdfcpu/validate/annotation.go:1631
github.com/pdfcpu/pdfcpu/pkg/pdfcpu/validate.validatePagesAnnotations
	github.com/pdfcpu/pdfcpu/pkg/pdfcpu/validate/annotation.go:1699
github.com/pdfcpu/pdfcpu/pkg/pdfcpu/validate.validateRootObject
	github.com/pdfcpu/pdfcpu/pkg/pdfcpu/validate/xReftable.go:1015
github.com/pdfcpu/pdfcpu/pkg/pdfcpu/validate.XRefTable
	github.com/pdfcpu/pdfcpu/pkg/pdfcpu/validate/xReftable.go:41
github.com/pdfcpu/pdfcpu/pkg/api.ValidateContext
	github.com/pdfcpu/pdfcpu/pkg/api/api.go:80
github.com/pdfcpu/pdfcpu/pkg/api.Validate
	github.com/pdfcpu/pdfcpu/pkg/api/validate.go:55
github.com/pdfcpu/pdfcpu/pkg/api.ValidateFile
	github.com/pdfcpu/pdfcpu/pkg/api/validate.go:96
github.com/pdfcpu/pdfcpu/pkg/api.ValidateFiles
	github.com/pdfcpu/pdfcpu/pkg/api/validate.go:119
github.com/pdfcpu/pdfcpu/pkg/cli.Validate
	github.com/pdfcpu/pdfcpu/pkg/cli/cli.go:32
github.com/pdfcpu/pdfcpu/pkg/cli.Process
	github.com/pdfcpu/pdfcpu/pkg/cli/process.go:35
main.process
	github.com/pdfcpu/pdfcpu/cmd/pdfcpu/process.go:136
main.processValidateCommand
	github.com/pdfcpu/pdfcpu/cmd/pdfcpu/process.go:193
main.commandMap.process
	github.com/pdfcpu/pdfcpu/cmd/pdfcpu/cmd.go:143
main.main
	github.com/pdfcpu/pdfcpu/cmd/pdfcpu/main.go:56
runtime.main
	runtime/proc.go:267
runtime.goexit
	runtime/asm_amd64.s:1650
validation error (obj#:864)
github.com/pdfcpu/pdfcpu/pkg/api.Validate
	github.com/pdfcpu/pdfcpu/pkg/api/validate.go:60
github.com/pdfcpu/pdfcpu/pkg/api.ValidateFile
	github.com/pdfcpu/pdfcpu/pkg/api/validate.go:96
github.com/pdfcpu/pdfcpu/pkg/api.ValidateFiles
	github.com/pdfcpu/pdfcpu/pkg/api/validate.go:119
github.com/pdfcpu/pdfcpu/pkg/cli.Validate
	github.com/pdfcpu/pdfcpu/pkg/cli/cli.go:32
github.com/pdfcpu/pdfcpu/pkg/cli.Process
	github.com/pdfcpu/pdfcpu/pkg/cli/process.go:35
main.process
	github.com/pdfcpu/pdfcpu/cmd/pdfcpu/process.go:136
main.processValidateCommand
	github.com/pdfcpu/pdfcpu/cmd/pdfcpu/process.go:193
main.commandMap.process
	github.com/pdfcpu/pdfcpu/cmd/pdfcpu/cmd.go:143
main.main
	github.com/pdfcpu/pdfcpu/cmd/pdfcpu/main.go:56
runtime.main
	runtime/proc.go:267
runtime.goexit
	runtime/asm_amd64.s:1650
```

**Comment by hhrutter** [comment]
This will be fixed in the upcoming release.

**Comment by sarahzc9** [comment]
thank you! may i ask what the issue was? :O

**Comment by hhrutter** [comment]
A bug, where pdfcpu was assuming numeric values for a rectangle.
The reality is the PDF spec also allows for indirect objects within rectangles.

**Comment by sarahzc9** [comment]
Ah I see! Thank you for letting me know. ^^ Not to rush you at all, but I was also wondering if you had a date planned for the next release? If not it's no biggie!

**Comment by hhrutter** [comment]
Over the next couple of days.. I do what I can..

**Comment by sarahzc9** [comment]
Ok, thank you! Again, no rush at all! Was just asking to coordinate with a teammate is all. Thank you for your work ^^

**Comment by hhrutter** [comment]
This is part of https://github.com/pdfcpu/pdfcpu/releases/tag/v0.6.0
