### ISSUE TITLE
invalid border array: [0 0 0 0]

### ISSUE THREAD

**Issue by 3052** [pdfcpu/pdfcpu#743]
using this file:

<https://github.com/pdfcpu/pdfcpu/files/13467741/ISO_IEC_23001-7_2023.en.pdf>

I get this result:

~~~
> pdfcpu validate 'ISO_IEC_23001-7_2023(en).pdf'
validating(mode=relaxed) ISO_IEC_23001-7_2023(en).pdf ...
validation error (obj#:750): invalid border array: [0 0 0 0]
~~~

https://pdfcpu.io/core/validate

**Comment by hhrutter** [comment]
You need to go get the latest commit.

**Comment by 3052** [comment]
confirmed thanks
