### ISSUE TITLE
An extracted image is missing some text that appears in the original

### ISSUE THREAD

**Issue by Derek-Jones** [pdfcpu/pdfcpu#753]
An extracted image is missing some text that appears in the original (using the latest 0.6 release). The images appear in the paper [Estimating computer depreciation using online auction data](https://www.researchgate.net/publication/227611535_Estimating_computer_depreciation_using_online_auction_data)
Below is a screenshot of the top half of Figure 1
![Screenshot from 2023-12-10 20-13-10](https://github.com/pdfcpu/pdfcpu/assets/5067248/f56bb0fc-d195-4398-b476-75ebc00cc021)
Below is the extracted image (which includes a plot not shown in the above screenshot)
![Estimatingcomputerdepreciationauctiondata_06_Im2](https://github.com/pdfcpu/pdfcpu/assets/5067248/999ff122-4c38-4f40-87bf-3853bcd516d2)

The legend text is missing, along with the y-axis numeric labels and the text "New" on the x-axis

**Comment by hhrutter** [comment]
This looks like some sort of layered image, maybe in combination with some PDF native graphics?
I will check it out, but if there is some native rendering on top of an image, of course that's not part of image stream extraction.

**Comment by Derek-Jones** [comment]
I'm guessing that a jpeg image was created and then imported into Acrobat (listed as the Producer; used [qpdf](https://github.com/qpdf/qpdf)).

Would Acrobat fiddle with the image?  No experience in this area.

It's a bit odd that only parts of the image are missing.

**Comment by hhrutter** [comment]
Just confirmed the content stream is painting the values over the image - produced by TeX most probably.

**Comment by Derek-Jones** [comment]
TeX is listed as a producer at the start of the pdf.

**Comment by Derek-Jones** [comment]
Why just part of the image?

Perhaps the text was added to fix a bug in the generated image (i.e., this text should have been in the original)?

**Comment by hhrutter** [comment]
Sorry, I don't know the story of this PDF.
Check out https://www.latex-project.org/
It's a powerful tool.

**Comment by Derek-Jones** [comment]
The suggestion about fixing a bug in the original image is just an idea for why the image stream would add material to an existing image.

I have used LaTeX for my books: Evidence-based software engineering[http://knosof.co.uk/ESEUR/](url)

**Comment by Derek-Jones** [comment]
One option would be to save a 'pdf' image as a svg file.
There are a few tools out there for converting pdf to svg, e.g., [pdf2svg](https://github.com/dawbarton/pdf2svg?tab=readme-ov-file).  Inkscape does the best job of retaining text in the pdf as text in the generated svg.

**Comment by hhrutter** [comment]
Closed due to inactivity.
