### ISSUE TITLE
bookmarks: global offset for bookmark export/import.

### ISSUE THREAD

**Issue by kvii** [pdfcpu/pdfcpu#754]
Most books have a content page. But the page 1 of content page is not the page 1 of pdf itself. So can we add a "global offset" field to ".json" file or can we add it to export/import option?

<img width="1073" alt="image" src="https://github.com/pdfcpu/pdfcpu/assets/56432636/66010cb7-3b13-4a5a-a15c-e0861a3096a1">

Because it's hard to calculate page number when we creating bookmark json from pdf content page.

<img width="1073" alt="image" src="https://github.com/pdfcpu/pdfcpu/assets/56432636/26aa9061-6f67-45fa-8b60-e3e5e89e207e">

**Comment by hhrutter** [comment]
Hello!

What is your exact use case?

If this is about generating bookmarks for an existing file from scratch you just take any discrepancy between logical and semantic page numbers into account when generating the JSON rep.

In the JSON datasets for bookmarks `page` refers to the logical page number whereas `title` is just semantics and you can set it to anything you like:


```
"bookmarks": [
		{
			"title": "Page 1: Level 1",
			"page": 1,
			"color": {
				"R": 0,
				"G": 1,
				"B": 0
			},
			"kids": [
				{
					"title": "Page 2: Level 1.1",
					"page": 2
				},
				{
					"title": "Page 3: Level 1.2",
					"page": 3,
					"kids": [
						{
							"title": "Page 4: Level 1.2.1",
							"page": 4
						}
					]
				}
			]
		}
]
```

**Comment by kvii** [comment]
> If this is about generating bookmarks for an existing file from scratch you just take any discrepancy between logical and semantic page numbers into account when generating the JSON rep.

This is my case. I wanna create a new outline for my pdf. I extract informations by my hand from "the outline page" of pdf. And I'will get result like below:

```json
{
	"bookmarks": [
		{
			"title": "第一章 函数与极限",
			"page": 1,
			"kids": [
				{
					"title": "第一节 映射与函数",
					"page": 1
				},
				{
					"title": "第二节 数列的极限",
					"page": 18
				}
			]
		}
	]
}
```

As you said, there is a difference between logical page numbers and display page numbers. So I want a "offset" field like this:

```jsonc
{
	"bookmarks": [
		{
			"title": "第一章 函数与极限",
			"offset": 15, // Map display page 1 to logical page 16, and for its children.
			"page": 1,
			"kids": [
				{
					"title": "第一节 映射与函数",
					"page": 1
				},
				{
					"title": "第二节 数列的极限",
					"page": 18
				}
			]
		}
	],
	"settings": {
		"offset": 15 // Or make a global field.
	}
}
```

It looks clearly, as same as what I see. Maybe it's better than write some script like `for m = range(bookmarks): m.page += 15`.

**Comment by hhrutter** [comment]
Sorry, I still do not understand your use case.
All I am getting is that there is some delta involved between semantic and physical page numbers.

Are you using the CLI, the API or both and if so in which manner?

Are you trying to modify existing outlines or create new ones for the first time?

Please describe
* your intention
*  the current steps 
*  any pdfcpu command executions involved

**Comment by kvii** [comment]
I'm sorry for my late reply and my poor communication skill. There is a [repo](https://github.com/kvii/bookmark_demo) to explain what I want. And I solve this issue in that repo. 

Sorry again for wasting your time. I'll close this issue soon.
