### ISSUE TITLE
Add margins by scaling down content only (not MediaBox)

### ISSUE THREAD

**Issue by liojacqs** [pdfcpu/pdfcpu#756]
Hello, 

It would be useful to be able to add margins by scaling down content while preserving the document size.

Unless I missed something, I didn't find a way to achieve that, at least in a simple way.
(I could by running 'pdfcpu poster -u mm "f:A4, margin: 5" a4file.pdf dir',  with a 1 page "a4file.pdf", creating a 2 pages file "dir/a4file_page_1.pdf" in which second page has such 5mm margins, but that's not quite simple...)

I have made a quick and dirty test by modifying resize.go as below, but it may not properly work with other stuff like background color, and it's probably not the best way to achieve that.
(It could also be something like an additional "fit" options to pdfcpu crop, resizing and positioning visible content to the new crop size, with or without preserving aspect ratio)

Any comments / suggestions about the way to do this would be appreciated, possibly the occasion for a first contribution on my side.

![image](https://github.com/pdfcpu/pdfcpu/assets/33750856/34e980d7-5d59-4650-89c0-9d3ba0530d27)

**Comment by hhrutter** [comment]
👍🏻 This is cropping while preserving page dimensions.

 Would most probably be something like a `preservePageSize` or `fit` option for the `crop` command.

There are different ways to achieve the scaling that's part of this.
Will be taken into consideration.

**Comment by hhrutter** [comment]
This fixed with https://github.com/pdfcpu/pdfcpu/releases/tag/v0.7.0
You can use the new zoom command to achieve this.
