### ISSUE TITLE
used merge tip:unexpected panic attack: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by wangchengjie-wcj** [pdfcpu/pdfcpu#759]
"pdfcpu merge demo.pdf 0_123.pdf" has an error or use golang to code by follow

> pdf.MergeCreateFile(${0_123.pdf}, ${demo.pdf}, false,nil)

it will tips:
`unexpected panic attack: runtime error: invalid memory address or nil pointer dereference`

env:
go version go1.20.4 linux/amd64
pdfcpu version:v0.6.0

PDF file is attached
0_123.pdf:[0_123.pdf](https://github.com/pdfcpu/pdfcpu/files/13734639/0_123.pdf)
demo.pdf:you can use any file or a output path to replace it

**Comment by wangchengjie-wcj** [comment]
I try to used the tool `validate` to check out this file. The result indicates that the file is eligible

**Comment by hhrutter** [comment]
Thanks! I will check it out!

**Comment by hhrutter** [comment]
Fixed with latest commit!

**Comment by wangchengjie-wcj** [comment]
Thanks!
