### ISSUE TITLE
bugs found by the linter

### ISSUE THREAD

**Issue by sivukhin** [pdfcpu/pdfcpu#761]
I ran [govanish](https://github.com/sivukhin/govanish) linter (it still in the WIP phase) against `pdfcpu` repo and it found several suspicious places. I don't use `pdfcpu` and don't have much context about the project - but found issues looks like a bugs in the implementation.

Linter found following issues:
1. `StreamDict.Clone` method has following code snippet
```go
f := PDFFilter{}
f.Name = v.Name
if f.DecodeParms != nil {
	f.DecodeParms = v.DecodeParms.Clone().(Dict)
}
pl[k] = f
```
  `govanish` reported that `if` condition were removed by compiler which is correct behaviour - `f.DecodeParms` is always `nil` (we created it in the loop). It seems like this is a typo and `v.DecodeParms` should be used there
2. `ParseXRefStreamDict` method has following code snippet:
```go
if len(indArr)%2 > 1 {
	return nil, errXrefStreamCorruptIndex
}
```
  `govanish` reported that this `if` condition were eliminated by compiler and this is correct - because `x % 2` always greater than 1. Based on the code after that check I suspect that this check supposed to validate that array has even length.
3. In the `equalFontNames` internal helper there is a forgotten type cast check.

**Comment by hhrutter** [comment]
Thanks I'll take a look at this.
