### ISSUE TITLE
pdfcpu: command not found

### ISSUE THREAD

**Issue by prescriptionlifeline** [pdfcpu/pdfcpu#763]
According to https://pdfcpu.io/getting_started/install.html all I need to do to install pdfcpu is the following:

```
$ git clone https://github.com/pdfcpu/pdfcpu
$ cd pdfcpu/cmd/pdfcpu
$ go install
$ pdfcpu version
```
When I do all that, however, I get a `pdfcpu: command not found` error.

`go version` returns `go version go1.21.5 linux/amd64` and I'm running Ubuntu 22.04.3 LTS.

**Comment by hhrutter** [comment]
Hi!

After which of the 4 steps above do you get this error?
Can you share a screenshot or post your CLI output?

Thanks!

**Comment by prescriptionlifeline** [comment]
The last step - the only step wherein I'm actually trying to call a command named pdfcpu. If I was going to get an error like that on `go install` the error I'd be getting would be `go:  command not found`. Same thing with `git clone https://github.com/pdfcpu/pdfcpu`. The error is saying **pdfcpu** isn't found - it's not saying git isn't found...

```
prescriptionlifeline@LAPTOP-0JA0S6CM:~$ pdfcpu version
pdfcpu: command not found
```

**Comment by hhrutter** [comment]
Did `go install` complete without error?
If so andyou get command not found you need to locate your binary and maybe put that into your path.
This is all dependent on your platform, which is ?

In case you just want to use the CLI I recommend grabbing the binary for your OS here: https://github.com/pdfcpu/pdfcpu/releases/tag/v0.6.0

**Comment by hhrutter** [comment]
Please answer the following:

* Which OS are you on?
* Did `go install` complete?
* Do you intend to use the CLI or are you going to use the API as well?

**Comment by prescriptionlifeline** [comment]
`which pdfcpu` doesn't return anything.

I made a video showing me trying to follow the directions:

https://www.youtube.com/watch?v=KAX5uxuuxAc

I'm bypassing the `git clone` step because I already did it. I'm bypassing the `cd` because I'm already in that directory in the video. I do an `ls -latr` so you can see the contents of that directory, however, so that should be sufficient for that

**Comment by hhrutter** [comment]
Closed due to inactivity.
