### ISSUE TITLE
Blank form fields in macOS Preview

### ISSUE THREAD

**Issue by bretwalker** [pdfcpu/pdfcpu#769]
Using:
pdfcpu: v0.6.0 dev
commit: e33b502b (2023-12-13T10:22:47Z)
base  : go1.21.0

On macOS 13.6 (22G120)

When I try to populate a PDF form that's been created using Acrobat Pro 2023.008.20458, I am unable to see the populated form fields in macOS Preview unless I edit the form fields. When I deselect a field, the field appears to go back to being blank. If the fields are locked after filling, I cannot select them to view them at all.

<img width="337" alt="Screenshot 2024-01-09 at 3 42 36 PM" src="https://github.com/pdfcpu/pdfcpu/assets/181698/6a03a4f3-55af-4fa1-848a-cd18676f8600">

<img width="337" alt="Screenshot 2024-01-09 at 3 42 51 PM" src="https://github.com/pdfcpu/pdfcpu/assets/181698/de320252-d69e-4fda-bb61-d61acd956188">

The form fields show as being populated in Google Chrome and Adobe Acrobat.
 
The relevant files are here:
[template.pdf](https://github.com/pdfcpu/pdfcpu/files/13878886/template.pdf)
[out.json](https://github.com/pdfcpu/pdfcpu/files/13878883/out.json)
[populated.out.json](https://github.com/pdfcpu/pdfcpu/files/13878885/populated.out.json)
[out.pdf](https://github.com/pdfcpu/pdfcpu/files/13878884/out.pdf)

Thank you for any assistance you can provide.

**Comment by hhrutter** [comment]
Have you checked if the behavior of Mac Preview after filling using pdfcpu is any different after filling with Preview or Acfrobat? MacPreview is known for suboptimal form support.

**Comment by bretwalker** [comment]
It does appear to be different. I tried filling the template PDF in Acrobat and in Preview, and both files opened in Preview with the form field filled.

**Comment by vedantmamgain** [comment]
@hhrutter Facing the same issue with my pdfs as well. Preview seems to be showing some fields as blank whereas Adobe works fine.

**Comment by hhrutter** [comment]
This is working with the latest commit.
Please check and feed back with a sample file in case this persists.

**Comment by bretwalker** [comment]
It doesn't appear to work for me.
I have Preview Version 11.0 (1044.2) on macOS 13.6 (22G120). I can try upgrading to Sonoma to see if it makes a difference.

```
~/go/bin/pdfcpu version
pdfcpu: v0.6.0 dev
commit: 055e03f0 (2024-02-06T22:40:41Z)
base  : go1.21.0
config: /Users/bretwalker/Library/Application Support/pdfcpu/config.yml
```

```
~/go/bin/pdfcpu form fill template.pdf populated.out.json out.pdf
writing out.pdf...
optimizing...
filling...
````

[out.pdf](https://github.com/pdfcpu/pdfcpu/files/14202273/out.pdf)

**Comment by hhrutter** [comment]
This is about the reported blank form fields issue and the sample you have given.
Your latest `out.pdf` is actually regarding #773 which is still being worked on.

**Comment by bretwalker** [comment]
While this does have the same text as I used in #773, I was testing the blank fields. The filled field is still blank in the above version of Preview. I’ll test with an upgraded macOS tomorrow.

**Comment by hhrutter** [comment]
In Preview Version 11.0 (1056.3.2) this is working and the appearance stream gets rendered correctly.
I want to stress though, that Preview remains an unreliable companion as far as PDF forms procressing,
so the focus of pdfcpu remains the behavior of A.Reader as far as form processing.

**Comment by bretwalker** [comment]
I can confirm the fields show filled as expected with Version 11.0 (1056.3.2). Thanks for your help!
