### ISSUE TITLE
panic occurs when call for 'WatermarkContext'

### ISSUE THREAD

**Issue by zvzo** [pdfcpu/pdfcpu#771]
version: 0.6.0
os macos 14.2.1

Panic occurs when calling the interface for adding watermarks. 

 is at the location shown in the screenshot. 

Maybe we need to check whether the array is empty? It may also be that my file is not standard. Is the file just a blank pdf file? If necessary, I can send it to you for review.

// WatermarkContext applies wm for selected pages to ctx.
func WatermarkContext(ctx *model.Context, selectedPages types.IntSet, wm *model.Watermark) error {
	return pdfcpu.AddWatermarks(ctx, selectedPages, wm)
}

![image](https://github.com/pdfcpu/pdfcpu/assets/15996309/e359f257-1cd3-4ca9-9696-7a8449804549)

**Comment by hhrutter** [comment]
Did you check if your file is valid?
`pdfcpu validate test.pdf`

**Comment by zvzo** [comment]
> Did you check if your file is valid? `pdfcpu validate test.pdf`

```
# pdfcpu validate /tmp/add_wm_panic_file.pdf
validating(mode=relaxed) /tmp/add_wm_panic_file.pdf ...
validation ok
```
looks like valid

**Comment by hhrutter** [comment]
ok, please share the file as debugging will be easier.

Thanks for using pdfcpu 💚

**Comment by hhrutter** [comment]
The line numbers of your screenshot are not from v0.6.0

I'd like to see `add_wm_panic_file.pdf`..
It appears to have a page with a corrupt content stream array.

**Comment by hhrutter** [comment]
This is fixed with the latest commit.

The consequence of accepting an empty page content array (which is a PDF spec violation)
is that you can't stamp such a page.

I recommend using testdata/empty.pdf or create such file using one of the more popular tools out there.
