### ISSUE TITLE
Parsing file with lots of dictionaries is extremely slow

### ISSUE THREAD

**Issue by fancycode** [pdfcpu/pdfcpu#775]
I experienced this with a PDF that is a 9-page export of CAD drawings containing lots of small lines and numbers (created using "PDFTron PDFNet, V6.40292"). Unfortunately I can't share the document.

Tested with latest master (b89d7b1ab108d54a983c9653d47df07bbad5336e) and the test script below.

<details>

```golang
package main

import (
	"log"
	"os"

	"github.com/pdfcpu/pdfcpu/pkg/pdfcpu"
	"github.com/pdfcpu/pdfcpu/pkg/pdfcpu/model"
)

func main() {
	log.SetFlags(log.Flags() | log.Lmicroseconds)
	fp, err := os.Open("slow-parse.pdf")
	if err != nil {
		log.Fatal(err)
	}
	defer fp.Close()

	conf := model.NewDefaultConfiguration()
	log.Printf("Parsing ...")
	pdf, err := pdfcpu.Read(fp, conf)
	if err != nil {
		log.Fatal(err)
	}
	log.Printf("Done")

	if err := pdf.EnsurePageCount(); err != nil {
		log.Fatal(err)
	}

	log.Printf("Parsed %d pages", pdf.PageCount)
}
```

</details>

Parsing doesn't stop (I killed it after 5 minutes taking 100% CPU). I have a patch ready takes improves parsing this file to below 4 seconds.

**Comment by hhrutter** [comment]
Hello and thanks fo reporting this!

If parsing does not stop, than that is a bug and smth I'd like to fix.
Usually this kind of behavior is an indicator for cyclical object references and this needs special treatment.
If you know how to create files like this one do you think you can produce and share another small one for testing/analysis ?

Thank you so much!

**Comment by fancycode** [comment]
I don't think it's a cyclic dependency but the fact that parsing dictionaries will iterate on all existing entries (and call `DecodeName` on the keys) for each added new entry, causing exponential timings. See the fix in #776 which fixes the issue for this particular file.

The more (or the larger) dictionaries you have, the slower parsing will get.

We noticed this happening with a file uploaded to one of our webservices, so this was a customer-generated file which I can't share and don't know how it was created (besides what is available in the PDF metadata).

**Comment by fancycode** [comment]
I added an (artificial) test in #776 that takes about 3.5 seconds on master and about 0.6 seconds with the fix (on my machine).

**Comment by hhrutter** [comment]
👍🏻 checking it out..
