### ISSUE TITLE
Allow cancelling of parsing

### ISSUE THREAD

**Issue by fancycode** [pdfcpu/pdfcpu#777]
Depending on the input file, parsing might take too long (see #775). It would be great if there was a way to cancel a previous call to `pdfcpu.Read`.

One possibility would be to add a `context.Context` to the `m̀odel.Configuration`, that, when cancelled, will stop further parsing and return the error from the context as result of the `pdfcpu.Read` call.

I'm happy to provide a PR for this.

**Comment by hhrutter** [comment]
Are we talking about cancelling on the CLI or within the API?

**Comment by fancycode** [comment]
This would be the API side. With the CLI you could just kill the command.

For example if you have a webservice that receives and parses a PDF, you might want to have a timeout when parsing for not blocking the request for too long in cases like #775. Or you could stop parsing if the client-side of the request goes away.

**Comment by hhrutter** [comment]
A timeout situation may not only occur during parsing but elsewhere across the codebase.

Still we can discuss this.
I recall some guidelines out there recommending for lib creators to ideally avoid dealing with concurrency within the lib and leave that up tp the caller. 

Although I am not sure if that's easily doable for you, I'd rather have  the caller manage timeout issues resulting from a pdfcpu API call.

**Comment by fancycode** [comment]
Don't know what you mean about concurrency here. This issue is about being able to cancel any (potentially) long-running task inside pdfcpu - starting with the parsing where I had the initial problem.

Of course I can do the pdfcpu API calls in a background goroutine, but still they will continue to use 100% CPU for minutes (or longer) because they can not be cancelled - even if the associated request in my webservice example above has been cancelled in the meantime.

**Comment by hhrutter** [comment]
👍🏻 Point taken.

Usually smth like this is handled via `context.WithCancel()`
I am not sure I want to use this since this pattern uses a  channel and involves firing up a goroutine.
Actually this would be something the caller can do - why not?

What kind of solution can you propose that does not introduce goroutines and channels?
Curious over here..
