### ISSUE TITLE
Read: xRefTable failed: EOF

### ISSUE THREAD

**Issue by chengyupeng** [pdfcpu/pdfcpu#781]
### Thank you for submitting a possible bug!

Please ensure the following:

* Your issue is based on the latest commit v0.3.13
* State your OS and OS version centos7.6
* When reporting a problem with a specific PDF input file please avoid stating the organization responsible for the PDFWriter - just refer to the *PDFWriter*
Read: xRefTable failed: EOF ,single file has no problem
<img width="184" alt="image" src="https://github.com/pdfcpu/pdfcpu/assets/14007580/67f00306-afa9-43bf-94b2-b8d41640a5e0">

**Comment by hhrutter** [comment]
Thanks for reporting this.

Did you ensure your input PDF files are valid?
`pdfcpu validate test.pdf`

**Comment by hhrutter** [comment]
Does the merging of your documents work on a simple workstation PC,Mac,Linux terminal etc. ?

**Comment by hhrutter** [comment]
Closed due to inactivity.
