### ISSUE TITLE
Issues with extracting embedded fonts

### ISSUE THREAD

**Issue by vedantmamgain** [pdfcpu/pdfcpu#782]
We got the following error after merging pdfs with PDFCPU. Can you explain why the issue happened and what are some possible solutions here.

![image](https://github.com/pdfcpu/pdfcpu/assets/17256082/7b4eb732-6498-410c-ba5f-cd2d68b7681b)

**Comment by vedantmamgain** [comment]
@hhrutter Displaying a merged file using Acrobat

**Comment by hhrutter** [comment]
Closed due to inactivity.
