### ISSUE TITLE
additional booklet options

### ISSUE THREAD

**Issue by adamgreenhall** [pdfcpu/pdfcpu#783]
it turns out there are several more options for booklet making workflows than we originally included in pdfcpu. In particular there are three main types:
* *"simple"* booklet
* *"advanced"* booklet - favored by some book binders that prefer a more complex, but more efficient collation process. This is the type of booklet ordering currently in pdfcpu
* perfect bound booklet - a booklet with a glued binding (i.e. cut the sheets into 4 pages, collate, and then glue), instead of folded and then stapled, like the other two methods above

Each type of booklet comes with its own preferred ordering of pages. 

Also, support for 6-up and 8-up booklets.

I've been using these different methods on a branch for awhile - PR to follow to merge them in.

**Comment by hhrutter** [comment]
That sounds excellent!
👍🏻 Keep em coming..

**Comment by piotr-lasota** [comment]
I might add to that (although perhaps this is me being unable to understand the docs) some additional config for how do we want to print/duplex the output.

e.g. you have a horizontal A5 book that you want to print on A3 horizontal as a booklet folded over the short edge so that you effectively get 8 pages per sheet. Seems like something that can't be done currently.

**Comment by petervwyatt** [comment]
I'd suggest looking at JDF/XJDF specifications if you want to understand the full gamut (and correct terminology) of booklet printing, product folds, page sequencing, etc. See https://github.com/cip4/JDF-Specification - the illustrations (e.g. Table 7.48) are very informative to avoid needing to read the entire spec...

Note that JDF is also directly supported in PDF/VT via DParts/DPM, and "ISO 21812-1:2019 Graphic technology — Print product metadata for PDF files —  Part 1: Architecture and core requirements for metadata".

**Comment by hhrutter** [comment]
#784 merged in.
