### ISSUE TITLE
custom postion for stamp images

### ISSUE THREAD

**Issue by nickpurn22** [pdfcpu/pdfcpu#788]
I want to add stamp in custom postion like x 100 y 250 ?
how to set this postion,thanks

**Comment by hhrutter** [comment]
Set your position to the bottom left corner `position: bl` and then use some `offset: 100, 250`

You have to play around but if you are using an image stamp eg. the image should end up nicely in the corner.

Also have a look at the tests ../api/tests/stamp_test.go and their results in the samples folder of the codebase

**Comment by nickpurn22** [comment]
thank you so much @hhrutter
