### ISSUE TITLE
Merge Pdf failed

### ISSUE THREAD

**Issue by vedantmamgain** [pdfcpu/pdfcpu#792]
I got the following error when trying to merge pdfs using the MergeRaw api function
`pdfcpu: MergeRaw: missing rsc`. 

Should I email the files as well ?

**Comment by hhrutter** [comment]
In merge_test.go we have: TestMergeRaw, which seems to be working.

`MergeRaw` is somehow deprecated, instead try to use:

`func Merge(destFile string, inFiles []string, w io.Writer, conf *model.Configuration, dividerPage bool) error`

**Comment by vedantmamgain** [comment]
@hhrutter I use pdfcpu api and there only `MergeRaw` accepts `[]io.ReadSeeker` and `Writer` since my use case involves merging in memory instead of reading from disk

**Comment by hhrutter** [comment]
Like I said we have a working testcase.

Please add detailed information about your issue!

There is no way to analyze this otherwise.
