### ISSUE TITLE
Problems removing annotations (missing required entry "Obj")

### ISSUE THREAD

**Issue by rdlarah** [pdfcpu/pdfcpu#796]
Hi Horst,

thank you for creating this great tool.

Unfortunately I can't use it to remove all annotations in the pdf file (or on a particular page) at once.

Let's assume I want to remove all of five annotations on page 414 of my test.pdf:
```
harald:~/test$ pdfcpu annot remove -pages 414 test.pdf 
writing test.pdf...
optimizing...
pages: 414
removing all annotations for selected pages!
pdfcpu: validateObjectReferenceDict: missing required entry "Obj"
```

The five annotations, however, are beautifully listed:
```
harald:~/test$ pdfcpu annot list -pages 414 test.pdf 
optimizing...
pages: 414
4 annotations available

Page 414:

  Popup:
     obj#                 rect id  content
    ======================================
     1974 (349, 244, 529, 364)    -> #1968

  Text:
     obj#                 rect                     id content
    =========================================================
     1963 ( 92, 151, 102, 166) ujABwuq5sSWDqo07nwvCoB 
     1966 (167, 222, 256, 237) WmaKX6_0mBTNBWUR-L-A-B 
     1968 (112, 349, 145, 364) 0Lbf4N1s7BrBN5inxKM2RC 
```
and I can remove them by manually giving the obj#'s:
```
harald:~/test$ pdfcpu annot remove test.pdf 1974 1963 1966 1968
writing test.pdf...
optimizing...
```
No error, and they are gone:
```
harald:~/test$ pdfcpu annot list -pages 414 test.pdf 
optimizing...
pages: 414
0 annotations available
```

I'm using the latest version:
```
harald:~/test$ pdfcpu version
pdfcpu: v0.6.0 dev
commit: dae09ebf (2024-01-30T10:04:31Z)
base  : go1.21.6
config: /home/harald/.config/pdfcpu/config.yml
```
on debian sid:
```
harald:~/test$  uname -a
Linux <hostname> 6.6.11-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.6.11-1 (2024-01-14) x86_64 GNU/Linux
```

It seems like pdfcpu finds all obj#'s but does not pass them correctly to the routine that deletes them.

Thanks in advance for looking into it.

Cheers
harald

**Comment by hhrutter** [comment]
Thanks for reporting this!

**Comment by rdlarah** [comment]
Additional Information: the annotations in test.pdf give a warning 
```
Unimplemented annotation: POPPLER_ANNOT_HIGHLIGHT
```
when viewing with `atril test.pdf`

I'm not sure if this can be relevant since `pdfcpu annot remove test.pdf 1974 1963 1966 1968` works without a problem, but...

Cheers 
harald

**Comment by hhrutter** [comment]
POPPLER_ANNOT_HIGHLIGHT ... this is some customization from the Poppler lib and goes beyond the PDF specification.

**Comment by rdlarah** [comment]
You're the expert, Horst. My humble 2 cts, however: 

If pdfcpu can remove it by `#obj` it should be able to remove them all, or for a range of pages...

Besides the error message is at least somewhat misleading.

btw: I removed them using foxitreader for Windows (running on wine) so it's not urgent at all.

**Comment by hhrutter** [comment]
I know... this is being worked on..

**Comment by rdlarah** [comment]
Okay Horst,

on first sight the file is valid:

```
harald:~/test$ pdfcpu val test.pdf 
validating(mode=relaxed) test.pdf ...
validation ok
```

Looking more closely, however:

```
harald:~/test$ pdfcpu val -m strict test.pdf 
validating(mode=strict) test.pdf ...
validation error (obj#:2004) (try -mode=relaxed): dict=type1FontDict required entry=FirstChar missing
```

The output of  `pdfcpu annot remove test.pdf &> trace` amounts to more than 60MB.
I tried to reduce it to the error stack and attach [trace_trunc.txt](https://github.com/pdfcpu/pdfcpu/files/14115792/trace_trunc.txt)

> I have around 80 open issues..

I know, and I understand. My original problem is already solved. So set your priorities, and I'll be happy with it. If you need more input from my side, I'll try to supply what helps.

Unfortunately my GO is much less than adequate, so I can't do much more.

Cheers
harald

**Comment by hhrutter** [comment]
That particular validation error does not make me worry.

OK that's what I needed to know -  removing annotations is actually doing a little bit too much in this case
so the struct tree of your file becomes invalid and the validation post processing step fails.

Stay tuned..

**Comment by rdlarah** [comment]
I'll do.

+1

**Comment by hhrutter** [comment]
This `pdfcpu: validateObjectReferenceDict: missing required entry "Obj"`
is actually a fatal error and the pdfcpu operation gets aborted.

When page annotations are removed the Annotation object itself only gets deleted for a reference count of 1.
When you have a struct tree referring to annotations, the ref count should be > 1 and the annotation object itself does not get deleted, hence the struct tree stays ok.

Looks like the ref counting does not work as intended for your file.

Can you share your test.pdf?
Then I can debug & analyze.

**Comment by rdlarah** [comment]
You've got mail, Horst.

**Comment by hhrutter** [comment]
Fixed with latest commit!

**Comment by rdlarah** [comment]
I can confirm the solution.

Thanks, Horst.
