### ISSUE TITLE
Wrap error during offsetLastXRefSection function rs.seek error

### ISSUE THREAD

**Issue by MdNumanSaleem** [pdfcpu/pdfcpu#797]
code permalink
https://github.com/pdfcpu/pdfcpu/blob/055e03f0bfd445f465e840d5acb8326c4aef86d0/pkg/pdfcpu/read.go#L167

reason:
it would be helpful while debugging the error

**Comment by hhrutter** [comment]
Hello!

Looks like pdfcpu is having a hard time reading in your file.
Can you share your file for analysis?

**Comment by hhrutter** [comment]
Closed due to inactivity.
