### ISSUE TITLE
Panic during outline tree validation

### ISSUE THREAD

**Issue by liron-l** [pdfcpu/pdfcpu#798]
The following [code](https://github.com/pdfcpu/pdfcpu/blob/master/pkg/pdfcpu/validate/outlineTree.go#L122C3-L127C4) panics:
```
if count == nil || *count == 0 {
			if xRefTable.ValidationMode == model.ValidationStrict {
				return errors.New("pdfcpu: validateOutlineTree: non-empty outline item dict needs \"Count\" <> 0")
			}
			*count = c
		}
```
`count` is nil hence *c will panic.

**Comment by hhrutter** [comment]
Thanks for discovering this!

**Comment by hhrutter** [comment]
Hi, can you share a file where this actually happens? ..because it shouldn't.
Would be very helpful for debugging and fixing this.
Thank you!

**Comment by makeitraina** [comment]
> Hi, can you share a file where this actually happens? ..because it shouldn't. Would be very helpful for debugging and fixing this. Thank you!

Hi hhrutter, I also experienced this issue. I cant share the file because it has some confidential information. I made a fork with a simple change to add:

```
if count == nil {
   count = new(int)
}
```

Curious if you think this change will suffice here.

**Comment by hhrutter** [comment]
We need an actual PDF in order to get to the root if this.

**Comment by hhrutter** [comment]
This should be fixed with latest commit!
