### ISSUE TITLE
Resize using API not as expect

### ISSUE THREAD

**Issue by mmmcatoo** [pdfcpu/pdfcpu#799]
I have a PDF file with a page size of 100*150 millimeters, and I would like to resize the page size of the PDF using api. So that it can be printed on a paper size of 100*200 millimeters using a label printer.

Which my code like below:
```go

resultFileName := fmt.Sprintf("%s/%s.pdf", resultWd, value)
// Modify as 100*200mm
if err := api.ResizeFile(p, resultFileName, []string{}, &model.Resize{
    Scale: 1,
    Unit:  types.CENTIMETRES,
    PageDim: &types.Dim{
        Width:  10.0,
        Height: 20.0,
    },
    UserDim:       true,
    EnforceOrient: true,
}, nil); err != nil {
    log.Fatalln(err)
}
```
But the result PDF still in 100*150 millimeters. In my go.sum the version show is : `require github.com/pdfcpu/pdfcpu v0.6.0`

**Comment by hhrutter** [comment]
Hello!

Did you try this using the CLI?

**Comment by hhrutter** [comment]
The resize command is resizing the page only, the contents proportions will be preserved and fitted into the resized page.
If you are still having problems, please share a sample file.

Thank you for using pdfcpu 💚

**Comment by hhrutter** [comment]
Closed due to inactivity.
