### ISSUE TITLE
PageCount API Error pdfcpu: validateDestinationArray: arr[1] corrup

### ISSUE THREAD

**Issue by jerem17** [pdfcpu/pdfcpu#805]
### Thank you for submitting a possible bug!

Please ensure the following:

* Your issue is based on the latest commit : v0.6.0
* State your OS and OS version : macOS
* When reporting a problem with a specific PDF input file please avoid stating the organization responsible for the PDFWriter - just refer to the *PDFWriter* 

Hi, I'm getting this error when I try to count the number of pages in a PDF. I can email you the document if you like. 

pdfcpu: validateDestinationArray: arr[1] corrupt

When i use : api.PageCount

**Comment by hhrutter** [comment]
Please do so!
Thank you!

**Comment by jerem17** [comment]
Sent by mail 
Thanks again

**Comment by hhrutter** [comment]
This should be fixed as per latest commit!
