### ISSUE TITLE
Fatal: dict=FreeText entry=DS: unsupported in version 1.4

### ISSUE THREAD

**Issue by xelan** [pdfcpu/pdfcpu#806]
### pdfcpu does not process PDF 1.4 with content unsupported in that version

Please ensure the following:

* Your issue is based on the latest commit

Current stable release 0.6.0, however I search for corresponding issues and had a quick look at the commits since that relase. Do you maybe have nightly builds or so?

* State your OS and OS version

Tested on Windows 10 22H2, Debian 11, Debian 12

* When reporting a problem with a specific PDF input file please avoid stating the organization responsible for the PDFWriter - just refer to the *PDFWriter*

We're using a PDFWriter which creates a PDF version 1.4 and another tool for annotations (comments, text markings). That tool has the problem that it applies those annotations, but does not update the PDF version. When trying the same with Acrobat Reader, the PDF version of the file is automatically changed to 1.6 after saving it.

When I'm manually just changing the version of the header of the "invalid" file to 1.5 without further changes, the validation is ok.

```
C:\Software\pdfcpu_0.6.0_Windows_x86_64>pdfcpu.exe validate -j example-pdf1.4-original.pdf
validating(mode=relaxed) example-pdf1.4-original.pdf ...
validation ok

C:\Software\pdfcpu_0.6.0_Windows_x86_64>pdfcpu.exe validate -j example-pdf1.4-comment.pdf
validating(mode=relaxed) example-pdf1.4-comment.pdf ...
validation error (obj#:39): dict=FreeText entry=DS: unsupported in version 1.4

C:\Software\pdfcpu_0.6.0_Windows_x86_64>pdfcpu.exe validate -j example-pdf1.5-comment-faked-version.pdf
validating(mode=relaxed) example-pdf1.5-comment-faked-version.pdf ...
validation ok
```

Thanks for helping, best regards
Andreas

Example files:
[example-pdf1.4-original.pdf](https://github.com/pdfcpu/pdfcpu/files/14357129/example-pdf1.4-original.pdf)
[example-pdf1.4-comment.pdf](https://github.com/pdfcpu/pdfcpu/files/14357132/example-pdf1.4-comment.pdf)
[example-pdf1.5-comment-faked-version.pdf](https://github.com/pdfcpu/pdfcpu/files/14357136/example-pdf1.5-comment-faked-version.pdf)

**Comment by hhrutter** [comment]
There is no `-j` option for the `validate` command.
Thanks for reporting this.

**Comment by hhrutter** [comment]
This is fixed with latest commit!
