### ISSUE TITLE
It seems like i meet a nil point panic from pdf_api.Decrypt func

### ISSUE THREAD

**Issue by HalyangQ** [pdfcpu/pdfcpu#808]
version: v0.6.0, (lastest code is same with this version)
golang version: go1.18

panic stack:
runtime error: invalid memory address or nil pointer dereference, stack=goroutine 431957 [running]:
runtime/debug.Stack()
	/usr/local/go/src/runtime/debug/stack.go:24 +0x65
code.byted.org/obric/developer_api/biz/handler/bot.checkKnowledgePdfFile.func1()
	/opt/tiger/compile_path/src/code.byted.org/obric/developer_api/biz/handler/bot/upload_file.go:112 +0x5d
panic({0x52b0da0, 0x9bafa10})
	/usr/local/go/src/runtime/panic.go:838 +0x207
github.com/pdfcpu/pdfcpu/pkg/pdfcpu/validate.evalOutlineCount(0xc007f7ab40?, 0x2, 0xc00b87eb90?, 0x7fd925adf280?, 0x0?, 0x7fd955eaa108?)
	/opt/tiger/compile_path/pkg/mod/github.com/pdfcpu/pdfcpu@v0.6.0/pkg/pdfcpu/validate/outlineTree.go:126 +0x50
github.com/pdfcpu/pdfcpu/pkg/pdfcpu/validate.validateOutlineTree(0xc007f7ab40, 0xc00b87eb00, 0xc00b87eb10)
	/opt/tiger/compile_path/pkg/mod/github.com/pdfcpu/pdfcpu@v0.6.0/pkg/pdfcpu/validate/outlineTree.go:198 +0x26e
github.com/pdfcpu/pdfcpu/pkg/pdfcpu/validate.validateOutlineTree(0xc007f7ab40, 0xc00b87e880, 0xc00b87e890)
	/opt/tiger/compile_path/pkg/mod/github.com/pdfcpu/pdfcpu@v0.6.0/pkg/pdfcpu/validate/outlineTree.go:193 +0x23f
github.com/pdfcpu/pdfcpu/pkg/pdfcpu/validate.validateOutlines(0xc007f7ab40, 0x40000c007ec5a68?, 0x0?, 0x8?)
	/opt/tiger/compile_path/pkg/mod/github.com/pdfcpu/pdfcpu@v0.6.0/pkg/pdfcpu/validate/outlineTree.go:290 +0x205
github.com/pdfcpu/pdfcpu/pkg/pdfcpu/validate.validateRootObject(0xc007f7ab40)
	/opt/tiger/compile_path/pkg/mod/github.com/pdfcpu/pdfcpu@v0.6.0/pkg/pdfcpu/validate/xReftable.go:921 +0x38c
github.com/pdfcpu/pdfcpu/pkg/pdfcpu/validate.XRefTable(0xc007f7ab40)
	/opt/tiger/compile_path/pkg/mod/github.com/pdfcpu/pdfcpu@v0.6.0/pkg/pdfcpu/validate/xReftable.go:44 +0xf0
github.com/pdfcpu/pdfcpu/pkg/api.readAndValidate({0x6587330?, 0xc0043a1830?}, 0xc000fafba0, {0xc0043a1830?, 0x7fd9249675e8?, 0x9c4b640?})
	/opt/tiger/compile_path/pkg/mod/github.com/pdfcpu/pdfcpu@v0.6.0/pkg/api/api.go:133 +0xea
github.com/pdfcpu/pdfcpu/pkg/api.ReadValidateAndOptimize({0x6587330?, 0xc0043a1830?}, 0xc000fafba0?, {0x10?, 0x7fd926622950?, 0x9c4b640?})
	/opt/tiger/compile_path/pkg/mod/github.com/pdfcpu/pdfcpu@v0.6.0/pkg/api/api.go:144 +0x2f
github.com/pdfcpu/pdfcpu/pkg/api.Optimize({0x6587330, 0xc0043a1830}, {0x6584b00, 0xc00d880000}, 0xc0000001b6?)
	/opt/tiger/compile_path/pkg/mod/github.com/pdfcpu/pdfcpu@v0.6.0/pkg/api/optimize.go:43 +0xc5
github.com/pdfcpu/pdfcpu/pkg/api.Decrypt({0x6587330?, 0xc0043a1830?}, {0x6584b00?, 0xc00d880000?}, 0x1?)
	/opt/tiger/compile_path/pkg/mod/github.com/pdfcpu/pdfcpu@v0.6.0/pkg/api/crypto.go:102 +0xa9
code.byted.org/obric/developer_api/biz/handler/bot.checkKnowledgePdfFile({0x6592870, 0xc0044de990}, {0xc00fdc6f40, 0x36}, {0xc0247e0000, 0xa0ee82, 0xa0ee82})

![image](https://github.com/pdfcpu/pdfcpu/assets/45139609/006ba09b-fe8e-4efe-a168-44bf5cdde409)

**Comment by hhrutter** [comment]
That's being addressed.
See #798

**Comment by HalyangQ** [comment]
[nil_panic_file.pdf](https://github.com/pdfcpu/pdfcpu/files/14370849/nil_panic_file.pdf)
hope that could help

**Comment by hhrutter** [comment]
This fixed with https://github.com/pdfcpu/pdfcpu/releases/tag/v0.7.0
