### ISSUE TITLE
Suspects unsupported in version 1.4

### ISSUE THREAD

**Issue by dougwettlaufer** [pdfcpu/pdfcpu#813]
We're using this library for merging PDFs we receive from a PDFWriter. Everything has been going well until recently our call to `api.MergeRaw` has started failing with the following:

```go
2024/02/28 12:51:21 dict=markInfoDict entry=Suspects: unsupported in version 1.4
This file could be PDF/A compliant but pdfcpu only supports versions <= PDF V1.7
```

It seems that they're using the wrong version on their PDFs which we're hoping to work with them to correct. Assuming this correction is made we're still left with a number of PDFs in this state so is there anything we can do to make `MergeRaw` work with these files?

Attached is a crash report generated with `pdfcpu validate -v` on macOS 13.5.2 (the errors during merging were originally seen when running in a linux based Docker container but reproduced on the same Mac).

Thanks!

[crash2.log](https://github.com/pdfcpu/pdfcpu/files/14438516/crash2.log)

**Comment by hhrutter** [comment]
Fixed with latest commit!
Thank you for using pdfcpu 💚

**Comment by dougwettlaufer** [comment]
You rock! Thanks for the quick turnaround @hhrutter

**Comment by hhrutter** [comment]
Please consider becoming a pdfcpu sponsor 💚 
This will help gain more visibility as a project moving forward and keep the maintainer motivated!
