### ISSUE TITLE
internal usage of optimization

### ISSUE THREAD

**Issue by vsenko** [pdfcpu/pdfcpu#815]
API functions `ExtractAttachmentsRaw`, `ExtractAttachments` and `ExtractAttachmentsFile` all do `ReadValidateAndOptimize` (https://github.com/pdfcpu/pdfcpu/blob/master/pkg/api/attach.go#L259), but does it makes sense since optimized context gets lost in the end?

Wouldn't it be enough to read and validate?

**Comment by hhrutter** [comment]
This is fixed with latest commit!
