### ISSUE TITLE
Increase resource ID limit while stamping

### ISSUE THREAD

**Issue by vsenko** [pdfcpu/pdfcpu#818]
During stamping operations there is an artificial limit on the highest resource id:
- https://github.com/pdfcpu/pdfcpu/blob/master/pkg/pdfcpu/stamp.go#L1122
- https://github.com/pdfcpu/pdfcpu/blob/master/pkg/pdfcpu/stamp.go#L1136

Is it possible to increase it (up to 100000 for example)?

**Comment by hhrutter** [comment]
This fixed with https://github.com/pdfcpu/pdfcpu/releases/tag/v0.7.0

**Comment by vsenko** [comment]
Cool, thank you!

And thank you for the new release!
