### ISSUE TITLE
Parsing error with literal "endobj"

### ISSUE THREAD

**Issue by cmil** [pdfcpu/pdfcpu#828]
### Thank you for submitting a possible bug!

Please ensure the following:

* Your issue is based on the latest commit: I used the latest binary for v0.7.0
* State your OS and OS version: macOS 13.6
* When reporting a problem with a specific PDF input file please avoid stating the organization responsible for the PDFWriter - just refer to the *PDFWriter*

This PDF input file [test-endobj.pdf](https://github.com/pdfcpu/pdfcpu/files/14562100/test-endobj.pdf) apparently causes a parsing error: 

```
$ ~/Downloads/pdfcpu_0.7.0_Darwin_arm64/pdfcpu info test-endobj.pdf 
dereferenceAndLoad: problem dereferencing object 5: pdfcpu: parse: corrupt string literal, possibly unbalanced parenthesis
```

The input file contains a Title object with the literal string "xxxxendobjxxxxx". If I remove or replace the "endobj" in this title pdfcpu parses the file just fine.

**Comment by hhrutter** [comment]
Thanks for reporting this!

**Comment by hhrutter** [comment]
This is fixed with the latest commit!
