### ISSUE TITLE
Documentation error

### ISSUE THREAD

**Issue by antoniopaolini** [pdfcpu/pdfcpu#830]
Page: https://pdfcpu.io/core/stamp
In the first example there is:
`$ pdfcpu stamp add -mode text "Page %p of %P" -- "scale:1.0 abs, pos:bc, rot:0" in.pdf out.pdf`
The correct version is:
`$ pdfcpu stamp add -mode text -- "Page %p of %P" "scale:1.0 abs, pos:bc, rot:0" in.pdf out.pdf`

**Comment by hhrutter** [comment]
Thx for reporting this!

**Comment by hhrutter** [comment]
Fixed!
