### ISSUE TITLE
Throw errors instead of os.Exit of invalid fonts

### ISSUE THREAD

**Issue by vedantmamgain** [pdfcpu/pdfcpu#833]
I faced an `os.Exit ` when pdfcpu tried to perform pdf operation on a pdf with invalid font with the following log.
`pdfcpu: user font not loaded: Arial`.

I looked in the code an found the following [line](https://github.com/pdfcpu/pdfcpu/blob/5ccea97431825eb3a02ac3e1aa57cf7163a0b503/pkg/font/metrics.go#L280) where we are doing an os.Exit instead of returning an error.

**Comment by hhrutter** [comment]
This is intentional!
Show me your stack trace.

**Comment by vedantmamgain** [comment]
@hhrutter I got `pdfcpu: user font not loaded: Arial` when trying to fill a pdf.

Why is this behaviour of throwing an os.Exit intentional, I'm using the PDFCPU API instead of CLI hence wouldn't we want to throw errors instead.

**Comment by hhrutter** [comment]
I need more info about what you are doing in oder to analyze this.

**Comment by fancycode** [comment]
Even if the API is used in an incompatible way, using `os.Exit` in library code is considered bad practice. Better would be to use `panic(fmt.Sprintf("pdfcpu: user font not loaded: %s", fontName))` here so it could be catched by the application while still aborting a commandline tool.

**Comment by hhrutter** [comment]
This is a judgement call and pdfcpu is still Alpha.
It's more an indication for that you should never ever get into this situation.
Instead of digressing I'd still like to get to the root of this and in order to do so I need more info.

**Comment by vedantmamgain** [comment]
@hhrutter There wasn't any other error before the `os.Exit`.

**Comment by hhrutter** [comment]
I need to see what you are doing in order to follow up.

**Comment by vedantmamgain** [comment]
@hhrutter I'm using the pdfcpu api's fill function on pdfs which are fetched from s3. I got the above os.Exit message when trying to perform fill action on a pdf.

**Comment by hhrutter** [comment]
There should have been a check if the font in question is installed as one of your pdfcpu user fonts prior to os.exiting.
In order to track that down I need to see a full stacktrace please.

**Comment by vedantmamgain** [comment]
@hhrutter Are you talking about checks in pdfcpu or checks that I should implement. I've verified the error log and post downloading the file from s3 the only log that I can see is `pdfcpu: user font not loaded: Arial%`

**Comment by vedantmamgain** [comment]
@hhrutter Verified that this is now fixed
