### ISSUE TITLE
Working with bytes (slices or buffers) instead of files

### ISSUE THREAD

**Issue by dc0d** [pdfcpu/pdfcpu#834]
Are there any plans to add the capability of working with bytes - instead of files - to the API?

More context:
I created a [tiny tool](https://pbtpocket.com/) that converts an 8-page PDF to PocketMod in WebAssembly. Many of the tools I needed (rotating pages, rearranging them, merging them, etc.) that can operate on bytes were already there. The only missing part was `ExtractPages(...)` - _for my use case_.

I also experimented with the idea of working with a "File System" inside WebAssembly (e.g., messing around with the JavaScript file included in Go WebAssembly to make it possible to use IndexedDB or something as the storage), and it turned out to be a far greater challenge than just transforming byte streams in memory.

This issue aims to determine whether there are any plans/interests for this, better support for WebAssembly and whether it is worth pursuing because it is not a small change.

**Comment by hhrutter** [comment]
Many API commands already work with readers. 
Can you be more specific about what you are missing.
Thank you!

**Comment by dc0d** [comment]
[`func ExtractPages(rs io.ReadSeeker, outDir, fileName string, selectedPages []string, conf *model.Configuration) error { ... }`](https://pkg.go.dev/github.com/pdfcpu/pdfcpu@v0.7.0/pkg/api#ExtractPages) is one such example. While it accepts an `io.ReadSeeker` as input, the output goes into a/some file in a directory. 

So, I created a function (a method for some struct) with the signature `ExtractPages(rs io.ReadSeeker, selectedPages []string, conf *pdfxmodel.Configuration) ([]*bytes.Buffer, error)`, which does the same thing. The only difference is the output target.

**Comment by hhrutter** [comment]
Try this in the api package:

`func ExtractImagesRaw(rs io.ReadSeeker, selectedPages []string, conf *model.Configuration) ([]map[int]model.Image, error) `

**Comment by hhrutter** [comment]
Misread your comment - page extraction just writes to files.
Sorry for the confusion!

**Comment by hhrutter** [comment]
This is fixed with the latest commit!

See: api/test/extract_test.go: TestExtractPagesLowLevel

**Comment by dc0d** [comment]
Please excuse me for not following up on this. 
Thank you! 
I'll take a look.
