### ISSUE TITLE
Error Merge: dict=formFieldDict required entry=Subtype missing

### ISSUE THREAD

**Issue by irwaank** [pdfcpu/pdfcpu#838]
[x] Your issue is based on the latest commit
[x] State your OS and OS version: MacOS 13.6.3

Here is my information:

`$ pdfcpu version`
`pdfcpu: v0.7.0 dev`

`$ pdfcpu validate pp.pdf`
`validating(mode=relaxed) pp.pdf ...`
`validation error (obj#:13): dict=formFieldDict required entry=Subtype missing`

`$ pdfcpu merge invoice.pdf ba.pdf pp.pdf`
`writing invoice.pdf...`
`ba.pdf`
`pp.pdf`
`dict=formFieldDict required entry=Subtype missing`

If you need the file (the file contains the PII), I will email you.

Thank you for your help!

**Comment by hhrutter** [comment]
Do your input files pass validation?
`pdfcpu val abc.pdf`

**Comment by irwaank** [comment]
No, here is  the result:
`$ pdfcpu validate pp.pdf`
`validating(mode=relaxed) pp.pdf`
`validation error (obj#:13): dict=formFieldDict required entry=Subtype missing`

And I read your specification in [validate section](https://pdfcpu.io/core/validate)

I get the the pdf file from my client, and I can't instructed them to change the format of their pdf output.

Do you have any another suggestion ?

**Comment by hhrutter** [comment]
send me the file so I can provide a fix

**Comment by hhrutter** [comment]
This should be fixed with the latest commit!
