### ISSUE TITLE
pdfcpu validate xxxx.pdf report error（dict=outlineItemDict entry=C: unsupported in version 1.3）

### ISSUE THREAD

**Issue by liumangtangseng** [pdfcpu/pdfcpu#839]
pdf：framemaker app export pdf

**Comment by liumangtangseng** [comment]
validating(mode=relaxed) test for watermark.pdf ...
 READ: 2024/03/25 18:51:24 Read: begin
 INFO: 2024/03/25 18:51:24 PDF Version 1.5 conforming reader
 READ: 2024/03/25 18:51:24 readXRefTable: begin
 READ: 2024/03/25 18:51:24 scanning for offsetLastXRefSection starting at 4270060
 READ: 2024/03/25 18:51:24 Offset last xrefsection: 116
 READ: 2024/03/25 18:51:24 buildXRefTableStartingAt: begin
 READ: 2024/03/25 18:51:24 headerVersion begin
 READ: 2024/03/25 18:51:24 headerVersion: end, found header version: 1.3
 READ: 2024/03/25 18:51:24 newPositionedReader: positioned to offset: 116
 READ: 2024/03/25 18:51:24 xref line 1: <xref>
 READ: 2024/03/25 18:51:24 tryXRefSection: found xref section
 READ: 2024/03/25 18:51:24 parseXRefSection begin
 READ: 2024/03/25 18:51:24 parseXRefSection: <22341 137>
 READ: 2024/03/25 18:51:24 parseXRefTableSubSection: begin
 READ: 2024/03/25 18:51:24 detected xref subsection, startObj=22341 length=137
 READ: 2024/03/25 18:51:24 parseXRefTableEntry: begin
 READ: 2024/03/25 18:51:24 createXRefTableEntry: Object #22341 is in use at offset=16, generation=0
 READ: 2024/03/25 18:51:24 parseXRefTableEntry: Insert new xr
.................................................
.................................................
.................................................
22474:   offset=   47829 generation=0 types.Dict 
<<
	<Count, -2>
	<Dest, (G11.1021972)>
	<First, (22475 0 R)>
	<Last, (22476 0 R)>
	<Parent, (22363 0 R)>
	<Prev, (22473 0 R)>
	<Title, (? 7 . 2 . 2   S y n c h r o n i z e r s)>
>>
22475:   offset=   47991 generation=0 types.Dict 
<<
	<Dest, (G11.1021976)>
	<Next, (22476 0 R)>
	<Parent, (22474 0 R)>
	<Title, (? 7 . 2 . 2 . 1   D a t a   S y n c h r o n i z e r s)>
>>
22476:   offset=   48127 generation=0 types.Dict 
<<
	<Dest, (G11.1022178)>
	<Parent, (22474 0 R)>
	<Prev, (22475 0 R)>
	<Title, (? 7 . 2 . 2 . 2   R e s e t   S y n c h r o n i z e r s)>
>>
22477:   offset=    3036 generation=0 types.StreamDict 
<<
	<C, 14423>
	<E, 14391>
	<Filter, FlateDecode>
	<I, 14445>
	<L, 14407>
	<Length, 2847>
	<O, 14375>
	<S, 14164>
>>
decoded stream content (length = 0)


Empty free list.

Total pages: 478
No font info available.

No image info available.


STATS: 2024/03/25 18:51:26 Timing:
STATS: 2024/03/25 18:51:26 read                 :  1.150s  68.0%
STATS: 2024/03/25 18:51:26 validate             :  0.540s  32.0%
STATS: 2024/03/25 18:51:26 total processing time:  1.690s

STATS: 2024/03/25 18:51:26 Original:
STATS: 2024/03/25 18:51:26 File size            : 4.1 MB (4270572 bytes)
STATS: 2024/03/25 18:51:26 Total binary data    : 1.8 MB (1895033 bytes) 44.4%
STATS: 2024/03/25 18:51:26 Total other data     : 2.3 MB (2375539 bytes) 55.6%

Fatal: dict=outlineItemDict entry=C: unsupported in version 1.3

github.com/pdfcpu/pdfcpu/pkg/pdfcpu/model.(*XRefTable).ValidateVersion
	/Users/horstrutter/Documents/go/pdfcpu/pkg/pdfcpu/model/xreftable.go:226
github.com/pdfcpu/pdfcpu/pkg/pdfcpu/validate.validateArrayEntry
	/Users/horstrutter/Documents/go/pdfcpu/pkg/pdfcpu/validate/object.go:93
github.com/pdfcpu/pdfcpu/pkg/pdfcpu/validate.validateNumberArrayEntry
	/Users/horstrutter/Documents/go/pdfcpu/pkg/pdfcpu/validate/object.go:898
github.com/pdfcpu/pdfcpu/pkg/pdfcpu/validate.validateOutlineItemDict
	/Users/horstrutter/Documents/go/pdfcpu/pkg/pdfcpu/validate/outlineTree.go:65
github.com/pdfcpu/pdfcpu/pkg/pdfcpu/validate.handleOutlineItemDict
	/Users/horstrutter/Documents/go/pdfcpu/pkg/pdfcpu/validate/outlineTree.go:89
github.com/pdfcpu/pdfcpu/pkg/pdfcpu/validate.validateOutlineTree
	/Users/horstrutter/Documents/go/pdfcpu/pkg/pdfcpu/validate/outlineTree.go:172
github.com/pdfcpu/pdfcpu/pkg/pdfcpu/validate.validateOutlines
	/Users/horstrutter/Documents/go/pdfcpu/pkg/pdfcpu/validate/outlineTree.go:295
github.com/pdfcpu/pdfcpu/pkg/pdfcpu/validate.validateRootObject
	/Users/horstrutter/Documents/go/pdfcpu/pkg/pdfcpu/validate/xReftable.go:936
github.com/pdfcpu/pdfcpu/pkg/pdfcpu/validate.XRefTable
	/Users/horstrutter/Documents/go/pdfcpu/pkg/pdfcpu/validate/xReftable.go:55
github.com/pdfcpu/pdfcpu/pkg/api.ValidateContext
	/Users/horstrutter/Documents/go/pdfcpu/pkg/api/api.go:106
github.com/pdfcpu/pdfcpu/pkg/api.Validate
	/Users/horstrutter/Documents/go/pdfcpu/pkg/api/validate.go:51
github.com/pdfcpu/pdfcpu/pkg/api.ValidateFile
	/Users/horstrutter/Documents/go/pdfcpu/pkg/api/validate.go:91
github.com/pdfcpu/pdfcpu/pkg/api.ValidateFiles
	/Users/horstrutter/Documents/go/pdfcpu/pkg/api/validate.go:110
github.com/pdfcpu/pdfcpu/pkg/cli.Validate
	/Users/horstrutter/Documents/go/pdfcpu/pkg/cli/cli.go:27
github.com/pdfcpu/pdfcpu/pkg/cli.Process
	/Users/horstrutter/Documents/go/pdfcpu/pkg/cli/process.go:35
main.process
	/Users/horstrutter/Documents/go/pdfcpu/cmd/pdfcpu/process.go:150
main.processValidateCommand
	/Users/horstrutter/Documents/go/pdfcpu/cmd/pdfcpu/process.go:207
main.commandMap.process
	/Users/horstrutter/Documents/go/pdfcpu/cmd/pdfcpu/cmd.go:143
main.main
	/Users/horstrutter/Documents/go/pdfcpu/cmd/pdfcpu/main.go:56
runtime.main
	/usr/local/go/src/runtime/proc.go:271
runtime.goexit
	/usr/local/go/src/runtime/asm_amd64.s:1695
validation error (obj#:22359)
github.com/pdfcpu/pdfcpu/pkg/api.Validate
	/Users/horstrutter/Documents/go/pdfcpu/pkg/api/validate.go:56
github.com/pdfcpu/pdfcpu/pkg/api.ValidateFile
	/Users/horstrutter/Documents/go/pdfcpu/pkg/api/validate.go:91
github.com/pdfcpu/pdfcpu/pkg/api.ValidateFiles
	/Users/horstrutter/Documents/go/pdfcpu/pkg/api/validate.go:110
github.com/pdfcpu/pdfcpu/pkg/cli.Validate
	/Users/horstrutter/Documents/go/pdfcpu/pkg/cli/cli.go:27
github.com/pdfcpu/pdfcpu/pkg/cli.Process
	/Users/horstrutter/Documents/go/pdfcpu/pkg/cli/process.go:35
main.process
	/Users/horstrutter/Documents/go/pdfcpu/cmd/pdfcpu/process.go:150
main.processValidateCommand
	/Users/horstrutter/Documents/go/pdfcpu/cmd/pdfcpu/process.go:207
main.commandMap.process
	/Users/horstrutter/Documents/go/pdfcpu/cmd/pdfcpu/cmd.go:143
main.main
	/Users/horstrutter/Documents/go/pdfcpu/cmd/pdfcpu/main.go:56
runtime.main
	/usr/local/go/src/runtime/proc.go:271
runtime.goexit
	/usr/local/go/src/runtime/asm_amd64.s:1695

**Comment by liumangtangseng** [comment]
validating(mode=relaxed) test for watermark.pdf ...
 READ: 2024/03/25 18:51:24 Read: begin
 INFO: 2024/03/25 18:51:24 PDF Version 1.5 conforming reader
 READ: 2024/03/25 18:51:24 readXRefTable: begin
 READ: 2024/03/25 18:51:24 scanning for offsetLastXRefSection starting at 4270060
 READ: 2024/03/25 18:51:24 Offset last xrefsection: 116
 READ: 2024/03/25 18:51:24 buildXRefTableStartingAt: begin
 READ: 2024/03/25 18:51:24 headerVersion begin
 READ: 2024/03/25 18:51:24 headerVersion: end, found header version: 1.3
 READ: 2024/03/25 18:51:24 newPositionedReader: positioned to offset: 116
 READ: 2024/03/25 18:51:24 xref line 1: <xref>
 READ: 2024/03/25 18:51:24 tryXRefSection: found xref section
 READ: 2024/03/25 18:51:24 parseXRefSection begin
 READ: 2024/03/25 18:51:24 parseXRefSection: <22341 137>
 READ: 2024/03/25 18:51:24 parseXRefTableSubSection: begin
 READ: 2024/03/25 18:51:24 detected xref subsection, startObj=22341 length=137
 READ: 2024/03/25 18:51:24 parseXRefTableEntry: begin
 READ: 2024/03/25 18:51:24 createXRefTableEntry: Object #22341 is in use at offset=16, generation=0
 READ: 2024/03/25 18:51:24 parseXRefTableEntry: Insert new xr
.................................................
.................................................
.................................................
22474:   offset=   47829 generation=0 types.Dict 
<<
	<Count, -2>
	<Dest, (G11.1021972)>
	<First, (22475 0 R)>
	<Last, (22476 0 R)>
	<Parent, (22363 0 R)>
	<Prev, (22473 0 R)>
	<Title, (? 7 . 2 . 2   S y n c h r o n i z e r s)>
>>
22475:   offset=   47991 generation=0 types.Dict 
<<
	<Dest, (G11.1021976)>
	<Next, (22476 0 R)>
	<Parent, (22474 0 R)>
	<Title, (? 7 . 2 . 2 . 1   D a t a   S y n c h r o n i z e r s)>
>>
22476:   offset=   48127 generation=0 types.Dict 
<<
	<Dest, (G11.1022178)>
	<Parent, (22474 0 R)>
	<Prev, (22475 0 R)>
	<Title, (? 7 . 2 . 2 . 2   R e s e t   S y n c h r o n i z e r s)>
>>
22477:   offset=    3036 generation=0 types.StreamDict 
<<
	<C, 14423>
	<E, 14391>
	<Filter, FlateDecode>
	<I, 14445>
	<L, 14407>
	<Length, 2847>
	<O, 14375>
	<S, 14164>
>>
decoded stream content (length = 0)


Empty free list.

Total pages: 478
No font info available.

No image info available.


STATS: 2024/03/25 18:51:26 Timing:
STATS: 2024/03/25 18:51:26 read                 :  1.150s  68.0%
STATS: 2024/03/25 18:51:26 validate             :  0.540s  32.0%
STATS: 2024/03/25 18:51:26 total processing time:  1.690s

STATS: 2024/03/25 18:51:26 Original:
STATS: 2024/03/25 18:51:26 File size            : 4.1 MB (4270572 bytes)
STATS: 2024/03/25 18:51:26 Total binary data    : 1.8 MB (1895033 bytes) 44.4%
STATS: 2024/03/25 18:51:26 Total other data     : 2.3 MB (2375539 bytes) 55.6%

Fatal: dict=outlineItemDict entry=C: unsupported in version 1.3

github.com/pdfcpu/pdfcpu/pkg/pdfcpu/model.(*XRefTable).ValidateVersion
	/Users/horstrutter/Documents/go/pdfcpu/pkg/pdfcpu/model/xreftable.go:226
github.com/pdfcpu/pdfcpu/pkg/pdfcpu/validate.validateArrayEntry
	/Users/horstrutter/Documents/go/pdfcpu/pkg/pdfcpu/validate/object.go:93
github.com/pdfcpu/pdfcpu/pkg/pdfcpu/validate.validateNumberArrayEntry
	/Users/horstrutter/Documents/go/pdfcpu/pkg/pdfcpu/validate/object.go:898
github.com/pdfcpu/pdfcpu/pkg/pdfcpu/validate.validateOutlineItemDict
	/Users/horstrutter/Documents/go/pdfcpu/pkg/pdfcpu/validate/outlineTree.go:65
github.com/pdfcpu/pdfcpu/pkg/pdfcpu/validate.handleOutlineItemDict
	/Users/horstrutter/Documents/go/pdfcpu/pkg/pdfcpu/validate/outlineTree.go:89
github.com/pdfcpu/pdfcpu/pkg/pdfcpu/validate.validateOutlineTree
	/Users/horstrutter/Documents/go/pdfcpu/pkg/pdfcpu/validate/outlineTree.go:172
github.com/pdfcpu/pdfcpu/pkg/pdfcpu/validate.validateOutlines
	/Users/horstrutter/Documents/go/pdfcpu/pkg/pdfcpu/validate/outlineTree.go:295
github.com/pdfcpu/pdfcpu/pkg/pdfcpu/validate.validateRootObject
	/Users/horstrutter/Documents/go/pdfcpu/pkg/pdfcpu/validate/xReftable.go:936
github.com/pdfcpu/pdfcpu/pkg/pdfcpu/validate.XRefTable
	/Users/horstrutter/Documents/go/pdfcpu/pkg/pdfcpu/validate/xReftable.go:55
github.com/pdfcpu/pdfcpu/pkg/api.ValidateContext
	/Users/horstrutter/Documents/go/pdfcpu/pkg/api/api.go:106
github.com/pdfcpu/pdfcpu/pkg/api.Validate
	/Users/horstrutter/Documents/go/pdfcpu/pkg/api/validate.go:51
github.com/pdfcpu/pdfcpu/pkg/api.ValidateFile
	/Users/horstrutter/Documents/go/pdfcpu/pkg/api/validate.go:91
github.com/pdfcpu/pdfcpu/pkg/api.ValidateFiles
	/Users/horstrutter/Documents/go/pdfcpu/pkg/api/validate.go:110
github.com/pdfcpu/pdfcpu/pkg/cli.Validate
	/Users/horstrutter/Documents/go/pdfcpu/pkg/cli/cli.go:27
github.com/pdfcpu/pdfcpu/pkg/cli.Process
	/Users/horstrutter/Documents/go/pdfcpu/pkg/cli/process.go:35
main.process
	/Users/horstrutter/Documents/go/pdfcpu/cmd/pdfcpu/process.go:150
main.processValidateCommand
	/Users/horstrutter/Documents/go/pdfcpu/cmd/pdfcpu/process.go:207
main.commandMap.process
	/Users/horstrutter/Documents/go/pdfcpu/cmd/pdfcpu/cmd.go:143
main.main
	/Users/horstrutter/Documents/go/pdfcpu/cmd/pdfcpu/main.go:56
runtime.main
	/usr/local/go/src/runtime/proc.go:271
runtime.goexit
	/usr/local/go/src/runtime/asm_amd64.s:1695
validation error (obj#:22359)
github.com/pdfcpu/pdfcpu/pkg/api.Validate
	/Users/horstrutter/Documents/go/pdfcpu/pkg/api/validate.go:56
github.com/pdfcpu/pdfcpu/pkg/api.ValidateFile
	/Users/horstrutter/Documents/go/pdfcpu/pkg/api/validate.go:91
github.com/pdfcpu/pdfcpu/pkg/api.ValidateFiles
	/Users/horstrutter/Documents/go/pdfcpu/pkg/api/validate.go:110
github.com/pdfcpu/pdfcpu/pkg/cli.Validate
	/Users/horstrutter/Documents/go/pdfcpu/pkg/cli/cli.go:27
github.com/pdfcpu/pdfcpu/pkg/cli.Process
	/Users/horstrutter/Documents/go/pdfcpu/pkg/cli/process.go:35
main.process
	/Users/horstrutter/Documents/go/pdfcpu/cmd/pdfcpu/process.go:150
main.processValidateCommand
	/Users/horstrutter/Documents/go/pdfcpu/cmd/pdfcpu/process.go:207
main.commandMap.process
	/Users/horstrutter/Documents/go/pdfcpu/cmd/pdfcpu/cmd.go:143
main.main
	/Users/horstrutter/Documents/go/pdfcpu/cmd/pdfcpu/main.go:56
runtime.main
	/usr/local/go/src/runtime/proc.go:271
runtime.goexit
	/usr/local/go/src/runtime/asm_amd64.s:1695

**Comment by hhrutter** [comment]
This is fixed with the latest commit!
