### ISSUE TITLE
Fatal: dict=fileSpecDict entry=UF: unsupported in version 1.3

### ISSUE THREAD

**Issue by renard** [pdfcpu/pdfcpu#841]
I tries to reopen #166 because I have similar issue but I cannot.

I am reopening this one because I have the same error with

The file I used is https://www.sia.aviation-civile.gouv.fr/media/store/documents/file/l/f/lf_sup_2023_066_fr.pdf.

```
Fatal: dict=fileSpecDict entry=UF: unsupported in version 1.3
```

I did a change in https://github.com/pdfcpu/pdfcpu/blob/dfaa588ecb32b15b6c4a1cc29b7f76d7b0e71c1b/pkg/pdfcpu/validate/fileSpec.go#L354 to   change the valid version to V13:

```
        sinceVersion = model.V13
```

And it works for me. Let me know if you want me to create a patch for that.

**Comment by hhrutter** [comment]
Thanks for reporting this!

**Comment by hhrutter** [comment]
This is fixed with the latest commit!
