### ISSUE TITLE
 api.PageCount Fails on PDF/A Compliant PDFs

### ISSUE THREAD

**Issue by yyoshiki41** [pdfcpu/pdfcpu#864]
I encountered an issue when using the `api.PageCount` function.
Below is the error message I received.
```
DereferenceStringOrHexLiteral: unsupported in version 1.4
This file could be PDF/A compliant but pdfcpu only supports versions <= PDF V1.7
```

I am looking forward to any guidance or updates on this issue. 

**Environment**:
- pdfcpu version: 0.8.0

Thanks

**Comment by hhrutter** [comment]
You are NOT on the latest release!

**Comment by yyoshiki41** [comment]
Sorry, I have updated to the latest version 0.8.0 of pdfcpu and the issue has been resolved.
Thank you for the support and continuous improvement of the library.
