### ISSUE TITLE
CLI: Add recursive functionality to the validate feature

### ISSUE THREAD

**Issue by charles-halifax** [pdfcpu/pdfcpu#868]
Add processing files in subfolders to the feature validate.

Thank you.

**Comment by hhrutter** [comment]
Good suggestion 👍🏻

**Comment by hhrutter** [comment]
validating "**/*.pdf" was already supported on Linux and MacOS.
Get the latest commit in order to validate dir trees recursively on Win as well.

Try 
```
pdfcpu val -q basedir/**/*.pdf
```
if you are only interested in validation errors.
