### ISSUE TITLE
Panic on image extract

### ISSUE THREAD

**Issue by sanbornm** [pdfcpu/pdfcpu#871]
I'm getting `panic: runtime error: index out of range [45675] with length 45675`

on `pdfcpu/pdfcpu/pkg/pdfcpu/writeImage.go:346`. when trying to extract images from PDF.

Is this potentially an off by one error? Maybe it just needs an length check and if it is out of bounds to use the defaulted `alpha := uint8(255)`?

Linux Arch
6.8.8-arch1-1 #1 SMP PREEMPT_DYNAMIC Sun, 28 Apr 2024 15:59:47 +0000 x86_64 GNU/Linux

Commenting out `alpha = im.softMask[y*im.w+x]` makes my PDF extract images without panic

**Comment by sanbornm** [comment]
I think this  is the same bug as: https://github.com/pdfcpu/pdfcpu/issues/804 sorry for the additional issue.

**Comment by hhrutter** [comment]
Perfect!
Could you share this file in order to get this fixed right way?
🙏🏻

**Comment by sanbornm** [comment]
Sent via email. I hope that's ok.

**Comment by hhrutter** [comment]
The file seems to be corrupt:
```
out pdfcpu val 2024-rs-excise-q1.pdf
validating(mode=relaxed) 2024-rs-excise-q1.pdf ...
Read: xRefTable failed: pdfcpu: corrupted last xref section
```

Neither does it open with Adobe Reader or Mac Preview.

**Comment by hhrutter** [comment]
My point was that the attached file got damaged probably during or on the way to the upload.
The error above is an indication for it - it crashes right at the beginning when trying to load the xreftable.

...unless you can also not open this file with Adobe Reader - then it would be corrupt for sure and needs fixing anyways.

**Comment by hhrutter** [comment]
This is fixed with the latest commit!

**Comment by sanbornm** [comment]
Thank you!!
