### ISSUE TITLE
api: create PDF

### ISSUE THREAD

**Issue by carmel** [pdfcpu/pdfcpu#874]
Since I am using pdfcpu in the form of api calls, the actual business needs to create a pdf file directly from the structure, so is there a ready-made api method?

**Comment by hhrutter** [comment]
Thank you for your contribution.
I need to see how this fits into the overall picture.
May take some time.

**Comment by carmel** [comment]
So, is there a roadmap here about the api refinement program?

**Comment by hhrutter** [comment]
Support for signature handling is the last milestone before pdfcpu goes Beta and a clean cut API will also be part of that.
So this will probably be the last thing taken care of before the Beta Release.

**Comment by carmel** [comment]
Got it. Thanks for the reply.
