### ISSUE TITLE
 Unreasonable execute permission for config.yml

### ISSUE THREAD

**Issue by hartvon** [pdfcpu/pdfcpu#875]
Hi, I notice the `config.yml` file generated by pdfcpu has executable permission, which didn't satisfy certain secure requirement.
I found that the config files of other cli tools do not have executable permissions, why pdfcpu is designed like this?

**Environment**:
* OS version: Linux PC 5.15.146.1-microsoft-standard-WSL2-x86_64
* pdfcpu version: https://github.com/pdfcpu/pdfcpu/releases/download/v0.8.0/pdfcpu_0.8.0_Linux_x86_64.tar.xz

**Steps**:
```bash
$ pdfcpu config
$ ll ~/.config/pdfcpu/config.yml 
-rwxr-xr-x 1 htvon htvon 1489 May 21 16:05 /home/htvon/.config/pdfcpu/config.yml*
```

**Comment by hhrutter** [comment]
I really can't say what the consequences for a yml file are..
All I know is that it has to be writable so an admin can mess with the configuration.
In general pdfcpu does not worry about permissions of the executgable and the configuration files  going along with it.
Do whatever you need and what you think it's appropriate.
Have fun with pdfcpu 💚
