### ISSUE TITLE
Decrypt a file without the knowledge of the owner password

### ISSUE THREAD

**Issue by readonly24** [pdfcpu/pdfcpu#876]
Hello,

I have problems understanding why I don't need the owner password to decrypt a file.

The [documantation](https://pdfcpu.io/encrypt/decryptPDF.html ) says: Decrypt a file that has only the owner password set. This will also reset all permissions, providing full access. **You don’t need to provide any password**

What is the sense of encrypting with opw when you just can decrypt without the knowledge of the owner password?

```
C:\Tmp\p>pdfcpu perm list b-org.pdf 
b-org.pdf: 
Full access

C:\Tmp\p>pdfcpu encrypt -opw TopSecret b-org.pdf b-enc.pdf 
writing b-enc.pdf...
using AES-256

C:\Tmp\p>pdfcpu perm set -perm print -opw TopSecret b-enc.pdf 
writing b-enc.pdf...

C:\Tmp\p>pdfcpu perm list b-enc.pdf 
b-enc.pdf:
permission bits: 100000000100 (x804)
Bit  3: true (print(rev2), print quality(rev>=3))
Bit  4: false (modify other than controlled by bits 6,9,11)
Bit  5: false (extract(rev2), extract other than controlled by bit 10(rev>=3))
Bit  6: false (add or modify annotations)
Bit  9: false (fill in form fields(rev>=3)
Bit 10: false (extract(rev>=3))
Bit 11: false (modify(rev>=3))
Bit 12: true (print high-level(rev>=3))

C:\Tmp\p>pdfcpu decrypt b-enc.pdf b-dec.pdf 
writing b-dec.pdf...

C:\Tmp\p>pdfcpu perm list b-dec.pdf 
b-dec.pdf:
Full access
```

**Comment by hhrutter** [comment]
The owner password controls the permissions.
As long as there is no user password set, pdfcpu is able to read the file.
This means it can process the file in any way it wants the only restriction being imposed by set permissions.

pdfcpu's philosophy is it will open whatever it can and thereby not misleading users in believing they are safe by just setting an owner passeword.

The recommendation is to always use both user and owner passwords!

**Comment by readonly24** [comment]
Thanks for clarification. I thought the opw would actually encrypt the file.
