### ISSUE TITLE
validateOutlines seems to have an calculation issue

### ISSUE THREAD

**Issue by tobwen** [pdfcpu/pdfcpu#878]
### summary
`validate --mode strict` seems to have an issue with calculating the amount of outlines. I'm able to reproduce this on several files. Sometimes _pdfcpu_ expects less outlines than actually available in the file, sometimes other errors appear.

### test file(s) and bugs
This file has 30 booksmarks, The even bookmarks of the first level are opened, the odd ones are collapsed.
[outline-test-1.pdf](https://github.com/pdfcpu/pdfcpu/files/15450965/outline-test-1.pdf)

![image](https://github.com/pdfcpu/pdfcpu/assets/1864057/c4602909-5301-478d-ad51-27174eb635ee)

```
$ pdfcpu validate --mode=strict outline-test-1.pdf
validating(mode=strict) outline-test-1.pdf ...
validation error (obj#:30) (try -mode=relaxed): pdfcpu: validateOutlines: corrupted, root "Count" = 30, expected to be 20
```  

### additional information
I know that working with outlines is quite annoying, as there can be positive and negative outlines below the root element (depending on whether they are expanded or not).

Sometimes I'm also getting issues like this on other files:
```
validating(mode=strict) outline-test-2.pdf ...
validation error (obj#:30) (try -mode=relaxed): pdfcpu: validateOutlines: corrupted, root "Count" shall be omitted if there are no open outline items
```
and I've also seen this:
```
validating(mode=strict) outline-test-3.pdf ...
validation error (obj#:205) (try -mode=relaxed): pdfcpu: validateOutlines: corrupted, root "Count" can't be negativ
```

### requested information
* tested on commit: 34062739335c4a109b5d4df26f546668c920b785
* OS: _Debian Bookworm_, AMD64

**Comment by hhrutter** [comment]
Who is the PDF writer of this file?
I see a lot of PDFWriters that do not respect the PDF specification of `Outlines`.
In general I recommend using relaxed validation to get around this.
I will take a look at your file.

**Comment by tobwen** [comment]
> Who is the PDF writer of this file?

It is a commercial software with which we have a support contract. I don't want to publicly discredit/bash this company.

> I see a lot of PDFWriters that do not respect the PDF specification of `Outlines`. 

It has promised to look into the case closely.

> In general I recommend using relaxed validation to get around this.

That's exactly what I don't want. I want a strict check in which such errors are displayed 😊 But you've given me an idea.

> I will take a look at your file.

Thank you for pdfcpu and your support 💚

**Comment by hhrutter** [comment]
Hard to believe a commercial PDFWriter does not create an Info dict:
```
i878.pdf:
              Source: i878.pdf
         PDF version: 1.5
          Page count: 10
          Page sizes: 595.23 x 841.78 points
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
               Title:
              Author:
             Subject:
        PDF Producer:
     Content creator:
       Creation date:
   Modification date:
           Page mode: UseOutlines
        Viewer Prefs: HideToolbar = false
                      HideMenubar = false
                      HideWindowUI = false
                      FitWindow = false
                      CenterWindow = false
                      DisplayDocTitle = true
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
              Tagged: Yes
              Hybrid: No
          Linearized: No
  Using XRef streams: No
Using object streams: No
         Watermarked: No
          Thumbnails: No
                Form: No
            Outlines: Yes
               Names: No
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
           Encrypted: No
         Permissions: Full access
```

**Comment by tobwen** [comment]
As already mentioned, I do NOT wish to expose the provider and have removed the corresponding reference. It's a shame that you're bothered with such trivialities.

If you are not interested in the bug report, feel free to close it.

**Comment by hhrutter** [comment]
Hello!

If you are saying you removed the info dict then that means you have manipulated the PDF somehow.
Your motivation for doing so I am having a hard time to comprehend.

All I can say is that I have been digging into PDFs causing problems by commercial vendors all the time for pdfcpu users.
I am NOT saying this is the case here, but what's the problem being exposed as a vendor with a potential bug in a product?  Even more likely it's a pdfcpu bug and well I wouldn't  be ashamed for that.
As a vendor I'd be proud about my project - bugs happen all the time - the very reason for product updates.

As far as the triviality of manipulating the PDF file before asking me to spend time on it I am reluctant. 
You have to understand that different people mean different things when they say they manipulated a PDF.
If I do not know the history of a file, then that's not really something I want to spend my time on.

I have around 70 open issues and I am really busy getting this project ready for Beta.
I am doing all of this in my spare time at night with a full time job going along and
I hope I can ask users for respecting my constraints and not taking anything for granted.

Thank you!

**Comment by tobwen** [comment]
I really don't know what the problem is. I have provided a test case that identifies a possible bug in your software.

If I remove the PDF-Producer for contractual reasons and to avoid slander, this has no effect on the bookmarks/outlines. You should actually be aware of this. If it were a problem, the validator would have to display this ;)

I think it's great that you are developing the software on your own and I have also supported similar projects with my time (e.g. reporting issues or feature requests) or financially. If it's not financially viable for you, you'll just have to run a dual licence with a commercial model.

I'm closing the bug here now so you have more time for the others.

**Comment by hhrutter** [comment]
The validation error: `Fatal: pdfcpu: validateOutlines: corrupted, root "Count" = 30, expected to be 20` is correct.

<img width="822" alt="Screenshot 2024-06-01 at 12 30 47" src="https://github.com/pdfcpu/pdfcpu/assets/11322155/0dc05db0-0417-406e-a311-c8e02d268eb4">

Even Adobe Reader correctly shows all 20 visible outline items:

<img width="365" alt="Screenshot 2024-06-01 at 12 28 38" src="https://github.com/pdfcpu/pdfcpu/assets/11322155/f41a0a71-340b-4be9-813d-c325788f9c19">
