### ISSUE TITLE
validation: partial validation

### ISSUE THREAD

**Issue by tobwen** [pdfcpu/pdfcpu#879]
### feature request
Based on an inspiration in https://github.com/pdfcpu/pdfcpu/issues/878, it would be nice to select particular tests only and not run the whole test suite.

**Comment by hhrutter** [comment]
Sorry, I really don't quite understand what it is that you are requesting..

In any case if you are using eg. VSCode then just click `Run test`:

<img width="867" alt="Screenshot 2024-06-01 at 10 41 49" src="https://github.com/pdfcpu/pdfcpu/assets/11322155/96a16136-7fcc-41b1-b8fc-0b547e02c605">

**Comment by tobwen** [comment]
I'm sorry for being unclear. I mean the command `validate`. 

It would be nice to enable or disable particular tests, either directly on the CLI or using a JSON file, like this:
``` sh
pdfcpu validate -m(ode) strict -t(ests) tests.json
```

with tests.json:
``` json
{
    "validateRootVersion": false,
    "validateExtensions": true,
    "validatePageLabels": true,
    "validateNames": true,
    "validateNamedDestinations": true,
    "validateViewerPreferences": true,
    "validatePageLayout": true,
    "validatePageMode": true,
    "validateOutlines": false,
    "validateThreads": true,
    "validateOpenAction": true,
    "validateRootAdditionalActions": true,
    "validateURI": false,
    "validateForm": true,
    "validateRootMetadata": true,
    "validateStructTree": true,
    "validateMarkInfo": true,
    "validateLang": true,
    "validateSpiderInfo": true,
    "validateOutputIntents": true,
    "validateRootPieceInfo": true,
    "validateOCProperties": true,
    "validatePermissions": true,
    "validateLegal": false,
    "validateRequirements": false,
    "validateCollection": false,
    "validateNeedsRendering": false
}
```

**Comment by hhrutter** [comment]
Validation either passes or it does not.
If validation fails pdfcpu aborts (the validation) and exits with a corresponding warning.

**Comment by tobwen** [comment]
Unfortunately, `validate` terminates at the first error. If you want to debug a specific error in a PDF (which might occure after the first error), you would have liked to perform the check more precisely.

But since you are obviously not convinced by this feature request, I prefer to close it.
