### ISSUE TITLE
pdfcpu: decodeString: dict=annotDict entry=Contents invalid type types.Integer

### ISSUE THREAD

**Issue by sundonghui** [pdfcpu/pdfcpu#886]
My issue pertains to the latest commit, version v0.8.0, where while working on a Mac with an M2 chip and utilizing the api.MergeCreateFile function, I encountered a bug with the error message stating: "pdfcpu: decodeString: dict=annotDict entry=Contents invalid type types.Integer".

**Comment by hhrutter** [comment]
Thanks for reporting this!

**Comment by hhrutter** [comment]
This is not a bug, this is a correctly identified validation error.

The PDF spec defines `Contents` to be of type string:

<img width="904" alt="Screenshot 2024-06-08 at 00 25 28" src="https://github.com/pdfcpu/pdfcpu/assets/11322155/02e02160-7aee-4371-b607-a8022cbf6b7e">

Always ensure your PDF inpuf file validates: `pdfcpu val input.pdf`

**Comment by hhrutter** [comment]
The latest commit repairs this situation in relaxed validation mode.
Please report back if your issue persists.
