### ISSUE TITLE
why xRefTable.PageCount is zero 0？？？

### ISSUE THREAD

**Issue by icetech233** [pdfcpu/pdfcpu#892]
why xRefTable.PageCount is zero 0？？？

**Comment by hhrutter** [comment]
Hello!

`A4` ist just some reasonable default value for the root `mediaBox`  that you need to supply in this situation.

**Comment by hhrutter** [comment]
Can you please update the issue header?
This does not make sense.

Please create meaningful issue headers when creating one.
Thank you!
