### ISSUE TITLE
Add properties, in some files, after stamp generates error 131 in Acrobat and blank file in Firefox

### ISSUE THREAD

**Issue by remenor** [pdfcpu/pdfcpu#896]
In certain files when adding properties ( Title, Subject, Author) after stamp, error 131 is produced in Acrobat and blank file in Firefox. Pdfcpu does not indicate errors
It seems related to the PDF version: if the file is converted to version 1.4 (GhostScript) becomes readable in all programs (but "watermark flag" as such is lost). Visually are identical files.
Do operations in the reverse order (1st properties; 2nd stamp) produces correct files.
I can't attach the PDF since you have data from a state institution.

mutool info output:
```
pruebaa_ARG.pdf:
warning: cannot seek backwards
warning: ... repeated 77 times...
warning: seek failed
error: unknown token in object stream
warning: cannot load object (2 0 R) into cache

PDF-1.7
Info object (1300 0 R):
<</Author(Dir. Prueba)/CreationDate(D:20240612101006-03'00')/ModDate(D:20240612101006-03'00')/Producer(pdfcpu v0.8.0 dev)>>
Pages: 0

warning: cannot seek backwards
warning: ... repeated 77 times...
warning: seek failed
error: unknown token in object stream
warning: cannot load object (2 0 R) into cache
Retrieving info from pages 1-1...
warning: cannot seek backwards
warning: ... repeated 77 times...
warning: seek failed
error: unknown token in object stream
warning: cannot load object (2 0 R) into cache
error: malformed page tree

```
pdftk output:
```
Error: Invalid PDF: trailer not found.
Error: Failed to open input PDF file: 
   pruebaa_ARG.pdf
Done.  Input errors, so no output created.
```
22.04.1-Ubuntu
pdfcpu: v0.8.0 dev
commit: 576f15e (2024-04-24T22:27:04Z)
base  : go1.22.0

Sorry for my english

**Comment by hhrutter** [comment]
Please check if pdfcpu is able to validate your file: `pdfcpu validate test.pdf`

**Comment by remenor** [comment]
`pdfcpu validate prueba_ARG.pdf 
validating(mode=relaxed) prueba_ARG.pdf ...
validation ok
`

**Comment by hhrutter** [comment]
Please describe your pdfcpu processing steps as detailed as you can.

**Comment by remenor** [comment]
Finally, I sent the two files to your email. Please do not make them public

**Comment by hhrutter** [comment]
Please describe your stamping operation.
How exactly did you stamp your file?
Via the pdfcpu CLI or API?
Once or repeatedly?

Like I said, it will be easier for me to help you if you can send me your
input file so I can reproduce your processing step(s) and provide a fix.

Regards,
Horst

does every page have a different stamp?

**Comment by remenor** [comment]
> Adding properties after stamping a file results in a damaged output file but not the other way around?

Yes. But not in all cases

> Are you using the CLI or the API?

CLI

> If you are using the CLI please describe the 2 processing steps.

I use it within a Bash script, but I also tried it step by step manually, with identical results.

1. In the "erroneous" case, an X file is stamped and renamed it. Then, to this 2nd file the properties are added
2. In the "correct" case, the properties are added to the X file and then stamped and the file is renamed

> It may be critical that the 2 processing steps are separate.

The processes are carried out individually and sequentially

**Comment by hhrutter** [comment]
Until I have time to take a closer look at this again, please get the latest commit and retry.
There were some important changes regarding property and keyword handling, maybe that resolves your issue..

**Comment by hhrutter** [comment]
I cannot reproduce this, so this should work with the latest commit.

**Comment by hhrutter** [comment]
Closed due to inactivity.
