### ISSUE TITLE
Optimization failure for merged PDFs containing ObjectStreamDict objects

### ISSUE THREAD

**Issue by xelan** [pdfcpu/pdfcpu#897]
Please ensure the following:

* Your issue is based on the latest commit

✅ Tested with a build based on the current master

* State your OS and OS version

✅ Debian 12

* When reporting a problem with a specific PDF input file please avoid stating the organization responsible for the PDFWriter - just refer to the *PDFWriter*

The used *PDFWriter* generates PDF files which apparently contain object streams of the type ObjectStreamDict

for example (output excerpt of `pdfcpu validate -vv 3.pdf`)
```
object stream count:100 size of objectarray:100
  585:   offset=  237340 generation=0 types.ObjectStreamDict 
<<
        <Filter, FlateDecode>
        <First, 999>
        <Length, 9411>
        <N, 100>
        <Type, ObjStm>
>>
```

When this PDF is merged with other PDFs, sometimes the resulting PDF cannot be optimized, any operation which performs optimization (such as `pdfcpu bookmark import` or of course `pdfcpu optimize`) fails with an error:

```
Fatal: writeIndirectObject: undefined PDF object #988 types.ObjectStreamDict
```

That object number slightly varies even for the same files when the combination of merge and optimize is run multiple times. The issue is unfortunately really hard to reproduce, it only occurs with certain files and in a specific order.

```
user@pc:/tmp/test$ pdfcpu merge out.pdf 1.pdf 2.pdf 3.pdf 4.pdf && pdfcpu optimize out.pdf
writing out.pdf...
1.pdf
2.pdf
3.pdf
4.pdf
optimizing...
writing out.pdf...
optimizing...
writeIndirectObject: undefined PDF object #988 types.ObjectStreamDict

user@pc:/tmp/test$ pdfcpu merge out.pdf 1.pdf 2.pdf 3.pdf 4.pdf && pdfcpu optimize out.pdf
writing out.pdf...
1.pdf
2.pdf
3.pdf
4.pdf
optimizing...
writing out.pdf...
optimizing...
writeIndirectObject: undefined PDF object #989 types.ObjectStreamDict

user@pc:/tmp/test$ pdfcpu merge out.pdf 1.pdf 2.pdf 3.pdf 4.pdf && pdfcpu optimize out.pdf
writing out.pdf...
1.pdf
2.pdf
3.pdf
4.pdf
optimizing...
writing out.pdf...
optimizing...
writeIndirectObject: undefined PDF object #988 types.ObjectStreamDict
```

Stack trace:
```
[...]/FontFile3 617 0 R/FontName/ArialMT/ItalicAngle 0/MaxWidth 2000/StemV 89/Type/FontDescriptor>><</BaseFont/Arial/DescendantFonts[988 1 R]/Encoding/Identity-H/Subtype/Type0/ToUnicode 989 1 R/Type/Font>>>
WRITE: 2024/06/24 14:11:25 writeObject end, obj#725 written to objectStream #996
WRITE: 2024/06/24 14:11:25 addToObjectStream end, obj#:725 gen#:0
WRITE: 2024/06/24 14:11:25 writeDeepObject: begin offset=585777
Arial
WRITE: 2024/06/24 14:11:25 writeDirectObject: end, direct obj - nothing written: offset=585777
Arial
WRITE: 2024/06/24 14:11:25 writeDeepObject: begin offset=585777
[(988 1 R)]
WRITE: 2024/06/24 14:11:25 writeDeepObject: begin offset=585777
(988 1 R)
TRACE: 2024/06/24 14:11:25 FindTableEntry: obj#:988 gen:1 
WRITE: 2024/06/24 14:11:25 writeIndirectObject: object #988 gets writeoffset: 585777
Fatal: writeIndirectObject: undefined PDF object #988 types.ObjectStreamDict

github.com/pdfcpu/pdfcpu/pkg/pdfcpu.writeObjectGeneric
	/root/pdfcpu/pkg/pdfcpu/writeObjects.go:689
github.com/pdfcpu/pdfcpu/pkg/pdfcpu.writeIndirectObject
	/root/pdfcpu/pkg/pdfcpu/writeObjects.go:728
github.com/pdfcpu/pdfcpu/pkg/pdfcpu.writeDeepObject
	/root/pdfcpu/pkg/pdfcpu/writeObjects.go:745
github.com/pdfcpu/pdfcpu/pkg/pdfcpu.writeDirectObject
	/root/pdfcpu/pkg/pdfcpu/writeObjects.go:552
github.com/pdfcpu/pdfcpu/pkg/pdfcpu.writeDeepObject
	/root/pdfcpu/pkg/pdfcpu/writeObjects.go:742
github.com/pdfcpu/pdfcpu/pkg/pdfcpu.writeDeepDict
	/root/pdfcpu/pkg/pdfcpu/writeObjects.go:600
github.com/pdfcpu/pdfcpu/pkg/pdfcpu.writeObjectGeneric
	/root/pdfcpu/pkg/pdfcpu/writeObjects.go:659
github.com/pdfcpu/pdfcpu/pkg/pdfcpu.writeIndirectObject
	/root/pdfcpu/pkg/pdfcpu/writeObjects.go:728
github.com/pdfcpu/pdfcpu/pkg/pdfcpu.writeDeepObject
	/root/pdfcpu/pkg/pdfcpu/writeObjects.go:745
github.com/pdfcpu/pdfcpu/pkg/pdfcpu.writeDirectObject
	/root/pdfcpu/pkg/pdfcpu/writeObjects.go:538
github.com/pdfcpu/pdfcpu/pkg/pdfcpu.writeDeepObject
	/root/pdfcpu/pkg/pdfcpu/writeObjects.go:742
github.com/pdfcpu/pdfcpu/pkg/pdfcpu.writeDirectObject
	/root/pdfcpu/pkg/pdfcpu/writeObjects.go:538
github.com/pdfcpu/pdfcpu/pkg/pdfcpu.writeDeepObject
	/root/pdfcpu/pkg/pdfcpu/writeObjects.go:742
github.com/pdfcpu/pdfcpu/pkg/pdfcpu.writeDeepDict
	/root/pdfcpu/pkg/pdfcpu/writeObjects.go:600
github.com/pdfcpu/pdfcpu/pkg/pdfcpu.writeObjectGeneric
	/root/pdfcpu/pkg/pdfcpu/writeObjects.go:659
github.com/pdfcpu/pdfcpu/pkg/pdfcpu.writeIndirectObject
	/root/pdfcpu/pkg/pdfcpu/writeObjects.go:728
github.com/pdfcpu/pdfcpu/pkg/pdfcpu.writeDeepObject
	/root/pdfcpu/pkg/pdfcpu/writeObjects.go:745
github.com/pdfcpu/pdfcpu/pkg/pdfcpu.writeDeepArray
	/root/pdfcpu/pkg/pdfcpu/writeObjects.go:638
github.com/pdfcpu/pdfcpu/pkg/pdfcpu.writeObjectGeneric
	/root/pdfcpu/pkg/pdfcpu/writeObjects.go:665
github.com/pdfcpu/pdfcpu/pkg/pdfcpu.writeIndirectObject
	/root/pdfcpu/pkg/pdfcpu/writeObjects.go:728
github.com/pdfcpu/pdfcpu/pkg/pdfcpu.writeDeepObject
	/root/pdfcpu/pkg/pdfcpu/writeObjects.go:745
github.com/pdfcpu/pdfcpu/pkg/pdfcpu.writeDeepDict
	/root/pdfcpu/pkg/pdfcpu/writeObjects.go:600
github.com/pdfcpu/pdfcpu/pkg/pdfcpu.writeObjectGeneric
	/root/pdfcpu/pkg/pdfcpu/writeObjects.go:659
github.com/pdfcpu/pdfcpu/pkg/pdfcpu.writeIndirectObject
	/root/pdfcpu/pkg/pdfcpu/writeObjects.go:728
github.com/pdfcpu/pdfcpu/pkg/pdfcpu.writeDeepObject
	/root/pdfcpu/pkg/pdfcpu/writeObjects.go:745
github.com/pdfcpu/pdfcpu/pkg/pdfcpu.writeDirectObject
	/root/pdfcpu/pkg/pdfcpu/writeObjects.go:552
github.com/pdfcpu/pdfcpu/pkg/pdfcpu.writeDeepObject
	/root/pdfcpu/pkg/pdfcpu/writeObjects.go:742
github.com/pdfcpu/pdfcpu/pkg/pdfcpu.writeDeepDict
	/root/pdfcpu/pkg/pdfcpu/writeObjects.go:600
github.com/pdfcpu/pdfcpu/pkg/pdfcpu.writeObjectGeneric
	/root/pdfcpu/pkg/pdfcpu/writeObjects.go:659
github.com/pdfcpu/pdfcpu/pkg/pdfcpu.writeIndirectObject
	/root/pdfcpu/pkg/pdfcpu/writeObjects.go:728
github.com/pdfcpu/pdfcpu/pkg/pdfcpu.writeDeepObject
	/root/pdfcpu/pkg/pdfcpu/writeObjects.go:745
github.com/pdfcpu/pdfcpu/pkg/pdfcpu.writeDirectObject
	/root/pdfcpu/pkg/pdfcpu/writeObjects.go:552
```

Apparently the affected object causing the problem is the embedded Arial Font in this case. Unfortunately I cannot provide an example file where the issue occurs, I don't know how to artificially produce a PDF with the embedded font as ObjectStreamDict.

If I run optimize on the individual files before the merge, the issue does not occur.

```
user@pc:/tmp/test$ pdfcpu optimize 1.pdf 
writing 1.pdf...
optimizing...
user@pc:/tmp/test$ pdfcpu optimize 2.pdf 
writing 2.pdf...
optimizing...
user@pc:/tmp/test$ pdfcpu optimize 3.pdf 
writing 3.pdf...
optimizing...
user@pc:/tmp/test$ pdfcpu optimize 4.pdf 
writing 4.pdf...
optimizing...
user@pc:/tmp/test$ pdfcpu merge out.pdf 1.pdf 2.pdf 3.pdf 4.pdf 
writing out.pdf...
1.pdf
2.pdf
3.pdf
4.pdf
optimizing...
user@pc:/tmp/test$ pdfcpu optimize out.pdf 
writing out.pdf...
optimizing...
```

**Comment by xelan** [comment]
if `writeXRefStream` is set to false in the configuration, the issue does not occur.

**Comment by hhrutter** [comment]
Interesting, I will check.
Using object stream dicts is nothing out of the ordinary.
This does not happen all the time.
Can you provide me with a sample in order to reproduce this?

**Comment by xelan** [comment]
Thank you so much! The seemingly random object number inconsistent between multiple calls is really strange. The problem with test files is that the issue only occurs in certain scenarios. For example if an additional file is merged, one is omitted or the order is changed, it does not appear.

Unfortunately the affected file cannot be distributed, and I could not create a synthetic test file for this issue so far. Can I somehow help you investigating the problem otherwise?

**Comment by hhrutter** [comment]
I need to reproduce in order to debug.

If you can tell me  a step-by-step guide involving one or two small files from the pdfcpu `testdata` dir,
I might be able to track this down.

**Comment by xelan** [comment]
Thanks, I'll try to reproduce it.

**Comment by xelan** [comment]
Hi @hhrutter, unfortunately I haven't been able to create a synthetic test file so far. But I had a look at the code, seems like `writeObjectGeneric` in writeObjects.go somehow gets a `types.ObjectStreamDict` object in this special case, which is not handled in the switch statement and thus throwing an error. If the configuration option `writeXRefStream`is set to false, this code path is not executed so the issue does not occur.

**Comment by xelan** [comment]
Tried to handle the `ObjectStreamDict`case in `writeObjectGeneric`,  but the `writeDeepStreamDict` only supports the `StreamDict` type. Maybe the actual object could be extracted from the `ObjectStreamDict` (seems like streamdict.go has a function for that) so a regular `StreamDict` is afterwards used in this case?

**Comment by xelan** [comment]
Apparently in even rarer cases (for the same files!) a `XRefStreamDict` is attempted to be written:

```
$ for I in $(seq 1 20); do pdfcpu merge out.pdf example-* > /dev/null && pdfcpu optimize out.pdf > /dev/null; done
writeIndirectObject: undefined PDF object #989 types.ObjectStreamDict

writeIndirectObject: undefined PDF object #989 types.ObjectStreamDict

writeIndirectObject: undefined PDF object #988 types.ObjectStreamDict

writeIndirectObject: undefined PDF object #988 types.ObjectStreamDict

writeIndirectObject: undefined PDF object #988 types.ObjectStreamDict

writeIndirectObject: undefined PDF object #989 types.ObjectStreamDict

writeIndirectObject: undefined PDF object #988 types.ObjectStreamDict

writeIndirectObject: undefined PDF object #988 types.ObjectStreamDict

writeIndirectObject: undefined PDF object #939 types.XRefStreamDict

writeIndirectObject: undefined PDF object #989 types.ObjectStreamDict

writeIndirectObject: undefined PDF object #989 types.ObjectStreamDict

writeIndirectObject: undefined PDF object #988 types.ObjectStreamDict

writeIndirectObject: undefined PDF object #988 types.ObjectStreamDict

writeIndirectObject: undefined PDF object #988 types.ObjectStreamDict

writeIndirectObject: undefined PDF object #988 types.ObjectStreamDict

writeIndirectObject: undefined PDF object #989 types.ObjectStreamDict

writeIndirectObject: undefined PDF object #988 types.ObjectStreamDict

writeIndirectObject: undefined PDF object #988 types.ObjectStreamDict

writeIndirectObject: undefined PDF object #989 types.ObjectStreamDict

writeIndirectObject: undefined PDF object #989 types.ObjectStreamDict
```

**Comment by hhrutter** [comment]
`writeXRefStream` uses `ObjectStreamDicts` - that's just how it works and it should be the default these days.
I need to know your detailed pdfcpu processing pipeline that provokes this error.
I any case optimizing the output of the merge command is redundant.

**Comment by nhannh23** [comment]
Hi @hhrutter 
I'm also encountering this issue. I will share you the PDF file via email.
What I did is as below:

#### # Stamp 1 time
I call the command to add a stamp which is an image into the PDF file.
- The input file is the problematic file `raw_ObjectStreamDict.pdf`
- The command produces the file `r1.pdf`
```bash
pdfcpu stamp add -p 1 -m image -- "line.png" "rot:0,scale:0.527 abs,offset:485 -400,pos:tl" raw_ObjectStreamDict.pdf r1.pdf
```

When I try to open the `r1.pdf` file in Adobe, it shows me a pop up and I couldn't view the file.
![Screenshot 2024-10-02 at 14 26 15](https://github.com/user-attachments/assets/3f7c0ce0-6bbe-4ca2-91b2-29b0149527cf)

#### # Repetitive stamps
With the `r1.pdf` file from the above step, I call stamp multiple times.
- For this time, input and output files are the same, `r1.pdf`
```bash
pdfcpu stamp add -p 1 -m image -- "line.png" "rot:0,scale:0.527 abs,offset:485 -400,pos:tl" r1.pdf r1.pdf
```
- When I make the call continuously around 6-7 times, it will fail and I get the error
```
writing r1.pdf...
optimizing...
pages: 1
writeIndirectObject: undefined PDF object #64 types.ObjectStreamDict
```

I hope this helps and thanks for your effort 🙏

**Comment by nhannh23** [comment]
Hi @hhrutter 
Can we have any updates on this issue? 🙏

**Comment by hhrutter** [comment]
@nhannh23 The issue with this file is unrelated to the original posted as #897, so much I can tell you.

A simple optimization also reproduces the Adobe warning: `pdfcpu optimize raw_ObjectStreamDict.pdf out.pdf`

All other PDF Viewers open this file with no apparent problem.

Analysis is ongoing..

**Comment by hhrutter** [comment]
This should be fixed with the latest commit!

**Comment by nhannh23** [comment]
Hi @hhrutter 
I'm sorry for the late response.
Thank you so much for fixing it 🙇

**Comment by xelan** [comment]
I second this, thanks for your great work :+1: :partying_face:
