### ISSUE TITLE
Bookmarks cannot be read using "bookmarks".

### ISSUE THREAD

**Issue by isseissei** [pdfcpu/pdfcpu#899]
### Thank you for submitting a possible bug!

Please ensure the following:

* Your issue is based on the latest commit ✅ yes
* State your OS and OS version ✅windows11 22H2

* When reporting a problem with a specific PDF input file please avoid stating the organization responsible for the PDFWriter - just refer to the *PDFWriter*

When reading pdf bookmarks with the "bookmarks" method, the result will be empty if there is only one bookmark that is not a child level.
To read the bookmarks, I typed the following command in the terminal.
I typed this command and got no response.The bookmark could not be read.
### Steps
```
go install github.com/pdfcpu/pdfcpu/cmd/pdfcpu@latest
pdfcpu bookmarks list ".\testdir\testpdf.pdf"
```
The testpdf is a two-page pdf and there is only one bookmark referencing the second page.

**Comment by isseissei** [comment]
Thanks for repry!

```
$ pdfcpu validate "testpdf.pdf"
validating(mode=relaxed) testpdf.pdf ...
validation ok
$ pdfcpu validate -mode strict "testpdf.pdf"
validating(mode=strict) testpdf.pdf ...
validation ok
```
We tried that command to see if it passed validation and it did in both cases.
Also, I could not find a bookmark using the "bookmarks" function when the file has only one bookmark, regardless of the number of pages.

**Comment by hhrutter** [comment]
Works for me:
```
$ pdfcpu bookmarks list testpdf.pdf
2ページ目
```

Although having only one of several pages bookmarked is a violation of the PDF spec:

12.3.3 Document Outline
A PDF document may contain a document outline that the interactive PDF processor may display on the screen, allowing the user to navigate interactively from one part of the document to another. **The outline consists of a tree-structured hierarchy of outline items (sometimes called bookmarks), which serve as a visual table of contents to display the document’s structure to the user.** 
....

If you have 4 pages but only one of them bookmarked, that does not reflect the document's structure to the user.

**Comment by isseissei** [comment]
Thank you for trying it.
It is strange that the bookmark does not appear with the same command in my environment...Do you have any idea why this happens?

Thank you for the information you provided on bookmark structure violations.
If there is only one bookmark, then the file is in violation of the specification?

**Comment by hhrutter** [comment]
Well yes, that's what the spec says - see above.
Make sure you go get the latest commit!

**Comment by isseissei** [comment]
Thank you for your reply.
I tried the same command in the docker virtual environment to see if it was due to differences in the environment, but it failed to detect the bookmarks in the same way.
Can you please ask them to try the same command?
The file used is the same as last time, "testpdf.pdf".
`docker run -it --rm -v ${YOUR_DIR}:/data golang:latest bash -c "go install [github.com/pdfcpu/pdfcpu/cmd/pdfcpu@latest](http://github.com/pdfcpu/pdfcpu/cmd/pdfcpu@latest) && pdfcpu bookmarks list /data/testpdf.pdf"`

**Comment by isseissei** [comment]
<img width="896" alt="image" src="https://github.com/pdfcpu/pdfcpu/assets/155043491/1f78cdba-b1c1-42f5-9c1b-b9915f5b0c71">
This is the actual screen when I ran it.
Is it possible to get someone to try this in the same way?
I am sorry, but thank you in advance.

**Comment by isseissei** [comment]
Thank you. After reflecting the latest commit, I was able to detect the bookmarks.
Will this commit go into version 0.9.0?
When will 0.9.0 be released?

**Comment by hhrutter** [comment]
Yes and hopefullly over the next weeks.

**Comment by isseissei** [comment]
Thank you. I'll wait for it to be released.
