### ISSUE TITLE
Add option to not output when Dict object is null

### ISSUE THREAD

**Issue by isseissei** [pdfcpu/pdfcpu#900]
## Request
When converting a Dict type object to a string (pdfString in dict.go), it outputs the string as null if the object type is null, but I would like an option not to output it.
When reading a pdf file created by pdfcpu with other libraries, it may not be readable if Outlines is null.
Outlines is not required by the pdf specification, but I would like to have the option for convenience.
An example of a library that generates an error is "[podofo](https://github.com/podofo/podofo)".
## Situations where we want this feature
When I remove bookmarks from a pdf file using the "RemoveBookmarks" function, the Outlines and Names objects become nil. I was able to view the resulting file in acrobat and chrome. However, podofo could not read the file due to the above reasons.

**Comment by hhrutter** [comment]
Hello!

Are you saying that `bookmarks remove` damages your file?

It should only remove any named destinations used in bookmarks.
Please submit a file for  analysis then I can help you!
You can also email me

**Comment by isseissei** [comment]
Thanks for the reply.
I have emailed you the pdf with the problem.
Please check it.

outline is an optional object, but if it contains null, it may not work correctly in some environments.
It seems that when you removebookmark, you may not delete the outline and make it null.

**Comment by isseissei** [comment]
Although null is correct for the pdf specification, it would be nice to have an option to not null it as it may not work correctly with some libraries.

**Comment by hhrutter** [comment]
There is nothing wrong with the file after removing bookmarks/outlines.
`Outlines` were removed of the root dictionary as you can see:

before:
```
 1:   offset=      15 generation=0 types.Dict type=Catalog
<<
	<Names, (8 0 R)>
	<Outlines, (10 0 R)>
	<Pages, (3 0 R)>
	<Type, Catalog>
>>
```

after:
```
 1:   offset=      15 generation=0 types.Dict type=Catalog
<<
	<Names, (8 0 R)>
	<Pages, (3 0 R)>
	<Type, Catalog>
>>
```

Your outputfile after removing bookmarks is PDF spec compliant and is therefore valid.

**Comment by isseissei** [comment]
The outline is displayed as null instead of undefined depending on the environment. If it is undefined, the OUTLINE item does not appear.
![image (3)](https://github.com/pdfcpu/pdfcpu/assets/155043491/43b42b2c-efb3-4db1-8d09-3ed736e6699e)
This is not a problem in the pdf definition, but it may not be usable when using other libraries.

The pdfcpu specification is fine, but it would be nice if there was an optional feature to distinguish between "null" and "undefined" for improved convenience.

**Comment by hhrutter** [comment]
I don't know what tool you are using but it does not make a difference.
`Outline` is optional in the root dict - so deleting it is spec compliant.
In fact many files just don't come with `Outlines`.
And yes - PDF tools interpret this as Null which is also PDF spec compliant.
PDF tools need to implement, respect and adhere to the PDF spec.
