### ISSUE TITLE
dereferenceObject: problem dereferencing stream

### ISSUE THREAD

**Issue by rorycl** [pdfcpu/pdfcpu#907]
Hi @hhrutter -- thanks a lot for this invaluable project.

## Problem

Error on v0.0.8:
```
dereferenceObject: problem dereferencing stream 7:
pdfcpu: loadEncodedStreamContent: missing streamLength
```
File:  [here](https://github.com/rorycl/rm2pdf/blob/master/testfiles/e724bba2-266f-434d-aaf2-935d2b405aee.pdf).

OS: Debian Linux (testing).

## Details

Having just upgraded `pdfcpu` to v0.8.0 (from v0.5.0) on a new branch of my project [rm2pdf](https://github.com/rorycl/rm2pdf) some of my tests using pdfcpu are failing with `dereferenceObject: problem dereferencing stream 7: pdfcpu: loadEncodedStreamContent: missing streamLength`. This seems similar to issue #786, which was caused by an invalid PDF file. Apologies if this is another issue with an invalid PDF.

This may be an invalid file (certainly github won't show it), but `qpdf` and `jhove` from [Open Preservation](https://jhove.openpreservation.org/) give it a thumbs-up. I've put the top of jhove output at the end of this report. I've had a go at re-cleaning the file with pdftk but that hasn't helped either.

If there is another PDF validation tool you recommend running please consider adding that to the bug report template.

```
Jhove (Rel. 1.30.0, 2024-06-03)
 Date: 2024-07-04 12:35:12 BST
 RepresentationInformation: ../testfiles/e724bba2-266f-434d-aaf2-935d2b4
  ReportingModule: PDF-hul, Rel. 1.12.5 (2024-03-05)
  LastModified: 2022-09-12 01:21:22 BST
  Size: 9860
  Format: PDF
  Version: 1.5
  Status: Well-Formed and valid
  SignatureMatches:
   PDF-hul
  MIMEtype: application/pdf
  PDFMetadata:
   Objects: 21
   FreeObjects: 4
   IncrementalUpdates: 0
   DocumentCatalog:
    PageLayout: SinglePage
    PageMode: UseNone
   Info:
    Creator: pdftk-java 3.2.2
    Producer: itext-paulo-155 (itextpdf.sf.net-lowagie.com)
    CreationDate: Fri Sep 09 14:15:25 BST 2022
    ModDate: Fri Sep 09 14:15:25 BST 2022
```

**Comment by rorycl** [comment]
I tried more verification tools and, it turns out, both pdfcpu and jhove fail, but in different ways; pdfcpu with a `dereferencing stream` error and jhove with a `SAXParseException....content not allowed in prolog`.  The results are shown in [results.txt](https://github.com/user-attachments/files/16101193/results.txt).

```
#!/bin/bash

# see https://www.bitsgalore.org/2021/09/06/pdf-processing-and-analysis-with-open-source-tools

function mkline {
	echo "";
	echo "------------------------------------";
	echo "";
}

FILE=../testfiles/e724bba2-266f-434d-aaf2-935d2b405aee.pdf

echo 'validate with pdfcpu'
echo "~/go/bin/pdfcpu validate FILE"
~/go/bin/pdfcpu validate $FILE

mkline

echo 'validating with jhove'
echo "-jar /tmp/jhove-latest.jar -m PDF-hul -i FILE"
java -jar /tmp/jhove-latest.jar -m PDF-hul -i $FILE

mkline

echo 'validating with qpdf'
echo "qpdf --check --verbose FILE"
qpdf --check --verbose $FILE

mkline

echo 'validating with gs'
echo "gs -dNOPAUSE -dBATCH -sDEVICE=nullpage FILE"
gs -dNOPAUSE -dBATCH -sDEVICE=nullpage $FILE

mkline

echo 'validating with mutool'
echo "mutool info FILE"
mutool info $FILE

mkline

echo 'checking with exiftool'
echo "exiftool FILE"
exiftool $FILE

mkline

```

**Comment by hhrutter** [comment]
Thanks, I'll check it out.

**Comment by hhrutter** [comment]
This is fixed with latest commit!

Please consider becoming a [pdfcpu sponsor](https://github.com/sponsors/hhrutter) 💚

**Comment by rorycl** [comment]
I confirm this is fixed for me in github.com/pdfcpu/pdfcpu@6a9df2e.

I'll make a sponsorship contribution. Thanks a lot!
