### ISSUE TITLE
Relaxed validation for pdf 1.3

### ISSUE THREAD

**Issue by septiyanmudhiya502** [pdfcpu/pdfcpu#908]
Hi @hhrutter , is it possible to enable relaxed validation for pdf version 1.3 ? Currently many of my users is using that pdf version, and we got this error
`dict=pagesDict entry=Tabs: unsupported in version 1.3`

Thank you!

### Thank you for submitting a possible bug!

Please ensure the following:

* Your issue is based on the latest commit
* State your OS and OS version
* When reporting a problem with a specific PDF input file please avoid stating the organization responsible for the PDFWriter - just refer to the *PDFWriter*

**Comment by hhrutter** [comment]
We can do that! Already doing it for v1.4.

**Comment by hhrutter** [comment]
This is fixed with the latest commit!

Please consider becoming a [pdfcpu sponsor](https://github.com/sponsors/hhrutter) 💚
