### ISSUE TITLE
Bookmarks get garbled after encryption

### ISSUE THREAD

**Issue by wdscxsj** [pdfcpu/pdfcpu#910]
With pdfcpu v0.8.0 (tested on Windows and Linux), bookmarks that contain CJK characters often get garbled after encryption.

For example, the attached `in.pdf` contains a single bookmark, "质量" ("quality" in English). `out.pdf` is generated with:

```
pdfcpu encrypt -opw myopw in.pdf out.pdf
```

, and the bookmark text becomes "赜⢑케" (unreadable even in Chinese). It doesn't change after decryption.

[in.pdf](https://github.com/user-attachments/files/16116305/in.pdf)
[out.pdf](https://github.com/user-attachments/files/16116306/out.pdf)

**Comment by hhrutter** [comment]
Thanks for reporting this.

**Comment by hhrutter** [comment]
Hello!

Quality = 质量 = 8D 28   91 CF

but your input file contains a string literal containing the following bytes for the bookmarl title:

FE FF 51 85 5B B9 8D 5C 28 91 CF

#FE #FF is the UTF16-BE prefix and #28 is escaped so that's fine.

The 4 bytes "51 85 5B B9" are a mystery to me and also the cause for the corrupt result after encrypting this string.

**Comment by wdscxsj** [comment]
Hi, thanks for the investigation! This happens to be something I can explain.

When this issue was identified, the original bookmark was `内容质量` ("content quality" in English), and the first 2 characters `内容` ("content" in English) were correct in the encrypted PDF. In UTF16-BE, `内容` = `51 85 5B B9`.

When this issue was reported, I decided to remove `内容` to make the problem easier to see. Thanks to the incremental saving of Acrobat, `内容` remained in the submitted `in.pdf`.

Let's start again from a clean empty PDF, add some bookmarks, and save only once. The attached `in1.pdf` contains 3 bookmarks: `内容`, `质量`, and `内容质量`. After encryption:

```
pdfcpu encrypt -opw myopw in1.pdf out.pdf
```

, we can find the latter 2 bookmarks still garbled.

![a](https://github.com/pdfcpu/pdfcpu/assets/863369/2f4223e0-dac7-4222-8737-65c5614a364a)

[in1.pdf](https://github.com/user-attachments/files/16152819/in1.pdf)

**Comment by hhrutter** [comment]
This is fixed with the latest commit!

**Comment by wdscxsj** [comment]
Fix confirmed. Thank you very much!
