### ISSUE TITLE
Inserted blank page doesn't respect dimensions of the document

### ISSUE THREAD

**Issue by jsx97** [pdfcpu/pdfcpu#918]
macOS Sonoma 14.5, Zsh 5.9

I have a PDF files that is 4.85 × 7.84 inches. When I insert a blank page with

```
pdfcpu pages insert -p 2 -m after input.pdf output.pdf
```

the blank page doesn't respect the dimensions of the document and is 8.5 × 11 inches instead.

- Is it a bug?
- or is this behavior by design and should be worked around somehow? I tried 

  ```
  pdfcpu pages insert -p 3 -m after resize -u in 'dim:4.85 7.84' input.pdf output.pdf
  ```

  but this produces an error.

**Comment by hhrutter** [comment]
Sounds like a bug! I take a look!
Thanks for reporting this 💚

**Comment by hhrutter** [comment]
Can you share a file in order to reproduce this?
Any page may have different dimensions.
The dimensions of inserted pages should derive from the active mediabox at the insert locations.

We definitely need a command option for the desired dimensions like what you have tried though.

**Comment by jsx97** [comment]
Here it is, both input and output files:

https://github.com/jsx97/test/blob/main/pdfcpu-test.zip

```
pdfcpu pages insert -p 2 -m after input.pdf output.pdf
```

**Comment by hhrutter** [comment]
```
Your input file specifies a default media box on the root page dict and that's what pdfcpu picksup when inserting new pages.

 4:   offset=   20583 generation=0 types.Dict type=Pages
<<
	<Count, 5>
	<Kids, [(3 0 R) (14 0 R) (17 0 R) (20 0 R) (23 0 R)]>
	<MediaBox, [0 0 612 792]>
	<Type, Pages>
>>
```

**Comment by jsx97** [comment]
> A parameter for defining the page dimension of new pages could be one solution.

Could you show how to specify it? I looked through Page Layout, Page Mode, Pages and Papersized sections at the website, and still not really sure how, or where, or what to do.

**Comment by hhrutter** [comment]
Like I just said, we could add a `dim` parameter to the `pages` command to manage cases like this.
It does not make much sense to use the dimensions of the previous page we already talked about this.

**Comment by hhrutter** [comment]
This should be fixed with the latest commit:

`usage: pdfcpu pages insert [-p(ages) selectedPages] [-m(ode) before|after] [description] inFile [outFile]`

**Comment by jsx97** [comment]
I have pdfcpu installed on macOS, using Homebrew.

`pdfcpu version`:

```
pdfcpu: v0.8.0 dev
commit: ? (?)
base  : go1.22.2
```

Currently `pdfcpu pages insert -p 2 -m after input.pdf output.pdf` still inserts a page of the wrong size. Probably my pdfcpu is not fresh enough?

**Comment by hhrutter** [comment]
Probably. You need to go get the latest commit.
