### ISSUE TITLE
pdfcpu: config dir problem: mkdir /.config: read-only file system

### ISSUE THREAD

**Issue by sayyep** [pdfcpu/pdfcpu#920]
Hi admin pdfcpu

I have installed pdfcpu in golang project and deploy to linux server. K8S environment. But I'm having a problem: pdfcpu: config dir problem: mkdir /.config: read-only file system

How can I fix it?
Thanks

**Comment by hhrutter** [comment]
You should be able to configure your pdfcpu config path properly eg. using the `-c` flag on the CLI.
See also https://pdfcpu.io/getting_started/common_flags

**Comment by sayyep** [comment]
Many thanks. I have resolved this issue. I COPY config folder to container in Dockerfile. It's work

I also tried to use -c flag but maybe the container not apply this config. When I try pdfcpu version. It is still using /.config folder

Many thanks
