### ISSUE TITLE
Error: dict=formFieldDict required entry=Subtype missing

### ISSUE THREAD

**Issue by Jiaget** [pdfcpu/pdfcpu#921]
State your OS and OS version: MacOS 13.6.3

$ pdfcpu version
pdfcpu: v0.8.0 dev

$ pdfcpu validate ./pkg/file_executor/test.pdf
validating(mode=relaxed) ./pkg/file_executor/test.pdf ...
validation error (obj#:296): dict=annotDict required entry=Subtype missing

I will post my pdf to your email with this issue link

**Comment by hhrutter** [comment]
Thank you so much for reporting this 💚

**Comment by hhrutter** [comment]
This is fixed with latest commit!
