### ISSUE TITLE
Reinstate `model.ValidationNone`

### ISSUE THREAD

**Issue by jamierumbelow** [pdfcpu/pdfcpu#922]
As of https://github.com/pdfcpu/pdfcpu/commit/be323230ede519cb324710899196d72f29315de1, `model.ValidationNone` has been removed.

The internals of the library require that validation occurs, since the library's design uses validation to cache and prepare various internal representations of the PDF for parsing.

We are parsing lots of PDFs from a range of different sources, including several places where the PDFs may be generated as invalid.

For instance, one PDF has a version tag of v1.3 (according to `file` and its headers) but uses the `UseOC` page mode, which is only available as of the v1.5 spec. It therefore fails validation, but can be opened in eg preview and is otherwise a valid PDF.

[This has been discussed already](https://github.com/pdfcpu/pdfcpu/issues/708), but I figured I would re-open to request that `ValidationNone` be reinstated. Our current workaround involves capturing these errors and delegating to another PDF library.

**Comment by hhrutter** [comment]
`ValidationNone` is gone for good - too much happening in preparation for subsequent processing steps.
Just post your specific issues and we tackle them one by one.

**Comment by hhrutter** [comment]
Closed due to inactivity
