### ISSUE TITLE
Chinese annotation support?

### ISSUE THREAD

**Issue by Jiaget** [pdfcpu/pdfcpu#924]
I'm not sure is Chinese support in annotation or something wrong with my workflow

**Comment by hhrutter** [comment]
Please be more specific if you could.
CJK support is not trivial and ongoing work.

**Comment by Jiaget** [comment]
It is my code below
```
	err := api.InstallFonts([]string{"./unifont-13.0.03.ttf"})
	if err != nil {
		t.Fatal(err)
	}
	var squareAnn model.AnnotationRenderer = model.NewSquareAnnotation(
		*types.NewRectangle(300, 0, 350, 50),
		"这是批注测试",
		"ID3",
		0,
		1,
		model.BSSolid,
		&color.Blue,
		false,
		0,
		nil,
		0, 0, 0, 0)

	inFile := "./test2.pdf"
	outFile := "./test2-annotations.pdf"
	// Add square annotation.
	if err := api.AddAnnotationsFile(inFile, outFile, nil, squareAnn, nil, false); err != nil {
		t.Fatal(err)
	}
```
and my output pdf's annotation
![image](https://github.com/user-attachments/assets/45543e00-6623-4d07-b9a3-c602b8a2cae7)

**Comment by hhrutter** [comment]
Thanks for reporting this!
I have more than 80 open issues to fix..

**Comment by hhrutter** [comment]
This is fixed with latest commit!
Plus we have support for a couple more annotation types.
