### ISSUE TITLE
Corrupt page content for a pdf

### ISSUE THREAD

**Issue by Priya-9** [pdfcpu/pdfcpu#926]
macOS  Sonama 14.5
For Pdf https://cityofavenal.com/DocumentCenter/View/749/Title-3-Finance
This error is coming 
`couldn't split pdf: pdfcpu: corrupt page content`

**Comment by hhrutter** [comment]
Thanks for reporting this!

**Comment by hhrutter** [comment]
This should be fixed with latest commit!

**Comment by Priya-9** [comment]
Can you please update me, when new code changes will be accessible to me.

**Comment by hhrutter** [comment]
You can always `go get` the latest commit.
There will probably be a maintenance release over the next couple of weeks.
