### ISSUE TITLE
Maintain inter-document links in trimmed files

### ISSUE THREAD

**Issue by wdscxsj** [pdfcpu/pdfcpu#931]
With the attached test.pdf, clicking "Jump" will jump to "Dest". But after a trim operation:

```
pdfcpu trim -p 1-3 test.pdf out.pdf
```

, the link is lost. Is it possible to maintain inter-document links? Thanks!

[test.pdf](https://github.com/user-attachments/files/16602914/test.pdf)

**Comment by hhrutter** [comment]
This is fixed with the latest commit!

Please consider becoming a [pdfcpu sponsor](https://github.com/sponsors/hhrutter) 💚
