### ISSUE TITLE
missing required resource subdict: ColorSpace

### ISSUE THREAD

**Issue by zollybig** [pdfcpu/pdfcpu#932]
[test.zip](https://github.com/user-attachments/files/16651257/test.zip)
win 10
github.com/pdfcpu/pdfcpu v0.8.0

src:
**err := api.CollectFile(pdfToProcess, SplitByFormatFileName(strings.TrimSuffix(pdfToProcess, filepath.Ext(pdfToProcess)), fmtName, &fmtList), getPageListForFormat(&fmtList), nil)**

almost all pages are processed normally but on some pages I got
_pdfcpu: page 2: missing required resource subdict: ColorSpace
PageResourceNames:
Font: C2_0
Pattern:
Properties:
Shading:
XObject: Im0, Fm0
ColorSpace:
ExtGState:_

pdfcpu --vv "1 A2 2 roll 610 mm.pdf" > crash.log gets

_validating(mode=relaxed) 1 A2 2 roll 610 mm.pdf ...
validation ok_

I tried to move pages inside file (it was page 15, now 28), resave file from Adobe Acrobat, save with optimisation, extract pages from file - with same result.
File perfectly visible in Acrobat DC, PDF-XChange, PDF24 reader.

I read issue[ #494]([url]https://github.com/pdfcpu/pdfcpu/issues/494(url)) but I got Error on latest release  0.8.0
Example file has Error is on page 2, page 1 has no problem

Do You have any solution or workaround? Thanks

**Comment by hhrutter** [comment]
Thank you for reporting this!

What do you mean by the following?
`pdfcpu --vv "1 A2 2 roll 610 mm.pdf`

**Comment by zollybig** [comment]
I used pdfcpu utility for check test file "1 A2 2 roll 610 mm.pdf" . I see recomendation to do so somewhere in  discussions.
perhaps this is unnecessary, since I haven't seen any error messages.
I see structure of this file but I'm not smart or experienced enough to find error and solution

**Comment by hhrutter** [comment]
So this should probably be: `pdfcpu validate --vv "1 A2 2 roll 610 mm.pdf"` ?

**Comment by hhrutter** [comment]
Sorry I do not understand.
The file "1 A2 2 roll 610 mm.pdf" is your input or output file?

The file validates fine:
```
$ pdfcpu val "1 A2 2 roll 610 mm.pdf"
validating(mode=relaxed) "1 A2 2 roll 610 mm.pdf" ...
validation ok
```

A detailed explanation of the issue please.

Are you using the CLI ? Then please submit the command.

Are you using the API? Then I need a complete working code snippet.

**Comment by zollybig** [comment]
The file "1 A2 2 roll 610 mm.pdf" is the input file. This is one of the faulty parts from another 164-page file. Initially, I processed files with a large number of pages, up to 250 pages in a file, such errors appeared. I cut out the bad pages to send them to you for testing. I am writing my own pdf processing program using the api. I only used the CLI to test the failed op file based on the advice from the discussion. I will be able to post the source code of the program in the evening, this is my pet project, I do it at home in the evenings. Thank you for your attention to my questions

**Comment by zollybig** [comment]
[https://cloud.mail.ru/public/DNHV/CKH3cEe55](url)
Archive contains: my source code **pdfpagesizes.go** fully functional
**big test pdf 1.pdf** (164 pages, error appears on process page 28)
small test file **1 A2 2 roll 610 mm.pdf** (2 pages, error on process page 2)
name of test file now hardcoded in **var pdfIn** in main()
also file **1report.pdf** contains report of format for each page generated by my own js utils working under Acrobat. 
Now I try to write functional analogue for than js script on Go using pdfcpy api, but stopped on error on collecting pages in **api.CollectFile()**

//-------------------------- ERRON INSIDE THIS FUNCTION
func splitByPageSize(pdfToProcess string, rangesInfo *[]PgRange) error{
    //  подготовим списки диапазонов каждого формата
    sortedFormats := organizeRangesByFormat(rangesInfo) 
    //  обойдем все форматы 
    for fmtName, fmtList := range sortedFormats {
       
        fmt.Printf("%s\n", fmtName)
        fmt.Printf("Pages list: %s \n", getPageListForFormat(&fmtList))
        fmt.Println(getSplitByFormatFileName(strings.TrimSuffix(pdfToProcess, filepath.Ext(pdfToProcess)), 
            fmtName, &fmtList))

        //  ---- ERROR BLOCK -----
        err := **api.CollectFile(pdfToProcess, 
            getSplitByFormatFileName(strings.TrimSuffix(pdfToProcess, filepath.Ext(pdfToProcess)),** 
            fmtName, &fmtList), getPageListForFormat(&fmtList), nil)
        /// ---- END ERROR BLOCK


        fmt.Println(err)
        if err != nil {
            return err
        }
    }
    return nil

**Comment by hhrutter** [comment]
Can you post the stacktrace that you are getting when calling CollectFile?

**Comment by zollybig** [comment]
[https://cloud.mail.ru/public/S18a/u8rAtrXGd](url)
Yesterday I made several mistaken deletions while preparing the sources for debugging. In this archive there is a normally working program + stacktrace, I was able to get it. But unfortunately I do not see the place and the reason for the error
goroutine 1 [running]:
_main.splitByPageSize.func1()
	C:/src/go/pdfpagessizes/pdfpagesizes.go:402 +0x3d
main.splitByPageSize({0xc00000b1e7, 0x5}, 0xc001709e38)
	C:/src/go/pdfpagessizes/pdfpagesizes.go:409 +0x695
main.main()
	C:/src/go/pdfpagessizes/pdfpagesizes.go:487 +0x525_

**Comment by hhrutter** [comment]
This is fixed with the latest commit!

**Comment by zollybig** [comment]
Unfortunely. Bad luck

_go install github.com/pdfcpu/pdfcpu/cmd/pdfcpu@latest
go mod tidy_

**build and run**
> Environment:
>   GOPATH=C:\src\go
> Directory: C:\src\go\pdfpagessizes
> Command: "C:\Program Files\Go\bin\go.exe" run -v C:\src\go\pdfpagessizes\pdfpagesizes.go
> Output:
1  1.pdf
1.pdf
Общее количество страниц в файле (файлах) 164
Досюда дошли A3
Pages list: [1-4 7-7 9-14 16-16 19-26 29-45 49-56 59-62 64-86 88-92 107-118] 
1_A3_89.pdf
'<nil>
Досюда дошли A4
Pages list: [5-6 8-8 46-48 57-58 87-87 93-106 119-164] 
1_A4_69.pdf
'<nil>
Досюда дошли A2
Pages list: [15-15 28-28] 
1_A2_2.pdf
goroutine 1 [running]:
main.splitByPageSize.func1()
	C:/src/go/pdfpagessizes/pdfpagesizes.go:402 +0x3d
main.splitByPageSize({0xc00000b1e7, 0x5}, 0xc00074fe38)
	C:/src/go/pdfpagessizes/pdfpagesizes.go:409 +0x695
main.main()
	C:/src/go/pdfpagessizes/pdfpagesizes.go:487 +0x525
Error in api.CollectFile: pdfcpu: page 28: missing required resource subdict: ColorSpace
PageResourceNames:
Shading: 
XObject: Im0, Fm0
ColorSpace: 
ExtGState: 
Font: C2_0
Pattern: 
Properties: 

> Elapsed: 7.292s
> Result: Success

Would you be so kind as to compile and run my program on your computer? Will it work fine with my test 1.pdf file?
[https://github.com/pdfcpu/pdfcpu/issues/url](url)

**Comment by zollybig** [comment]
Unfotrunaly something goes wrong. Bad luck
_go install github.com/pdfcpu/pdfcpu/cmd/pdfcpu@latest
go mod tidy_
> Environment:
>   GOPATH=C:\src\go
> Directory: C:\src\go\pdfpagessizes
> Command: "C:\Program Files\Go\bin\go.exe" run -v C:\src\go\pdfpagessizes\pdfpagesizes.go
> Output:
command-line-arguments
1  1.pdf
1.pdf
Общее количество страниц в файле (файлах) 164
Досюда дошли A3
Pages list: [1-4 7 9-14 16 19-26 29-45 49-56 59-62 64-86 88-92 107-118] 
1_A3_89.pdf
Досюда дошли A4
Pages list: [5-6 8 46-48 57-58 87 93-106 119-164] 
1_A4_69.pdf
Досюда дошли A2
Pages list: [15 28] 
1_A2_2.pdf
goroutine 1 [running]:
main.splitByPageSize.func1()
	C:/src/go/pdfpagessizes/pdfpagesizes.go:407 +0x3d
main.splitByPageSize({0xc00000b1e7, 0x5}, 0xc000035e38)
	C:/src/go/pdfpagessizes/pdfpagesizes.go:414 +0x695
main.main()
	C:/src/go/pdfpagessizes/pdfpagesizes.go:492 +0x525
Error in api.CollectFile: pdfcpu: page 28: missing required resource subdict: ColorSpace
PageResourceNames:
ExtGState: 
Font: C2_0
Pattern: 
Properties: 
Shading: 
XObject: Im0, Fm0
ColorSpace: 

Would you be so kind as to compile and run [my program](https://cloud.mail.ru/public/S18a/u8rAtrXGd) on your computer? Will it work fine with my test 1.pdf file?

**Comment by zollybig** [comment]
Also this error is present in CLI pdfcpu.
I tried to split 1.pdf and CLI stops on same page 27 (A1)
You can see output and stacktrace
C:\src\go\pdfpagessizes>pdfcpu split -v 1.pdf 1s
splitting 1.pdf to 1s/...
 INFO: 2024/08/25 00:10:48 PDF Version 1.5 conforming reader
 INFO: 2024/08/25 00:10:48 validating
optimizing...
 INFO: 2024/08/25 00:10:48 optimizing fonts & images
writing 1s\1_1.pdf...
writing 1s\1_2.pdf...
writing 1s\1_3.pdf...
writing 1s\1_4.pdf...
writing 1s\1_5.pdf...
writing 1s\1_6.pdf...
writing 1s\1_7.pdf...
writing 1s\1_8.pdf...
writing 1s\1_9.pdf...
writing 1s\1_10.pdf...
writing 1s\1_11.pdf...
writing 1s\1_12.pdf...
writing 1s\1_13.pdf...
writing 1s\1_14.pdf...
writing 1s\1_15.pdf...
writing 1s\1_16.pdf...
writing 1s\1_17.pdf...
writing 1s\1_18.pdf...
writing 1s\1_19.pdf...
writing 1s\1_20.pdf...
writing 1s\1_21.pdf...
writing 1s\1_22.pdf...
writing 1s\1_23.pdf...
writing 1s\1_24.pdf...
writing 1s\1_25.pdf...
writing 1s\1_26.pdf...
Fatal: pdfcpu: page 27: missing required resource subdict: ColorSpace
PageResourceNames:
Shading:
XObject:
ColorSpace:
ExtGState:
Font: C2_0
Pattern:
Properties:

github.com/pdfcpu/pdfcpu/pkg/pdfcpu/model.consolidateResourceSubDict
        C:/src/go/pkg/mod/github.com/pdfcpu/pdfcpu@v0.8.0/pkg/pdfcpu/model/xreftable.go:1794
github.com/pdfcpu/pdfcpu/pkg/pdfcpu/model.consolidateResourceDict
        C:/src/go/pkg/mod/github.com/pdfcpu/pdfcpu@v0.8.0/pkg/pdfcpu/model/xreftable.go:1826
github.com/pdfcpu/pdfcpu/pkg/pdfcpu/model.(*XRefTable).consolidateResourcesWithContent
        C:/src/go/pkg/mod/github.com/pdfcpu/pdfcpu@v0.8.0/pkg/pdfcpu/model/xreftable.go:1856
github.com/pdfcpu/pdfcpu/pkg/pdfcpu/model.(*XRefTable).processPageTreeForPageDict
        C:/src/go/pkg/mod/github.com/pdfcpu/pdfcpu@v0.8.0/pkg/pdfcpu/model/xreftable.go:1885
github.com/pdfcpu/pdfcpu/pkg/pdfcpu/model.(*XRefTable).processPageTreeForPageDict
        C:/src/go/pkg/mod/github.com/pdfcpu/pdfcpu@v0.8.0/pkg/pdfcpu/model/xreftable.go:1920
github.com/pdfcpu/pdfcpu/pkg/pdfcpu/model.(*XRefTable).processPageTreeForPageDict
        C:/src/go/pkg/mod/github.com/pdfcpu/pdfcpu@v0.8.0/pkg/pdfcpu/model/xreftable.go:1909
github.com/pdfcpu/pdfcpu/pkg/pdfcpu/model.(*XRefTable).processPageTreeForPageDict
        C:/src/go/pkg/mod/github.com/pdfcpu/pdfcpu@v0.8.0/pkg/pdfcpu/model/xreftable.go:1909
github.com/pdfcpu/pdfcpu/pkg/pdfcpu/model.(*XRefTable).PageDict
        C:/src/go/pkg/mod/github.com/pdfcpu/pdfcpu@v0.8.0/pkg/pdfcpu/model/xreftable.go:1950
github.com/pdfcpu/pdfcpu/pkg/pdfcpu.addPages
        C:/src/go/pkg/mod/github.com/pdfcpu/pdfcpu@v0.8.0/pkg/pdfcpu/page.go:49
github.com/pdfcpu/pdfcpu/pkg/pdfcpu.AddPages
        C:/src/go/pkg/mod/github.com/pdfcpu/pdfcpu@v0.8.0/pkg/pdfcpu/page.go:117
github.com/pdfcpu/pdfcpu/pkg/pdfcpu.ExtractPages
        C:/src/go/pkg/mod/github.com/pdfcpu/pdfcpu@v0.8.0/pkg/pdfcpu/extract.go:589
github.com/pdfcpu/pdfcpu/pkg/api.pageSpan
        C:/src/go/pkg/mod/github.com/pdfcpu/pdfcpu@v0.8.0/pkg/api/split.go:40
github.com/pdfcpu/pdfcpu/pkg/api.writePageSpan
        C:/src/go/pkg/mod/github.com/pdfcpu/pdfcpu@v0.8.0/pkg/api/split.go:72
github.com/pdfcpu/pdfcpu/pkg/api.writePageSpans
        C:/src/go/pkg/mod/github.com/pdfcpu/pdfcpu@v0.8.0/pkg/api/split.go:151
github.com/pdfcpu/pdfcpu/pkg/api.Split
        C:/src/go/pkg/mod/github.com/pdfcpu/pdfcpu@v0.8.0/pkg/api/split.go:259
github.com/pdfcpu/pdfcpu/pkg/api.SplitFile
        C:/src/go/pkg/mod/github.com/pdfcpu/pdfcpu@v0.8.0/pkg/api/split.go:283
github.com/pdfcpu/pdfcpu/pkg/cli.Split
        C:/src/go/pkg/mod/github.com/pdfcpu/pdfcpu@v0.8.0/pkg/cli/cli.go:67
github.com/pdfcpu/pdfcpu/pkg/cli.Process
        C:/src/go/pkg/mod/github.com/pdfcpu/pdfcpu@v0.8.0/pkg/cli/process.go:35
main.process
        C:/src/go/pkg/mod/github.com/pdfcpu/pdfcpu@v0.8.0/cmd/pdfcpu/process.go:150
main.processSplitCommand
        C:/src/go/pkg/mod/github.com/pdfcpu/pdfcpu@v0.8.0/cmd/pdfcpu/process.go:296
main.commandMap.process
        C:/src/go/pkg/mod/github.com/pdfcpu/pdfcpu@v0.8.0/cmd/pdfcpu/cmd.go:143
main.main
        C:/src/go/pkg/mod/github.com/pdfcpu/pdfcpu@v0.8.0/cmd/pdfcpu/main.go:56
runtime.main
        C:/Program Files/Go/src/runtime/proc.go:271
runtime.goexit
        C:/Program Files/Go/src/runtime/asm_amd64.s:1695

**Comment by GitHubRulesOK** [comment]
@zollybig just an observation in answer to your question that If I compile latest command line pdfcpu and run alongside the exe
```
go.exe run "C:\Users\lez\Downloads\demo\pdfcpu issues\pdfpagesizes.go" 1 1.pdf
```

console output (no errors)

```
1  1.pdf
1.pdf
Общее количество страниц в файле (файлах) 164
Досюда дошли A4
Pages list: [5-6 8-8 46-48 57-58 87-87 93-106 119-164]
1_A4_69.pdf
<nil>
Досюда дошли A2
Pages list: [15-15 28-28]
1_A2_2.pdf
<nil>
Досюда дошли 3364x1191
Pages list: [17-17]
1_3364x1191_1.pdf
<nil>
Досюда дошли 1193x426
Pages list: [18-18]
1_1193x426_1.pdf
<nil>
Досюда дошли A1
Pages list: [27-27 63-63]
1_A1_2.pdf
<nil>
Досюда дошли A3
Pages list: [1-4 7-7 9-14 16-16 19-26 29-45 49-56 59-62 64-86 88-92 107-118]
1_A3_89.pdf
<nil>
goroutine 1 [running]:
main.splitByPageSize.func1()
        C:/Users/lez/Downloads/demo/pdfcpu issues/pdfpagesizes.go:402 +0x5a
main.splitByPageSize({0x1499137, 0x5}, 0x1449f28)
        C:/Users/lez/Downloads/demo/pdfcpu issues/pdfpagesizes.go:419 +0x5f9
main.main()
        C:/Users/lez/Downloads/demo/pdfcpu issues/pdfpagesizes.go:487 +0x5d2
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
goroutine 1 [running]:
main.splitByPageSize.func1()
        C:/Users/lez/Downloads/demo/pdfcpu issues/pdfpagesizes.go:402 +0x5a
main.splitByPageSize({0x1499137, 0x5}, 0x1449f28)
        C:/Users/lez/Downloads/demo/pdfcpu issues/pdfpagesizes.go:419 +0x5f9
main.main()
        C:/Users/lez/Downloads/demo/pdfcpu issues/pdfpagesizes.go:487 +0x5d2
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
goroutine 1 [running]:
main.splitByPageSize.func1()
        C:/Users/lez/Downloads/demo/pdfcpu issues/pdfpagesizes.go:402 +0x5a
main.splitByPageSize({0x1499137, 0x5}, 0x1449f28)
        C:/Users/lez/Downloads/demo/pdfcpu issues/pdfpagesizes.go:419 +0x5f9
main.main()
        C:/Users/lez/Downloads/demo/pdfcpu issues/pdfpagesizes.go:487 +0x5d2
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
goroutine 1 [running]:
main.splitByPageSize.func1()
        C:/Users/lez/Downloads/demo/pdfcpu issues/pdfpagesizes.go:402 +0x5a
main.splitByPageSize({0x1499137, 0x5}, 0x1449f28)
        C:/Users/lez/Downloads/demo/pdfcpu issues/pdfpagesizes.go:419 +0x5f9
main.main()
        C:/Users/lez/Downloads/demo/pdfcpu issues/pdfpagesizes.go:487 +0x5d2
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
goroutine 1 [running]:
main.splitByPageSize.func1()
        C:/Users/lez/Downloads/demo/pdfcpu issues/pdfpagesizes.go:402 +0x5a
main.splitByPageSize({0x1499137, 0x5}, 0x1449f28)
        C:/Users/lez/Downloads/demo/pdfcpu issues/pdfpagesizes.go:419 +0x5f9
main.main()
        C:/Users/lez/Downloads/demo/pdfcpu issues/pdfpagesizes.go:487 +0x5d2
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
goroutine 1 [running]:
main.splitByPageSize.func1()
        C:/Users/lez/Downloads/demo/pdfcpu issues/pdfpagesizes.go:402 +0x5a
main.splitByPageSize({0x1499137, 0x5}, 0x1449f28)
        C:/Users/lez/Downloads/demo/pdfcpu issues/pdfpagesizes.go:419 +0x5f9
main.main()
        C:/Users/lez/Downloads/demo/pdfcpu issues/pdfpagesizes.go:487 +0x5d2
```
6 pdfs (14.8 MB (15,528,917 bytes)
![image](https://github.com/user-attachments/assets/ea7b1892-f134-4d8e-922a-5f44a87cf931)

Is that what you wanted for confirmation ?

**Comment by hhrutter** [comment]
The initial problem within `api.CollectFile` is fixed.
If there is some other issue with one of the core pdfcpu operations, please isolate and file a separate issue.
Unfortunately I don't have the time to debug any other than calling pdfcpu core api calls.

Thank you for using pdfcpu 💚

**Comment by zollybig** [comment]
@GitHubRulesOK Thank You for testing, Thank you for checking, this is how it should work.

@hhrutter Thank You for Your attention and Your pdfcpu.
