### ISSUE TITLE
Inserting images in pdf form fields

### ISSUE THREAD

**Issue by Harshpawar18** [pdfcpu/pdfcpu#937]
The pdfcpu library provides robust functionality for filling PDF form fields using JSON files. Currently, it supports text fields, checkboxes, radio buttons, list boxes, date fields, and combo boxes. However, I am encountering a limitation when attempting to insert images into form fields.

**Comment by hhrutter** [comment]
You opened this issue twice. See #936
Please also close this unless there is still some issue.

**Comment by Harshpawar18** [comment]
Thank you for your response, but I'm still having trouble finding a method or JSON payload format that helps me to insert an image into a PDF form field, and #936 is already closed.

**Comment by Harshpawar18** [comment]
currently i am working on a project where i want to create a go program to fill pdf form fields, i know how to fill text fields but i'm facing problem in inserting images in pdf, can you provide any method or sample code on how to insert image in a pdf or form field.

**Comment by hhrutter** [comment]
There is nothing like an image PDF form field.
pdfcpu implements this though and you can check out the corresponding test:
form_test.go: TestMultiFillFormJSON using person.json
