### ISSUE TITLE
Radio Button Groups. Missmatched options, text render issues

### ISSUE THREAD

**Issue by LNAhri** [pdfcpu/pdfcpu#940]
Ubuntu 22.04.4 LTS
pdfcpu v0.8.1 dev

The Following File: 
[test.pdf](https://github.com/user-attachments/files/16844977/test.pdf)

produces this output when getting all form fields: (./pdfcpu form list test.pdf)
     RadioBGr. │ 1121 │ rbtn_23_Betriebsgroesse                                           │ 0,1,2,3
     Textfield │ 1181 │ txtf_24_Bezeichnung_Maßnahme                                      │ 
     Textfield │ 1179 │ txtf_25_Lehrgangskosten                                           │ 
     RadioBGr. │ 1175 │ rbtn_26_Betriebsvereinbarung                                      │ 0,1
     RadioBGr. │ 1169 │ rbtn_27_Betriebsvereinbarung                                      │ 0,1
━━━━━━━━━━━━━━━┿━━━━━━┿━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┿━━━━━━━━
3    Textfield │ 1081 │ txtf_28_Anzahl_Beschaeftigte                                      │ 
     Textfield │ 1079 │ txtf_29_Berufliche_Kompetenzen                                    │ 
     Textfield │ 1077 │ txtf_30_Erlaeuterung_Aufgaben                                     │ 
     RadioBGr. │ 1073 │ rbtn_31_Massnahmen                                                │ 0,1
     RadioBGr. │ 1067 │ rbtn_32_Dauer_Massnahmen                                          │ 0,1
     RadioBGr. │ 1061 │ rbtn_33_Inhalte_Massnahmen                                        │ 0,1
     RadioBGr. │ 1055 │ rbtn_34_Kostenpauschale                                           │ 0,1
     RadioBGr. │ 1049 │ rbtn_35_Beschaeftigungsverhaeltnisse_sozialversicherungspflichtig │ 0,1
━━━━━━━━━━━━━━━┿━━━━━━┿━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┿━━━━━━━━
4    RadioBGr. │ 878  │ rbtn_36_Massnahme_in_Arbeitszeiten                                │ 0,1
     RadioBGr. │ 854  │ rbtn_39_Kurzarbeitergeld_beantragt                                │ 0,1
     Textfield │ 941  │ txtf_40_Name_Zeile1                                               │ 
...
     Textfield │ 861  │ txtf_38_Zuschuss                                                  │ 
━━━━━━━━━━━━━━━┿━━━━━━┿━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┿━━━━━━━━
5    Textfield │ 786  │ txtf_41_Ort                                                       │ 
     Textfield │ 784  │ txtf_42_Datum                                                     │ 
     Textfield │ 782  │ txtf_43_Name                                                      │ 
     RadioBGr. │ 775  │ chbx_Anlage_Tabelle_1_Z1                                          │ beigef�gt,wird nachgereicht,bereits vorliegend,entfaellt
     RadioBGr. │ 766  │ chbx_Anlage_Tabelle_1_Z2                                          │ beigef�gt,wird nachgereicht,bereits vorliegend,entfaellt
     RadioBGr. │ 757  │ chbx_Anlage_Tabelle_1_Z3                                          │ beigefuegt,wird nachgereicht,bereits vorliegend,entfaellt
     RadioBGr. │ 748  │ chbx_Anlage_Tabelle_1_Z4                                          │ beigefuegt,wird nachgereicht,bereits vorliegend,entfaellt
     RadioBGr. │ 739  │ chbx_Anlage_Tabelle_1_Z5                                          │ beigefuegt,wird nachgereicht,bereits vorliegend,entfaellt
     RadioBGr. │ 730  │ chbx_Anlage_Tabelle_1_Z6                                          │ beigefuegt,wird nachgereicht,bereits vorliegend,entfaellt
     RadioBGr. │ 721  │ chbx_Anlage_Tabelle_1_Z7                                          │ beigefuegt,wird nachgereicht,bereits vorliegend,entfaellt
     Textfield │ 717  │ Sonstige_Anlagen_Zeile_2                                          │ 

First Problem here, field rbtn_26_Betriebsvereinbarung has in a PDF Editor the options "Ja" and "Nein". 
Seems like there being wrongly read?

Also filling the form is somehow a problem. I'm not sure wheter it is the PDF File or just a bug, but what happens when you fill the form now.

used test fields:
mapping := map[string]interface{}{
		"txtf_Tag_Antragstellung":      "test",
		"rbtn_26_Betriebsvereinbarung": "0",
		"rbtn_27_Betriebsvereinbarung": "1",
}

with defautlt config and NeedAppearances = true.
Form Text fields are filled, but when the PDF File is opened with an older PDF Client or Adobe Acrobat Reader the Radio Groups are no longer filled. Also in Firefox ESR 115.14.0esr (pdfjs 3.7.96 it looks scrambled.

with defautlt config and NeedAppearances = false.
every PDF Editor is showing the Radio Groups selection correctly. But the text is scrampled in every PDF Viewer.

I tried at least for a day to find a working solution to use the original file as input without changing it too much, but didn't got far. Seems like this PDF File is kinda special. I also tried to change other settings in pdfcpu but also didn't helped here. 
Thanks.

**Comment by hhrutter** [comment]
Thanks for reporting this I'll check it out!

**Comment by LNAhri** [comment]
I found a way to fix my issue stated in the pull request. I don't know if this is enough for all types of pdf(s).
For me the changes are working in all my needed pdf viewers

**Comment by hhrutter** [comment]
I am going to take it into consideration and let you know.

**Comment by hhrutter** [comment]
This is fixed with the latest commit:

- digest optional Opt entries while executing `form list, export, fill `.
- correct choosing the right font dict for appearance streams

Note: Your file comes with some typos for repeating radio button groups
The fill command will support for radio button value setting either the long option or the corresponding index in the options array.

eg. consider the following output of `form list`:

 RadioBGr. │ 766  │ chbx_Anlage_Tabelle_1_Z2                                          │                              │ beigef�gt,wird nachgereicht,bereits vorliegend,entfaellt
     RadioBGr. │ 757  │ chbx_Anlage_Tabelle_1_Z3                                          │                               │ beigefuegt,wird nachgereicht,bereits vorliegend,entfaellt

if filling fails eg. because of involved special characters (introduced by the original author of the form) you can also set the value of the index of the entry of the option in the options array:

```
 {
     "pages": [5],
     "id": "775",
     "name": "chbx_Anlage_Tabelle_1_Z1",
     "options": [
             "beigef\ufffdgt",
             "wird nachgereicht",
             "bereits vorliegend",
             "entfaellt"
      ],
      "value": "0",
      "locked": false
},
```
