### ISSUE TITLE
Allow FreeText annotations without DA in relaxed mode

### ISSUE THREAD

**Issue by xelan** [pdfcpu/pdfcpu#948]
### Allow FreeText annotations without DA in relaxed mode

Please ensure the following:

* Your issue is based on the latest commit

Tested with pdfcpu 0.8.1

* State your OS and OS version

Debian 12, Windows 10

The PDF files automatically annotated by the Austrian justice document management system contain FreeText annotations which are missing the Default Appearance (DA) entry. Apparently the Default Appearance is [required for FreeText](https://pdf-issues.pdfa.org/32000-2-2020/clause12.html), but missing in those PDFs. Unfortunately we have no control over the PDFs, but must be able to process them.

Here is an artificial example file I created by editing an uncompressed PDF with FreeType entry in a Hex editor:
[example-freetext-no-da-uncompressed.pdf](https://github.com/user-attachments/files/16940599/example-freetext-no-da-uncompressed.pdf)

```
$ pdfcpu info example-freetext-no-da-uncompressed.pdf

repaired: xreftable
dict=FreeText required entry=DA missing
```

The xreftable is probably borked due to the crude editing, but that was the quickest way to create an example file.

Thank you very much, kind regards
Andreas

**Comment by hhrutter** [comment]
I guess we can ignore a missing `DA` entry if there is an `AP` present.

**Comment by xelan** [comment]
That sounds great, upon a first look the affected documents have an AP entry - hope that this will be the case for all of them😅 Thanks!

**Comment by hhrutter** [comment]
This should be fixed with the latest commit!

**Comment by xelan** [comment]
Thank you very much, I've just tested with the latest master `84cdec02`.
