### ISSUE TITLE
PDF Splitting with Overlapping Page Ranges

### ISSUE THREAD

**Issue by elainejykim** [pdfcpu/pdfcpu#949]
**Description:**

I have a use case where I need to split a PDF into sections that overlap with each other. For example, given a 10-page PDF, I'd like the splits to include the following page ranges:

- Pages 1 to 5
- Pages 3 to 7
- Pages 5 to 10

**Proposed Feature:**

It would be helpful to have a function that allows the following inputs:

1. PDF content (e.g., as an io.Reader)
2. A list of page ranges (to specify how the PDF should be split, including overlapping ranges)
3. An output path (where the split PDFs will be saved)

The function would generate and save the PDF splits according to the specified page ranges.

**Example Workflow:**

Input: A 10-page PDF and a list of ranges
Output: Three PDFs corresponding to the given ranges, saved to the specified output path.

What do you think? Thank you!

**Comment by hhrutter** [comment]
Hi there,

What you want to do is a sequence of trimming.
See `pdfcpu help trim`
You can either write a script or using Go api.TrimFile() is a good starting point I guess.

**Comment by elainejykim** [comment]
> Hi there,
> 
> What you want to do is a sequence of trimming. See `pdfcpu help trim` You can either write a script or using Go api.TrimFile() is a good starting point I guess.

A you are so right. Thank you!!
