### ISSUE TITLE
CLI: trim command automatically sorts pages

### ISSUE THREAD

**Issue by diizzyy** [pdfcpu/pdfcpu#950]
Hi,

Not sure if it's intended but if you specifiy pages out of order at least using the trim function automatically sorts them which may not be expected behaviour. It would be nice if there were a switch to select this behaviour.

Thanks for creating an awesome tool!

**Comment by hhrutter** [comment]
This is expected behavior for `trim`.
What you are looking for is `collect`.

**Comment by diizzyy** [comment]
Oh, I see.... Thanks! :)
