### ISSUE TITLE
Request to Add Support for Data Structure in AAPL:AKExtras

### ISSUE THREAD

**Issue by rtkym** [pdfcpu/pdfcpu#955]
Thank you for the excellent tool.

When handwriting on PDFs using an iPad, AAPL:AKExtras is added to the AcroForm. This added AAPL:AKExtras is not a Dictionary, causing an error (dict=annotDict required entry=Subtype missing).

Could you please add support for AAPL:AKExtras that is added when handwriting on an iPad?

![picture](https://github.com/user-attachments/assets/93e492ca-7de9-4699-97a7-7ff0573c3757)

**Comment by 1cergey** [comment]
Hi!
I try check pdf from "https://www.learningcontainer.com/wp-content/uploads/2019/09/sample-pdf-with-images.pdf" and haver error in validateDocInfoDictEntry() func, because  "AAPL:Keywords"

**Comment by rtkym** [comment]
Hi 1cergey
I created a PDF containing fields (AcroForm) using AcrobatPro, and I was able to reproduce the issue by handwriting on it using an iPad.

**Comment by hhrutter** [comment]
Validating out of spec annotation is just a nice to have.
A missing annotation subtype is violating the PDF spec.
It's probably fpr the best to turn off validating of AAPL: entries all together from now on. 

As far as AAPL:Keywords I'd like to to see this, can anybody share a sample file for analysis?

**Comment by petervwyatt** [comment]
`/AAPL:Keywords` is documented here: https://developer.apple.com/documentation/coregraphics/kcgpdfcontextkeywords. And, yes, it goes against the requirement that has existed since Adobe PDF 1.5: "_The value associated with any key not specifically mentioned in Table 10.2 must be a text string._"

I'm yet to find public documentation for other Apple-specific (`/AAPL:xxx`) stuff.

**Comment by rtkym** [comment]
> It's probably for the best to turn off validating of AAPL: entries all together from now on.

I am using `api.MergeAppendFile`. How can I turn off the validation of AAPL: entries?

**Comment by hhrutter** [comment]
As soon as I have a sample I can take a look at this.

**Comment by hhrutter** [comment]
The latest commit deactivates the validation of AAPL:* entries.
CLI validation will report presence of any Apple extensions.
