### ISSUE TITLE
Merged PDF is v1.7 after optimize despite all input PDFs being v1.3

### ISSUE THREAD

**Issue by RoyHP** [pdfcpu/pdfcpu#959]
Currently, pdfcpu will always produce a v1.7 PDF even if all the input files are v1.3. I looked through the docs and existing issues and cannot find a way to set the output version/compatibility mode to v1.3, so that if all the input files being merged are v1.3, pdfcpu produces a v1.3 output. Is this possible?

My apologies if I am missing something here.

pdfcpu: v0.8.1 dev
commit: ? (?)
base  : go1.23.0
macOS 14.6.1

**Comment by hhrutter** [comment]
pdfcpu will always write v1.7 PDFs unless the input file is using v2.0.
The reason for this is that pdfcpu is utilizing v1.7 features.

**Comment by RoyHP** [comment]
Thank you!
