### ISSUE TITLE
User date without seconds are not parsed

### ISSUE THREAD

**Issue by idonthavetimeforthis** [pdfcpu/pdfcpu#962]
* Your issue is based on the latest commit - Yes
* State your OS and OS version - Windows 11

When adding a watermark to a PDF, the error "parsing time "2024-09-18T15:51+02:00" as "2006-01-02T15:04:05-07:00": cannot parse "+02:00" as ":"" was returned.

**Comment by hhrutter** [comment]
I need to know more about this.
Can you share the file?
Who is the PDF creator?

**Comment by idonthavetimeforthis** [comment]
I realized the issue is on v0.8.0 and not on v0.8.1 .
Shall I close the issue ?
I made a private reproductive repo as I not wish the file to be shared.

**Comment by hhrutter** [comment]
Please go get the latest commit and see if the issue persists.
If not - go ahead and close it.

**Comment by idonthavetimeforthis** [comment]
Issue is not reproductible on latest commit [#dc3855a](https://github.com/pdfcpu/pdfcpu/commit/dc38554a2a84e3e3d14978f3df87e417ab772d72)

**Comment by idonthavetimeforthis** [comment]
Issue is not reproductible on latest commit [#dc3855a](https://github.com/pdfcpu/pdfcpu/commit/dc38554a2a84e3e3d14978f3df87e417ab772d72)
