### ISSUE TITLE
Adding parameter to include multiple PDF pages into one image while image extraction

### ISSUE THREAD

**Issue by oatmi** [pdfcpu/pdfcpu#967]
Hi,

Wondering if it’s possible to add a parameter to control how many PDF pages are extracted into one image.

**Comment by hhrutter** [comment]
Sorry I do not understand your question.

Are you referring to the CLI or API?

Image extraction will extract images from page content of your selected pages.


If you have a question please post on the discussion board the next time.
Thank you 💚 for using pdfcpu

**Comment by oatmi** [comment]
Thanks for the reply, and I apologize for not expressing myself clearly earlier.

I’m referring to the API. Currently, the API extracts each page of a PDF into a separate image, so for a 10-page PDF, we get 10 images.

What I’m asking is if it's possiple to add a parameter that allows multiple PDF pages (for example, every 2 pages or N pages) to be combined into a single image during extraction. So, for a 10-page PDF, the final output would be 5 images.

**Comment by hhrutter** [comment]
Image extraction does not convert pages into images!
If you are extracing images you get an image file for each image that is part of the content of a page.

**Comment by oatmi** [comment]
Oh! I get it now... Thanks for your patient reply. I will close this issue.
