### ISSUE TITLE
booklet 8up orientations

### ISSUE THREAD

**Issue by adamgreenhall** [pdfcpu/pdfcpu#968]
Currently booklet making only supports 8up for portrait orientation with long-edge binding. But there are 3 more options! PRs to follow.

**Comment by hhrutter** [comment]
👍🏻 perfect timing. I am preparing the next release.

**Comment by hamdan7m** [comment]
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.
