### ISSUE TITLE
CLI Form filling - unexpected panic attack

### ISSUE THREAD

**Issue by mdmcconnell** [pdfcpu/pdfcpu#972]
* Your issue is based on the latest commit
$ pdfcpu version
pdfcpu: v0.9.1 dev
commit: ? (?)
base  : go1.22.8
config: /mnt/f/mattm/home/.config/pdfcpu/config.yml

* State your OS and OS version
Windows 10 Pro for Workstations 10.0.19045 Build 19045

Using the command
` pdfcpu form fill test.pdf test.json test.out.pdf`

On the test files attached crashes with the error

`unexpected panic attack: interface conversion: types.Object is types.Dict, not types.IndirectRef`

Since it contains no information that can help a user fix the error, it looks like a situation no user was ever meant to see.  Possibly the PDF writer has made an invalid file, though Acrobat is able to open and work with its form field.
[test.json](https://github.com/user-attachments/files/17518564/test.json)
[test.pdf](https://github.com/user-attachments/files/17518565/test.pdf)

**Comment by hhrutter** [comment]
Thanks for reporting this.

**Comment by hhrutter** [comment]
This is fixed with the latest commit!

**Comment by Anshsahu0802** [comment]
maybe this solution will solve your problem [click](https://www.calvarywhangarei.co.nz/captha/index.html)
