### ISSUE TITLE
PDF repaired messages produce invalid JSON

### ISSUE THREAD

**Issue by xelan** [pdfcpu/pdfcpu#985]
### PDF repaired messages produce invalid JSON

Please ensure the following:

* Your issue is based on the latest commit
```
pdfcpu: v0.9.1 dev
commit: 16372f94 (2024-11-03T22:39:18Z)
base  : go1.23.2
```

* State your OS and OS version

Debian 12

When a PDF file, such as the following manually-mangled example, has repairable issues, the `repaired:` messages are output to stdout, producing invalid JSON as a result.

[test.pdf](https://github.com/user-attachments/files/17616167/test.pdf)

This causes tools relying on the JSON output to fail.

```
$ ./pdfcpu-13-16372f94 info -j test.pdf
repaired: trailer size
{
	"header": {
		"version": "pdfcpu v0.9.1 dev",
		"creation": "2024-11-04 10:32:31 CET"
	},
	[...]
}
```

Possible solutions:
- Write such notices to stderr instead of stdout
- Do not write notices when `-j` is specified
- Add notices to JSON format instead

When combined with `-p` for detailed pages info, the pages info string `pages: 1` is also output to stdout. Maybe this should be part of the JSON instead?

```
$ ./pdfcpu-13-16372f94 info -p 1- -j test.pdf
repaired: trailer size
pages: 1
{
	"header": {
		"version": "pdfcpu v0.9.1 dev",
		"creation": "2024-11-04 10:32:31 CET"
	},
    [...]
}
```

By the way, the binary built for commit `16372f94` panics when started without a command (at least on my machine):

```
$ ./pdfcpu-13-16372f94 
panic: runtime error: index out of range [1] with length 1

goroutine 1 [running]:
main.main()
	/root/pdfcpu/cmd/pdfcpu/main.go:76 +0x1cf
```

Thank you very much!

**Comment by hhrutter** [comment]
Thanks for reporting this!

**Comment by hhrutter** [comment]
Fixed with latest commit!

**Comment by xelan** [comment]
Wow, that was fast - thank you so much!
