### ISSUE TITLE
Reporting a list of fonts included in a PDF, in JSON format

### ISSUE THREAD

**Issue by gmile** [pdfcpu/pdfcpu#987]
(as per a request [here](https://github.com/pdfcpu/pdfcpu/discussions/986#discussioncomment-11144159))

It would be beneficial that `pdfcpu` reports a list of fonts used in a PDF file - as JSON output. Doing so would be beneficial for applications, that feed on the output from `pdfcpu`.

Today, running `pdfcpu validate -v in.pdf` returns an output that includes a "Fonts" section like this, for example:

```
...
Fonts:
obj     prefix     Fontname                       Subtype    Encoding             Embedded ResourceIds
#13                Arial-BoldMT                   TrueType   WinAnsiEncoding      true     F2
#71                Arial-BoldMT                   Type0      Identity-H           true     F6
#15                ArialMT                        TrueType   WinAnsiEncoding      true     F3
#28                ArialMT                        Type0      Identity-H           true     F5
#9      BCDEEE     Calibri                        TrueType   WinAnsiEncoding      true     F1
#76     BCDGEE     Century                        Type0      Identity-H           true     F7
#23     BCDFEE     Wingdings-Regular              Type0      Identity-H           true     F4
...
```

Parsing table output above can be tricky, especially in a case when value in any column, for example font name, contains a space.

**Comment by hhrutter** [comment]
This is implemented as of the latest commit!

`pdfcpu info -fonts -json in.pdf`

and there is also:

`pdfcpu info -fonts in.pdf`

**Comment by gmile** [comment]
Fantastic, thanks so much @hhrutter!
