### ISSUE TITLE
stamping problem

### ISSUE THREAD

**Issue by Rae93** [pdfcpu/pdfcpu#989]
OS: macOS Sonoma 14.0

Hi, I tried to watermark a pdf using pdfcpu, but the result pdf can not be opened by Acrobat Reader (but can be opened by all other browsers like Chrome, firefox, etc.). I wonder what is the cause?
The watermark method that I tried to use is drawing some texts over an image.Image, convert them to .png and then apply the png to the all of the pdf pages. 
I attached the original pdf and the generated pdf
[original.pdf](https://github.com/user-attachments/files/17634063/original.pdf)
[pdfcpu watermark.pdf](https://github.com/user-attachments/files/17634064/pdfcpu.watermark.pdf)

The error when opening `pdfcpu watermark.pdf` in adobe 
<img width="251" alt="image" src="https://github.com/user-attachments/assets/2327d399-1856-4986-a51c-5a8026921d6f">

**Comment by hhrutter** [comment]
output of `pdfcpu version` please

**Comment by Rae93** [comment]
```
pdfcpu version
pdfcpu: v0.9.1 dev
commit: ? (?)
base  : go1.23.2
```

**Comment by hhrutter** [comment]
Please show me how you watermark this file.

**Comment by hhrutter** [comment]
I need a simple one page document giving this issue in order to fix this.

**Comment by hhrutter** [comment]
Adobe Reader already issues a warning when I open your inputfile.
Some font dict problem I guess that I will not further pursue:

<img width="440" alt="Screenshot 2024-11-09 at 00 17 43" src="https://github.com/user-attachments/assets/ea24e416-5dad-41f4-82ef-a9ca9ee6db1e">
