### ISSUE TITLE
Panic when Export bookmark

### ISSUE THREAD

**Issue by kitisakOng** [pdfcpu/pdfcpu#991]
Export bookmark can panic here:

![image](https://github.com/user-attachments/assets/dd39abe8-056d-4586-add6-4c32ce8ee4d4)

![image](https://github.com/user-attachments/assets/f004c583-6267-435c-b244-5015cd692646)

my pdfcpu version

![image](https://github.com/user-attachments/assets/83f7da3d-850d-480f-9dbb-26569a8727de)

Testing PDF :
[land.pdf](https://github.com/user-attachments/files/17658268/land.pdf)

**Comment by hhrutter** [comment]
Thanks for reporting this!

**Comment by hhrutter** [comment]
This is fixed with the latest commit!

**Comment by kitisakOng** [comment]
I have a few questions about this. Page in bookmark should start from 1. Am I right?

![image](https://github.com/user-attachments/assets/28a9a2c5-3173-4efd-b977-e7eff2718502)
