### ISSUE TITLE
Cannot export image

### ISSUE THREAD

**Issue by lonevle** [pdfcpu/pdfcpu#994]
### Thank you for submitting a possible bug!

Please ensure the following:

* Your issue is based on the latest commit
* State your OS and OS version
* When reporting a problem with a specific PDF input file please avoid stating the organization responsible for the PDFWriter - just refer to the *PDFWriter*

### raw file
[jp.pdf](https://github.com/user-attachments/files/17746303/jp.pdf)
### This PDF cannot directly read image files
```
$ pdfcpu images list jp.pdf
pages: all

jp.pdf:
0 images available
```

### If you use a PDF editor to save again or export the PDF directly, the image can be read normally
```
$ pdfcpu extract -mode page jp.pdf .
extracting pages from jp.pdf into ./ ...

validating URIs..

optimizing...
writing jp_page_1.pdf...

$ pdfcpu images list jp_page_1.pdf
pages: all

jp_page_1.pdf:
3 images available (11 KB)
Page Obj# │ Id │ Type  SoftMask ImgMask │ Width │ Height │ ColorSpace Comp bpc Interp │ Size │ Filters
━━━━━━━━━━┿━━━━┿━━━━━━━━━━━━━━━━━━━━━━━━┿━━━━━━━┿━━━━━━━━┿━━━━━━━━━━━━━━━━━━━━━━━━━━━━┿━━━━━━┿━━━━━━━━━━
   1   28 │ X1 │ image                  │    74 │     74 │  DeviceRGB    3   8        │ 3 KB │ DCTDecode
       29 │ X2 │ image                  │    30 │     30 │  DeviceRGB    3   8        │ 2 KB │ DCTDecode
       30 │ X3 │ image    *             │   354 │    236 │  DeviceRGB    3   8        │ 5 KB │ DCTDecode
```

os：window10
version: pdfcpu_0.9.1_Windows_x86_64

**Comment by hhrutter** [comment]
Thanks for reporting this!

**Comment by hhrutter** [comment]
Please use the latest commit!

**Comment by lonevle** [comment]
Thank you very much. I have tried the latest version and have not encountered this issue.

pdfcpu version
pdfcpu: v0.9.1 dev
commit: c4f314bc (2024-11-17T17:13:19Z)
base  : go1.22.5
