### ISSUE TITLE
Slow parsing for objects with huge entries in dictionaries

### ISSUE THREAD

**Issue by fancycode** [pdfcpu/pdfcpu#997]
### Thank you for submitting a possible bug!

Please ensure the following:

* Your issue is based on the latest commit
Yes (c4f314bcfb19ecde85b91e846a84ac0c3b9fcc80)

* State your OS and OS version
Ubuntu 22.04

* When reporting a problem with a specific PDF input file please avoid stating the organization responsible for the PDFWriter - just refer to the *PDFWriter*

We saw a file on one of our servers that contained multiple objects consisting of a single dictionary that had an entry with a value of about 10 MBytes of hex-encoded binary data, i.e.
```
123 0 obj
<<
  /Contents <very-long-hex-encoded-data>
  ...other-entries...
>>
endobj
```

Unfortunately I can't share this file. Parsing this file takes ages (cancelled after a couple of minutes), most likely due to `buffer` reading data incrementally and then searches for `stream` / `endobj` in the buffer:
https://github.com/pdfcpu/pdfcpu/blob/c4f314bcfb19ecde85b91e846a84ac0c3b9fcc80/pkg/pdfcpu/read.go#L1708

I'm working on a fix but already adding as issue for discussion.

**Comment by hhrutter** [comment]
Another corner case. Nice! 
Already curious but I'd need to test this somehow.
